"""Render the Apache content-negotiation include for the GMEOW namespace.

The output is a **vhost-body include**: the deploying site ``Include``s it from
inside the ``<VirtualHost>`` that serves the canonical IRI, replacing any
hand-maintained copy of these rules (Principle 4 — the publication contract is
generated, never duplicated). It carries the complete ``/gmeow`` contract:

* Accept-header 303s for the four canonical serializations (W3C *Best
  Practice Recipes* slash-namespace pattern); browsers fall through to the
  ``/gmeow/`` directory index.
* Slice-IRI dereferencing (#329): every term's ``rdfs:isDefinedBy`` points at
  its owning slice, so ``…/gmeow/slices/<name>`` must resolve.
* Profile-IRI dereferencing (#330): ``…/gmeow/full`` and
  ``…/gmeow/profiles/<name>`` are generated aggregation ontologies.
* A permanent ``modules/* -> slices/*`` redirect: pre-slice releases published
  module IRIs in ``isDefinedBy`` values, and released data keeps working.
* Per-term dereferencing into the pyLODE reference anchors.
* RDF media types, CORS, and the conneg cache semantics (``Vary: Accept`` on
  the negotiated endpoint only).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from gmeow_tools.config import APACHE_CONF, ONTOLOGY_IRI, PROJECT_ROOT
from gmeow_tools.generator import Generator, register, write_text

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

_VERSIONED_GTS_RE = (
    r"^/(?:gmeow|packages)(?:/.*)?/"
    r"(?:[0-9]+(?:\.[0-9]+)*/|(?:[0-9]{4}-[0-9]{2}-[0-9]{2})/)"
    r"[^/]+\.gts$"
)

_TEMPLATE = """\
# GMEOW content-negotiation include (generated by gmeow_tools.apache).
# Include this from the <VirtualHost> body of the site serving {ontology} —
# it is the COMPLETE /gmeow publication contract; do not duplicate these
# rules in the vhost.

<IfModule mod_rewrite.c>
    RewriteEngine On

    # --- /gmeow — the negotiated ontology IRI ------------------------------
    # Accept-header routing per the W3C Best Practice Recipes for Publishing
    # RDF Vocabularies. Browsers (text/html) fall through to the /gmeow/
    # directory index — the human landing page.
    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/x-turtle
    RewriteRule ^/?gmeow/?$ /gmeow.ttl [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml
    RewriteRule ^/?gmeow/?$ /gmeow.rdf [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/n-triples
    RewriteRule ^/?gmeow/?$ /gmeow.nt [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/?gmeow/?$ /gmeow.jsonld [R=303,L]

    # --- Slice IRIs (#329) --------------------------------------------------
    # Every term's rdfs:isDefinedBy points at its owning slice. RDF requests
    # get the canonical serialization; HTML lands on the ontology page
    # (upgrade target: per-slice guides when #325 publishes them).
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/?gmeow/slices/([a-z][a-z0-9-]*)$ /gmeow.ttl [R=303,L]
    RewriteRule ^/?gmeow/slices/([a-z][a-z0-9-]*)$ /gmeow/ [R=303,L]

    # --- Profile IRIs (#330) ------------------------------------------------
    # The root IRI is the core profile; <…/gmeow/full> and
    # <…/gmeow/profiles/<name>> are generated owl:imports aggregations. RDF
    # requests get the canonical serialization; HTML falls through to the
    # human landing page (a profile-aware page is the subject of #325).
    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/x-turtle
    RewriteRule ^/?gmeow/full$ /gmeow/full.ttl [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml
    RewriteRule ^/?gmeow/full$ /gmeow/full.rdf [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/n-triples
    RewriteRule ^/?gmeow/full$ /gmeow/full.nt [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/?gmeow/full$ /gmeow/full.jsonld [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/x-turtle
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.ttl [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.rdf [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/n-triples
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.nt [R=303,L]

    RewriteCond %{{HTTP_ACCEPT}} !text/html
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.jsonld [R=303,L]

    # --- Legacy module IRIs -------------------------------------------------
    # Pre-slice releases published .../gmeow/modules/<name> in isDefinedBy
    # values; released data is immutable (Principle 6), so those IRIs keep
    # dereferencing forever via a permanent redirect to the slice IRI.
    RewriteRule ^/?gmeow/modules/([a-z][a-z0-9-]*)$ /gmeow/slices/$1 [R=301,L]

    # --- Per-term dereferencing ---------------------------------------------
    # A bare term IRI (slash namespace, no extension) resolves to its anchor
    # in the pyLODE reference.
    RewriteRule ^/?gmeow/([A-Za-z][A-Za-z0-9_]*)$ \\
        /gmeow/reference.html#$1 [R=303,L,NE]
</IfModule>

# --- RDF media types ---------------------------------------------------------
# .ttl/.rdf/.nt/.jsonld are not globally typed, so scope them to /gmeow.
<LocationMatch "^/gmeow(\\.ttl|/.+\\.ttl)$">
    Header always set Content-Type "text/turtle; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\\.rdf|/.+\\.rdf)$">
    Header always set Content-Type "application/rdf+xml; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\\.nt|/.+\\.nt)$">
    Header always set Content-Type "application/n-triples; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\\.jsonld|/.+\\.jsonld|/context\\.jsonld)$">
    Header always set Content-Type "application/ld+json; charset=utf-8"
</LocationMatch>

# --- CORS ----------------------------------------------------------------------
# A public vocabulary is expected to be cross-origin readable.
<LocationMatch "^/gmeow($|[./])">
    Header always set Access-Control-Allow-Origin "*"
</LocationMatch>

# --- GTS package serving (§16) -------------------------------------------------
# .gts files are CBOR Sequence packages with byte-accurate content hashes.
<FilesMatch "\\.gts$">
    Header always set Content-Type "application/vnd.blackcat.gts+cbor"
    Header always set Accept-Ranges "bytes"
    Header always set Access-Control-Allow-Origin "*"
</FilesMatch>

# Versioned releases (e.g. /gmeow/1.2.3/gmeow.gts or
# /packages/music/2026-06-11/music.gts) are immutable for one year.
# The ETag SHOULD be the hex of the file's last segment head id (§16.3);
# if the deployment cannot compute it, Apache's default file ETag is acceptable
# because the URL itself names one exact byte sequence.
<LocationMatch "{versioned_gts_re}">
    Header always set Cache-Control "public, max-age=31536000, immutable"
</LocationMatch>

# latest / conneg aliases may change; do not let a shared cache pin one variant.
<LocationMatch "^/(?:gmeow|packages)(?:/.*)?/latest/[^/]+\\.gts$">
    Header always set Cache-Control "private, no-store"
    Header always set Vary "Accept"
</LocationMatch>

# --- Conneg cache semantics ------------------------------------------------------
# Every endpoint whose 303-target depends on the Accept header must Vary and
# must not be cached as a single variant, or a shared cache (Cloudflare) pins
# one serialization for every client. That is the bare /gmeow, the slice
# IRIs (#329), and the profile IRIs (#330) — all negotiate. The
# serializations themselves, the per-term redirects, and the legacy 301s
# (one URL -> one target) stay cacheable.
<LocationMatch "^/gmeow(/?$|/(slices|profiles)/[a-z][a-z0-9-]*$|/full$)">
    Header always set Vary "Accept"
    Header always set Cache-Control "private, no-store"
</LocationMatch>
"""


def render_conf() -> str:
    """Return the Apache content-negotiation include as a string."""
    return _TEMPLATE.format(ontology=ONTOLOGY_IRI, versioned_gts_re=_VERSIONED_GTS_RE)


# --------------------------------------------------------------------------- #
# Registered generator
# --------------------------------------------------------------------------- #


@register
class ApacheGenerator(Generator):
    """Render the Apache content-negotiation include."""

    name: str = "apache"

    @property
    def inputs(self) -> Sequence[Path]:
        """Canonical inputs: this module itself — the template lives here.

        (The previous input, ``config.py``, missed template edits entirely:
        a freshness bug of the class the #287 audit kept finding.)
        """
        return [PROJECT_ROOT / "src" / "gmeow_tools" / "apache.py"]

    @property
    def outputs(self) -> Sequence[Path]:
        """Committed outputs for the Apache generator."""
        return [APACHE_CONF]

    def render(self, staging: Path) -> None:
        """Render the Apache content-negotiation include."""
        path = staging / APACHE_CONF.relative_to(PROJECT_ROOT)
        write_text(
            path,
            render_conf(),
            name=self.name,
            source_hash=getattr(self, "_source_hash", ""),
        )
