"""Render the Apache content-negotiation include for the GMEOW namespace.

The output is an includable ``<Location>`` block (not a standalone ``.htaccess``)
so it composes with the site's existing site-wide negotiation. It implements the
W3C *Best Practice Recipes* slash-namespace pattern: Accept-header routing to
Turtle / RDF-XML / JSON-LD with an HTML fallback, plus CORS and correct media
types.
"""

from __future__ import annotations

from pathlib import Path

from gmeow_tools.config import APACHE_CONF, ONTOLOGY_IRI

_TEMPLATE = """\
# GMEOW content-negotiation include (generated by gmeow_tools.apache).
# Include this from the blackcatinformatics.ca vhost. Slash-namespace,
# Accept-header negotiation per the W3C Best Practice Recipes for Publishing
# RDF Vocabularies. Assumes the serializations live alongside the docs:
#   {ontology}.ttl  .rdf  .nt  .jsonld   and index.html (WIDOCO/pyLODE).

<Location "/gmeow">
    # Cross-origin reads are expected for a public vocabulary.
    Header set Access-Control-Allow-Origin "*"

    AddType text/turtle .ttl
    AddType application/rdf+xml .rdf
    AddType application/n-triples .nt
    AddType application/ld+json .jsonld

    RewriteEngine On

    # Turtle
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/x-turtle
    RewriteRule ^/gmeow/?$ /gmeow.ttl [R=303,L]

    # RDF/XML
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml
    RewriteRule ^/gmeow/?$ /gmeow.rdf [R=303,L]

    # N-Triples
    RewriteCond %{{HTTP_ACCEPT}} application/n-triples
    RewriteRule ^/gmeow/?$ /gmeow.nt [R=303,L]

    # JSON-LD
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/gmeow/?$ /gmeow.jsonld [R=303,L]

    # Default: human-readable documentation.
    RewriteRule ^/gmeow/?$ /gmeow/index.html [R=303,L]

    # Per-term dereferencing (slash namespace): a term URI resolves to the
    # documentation anchor for that term.
    RewriteCond %{{HTTP_ACCEPT}} !text/turtle
    RewriteCond %{{HTTP_ACCEPT}} !application/rdf\\+xml
    RewriteCond %{{HTTP_ACCEPT}} !application/ld\\+json
    RewriteRule ^/gmeow/([A-Za-z][A-Za-z0-9_]*)$ /gmeow/index.html#$1 [R=303,L,NE]
</Location>
"""


def render_conf() -> str:
    """Return the Apache content-negotiation include as a string."""
    return _TEMPLATE.format(ontology=ONTOLOGY_IRI)


def write_conf(path: Path = APACHE_CONF) -> Path:
    """Write the Apache include to ``apache/gmeow.conf``.

    Args:
        path: Destination path.

    Returns:
        The path written.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_conf(), encoding="utf-8")
    return path
