"""Render the Apache content-negotiation include for the GMEOW namespace.

The output is an includable ``<Location>`` block (not a standalone ``.htaccess``)
so it composes with the site's existing site-wide negotiation. It implements the
W3C *Best Practice Recipes* slash-namespace pattern: Accept-header routing to
Turtle / RDF-XML / JSON-LD with an HTML fallback, plus CORS and correct media
types.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from gmeow_tools.config import APACHE_CONF, ONTOLOGY_IRI, PROJECT_ROOT
from gmeow_tools.generator import Generator, register, write_text

_TEMPLATE = """\
# GMEOW content-negotiation include (generated by gmeow_tools.apache).
# Include this from the blackcatinformatics.ca vhost. Slash-namespace,
# Accept-header negotiation per the W3C Best Practice Recipes for Publishing
# RDF Vocabularies. Assumes the serializations live alongside the docs:
#   {ontology}.ttl  .rdf  .nt  .jsonld   and index.html (WIDOCO/pyLODE).

<Location "/gmeow">
    # Cross-origin reads are expected for a public vocabulary.
    Header set Access-Control-Allow-Origin "*"

    AddType text/turtle .ttl
    AddType application/rdf+xml .rdf
    AddType application/n-triples .nt
    AddType application/ld+json .jsonld

    RewriteEngine On

    # Turtle
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/x-turtle
    RewriteRule ^/gmeow/?$ /gmeow.ttl [R=303,L]

    # RDF/XML
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml
    RewriteRule ^/gmeow/?$ /gmeow.rdf [R=303,L]

    # N-Triples
    RewriteCond %{{HTTP_ACCEPT}} application/n-triples
    RewriteRule ^/gmeow/?$ /gmeow.nt [R=303,L]

    # JSON-LD
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/gmeow/?$ /gmeow.jsonld [R=303,L]

    # Default: human-readable documentation.
    RewriteRule ^/gmeow/?$ /gmeow/index.html [R=303,L]

    # Slice IRIs (#329): every term's rdfs:isDefinedBy points at its owning
    # slice — the IRI must dereference. Until per-slice guides publish (#325),
    # land on the module-status anchor of the landing page; RDF requests get
    # the canonical serialization.
    RewriteCond %{{HTTP_ACCEPT}} text/turtle [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/rdf\\+xml [OR]
    RewriteCond %{{HTTP_ACCEPT}} application/ld\\+json
    RewriteRule ^/gmeow/slices/([a-z][a-z0-9-]*)$ /gmeow.ttl [R=303,L]
    RewriteRule ^/gmeow/slices/([a-z][a-z0-9-]*)$ \
        /gmeow/index.html#slice-$1 [R=303,L,NE]

    # Per-term dereferencing (slash namespace): a term URI resolves to the
    # documentation anchor for that term.
    RewriteCond %{{HTTP_ACCEPT}} !text/turtle
    RewriteCond %{{HTTP_ACCEPT}} !application/rdf\\+xml
    RewriteCond %{{HTTP_ACCEPT}} !application/ld\\+json
    RewriteRule ^/gmeow/([A-Za-z][A-Za-z0-9_]*)$ /gmeow/index.html#$1 [R=303,L,NE]
</Location>
"""


def render_conf() -> str:
    """Return the Apache content-negotiation include as a string."""
    return _TEMPLATE.format(ontology=ONTOLOGY_IRI)


# --------------------------------------------------------------------------- #
# Registered generator
# --------------------------------------------------------------------------- #


@register
class ApacheGenerator(Generator):
    """Render the Apache content-negotiation include."""

    name: str = "apache"

    @property
    def inputs(self) -> Sequence[Path]:
        """Canonical inputs for the Apache generator."""
        return [PROJECT_ROOT / "src" / "gmeow_tools" / "config.py"]

    @property
    def outputs(self) -> Sequence[Path]:
        """Committed outputs for the Apache generator."""
        return [APACHE_CONF]

    def render(self, staging: Path) -> None:
        """Render the Apache content-negotiation include."""
        path = staging / APACHE_CONF.relative_to(PROJECT_ROOT)
        write_text(
            path,
            render_conf(),
            name=self.name,
            source_hash=getattr(self, "_source_hash", ""),
        )
