# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: AGPL-3.0-only

"""The ``frame-shapes`` generator: Principle 11 by annotation (#283).

"A value asserted without its frame is ill-formed" used to be enforced by
hand-written SHACL — one shape per frame-carrying class, added when someone
remembered. Now the modules DECLARE the requirement (``gmeow:requiresFrame``
on the carrier class) and this generator derives the shape:

* cardinality from the frame property's character — ``owl:FunctionalProperty``
  means exactly one, otherwise at least one — overridable per carrier with
  ``gmeow:frameCardinality "exactly-one"``;
* severity ``sh:Violation``, downgradable with
  ``gmeow:frameRequirementSeverity "warning"`` while a corpus is brought up
  to frame completeness.

A new frame-relative class is enforced the moment it is declared — never by
remembering to write its shape. The companion lint
(:func:`gmeow_tools.reasoning_lint.frame_declaration_completeness`) closes
the loop from the other side: a frame-pointing property whose domain class
carries no declaration is flagged.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from rdflib import RDF, URIRef
from rdflib.namespace import OWL

from gmeow_tools.config import (
    FRAME_SHAPES_FILE,
    GENERATED_SHAPES_DIR,
    NAMESPACE,
    ONTOLOGY_FILE,
    PROJECT_ROOT,
)
from gmeow_tools.generator import Generator, register
from gmeow_tools.graph import load_merged_graph
from gmeow_tools.slices import iter_slice_module_files

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

    from rdflib import Graph

_HEADER = """\
# GENERATED by `gmeow regenerate` (frame-shapes) from gmeow:requiresFrame
# declarations in the slice modules — DO NOT EDIT (#283, CONSTITUTION P11).
@prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
"""


def frame_requirements(graph: Graph) -> list[tuple[str, str, bool, str]]:
    """Every ``gmeow:requiresFrame`` declaration, resolved and sorted.

    Returns ``(carrier local, frame-property local, exactly_one, severity)``
    per declaration.
    """
    requires = URIRef(NAMESPACE + "requiresFrame")
    cardinality = URIRef(NAMESPACE + "frameCardinality")
    severity_prop = URIRef(NAMESPACE + "frameRequirementSeverity")
    rows: list[tuple[str, str, bool, str]] = []
    for carrier, frame_prop in sorted(graph.subject_objects(requires)):
        if not isinstance(carrier, URIRef) or not isinstance(frame_prop, URIRef):
            continue
        override = graph.value(carrier, cardinality)
        if override is not None:
            exactly_one = str(override) == "exactly-one"
        else:
            exactly_one = (frame_prop, RDF.type, OWL.FunctionalProperty) in graph
        severity = str(graph.value(carrier, severity_prop) or "violation")
        rows.append(
            (
                str(carrier).removeprefix(NAMESPACE),
                str(frame_prop).removeprefix(NAMESPACE),
                exactly_one,
                severity,
            )
        )
    return rows


def render_frame_shapes(graph: Graph | None = None) -> str:
    """Render the generated frame-relativity shapes document."""
    if graph is None:
        graph = load_merged_graph(include_imports=False)
    blocks: list[str] = [_HEADER]
    for carrier, prop, exactly_one, severity in frame_requirements(graph):
        sh_severity = "sh:Warning" if severity == "warning" else "sh:Violation"
        count = "exactly one" if exactly_one else "at least one"
        lines = [
            f"gmeow:{carrier}FrameRequirementShape",
            "    a sh:NodeShape ;",
            f'    rdfs:label "{carrier} frame-relativity shape (generated)"@en ;',
            f"    sh:targetClass gmeow:{carrier} ;",
            "    sh:property [",
            f"        sh:path gmeow:{prop} ;",
            "        sh:minCount 1 ;",
        ]
        if exactly_one:
            lines.append("        sh:maxCount 1 ;")
        # Deliberately no sh:class: the frame property's rdfs:range already
        # types the object for the REASONER (the open-world discipline), and
        # SHACL sh:class over fixture-only data graphs — where the ontology's
        # frame individuals carry no type triples — would reject valid data.
        lines.append("        sh:nodeKind sh:IRI ;")
        lines.extend(
            [
                f"        sh:severity {sh_severity} ;",
                f'        sh:message "A {carrier} must carry {count} '
                f"reference frame (gmeow:{prop}) — a value asserted without "
                f'its frame is ill-formed (CONSTITUTION P11)." ;',
                "    ] .",
            ]
        )
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


@register
class FrameShapesGenerator(Generator):
    """Emit frame-relativity SHACL from gmeow:requiresFrame declarations."""

    name: str = "frame-shapes"

    @property
    def inputs(self) -> Sequence[Path]:
        """The declarations live in the root ontology + slice modules."""
        return [ONTOLOGY_FILE, *iter_slice_module_files()]

    @property
    def outputs(self) -> Sequence[Path]:
        """One generated shapes document."""
        return [FRAME_SHAPES_FILE]

    def render(self, staging: Path) -> None:
        """Render the shapes document into the staging tree."""
        target_dir = staging / GENERATED_SHAPES_DIR.relative_to(PROJECT_ROOT)
        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / FRAME_SHAPES_FILE.name).write_text(
            render_frame_shapes(), encoding="utf-8"
        )
