# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: AGPL-3.0-only
"""Render-helper library for GMEOW artifact producers (the surviving seam).

The Python build *orchestrator* (the old ``generator.py`` registry, ``run`` /
``regenerate`` / ``check_all`` / topological scheduler / stamp cache) was retired
in #861 P7: the build authority is now the Rust ``gmeow-pipeline`` executor
(``gmeow_native.pipeline.run_pipeline``), which reads the dogfooded build DAG in
``slices/core/pipeline/`` and reproduces every committed artifact single-pass.

What survives here are the *pure render helpers* the lane-only schema compiler
and the remaining library halves of the former render modules still call:

- the :class:`Generator` shape (a structural base the lane-only ``schemas``
  compiler subclasses) — no registry, no decorator;
- the ``GENERATED … DO NOT EDIT`` banner writers (:func:`write_text`,
  :func:`write_turtle`);
- the deterministic input :func:`source_hash` (banner provenance);
- the RDF graph-isomorphism comparator (:func:`rdf_compare`) and the small
  path helpers (:func:`_rel`, :func:`_staging_rel`) those library halves reuse.

There is intentionally NO ``register`` / ``registry`` here: nothing in the build
is keyed on a Python registry any more.
"""

from __future__ import annotations

import hashlib
import logging
from collections.abc import Sequence
from pathlib import Path
from typing import Protocol, runtime_checkable

from gmeow_rdf.compat.rdflib import Graph

from gmeow_tools.config import PROJECT_ROOT
from gmeow_tools.rdf_canonical import graphs_isomorphic

__all__ = [
    "Generator",
    "GeneratorError",
    "_rel",
    "_staging_rel",
    "rdf_compare",
    "source_hash",
    "write_text",
    "write_turtle",
]


class GeneratorError(RuntimeError):
    """A render helper produced invalid output (e.g. internal-tag leakage)."""


@runtime_checkable
class Generator(Protocol):
    """Structural shape for a render helper.

    Retained so the lane-only ``schemas`` compiler (driven as a subprocess by the
    Rust ``stage-export-schemas`` leaf) keeps a stable base. It declares canonical
    *inputs* and committed *outputs* and a :meth:`render` into a staging tree.
    """

    name: str
    is_directory_output: bool = False
    allows_internal_tags: bool = False

    @property
    def inputs(self) -> Sequence[Path]:
        """Canonical inputs that determine the source hash."""
        ...

    @property
    def outputs(self) -> Sequence[Path]:
        """Committed artifact paths produced by this helper."""
        ...

    def render(self, staging: Path) -> None:
        """Render all artifacts into *staging* (absolute paths mirroring repo root)."""
        ...


def _rel(path: Path) -> str:
    """Repo-relative string for *path*, or the absolute string if outside the root."""
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def _staging_rel(path: Path) -> Path:
    """Map a committed output path to its location inside a staging tree.

    If *path* is under :data:`PROJECT_ROOT`, return the subpath. Otherwise fall
    back to the final component so callers that stage to temp paths outside the
    repo still work.
    """
    if path.is_relative_to(PROJECT_ROOT):
        return path.relative_to(PROJECT_ROOT)
    return Path(path.name)


def source_hash(inputs: Sequence[Path]) -> str:
    """Compute a deterministic content hash of *inputs*.

    The hash is independent of mtime (so it is stable across ``git clone``) and
    depends on the relative path, file size, and full content of every input.
    """
    h = hashlib.sha256()
    root = PROJECT_ROOT.resolve()
    for inp in sorted(p.resolve() for p in inputs):
        if not inp.exists():
            logging.warning("render input missing: %s", inp)
            continue
        rel = str(inp.relative_to(root)) if inp.is_relative_to(root) else str(inp)
        h.update(rel.encode("utf-8"))
        h.update(str(inp.stat().st_size).encode("utf-8"))
        h.update(inp.read_bytes())
    return h.hexdigest()[:16]


_GENERATED_BANNER = (
    "# GENERATED by gmeow {name} — DO NOT EDIT.\n"
    "# https://github.com/Blackcat-Informatics/gmeow-ontology\n"
    "\n"
)


def write_text(
    path: Path,
    content: str,
    *,
    name: str = "",
    source_hash: str = "",
) -> None:
    """Write a text file, optionally prepending the generated banner.

    The banner uses ``#`` line comments, suitable for Turtle, SPARQL, YAML,
    Python, TypeScript, shell scripts, etc. ``source_hash`` is accepted for
    backward compatibility but is not embedded in generated artifacts.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if name:
        banner = _GENERATED_BANNER.format(name=name)
        content = banner + content
    path.write_text(content, encoding="utf-8")


def write_turtle(
    path: Path,
    graph: Graph,
    *,
    name: str = "",
    source_hash: str = "",
    tag_map: dict[str, str] | None = None,
) -> None:
    """Serialize an rdflib :class:`Graph` as Turtle with the generated banner.

    Internal ``x-gmeow-*`` language tags are retagged to public BCP-47 at this
    boundary (#287): registry artifacts are consumer-facing projections.
    ``tag_map`` lets fold-sealed callers supply the mapping explicitly — the
    default falls back to loading the merged graph, a canonical-source read the
    narrow-waist exporters must not trigger.
    """
    from gmeow_tools.language_tags import retag_graph

    path.parent.mkdir(parents=True, exist_ok=True)
    turtle = retag_graph(graph, tag_map=tag_map).serialize(format="turtle")
    if name:
        banner = _GENERATED_BANNER.format(name=name)
        turtle = banner + turtle
    path.write_text(turtle, encoding="utf-8")


def rdf_compare(fresh: Path, committed: Path) -> list[str]:
    """Graph-isomorphism comparator for RDF/Turtle files.

    A foreign serialization of an isomorphic graph is itself drift, so a second
    writer for a canonical artifact cannot pass the gates.
    """
    rel = _rel(committed)
    if not committed.exists():
        return [f"{rel} (missing committed file)"]
    if not fresh.exists():
        return [f"{rel} (not produced in staging)"]
    try:
        a = Graph().parse(fresh, format="turtle")
        b = Graph().parse(committed, format="turtle")
    except Exception as exc:
        return [f"{rel} (parse error: {exc})"]
    if not graphs_isomorphic(a, b):
        return [f"{rel}"]
    return []
