"""Compile the GMEOW mapping DSL into the four standard alignment artifacts.

``gmeow-dev regenerate mappings`` renders, from the single authoring source in
``mapping-dsl/``:

* ``mappings/*.sssom.tsv`` — SSSOM 1:1 term-equivalence rows;
* ``projections/*.edoal.ttl`` — EDOAL complex-alignment cells (with ``edoal:measure``);
* ``projections/functions.fno.ttl`` — the FnO transform catalog, its parameter
  ``fno:type`` DERIVED from each predicate's ontology ``rdfs:range`` (so the
  type-mismatch bug class is structurally impossible);
* ``queries/projections/*.rq`` — the executable SPARQL CONSTRUCT branches.

Before writing anything, the compiler renders the artifacts to a temporary tree
and runs the three :mod:`gmeow_tools.projection_lint` cross-layer invariants on
them; a violation aborts the compile (it can never reach disk). ``--check``
renders to a temp tree and diffs it against the committed files (RDF by graph
isomorphism, TSV/SPARQL by bytes), reporting any drift without writing.
"""

from __future__ import annotations

import concurrent.futures
import json
import os
import re
import shutil
from collections.abc import Sequence
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

import gmeow_rdf
import gmeow_slice
from gmeow_rdf.compat.rdflib import RDF, RDFS, SKOS, BNode, Graph, Literal, URIRef
from gmeow_rdf.compat.rdflib.collection import Collection
from gmeow_rdf.compat.rdflib.namespace import Namespace
from gmeow_rdf.compat.rdflib.term import Node

from gmeow_tools import diagnostics
from gmeow_tools.config import (
    MAPPING_DSL_DIR,
    MAPPINGS_DIR,
    ONTOLOGY_IRI,
    PREFIXES,
    PROJECT_ROOT,
    PROJECTION_QUERY_DIR,
    PROJECTIONS_DIR,
)
from gmeow_tools.graph import bind_prefixes, load_merged_graph
from gmeow_tools.language_tags import retag_graph
from gmeow_tools.mapping_dsl import (
    Atom,
    CompileError,
    Dsl,
    MappingPattern,
    OptionalGroup,
    ProfileBinding,
    ProjectionCell,
    curie,
    load_dsl,
    render_expr,
    sparql_string,
)
from gmeow_tools.projection_lint import (
    fno_reference_integrity,
    fno_type_mismatches,
    projection_spec_drift,
)

GM = Namespace(PREFIXES["gmeow"])
ALIGN = Namespace(PREFIXES["align"])
EDOAL = Namespace(PREFIXES["edoal"])
DCTERMS = Namespace(PREFIXES["dcterms"])

#: The projection profiles and the FnO catalog file name.
_PROFILES = (
    "schema-org",
    "vcard",
    "foaf",
    "geosparql",
    "qb",
    "ical",
    # Calendar / scheduling slice (#62)
    "jcal",
    "schema-org-schedule",
    "owl-time",
    "odrl",
    "cc",
    "dcterms",
    "oai_dc",
    "spdx",
    "ontolex",
    "web-annotation",
    "skos",
    "activitystreams",
    "markdown",
    "bot",
    "sosa",
    "crmarchaeo",
    "ivoa",
    "iptc",
    "loinc",
    "slsa",
    "intoto",
    "sigstore",
    "mailmap",
    # Image super-ontology (#22)
    "iiif",
    "exif",
    "doap",
    "codemeta",
    "resume",
    # Research-object / catalog packaging (#58)
    "dcat",
    # Transpiler coverage, #34 phases 2-3
    "org",
    "bibo",
    "bibframe",
    "gedcom",
    "sioc",
    # Build provenance — the PROV qualification pattern (#415, #34 verdict 8)
    "prov",
    # Notation/music projection layer (#318)
    "lrmoo",
    "mo",
    "pon",
    "jams",
)
_FNO_FILE = "functions.fno.ttl"
#: Hand-authored FnO file the compiler reads (for the lint) but never writes.
_TRANSFORMS_FILE = "transforms.fno.ttl"

_GENERATED_BANNER = (
    "GENERATED by `gmeow regenerate` (mappings) from mapping-dsl/ — DO NOT EDIT."
)

#: Per-profile rendering state for the process pool (set by initializer).
_PROFILE_DSL: Dsl | None = None
_PROFILE_VOCAB: SuppressionVocab | None = None


def _init_profile_worker(dsl: Dsl, vocab: SuppressionVocab) -> None:
    """Process-pool initializer: cache DSL/vocab in worker globals."""
    global _PROFILE_DSL, _PROFILE_VOCAB
    _PROFILE_DSL = dsl
    _PROFILE_VOCAB = vocab


def _emit_profile_pair(profile: str) -> tuple[str, Graph, str]:
    """Emit the EDOAL graph and SPARQL query for one profile.

    Must be a top-level picklable function so it can run in a process pool.
    """
    assert _PROFILE_DSL is not None and _PROFILE_VOCAB is not None
    edoal_graph = emit_edoal(_PROFILE_DSL, profile)
    sparql_text = emit_sparql(_PROFILE_DSL, profile, _PROFILE_VOCAB)
    return profile, edoal_graph, sparql_text


# --------------------------------------------------------------------------- #
# FnO emitter
# --------------------------------------------------------------------------- #


def _local(iri: URIRef) -> str:
    """The local name of an IRI (after the last ``#`` or ``/``)."""
    text = str(iri)
    cut = max(text.rfind("#"), text.rfind("/"))
    return text[cut + 1 :] if cut >= 0 else text


def emit_fno(dsl: Dsl, onto: Graph) -> Graph:
    """Render the FnO function catalog (param fno:type derived from rdfs:range).

    FnO emission is now wholly native (#848): the entire emitter lives in the Rust
    slice framework (``gmeow_slice.emit_fno`` → ``crates/slice/src/fno_emit.rs``),
    which sources every input from the repo itself — the projection functions +
    cells from the slice ``mappings/*.ttl`` artifacts and the shared
    ``dsl/mappings/`` tree, and each input predicate's ``rdfs:range`` from
    ``ontology/gmeow.ttl`` + the slice ``module.ttl`` artifacts (the
    ``load_merged_graph`` source set). Python passes only the repo root; the ``dsl``
    and ``onto`` arguments are accepted for call-site compatibility but are no
    longer read (the native emitter rediscovers the same sources). The fail-closed
    ``fno:type`` guard (an input predicate with no ontology range is a hard error)
    is reproduced natively.

    The native emitter returns the FnO graph as full-IRI N-Triples; this wrapper
    re-parses it into a fresh rdflib :class:`Graph` (so the downstream
    ``projection_lint`` reads + the Turtle writer are unchanged) and binds the
    canonical prefixes as the old code did. The result is graph-isomorphic to the
    historical Python emitter.
    """
    del dsl, onto  # Sourced natively from PROJECT_ROOT; see the docstring.
    ntriples = gmeow_slice.emit_fno(str(PROJECT_ROOT))
    graph = Graph()
    graph.parse(data=ntriples, format="nt")
    bind_prefixes(graph)
    return graph


def _stable_bnode(label: str) -> BNode:
    """A blank node with a deterministic, meaningful id.

    Issue #36: rdflib's Turtle serializer orders blank nodes by their id, and a
    default ``BNode()`` id carries a per-process random component — so the emitted
    cell/mapping order (hence the committed artifact) varied run to run. Minting the
    id from the node's own content makes it stable across processes *and*
    self-documenting, while keeping EDOAL's anonymous-cell convention (the id drives
    ordering; the node still serializes inline as ``[ … ]`` with its ``rdfs:label``).
    """
    safe = "".join(c if c.isalnum() else "_" for c in label)
    return BNode(f"n_{safe}")


def _attach_list(
    graph: Graph, subject: Node, predicate: URIRef, items: Sequence[Node]
) -> None:
    """Attach an rdf:List of items to subject via predicate."""
    head = BNode()
    Collection(graph, head, list(items))
    graph.add((subject, predicate, head))


# --------------------------------------------------------------------------- #
# EDOAL emitter
# --------------------------------------------------------------------------- #

_EDOAL_KIND = {
    "class": EDOAL.Class,
    "relation": EDOAL.Relation,
    "property": EDOAL.Property,
}


def _edoal_entity(graph: Graph, term: URIRef, kind: str) -> BNode:
    node = BNode()
    graph.add((node, RDF.type, _EDOAL_KIND[kind]))
    graph.add((node, EDOAL.uri, term))
    return node


def _edoal_restriction(
    graph: Graph, source: URIRef, attr: URIRef, value: URIRef
) -> BNode:
    cls = BNode()
    graph.add((cls, RDF.type, EDOAL.Class))
    restriction = BNode()
    graph.add((restriction, RDF.type, EDOAL.AttributeValueRestriction))
    on_attr = BNode()
    graph.add((on_attr, RDF.type, EDOAL.Relation))
    graph.add((on_attr, EDOAL.uri, attr))
    graph.add((restriction, EDOAL.onAttribute, on_attr))
    graph.add((restriction, EDOAL.comparator, EDOAL.equals))
    val = BNode()
    graph.add((val, EDOAL.uri, value))
    graph.add((restriction, EDOAL.value, val))
    base = _edoal_entity(graph, source, "class")
    _attach_list(graph, cls, EDOAL["and"], [base, restriction])
    return cls


def _flatten_atoms(items: tuple[Atom | OptionalGroup, ...]) -> list[Atom]:
    """Flatten a pattern's items (recursing OPTIONAL groups) to bare atoms."""
    out: list[Atom] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.extend(_flatten_atoms(item.items))
        else:
            out.append(item)
    return out


def _nav_edges(pattern: MappingPattern) -> list[tuple[str, str, Atom]]:
    """Navigation edges (subjVar, objVar, atom): atoms relating two variables."""
    edges: list[tuple[str, str, Atom]] = []
    for atom in _flatten_atoms(pattern.atoms):
        has_pred = (
            atom.predicate is not None
            or atom.predicate_var is not None
            or atom.path is not None
            or atom.path_alts
        )
        if atom.object_var is not None and has_pred:
            edges.append((atom.subject_var, atom.object_var, atom))
    return edges


def _find_var_path(
    edges: list[tuple[str, str, Atom]], anchor: str, value: str
) -> list[tuple[Atom, bool]] | None:
    """BFS a simple variable path anchor→value; steps carry a forward/inverse flag."""
    from collections import deque

    adj: dict[str, list[tuple[str, Atom, bool]]] = {}
    for subj, obj, atom in edges:
        adj.setdefault(subj, []).append((obj, atom, True))
        adj.setdefault(obj, []).append((subj, atom, False))
    queue: deque[tuple[str, list[tuple[Atom, bool]]]] = deque([(anchor, [])])
    seen = {anchor}
    while queue:
        node, steps = queue.popleft()
        if node == value:
            return steps
        for nbr, atom, forward in adj.get(node, []):
            if nbr not in seen:
                seen.add(nbr)
                queue.append((nbr, [*steps, (atom, forward)]))
    return None


def _edoal_relation_step(graph: Graph, atom: Atom, forward: bool) -> BNode:
    """Render one navigation step as an EDOAL relation (inverse when backward)."""
    if atom.path_alts:
        if len(atom.path_alts) == 1:
            base = _edoal_entity(graph, atom.path_alts[0], "relation")
        else:
            # An alternation of relations: EDOAL edoal:or over the alternatives
            # (validator-safe; the executor still matches `a|b`).
            base = BNode()
            graph.add((base, RDF.type, EDOAL.Relation))
            _attach_list(
                graph,
                base,
                EDOAL["or"],
                [_edoal_entity(graph, a, "relation") for a in atom.path_alts],
            )
    elif atom.predicate is not None:
        base = _edoal_entity(graph, atom.predicate, "relation")
    else:  # an opaque seq/zero-or-more path — degrade to a commented relation node
        base = BNode()
        graph.add((base, RDF.type, EDOAL.Relation))
        graph.add(
            (base, RDFS.comment, Literal(atom.path or atom.predicate_var or "path"))
        )
    if forward:
        return base
    inverse = BNode()
    graph.add((inverse, RDF.type, EDOAL.Relation))
    graph.add((inverse, EDOAL.inverse, base))
    return inverse


def _edoal_path(graph: Graph, pattern: MappingPattern) -> BNode | None:
    """Derive entity1 as the anchor→value relation path (compose/inverse), or None."""
    if pattern.value is None:
        return None
    steps = _find_var_path(_nav_edges(pattern), pattern.anchor, pattern.value)
    if not steps:
        return None
    relations = [_edoal_relation_step(graph, atom, fwd) for atom, fwd in steps]
    if len(relations) == 1:
        return relations[0]
    compose = BNode()
    graph.add((compose, RDF.type, EDOAL.Relation))
    _attach_list(graph, compose, EDOAL.compose, relations)
    return compose


def emit_edoal(dsl: Dsl, profile: str) -> Graph:
    """Render the EDOAL alignment for one profile."""
    graph = Graph()
    bind_prefixes(graph)
    align = URIRef(f"{ONTOLOGY_IRI}/projections/{profile}")
    graph.add((align, RDF.type, ALIGN.Alignment))
    graph.add(
        (
            align,
            RDFS.label,
            Literal(f"GMEOW → {profile} (EDOAL)", lang="x-gmeow-english"),
        )
    )
    graph.add((align, DCTERMS.isPartOf, URIRef(ONTOLOGY_IRI)))
    graph.add((align, RDFS.comment, Literal(_GENERATED_BANNER, lang="x-gmeow-english")))
    graph.add((align, ALIGN.level, Literal("2EDOAL")))
    for n, name in ((ALIGN.onto1, "GMEOW"), (ALIGN.onto2, profile)):
        onto = BNode()
        graph.add((onto, RDF.type, ALIGN.Ontology))
        formalism = BNode()
        graph.add((formalism, ALIGN.name, Literal(name)))
        graph.add((onto, ALIGN.formalism, formalism))
        graph.add((align, n, onto))

    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for map_cell in _edoal_cells(graph, cell, b):
                graph.add((align, ALIGN.map, map_cell))
    return graph


def _edoal_cells(graph: Graph, cell: ProjectionCell, b: ProfileBinding) -> list[BNode]:
    """Return the EDOAL align:Cell node(s) for one binding (0, 1, or N)."""
    pattern = cell.pattern
    cells: list[BNode] = []

    def _cell(entity1: Node, entity2: Node, label: str, key: str) -> BNode:
        # Deterministic, meaningful blank-node id (issue #36) — keyed on the source
        # projection cell, the profile, and a fan-out key so it is unique and stable.
        node = _stable_bnode(f"cell-{b.profile}-{_local(cell.iri)}-{key}")
        graph.add((node, RDF.type, ALIGN.Cell))
        graph.add((node, RDFS.label, Literal(label, lang="x-gmeow-english")))
        graph.add((node, ALIGN.entity1, entity1))
        graph.add((node, ALIGN.entity2, entity2))
        graph.add((node, ALIGN.relation, Literal(b.relation)))
        if b.transform is not None:
            trans = BNode()
            graph.add((trans, RDFS.seeAlso, b.transform))
            graph.add((node, EDOAL.transformation, trans))
        if b.confidence is not None:
            graph.add((node, EDOAL.measure, Literal(b.confidence)))
        return node

    if b.value_class_map:
        if pattern.edoal_source is None:
            raise CompileError(f"{cell.iri}: value-class map needs edoalSource")
        for i, vc in enumerate(b.value_class_map):
            entity1 = _edoal_restriction(
                graph, pattern.edoal_source, _attr_of(pattern), vc.when_value
            )
            entity2 = _edoal_entity(graph, vc.to_class, "class")
            cells.append(
                _cell(
                    entity1,
                    entity2,
                    f"{curie(pattern.edoal_source)} "
                    f"[{curie(vc.when_value)}] → {curie(vc.to_class)}",
                    key=f"{i}-{_local(vc.to_class)}",
                )
            )
        return cells

    # entity1: a derived relation path (compose/inverse) when opted in; else the
    # authored salient term; else no cell (structural / SSSOM-backed projection).
    target, target_kind = _edoal_target(b)
    if target is None:
        return cells

    source: Node | None
    if pattern.edoal_path:
        source = _edoal_path(graph, pattern)
        if source is None:
            raise CompileError(f"{cell.iri}: edoalPath set but no anchor→value path")
    elif pattern.edoal_source is not None:
        source = _edoal_entity(graph, pattern.edoal_source, pattern.edoal_source_kind)
    else:
        return cells

    target_entity = _edoal_entity(graph, target, target_kind)
    cells.append(
        _cell(source, target_entity, cell.label or f"→ {curie(target)}", key="0")
    )
    return cells


def _attr_of(pattern: MappingPattern) -> URIRef:
    """The value->class restriction attribute (the placeType-style predicate)."""
    for atom in _flatten_atoms(pattern.atoms):
        if atom.object_var == pattern.value and atom.predicate is not None:
            return atom.predicate
    raise CompileError("value-class pattern has no value-binding predicate")


def _edoal_target(b: ProfileBinding) -> tuple[URIRef | None, str]:
    if b.edoal_target is not None:
        return b.edoal_target, b.edoal_target_kind or "class"
    if b.to_class is not None:
        return b.to_class, b.edoal_target_kind or "class"
    if b.to_predicate is not None:
        return b.to_predicate, b.edoal_target_kind or "property"
    return None, "property"


# --------------------------------------------------------------------------- #
# SSSOM emitter (native)
# --------------------------------------------------------------------------- #


def emit_sssom(dsl: Dsl) -> dict[str, str]:
    """Render every SSSOM TSV file from the term-equivalence cells.

    SSSOM emission is now wholly native (#848): the entire emitter lives in the
    Rust slice framework (``gmeow_slice.emit_sssom`` →
    ``crates/slice/src/mapping_emit.rs``), which sources every input from the repo
    itself — the slice ``mappings/*.ttl`` artifacts, the shared ``dsl/mappings/``
    tree, the curated prefix registry, and ``metadata/gmeow-self.ttl`` for the
    version + release date. Python passes only the repo root; the ``dsl`` argument
    is accepted for call-site compatibility but is no longer read (the native
    emitter rediscovers the same sources). The result is byte-identical to the
    historical Python emitter.

    SSSOM rows are owned exclusively by gmeow:TermEquivalence cells (a 1:1 with
    the rows). Each file carries deterministic provenance metadata + a curie_map
    of the prefixes it uses; subject_label/object_label columns appear only when a
    row populates them.
    """
    del dsl  # Sourced natively from PROJECT_ROOT; see the docstring.
    result = gmeow_slice.emit_sssom(str(PROJECT_ROOT))
    return dict(result)


# --------------------------------------------------------------------------- #
# SSSOM validation
# --------------------------------------------------------------------------- #


def _validate_sssom(sssom_texts: dict[str, str]) -> list[str]:
    """Run every generated SSSOM TSV through the native SSSOM validator.

    Validates each text in memory (so the exact bytes that will be written are
    checked) via the Rust ``gmeow_rdf`` kernel — which subsumes the former
    ``sssom`` package (#848) and reads GMEOW's own SSSOM format directly, so no
    header-quoting shim is needed. Returns a flat list of diagnostic strings;
    an empty list means every file passed validation.

    The native validator replicates sssom-py's reachable default checks
    (``PrefixMapCompleteness``, ``JsonSchema``) and adds a strict-superset
    ``RequiredSlot`` check (sssom-py silently dropped malformed rows); parse
    failures surface as a ``FATAL``/``check=parse`` diagnostic.
    """
    problems: list[str] = []
    for rel_path, text in sssom_texts.items():
        # The mappings-dir text artifacts include dsl-stats.json (#3); only the
        # SSSOM TSVs are mapping sets.
        if not rel_path.endswith(".sssom.tsv"):
            continue
        for result in gmeow_rdf.validate_sssom(text):
            if result["severity"] in ("ERROR", "FATAL"):
                node = result["instance"] if result["instance"] is not None else "—"
                problems.append(
                    f"{rel_path}: {result['message']} "
                    f"(type={result['code']}, node={node}, "
                    f"check={result['check']})"
                )
    return problems


# --------------------------------------------------------------------------- #
# SPARQL emitter
# --------------------------------------------------------------------------- #


def _term(atom: Atom, var_map: dict[str, str] | None = None) -> str:
    if atom.object_var is not None:
        obj_var = atom.object_var
        if var_map and obj_var in var_map:
            obj_var = var_map[obj_var]
        return f"?{obj_var}"
    if atom.object_value is not None:
        return curie(atom.object_value)
    if atom.object_literal is not None:
        lit = atom.object_literal
        if lit.datatype == URIRef(PREFIXES["xsd"] + "boolean"):
            return "true" if str(lit).lower() in ("true", "1") else "false"
        return sparql_string(str(lit))
    raise CompileError("atom has no object")


def _atom_triple(atom: Atom, var_map: dict[str, str] | None = None) -> str:
    subj_var = atom.subject_var
    if var_map and subj_var in var_map:
        subj_var = var_map[subj_var]
    subj = f"?{subj_var}"
    if atom.path is not None:
        pred = atom.path
    elif atom.predicate_var is not None:
        pred = f"?{atom.predicate_var}"
    elif atom.predicate == RDF.type and atom.object_value is not None:
        pred = "a"
    elif atom.predicate is not None:
        pred = curie(atom.predicate)
    else:
        raise CompileError(f"atom on ?{atom.subject_var} has no predicate/path")
    return f"{subj} {pred} {_term(atom, var_map)} ."


def _class_var(pattern: MappingPattern) -> str:
    return f"{pattern.value}Class"


def _where_items(
    items: tuple[Atom | OptionalGroup, ...], indent: str = ""
) -> list[str]:
    """Render WHERE items (atoms + nested OPTIONAL groups) at a relative indent."""
    out: list[str] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.append(f"{indent}OPTIONAL {{")
            out.extend(_where_items(item.items, indent + "    "))
            out.append(f"{indent}}}")
        else:
            triple = _atom_triple(item)
            wrapped = f"OPTIONAL {{ {triple} }}" if item.optional else triple
            out.append(f"{indent}{wrapped}")
    return out


@dataclass(frozen=True, slots=True)
class SuppressionVocab:
    """Ontology-derived suppression knowledge for guard injection (#282).

    "Suppression-bearing" is determined from the ontology, never from a
    hand-maintained list: a new appellation subclass or bearer property
    extends the guards on the next regenerate.
    """

    #: Properties whose range is ⊑ gmeow:Appellation — the bearer→appellation
    #: links, used (as an alternation) to guard an appellation whose bearer is
    #: not bound in the branch pattern.
    bearer_props: tuple[URIRef, ...]
    #: Properties whose domain is ⊑ gmeow:Appellation — reading one marks the
    #: subject variable as an appellation.
    appellation_domain_props: frozenset[URIRef]
    #: Classes ⊑ gmeow:Appellation, for explicit ``a gmeow:X`` pattern atoms.
    appellation_classes: frozenset[URIRef]
    #: Properties annotated ``gmeow:coarsenGuarded true`` — reading one means
    #: the subject's precise values must not pass a ``gmeow:coarsenTo`` mark.
    coarsen_guarded: frozenset[URIRef]


def _subclass_closure(graph: Graph, root: URIRef) -> frozenset[URIRef]:
    """``root`` plus every class transitively ``rdfs:subClassOf`` it."""
    closure: set[URIRef] = {root}
    grew = True
    while grew:
        grew = False
        for sub, sup in graph.subject_objects(RDFS.subClassOf):
            if sup in closure and isinstance(sub, URIRef) and sub not in closure:
                closure.add(sub)
                grew = True
    return frozenset(closure)


def suppression_vocab(onto: Graph) -> SuppressionVocab:
    """Derive the suppression vocabulary from the merged ontology."""
    appellation = GM.Appellation
    guarded = GM.coarsenGuarded
    classes = _subclass_closure(onto, appellation)
    bearer: set[URIRef] = set()
    domain_props: set[URIRef] = set()
    for prop, rng in onto.subject_objects(RDFS.range):
        if rng in classes and isinstance(prop, URIRef):
            bearer.add(prop)
    for prop, dom in onto.subject_objects(RDFS.domain):
        if dom in classes and isinstance(prop, URIRef):
            domain_props.add(prop)
    coarsen = {
        s
        for s, o in onto.subject_objects(guarded)
        if isinstance(s, URIRef) and str(o) == "true"
    }
    return SuppressionVocab(
        bearer_props=tuple(sorted(bearer)),
        appellation_domain_props=frozenset(domain_props),
        appellation_classes=classes,
        coarsen_guarded=frozenset(coarsen),
    )


@lru_cache(maxsize=1)
def _default_suppression_vocab() -> SuppressionVocab:
    """The vocab over the merged ontology (cached; used outside _artifacts)."""
    return suppression_vocab(load_merged_graph(include_imports=False))


def _suppression_anchors(p: MappingPattern) -> list[str]:
    """Subject variables of the REQUIRED pattern atoms, in pattern order.

    These are the gmeow-side entities a branch reads; ``gmeow:displayable``
    is deliberately domain-free, so EVERY one of them may carry
    ``displayable false`` and every one gets a withhold guard (#282,
    CONSTITUTION P10 — the producer enforces the display contract; consumers
    are never trusted to). Variables bound only inside OPTIONAL groups (or
    optional atoms) are excluded: a ``FILTER NOT EXISTS`` over a variable the
    solution leaves unbound would match ANY suppressed entity in the dataset
    and silently kill the whole branch.
    """
    anchors: list[str] = []
    for item in p.atoms:
        if isinstance(item, OptionalGroup) or item.optional:
            continue
        if item.subject_var not in anchors:
            anchors.append(item.subject_var)
    return anchors


def _required_atoms(p: MappingPattern) -> list[Atom]:
    """The top-level, non-optional pattern atoms (guard-injection scope)."""
    return [
        item
        for item in p.atoms
        if not isinstance(item, OptionalGroup) and not item.optional
    ]


def _injected_guards(p: MappingPattern, vocab: SuppressionVocab) -> list[str]:
    """The ontology-derived suppression guards for one branch (#282, P10).

    Three families, all fail-closed:

    * a ``displayable false`` withhold per required subject variable;
    * a ``coarsenTo`` filter wherever a required atom reads a
      ``gmeow:coarsenGuarded`` property — precise values never pass the
      mark; the coarse form is published only by a profile's explicit
      coarsening branch;
    * a bearer guard for appellation variables whose bearer is NOT bound in
      the pattern — a suppressed entity's otherwise-unmarked name must not
      surface through a bearer-less lexical branch.
    """
    required = _required_atoms(p)
    guards: list[str] = []
    # A variable whose pattern (or authored guards) already SPEAKS about
    # gmeow:displayable keeps its authored polarity — e.g. the mailmap
    # remapping cell positively matches `displayable false` because emitting
    # superseded identities under the canonical one IS the projection
    # (a licensed, reviewable re-publication; P10's retain-don't-delete).
    displayable_authored = {
        atom.subject_var
        for atom in (*required, *p.suppress_when, *p.project_when)
        if atom.predicate == GM.displayable
    }
    for var in _suppression_anchors(p):
        if var in displayable_authored:
            continue
        guards.append(f"FILTER NOT EXISTS {{ ?{var} gmeow:displayable false . }}")
    coarsen_suppressed = {
        atom.subject_var for atom in p.suppress_when if atom.predicate == GM.coarsenTo
    }
    for atom in required:
        if atom.predicate in vocab.coarsen_guarded:
            if atom.subject_var in coarsen_suppressed:
                continue  # the profile's authored coarsening branch governs
            guard = f"FILTER NOT EXISTS {{ ?{atom.subject_var} gmeow:coarsenTo [] . }}"
            if guard not in guards:
                guards.append(guard)
    bearer_visible = {
        atom.object_var
        for atom in required
        if atom.predicate in vocab.bearer_props
        or (atom.path_alts and set(atom.path_alts) & set(vocab.bearer_props))
    }
    appellation_vars: list[str] = []
    for atom in required:
        is_appellation = atom.predicate in vocab.appellation_domain_props or (
            atom.predicate == RDF.type
            and atom.object_value in vocab.appellation_classes
        )
        if (
            is_appellation
            and atom.subject_var not in bearer_visible
            and atom.subject_var not in appellation_vars
        ):
            appellation_vars.append(atom.subject_var)
    if appellation_vars and vocab.bearer_props:
        alternation = "|".join(curie(prop) for prop in vocab.bearer_props)
        for var in appellation_vars:
            guards.append(
                f"FILTER NOT EXISTS {{ ?_supBearer {alternation} ?{var} . "
                f"?_supBearer gmeow:displayable false . }}"
            )
    return guards


def _branch(cell: ProjectionCell, b: ProfileBinding, vocab: SuppressionVocab) -> str:
    p = cell.pattern
    lines: list[str] = _where_items(p.atoms)
    if b.value_class_map:
        cv = _class_var(p)
        lines.append(f"VALUES ( ?{p.value} ?{cv} ) {{")
        for vc in b.value_class_map:
            lines.append(f"    ( {curie(vc.when_value)} {curie(vc.to_class)} )")
        lines.append("}")
    for mint in p.mints:
        lines.append(f"BIND ( {render_expr(mint.expr)} AS ?{mint.var} )")
    for bind in p.binds:
        lines.append(f"BIND ( {render_expr(bind.expr)} AS ?{bind.var} )")
    authored_guards: set[str] = set()
    for atom in (*p.suppress_when, *p.exclude_when):
        guard = f"FILTER NOT EXISTS {{ {_atom_triple(atom)} }}"
        authored_guards.add(guard)
        lines.append(guard)
    # Suppression by construction (#282): P10's guards are injected into
    # every branch — derived from the pattern + ontology, never hand lists.
    for guard in _injected_guards(p, vocab):
        if guard not in authored_guards:
            lines.append(guard)
    for atom in p.project_when:
        lines.append(f"FILTER EXISTS {{ {_atom_triple(atom)} }}")
    for flt in p.filters:
        lines.append(f"FILTER( {render_expr(flt)} )")

    # Auto-retag GMEOW internal language tags (x-gmeow-...)
    val = p.value
    retag_lines = []
    bind_expr = None
    flat_atoms = _flatten_atoms(p.atoms)
    if p.edoal_source == GM.fullName:
        parent_var = None
        for a in flat_atoms:
            if a.predicate == GM.fullName:
                parent_var = a.subject_var
                break
        if parent_var:
            lang_var = "_lang"
            for a in flat_atoms:
                if a.predicate == GM.nameLanguage and a.subject_var == parent_var:
                    lang_var = a.object_var or lang_var
                    break
            ext_tag_var = "_extTag"
            for a in flat_atoms:
                if a.predicate == GM.bcp47Tag and a.subject_var == lang_var:
                    ext_tag_var = a.object_var or ext_tag_var
                    break
            retag_lines.extend(
                [
                    "OPTIONAL {",
                    f"    ?{parent_var} gmeow:nameLanguage ?{lang_var} .",
                    f"    ?{lang_var} gmeow:languageTag ?_intTag .",
                    f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                    f"    ?{lang_var} gmeow:bcp47Tag ?{ext_tag_var} .",
                    f"    OPTIONAL {{ ?{parent_var} gmeow:nameScript ?_sc . }}",
                    "}",
                ]
            )
            bind_expr = (
                f"IF(BOUND(?{ext_tag_var}), "
                f"STRLANG(STR(?{val}), "
                f"IF(BOUND(?_sc), CONCAT(STR(?{ext_tag_var}), '-', ?_sc), "
                f"STR(?{ext_tag_var}))), "
                f"?{val})"
            )
    elif p.edoal_source in (GM.partText, GM.partExpansion, GM.romanization):
        np_var = None
        for a in flat_atoms:
            if a.predicate in (
                GM.partText,
                GM.partExpansion,
                GM.romanization,
            ):
                np_var = a.subject_var
                break
        app_var = None
        for a in flat_atoms:
            if a.predicate == GM.hasNamePart and a.object_var == np_var:
                app_var = a.subject_var
                break
        if not app_var and np_var:
            for a in flat_atoms:
                if a.object_var == np_var:
                    app_var = a.subject_var
                    break
        if app_var and np_var:
            retag_lines.extend(
                [
                    "OPTIONAL {",
                    f"    ?{app_var} gmeow:nameLanguage ?_lang .",
                    "    ?_lang gmeow:languageTag ?_intTag .",
                    f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                    "    ?_lang gmeow:bcp47Tag ?_extTag .",
                    f"    OPTIONAL {{ ?{app_var} gmeow:nameScript ?_sc . }}",
                    "}",
                ]
            )
            bind_expr = (
                f"IF(BOUND(?_extTag), "
                f"STRLANG(STR(?{val}), "
                f"IF(BOUND(?_sc), CONCAT(STR(?_extTag), '-', ?_sc), STR(?_extTag))), "
                f"?{val})"
            )
    elif p.edoal_source in (GM.description, GM.designGoal, GM.title, GM.slogan):
        retag_lines.extend(
            [
                "OPTIONAL {",
                "    ?_lang gmeow:languageTag ?_intTag .",
                f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                "    ?_lang gmeow:bcp47Tag ?_extTag .",
                "}",
            ]
        )
        bind_expr = f"IF(BOUND(?_extTag), STRLANG(STR(?{val}), STR(?_extTag)), ?{val})"
    elif any(
        a.predicate in (RDFS.label, SKOS.definition, RDFS.comment)
        and a.object_var == val
        for a in flat_atoms
    ):
        # Generic fallback for standard annotation predicates that carry
        # language-tagged literals but have no explicit language link in the
        # pattern (e.g. genderValue rdfs:label, honorific rdfs:label).
        retag_lines.extend(
            [
                "OPTIONAL {",
                "    ?_lang gmeow:languageTag ?_intTag .",
                f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                "    ?_lang gmeow:bcp47Tag ?_extTag .",
                "}",
            ]
        )
        bind_expr = f"IF(BOUND(?_extTag), STRLANG(STR(?{val}), STR(?_extTag)), ?{val})"

    if retag_lines and bind_expr:
        lines.extend(retag_lines)
        lines.append(f"BIND ( {bind_expr} AS ?_final_{val} )")

    body = "\n".join(f"        {ln}" for ln in lines)
    return "{\n" + body + "\n    }"


def _templates(cell: ProjectionCell, b: ProfileBinding) -> list[str]:
    p = cell.pattern
    var_map: dict[str, str] = {}
    if (
        p.edoal_source
        in (
            GM.fullName,
            GM.partText,
            GM.partExpansion,
            GM.romanization,
            GM.description,
            GM.designGoal,
            GM.title,
            GM.slogan,
        )
        and p.value is not None
    ):
        var_map[p.value] = f"_final_{p.value}"
    elif p.value is not None and any(
        a.predicate in (RDFS.label, SKOS.definition, RDFS.comment)
        and a.object_var == p.value
        for a in _flatten_atoms(p.atoms)
    ):
        # Generic fallback for standard annotation predicates that carry
        # language-tagged literals (e.g. genderValue rdfs:label,
        # honorific rdfs:label).
        var_map[p.value] = f"_final_{p.value}"

    if b.template_atoms:
        return [_atom_triple(a, var_map) for a in b.template_atoms]
    if b.value_class_map:
        return [f"?{p.anchor} a ?{_class_var(p)} ."]
    if b.to_class is not None:
        return [f"?{p.anchor} a {curie(b.to_class)} ."]
    if b.to_predicate is not None:
        val = p.value
        if val in var_map:
            val = var_map[val]
        return [f"?{p.anchor} {curie(b.to_predicate)} ?{val} ."]
    raise CompileError(f"{cell.iri}: binding for {b.profile} has no output")


def _prefix_block(text: str) -> str:
    lines = []
    # Strip absolute IRIs (<...>) first so a prefix is never detected inside a URI
    # path/segment (e.g. "ps:" inside "https://…" or "…/ps:foo"). Then require a
    # token boundary that also excludes "_" (\w) so "foo_ps:" never matches "ps:".
    search_text = re.sub(r"<[^>]*>", "", text)
    for prefix, ns in PREFIXES.items():
        if re.search(rf"(?<!\w){re.escape(prefix)}:", search_text):
            lines.append(f"PREFIX {prefix}: <{ns}>")
    return "\n".join(lines)


#: The Standpoint-OWL 2 projection — re-expresses the standpoint axis as the
#: tool-compatible standpointLabel encoding (cl-tud/standpoint-owl2). The tool
#: matches any annotation property ending in ``#standpointLabel`` and reads a
#: structured ``<standpointAxiom><Box|Diamond><Standpoint name="…"/></…>`` string;
#: GMEOW's own ontology IRI yields ``…/gmeow#standpointLabel`` by that convention.
#:
#: This is the ONLY standpoint projection, and it is deliberately LOSSLESS: it
#: preserves every standpoint. There is no winner-selecting / frame-collapsing
#: projection — choosing one standpoint in a down-projection would re-create the
#: single winning slot the facility exists to abolish (Principle 9: no single slot
#: to win). A flat, perspectiveless format simply cannot carry "according to whom".
_STANDPOINT_OWL2_QUERY = "generated/queries/standpoint-owl2.rq"
_STANDPOINT_LABEL_IRI = f"{ONTOLOGY_IRI}#standpointLabel"


def emit_standpoint_owl2_sparql() -> str:
    """Render the lossless Standpoint-OWL 2 projection (the superset downcast, #43).

    Re-expresses every reified statement's ``gmeow:accordingTo`` +
    ``gmeow:standpointModality`` as a ``standpointLabel`` annotation in the exact
    syntax the cl-tud/standpoint-owl2 translator consumes — ``Box`` for unequivocal
    (□, the default), ``Diamond`` for conceivable (◊), the standpoint IRI as the
    ``Standpoint name`` (``*`` for the universal standpoint or an unindexed claim).
    A standpoint-aware reasoner can then run per-standpoint and cross-standpoint
    consistency over GMEOW's *full* multi-perspective KB. It is LOSSLESS by design —
    every standpoint is preserved, NONE is selected; collapsing to one frame would
    pick a winner (Principle 9). Fixed transformation, so this emitter is the
    canonical source (P4); the ``.rq`` is generated, never hand-edited.
    """
    label_concat = (
        "    BIND(CONCAT("
        '"<standpointAxiom><", ?op, '
        '"><Standpoint name=\\"", ?spName, '
        '"\\"/></", ?op, '
        '"></standpointAxiom>") AS ?label)\n'
    )
    sp_name = (
        "    BIND(IF(!BOUND(?sp) || ?sp = gmeow:universalStandpoint, "
        '"*", STR(?sp)) AS ?spName)\n'
    )
    modality = (
        "    BIND(IF(BOUND(?mod) && (?mod = gmeow:conceivable "
        "|| ?mod = gmeow:probable), "
        '"Diamond", "Box") AS ?op)\n'
    )
    # A refuted claim is the standpoint DENYING the proposition; the standpointLabel
    # encoding labels an ASSERTED axiom, so a denial cannot be expressed here without
    # asserting what S rejects. Refutations are carried losslessly by the CRMinf
    # projection (J5 holds to be 'false'); they are excluded here.
    refuted_filter = "    FILTER(!BOUND(?mod) || ?mod != gmeow:refuted)\n"
    body = (
        "CONSTRUCT {\n"
        # Declare the standpointLabel annotation property so the projected graph is
        # self-contained and DL-clean standalone (no undeclared-entity warnings).
        f"    <{_STANDPOINT_LABEL_IRI}> a owl:AnnotationProperty .\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o ;\n"
        f"        <{_STANDPOINT_LABEL_IRI}> ?label .\n"
        "    ?s ?p ?o .\n"
        "}\n"
        "WHERE {\n"
        "    { ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "      OPTIONAL { ?ax gmeow:standpointModality ?mod } }\n"
        "    UNION\n"
        "    { ?claim a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?ax .\n"
        "      ?ax a owl:Axiom ;\n"
        "          owl:annotatedSource ?s ;\n"
        "          owl:annotatedProperty ?p ;\n"
        "          owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?claim gmeow:claimModality ?mod } }\n"
        f"{refuted_filter}{sp_name}{modality}{label_concat}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → Standpoint-OWL 2 (standpointLabel). "
        f"{_GENERATED_BANNER}\n"
        "# Lossless multi-perspective downcast: re-expresses gmeow:accordingTo +\n"
        "# gmeow:standpointModality as the cl-tud/standpoint-owl2 standpointLabel\n"
        "# encoding (Box=□ settled, Diamond=◊ possible/probable, name=* universal).\n"
        "# Refuted (denied) claims are excluded — carried by standpoint-crminf.rq.\n"
        "# Branch B (#127): StandpointClaim with reified-statement observedFeature.\n"
        "# Branch C (generic-entity observedFeature) is excluded by design — the\n"
        "# translator matches only owl:Axiom individuals.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The CRMinf projection — re-expresses the standpoint axis as the CIDOC-CRM
#: Argumentation/belief model (I1 Argumentation / I2 Belief / I4 Proposition Set /
#: J5 holds to be a belief value). This carries the FULL belief-value space
#: (true/probable/possible/false), so a standpoint's DENIAL is first-class — the
#: parity that makes GMEOW at least as expressive as CRMinf.
_STANDPOINT_CRMINF_QUERY = "generated/queries/standpoint-crminf.rq"


def emit_standpoint_crminf_sparql() -> str:
    """Render the lossless CRMinf (CIDOC-CRM Argumentation) projection (#43).

    Each reified statement becomes an ``I1 Argumentation`` carried out by the
    standpoint (the universal standpoint when unindexed), which ``J2 concluded
    that`` an ``I2 Belief`` ``J4 that`` an ``I4 Proposition Set``; the proposition
    set ``J5 holds to be`` a belief value derived from gmeow:standpointModality —
    ``true`` (unequivocal), ``probable``, ``possible`` (conceivable), or ``false``
    (refuted). Because the value is explicit, a DENIAL is carried faithfully and the
    proposition is never asserted as a fact — GMEOW is thereby at least as expressive
    as CRMinf. Fixed transformation; the ``.rq`` is generated, never hand-edited.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    value = (
        '    BIND(IF(!BOUND(?mod), "true",'
        ' IF(?mod = gmeow:refuted, "false",'
        ' IF(?mod = gmeow:conceivable, "possible",'
        ' IF(?mod = gmeow:probable, "probable", "true")))) AS ?value)\n'
    )
    subject_bind = "    BIND(COALESCE(?s, ?feature) AS ?subject)\n"
    prop_text = (
        "    BIND(IF(BOUND(?s), "
        'CONCAT(STR(?s), " ", STR(?p), " ", STR(?o)), '
        "STR(?feature)) AS ?propText)\n"
    )
    mint = (
        '    BIND(IRI(CONCAT(STR(?ax), "/argumentation")) AS ?arg)\n'
        '    BIND(IRI(CONCAT(STR(?ax), "/belief")) AS ?belief)\n'
        '    BIND(IRI(CONCAT(STR(?ax), "/proposition")) AS ?prop)\n'
    )
    body = (
        "CONSTRUCT {\n"
        "    ?arg a crminf:I1_Argumentation ;\n"
        "        crm:P14_carried_out_by ?holder ;\n"
        "        crminf:J2_concluded_that ?belief .\n"
        "    ?belief a crminf:I2_Belief ;\n"
        "        crminf:J4_that ?prop .\n"
        "    ?prop a crminf:I4_Proposition_Set ;\n"
        "        crm:P67_refers_to ?subject ;\n"
        "        rdf:value ?propText ;\n"
        "        crminf:J5_holds_to_be ?value .\n"
        "}\n"
        "WHERE {\n"
        "    { ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "      OPTIONAL { ?ax gmeow:standpointModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?stmt .\n"
        "      ?stmt owl:annotatedSource ?s ;\n"
        "            owl:annotatedProperty ?p ;\n"
        "            owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?feature .\n"
        "      FILTER NOT EXISTS { ?feature owl:annotatedSource ?s }\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        f"{holder}{value}{subject_bind}{prop_text}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → CRMinf (CIDOC-CRM Argumentation). "
        f"{_GENERATED_BANNER}\n"
        "# Lossless belief projection: each standpoint-indexed statement becomes an\n"
        "# I1 Argumentation (carried out by the standpoint) concluding an I2 Belief\n"
        "# J4 that an I4 Proposition Set J5 holds to be true/probable/possible/false.\n"
        "# The explicit belief value carries DENIAL faithfully (≥ CRMinf); the\n"
        "# proposition is referred to, never asserted as fact.\n"
        "# Branches B/C (#127): StandpointClaim with reified-statement or\n"
        "# generic-entity observedFeature. Generic entities use ?feature as the\n"
        "# referred-to subject.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The PROV-O projection — each standpoint-indexed claim becomes a prov:Entity
#: attributed (prov:qualifiedAttribution) to its standpoint agent. Perspective-
#: preserving (every standpoint retained, none privileged), lossy on the belief
#: value / confidence (carried by the CRMinf + OWL 2 projections).
_STANDPOINT_PROV_QUERY = "generated/queries/standpoint-prov.rq"


def emit_standpoint_prov_sparql() -> str:
    """Render the PROV-O qualified-attribution projection (#43).

    Each reified statement becomes a ``prov:Entity`` (its proposition kept reified,
    never asserted) ``prov:wasAttributedTo`` its standpoint agent, with a
    ``prov:qualifiedAttribution`` node naming the ``prov:agent`` — the standpoint
    (the universal standpoint when unindexed). Every standpoint is retained and
    NONE is privileged; it is lossy only on the belief value (gmeow:standpointModality)
    and confidence, which the CRMinf / Standpoint-OWL 2 projections carry. Fixed
    transformation; the ``.rq`` is generated, never hand-edited.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/attribution")) AS ?attr)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?ax a prov:Entity ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o ;\n"
        "        prov:wasAttributedTo ?holder ;\n"
        "        prov:qualifiedAttribution ?attr .\n"
        "    ?attr a prov:Attribution ;\n"
        "        prov:agent ?holder .\n"
        "    ?holder a prov:Agent .\n"
        "}\n"
        "WHERE {\n"
        "    { ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:accordingTo ?sp } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?stmt .\n"
        "      ?stmt owl:annotatedSource ?s ;\n"
        "            owl:annotatedProperty ?p ;\n"
        "            owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?feature .\n"
        "      FILTER NOT EXISTS { ?feature owl:annotatedSource ?s }\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        f"{holder}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → PROV-O (qualified attribution). "
        f"{_GENERATED_BANNER}\n"
        "# Perspective-preserving provenance: each reified claim is a prov:Entity\n"
        "# attributed to its standpoint agent (prov:qualifiedAttribution). Every\n"
        "# standpoint retained, none privileged; lossy-drop: belief value (modality)\n"
        "# and confidence dropped — carried by standpoint-crminf.rq / -owl2.rq.\n"
        "# Branches B/C (#127): StandpointClaim with reified-statement or\n"
        "# generic-entity observedFeature. Generic-entity branch omits\n"
        "# owl:annotated* (unbound, skipped).\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The Web Annotation (OA) projection — each standpoint-indexed claim becomes an
#: oa:Annotation: body = the quoted statement, target = its subject, creator = the
#: standpoint. Perspective-preserving, lossy on the belief value / confidence.
_STANDPOINT_OA_QUERY = "generated/queries/standpoint-oa.rq"


def emit_standpoint_oa_sparql() -> str:
    """Render the W3C Web Annotation (OA) projection (#43).

    Each reified statement becomes an ``oa:Annotation`` whose ``oa:hasBody`` is the
    (still-reified, never-asserted) quoted statement, whose ``oa:hasTarget`` is the
    statement's subject, and whose ``dcterms:creator`` is the standpoint (the
    universal standpoint when unindexed), ``oa:motivatedBy oa:describing``. Every
    standpoint is retained and none is privileged; lossy only on the belief value
    (gmeow:standpointModality) and confidence. Fixed transformation; generated.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    target = "    BIND(COALESCE(?s, ?feature) AS ?target)\n"
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/annotation")) AS ?ann)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?ann a oa:Annotation ;\n"
        "        oa:hasTarget ?target ;\n"
        "        oa:hasBody ?ax ;\n"
        "        oa:motivatedBy oa:describing ;\n"
        "        dcterms:creator ?holder .\n"
        "    ?ax owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "}\n"
        "WHERE {\n"
        "    { ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:accordingTo ?sp } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?stmt .\n"
        "      ?stmt owl:annotatedSource ?s ;\n"
        "            owl:annotatedProperty ?p ;\n"
        "            owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?feature .\n"
        "      FILTER NOT EXISTS { ?feature owl:annotatedSource ?s }\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        f"{holder}{target}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → W3C Web Annotation (oa). "
        f"{_GENERATED_BANNER}\n"
        "# Perspective-preserving: each reified claim is an oa:Annotation (body = the\n"
        "# quoted statement, target = its subject, creator = the standpoint). Every\n"
        "# standpoint retained, none privileged; lossy-drop: belief value (modality)\n"
        "# and confidence dropped — carried by standpoint-crminf.rq / -owl2.rq.\n"
        "# Branches B/C (#127): StandpointClaim with reified-statement or\n"
        "# generic-entity observedFeature. Generic-entity branch uses ?feature as\n"
        "# oa:hasTarget.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The schema.org projection — each (non-denied) standpoint-indexed claim becomes a
#: schema:Claim authored by its standpoint, for the web / fact-check ecosystem. A
#: refuted (denied) claim is excluded (schema:author would misread denial as
#: authorship); denials are carried by the CRMinf projection.
_STANDPOINT_SCHEMA_QUERY = "generated/queries/standpoint-schema.rq"


def emit_standpoint_schema_sparql() -> str:
    """Render the schema.org Claim projection (#43).

    Each reified statement (other than a ``refuted`` denial) becomes a
    ``schema:Claim`` whose ``schema:author`` is the standpoint (the universal
    standpoint when unindexed) and whose ``schema:text`` is the rendered proposition
    — never the asserted base triple. Per-standpoint claims coexist (no single
    ``schema:ClaimReview`` verdict, the false-credibility GMEOW refuses). Denials are
    excluded — `schema:author` would misread them as authorship — and carried by the
    CRMinf projection instead. Perspective-preserving, lossy on the belief value.
    """
    refuted_filter = "    FILTER(!BOUND(?mod) || ?mod != gmeow:refuted)\n"
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    prop_text = (
        "    BIND(IF(BOUND(?s), "
        'CONCAT(STR(?s), " ", STR(?p), " ", STR(?o)), '
        "STR(?feature)) AS ?propText)\n"
    )
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/claim")) AS ?claim)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?claim a schema:Claim ;\n"
        "        schema:author ?holder ;\n"
        "        schema:text ?propText .\n"
        "}\n"
        "WHERE {\n"
        "    { ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "      OPTIONAL { ?ax gmeow:standpointModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?stmt .\n"
        "      ?stmt owl:annotatedSource ?s ;\n"
        "            owl:annotatedProperty ?p ;\n"
        "            owl:annotatedTarget ?o .\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        "    UNION\n"
        "    { ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?feature .\n"
        "      FILTER NOT EXISTS { ?feature owl:annotatedSource ?s }\n"
        "      OPTIONAL { ?ax gmeow:claimModality ?mod } }\n"
        f"{refuted_filter}{holder}{prop_text}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → schema.org Claim. "
        f"{_GENERATED_BANNER}\n"
        "# Web / fact-check ecosystem: each (non-denied) claim is a schema:Claim\n"
        "# authored by its standpoint; per-standpoint claims coexist (no single\n"
        "# ClaimReview verdict). Refuted/denied claims excluded (carried by\n"
        "# standpoint-crminf.rq); lossy-drop: belief value (modality) + confidence.\n"
        "# Branches B/C (#127): StandpointClaim with reified-statement or\n"
        "# generic-entity observedFeature. Generic-entity branch renders ?feature\n"
        "# IRI as schema:text.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The BBC News Ontology projection — standpoint-claims about events become
#: bbc:NewsEvent individuals with standpoint metadata.
_STANDPOINT_BBC_QUERY = "generated/queries/standpoint-bbc.rq"


def emit_standpoint_bbc_sparql() -> str:
    """Render the BBC News Ontology projection (#127).

    Each StandpointClaim whose observedFeature is a gmeow:Event becomes a
    ``bbc:NewsEvent`` whose ``bbc:about`` is the event, ``bbc:standpoint`` is the
    vantage, and ``bbc:modality`` is the claimModality.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    mint = '    BIND(IRI(CONCAT(STR(?event), "/news-event")) AS ?newsEvent)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?newsEvent a bbc:NewsEvent ;\n"
        "        bbc:about ?event ;\n"
        "        bbc:standpoint ?holder ;\n"
        "        bbc:modality ?mod .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a gmeow:StandpointClaim ;\n"
        "        gmeow:vantage ?sp ;\n"
        "        gmeow:observedFeature ?event .\n"
        "    ?event a gmeow:Event .\n"
        "    OPTIONAL { ?ax gmeow:claimModality ?mod }\n"
        f"{holder}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → BBC News Ontology. "
        f"{_GENERATED_BANNER}\n"
        "# Media-standpoint projection: StandpointClaim about an Event becomes a\n"
        "# bbc:NewsEvent with standpoint and modality metadata.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


def emit_sparql(dsl: Dsl, profile: str, vocab: SuppressionVocab | None = None) -> str:
    """Render the SPARQL CONSTRUCT executor for one profile."""
    if vocab is None:
        vocab = _default_suppression_vocab()
    templates: list[str] = []
    branches: list[str] = []
    drops: list[str] = []
    seen_branches: set[str] = set()
    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for tmpl in _templates(cell, b):
                if tmpl not in templates:
                    templates.append(tmpl)
            branch = _branch(cell, b, vocab)
            if branch not in seen_branches:
                seen_branches.add(branch)
                branches.append(branch)
            for d in b.lossy_drops:
                if d not in drops:
                    drops.append(d)
    if not branches:
        raise CompileError(f"no bindings for profile {profile!r}")

    construct = "\n".join(f"    {t}" for t in templates)
    where = "\n    ".join(b if i == 0 else f"UNION {b}" for i, b in enumerate(branches))
    body = f"CONSTRUCT {{\n{construct}\n}}\nWHERE {{\n    {where}\n}}\n"
    header = (
        f"# Projection: GMEOW → pure {profile}. {_GENERATED_BANNER}\n"
        f"# Lossy and directional by design"
        + (f"; drops: {'; '.join(drops)}." if drops else ".")
        + "\n"
    )
    prefixes = _prefix_block(body)
    return f"{header}{prefixes}\n\n{body}"


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


_DSL_STATS_FILE = "generated/mappings/dsl-stats.json"


def emit_dsl_stats(dsl: Dsl) -> str:
    """Render the DSL's surface counts as a committed, drift-gated artifact.

    Replaces hand-pinned counts in the test suite: a vocabulary addition
    changes THIS file (regenerate to resolve, the delta is reviewable in the
    PR diff) instead of a Python assertion that conflicts on every branch.
    Tests keep only structural invariants and catastrophe floors.
    """
    cells_by_set: dict[str, int] = {}
    for cell in dsl.equivalences:
        cells_by_set[cell.sssom_file] = cells_by_set.get(cell.sssom_file, 0) + 1
    stats = {
        "equivalences": len(dsl.equivalences),
        "functions": len(dsl.functions),
        "mapping_sets": len(dsl.mapping_sets),
        "projections": len(dsl.projections),
        "cells_by_set": dict(sorted(cells_by_set.items())),
    }
    return json.dumps(stats, indent=1, sort_keys=True) + "\n"


def _artifacts(
    dsl: Dsl, onto: Graph
) -> tuple[dict[str, Graph], dict[str, str], dict[str, str]]:
    """Render every artifact. Returns (rdf_graphs, sparql_texts, sssom_texts)."""
    rdf_graphs: dict[str, Graph] = {
        f"generated/projections/{_FNO_FILE}": emit_fno(dsl, onto)
    }
    sparql_texts: dict[str, str] = {}
    vocab = suppression_vocab(onto)

    # Per-profile EDOAL + SPARQL work is embarrassingly parallel.
    workers = max(1, min(os.cpu_count() or 1, 8, len(_PROFILES)))
    if workers == 1:
        for profile in _PROFILES:
            rdf_graphs[f"generated/projections/{profile}.edoal.ttl"] = emit_edoal(
                dsl, profile
            )
            sparql_texts[f"generated/queries/{profile}.rq"] = emit_sparql(
                dsl, profile, vocab
            )
    else:
        with concurrent.futures.ProcessPoolExecutor(
            max_workers=workers,
            initializer=_init_profile_worker,
            initargs=(dsl, vocab),
        ) as executor:
            for profile, edoal_graph, sparql_text in executor.map(
                _emit_profile_pair, _PROFILES, chunksize=1
            ):
                rdf_graphs[f"generated/projections/{profile}.edoal.ttl"] = edoal_graph
                sparql_texts[f"generated/queries/{profile}.rq"] = sparql_text

    sparql_texts[_STANDPOINT_OWL2_QUERY] = emit_standpoint_owl2_sparql()
    sparql_texts[_STANDPOINT_CRMINF_QUERY] = emit_standpoint_crminf_sparql()
    sparql_texts[_STANDPOINT_PROV_QUERY] = emit_standpoint_prov_sparql()
    sparql_texts[_STANDPOINT_OA_QUERY] = emit_standpoint_oa_sparql()
    sparql_texts[_STANDPOINT_SCHEMA_QUERY] = emit_standpoint_schema_sparql()
    sparql_texts[_STANDPOINT_BBC_QUERY] = emit_standpoint_bbc_sparql()
    sssom_texts = {
        f"generated/mappings/{file}": text for file, text in emit_sssom(dsl).items()
    }
    sssom_texts[_DSL_STATS_FILE] = emit_dsl_stats(dsl)
    return rdf_graphs, sparql_texts, sssom_texts


def _write_tree(
    root: Path,
    rdf_graphs: dict[str, Graph],
    sparql_texts: dict[str, str],
    sssom_texts: dict[str, str],
) -> None:
    for rel, graph in rdf_graphs.items():
        retag_graph(graph)  # projection boundary: public BCP-47 only (#287)
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        # Normalise the trailing newline so the pre-commit end-of-file fixer
        # never re-touches a generated file.
        turtle = graph.serialize(format="turtle").rstrip("\n") + "\n"
        path.write_text(turtle, encoding="utf-8")
    for rel, text in {**sparql_texts, **sssom_texts}.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def _run_invariants(root: Path) -> list[str]:
    """Run the three projection-lint invariants against a rendered tree."""
    # transforms.fno.ttl is hand-authored — copy it in so the FnO lint sees it.
    shutil.copy2(
        MAPPING_DSL_DIR / _TRANSFORMS_FILE,
        root / "generated" / "projections" / _TRANSFORMS_FILE,
    )
    proj = root / "generated" / "projections"
    queries = root / "generated" / "queries"
    maps = root / "generated" / "mappings"
    return [
        *fno_type_mismatches(proj),
        *fno_reference_integrity(proj),
        *projection_spec_drift(proj, queries, maps),
    ]


#: Canonical tool/code namespace for this surface's diagnostics (#809).
TOOL = "mapping-compile"


def compile_diagnostics_report(
    *,
    tool: str = TOOL,
) -> diagnostics.DiagnosticsReport:
    """Surface the mapping **DSL/compile** diagnostics as canonical findings (#809).

    Deliberately scoped to the DSL → artifact compile path: it loads the mapping
    DSL and builds the artifacts, mapping any ``CompileError`` (a malformed cell,
    missing binding, or unresolved value pattern) to a ``mapping-compile.dsl-error``
    finding. It does NOT run the FnO ``projection_lint`` trio or ``_validate_sssom``
    — those graph/SSSOM checks are being subsumed natively into ``gmeow-rdf`` by
    #848, so wrapping the current Python would only churn code #848 deletes; their
    Findings are tracked in #854 to ride #848's native SSSOM/FnO core. The
    mapping DSL compiler itself is still Python, so this surface is an honest thin
    forward into the Rust ``diagnostics.finding`` model until that too is subsumed.
    """
    report = diagnostics.report(tool)
    try:
        dsl = load_dsl()
        onto = load_merged_graph(include_imports=False)
        _artifacts(dsl, onto)
    except CompileError as exc:
        report.add(
            diagnostics.finding(
                severity="error",
                code=f"{tool}.dsl-error",
                message=str(exc),
                tool=tool,
            )
        )
    return report


def _committed_paths() -> dict[str, Path]:
    paths: dict[str, Path] = {
        f"generated/projections/{_FNO_FILE}": PROJECTIONS_DIR / _FNO_FILE
    }
    for profile in _PROFILES:
        paths[f"generated/projections/{profile}.edoal.ttl"] = (
            PROJECTIONS_DIR / f"{profile}.edoal.ttl"
        )
        paths[f"generated/queries/{profile}.rq"] = (
            PROJECTION_QUERY_DIR / f"{profile}.rq"
        )
    paths[_STANDPOINT_OWL2_QUERY] = PROJECTION_QUERY_DIR / "standpoint-owl2.rq"
    paths[_STANDPOINT_CRMINF_QUERY] = PROJECTION_QUERY_DIR / "standpoint-crminf.rq"
    paths[_STANDPOINT_PROV_QUERY] = PROJECTION_QUERY_DIR / "standpoint-prov.rq"
    paths[_STANDPOINT_OA_QUERY] = PROJECTION_QUERY_DIR / "standpoint-oa.rq"
    paths[_STANDPOINT_SCHEMA_QUERY] = PROJECTION_QUERY_DIR / "standpoint-schema.rq"
    paths[_STANDPOINT_BBC_QUERY] = PROJECTION_QUERY_DIR / "standpoint-bbc.rq"
    paths[_DSL_STATS_FILE] = MAPPINGS_DIR / "dsl-stats.json"
    return paths


def _drift(root: Path) -> list[str]:
    """Compare a freshly-rendered tree against the committed artifacts."""
    from gmeow_tools.rdf_canonical import graphs_isomorphic

    drifted: list[str] = []
    committed = _committed_paths()
    for rel, path in committed.items():
        fresh = root / rel
        if not path.exists():
            drifted.append(f"{rel} (missing committed file)")
            continue
        if rel.endswith(".ttl"):
            a, b = Graph().parse(path), Graph().parse(fresh)
            if not graphs_isomorphic(a, b):
                drifted.append(rel)
        else:
            if path.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                drifted.append(rel)
    fresh_sssom = {p.name for p in (root / "mappings").glob("*.sssom.tsv")}
    for name in sorted(fresh_sssom):
        committed_tsv = MAPPINGS_DIR / name
        if not committed_tsv.exists() or committed_tsv.read_text(encoding="utf-8") != (
            root / "mappings" / name
        ).read_text(encoding="utf-8"):
            drifted.append(f"mappings/{name}")
    # Orphans: a committed SSSOM file the DSL no longer produces (e.g. after a
    # greenfield deletion of its source) must be flagged, or it sits stale.
    for committed_tsv in sorted(MAPPINGS_DIR.glob("*.sssom.tsv")):
        if committed_tsv.name not in fresh_sssom:
            drifted.append(
                f"mappings/{committed_tsv.name} (orphaned — not produced by the DSL)"
            )
    return drifted


# --------------------------------------------------------------------------- #
# Registered generator
# --------------------------------------------------------------------------- #
