"""Compile the GMEOW mapping DSL into the four standard alignment artifacts.

``gmeow compile-mappings`` renders, from the single authoring source in
``mapping-dsl/``:

* ``mappings/*.sssom.tsv`` — SSSOM 1:1 term-equivalence rows;
* ``projections/*.edoal.ttl`` — EDOAL complex-alignment cells (with ``edoal:measure``);
* ``projections/functions.fno.ttl`` — the FnO transform catalog, its parameter
  ``fno:type`` DERIVED from each predicate's ontology ``rdfs:range`` (so the
  type-mismatch bug class is structurally impossible);
* ``queries/projections/*.rq`` — the executable SPARQL CONSTRUCT branches.

Before writing anything, the compiler renders the artifacts to a temporary tree
and runs the three :mod:`gmeow_tools.projection_lint` cross-layer invariants on
them; a violation aborts the compile (it can never reach disk). ``--check``
renders to a temp tree and diffs it against the committed files (RDF by graph
isomorphism, TSV/SPARQL by bytes), reporting any drift without writing.
"""

from __future__ import annotations

import io
import re
import shutil
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

import sssom
from rdflib import RDF, RDFS, BNode, Graph, Literal, URIRef
from rdflib.collection import Collection
from rdflib.compare import isomorphic
from rdflib.namespace import Namespace
from rdflib.term import Node
from sssom.validators import validate

from gmeow_tools.config import (
    MAPPINGS_DIR,
    ONTOLOGY_IRI,
    PREFIXES,
    PROJECTION_QUERY_DIR,
    PROJECTIONS_DIR,
    RELEASE_DATE,
    VERSION,
)
from gmeow_tools.graph import bind_prefixes, load_merged_graph
from gmeow_tools.mapping_dsl import (
    Atom,
    CompileError,
    Dsl,
    MappingPattern,
    MappingSet,
    OptionalGroup,
    ProfileBinding,
    ProjectionCell,
    curie,
    load_dsl,
    render_expr,
    sparql_string,
)
from gmeow_tools.projection_lint import (
    fno_reference_integrity,
    fno_type_mismatches,
    projection_spec_drift,
)

GM = Namespace(PREFIXES["gmeow"])
FNO = Namespace(PREFIXES["fno"])
FNOM = Namespace(PREFIXES["fnom"])
ALIGN = Namespace(PREFIXES["align"])
EDOAL = Namespace(PREFIXES["edoal"])
DCTERMS = Namespace(PREFIXES["dcterms"])

#: The projection profiles and the FnO catalog file name.
_PROFILES = (
    "schema-org",
    "vcard",
    "foaf",
    "geosparql",
    "qb",
    "ical",
    "owl-time",
    "odrl",
    "cc",
    "dcterms",
    "spdx",
    "ontolex",
    "web-annotation",
    "bot",
)
_FNO_FILE = "functions.fno.ttl"
#: Hand-authored FnO file the compiler reads (for the lint) but never writes.
_TRANSFORMS_FILE = "transforms.fno.ttl"

_GENERATED_BANNER = (
    "GENERATED by `gmeow compile-mappings` from mapping-dsl/ — DO NOT EDIT."
)


# --------------------------------------------------------------------------- #
# FnO emitter
# --------------------------------------------------------------------------- #


def _local(iri: URIRef) -> str:
    """The local name of an IRI (after the last ``#`` or ``/``)."""
    text = str(iri)
    cut = max(text.rfind("#"), text.rfind("/"))
    return text[cut + 1 :] if cut >= 0 else text


def _param_iri(predicate: URIRef) -> URIRef:
    local = _local(predicate)
    return URIRef(GM + "param" + local[:1].upper() + local[1:])


def _output_iri(fn: URIRef) -> URIRef:
    local = _local(fn)
    stem = local[2:] if local.startswith("fn") else local
    return URIRef(GM + "out" + stem)


def emit_fno(dsl: Dsl, onto: Graph) -> Graph:
    """Render the FnO function catalog; param fno:type derived from rdfs:range."""
    graph = Graph()
    bind_prefixes(graph)
    onto_iri = URIRef(ONTOLOGY_IRI)
    doc = URIRef(ONTOLOGY_IRI + "/projections/functions")
    graph.add((doc, RDF.type, URIRef(PREFIXES["owl"] + "Ontology")))
    graph.add((doc, RDFS.label, Literal("GMEOW projection functions (FnO)", lang="en")))
    graph.add((doc, DCTERMS.isPartOf, onto_iri))
    graph.add((doc, RDFS.comment, Literal(_GENERATED_BANNER, lang="en")))

    # Which profiles use each transform (+ ALL cells per (transform, profile) — a
    # transform can fan out to several cells, e.g. fnHonorificToAffix → prefix and
    # suffix — so the fnom mapping must aggregate every cell's var bindings).
    used_by: dict[URIRef, list[str]] = {}
    transform_cells: dict[tuple[URIRef, str], list[ProjectionCell]] = {}
    for cell in dsl.projections:
        for b in cell.bindings:
            if b.transform is not None:
                used_by.setdefault(b.transform, [])
                if b.profile not in used_by[b.transform]:
                    used_by[b.transform].append(b.profile)
                transform_cells.setdefault((b.transform, b.profile), []).append(cell)

    params_emitted: dict[URIRef, URIRef] = {}
    for fn_iri in sorted(dsl.functions, key=str):
        fn = dsl.functions[fn_iri]
        graph.add((fn_iri, RDF.type, FNO.Function))
        graph.add((fn_iri, RDFS.label, Literal(fn.label, lang="en")))
        if fn.description:
            graph.add((fn_iri, DCTERMS.description, Literal(fn.description, lang="en")))
        profiles = used_by.get(fn_iri) or ["schema-org"]
        graph.add(
            (
                fn_iri,
                RDFS.seeAlso,
                URIRef(f"{ONTOLOGY_IRI}/queries/projections/{profiles[0]}.rq"),
            )
        )
        # expects (required first, then optional), each param derives fno:type.
        expects: list[URIRef] = []
        for predicate, required in [
            *[(p, True) for p in fn.inputs],
            *[(p, False) for p in fn.optional_inputs],
        ]:
            param = _param_iri(predicate)
            # The derived fno:type is the whole point — refuse to emit a param
            # whose source predicate has no ontology range (the type mismatch
            # bug class would otherwise move from "wrong type" to "missing type").
            rng = onto.value(predicate, RDFS.range)
            if not isinstance(rng, URIRef):
                raise CompileError(
                    f"{fn_iri}: input {predicate} has no rdfs:range — "
                    "cannot derive its fno:type"
                )
            prior = params_emitted.get(param)
            if prior is not None and prior != predicate:
                raise CompileError(
                    f"param IRI collision: {param} is minted from both "
                    f"{prior} and {predicate}"
                )
            expects.append(param)
            if param not in params_emitted:
                params_emitted[param] = predicate
                graph.add((param, RDF.type, FNO.Parameter))
                graph.add((param, FNO.predicate, predicate))
                graph.add((param, FNO.type, rng))
                graph.add((param, FNO.required, Literal(required)))
        _attach_list(graph, fn_iri, FNO.expects, expects)
        out = _output_iri(fn_iri)
        graph.add((out, RDF.type, FNO.Output))
        graph.add((out, FNO.predicate, fn.output))
        graph.add((out, FNO.type, fn.output_type))
        _attach_list(graph, fn_iri, FNO.returns, [out])

    _emit_fnom(graph, dsl, used_by, transform_cells)
    return graph


def _camel(text: str) -> str:
    return "".join(p.capitalize() for p in text.replace("_", "-").split("-"))


def _impl_iri(profile: str) -> URIRef:
    return URIRef(GM + "impl" + _camel(profile))


def _var_for_predicate(cell: ProjectionCell, predicate: URIRef) -> str | None:
    """The SPARQL object variable an atom binds for ``predicate`` (or None).

    Matches a plain-predicate atom, and an alternation-path atom one of whose
    alternatives is the predicate (e.g. ``hasAppellation`` inside
    ``hasAppellation|hasName`` → the appellation variable).
    """
    for atom in _flatten_atoms(cell.pattern.atoms):
        if atom.object_var is None:
            continue
        if atom.predicate == predicate or predicate in atom.path_alts:
            return atom.object_var
    return None


def _output_var(cell: ProjectionCell) -> str | None:
    """The SPARQL variable a cell's output value binds to.

    The pattern's ``value`` for a single-value projection; for a structural
    (templateAtoms) transform with no value var, the last derived ``BIND`` var
    (the composed/retagged literal — e.g. the WKT, the address label).
    """
    if cell.pattern.value is not None:
        return cell.pattern.value
    if cell.pattern.binds:
        return cell.pattern.binds[-1].var
    return None


def _stable_bnode(label: str) -> BNode:
    """A blank node with a deterministic, meaningful id.

    Issue #36: rdflib's Turtle serializer orders blank nodes by their id, and a
    default ``BNode()`` id carries a per-process random component — so the emitted
    cell/mapping order (hence the committed artifact) varied run to run. Minting the
    id from the node's own content makes it stable across processes *and*
    self-documenting, while keeping EDOAL's anonymous-cell convention (the id drives
    ordering; the node still serializes inline as ``[ … ]`` with its ``rdfs:label``).
    """
    safe = "".join(c if c.isalnum() else "_" for c in label)
    return BNode(f"n_{safe}")


def _emit_fnom(
    graph: Graph,
    dsl: Dsl,
    used_by: dict[URIRef, list[str]],
    transform_cells: dict[tuple[URIRef, str], list[ProjectionCell]],
) -> None:
    """Emit fno:Implementation + fno:Mapping linking each function to its SPARQL.

    The FnO mapping vocabulary (fnom) makes the function self-describing about HOW
    it executes: one fno:Implementation per profile .rq, and one fno:Mapping per
    (function, profile) binding each parameter/output to the SPARQL variable that
    realises it (a PropertyParameterMapping — a SPARQL var is a named property).
    A transform may fan out to several cells in a profile (e.g. honorific →
    prefix and suffix), so the bindings are aggregated across every such cell.
    """
    impl_emitted: set[str] = set()
    for fn_iri in sorted(dsl.functions, key=str):
        fn = dsl.functions[fn_iri]
        out_node = _output_iri(fn_iri)
        for profile in used_by.get(fn_iri, []):
            impl = _impl_iri(profile)
            if profile not in impl_emitted:
                impl_emitted.add(profile)
                graph.add((impl, RDF.type, FNO.Implementation))
                graph.add(
                    (impl, DCTERMS["format"], Literal("application/sparql-query"))
                )
                graph.add(
                    (
                        impl,
                        RDFS.seeAlso,
                        URIRef(f"{ONTOLOGY_IRI}/queries/projections/{profile}.rq"),
                    )
                )
            cells = transform_cells.get((fn_iri, profile), [])
            # Aggregate every cell's parameter/output variable bindings.
            param_vars: dict[URIRef, set[str]] = {}
            out_vars: set[str] = set()
            for cell in cells:
                for predicate in (*fn.inputs, *fn.optional_inputs):
                    var = _var_for_predicate(cell, predicate)
                    if var is not None:
                        param_vars.setdefault(_param_iri(predicate), set()).add(var)
                out_var = _output_var(cell)
                if out_var is not None:
                    out_vars.add(out_var)

            fn_local = _local(fn_iri)
            mapping = _stable_bnode(f"mapping-{fn_local}-{profile}")
            graph.add((mapping, RDF.type, FNO.Mapping))
            # Label from the *neutral* function local name + profile — never
            # ``fn.label``, which may embed one profile's target term (e.g.
            # "… → schema:birthDate") and mislead when the function is reused
            # across profiles (vCard/FOAF).
            graph.add(
                (
                    mapping,
                    RDFS.label,
                    Literal(f"{fn_local} → {profile} (FnO mapping)", lang="en"),
                )
            )
            graph.add((mapping, FNO.function, fn_iri))
            graph.add((mapping, FNO.implementation, impl))
            for param in sorted(param_vars, key=str):
                for var in sorted(param_vars[param]):
                    pmap = _stable_bnode(
                        f"param-{fn_local}-{profile}-{_local(param)}-{var}"
                    )
                    graph.add((pmap, RDF.type, FNOM.PropertyParameterMapping))
                    graph.add(
                        (
                            pmap,
                            RDFS.label,
                            Literal(f"{_local(param)} ↦ ?{var}", lang="en"),
                        )
                    )
                    graph.add((pmap, FNOM.functionParameter, param))
                    graph.add((pmap, FNOM.implementationProperty, Literal(var)))
                    graph.add((mapping, FNO.parameterMapping, pmap))
            for var in sorted(out_vars):
                rmap = _stable_bnode(f"return-{fn_local}-{profile}-{var}")
                graph.add((rmap, RDF.type, FNOM.DefaultReturnMapping))
                graph.add(
                    (
                        rmap,
                        RDFS.label,
                        Literal(f"{fn_local} output ↦ ?{var}", lang="en"),
                    )
                )
                graph.add((rmap, FNOM.functionOutput, out_node))
                graph.add((rmap, FNOM.implementationProperty, Literal(var)))
                graph.add((mapping, FNO.returnMapping, rmap))


def _attach_list(
    graph: Graph, subject: Node, predicate: URIRef, items: Sequence[Node]
) -> None:
    """Attach an rdf:List of items to subject via predicate."""
    head = BNode()
    Collection(graph, head, list(items))
    graph.add((subject, predicate, head))


# --------------------------------------------------------------------------- #
# EDOAL emitter
# --------------------------------------------------------------------------- #

_EDOAL_KIND = {
    "class": EDOAL.Class,
    "relation": EDOAL.Relation,
    "property": EDOAL.Property,
}


def _edoal_entity(graph: Graph, term: URIRef, kind: str) -> BNode:
    node = BNode()
    graph.add((node, RDF.type, _EDOAL_KIND[kind]))
    graph.add((node, EDOAL.uri, term))
    return node


def _edoal_restriction(
    graph: Graph, source: URIRef, attr: URIRef, value: URIRef
) -> BNode:
    cls = BNode()
    graph.add((cls, RDF.type, EDOAL.Class))
    restriction = BNode()
    graph.add((restriction, RDF.type, EDOAL.AttributeValueRestriction))
    on_attr = BNode()
    graph.add((on_attr, RDF.type, EDOAL.Relation))
    graph.add((on_attr, EDOAL.uri, attr))
    graph.add((restriction, EDOAL.onAttribute, on_attr))
    graph.add((restriction, EDOAL.comparator, EDOAL.equals))
    val = BNode()
    graph.add((val, EDOAL.uri, value))
    graph.add((restriction, EDOAL.value, val))
    base = _edoal_entity(graph, source, "class")
    _attach_list(graph, cls, EDOAL["and"], [base, restriction])
    return cls


def _flatten_atoms(items: tuple[Atom | OptionalGroup, ...]) -> list[Atom]:
    """Flatten a pattern's items (recursing OPTIONAL groups) to bare atoms."""
    out: list[Atom] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.extend(_flatten_atoms(item.items))
        else:
            out.append(item)
    return out


def _nav_edges(pattern: MappingPattern) -> list[tuple[str, str, Atom]]:
    """Navigation edges (subjVar, objVar, atom): atoms relating two variables."""
    edges: list[tuple[str, str, Atom]] = []
    for atom in _flatten_atoms(pattern.atoms):
        has_pred = (
            atom.predicate is not None
            or atom.predicate_var is not None
            or atom.path is not None
            or atom.path_alts
        )
        if atom.object_var is not None and has_pred:
            edges.append((atom.subject_var, atom.object_var, atom))
    return edges


def _find_var_path(
    edges: list[tuple[str, str, Atom]], anchor: str, value: str
) -> list[tuple[Atom, bool]] | None:
    """BFS a simple variable path anchor→value; steps carry a forward/inverse flag."""
    from collections import deque

    adj: dict[str, list[tuple[str, Atom, bool]]] = {}
    for subj, obj, atom in edges:
        adj.setdefault(subj, []).append((obj, atom, True))
        adj.setdefault(obj, []).append((subj, atom, False))
    queue: deque[tuple[str, list[tuple[Atom, bool]]]] = deque([(anchor, [])])
    seen = {anchor}
    while queue:
        node, steps = queue.popleft()
        if node == value:
            return steps
        for nbr, atom, forward in adj.get(node, []):
            if nbr not in seen:
                seen.add(nbr)
                queue.append((nbr, [*steps, (atom, forward)]))
    return None


def _edoal_relation_step(graph: Graph, atom: Atom, forward: bool) -> BNode:
    """Render one navigation step as an EDOAL relation (inverse when backward)."""
    if atom.path_alts:
        if len(atom.path_alts) == 1:
            base = _edoal_entity(graph, atom.path_alts[0], "relation")
        else:
            # An alternation of relations: EDOAL edoal:or over the alternatives
            # (validator-safe; the executor still matches `a|b`).
            base = BNode()
            graph.add((base, RDF.type, EDOAL.Relation))
            _attach_list(
                graph,
                base,
                EDOAL["or"],
                [_edoal_entity(graph, a, "relation") for a in atom.path_alts],
            )
    elif atom.predicate is not None:
        base = _edoal_entity(graph, atom.predicate, "relation")
    else:  # an opaque seq/zero-or-more path — degrade to a commented relation node
        base = BNode()
        graph.add((base, RDF.type, EDOAL.Relation))
        graph.add(
            (base, RDFS.comment, Literal(atom.path or atom.predicate_var or "path"))
        )
    if forward:
        return base
    inverse = BNode()
    graph.add((inverse, RDF.type, EDOAL.Relation))
    graph.add((inverse, EDOAL.inverse, base))
    return inverse


def _edoal_path(graph: Graph, pattern: MappingPattern) -> BNode | None:
    """Derive entity1 as the anchor→value relation path (compose/inverse), or None."""
    if pattern.value is None:
        return None
    steps = _find_var_path(_nav_edges(pattern), pattern.anchor, pattern.value)
    if not steps:
        return None
    relations = [_edoal_relation_step(graph, atom, fwd) for atom, fwd in steps]
    if len(relations) == 1:
        return relations[0]
    compose = BNode()
    graph.add((compose, RDF.type, EDOAL.Relation))
    _attach_list(graph, compose, EDOAL.compose, relations)
    return compose


def emit_edoal(dsl: Dsl, profile: str) -> Graph:
    """Render the EDOAL alignment for one profile."""
    graph = Graph()
    bind_prefixes(graph)
    align = URIRef(f"{ONTOLOGY_IRI}/projections/{profile}")
    graph.add((align, RDF.type, ALIGN.Alignment))
    graph.add((align, RDFS.label, Literal(f"GMEOW → {profile} (EDOAL)", lang="en")))
    graph.add((align, DCTERMS.isPartOf, URIRef(ONTOLOGY_IRI)))
    graph.add((align, RDFS.comment, Literal(_GENERATED_BANNER, lang="en")))
    graph.add((align, ALIGN.level, Literal("2EDOAL")))
    for n, name in ((ALIGN.onto1, "GMEOW"), (ALIGN.onto2, profile)):
        onto = BNode()
        graph.add((onto, RDF.type, ALIGN.Ontology))
        formalism = BNode()
        graph.add((formalism, ALIGN.name, Literal(name)))
        graph.add((onto, ALIGN.formalism, formalism))
        graph.add((align, n, onto))

    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for map_cell in _edoal_cells(graph, cell, b):
                graph.add((align, ALIGN.map, map_cell))
    return graph


def _edoal_cells(graph: Graph, cell: ProjectionCell, b: ProfileBinding) -> list[BNode]:
    """Return the EDOAL align:Cell node(s) for one binding (0, 1, or N)."""
    pattern = cell.pattern
    cells: list[BNode] = []

    def _cell(entity1: Node, entity2: Node, label: str, key: str) -> BNode:
        # Deterministic, meaningful blank-node id (issue #36) — keyed on the source
        # projection cell, the profile, and a fan-out key so it is unique and stable.
        node = _stable_bnode(f"cell-{b.profile}-{_local(cell.iri)}-{key}")
        graph.add((node, RDF.type, ALIGN.Cell))
        graph.add((node, RDFS.label, Literal(label, lang="en")))
        graph.add((node, ALIGN.entity1, entity1))
        graph.add((node, ALIGN.entity2, entity2))
        graph.add((node, ALIGN.relation, Literal(b.relation)))
        if b.transform is not None:
            trans = BNode()
            graph.add((trans, RDFS.seeAlso, b.transform))
            graph.add((node, EDOAL.transformation, trans))
        if b.confidence is not None:
            graph.add((node, EDOAL.measure, Literal(b.confidence)))
        return node

    if b.value_class_map:
        if pattern.edoal_source is None:
            raise CompileError(f"{cell.iri}: value-class map needs edoalSource")
        for i, vc in enumerate(b.value_class_map):
            entity1 = _edoal_restriction(
                graph, pattern.edoal_source, _attr_of(pattern), vc.when_value
            )
            entity2 = _edoal_entity(graph, vc.to_class, "class")
            cells.append(
                _cell(
                    entity1,
                    entity2,
                    f"{curie(pattern.edoal_source)} "
                    f"[{curie(vc.when_value)}] → {curie(vc.to_class)}",
                    key=f"{i}-{_local(vc.to_class)}",
                )
            )
        return cells

    # entity1: a derived relation path (compose/inverse) when opted in; else the
    # authored salient term; else no cell (structural / SSSOM-backed projection).
    target, target_kind = _edoal_target(b)
    if target is None:
        return cells

    source: Node | None
    if pattern.edoal_path:
        source = _edoal_path(graph, pattern)
        if source is None:
            raise CompileError(f"{cell.iri}: edoalPath set but no anchor→value path")
    elif pattern.edoal_source is not None:
        source = _edoal_entity(graph, pattern.edoal_source, pattern.edoal_source_kind)
    else:
        return cells

    target_entity = _edoal_entity(graph, target, target_kind)
    cells.append(
        _cell(source, target_entity, cell.label or f"→ {curie(target)}", key="0")
    )
    return cells


def _attr_of(pattern: MappingPattern) -> URIRef:
    """The value->class restriction attribute (the placeType-style predicate)."""
    for atom in _flatten_atoms(pattern.atoms):
        if atom.object_var == pattern.value and atom.predicate is not None:
            return atom.predicate
    raise CompileError("value-class pattern has no value-binding predicate")


def _edoal_target(b: ProfileBinding) -> tuple[URIRef | None, str]:
    if b.edoal_target is not None:
        return b.edoal_target, b.edoal_target_kind or "class"
    if b.to_class is not None:
        return b.to_class, b.edoal_target_kind or "class"
    if b.to_predicate is not None:
        return b.to_predicate, b.edoal_target_kind or "property"
    return None, "property"


# --------------------------------------------------------------------------- #
# SSSOM emitter
# --------------------------------------------------------------------------- #

_DEFAULT_JUSTIFICATION = URIRef(PREFIXES["semapv"] + "ManualMappingCuration")


def _conf(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:g}" if value != int(value) else f"{value:.1f}"


#: SSSOM columns in canonical order; labels are emitted only when populated.
_SSSOM_ORDER = (
    "subject_id",
    "subject_label",
    "predicate_id",
    "object_id",
    "object_label",
    "mapping_justification",
    "confidence",
    "comment",
)
_SSSOM_ALWAYS = frozenset(
    {
        "subject_id",
        "predicate_id",
        "object_id",
        "mapping_justification",
        "confidence",
        "comment",
    }
)


def _sssom_header(meta: MappingSet | None, prefixes: list[str]) -> list[str]:
    """The SSSOM YAML metadata header: set id, license, provenance, curie_map."""
    lines: list[str] = []
    if meta is not None and meta.set_id:
        lines.append(f"# mapping_set_id: {meta.set_id}")
        lines.append(f"# mapping_set_version: {VERSION}")
        lines.append(f"# license: {meta.license}")
    lines.append("# mapping_tool: gmeow compile-mappings")
    lines.append(f"# mapping_tool_version: {VERSION}")
    lines.append(f"# mapping_date: {RELEASE_DATE}")
    if meta is not None and meta.comment:
        # Collapse any whitespace run (incl. the newlines of a multi-line Turtle
        # """...""" source literal) to single spaces, so the comment stays on one
        # SSSOM header line regardless of how it is wrapped in the DSL source.
        comment = " ".join(meta.comment.split())
        lines.append(f"# comment: {comment}")
    lines.append("# curie_map:")
    for prefix in prefixes:
        lines.append(f"#   {prefix}: {PREFIXES[prefix]}")
    return lines


def emit_sssom(dsl: Dsl) -> dict[str, str]:
    """Render every SSSOM TSV file from the term-equivalence cells.

    SSSOM rows are owned exclusively by gmeow:TermEquivalence cells (a 1:1 with
    the rows). Each file carries deterministic provenance metadata + a curie_map
    of the prefixes it uses; subject_label/object_label columns appear only when a
    row populates them.
    """
    rows: dict[str, list[dict[str, str]]] = {}
    for eq in dsl.equivalences:
        rows.setdefault(eq.sssom_file, []).append(
            {
                "subject_id": curie(eq.subject),
                "subject_label": eq.subject_label,
                "predicate_id": curie(eq.predicate),
                "object_id": curie(eq.obj),
                "object_label": eq.object_label,
                "mapping_justification": curie(
                    eq.justification or _DEFAULT_JUSTIFICATION
                ),
                "confidence": _conf(eq.confidence),
                "comment": eq.comment,
            }
        )

    out: dict[str, str] = {}
    for file, file_rows in rows.items():
        meta = dsl.mapping_sets.get(file)
        columns = [
            c
            for c in _SSSOM_ORDER
            if c in _SSSOM_ALWAYS or any(r[c] for r in file_rows)
        ]
        used_prefixes = sorted(
            {
                tok.split(":", 1)[0]
                for r in file_rows
                for tok in (
                    r["subject_id"],
                    r["predicate_id"],
                    r["object_id"],
                    r["mapping_justification"],
                )
                if ":" in tok and tok.split(":", 1)[0] in PREFIXES
            }
        )
        lines = _sssom_header(meta, used_prefixes)
        lines.append("\t".join(columns))
        for r in sorted(
            file_rows,
            key=lambda r: (r["subject_id"], r["predicate_id"], r["object_id"]),
        ):
            lines.append("\t".join(r[c] for c in columns))
        if meta is not None and meta.trailer:
            lines.extend(meta.trailer.splitlines())
        out[file] = "\n".join(lines) + "\n"
    return out


# --------------------------------------------------------------------------- #
# SSSOM validation
# --------------------------------------------------------------------------- #


def _sssom_for_validation(text: str) -> str:
    """Return a version of a GMEOW SSSOM text that ``sssom-py`` can parse.

    Applies two GMEOW→SSSOM-Toolkit compatibility shims:

    1. **Quote the ``comment`` header value** if it contains YAML-special
       characters (colons, brackets, etc.).  GMEOW comments are prose that
       may contain ``FORMAL GROUNDING:`` and similar colons; the SSSOM
       Toolkit header parser treats the header as YAML and fails on unquoted
       colons.
    2. **Strip trailer comments** that appear after the data section.
       ``sssom-py`` consumes every ``#``-prefixed line before the TSV column
       header as YAML metadata; any ``#`` line *after* the header is passed
       to pandas as a data row and reported as a malformed mapping.  GMEOW
       intentionally emits trailer comments (e.g. ``# REFUSED …``) to
       document refused alignments; these are stripped for validation only.
    """
    lines = text.splitlines()

    # Find the TSV column-header row (first line that does not start with #).
    header_idx: int | None = None
    for i, line in enumerate(lines):
        if not line.startswith("#"):
            header_idx = i
            break

    if header_idx is None:
        # No data rows — nothing that sssom-py can validate meaningfully.
        return text

    # Strip trailer comments that follow the data rows.
    data_lines = lines[header_idx:]
    while data_lines and data_lines[-1].startswith("#"):
        data_lines.pop()

    # Fix YAML in header key-value lines (curie_map entries are left untouched).
    fixed_header: list[str] = []
    for line in lines[:header_idx]:
        m = re.match(r"^# ([A-Za-z0-9_]+): (.*)$", line)
        if m and m.group(1) != "curie_map":
            key, value = m.groups()
            if ": " in value or value.startswith(("[", "{", "|", ">", "*", "&", "!")):
                escaped = value.replace("\\", "\\\\").replace('"', '\\"')
                fixed_header.append(f'# {key}: "{escaped}"')
            else:
                fixed_header.append(line)
        else:
            fixed_header.append(line)

    return "\n".join(fixed_header + data_lines) + "\n"


def _validate_sssom(sssom_texts: dict[str, str]) -> list[str]:
    """Run every generated SSSOM TSV through the SSSOM Toolkit validator.

    Parses each text in memory (so the exact bytes that will be written are
    checked) and returns a flat list of diagnostic strings.  An empty list
    means every file passed validation.
    """
    problems: list[str] = []
    for rel_path, text in sssom_texts.items():
        safe = _sssom_for_validation(text)
        try:
            msdf = sssom.parse_tsv(io.StringIO(safe))
        except Exception as exc:
            problems.append(f"{rel_path}: parse error — {exc}")
            continue
        try:
            reports = validate(msdf, validation_types=None, fail_on_error=False)
        except Exception as exc:
            problems.append(f"{rel_path}: validation engine error — {exc}")
            continue
        for validation_type, report in reports.items():
            for result in report.results:
                if result.severity.value in ("ERROR", "FATAL"):
                    node = result.instance if result.instance is not None else "—"
                    problems.append(
                        f"{rel_path}: {result.message} "
                        f"(type={result.type}, node={node}, "
                        f"check={validation_type.value})"
                    )
    return problems


# --------------------------------------------------------------------------- #
# SPARQL emitter
# --------------------------------------------------------------------------- #


def _term(atom: Atom, var_map: dict[str, str] | None = None) -> str:
    if atom.object_var is not None:
        obj_var = atom.object_var
        if var_map and obj_var in var_map:
            obj_var = var_map[obj_var]
        return f"?{obj_var}"
    if atom.object_value is not None:
        return curie(atom.object_value)
    if atom.object_literal is not None:
        lit = atom.object_literal
        if lit.datatype == URIRef(PREFIXES["xsd"] + "boolean"):
            return "true" if str(lit).lower() in ("true", "1") else "false"
        return sparql_string(str(lit))
    raise CompileError("atom has no object")


def _atom_triple(atom: Atom, var_map: dict[str, str] | None = None) -> str:
    subj_var = atom.subject_var
    if var_map and subj_var in var_map:
        subj_var = var_map[subj_var]
    subj = f"?{subj_var}"
    if atom.path is not None:
        pred = atom.path
    elif atom.predicate_var is not None:
        pred = f"?{atom.predicate_var}"
    elif atom.predicate == RDF.type and atom.object_value is not None:
        pred = "a"
    elif atom.predicate is not None:
        pred = curie(atom.predicate)
    else:
        raise CompileError(f"atom on ?{atom.subject_var} has no predicate/path")
    return f"{subj} {pred} {_term(atom, var_map)} ."


def _class_var(pattern: MappingPattern) -> str:
    return f"{pattern.value}Class"


def _where_items(
    items: tuple[Atom | OptionalGroup, ...], indent: str = ""
) -> list[str]:
    """Render WHERE items (atoms + nested OPTIONAL groups) at a relative indent."""
    out: list[str] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.append(f"{indent}OPTIONAL {{")
            out.extend(_where_items(item.items, indent + "    "))
            out.append(f"{indent}}}")
        else:
            triple = _atom_triple(item)
            wrapped = f"OPTIONAL {{ {triple} }}" if item.optional else triple
            out.append(f"{indent}{wrapped}")
    return out


def _branch(cell: ProjectionCell, b: ProfileBinding) -> str:
    p = cell.pattern
    lines: list[str] = _where_items(p.atoms)
    if b.value_class_map:
        cv = _class_var(p)
        lines.append(f"VALUES ( ?{p.value} ?{cv} ) {{")
        for vc in b.value_class_map:
            lines.append(f"    ( {curie(vc.when_value)} {curie(vc.to_class)} )")
        lines.append("}")
    for mint in p.mints:
        lines.append(f"BIND ( {render_expr(mint.expr)} AS ?{mint.var} )")
    for bind in p.binds:
        lines.append(f"BIND ( {render_expr(bind.expr)} AS ?{bind.var} )")
    for atom in (*p.suppress_when, *p.exclude_when):
        lines.append(f"FILTER NOT EXISTS {{ {_atom_triple(atom)} }}")
    for flt in p.filters:
        lines.append(f"FILTER( {render_expr(flt)} )")

    # Auto-retag GMEOW internal language tags (x-gmeow-...)
    val = p.value
    retag_lines = []
    bind_expr = None
    flat_atoms = _flatten_atoms(p.atoms)
    if p.edoal_source == GM.fullName:
        parent_var = None
        for a in flat_atoms:
            if a.predicate == GM.fullName:
                parent_var = a.subject_var
                break
        if parent_var:
            lang_var = "_lang"
            for a in flat_atoms:
                if a.predicate == GM.nameLanguage and a.subject_var == parent_var:
                    lang_var = a.object_var or lang_var
                    break
            ext_tag_var = "_extTag"
            for a in flat_atoms:
                if a.predicate == GM.bcp47Tag and a.subject_var == lang_var:
                    ext_tag_var = a.object_var or ext_tag_var
                    break
            retag_lines.extend(
                [
                    "OPTIONAL {",
                    f"    ?{parent_var} gmeow:nameLanguage ?{lang_var} .",
                    f"    ?{lang_var} gmeow:languageTag ?_intTag .",
                    f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                    f"    ?{lang_var} gmeow:bcp47Tag ?{ext_tag_var} .",
                    f"    OPTIONAL {{ ?{parent_var} gmeow:nameScript ?_sc . }}",
                    "}",
                ]
            )
            bind_expr = (
                f"IF(BOUND(?{ext_tag_var}), "
                f"STRLANG(STR(?{val}), "
                f"IF(BOUND(?_sc), CONCAT(STR(?{ext_tag_var}), '-', ?_sc), "
                f"STR(?{ext_tag_var}))), "
                f"?{val})"
            )
    elif p.edoal_source in (GM.partText, GM.partExpansion, GM.romanization):
        np_var = None
        for a in flat_atoms:
            if a.predicate in (
                GM.partText,
                GM.partExpansion,
                GM.romanization,
            ):
                np_var = a.subject_var
                break
        app_var = None
        for a in flat_atoms:
            if a.predicate == GM.hasNamePart and a.object_var == np_var:
                app_var = a.subject_var
                break
        if not app_var and np_var:
            for a in flat_atoms:
                if a.object_var == np_var:
                    app_var = a.subject_var
                    break
        if app_var and np_var:
            retag_lines.extend(
                [
                    "OPTIONAL {",
                    f"    ?{app_var} gmeow:nameLanguage ?_lang .",
                    "    ?_lang gmeow:languageTag ?_intTag .",
                    f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                    "    ?_lang gmeow:bcp47Tag ?_extTag .",
                    f"    OPTIONAL {{ ?{app_var} gmeow:nameScript ?_sc . }}",
                    "}",
                ]
            )
            bind_expr = (
                f"IF(BOUND(?_extTag), "
                f"STRLANG(STR(?{val}), "
                f"IF(BOUND(?_sc), CONCAT(STR(?_extTag), '-', ?_sc), STR(?_extTag))), "
                f"?{val})"
            )
    elif p.edoal_source in (GM.description, GM.designGoal):
        retag_lines.extend(
            [
                "OPTIONAL {",
                "    ?_lang gmeow:languageTag ?_intTag .",
                f"    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)",
                "    ?_lang gmeow:bcp47Tag ?_extTag .",
                "}",
            ]
        )
        bind_expr = f"IF(BOUND(?_extTag), STRLANG(STR(?{val}), STR(?_extTag)), ?{val})"

    if retag_lines and bind_expr:
        lines.extend(retag_lines)
        lines.append(f"BIND ( {bind_expr} AS ?_final_{val} )")

    body = "\n".join(f"        {ln}" for ln in lines)
    return "{\n" + body + "\n    }"


def _templates(cell: ProjectionCell, b: ProfileBinding) -> list[str]:
    p = cell.pattern
    var_map: dict[str, str] = {}
    if (
        p.edoal_source
        in (
            GM.fullName,
            GM.partText,
            GM.partExpansion,
            GM.romanization,
            GM.description,
            GM.designGoal,
        )
        and p.value is not None
    ):
        var_map[p.value] = f"_final_{p.value}"

    if b.template_atoms:
        return [_atom_triple(a, var_map) for a in b.template_atoms]
    if b.value_class_map:
        return [f"?{p.anchor} a ?{_class_var(p)} ."]
    if b.to_class is not None:
        return [f"?{p.anchor} a {curie(b.to_class)} ."]
    if b.to_predicate is not None:
        val = p.value
        if val in var_map:
            val = var_map[val]
        return [f"?{p.anchor} {curie(b.to_predicate)} ?{val} ."]
    raise CompileError(f"{cell.iri}: binding for {b.profile} has no output")


def _prefix_block(text: str) -> str:
    lines = []
    # Strip absolute IRIs (<...>) first so a prefix is never detected inside a URI
    # path/segment (e.g. "ps:" inside "https://…" or "…/ps:foo"). Then require a
    # token boundary that also excludes "_" (\w) so "foo_ps:" never matches "ps:".
    search_text = re.sub(r"<[^>]*>", "", text)
    for prefix, ns in PREFIXES.items():
        if re.search(rf"(?<!\w){re.escape(prefix)}:", search_text):
            lines.append(f"PREFIX {prefix}: <{ns}>")
    return "\n".join(lines)


#: The Standpoint-OWL 2 projection — re-expresses the standpoint axis as the
#: tool-compatible standpointLabel encoding (cl-tud/standpoint-owl2). The tool
#: matches any annotation property ending in ``#standpointLabel`` and reads a
#: structured ``<standpointAxiom><Box|Diamond><Standpoint name="…"/></…>`` string;
#: GMEOW's own ontology IRI yields ``…/gmeow#standpointLabel`` by that convention.
#:
#: This is the ONLY standpoint projection, and it is deliberately LOSSLESS: it
#: preserves every standpoint. There is no winner-selecting / frame-collapsing
#: projection — choosing one standpoint in a down-projection would re-create the
#: single winning slot the facility exists to abolish (Principle 9: no single slot
#: to win). A flat, perspectiveless format simply cannot carry "according to whom".
_STANDPOINT_OWL2_QUERY = "queries/projections/standpoint-owl2.rq"
_STANDPOINT_LABEL_IRI = f"{ONTOLOGY_IRI}#standpointLabel"


def emit_standpoint_owl2_sparql() -> str:
    """Render the lossless Standpoint-OWL 2 projection (the superset downcast, #43).

    Re-expresses every reified statement's ``gmeow:accordingTo`` +
    ``gmeow:standpointModality`` as a ``standpointLabel`` annotation in the exact
    syntax the cl-tud/standpoint-owl2 translator consumes — ``Box`` for unequivocal
    (□, the default), ``Diamond`` for conceivable (◊), the standpoint IRI as the
    ``Standpoint name`` (``*`` for the universal standpoint or an unindexed claim).
    A standpoint-aware reasoner can then run per-standpoint and cross-standpoint
    consistency over GMEOW's *full* multi-perspective KB. It is LOSSLESS by design —
    every standpoint is preserved, NONE is selected; collapsing to one frame would
    pick a winner (Principle 9). Fixed transformation, so this emitter is the
    canonical source (P4); the ``.rq`` is generated, never hand-edited.
    """
    label_concat = (
        "    BIND(CONCAT("
        '"<standpointAxiom><", ?op, '
        '"><Standpoint name=\\"", ?spName, '
        '"\\"/></", ?op, '
        '"></standpointAxiom>") AS ?label)\n'
    )
    sp_name = (
        "    BIND(IF(!BOUND(?sp) || ?sp = gmeow:universalStandpoint, "
        '"*", STR(?sp)) AS ?spName)\n'
    )
    modality = (
        "    BIND(IF(BOUND(?mod) && (?mod = gmeow:conceivable "
        "|| ?mod = gmeow:probable), "
        '"Diamond", "Box") AS ?op)\n'
    )
    # A refuted claim is the standpoint DENYING the proposition; the standpointLabel
    # encoding labels an ASSERTED axiom, so a denial cannot be expressed here without
    # asserting what S rejects. Refutations are carried losslessly by the CRMinf
    # projection (J5 holds to be 'false'); they are excluded here.
    refuted_filter = "    FILTER(!BOUND(?mod) || ?mod != gmeow:refuted)\n"
    body = (
        "CONSTRUCT {\n"
        # Declare the standpointLabel annotation property so the projected graph is
        # self-contained and DL-clean standalone (no undeclared-entity warnings).
        f"    <{_STANDPOINT_LABEL_IRI}> a owl:AnnotationProperty .\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o ;\n"
        f"        <{_STANDPOINT_LABEL_IRI}> ?label .\n"
        "    ?s ?p ?o .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "    OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "    OPTIONAL { ?ax gmeow:standpointModality ?mod }\n"
        f"{refuted_filter}{sp_name}{modality}{label_concat}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → Standpoint-OWL 2 (standpointLabel). "
        f"{_GENERATED_BANNER}\n"
        "# Lossless multi-perspective downcast: re-expresses gmeow:accordingTo +\n"
        "# gmeow:standpointModality as the cl-tud/standpoint-owl2 standpointLabel\n"
        "# encoding (Box=□ settled, Diamond=◊ possible/probable, name=* universal).\n"
        "# Refuted (denied) claims are excluded — carried by standpoint-crminf.rq.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The CRMinf projection — re-expresses the standpoint axis as the CIDOC-CRM
#: Argumentation/belief model (I1 Argumentation / I2 Belief / I4 Proposition Set /
#: J5 holds to be a belief value). This carries the FULL belief-value space
#: (true/probable/possible/false), so a standpoint's DENIAL is first-class — the
#: parity that makes GMEOW at least as expressive as CRMinf.
_STANDPOINT_CRMINF_QUERY = "queries/projections/standpoint-crminf.rq"


def emit_standpoint_crminf_sparql() -> str:
    """Render the lossless CRMinf (CIDOC-CRM Argumentation) projection (#43).

    Each reified statement becomes an ``I1 Argumentation`` carried out by the
    standpoint (the universal standpoint when unindexed), which ``J2 concluded
    that`` an ``I2 Belief`` ``J4 that`` an ``I4 Proposition Set``; the proposition
    set ``J5 holds to be`` a belief value derived from gmeow:standpointModality —
    ``true`` (unequivocal), ``probable``, ``possible`` (conceivable), or ``false``
    (refuted). Because the value is explicit, a DENIAL is carried faithfully and the
    proposition is never asserted as a fact — GMEOW is thereby at least as expressive
    as CRMinf. Fixed transformation; the ``.rq`` is generated, never hand-edited.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    value = (
        '    BIND(IF(!BOUND(?mod), "true",'
        ' IF(?mod = gmeow:refuted, "false",'
        ' IF(?mod = gmeow:conceivable, "possible",'
        ' IF(?mod = gmeow:probable, "probable", "true")))) AS ?value)\n'
    )
    prop_text = '    BIND(CONCAT(STR(?s), " ", STR(?p), " ", STR(?o)) AS ?propText)\n'
    mint = (
        '    BIND(IRI(CONCAT(STR(?ax), "/argumentation")) AS ?arg)\n'
        '    BIND(IRI(CONCAT(STR(?ax), "/belief")) AS ?belief)\n'
        '    BIND(IRI(CONCAT(STR(?ax), "/proposition")) AS ?prop)\n'
    )
    body = (
        "CONSTRUCT {\n"
        "    ?arg a crminf:I1_Argumentation ;\n"
        "        crm:P14_carried_out_by ?holder ;\n"
        "        crminf:J2_concluded_that ?belief .\n"
        "    ?belief a crminf:I2_Belief ;\n"
        "        crminf:J4_that ?prop .\n"
        "    ?prop a crminf:I4_Proposition_Set ;\n"
        "        crm:P67_refers_to ?s ;\n"
        "        rdf:value ?propText ;\n"
        "        crminf:J5_holds_to_be ?value .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "    OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "    OPTIONAL { ?ax gmeow:standpointModality ?mod }\n"
        f"{holder}{value}{prop_text}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → CRMinf (CIDOC-CRM Argumentation). "
        f"{_GENERATED_BANNER}\n"
        "# Lossless belief projection: each standpoint-indexed statement becomes an\n"
        "# I1 Argumentation (carried out by the standpoint) concluding an I2 Belief\n"
        "# J4 that an I4 Proposition Set J5 holds to be true/probable/possible/false.\n"
        "# The explicit belief value carries DENIAL faithfully (≥ CRMinf); the\n"
        "# proposition is referred to, never asserted as fact.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The PROV-O projection — each standpoint-indexed claim becomes a prov:Entity
#: attributed (prov:qualifiedAttribution) to its standpoint agent. Perspective-
#: preserving (every standpoint retained, none privileged), lossy on the belief
#: value / confidence (carried by the CRMinf + OWL 2 projections).
_STANDPOINT_PROV_QUERY = "queries/projections/standpoint-prov.rq"


def emit_standpoint_prov_sparql() -> str:
    """Render the PROV-O qualified-attribution projection (#43).

    Each reified statement becomes a ``prov:Entity`` (its proposition kept reified,
    never asserted) ``prov:wasAttributedTo`` its standpoint agent, with a
    ``prov:qualifiedAttribution`` node naming the ``prov:agent`` — the standpoint
    (the universal standpoint when unindexed). Every standpoint is retained and
    NONE is privileged; it is lossy only on the belief value (gmeow:standpointModality)
    and confidence, which the CRMinf / Standpoint-OWL 2 projections carry. Fixed
    transformation; the ``.rq`` is generated, never hand-edited.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/attribution")) AS ?attr)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?ax a prov:Entity ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o ;\n"
        "        prov:wasAttributedTo ?holder ;\n"
        "        prov:qualifiedAttribution ?attr .\n"
        "    ?attr a prov:Attribution ;\n"
        "        prov:agent ?holder .\n"
        "    ?holder a prov:Agent .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "    OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        f"{holder}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → PROV-O (qualified attribution). "
        f"{_GENERATED_BANNER}\n"
        "# Perspective-preserving provenance: each reified claim is a prov:Entity\n"
        "# attributed to its standpoint agent (prov:qualifiedAttribution). Every\n"
        "# standpoint retained, none privileged; lossy-drop: belief value (modality)\n"
        "# and confidence dropped — carried by standpoint-crminf.rq / -owl2.rq.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The Web Annotation (OA) projection — each standpoint-indexed claim becomes an
#: oa:Annotation: body = the quoted statement, target = its subject, creator = the
#: standpoint. Perspective-preserving, lossy on the belief value / confidence.
_STANDPOINT_OA_QUERY = "queries/projections/standpoint-oa.rq"


def emit_standpoint_oa_sparql() -> str:
    """Render the W3C Web Annotation (OA) projection (#43).

    Each reified statement becomes an ``oa:Annotation`` whose ``oa:hasBody`` is the
    (still-reified, never-asserted) quoted statement, whose ``oa:hasTarget`` is the
    statement's subject, and whose ``dcterms:creator`` is the standpoint (the
    universal standpoint when unindexed), ``oa:motivatedBy oa:describing``. Every
    standpoint is retained and none is privileged; lossy only on the belief value
    (gmeow:standpointModality) and confidence. Fixed transformation; generated.
    """
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/annotation")) AS ?ann)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?ann a oa:Annotation ;\n"
        "        oa:hasTarget ?s ;\n"
        "        oa:hasBody ?ax ;\n"
        "        oa:motivatedBy oa:describing ;\n"
        "        dcterms:creator ?holder .\n"
        "    ?ax owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "    OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        f"{holder}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → W3C Web Annotation (oa). "
        f"{_GENERATED_BANNER}\n"
        "# Perspective-preserving: each reified claim is an oa:Annotation (body = the\n"
        "# quoted statement, target = its subject, creator = the standpoint). Every\n"
        "# standpoint retained, none privileged; lossy-drop: belief value (modality)\n"
        "# and confidence dropped — carried by standpoint-crminf.rq / -owl2.rq.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


#: The schema.org projection — each (non-denied) standpoint-indexed claim becomes a
#: schema:Claim authored by its standpoint, for the web / fact-check ecosystem. A
#: refuted (denied) claim is excluded (schema:author would misread denial as
#: authorship); denials are carried by the CRMinf projection.
_STANDPOINT_SCHEMA_QUERY = "queries/projections/standpoint-schema.rq"


def emit_standpoint_schema_sparql() -> str:
    """Render the schema.org Claim projection (#43).

    Each reified statement (other than a ``refuted`` denial) becomes a
    ``schema:Claim`` whose ``schema:author`` is the standpoint (the universal
    standpoint when unindexed) and whose ``schema:text`` is the rendered proposition
    — never the asserted base triple. Per-standpoint claims coexist (no single
    ``schema:ClaimReview`` verdict, the false-credibility GMEOW refuses). Denials are
    excluded — `schema:author` would misread them as authorship — and carried by the
    CRMinf projection instead. Perspective-preserving, lossy on the belief value.
    """
    refuted_filter = "    FILTER(!BOUND(?mod) || ?mod != gmeow:refuted)\n"
    holder = "    BIND(COALESCE(?sp, gmeow:universalStandpoint) AS ?holder)\n"
    prop_text = '    BIND(CONCAT(STR(?s), " ", STR(?p), " ", STR(?o)) AS ?propText)\n'
    mint = '    BIND(IRI(CONCAT(STR(?ax), "/claim")) AS ?claim)\n'
    body = (
        "CONSTRUCT {\n"
        "    ?claim a schema:Claim ;\n"
        "        schema:author ?holder ;\n"
        "        schema:text ?propText .\n"
        "}\n"
        "WHERE {\n"
        "    ?ax a owl:Axiom ;\n"
        "        owl:annotatedSource ?s ;\n"
        "        owl:annotatedProperty ?p ;\n"
        "        owl:annotatedTarget ?o .\n"
        "    OPTIONAL { ?ax gmeow:accordingTo ?sp }\n"
        "    OPTIONAL { ?ax gmeow:standpointModality ?mod }\n"
        f"{refuted_filter}{holder}{prop_text}{mint}"
        "}\n"
    )
    header = (
        "# Projection: GMEOW → schema.org Claim. "
        f"{_GENERATED_BANNER}\n"
        "# Web / fact-check ecosystem: each (non-denied) claim is a schema:Claim\n"
        "# authored by its standpoint; per-standpoint claims coexist (no single\n"
        "# ClaimReview verdict). Refuted/denied claims excluded (carried by\n"
        "# standpoint-crminf.rq); lossy-drop: belief value (modality) + confidence.\n"
    )
    return f"{header}{_prefix_block(body)}\n\n{body}"


def emit_sparql(dsl: Dsl, profile: str) -> str:
    """Render the SPARQL CONSTRUCT executor for one profile."""
    templates: list[str] = []
    branches: list[str] = []
    drops: list[str] = []
    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for tmpl in _templates(cell, b):
                if tmpl not in templates:
                    templates.append(tmpl)
            branches.append(_branch(cell, b))
            for d in b.lossy_drops:
                if d not in drops:
                    drops.append(d)
    if not branches:
        raise CompileError(f"no bindings for profile {profile!r}")

    construct = "\n".join(f"    {t}" for t in templates)
    where = "\n    ".join(b if i == 0 else f"UNION {b}" for i, b in enumerate(branches))
    body = f"CONSTRUCT {{\n{construct}\n}}\nWHERE {{\n    {where}\n}}\n"
    header = (
        f"# Projection: GMEOW → pure {profile}. {_GENERATED_BANNER}\n"
        f"# Lossy and directional by design"
        + (f"; drops: {'; '.join(drops)}." if drops else ".")
        + "\n"
    )
    prefixes = _prefix_block(body)
    return f"{header}{prefixes}\n\n{body}"


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


@dataclass(slots=True)
class CompileReport:
    """The outcome of a compile (or --check) run."""

    written: list[Path] = field(default_factory=list)
    drifted: list[str] = field(default_factory=list)


def _artifacts(
    dsl: Dsl, onto: Graph
) -> tuple[dict[str, Graph], dict[str, str], dict[str, str]]:
    """Render every artifact. Returns (rdf_graphs, sparql_texts, sssom_texts)."""
    rdf_graphs: dict[str, Graph] = {f"projections/{_FNO_FILE}": emit_fno(dsl, onto)}
    sparql_texts: dict[str, str] = {}
    for profile in _PROFILES:
        rdf_graphs[f"projections/{profile}.edoal.ttl"] = emit_edoal(dsl, profile)
        sparql_texts[f"queries/projections/{profile}.rq"] = emit_sparql(dsl, profile)
    sparql_texts[_STANDPOINT_OWL2_QUERY] = emit_standpoint_owl2_sparql()
    sparql_texts[_STANDPOINT_CRMINF_QUERY] = emit_standpoint_crminf_sparql()
    sparql_texts[_STANDPOINT_PROV_QUERY] = emit_standpoint_prov_sparql()
    sparql_texts[_STANDPOINT_OA_QUERY] = emit_standpoint_oa_sparql()
    sparql_texts[_STANDPOINT_SCHEMA_QUERY] = emit_standpoint_schema_sparql()
    sssom_texts = {f"mappings/{file}": text for file, text in emit_sssom(dsl).items()}
    return rdf_graphs, sparql_texts, sssom_texts


def _write_tree(
    root: Path,
    rdf_graphs: dict[str, Graph],
    sparql_texts: dict[str, str],
    sssom_texts: dict[str, str],
) -> list[Path]:
    written: list[Path] = []
    for rel, graph in rdf_graphs.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        # Normalise the trailing newline so the pre-commit end-of-file fixer
        # never re-touches a generated file.
        turtle = graph.serialize(format="turtle").rstrip("\n") + "\n"
        path.write_text(turtle, encoding="utf-8")
        written.append(path)
    for rel, text in {**sparql_texts, **sssom_texts}.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def _run_invariants(root: Path) -> list[str]:
    """Run the three projection-lint invariants against a rendered tree."""
    # transforms.fno.ttl is hand-authored — copy it in so the FnO lint sees it.
    shutil.copy2(
        PROJECTIONS_DIR / _TRANSFORMS_FILE, root / "projections" / _TRANSFORMS_FILE
    )
    proj = root / "projections"
    queries = root / "queries" / "projections"
    maps = root / "mappings"
    return [
        *fno_type_mismatches(proj),
        *fno_reference_integrity(proj),
        *projection_spec_drift(proj, queries, maps),
    ]


def _committed_paths() -> dict[str, Path]:
    paths: dict[str, Path] = {f"projections/{_FNO_FILE}": PROJECTIONS_DIR / _FNO_FILE}
    for profile in _PROFILES:
        paths[f"projections/{profile}.edoal.ttl"] = (
            PROJECTIONS_DIR / f"{profile}.edoal.ttl"
        )
        paths[f"queries/projections/{profile}.rq"] = (
            PROJECTION_QUERY_DIR / f"{profile}.rq"
        )
    paths[_STANDPOINT_OWL2_QUERY] = PROJECTION_QUERY_DIR / "standpoint-owl2.rq"
    paths[_STANDPOINT_CRMINF_QUERY] = PROJECTION_QUERY_DIR / "standpoint-crminf.rq"
    paths[_STANDPOINT_PROV_QUERY] = PROJECTION_QUERY_DIR / "standpoint-prov.rq"
    paths[_STANDPOINT_OA_QUERY] = PROJECTION_QUERY_DIR / "standpoint-oa.rq"
    paths[_STANDPOINT_SCHEMA_QUERY] = PROJECTION_QUERY_DIR / "standpoint-schema.rq"
    return paths


def compile_all(check: bool = False) -> CompileReport:
    """Compile the DSL to all four artifacts, lint, then write in-place (or --check)."""
    dsl = load_dsl()
    onto = load_merged_graph(include_imports=False)
    rdf_graphs, sparql_texts, sssom_texts = _artifacts(dsl, onto)

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        _write_tree(root, rdf_graphs, sparql_texts, sssom_texts)
        problems = _run_invariants(root)
        if problems:
            raise CompileError(
                "compiler output violates projection invariants:\n  "
                + "\n  ".join(problems)
            )
        sssom_problems = _validate_sssom(sssom_texts)
        if sssom_problems:
            raise CompileError(
                "SSSOM validation failed:\n  " + "\n  ".join(sssom_problems)
            )
        if check:
            return CompileReport(drifted=_drift(root))

    written = _write_tree(PROJECTIONS_DIR.parent, rdf_graphs, sparql_texts, sssom_texts)
    return CompileReport(written=written)


def _drift(root: Path) -> list[str]:
    """Compare a freshly-rendered tree against the committed artifacts."""
    drifted: list[str] = []
    committed = _committed_paths()
    # RDF artifacts → isomorphism; SPARQL/TSV → bytes.
    for rel, path in committed.items():
        fresh = root / rel
        if not path.exists():
            drifted.append(f"{rel} (missing committed file)")
            continue
        if rel.endswith(".ttl"):
            a, b = Graph().parse(path), Graph().parse(fresh)
            if not isomorphic(a, b):
                drifted.append(rel)
        else:
            if path.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                drifted.append(rel)
    fresh_sssom = {p.name for p in (root / "mappings").glob("*.sssom.tsv")}
    for name in sorted(fresh_sssom):
        committed_tsv = MAPPINGS_DIR / name
        if not committed_tsv.exists() or committed_tsv.read_text(encoding="utf-8") != (
            root / "mappings" / name
        ).read_text(encoding="utf-8"):
            drifted.append(f"mappings/{name}")
    # Orphans: a committed SSSOM file the DSL no longer produces (e.g. after a
    # greenfield deletion of its source) must be flagged, or it sits stale.
    for committed_tsv in sorted(MAPPINGS_DIR.glob("*.sssom.tsv")):
        if committed_tsv.name not in fresh_sssom:
            drifted.append(
                f"mappings/{committed_tsv.name} (orphaned — not produced by the DSL)"
            )
    return drifted
