"""Compile the GMEOW mapping DSL into the four standard alignment artifacts.

``gmeow compile-mappings`` renders, from the single authoring source in
``mapping-dsl/``:

* ``mappings/*.sssom.tsv`` — SSSOM 1:1 term-equivalence rows;
* ``projections/*.edoal.ttl`` — EDOAL complex-alignment cells (with ``edoal:measure``);
* ``projections/functions.fno.ttl`` — the FnO transform catalog, its parameter
  ``fno:type`` DERIVED from each predicate's ontology ``rdfs:range`` (so the
  type-mismatch bug class is structurally impossible);
* ``queries/projections/*.rq`` — the executable SPARQL CONSTRUCT branches.

Before writing anything, the compiler renders the artifacts to a temporary tree
and runs the three :mod:`gmeow_tools.projection_lint` cross-layer invariants on
them; a violation aborts the compile (it can never reach disk). ``--check``
renders to a temp tree and diffs it against the committed files (RDF by graph
isomorphism, TSV/SPARQL by bytes), reporting any drift without writing.
"""

from __future__ import annotations

import shutil
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

from rdflib import RDF, RDFS, BNode, Graph, Literal, URIRef
from rdflib.collection import Collection
from rdflib.compare import isomorphic
from rdflib.namespace import Namespace
from rdflib.term import Node

from gmeow_tools.config import (
    MAPPINGS_DIR,
    ONTOLOGY_IRI,
    PREFIXES,
    PROJECTION_QUERY_DIR,
    PROJECTIONS_DIR,
    RELEASE_DATE,
    VERSION,
)
from gmeow_tools.graph import bind_prefixes, load_merged_graph
from gmeow_tools.mapping_dsl import (
    Atom,
    CompileError,
    Dsl,
    MappingPattern,
    MappingSet,
    OptionalGroup,
    ProfileBinding,
    ProjectionCell,
    curie,
    load_dsl,
    render_expr,
    sparql_string,
)
from gmeow_tools.projection_lint import (
    fno_reference_integrity,
    fno_type_mismatches,
    projection_spec_drift,
)

GM = Namespace(PREFIXES["gmeow"])
FNO = Namespace(PREFIXES["fno"])
FNOM = Namespace(PREFIXES["fnom"])
ALIGN = Namespace(PREFIXES["align"])
EDOAL = Namespace(PREFIXES["edoal"])
DCTERMS = Namespace(PREFIXES["dcterms"])

#: The four projection profiles and the FnO catalog file name.
_PROFILES = ("schema-org", "vcard", "foaf", "geosparql")
_FNO_FILE = "functions.fno.ttl"
#: Hand-authored FnO file the compiler reads (for the lint) but never writes.
_TRANSFORMS_FILE = "transforms.fno.ttl"

_GENERATED_BANNER = (
    "GENERATED by `gmeow compile-mappings` from mapping-dsl/ — DO NOT EDIT."
)


# --------------------------------------------------------------------------- #
# FnO emitter
# --------------------------------------------------------------------------- #


def _param_iri(predicate: URIRef) -> URIRef:
    local = str(predicate).rsplit("/", 1)[-1].rsplit("#", 1)[-1]
    return URIRef(GM + "param" + local[:1].upper() + local[1:])


def _output_iri(fn: URIRef) -> URIRef:
    local = str(fn).rsplit("/", 1)[-1].rsplit("#", 1)[-1]
    stem = local[2:] if local.startswith("fn") else local
    return URIRef(GM + "out" + stem)


def emit_fno(dsl: Dsl, onto: Graph) -> Graph:
    """Render the FnO function catalog; param fno:type derived from rdfs:range."""
    graph = Graph()
    bind_prefixes(graph)
    onto_iri = URIRef(ONTOLOGY_IRI)
    doc = URIRef(ONTOLOGY_IRI + "/projections/functions")
    graph.add((doc, RDF.type, URIRef(PREFIXES["owl"] + "Ontology")))
    graph.add((doc, RDFS.label, Literal("GMEOW projection functions (FnO)", lang="en")))
    graph.add((doc, DCTERMS.isPartOf, onto_iri))
    graph.add((doc, RDFS.comment, Literal(_GENERATED_BANNER, lang="en")))

    # Which profiles use each transform (+ ALL cells per (transform, profile) — a
    # transform can fan out to several cells, e.g. fnHonorificToAffix → prefix and
    # suffix — so the fnom mapping must aggregate every cell's var bindings).
    used_by: dict[URIRef, list[str]] = {}
    transform_cells: dict[tuple[URIRef, str], list[ProjectionCell]] = {}
    for cell in dsl.projections:
        for b in cell.bindings:
            if b.transform is not None:
                used_by.setdefault(b.transform, [])
                if b.profile not in used_by[b.transform]:
                    used_by[b.transform].append(b.profile)
                transform_cells.setdefault((b.transform, b.profile), []).append(cell)

    params_emitted: dict[URIRef, URIRef] = {}
    for fn_iri in sorted(dsl.functions, key=str):
        fn = dsl.functions[fn_iri]
        graph.add((fn_iri, RDF.type, FNO.Function))
        graph.add((fn_iri, RDFS.label, Literal(fn.label, lang="en")))
        if fn.description:
            graph.add((fn_iri, DCTERMS.description, Literal(fn.description, lang="en")))
        profiles = used_by.get(fn_iri) or ["schema-org"]
        graph.add(
            (
                fn_iri,
                RDFS.seeAlso,
                URIRef(f"{ONTOLOGY_IRI}/queries/projections/{profiles[0]}.rq"),
            )
        )
        # expects (required first, then optional), each param derives fno:type.
        expects: list[URIRef] = []
        for predicate, required in [
            *[(p, True) for p in fn.inputs],
            *[(p, False) for p in fn.optional_inputs],
        ]:
            param = _param_iri(predicate)
            # The derived fno:type is the whole point — refuse to emit a param
            # whose source predicate has no ontology range (the type mismatch
            # bug class would otherwise move from "wrong type" to "missing type").
            rng = onto.value(predicate, RDFS.range)
            if not isinstance(rng, URIRef):
                raise CompileError(
                    f"{fn_iri}: input {predicate} has no rdfs:range — "
                    "cannot derive its fno:type"
                )
            prior = params_emitted.get(param)
            if prior is not None and prior != predicate:
                raise CompileError(
                    f"param IRI collision: {param} is minted from both "
                    f"{prior} and {predicate}"
                )
            expects.append(param)
            if param not in params_emitted:
                params_emitted[param] = predicate
                graph.add((param, RDF.type, FNO.Parameter))
                graph.add((param, FNO.predicate, predicate))
                graph.add((param, FNO.type, rng))
                graph.add((param, FNO.required, Literal(required)))
        _attach_list(graph, fn_iri, FNO.expects, expects)
        out = _output_iri(fn_iri)
        graph.add((out, RDF.type, FNO.Output))
        graph.add((out, FNO.predicate, fn.output))
        graph.add((out, FNO.type, fn.output_type))
        _attach_list(graph, fn_iri, FNO.returns, [out])

    _emit_fnom(graph, dsl, used_by, transform_cells)
    return graph


def _camel(text: str) -> str:
    return "".join(p.capitalize() for p in text.replace("_", "-").split("-"))


def _impl_iri(profile: str) -> URIRef:
    return URIRef(GM + "impl" + _camel(profile))


def _var_for_predicate(cell: ProjectionCell, predicate: URIRef) -> str | None:
    """The SPARQL object variable an atom binds for ``predicate`` (or None).

    Matches a plain-predicate atom, and an alternation-path atom one of whose
    alternatives is the predicate (e.g. ``hasAppellation`` inside
    ``hasAppellation|hasName`` → the appellation variable).
    """
    for atom in _flatten_atoms(cell.pattern.atoms):
        if atom.object_var is None:
            continue
        if atom.predicate == predicate or predicate in atom.path_alts:
            return atom.object_var
    return None


def _output_var(cell: ProjectionCell) -> str | None:
    """The SPARQL variable a cell's output value binds to.

    The pattern's ``value`` for a single-value projection; for a structural
    (templateAtoms) transform with no value var, the last derived ``BIND`` var
    (the composed/retagged literal — e.g. the WKT, the address label).
    """
    if cell.pattern.value is not None:
        return cell.pattern.value
    if cell.pattern.binds:
        return cell.pattern.binds[-1].var
    return None


def _emit_fnom(
    graph: Graph,
    dsl: Dsl,
    used_by: dict[URIRef, list[str]],
    transform_cells: dict[tuple[URIRef, str], list[ProjectionCell]],
) -> None:
    """Emit fno:Implementation + fno:Mapping linking each function to its SPARQL.

    The FnO mapping vocabulary (fnom) makes the function self-describing about HOW
    it executes: one fno:Implementation per profile .rq, and one fno:Mapping per
    (function, profile) binding each parameter/output to the SPARQL variable that
    realises it (a PropertyParameterMapping — a SPARQL var is a named property).
    A transform may fan out to several cells in a profile (e.g. honorific →
    prefix and suffix), so the bindings are aggregated across every such cell.
    """
    impl_emitted: set[str] = set()
    for fn_iri in sorted(dsl.functions, key=str):
        fn = dsl.functions[fn_iri]
        out_node = _output_iri(fn_iri)
        for profile in used_by.get(fn_iri, []):
            impl = _impl_iri(profile)
            if profile not in impl_emitted:
                impl_emitted.add(profile)
                graph.add((impl, RDF.type, FNO.Implementation))
                graph.add(
                    (impl, DCTERMS["format"], Literal("application/sparql-query"))
                )
                graph.add(
                    (
                        impl,
                        RDFS.seeAlso,
                        URIRef(f"{ONTOLOGY_IRI}/queries/projections/{profile}.rq"),
                    )
                )
            cells = transform_cells.get((fn_iri, profile), [])
            # Aggregate every cell's parameter/output variable bindings.
            param_vars: dict[URIRef, set[str]] = {}
            out_vars: set[str] = set()
            for cell in cells:
                for predicate in (*fn.inputs, *fn.optional_inputs):
                    var = _var_for_predicate(cell, predicate)
                    if var is not None:
                        param_vars.setdefault(_param_iri(predicate), set()).add(var)
                out_var = _output_var(cell)
                if out_var is not None:
                    out_vars.add(out_var)

            mapping = BNode()
            graph.add((mapping, RDF.type, FNO.Mapping))
            graph.add((mapping, FNO.function, fn_iri))
            graph.add((mapping, FNO.implementation, impl))
            for param in sorted(param_vars, key=str):
                for var in sorted(param_vars[param]):
                    pmap = BNode()
                    graph.add((pmap, RDF.type, FNOM.PropertyParameterMapping))
                    graph.add((pmap, FNOM.functionParameter, param))
                    graph.add((pmap, FNOM.implementationProperty, Literal(var)))
                    graph.add((mapping, FNO.parameterMapping, pmap))
            for var in sorted(out_vars):
                rmap = BNode()
                graph.add((rmap, RDF.type, FNOM.DefaultReturnMapping))
                graph.add((rmap, FNOM.functionOutput, out_node))
                graph.add((rmap, FNOM.implementationProperty, Literal(var)))
                graph.add((mapping, FNO.returnMapping, rmap))


def _attach_list(
    graph: Graph, subject: Node, predicate: URIRef, items: Sequence[Node]
) -> None:
    """Attach an rdf:List of items to subject via predicate."""
    head = BNode()
    Collection(graph, head, list(items))
    graph.add((subject, predicate, head))


# --------------------------------------------------------------------------- #
# EDOAL emitter
# --------------------------------------------------------------------------- #

_EDOAL_KIND = {
    "class": EDOAL.Class,
    "relation": EDOAL.Relation,
    "property": EDOAL.Property,
}


def _edoal_entity(graph: Graph, term: URIRef, kind: str) -> BNode:
    node = BNode()
    graph.add((node, RDF.type, _EDOAL_KIND[kind]))
    graph.add((node, EDOAL.uri, term))
    return node


def _edoal_restriction(
    graph: Graph, source: URIRef, attr: URIRef, value: URIRef
) -> BNode:
    cls = BNode()
    graph.add((cls, RDF.type, EDOAL.Class))
    restriction = BNode()
    graph.add((restriction, RDF.type, EDOAL.AttributeValueRestriction))
    on_attr = BNode()
    graph.add((on_attr, RDF.type, EDOAL.Relation))
    graph.add((on_attr, EDOAL.uri, attr))
    graph.add((restriction, EDOAL.onAttribute, on_attr))
    graph.add((restriction, EDOAL.comparator, EDOAL.equals))
    val = BNode()
    graph.add((val, EDOAL.uri, value))
    graph.add((restriction, EDOAL.value, val))
    base = _edoal_entity(graph, source, "class")
    _attach_list(graph, cls, EDOAL["and"], [base, restriction])
    return cls


def _flatten_atoms(items: tuple[Atom | OptionalGroup, ...]) -> list[Atom]:
    """Flatten a pattern's items (recursing OPTIONAL groups) to bare atoms."""
    out: list[Atom] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.extend(_flatten_atoms(item.items))
        else:
            out.append(item)
    return out


def _nav_edges(pattern: MappingPattern) -> list[tuple[str, str, Atom]]:
    """Navigation edges (subjVar, objVar, atom): atoms relating two variables."""
    edges: list[tuple[str, str, Atom]] = []
    for atom in _flatten_atoms(pattern.atoms):
        has_pred = atom.predicate is not None or atom.path is not None or atom.path_alts
        if atom.object_var is not None and has_pred:
            edges.append((atom.subject_var, atom.object_var, atom))
    return edges


def _find_var_path(
    edges: list[tuple[str, str, Atom]], anchor: str, value: str
) -> list[tuple[Atom, bool]] | None:
    """BFS a simple variable path anchor→value; steps carry a forward/inverse flag."""
    from collections import deque

    adj: dict[str, list[tuple[str, Atom, bool]]] = {}
    for subj, obj, atom in edges:
        adj.setdefault(subj, []).append((obj, atom, True))
        adj.setdefault(obj, []).append((subj, atom, False))
    queue: deque[tuple[str, list[tuple[Atom, bool]]]] = deque([(anchor, [])])
    seen = {anchor}
    while queue:
        node, steps = queue.popleft()
        if node == value:
            return steps
        for nbr, atom, forward in adj.get(node, []):
            if nbr not in seen:
                seen.add(nbr)
                queue.append((nbr, [*steps, (atom, forward)]))
    return None


def _edoal_relation_step(graph: Graph, atom: Atom, forward: bool) -> BNode:
    """Render one navigation step as an EDOAL relation (inverse when backward)."""
    if atom.path_alts:
        if len(atom.path_alts) == 1:
            base = _edoal_entity(graph, atom.path_alts[0], "relation")
        else:
            # An alternation of relations: EDOAL edoal:or over the alternatives
            # (validator-safe; the executor still matches `a|b`).
            base = BNode()
            graph.add((base, RDF.type, EDOAL.Relation))
            _attach_list(
                graph,
                base,
                EDOAL["or"],
                [_edoal_entity(graph, a, "relation") for a in atom.path_alts],
            )
    elif atom.predicate is not None:
        base = _edoal_entity(graph, atom.predicate, "relation")
    else:  # an opaque seq/zero-or-more path — degrade to a commented relation node
        base = BNode()
        graph.add((base, RDF.type, EDOAL.Relation))
        graph.add((base, RDFS.comment, Literal(atom.path or "path")))
    if forward:
        return base
    inverse = BNode()
    graph.add((inverse, RDF.type, EDOAL.Relation))
    graph.add((inverse, EDOAL.inverse, base))
    return inverse


def _edoal_path(graph: Graph, pattern: MappingPattern) -> BNode | None:
    """Derive entity1 as the anchor→value relation path (compose/inverse), or None."""
    if pattern.value is None:
        return None
    steps = _find_var_path(_nav_edges(pattern), pattern.anchor, pattern.value)
    if not steps:
        return None
    relations = [_edoal_relation_step(graph, atom, fwd) for atom, fwd in steps]
    if len(relations) == 1:
        return relations[0]
    compose = BNode()
    graph.add((compose, RDF.type, EDOAL.Relation))
    _attach_list(graph, compose, EDOAL.compose, relations)
    return compose


def emit_edoal(dsl: Dsl, profile: str) -> Graph:
    """Render the EDOAL alignment for one profile."""
    graph = Graph()
    bind_prefixes(graph)
    align = URIRef(f"{ONTOLOGY_IRI}/projections/{profile}")
    graph.add((align, RDF.type, ALIGN.Alignment))
    graph.add((align, RDFS.label, Literal(f"GMEOW → {profile} (EDOAL)", lang="en")))
    graph.add((align, DCTERMS.isPartOf, URIRef(ONTOLOGY_IRI)))
    graph.add((align, RDFS.comment, Literal(_GENERATED_BANNER, lang="en")))
    graph.add((align, ALIGN.level, Literal("2EDOAL")))
    for n, name in ((ALIGN.onto1, "GMEOW"), (ALIGN.onto2, profile)):
        onto = BNode()
        graph.add((onto, RDF.type, ALIGN.Ontology))
        formalism = BNode()
        graph.add((formalism, ALIGN.name, Literal(name)))
        graph.add((onto, ALIGN.formalism, formalism))
        graph.add((align, n, onto))

    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for map_cell in _edoal_cells(graph, cell, b):
                graph.add((align, ALIGN.map, map_cell))
    return graph


def _edoal_cells(graph: Graph, cell: ProjectionCell, b: ProfileBinding) -> list[BNode]:
    """Return the EDOAL align:Cell node(s) for one binding (0, 1, or N)."""
    pattern = cell.pattern
    cells: list[BNode] = []

    def _cell(entity1: Node, entity2: Node, label: str) -> BNode:
        node = BNode()
        graph.add((node, RDF.type, ALIGN.Cell))
        graph.add((node, RDFS.label, Literal(label, lang="en")))
        graph.add((node, ALIGN.entity1, entity1))
        graph.add((node, ALIGN.entity2, entity2))
        graph.add((node, ALIGN.relation, Literal(b.relation)))
        if b.transform is not None:
            trans = BNode()
            graph.add((trans, RDFS.seeAlso, b.transform))
            graph.add((node, EDOAL.transformation, trans))
        if b.confidence is not None:
            graph.add((node, EDOAL.measure, Literal(b.confidence)))
        return node

    if b.value_class_map:
        if pattern.edoal_source is None:
            raise CompileError(f"{cell.iri}: value-class map needs edoalSource")
        for vc in b.value_class_map:
            entity1 = _edoal_restriction(
                graph, pattern.edoal_source, _attr_of(pattern), vc.when_value
            )
            entity2 = _edoal_entity(graph, vc.to_class, "class")
            cells.append(
                _cell(
                    entity1,
                    entity2,
                    f"{curie(pattern.edoal_source)} "
                    f"[{curie(vc.when_value)}] → {curie(vc.to_class)}",
                )
            )
        return cells

    # entity1: a derived relation path (compose/inverse) when opted in; else the
    # authored salient term; else no cell (structural / SSSOM-backed projection).
    source: Node | None
    if pattern.edoal_path:
        source = _edoal_path(graph, pattern)
        if source is None:
            raise CompileError(f"{cell.iri}: edoalPath set but no anchor→value path")
    elif pattern.edoal_source is not None:
        source = _edoal_entity(graph, pattern.edoal_source, pattern.edoal_source_kind)
    else:
        return cells

    target, target_kind = _edoal_target(b)
    if target is None:
        return cells
    target_entity = _edoal_entity(graph, target, target_kind)
    cells.append(_cell(source, target_entity, cell.label or f"→ {curie(target)}"))
    return cells


def _attr_of(pattern: MappingPattern) -> URIRef:
    """The value->class restriction attribute (the placeType-style predicate)."""
    for atom in _flatten_atoms(pattern.atoms):
        if atom.object_var == pattern.value and atom.predicate is not None:
            return atom.predicate
    raise CompileError("value-class pattern has no value-binding predicate")


def _edoal_target(b: ProfileBinding) -> tuple[URIRef | None, str]:
    if b.edoal_target is not None:
        return b.edoal_target, b.edoal_target_kind or "class"
    if b.to_class is not None:
        return b.to_class, b.edoal_target_kind or "class"
    if b.to_predicate is not None:
        return b.to_predicate, b.edoal_target_kind or "property"
    return None, "property"


# --------------------------------------------------------------------------- #
# SSSOM emitter
# --------------------------------------------------------------------------- #

_DEFAULT_JUSTIFICATION = URIRef(PREFIXES["semapv"] + "ManualMappingCuration")


def _conf(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:g}" if value != int(value) else f"{value:.1f}"


#: SSSOM columns in canonical order; labels are emitted only when populated.
_SSSOM_ORDER = (
    "subject_id",
    "subject_label",
    "predicate_id",
    "object_id",
    "object_label",
    "mapping_justification",
    "confidence",
    "comment",
)
_SSSOM_ALWAYS = frozenset(
    {
        "subject_id",
        "predicate_id",
        "object_id",
        "mapping_justification",
        "confidence",
        "comment",
    }
)


def _sssom_header(meta: MappingSet | None, prefixes: list[str]) -> list[str]:
    """The SSSOM YAML metadata header: set id, license, provenance, curie_map."""
    lines: list[str] = []
    if meta is not None and meta.set_id:
        lines.append(f"# mapping_set_id: {meta.set_id}")
        lines.append(f"# mapping_set_version: {VERSION}")
        lines.append(f"# license: {meta.license}")
    lines.append("# mapping_tool: gmeow compile-mappings")
    lines.append(f"# mapping_tool_version: {VERSION}")
    lines.append(f"# mapping_date: {RELEASE_DATE}")
    if meta is not None and meta.comment:
        lines.append(f"# comment: {meta.comment}")
    lines.append("# curie_map:")
    for prefix in prefixes:
        lines.append(f"#   {prefix}: {PREFIXES[prefix]}")
    return lines


def emit_sssom(dsl: Dsl) -> dict[str, str]:
    """Render every SSSOM TSV file from the term-equivalence cells.

    SSSOM rows are owned exclusively by gmeow:TermEquivalence cells (a 1:1 with
    the rows). Each file carries deterministic provenance metadata + a curie_map
    of the prefixes it uses; subject_label/object_label columns appear only when a
    row populates them.
    """
    rows: dict[str, list[dict[str, str]]] = {}
    for eq in dsl.equivalences:
        rows.setdefault(eq.sssom_file, []).append(
            {
                "subject_id": curie(eq.subject),
                "subject_label": eq.subject_label,
                "predicate_id": curie(eq.predicate),
                "object_id": curie(eq.obj),
                "object_label": eq.object_label,
                "mapping_justification": curie(
                    eq.justification or _DEFAULT_JUSTIFICATION
                ),
                "confidence": _conf(eq.confidence),
                "comment": eq.comment,
            }
        )

    out: dict[str, str] = {}
    for file, file_rows in rows.items():
        meta = dsl.mapping_sets.get(file)
        columns = [
            c
            for c in _SSSOM_ORDER
            if c in _SSSOM_ALWAYS or any(r[c] for r in file_rows)
        ]
        used_prefixes = sorted(
            {
                tok.split(":", 1)[0]
                for r in file_rows
                for tok in (
                    r["subject_id"],
                    r["predicate_id"],
                    r["object_id"],
                    r["mapping_justification"],
                )
                if ":" in tok and tok.split(":", 1)[0] in PREFIXES
            }
        )
        lines = _sssom_header(meta, used_prefixes)
        lines.append("\t".join(columns))
        for r in sorted(
            file_rows,
            key=lambda r: (r["subject_id"], r["predicate_id"], r["object_id"]),
        ):
            lines.append("\t".join(r[c] for c in columns))
        if meta is not None and meta.trailer:
            lines.extend(meta.trailer.splitlines())
        out[file] = "\n".join(lines) + "\n"
    return out


# --------------------------------------------------------------------------- #
# SPARQL emitter
# --------------------------------------------------------------------------- #


def _term(atom: Atom) -> str:
    if atom.object_var is not None:
        return f"?{atom.object_var}"
    if atom.object_value is not None:
        return curie(atom.object_value)
    if atom.object_literal is not None:
        lit = atom.object_literal
        if lit.datatype == URIRef(PREFIXES["xsd"] + "boolean"):
            return "true" if str(lit).lower() in ("true", "1") else "false"
        return sparql_string(str(lit))
    raise CompileError("atom has no object")


def _atom_triple(atom: Atom) -> str:
    subj = f"?{atom.subject_var}"
    if atom.path is not None:
        pred = atom.path
    elif atom.predicate == RDF.type and atom.object_value is not None:
        pred = "a"
    elif atom.predicate is not None:
        pred = curie(atom.predicate)
    else:
        raise CompileError(f"atom on ?{atom.subject_var} has no predicate/path")
    return f"{subj} {pred} {_term(atom)} ."


def _class_var(pattern: MappingPattern) -> str:
    return f"{pattern.value}Class"


def _where_items(
    items: tuple[Atom | OptionalGroup, ...], indent: str = ""
) -> list[str]:
    """Render WHERE items (atoms + nested OPTIONAL groups) at a relative indent."""
    out: list[str] = []
    for item in items:
        if isinstance(item, OptionalGroup):
            out.append(f"{indent}OPTIONAL {{")
            out.extend(_where_items(item.items, indent + "    "))
            out.append(f"{indent}}}")
        else:
            triple = _atom_triple(item)
            wrapped = f"OPTIONAL {{ {triple} }}" if item.optional else triple
            out.append(f"{indent}{wrapped}")
    return out


def _branch(cell: ProjectionCell, b: ProfileBinding) -> str:
    p = cell.pattern
    lines: list[str] = _where_items(p.atoms)
    if b.value_class_map:
        cv = _class_var(p)
        lines.append(f"VALUES ( ?{p.value} ?{cv} ) {{")
        for vc in b.value_class_map:
            lines.append(f"    ( {curie(vc.when_value)} {curie(vc.to_class)} )")
        lines.append("}")
    for mint in p.mints:
        lines.append(f"BIND ( {render_expr(mint.expr)} AS ?{mint.var} )")
    for bind in p.binds:
        lines.append(f"BIND ( {render_expr(bind.expr)} AS ?{bind.var} )")
    for atom in (*p.suppress_when, *p.exclude_when):
        lines.append(f"FILTER NOT EXISTS {{ {_atom_triple(atom)} }}")
    for flt in p.filters:
        lines.append(f"FILTER( {render_expr(flt)} )")
    body = "\n".join(f"        {ln}" for ln in lines)
    return "{\n" + body + "\n    }"


def _templates(cell: ProjectionCell, b: ProfileBinding) -> list[str]:
    p = cell.pattern
    if b.template_atoms:
        return [_atom_triple(a) for a in b.template_atoms]
    if b.value_class_map:
        return [f"?{p.anchor} a ?{_class_var(p)} ."]
    if b.to_class is not None:
        return [f"?{p.anchor} a {curie(b.to_class)} ."]
    if b.to_predicate is not None:
        return [f"?{p.anchor} {curie(b.to_predicate)} ?{p.value} ."]
    raise CompileError(f"{cell.iri}: binding for {b.profile} has no output")


def _prefix_block(text: str) -> str:
    lines = []
    for prefix, ns in PREFIXES.items():
        if f"{prefix}:" in text:
            lines.append(f"PREFIX {prefix}: <{ns}>")
    return "\n".join(lines)


def emit_sparql(dsl: Dsl, profile: str) -> str:
    """Render the SPARQL CONSTRUCT executor for one profile."""
    templates: list[str] = []
    branches: list[str] = []
    drops: list[str] = []
    for cell in dsl.projections:
        for b in cell.bindings:
            if b.profile != profile:
                continue
            for tmpl in _templates(cell, b):
                if tmpl not in templates:
                    templates.append(tmpl)
            branches.append(_branch(cell, b))
            for d in b.lossy_drops:
                if d not in drops:
                    drops.append(d)
    if not branches:
        raise CompileError(f"no bindings for profile {profile!r}")

    construct = "\n".join(f"    {t}" for t in templates)
    where = "\n    ".join(b if i == 0 else f"UNION {b}" for i, b in enumerate(branches))
    body = f"CONSTRUCT {{\n{construct}\n}}\nWHERE {{\n    {where}\n}}\n"
    header = (
        f"# Projection: GMEOW → pure {profile}. {_GENERATED_BANNER}\n"
        f"# Lossy and directional by design"
        + (f"; drops: {'; '.join(drops)}." if drops else ".")
        + "\n"
    )
    prefixes = _prefix_block(body)
    return f"{header}{prefixes}\n\n{body}"


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


@dataclass(slots=True)
class CompileReport:
    """The outcome of a compile (or --check) run."""

    written: list[Path] = field(default_factory=list)
    drifted: list[str] = field(default_factory=list)


def _artifacts(
    dsl: Dsl, onto: Graph
) -> tuple[dict[str, Graph], dict[str, str], dict[str, str]]:
    """Render every artifact. Returns (rdf_graphs, sparql_texts, sssom_texts)."""
    rdf_graphs: dict[str, Graph] = {f"projections/{_FNO_FILE}": emit_fno(dsl, onto)}
    sparql_texts: dict[str, str] = {}
    for profile in _PROFILES:
        rdf_graphs[f"projections/{profile}.edoal.ttl"] = emit_edoal(dsl, profile)
        sparql_texts[f"queries/projections/{profile}.rq"] = emit_sparql(dsl, profile)
    sssom_texts = {f"mappings/{file}": text for file, text in emit_sssom(dsl).items()}
    return rdf_graphs, sparql_texts, sssom_texts


def _write_tree(
    root: Path,
    rdf_graphs: dict[str, Graph],
    sparql_texts: dict[str, str],
    sssom_texts: dict[str, str],
) -> list[Path]:
    written: list[Path] = []
    for rel, graph in rdf_graphs.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        # Normalise the trailing newline so the pre-commit end-of-file fixer
        # never re-touches a generated file.
        turtle = graph.serialize(format="turtle").rstrip("\n") + "\n"
        path.write_text(turtle, encoding="utf-8")
        written.append(path)
    for rel, text in {**sparql_texts, **sssom_texts}.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def _run_invariants(root: Path) -> list[str]:
    """Run the three projection-lint invariants against a rendered tree."""
    # transforms.fno.ttl is hand-authored — copy it in so the FnO lint sees it.
    shutil.copy2(
        PROJECTIONS_DIR / _TRANSFORMS_FILE, root / "projections" / _TRANSFORMS_FILE
    )
    proj = root / "projections"
    queries = root / "queries" / "projections"
    maps = root / "mappings"
    return [
        *fno_type_mismatches(proj),
        *fno_reference_integrity(proj),
        *projection_spec_drift(proj, queries, maps),
    ]


def _committed_paths() -> dict[str, Path]:
    paths: dict[str, Path] = {f"projections/{_FNO_FILE}": PROJECTIONS_DIR / _FNO_FILE}
    for profile in _PROFILES:
        paths[f"projections/{profile}.edoal.ttl"] = (
            PROJECTIONS_DIR / f"{profile}.edoal.ttl"
        )
        paths[f"queries/projections/{profile}.rq"] = (
            PROJECTION_QUERY_DIR / f"{profile}.rq"
        )
    return paths


def compile_all(check: bool = False) -> CompileReport:
    """Compile the DSL to all four artifacts, lint, then write in-place (or --check)."""
    dsl = load_dsl()
    onto = load_merged_graph(include_imports=False)
    rdf_graphs, sparql_texts, sssom_texts = _artifacts(dsl, onto)

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        _write_tree(root, rdf_graphs, sparql_texts, sssom_texts)
        problems = _run_invariants(root)
        if problems:
            raise CompileError(
                "compiler output violates projection invariants:\n  "
                + "\n  ".join(problems)
            )
        if check:
            return CompileReport(drifted=_drift(root))

    written = _write_tree(PROJECTIONS_DIR.parent, rdf_graphs, sparql_texts, sssom_texts)
    return CompileReport(written=written)


def _drift(root: Path) -> list[str]:
    """Compare a freshly-rendered tree against the committed artifacts."""
    drifted: list[str] = []
    committed = _committed_paths()
    # RDF artifacts → isomorphism; SPARQL/TSV → bytes.
    for rel, path in committed.items():
        fresh = root / rel
        if not path.exists():
            drifted.append(f"{rel} (missing committed file)")
            continue
        if rel.endswith(".ttl"):
            a, b = Graph().parse(path), Graph().parse(fresh)
            if not isomorphic(a, b):
                drifted.append(rel)
        else:
            if path.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                drifted.append(rel)
    fresh_sssom = {p.name for p in (root / "mappings").glob("*.sssom.tsv")}
    for name in sorted(fresh_sssom):
        committed_tsv = MAPPINGS_DIR / name
        if not committed_tsv.exists() or committed_tsv.read_text(encoding="utf-8") != (
            root / "mappings" / name
        ).read_text(encoding="utf-8"):
            drifted.append(f"mappings/{name}")
    # Orphans: a committed SSSOM file the DSL no longer produces (e.g. after a
    # greenfield deletion of its source) must be flagged, or it sits stale.
    for committed_tsv in sorted(MAPPINGS_DIR.glob("*.sssom.tsv")):
        if committed_tsv.name not in fresh_sssom:
            drifted.append(
                f"mappings/{committed_tsv.name} (orphaned — not produced by the DSL)"
            )
    return drifted
