"""RDF 1.2 / RDF* codec helpers (Apache Jena — required).

GMEOW is **RDF 1.2 / RDF*-first** (CONSTITUTION Principles 2-3): the statement-level
metadata layer is authored canonically in ``statement-dsl/`` and compiled to two
generated forms — the RDF 1.2 / RDF* serialization (the canonical **lead**
artifact) and the OWL 2 axiom-annotation form (the reasoning-lossless **downcast**
the OWL 2 DL reasoners consume). This module owns the Jena side of that compile:
it cannot be done in pure rdflib because rdflib (7.6) does not yet read or write
RDF 1.2 triple-term syntax, so Apache Jena is the only engine that materializes and
re-reads the triple-term form.

Jena is a **required** tool — RDF 1.2 is a verified, required output, not an
optional add-on. A missing Docker / Jena image is a hard failure
(:func:`~gmeow_tools.runner.run_container` raises
:class:`~gmeow_tools.runner.ToolUnavailableError`): there is no degraded / skip
mode. The orchestration (emit the OWL form, drive this codec, prove the round-trip
lossless, gate drift) lives in :mod:`gmeow_tools.statement_compile`.

Oracle-only note (#667 / Principle 18)
--------------------------------------
This Jena codec is **not** the lead writer and **not** on the normal-use primary
path. As of #667 the **lead** RDF 1.2 producer is the native ``gmeow-rdf`` Rust
codec (``gmeow_rdf.project_statements_rdf12`` / ``normalize_rdf12_to_owl``, driven
by :mod:`gmeow_tools.statement_compile`), so ``make check`` / ``check-generated`` /
``regenerate`` carry **zero Java and zero Docker**. This module survives **only**
as the ``classic-cross-check`` Jena oracle
(:mod:`gmeow_tools.statements_docker_check`): it re-reads the native-written lead
artifact and proves the two engines agree by RDF 1.2 graph isomorphism. It is
never imported on the primary path.
"""

from __future__ import annotations

from pathlib import Path

from rdflib import Graph

from gmeow_tools.config import JENA_IMAGE, PROJECT_ROOT, QUERIES_DIR
from gmeow_tools.graph import bind_prefixes
from gmeow_tools.runner import run_container

#: OWL axiom-annotation downcast → RDF 1.2 / RDF* reifying triples.
PROJECT_QUERY = QUERIES_DIR / "codecs" / "rdf12-project.rq"
#: RDF 1.2 / RDF* → OWL axiom-annotation normal form (the round-trip inverse).
NORMALIZE_QUERY = QUERIES_DIR / "codecs" / "rdf12-to-owl.rq"

#: Header prepended to the emitted RDF 1.2 lead artifact.
_RDF12_BANNER = (
    "# RDF 1.2 / RDF* — GMEOW's canonical statement-level model, the lead\n"
    "# serialization. Generated by `gmeow compile-statements` from statement-dsl/\n"
    "# together with (and verified isomorphic to) the OWL 2 axiom-annotation\n"
    "# downcast the reasoner consumes. DO NOT EDIT — author in statement-dsl/.\n"
)


def _rel(path: Path) -> str:
    """Return a container path (relative to the repo root mounted at /work).

    Jena runs with ``PROJECT_ROOT`` mounted at ``/work``; both the query and the
    data file must live under the repo root to be visible inside the container.
    """
    return str(path.relative_to(PROJECT_ROOT))


def _jena_construct(query: Path, data: Path) -> str:
    """Run a SPARQL 1.2 CONSTRUCT in Jena over ``data``; return Turtle stdout."""
    if not query.exists():
        raise FileNotFoundError(f"query not found: {query}")
    if not data.exists():
        raise FileNotFoundError(f"data not found: {data}")
    result = run_container(
        JENA_IMAGE,
        ["sparql", "--data", _rel(data), "--query", _rel(query), "--results", "ttl"],
        # Jena calls getLocalHost() on init; a resolvable hostname avoids a hard
        # failure under the hermetic --network none (see run_container).
        hostname="localhost",
    )
    return result.stdout


def project_owl_to_rdf12(owl_path: Path, output: Path) -> Path:
    """Materialize the RDF 1.2 / RDF* lead artifact from the OWL downcast.

    Args:
        owl_path: The generated OWL axiom-annotation form (under the repo root).
        output: Destination for the RDF 1.2 Turtle serialization.

    Returns:
        The path to the generated RDF 1.2 artifact.

    Raises:
        ToolUnavailableError: If Docker / the pinned Jena image is unavailable.
    """
    ttl = _jena_construct(PROJECT_QUERY, owl_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    # Normalize the trailing newline so the pre-commit end-of-file fixer never
    # re-touches the committed artifact (the mapping compiler does the same).
    output.write_text(_RDF12_BANNER + ttl.rstrip("\n") + "\n", encoding="utf-8")
    return output


def normalize_rdf12_to_owl(rdf12_path: Path) -> Graph:
    """Normalize an RDF 1.2 file back to the OWL axiom-annotation normal form.

    The inverse of :func:`project_owl_to_rdf12`, used to prove the round-trip
    lossless: the RDF 1.2 form is re-read by Jena into plain-RDF ``owl:Axiom``
    reification, which rdflib *can* compare by isomorphism (it cannot parse the
    RDF 1.2 triple terms directly).

    Args:
        rdf12_path: The RDF 1.2 Turtle file (under the repo root).

    Returns:
        The OWL normal form as an rdflib graph.

    Raises:
        ToolUnavailableError: If Docker / the pinned Jena image is unavailable.
    """
    ttl = _jena_construct(NORMALIZE_QUERY, rdf12_path)
    graph = Graph()
    graph.parse(data=ttl, format="turtle")
    bind_prefixes(graph)
    return graph
