"""Compile the statement DSL → the RDF 1.2 lead artifact + OWL downcast.

``gmeow regenerate`` (statements) renders, from the single authoring source in
``statement-dsl/`` (CONSTITUTION Principles 2-4):

* ``statements/gmeow.rdf12.ttl`` — the RDF 1.2 / RDF* serialization, the canonical
  **lead** artifact (via the native ``gmeow-rdf`` Rust codec — no Jena, no Docker,
  no SPARQL engine; #667);
* ``statements/gmeow-statements.owl.ttl`` — the OWL 2 axiom-annotation form, the
  reasoning-lossless **downcast** the OWL 2 DL reasoners consume.

The OWL form is rendered in pure rdflib (the reifier IRI becomes the named
``owl:Axiom`` node); the RDF 1.2 form is materialized from it natively by
``gmeow_rdf.project_statements_rdf12``. Before writing anything, the compiler
proves the two forms encode the same statement metadata by **round-trip
isomorphism** (the RDF 1.2 form, normalized back to OWL by
``gmeow_rdf.normalize_rdf12_to_owl``, must be isomorphic to the OWL form) — a lossy
emit can never reach disk (CONSTITUTION Principle 7). Apache Jena survives only as
a non-required ``classic-cross-check`` oracle
(:mod:`gmeow_tools.statements_docker_check`).
``--check`` renders to a temp tree and reports drift against the committed
artifacts without writing.

This mirrors the mapping compiler's *author once → verified generated downcasts*
engine (:mod:`gmeow_tools.mapping_compile`), generalized to the metadata layer.
"""

from __future__ import annotations

import tempfile
from collections.abc import Sequence
from pathlib import Path

from gmeow_rdf.compat.rdflib import RDF, Graph
from gmeow_rdf.compat.rdflib.namespace import OWL

from gmeow_tools import diagnostics
from gmeow_tools.config import (
    PROJECT_ROOT,
    STATEMENT_DSL_DIR,
    STATEMENT_OWL_FILE,
    STATEMENT_RDF12_FILE,
)
from gmeow_tools.generator import Generator, rdf_compare, register
from gmeow_tools.graph import bind_prefixes, iter_module_files, load_merged_graph
from gmeow_tools.mapping_dsl import CompileError
from gmeow_tools.rdf_canonical import graphs_isomorphic
from gmeow_tools.statement_dsl import StatementDsl, load_statement_dsl

#: Canonical tool/code namespace for this surface's diagnostics (#809).
TOOL = "statement-compile"

_OWL_BANNER = (
    "# GENERATED by `gmeow regenerate` (statements) from statement-dsl/ "
    "— DO NOT EDIT.\n"
    "# The OWL 2 axiom-annotation downcast of GMEOW's canonical RDF 1.2 "
    "statement metadata; the reasoning-lossless form the OWL 2 DL reasoners "
    "consume (CONSTITUTION Principle 3). Verified isomorphic to "
    "statements/gmeow.rdf12.ttl.\n"
)

_RDF12_BANNER = (
    "# RDF 1.2 / RDF* — GMEOW's canonical statement-level model, the lead\n"
    "# serialization. Generated natively by `gmeow regenerate` (statements) via the\n"
    "# gmeow-rdf Rust codec (no Jena, no Docker) from statement-dsl/, together with\n"
    "# (and verified isomorphic to) the OWL 2 axiom-annotation downcast the reasoner\n"
    "# consumes (CONSTITUTION Principle 7). DO NOT EDIT — author in statement-dsl/.\n"
)


def _write_ttl(graph: Graph, path: Path, banner: str) -> None:
    """Write a graph as Turtle with a generated banner + a normalized newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    turtle = graph.serialize(format="turtle").rstrip("\n") + "\n"
    path.write_text(banner + turtle, encoding="utf-8")


def _project_to_rdf12(owl_path: Path, output: Path) -> Path:
    """Project the OWL downcast → the RDF 1.2 lead artifact natively (gmeow-rdf).

    The native (no Jena, no Docker, no SPARQL) replacement for the former Jena
    codec on the lead-writer path (#667).
    """
    # Deferred import: the gmeow_rdf native ext is a hard requirement of the lead
    # writer, but NOT of this module's pure-rdflib `emit_owl`, which the Jena
    # oracle lane (statements_docker_check) imports without building the ext (#667).
    import gmeow_rdf

    rdf12 = gmeow_rdf.project_statements_rdf12(owl_path.read_text(encoding="utf-8"))
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_RDF12_BANNER + rdf12.rstrip("\n") + "\n", encoding="utf-8")
    return output


def _normalize_to_owl_graph(rdf12_path: Path) -> Graph:
    """Normalize an RDF 1.2 file → the OWL normal form as an rdflib graph (gmeow-rdf).

    rdflib cannot parse RDF 1.2 triple terms, so the native codec emits the plain
    ``owl:Axiom`` normal form rdflib then parses for the isomorphism comparison.
    """
    # Deferred import — see _project_to_rdf12 (keeps emit_owl importable in the
    # Jena oracle lane, which does not build the gmeow_rdf ext; #667).
    import gmeow_rdf

    owl_ttl = gmeow_rdf.normalize_rdf12_to_owl(rdf12_path.read_text(encoding="utf-8"))
    graph = Graph()
    graph.parse(data=owl_ttl, format="turtle")
    bind_prefixes(graph)
    return graph


def _drift(owl_graph: Graph, fresh_rdf12: Path) -> list[str]:
    """Compare freshly-rendered artifacts against the committed ones."""
    drifted: list[str] = []
    if not STATEMENT_OWL_FILE.exists():
        drifted.append(f"{_rel_str(STATEMENT_OWL_FILE)} (missing committed file)")
    elif not graphs_isomorphic(
        Graph().parse(STATEMENT_OWL_FILE, format="turtle"), owl_graph
    ):
        drifted.append(_rel_str(STATEMENT_OWL_FILE))
    if not STATEMENT_RDF12_FILE.exists():
        drifted.append(f"{_rel_str(STATEMENT_RDF12_FILE)} (missing committed file)")
    elif not graphs_isomorphic(
        _normalize_to_owl_graph(STATEMENT_RDF12_FILE),
        _normalize_to_owl_graph(fresh_rdf12),
    ):
        drifted.append(_rel_str(STATEMENT_RDF12_FILE))
    return drifted


class StatementReport:
    """The outcome of a compile (or --check) run."""

    written: list[Path]
    drifted: list[str]

    def __init__(
        self,
        written: list[Path] | None = None,
        drifted: list[str] | None = None,
    ) -> None:
        """Create a report with optional written paths and drift diagnostics."""
        self.written = written or []
        self.drifted = drifted or []


# --------------------------------------------------------------------------- #
# OWL axiom-annotation emitter (pure rdflib — the reasoning downcast)
# --------------------------------------------------------------------------- #


def emit_owl(dsl: StatementDsl) -> Graph:
    """Render the OWL axiom-annotation form: base triple + reified annotations.

    The reifier IRI is reused as the named ``owl:Axiom`` node, which makes the
    OWL ↔ RDF 1.2 correspondence a clean named bijection (no blank-node guessing
    in the round-trip isomorphism).
    """
    graph = Graph()
    bind_prefixes(graph)
    for cell in dsl.cells:
        s, p, o = cell.triple.subject, cell.triple.predicate, cell.triple.obj
        graph.add((s, p, o))
        ax = cell.reifier
        graph.add((ax, RDF.type, OWL.Axiom))
        graph.add((ax, OWL.annotatedSource, s))
        graph.add((ax, OWL.annotatedProperty, p))
        graph.add((ax, OWL.annotatedTarget, o))
        for ann in cell.annotations:
            graph.add((ax, ann.prop, ann.value))
    return graph


def lossless_report(
    owl_graph: Graph,
    rdf12_path: Path,
) -> diagnostics.DiagnosticsReport:
    """Prove the RDF 1.2 form round-trips to the OWL form, as a native report.

    The RDF 1.2 file is normalized back to OWL normal form natively (gmeow-rdf);
    the divergence against the authored OWL graph is then computed **in Rust**
    (``gmeow_validate.check_statement_lossless`` — an oxigraph quad-set diff, not
    rdflib ``graph_diff``). An empty (``ok``) report == lossless; otherwise each
    diverging triple is one ``statement-compile.lossless-round-trip`` finding.
    """
    import gmeow_rdf
    from gmeow_validate import check_statement_lossless

    authored_ttl = owl_graph.serialize(format="turtle")
    normalized_ttl = gmeow_rdf.normalize_rdf12_to_owl(
        rdf12_path.read_text(encoding="utf-8")
    )
    return check_statement_lossless(authored_ttl, normalized_ttl)


def assert_lossless(owl_graph: Graph, rdf12_path: Path) -> list[str]:
    """Prove the RDF 1.2 form round-trips to the OWL form (empty == lossless).

    Thin wrapper over :func:`lossless_report` returning the native report's error
    messages, so the compile path can keep raising ``CompileError`` verbatim.
    """
    return list(lossless_report(owl_graph, rdf12_path).errors)


# --------------------------------------------------------------------------- #
# Canonical diagnostics surface (#809)
# --------------------------------------------------------------------------- #


def compile_diagnostics_report(
    *,
    tool: str = TOOL,
) -> diagnostics.DiagnosticsReport:
    """Run the statement compile checks and project them into one report (#809).

    The dev-gate surface entry (folded into the feedback bundle): it emits the OWL
    downcast, runs the native statement-metadata invariants and the native RDF-1.2
    round-trip lossless check, and unions their findings. Both checks are
    Rust-backed (``gmeow_validate``); this Python is the thin surface. A
    ``CompileError`` from the DSL→OWL compile is surfaced as a single
    ``statement-compile.dsl-error`` finding; any other failure is unexpected and
    propagates (no-optionality — never swallowed into a soft finding).
    """
    from gmeow_validate import check_statement_invariants

    report = diagnostics.report(tool)
    try:
        dsl = load_statement_dsl()
        onto = load_merged_graph(include_imports=False)
        owl = emit_owl(dsl)
        report.extend(
            check_statement_invariants(
                owl.serialize(format="turtle"),
                onto.serialize(format="nt"),
            )
        )
        with tempfile.TemporaryDirectory() as tmp:
            owl_tmp = Path(tmp) / "owl.ttl"
            rdf12_tmp = Path(tmp) / "rdf12.ttl"
            _write_ttl(owl, owl_tmp, _OWL_BANNER)
            _project_to_rdf12(owl_tmp, rdf12_tmp)
            report.extend(lossless_report(owl, rdf12_tmp))
    except CompileError as exc:
        # The DSL→OWL compile is the one EXPECTED structured error this surface
        # exists to report — emit it as a finding (mirrors mapping_compile). Any
        # OTHER failure (missing input, projection error, native crash) is
        # unexpected and MUST hard-fail rather than be swallowed here
        # (no-optionality doctrine).
        report.add(
            diagnostics.finding(
                severity="error",
                code=f"{tool}.dsl-error",
                message=str(exc),
                tool=tool,
            )
        )
    return report


def _rel_str(path: Path) -> str:
    return str(path.relative_to(PROJECT_ROOT))


# --------------------------------------------------------------------------- #
# Registered generator
# --------------------------------------------------------------------------- #


@register
class StatementGenerator(Generator):
    """Compile statement-dsl/ → RDF 1.2 lead artifact + OWL downcast."""

    name: str = "statements"
    #: The canonical internal compilation keeps x-gmeow-* tags (#287 leak gate).
    allows_internal_tags: bool = True

    @property
    def inputs(self) -> Sequence[Path]:
        """Canonical inputs for the statement generator."""
        return [
            *list(STATEMENT_DSL_DIR.glob("*.ttl")),
            PROJECT_ROOT / "ontology" / "gmeow.ttl",
            *iter_module_files(),
            *list((PROJECT_ROOT / "imports").glob("*.ttl")),
        ]

    @property
    def outputs(self) -> Sequence[Path]:
        """Committed outputs for the statement generator."""
        return [STATEMENT_OWL_FILE, STATEMENT_RDF12_FILE]

    def render(self, staging: Path) -> None:
        """Render statement artifacts into the staging tree."""
        dsl = load_statement_dsl()
        onto = load_merged_graph(include_imports=False)

        # Author once → verify natively: emit the OWL downcast first, then run the
        # statement-metadata invariants in Rust (gmeow_validate) over that emitted
        # OWL graph unioned with the ontology — the pure-Python statement_lint was
        # retired in the #630 cutover. Any finding blocks the compile, exactly as
        # the former invariant list did.
        #
        # Deferred import — see _project_to_rdf12: the native ext is a hard
        # requirement of this writer path, but NOT of the module's pure-rdflib
        # emit_owl, which the Jena oracle lane imports without building the ext.
        from gmeow_validate import check_statement_invariants

        owl = emit_owl(dsl)
        report = check_statement_invariants(
            owl.serialize(format="turtle"),
            onto.serialize(format="nt"),
        )
        if not report.ok:
            raise CompileError(
                "statement DSL violates invariants:\n  " + "\n  ".join(report.errors)
            )

        owl_tmp = staging / STATEMENT_OWL_FILE.relative_to(PROJECT_ROOT)
        rdf12_tmp = staging / STATEMENT_RDF12_FILE.relative_to(PROJECT_ROOT)

        _write_ttl(owl, owl_tmp, _OWL_BANNER)

        _project_to_rdf12(owl_tmp, rdf12_tmp)

        lossy = assert_lossless(owl, rdf12_tmp)
        if lossy:
            raise CompileError(
                "RDF 1.2 / OWL round-trip is lossy (emit blocked):\n  "
                + "\n  ".join(lossy)
            )

    def compare(self, fresh: Path, committed: Path) -> list[str]:
        """Use graph isomorphism for OWL; normalize RDF 1.2 natively (gmeow-rdf)."""
        if committed == STATEMENT_OWL_FILE:
            return rdf_compare(fresh, committed)
        # RDF 1.2: normalize both to OWL natively (gmeow-rdf), then isomorphism
        if not committed.exists():
            return [f"{_rel_str(committed)} (missing committed file)"]
        try:
            a = _normalize_to_owl_graph(committed)
            b = _normalize_to_owl_graph(fresh)
        except Exception as exc:
            return [f"{_rel_str(committed)} (normalization error: {exc})"]
        if not graphs_isomorphic(a, b):
            return [f"{_rel_str(committed)}"]
        return []
