"""Compile the statement DSL → the RDF 1.2 lead artifact + OWL downcast.

``gmeow compile-statements`` renders, from the single authoring source in
``statement-dsl/`` (CONSTITUTION Principles 2-4):

* ``statements/gmeow.rdf12.ttl`` — the RDF 1.2 / RDF* serialization, the canonical
  **lead** artifact (via Apache Jena — the only engine that emits triple terms);
* ``statements/gmeow-statements.owl.ttl`` — the OWL 2 axiom-annotation form, the
  reasoning-lossless **downcast** the OWL 2 DL reasoners consume.

The OWL form is rendered in pure rdflib (the reifier IRI becomes the named
``owl:Axiom`` node); the RDF 1.2 form is materialized from it by Jena. Before
writing anything, the compiler proves the two forms encode the same statement
metadata by **round-trip isomorphism** (the RDF 1.2 form, normalized back to OWL by
Jena, must be isomorphic to the OWL form) — a lossy emit can never reach disk
(CONSTITUTION Principle 7). ``--check`` renders to a temp tree and reports drift
against the committed artifacts without writing.

This mirrors the mapping compiler's *author once → verified generated downcasts*
engine (:mod:`gmeow_tools.mapping_compile`), generalized to the metadata layer.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from rdflib import RDF, Graph
from rdflib.compare import graph_diff, isomorphic
from rdflib.namespace import OWL

from gmeow_tools.config import (
    PROJECT_ROOT,
    STATEMENT_OWL_FILE,
    STATEMENT_RDF12_FILE,
    STATEMENTS_DIR,
    gmeow_temp_dir,
    sweep_stale_gmeow_temp_dirs,
)
from gmeow_tools.graph import bind_prefixes, load_merged_graph
from gmeow_tools.mapping_dsl import CompileError
from gmeow_tools.rdf12 import normalize_rdf12_to_owl, project_owl_to_rdf12
from gmeow_tools.statement_dsl import StatementDsl, load_statement_dsl
from gmeow_tools.statement_lint import statement_invariants

_OWL_BANNER = (
    "# GENERATED by `gmeow compile-statements` from statement-dsl/ — DO NOT EDIT.\n"
    "# The OWL 2 axiom-annotation downcast of GMEOW's canonical RDF 1.2 statement\n"
    "# metadata; the reasoning-lossless form the OWL 2 DL reasoners consume\n"
    "# (CONSTITUTION Principle 3). Verified isomorphic to statements/gmeow.rdf12.ttl.\n"
)


# --------------------------------------------------------------------------- #
# OWL axiom-annotation emitter (pure rdflib — the reasoning downcast)
# --------------------------------------------------------------------------- #


def emit_owl(dsl: StatementDsl) -> Graph:
    """Render the OWL axiom-annotation form: base triple + reified annotations.

    The reifier IRI is reused as the named ``owl:Axiom`` node, which makes the
    OWL ↔ RDF 1.2 correspondence a clean named bijection (no blank-node guessing
    in the round-trip isomorphism).
    """
    graph = Graph()
    bind_prefixes(graph)
    for cell in dsl.cells:
        s, p, o = cell.triple.subject, cell.triple.predicate, cell.triple.obj
        graph.add((s, p, o))
        ax = cell.reifier
        graph.add((ax, RDF.type, OWL.Axiom))
        graph.add((ax, OWL.annotatedSource, s))
        graph.add((ax, OWL.annotatedProperty, p))
        graph.add((ax, OWL.annotatedTarget, o))
        for ann in cell.annotations:
            graph.add((ax, ann.prop, ann.value))
    return graph


def _write_ttl(graph: Graph, path: Path, banner: str) -> None:
    """Write a graph as Turtle with a generated banner + a normalized newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    turtle = graph.serialize(format="turtle").rstrip("\n") + "\n"
    path.write_text(banner + turtle, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Round-trip lossless proof + drift (Jena-backed)
# --------------------------------------------------------------------------- #


def _rel_str(path: Path) -> str:
    return str(path.relative_to(PROJECT_ROOT))


def assert_lossless(owl_graph: Graph, rdf12_path: Path) -> list[str]:
    """Prove the RDF 1.2 form round-trips to the OWL form (empty == lossless).

    Normalizes the RDF 1.2 file back to OWL normal form via Jena and compares it
    to the authored OWL graph by isomorphism. A non-empty result lists, with
    direction, the statement-metadata triples that diverged.
    """
    normalized = normalize_rdf12_to_owl(rdf12_path)
    if isomorphic(owl_graph, normalized):
        return []
    _, only_owl, only_rdf12 = graph_diff(owl_graph, normalized)
    problems: list[str] = []
    for triple in sorted(only_owl, key=str):
        problems.append(f"OWL form has, RDF 1.2 lost: {triple}")
    for triple in sorted(only_rdf12, key=str):
        problems.append(f"RDF 1.2 form has, OWL lacks: {triple}")
    return problems


def _drift(owl_graph: Graph, fresh_rdf12: Path) -> list[str]:
    """Compare freshly-rendered artifacts against the committed ones."""
    drifted: list[str] = []
    if not STATEMENT_OWL_FILE.exists():
        drifted.append(f"{_rel_str(STATEMENT_OWL_FILE)} (missing committed file)")
    elif not isomorphic(Graph().parse(STATEMENT_OWL_FILE, format="turtle"), owl_graph):
        drifted.append(_rel_str(STATEMENT_OWL_FILE))
    # RDF 1.2 cannot be isomorphism-checked by rdflib; compare the Jena-normalized
    # OWL forms of the committed and fresh files (semantic, not byte, comparison).
    if not STATEMENT_RDF12_FILE.exists():
        drifted.append(f"{_rel_str(STATEMENT_RDF12_FILE)} (missing committed file)")
    elif not isomorphic(
        normalize_rdf12_to_owl(STATEMENT_RDF12_FILE),
        normalize_rdf12_to_owl(fresh_rdf12),
    ):
        drifted.append(_rel_str(STATEMENT_RDF12_FILE))
    return drifted


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


@dataclass(slots=True)
class StatementReport:
    """The outcome of a compile (or --check) run."""

    written: list[Path] = field(default_factory=list)
    drifted: list[str] = field(default_factory=list)


def compile_statements(check: bool = False) -> StatementReport:
    """Compile statement-dsl/ → RDF 1.2 + OWL downcast; verify, then write/--check.

    Pure-Python invariants run first; the OWL form is emitted in rdflib, the RDF
    1.2 form by Jena, and the round-trip-lossless invariant gates the emit before
    anything is written. Temp artifacts are staged under the repo root so Jena
    (which mounts the root at /work) can read them.

    Raises:
        CompileError: On an invariant violation or a lossy round-trip.
        ToolUnavailableError: If Docker / the pinned Jena image is unavailable.
    """
    sweep_stale_gmeow_temp_dirs()

    dsl = load_statement_dsl()
    onto = load_merged_graph(include_imports=False)
    problems = statement_invariants(dsl, onto)
    if problems:
        raise CompileError(
            "statement DSL violates invariants:\n  " + "\n  ".join(problems)
        )

    owl = emit_owl(dsl)
    with gmeow_temp_dir() as tmp:
        root = Path(tmp)
        owl_tmp = root / "gmeow-statements.owl.ttl"
        _write_ttl(owl, owl_tmp, _OWL_BANNER)
        rdf12_tmp = root / "gmeow.rdf12.ttl"
        project_owl_to_rdf12(owl_tmp, rdf12_tmp)

        lossy = assert_lossless(owl, rdf12_tmp)
        if lossy:
            raise CompileError(
                "RDF 1.2 / OWL round-trip is lossy (emit blocked):\n  "
                + "\n  ".join(lossy)
            )
        if check:
            return StatementReport(drifted=_drift(owl, rdf12_tmp))

        STATEMENTS_DIR.mkdir(parents=True, exist_ok=True)
        _write_ttl(owl, STATEMENT_OWL_FILE, _OWL_BANNER)
        STATEMENT_RDF12_FILE.write_text(
            rdf12_tmp.read_text(encoding="utf-8"), encoding="utf-8"
        )
    return StatementReport(written=[STATEMENT_OWL_FILE, STATEMENT_RDF12_FILE])
