# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: AGPL-3.0-only

# Type stub for the gmeow_slice PyO3 extension (#820 S8).
#
# Signatures transcribed verbatim from crates/slice/src/py.rs — keep in lockstep
# with that file (the ABI source of truth). This is the authoritative native
# slice catalog + ownership/dependency analyzer surface.

from __future__ import annotations

# ── Classes ──────────────────────────────────────────────────────────────────

class ArtifactRecord:
    @property
    def role(self) -> str: ...
    @property
    def logical_path(self) -> str: ...
    @property
    def media_type(self) -> str: ...
    @property
    def raw_digest(self) -> str: ...
    @property
    def semantic_digest(self) -> str | None: ...
    @property
    def content(self) -> bytes: ...

class ManifestView:
    @property
    def slice_iri(self) -> str: ...
    @property
    def label(self) -> str | None: ...
    @property
    def title(self) -> str | None: ...
    @property
    def creators(self) -> list[str]: ...
    @property
    def identifier(self) -> str | None: ...
    @property
    def tier(self) -> str | None: ...
    @property
    def consumers(self) -> list[str]: ...

class SliceRecord:
    @property
    def manifest(self) -> ManifestView: ...
    @property
    def artifacts(self) -> list[ArtifactRecord]: ...

class SliceCatalog:
    @staticmethod
    def discover(root: str) -> SliceCatalog: ...
    def records(self) -> list[SliceRecord]: ...
    def core_slice_iris(self) -> list[str]: ...

class DependencyEdge:
    @property
    def from_slice(self) -> str: ...
    @property
    def to_slice(self) -> str: ...
    @property
    def reconciliation(self) -> str: ...
    @property
    def is_semantic(self) -> bool: ...

class OwnershipReport:
    @property
    def edges(self) -> list[DependencyEdge]: ...
    def ownership_errors(self) -> list[str]: ...
    def has_ownership_defect(self) -> bool: ...

class OwnershipAnalyzer:
    def __init__(self, catalog: SliceCatalog) -> None: ...
    def analyze(self) -> OwnershipReport: ...
    def analysis_graph_turtle(
        self,
        authored_input_text: str,
        compiler_version: str,
        reasoning_profile: str,
    ) -> str: ...
