// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `gmeow gmn` conformance surface — the shipped, checkout-free twin of the
//! GMN-1 gates and the frozen-corpus discharge test.
//!
//! The digest / codec / witness / pack layer built in the codec crate is otherwise
//! reachable only from `crates/pipeline`'s own gates and tests. This module exposes
//! it on the shipped `gmeow` binary so an INDEPENDENT GMN-1 implementation can
//! conform AGAINST the CLI: `gmn digest` prints the codebook Merkle root and an
//! input's content digest, `gmn encode`/`gmn decode` are the two codec legs, and
//! `gmn verify` is the conformance driver over the frozen vector corpus. Every
//! subcommand HARD-FAILS (non-zero exit + a typed diagnostic) on any mismatch —
//! never a soft warning (no-optionality).
//!
//! The GMN codebook + dictionary are resolved from the lang slice's authored
//! `module.ttl` (`gmeow:gmnCodebookCurrent` + `gmeow:gmnDictV3`), mirroring
//! `crates/pipeline/src/stages/gmn1_gate.rs::load_lang_dictionary` — the SAME
//! codebook the production gate, the shipped-projection lint, and the frozen corpus
//! are all pinned against, so the digests this surface prints recompute to the
//! values `manifest.ttl` / `conformance-pack.ttl` declare.

use std::collections::BTreeMap;
use std::path::Path;

use gmeow_cli_core::Reporter;
use gmeow_lang_bridge::{
    CurrentCodebook, Gmn0Model, Gmn1Document, GmnDictionary, codebook_digest, content_digest,
    gmn0_canonically_equal, gmn1_read, gmn1_write, idempotence_check, pack_root,
    per_claim_round_trip_check, resolve_current_codebook,
};
use purrdf::RdfTerm;

use crate::commands::{emit_error, fail};

/// The lang slice's authored `module.ttl` — the source of `gmeow:gmnCodebookCurrent`
/// and `gmeow:gmnDictV3` (the one shipped codebook every leg pins against).
const DEFAULT_LANG_MODULE: &str = "slices/grounding/lang/module.ttl";
/// The frozen GMN-1 conformance-vector corpus root.
const DEFAULT_VECTORS: &str = "slices/grounding/lang/tests/gmn1-vectors";
/// The AUTHORED GMN grammar (pre-render) — the grammar leaf `pack_root` hashes.
const DEFAULT_GRAMMAR: &str = "slices/grounding/lang/grammars/gmn.ebnf";
/// The shipped self-certifying conformance-pack projection (regenerated by the
/// pipeline). When present, `verify` byte-checks the recomputed pack root against
/// its declared `gmeow:gmnPackRoot`; when absent, it recomputes-and-reports.
const DEFAULT_PACK: &str = "generated/projections/lang/gmn1/conformance-pack.ttl";

const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const GMN_PACK_ROOT: &str = "https://blackcatinformatics.ca/gmeow/gmnPackRoot";
const GMN_CODEBOOK_DIGEST: &str = "https://blackcatinformatics.ca/gmeow/gmnCodebookDigest";
const ENFORCES_FAILURE_CLASS: &str = "https://blackcatinformatics.ca/gmeow/enforcesFailureClass";

/// The `gmn digest` output serialization.
#[derive(Debug, Clone, Copy, Default, clap::ValueEnum)]
pub enum DigestFormat {
    /// Two labeled, greppable lines (the default).
    #[default]
    Text,
    /// A single JSON object `{ "codebook_digest": …, "content_digest": … }`.
    Json,
}

/// The `gmn decode` output serialization for the reconstructed GMN-0 model.
#[derive(Debug, Clone, Copy, Default, clap::ValueEnum)]
pub enum DecodeFormat {
    /// RDFC-1.0 canonical N-Quads (the default — the same form the content digest
    /// is taken over).
    #[default]
    Nquads,
    /// Turtle (default graph).
    Turtle,
}

// ── shared resolvers ───────────────────────────────────────────────────────────

/// Read + parse the lang `module.ttl` and resolve the current codebook + the
/// `gmeow:gmnDictV3` dictionary — the exact pair `gmn1_gate.rs` loads. A read /
/// parse / resolution failure is a HARD fail (exit 1), never a degraded default.
fn load_codebook_and_dict(
    reporter: &dyn Reporter,
    lang_module: &Path,
) -> Result<(CurrentCodebook, GmnDictionary), i32> {
    let bytes = std::fs::read(lang_module).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.lang-module-read",
            format!("cannot read {}: {e}", lang_module.display()),
        )
    })?;
    let ds = purrdf::parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.lang-module-parse",
            format!("cannot parse {} as Turtle: {e}", lang_module.display()),
        )
    })?;
    let codebook = resolve_current_codebook(&ds).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.codebook",
            format!("cannot resolve gmeow:gmnCodebookCurrent: {}", e.0),
        )
    })?;
    let dict = GmnDictionary::from_dataset(&ds).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.dictionary",
            format!("cannot load gmeow:gmnDictV3: {}", e.0),
        )
    })?;
    Ok((codebook, dict))
}

/// Parse a user-supplied RDF file as Turtle into the codec's GMN-0 quad model
/// (`Gmn0Model::from_dataset` materializes purrdf's RDF-1.2 reifier/annotation side
/// tables, so a triple-term or by-reference annotation reaches the codec).
fn model_from_ttl(reporter: &dyn Reporter, input: &Path) -> Result<Gmn0Model, i32> {
    let bytes = std::fs::read(input).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.input-read",
            format!("cannot read {}: {e}", input.display()),
        )
    })?;
    let ds = purrdf::parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.input-parse",
            format!("cannot parse {} as Turtle: {e}", input.display()),
        )
    })?;
    Ok(Gmn0Model::from_dataset(&ds))
}

// ── gmn digest ─────────────────────────────────────────────────────────────────

/// `gmeow gmn digest <input.ttl>` — print BOTH the codebook Merkle root
/// (`codebook_digest`, a `blake3:…` value) and the input's content digest
/// (`content_digest`, `blake3:…` over its RDFC-1.0 canonical N-Quads).
pub fn digest(
    reporter: &dyn Reporter,
    input: &Path,
    lang_module: Option<&Path>,
    format: DigestFormat,
) -> i32 {
    let lang_module = lang_module.unwrap_or(Path::new(DEFAULT_LANG_MODULE));
    let (codebook, dict) = match load_codebook_and_dict(reporter, lang_module) {
        Ok(pair) => pair,
        Err(code) => return code,
    };
    let model = match model_from_ttl(reporter, input) {
        Ok(m) => m,
        Err(code) => return code,
    };
    let cb = codebook_digest(&codebook, &dict);
    let cd = content_digest(&model);
    match format {
        DigestFormat::Text => {
            println!("codebook_digest {cb}");
            println!("content_digest {cd}");
        }
        DigestFormat::Json => {
            println!(
                "{}",
                serde_json::json!({ "codebook_digest": cb, "content_digest": cd })
            );
        }
    }
    0
}

// ── gmn encode ─────────────────────────────────────────────────────────────────

/// `gmeow gmn encode <input.ttl>` — parse → `Gmn0Model` → `gmn1_write` against the
/// codebook dictionary → print the GMN-1 document text to stdout. An uncovered /
/// out-of-domain construct HARD-FAILS with the typed `Gmn1Error` (exit 1).
pub fn encode(reporter: &dyn Reporter, input: &Path, lang_module: Option<&Path>) -> i32 {
    let lang_module = lang_module.unwrap_or(Path::new(DEFAULT_LANG_MODULE));
    let (_codebook, dict) = match load_codebook_and_dict(reporter, lang_module) {
        Ok(pair) => pair,
        Err(code) => return code,
    };
    let model = match model_from_ttl(reporter, input) {
        Ok(m) => m,
        Err(code) => return code,
    };
    match gmn1_write(&model, &dict) {
        Ok(doc) => {
            print!("{}", doc.text);
            0
        }
        Err(e) => fail(
            reporter,
            "gmeow-cli.gmn.encode",
            format!("cannot encode {} to GMN-1: {e}", input.display()),
        ),
    }
}

// ── gmn decode ─────────────────────────────────────────────────────────────────

/// `gmeow gmn decode <input.gmn>` — read GMN-1 text → `gmn1_read` → serialize the
/// reconstructed `Gmn0Model` back to canonical N-Quads (or Turtle) on stdout.
///
/// The reader is presented raw text via [`Gmn1Document::from_text`] (an EMPTY
/// out-of-band reference table): a document that names an unresolvable
/// `r_<hash>` by-reference token HARD-FAILS as `lang:GmnUncoveredTerm` — never a
/// silent drop.
pub fn decode(
    reporter: &dyn Reporter,
    input: &Path,
    lang_module: Option<&Path>,
    format: DecodeFormat,
) -> i32 {
    let lang_module = lang_module.unwrap_or(Path::new(DEFAULT_LANG_MODULE));
    let (_codebook, dict) = match load_codebook_and_dict(reporter, lang_module) {
        Ok(pair) => pair,
        Err(code) => return code,
    };
    let text = match std::fs::read_to_string(input) {
        Ok(t) => t,
        Err(e) => {
            return fail(
                reporter,
                "gmeow-cli.gmn.input-read",
                format!("cannot read {}: {e}", input.display()),
            );
        }
    };
    let doc = Gmn1Document::from_text(text);
    let model = match gmn1_read(&doc, &dict) {
        Ok(m) => m,
        Err(e) => {
            return fail(
                reporter,
                "gmeow-cli.gmn.decode",
                format!("cannot decode {} from GMN-1: {e}", input.display()),
            );
        }
    };
    match format {
        DecodeFormat::Nquads => {
            print!("{}", model.canonical_nquads());
            0
        }
        DecodeFormat::Turtle => {
            match purrdf::serialize_dataset(
                &model.to_dataset(),
                "text/turtle",
                purrdf::SerializeGraph::DefaultGraph,
            ) {
                Ok(bytes) => match String::from_utf8(bytes) {
                    Ok(s) => {
                        print!("{s}");
                        0
                    }
                    Err(e) => fail(
                        reporter,
                        "gmeow-cli.gmn.decode-serialize",
                        format!("decoded Turtle is not UTF-8: {e}"),
                    ),
                },
                Err(e) => fail(
                    reporter,
                    "gmeow-cli.gmn.decode-serialize",
                    format!("cannot serialize decoded model to Turtle: {e}"),
                ),
            }
        }
    }
}

// ── gmn verify ─────────────────────────────────────────────────────────────────

/// `gmeow gmn verify` — the conformance driver an external GMN-1 implementation
/// runs against the shipped CLI. Over the frozen vector corpus it proves, for every
/// POSITIVE vector, that `gmn1_write` reproduces the frozen `.gmn` byte-for-byte and
/// that the reconstructed document reads back canonically equal AND passes the
/// per-claim inversion + idempotence witnesses; for every CODEC-tier negative, that
/// the recorded `lang:` failure class is raised; and that the recomputed `pack_root`
/// (and the manifest's pinned codebook digest) equal what the shipped artifacts
/// declare. Any failure prints a diagnostic and EXITS NON-ZERO.
///
/// This is the same corpus + logic as the Task-7 discharge test
/// (`crates/pipeline/tests/gmn1_vectors.rs`), driven from the shipped binary rather
/// than forking a weaker check: the positive tier is discovered from the on-disk
/// `*.in.ttl` inputs, so `--vectors` may point at any copy of the corpus.
pub fn verify(
    reporter: &dyn Reporter,
    vectors: Option<&Path>,
    lang_module: Option<&Path>,
    grammar: Option<&Path>,
    pack: Option<&Path>,
) -> i32 {
    let vectors = vectors.unwrap_or(Path::new(DEFAULT_VECTORS));
    let lang_module = lang_module.unwrap_or(Path::new(DEFAULT_LANG_MODULE));
    let grammar = grammar.unwrap_or(Path::new(DEFAULT_GRAMMAR));
    let pack = pack.unwrap_or(Path::new(DEFAULT_PACK));

    let (codebook, dict) = match load_codebook_and_dict(reporter, lang_module) {
        Ok(pair) => pair,
        Err(code) => return code,
    };

    let mut failures: Vec<String> = Vec::new();
    let mut positives = 0usize;
    let mut negatives = 0usize;

    // ── (A) positive vectors: byte-frozen + witnessed ──
    let stems = match positive_stems(reporter, vectors) {
        Ok(s) => s,
        Err(code) => return code,
    };
    if stems.is_empty() {
        return fail(
            reporter,
            "gmeow-cli.gmn.verify.empty-corpus",
            format!(
                "no *.in.ttl positive vectors under {} — nothing to conform against",
                vectors.display()
            ),
        );
    }
    for stem in &stems {
        let in_ttl = vectors.join(format!("{stem}.in.ttl"));
        let model = match model_from_ttl(reporter, &in_ttl) {
            Ok(m) => m,
            Err(code) => return code,
        };
        let doc = match gmn1_write(&model, &dict) {
            Ok(d) => d,
            Err(e) => {
                failures.push(format!("positive {stem}: gmn1_write failed: {e}"));
                continue;
            }
        };
        let frozen_path = vectors.join(format!("{stem}.gmn"));
        let frozen = match std::fs::read(&frozen_path) {
            Ok(b) => b,
            Err(e) => {
                failures.push(format!(
                    "positive {stem}: frozen {} unreadable: {e}",
                    frozen_path.display()
                ));
                continue;
            }
        };
        if doc.text.as_bytes() != frozen.as_slice() {
            failures.push(format!(
                "positive {stem}: gmn1_write output differs from frozen {stem}.gmn (byte mismatch)"
            ));
            continue;
        }
        let back = match gmn1_read(&doc, &dict) {
            Ok(b) => b,
            Err(e) => {
                failures.push(format!(
                    "positive {stem}: gmn1_read of its own output failed: {e}"
                ));
                continue;
            }
        };
        if !gmn0_canonically_equal(&model, &back) {
            failures.push(format!(
                "positive {stem}: reconstructed model is not canonically equal to the source"
            ));
            continue;
        }
        if let Err(e) = per_claim_round_trip_check(&model, &dict) {
            failures.push(format!(
                "positive {stem}: per-claim inversion witness failed: {e}"
            ));
            continue;
        }
        if let Err(e) = idempotence_check(&doc, &dict) {
            failures.push(format!("positive {stem}: idempotence witness failed: {e}"));
            continue;
        }
        positives += 1;
    }

    // ── (B) codec-tier negatives: each raises exactly its recorded class ──
    let neg_dir = vectors.join("negative-codec");
    if neg_dir.is_dir() {
        match expected_negative_classes(reporter, &neg_dir) {
            Ok(expected) => {
                for (file, want_class) in &expected {
                    let path = neg_dir.join(file);
                    let got = if file.ends_with(".gmn") {
                        match std::fs::read_to_string(&path) {
                            Ok(text) => gmn1_read(&Gmn1Document::from_text(text), &dict).err(),
                            Err(e) => {
                                failures.push(format!("negative {file}: unreadable: {e}"));
                                continue;
                            }
                        }
                    } else {
                        match model_from_ttl(reporter, &path) {
                            Ok(model) => gmn1_write(&model, &dict).err(),
                            Err(code) => return code,
                        }
                    };
                    match got {
                        None => failures.push(format!(
                            "negative {file}: expected lang:{want_class} but the codec ACCEPTED it"
                        )),
                        Some(err) => {
                            let got_class = local_name(err.failure_class());
                            if &got_class == want_class {
                                negatives += 1;
                            } else {
                                failures.push(format!(
                                    "negative {file}: expected lang:{want_class}, got lang:{got_class}"
                                ));
                            }
                        }
                    }
                }
            }
            Err(code) => return code,
        }
    }

    // ── (C) codebook digest + pack root recompute-and-assert ──
    let recomputed_digest = codebook_digest(&codebook, &dict);
    // The frozen corpus pins the codebook it was derived against.
    let manifest = vectors.join("manifest.ttl");
    if manifest.is_file() {
        match pinned_literal(reporter, &manifest, GMN_CODEBOOK_DIGEST) {
            Ok(Some(pinned)) if pinned == recomputed_digest => {}
            Ok(Some(pinned)) => failures.push(format!(
                "manifest.ttl pins codebook digest {pinned} but the live carrier recomputes to {recomputed_digest}"
            )),
            Ok(None) => failures.push(
                "manifest.ttl declares no gmeow:gmnCodebookDigest".to_owned(),
            ),
            Err(code) => return code,
        }
    }

    let grammar_bytes = match std::fs::read(grammar) {
        Ok(b) => b,
        Err(e) => {
            return fail(
                reporter,
                "gmeow-cli.gmn.verify.grammar",
                format!("cannot read GMN grammar {}: {e}", grammar.display()),
            );
        }
    };
    let recomputed_root = pack_root(&recomputed_digest, &dict, &grammar_bytes);
    let pack_status: String = if pack.is_file() {
        match pinned_literal(reporter, pack, GMN_PACK_ROOT) {
            Ok(Some(declared)) if declared == recomputed_root => {
                format!("pack-root {recomputed_root} (matches {})", pack.display())
            }
            Ok(Some(declared)) => {
                failures.push(format!(
                    "conformance pack {} declares gmeow:gmnPackRoot {declared} but the parts recompute to {recomputed_root}",
                    pack.display()
                ));
                format!("pack-root {recomputed_root} (MISMATCH vs {declared})")
            }
            Ok(None) => {
                failures.push(format!(
                    "conformance pack {} declares no gmeow:gmnPackRoot",
                    pack.display()
                ));
                format!("pack-root {recomputed_root} (pack declares none)")
            }
            Err(code) => return code,
        }
    } else {
        // No shipped pack in this tree (e.g. a source checkout with no generated
        // fanout yet): recompute-and-report, per Task 8's own guidance.
        format!(
            "pack-root {recomputed_root} (recomputed; no shipped pack at {})",
            pack.display()
        )
    };

    // ── summary + exit ──
    println!("codebook-digest {recomputed_digest}");
    println!("{pack_status}");
    println!("positives {positives}/{}", stems.len());
    println!("negatives {negatives}");
    if failures.is_empty() {
        println!("gmn conformance PASS");
        0
    } else {
        for f in &failures {
            emit_error(reporter, "gmeow-cli.gmn.verify.failure", f.clone());
        }
        fail(
            reporter,
            "gmeow-cli.gmn.verify.failed",
            format!("gmn conformance FAILED with {} failure(s)", failures.len()),
        )
    }
}

// ── small structural helpers ───────────────────────────────────────────────────

fn local_name(iri: &str) -> String {
    iri.rsplit(['/', '#']).next().unwrap_or(iri).to_owned()
}

/// The sorted `<stem>` of every `*.in.ttl` at the corpus root (the positive inputs).
fn positive_stems(reporter: &dyn Reporter, dir: &Path) -> Result<Vec<String>, i32> {
    let mut stems = Vec::new();
    let entries = std::fs::read_dir(dir).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.verify.vectors",
            format!("cannot read vectors dir {}: {e}", dir.display()),
        )
    })?;
    for entry in entries {
        let entry = entry.map_err(|e| {
            fail(
                reporter,
                "gmeow-cli.gmn.verify.vectors",
                format!("dir entry error in {}: {e}", dir.display()),
            )
        })?;
        if let Some(name) = entry.file_name().to_str()
            && let Some(stem) = name.strip_suffix(".in.ttl")
        {
            stems.push(stem.to_owned());
        }
    }
    stems.sort();
    Ok(stems)
}

/// Parse `negative-codec/expected.ttl` into a `filename -> failure-class-local-name` map.
fn expected_negative_classes(
    reporter: &dyn Reporter,
    neg_dir: &Path,
) -> Result<BTreeMap<String, String>, i32> {
    let path = neg_dir.join("expected.ttl");
    let bytes = std::fs::read(&path).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.verify.expected",
            format!("cannot read {}: {e}", path.display()),
        )
    })?;
    let ds = purrdf::parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.verify.expected",
            format!("cannot parse {}: {e}", path.display()),
        )
    })?;
    let mut label: BTreeMap<String, String> = BTreeMap::new();
    let mut class: BTreeMap<String, String> = BTreeMap::new();
    for q in ds.owned_quads() {
        let RdfTerm::BlankNode(subj) = &q.subject else {
            continue;
        };
        match q.predicate.as_str() {
            RDFS_LABEL => {
                if let RdfTerm::Literal(lit) = &q.object {
                    label.insert(subj.clone(), lit.lexical_form.clone());
                }
            }
            ENFORCES_FAILURE_CLASS => {
                if let RdfTerm::Iri(iri) = &q.object {
                    class.insert(subj.clone(), local_name(iri));
                }
            }
            _ => {}
        }
    }
    let mut out = BTreeMap::new();
    for (subj, file) in label {
        if let Some(cls) = class.get(&subj) {
            out.insert(file, cls.clone());
        } else {
            return Err(fail(
                reporter,
                "gmeow-cli.gmn.verify.expected",
                format!("expected.ttl entry {file} has no gmeow:enforcesFailureClass"),
            ));
        }
    }
    Ok(out)
}

/// The single literal lexical value declared for `predicate` anywhere in a parsed
/// Turtle document (the pack / manifest declare exactly one). Returns `None` when
/// the predicate is absent.
fn pinned_literal(
    reporter: &dyn Reporter,
    path: &Path,
    predicate: &str,
) -> Result<Option<String>, i32> {
    let bytes = std::fs::read(path).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.verify.pinned",
            format!("cannot read {}: {e}", path.display()),
        )
    })?;
    // The shipped pack projection is N-Triples on disk; Turtle parses both.
    let ds = purrdf::parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        fail(
            reporter,
            "gmeow-cli.gmn.verify.pinned",
            format!("cannot parse {}: {e}", path.display()),
        )
    })?;
    let mut found: Vec<String> = ds
        .owned_quads()
        .filter(|q| q.predicate == predicate)
        .filter_map(|q| match &q.object {
            RdfTerm::Literal(lit) => Some(lit.lexical_form.clone()),
            _ => None,
        })
        .collect();
    found.sort();
    found.dedup();
    Ok(found.into_iter().next())
}
