// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! CLIF dialect tests (#721): emit-shape, comprehensive IR round-trip, and the
//! production round-trip (the acceptance bar that proves the Exact claim is honest).

use crate::adapter::assert_ir_isomorphic;
use crate::clif::{parse_clif_str, project_clif};
use crate::frontend::parse_logic_str;
use crate::ir::{
    ContextualScope, Correspondence, CorrespondenceRelation, Formula, LogicAxiom, LogicProgram,
    LogicRule, MorphismClass, MorphismKind, ReasoningContract, SemanticProfileId, Term,
};

// The real `logic:` namespace (see `crate::ir::LOGIC_NAMESPACE`); a meta-channel triple
// is only re-classified as a domain axiom when its predicate sits in this namespace, so the
// round-trip fixtures must mint their IRIs here.
const LOGIC: &str = "https://blackcatinformatics.ca/logic/";

fn iri(local: &str) -> String {
    format!("{LOGIC}{local}")
}

/// Build a small program with one rule + a few formulas (quantifier, disjunction, strong
/// negation, sequence marker) + one axiom — the emit-shape fixture.
fn shape_program() -> LogicProgram {
    let axiom = LogicAxiom::ground(iri("a"), iri("knows"), iri("b"), false).expect("axiom");

    let rule = LogicRule::new(
        LogicAxiom::new(
            "?x",
            iri("ancestor"),
            "?z",
            false,
            false,
            ContextualScope::default(),
        )
        .expect("head"),
        vec![
            LogicAxiom::new(
                "?x",
                iri("parent"),
                "?y",
                false,
                false,
                ContextualScope::default(),
            )
            .expect("b1"),
            LogicAxiom::new(
                "?y",
                iri("parent"),
                "?z",
                false,
                false,
                ContextualScope::default(),
            )
            .expect("b2"),
        ],
        vec![("?x".to_owned(), "?z".to_owned())],
        ContextualScope::default(),
    );

    // (forall (?p) (or (mortal ?p) (not (mortal ?p))))  with a sequence marker arg.
    let inner_or = Formula::Or(vec![
        Formula::atom(
            Term::iri(iri("mortal")).unwrap(),
            vec![
                Term::var("p").unwrap(),
                Term::sequence_marker("rest").unwrap(),
            ],
        )
        .unwrap(),
        Formula::Not(Box::new(
            Formula::atom(
                Term::iri(iri("mortal")).unwrap(),
                vec![Term::var("p").unwrap()],
            )
            .unwrap(),
        )),
    ]);
    let formula = Formula::Forall {
        vars: vec!["p".to_owned()],
        body: Box::new(inner_or),
    };

    LogicProgram::new(
        vec![axiom],
        vec![rule],
        Vec::new(),
        Some("urn:test:shape".to_owned()),
    )
    .with_formulas(vec![formula])
}

#[test]
fn emit_shape_contains_idiomatic_forms() {
    let p = shape_program();
    let out = project_clif(&p).content;

    assert!(out.contains(";; GENERATED by"), "banner missing:\n{out}");
    assert!(out.contains("(forall"), "no (forall …):\n{out}");
    assert!(out.contains("(if "), "no (if …) for the rule:\n{out}");
    assert!(
        out.contains("(/= "),
        "no (/=) for the distinct pair:\n{out}"
    );
    assert!(out.contains("(or "), "no (or …):\n{out}");
    assert!(out.contains("(not "), "no (not …):\n{out}");
    assert!(
        out.contains("(seq "),
        "no (seq …) for the sequence marker:\n{out}"
    );
    // The axiom rides the RDF channel after the sentinel.
    assert!(
        out.contains("@@gmeow-rdf-meta@@"),
        "no RDF-meta sentinel for the axiom channel:\n{out}"
    );
}

#[test]
fn comprehensive_round_trip_is_isomorphic() {
    // An axiom, a rule (negated body atom + distinct pair), a full-FOL formula (quantifier
    // + disjunction + sequence marker), plus meta: a reasoning contract and a correspondence.
    let axiom = LogicAxiom::ground(iri("socrates"), iri("isA"), iri("Human"), false).unwrap();

    let rule = LogicRule::new(
        LogicAxiom::new(
            "?x",
            iri("eligible"),
            "?y",
            false,
            false,
            ContextualScope::default(),
        )
        .unwrap(),
        vec![
            LogicAxiom::new(
                "?x",
                iri("member"),
                "?y",
                false,
                false,
                ContextualScope::default(),
            )
            .unwrap(),
            // A negation-as-failure body atom (negated = the 5th arg).
            LogicAxiom::new(
                "?x",
                iri("banned"),
                "?y",
                false,
                true,
                ContextualScope::default(),
            )
            .unwrap(),
        ],
        vec![("?x".to_owned(), "?y".to_owned())],
        ContextualScope::default(),
    );

    let formula = Formula::Exists {
        vars: vec!["w".to_owned()],
        body: Box::new(Formula::Or(vec![
            Formula::atom(
                Term::iri(iri("rel")).unwrap(),
                vec![
                    Term::var("w").unwrap(),
                    Term::sequence_marker("rest").unwrap(),
                ],
            )
            .unwrap(),
            Formula::Not(Box::new(
                Formula::atom(
                    Term::iri(iri("rel")).unwrap(),
                    vec![Term::literal("v", Some(iri("Tag"))).unwrap()],
                )
                .unwrap(),
            )),
        ])),
    };

    let contract = ReasoningContract::from_preset(SemanticProfileId::StratifiedNaf);

    let correspondence = Correspondence::new(
        iri("corr/test"),
        CorrespondenceRelation::Equiv,
        MorphismClass::Isomorphism,
        MorphismKind::InstitutionMorphism,
        true,
        None,
        None,
        None,
        Vec::new(),
        Some(0.9),
        None,
        None,
        None,
        None,
    )
    .unwrap();

    let orig = LogicProgram::new(
        vec![axiom],
        vec![rule],
        vec![contract],
        Some("urn:test:comprehensive".to_owned()),
    )
    .with_correspondences(vec![correspondence])
    .with_formulas(vec![formula]);

    // First normalization: a programmatically-built program is not yet at the frontend's
    // canonical fixpoint (e.g. the frontend re-classifies a correspondence's `logic:`
    // predicates as flat axioms too, and re-derives a rule's structural head/body axioms).
    // The Exact property is that CLIF is an IDEMPOTENT lossless codec at that fixpoint: round-
    // tripping once reaches it, and EVERY further round-trip is the identity. Each leg also
    // checks the correspondence / contract / formula survive (none silently dropped).
    let src = Some("urn:test:comprehensive".to_owned());
    let clif1 = project_clif(&orig).content;
    let (fp, diags1) = parse_clif_str(&clif1, src.clone()).expect("parse_clif_str #1");
    assert!(
        diags1.iter().all(|d| d.code != "CLIF_MALFORMED_SENTENCE"),
        "malformed-sentence diagnostics on a well-formed round-trip: {diags1:?}\n--- CLIF ---\n{clif1}"
    );
    // The exercised constructs all survive into the fixpoint.
    assert_eq!(
        fp.correspondences.len(),
        1,
        "the correspondence must survive the round-trip"
    );
    assert_eq!(
        fp.contracts.len(),
        1,
        "the reasoning contract must survive the round-trip"
    );
    assert_eq!(
        fp.formulas.len(),
        1,
        "the full-FOL formula must survive the round-trip"
    );
    assert!(
        fp.rules.iter().any(|r| !r.distinct_pairs.is_empty()),
        "the rule's distinct pair must survive"
    );
    assert!(
        fp.rules.iter().any(|r| r.body.iter().any(|b| b.negated)),
        "the rule's negated body atom must survive"
    );

    // Idempotence: the second round-trip is the exact identity on the fixpoint.
    let clif2 = project_clif(&fp).content;
    assert_eq!(
        clif1, clif2,
        "CLIF emission is not idempotent at the fixpoint (byte drift):\n--- 1 ---\n{clif1}\n--- 2 ---\n{clif2}"
    );
    let (fp2, _diags2) = parse_clif_str(&clif2, src).expect("parse_clif_str #2");
    assert_ir_isomorphic(&fp, &fp2).unwrap_or_else(|e| {
        panic!("comprehensive round-trip not idempotent: {e}\n--- CLIF ---\n{clif2}")
    });
    assert!(
        fp == fp2,
        "comprehensive fixpoint round-trip differs (scope / correspondences)"
    );
}

#[test]
fn production_module_round_trip_is_isomorphic() {
    // The hard Exact proof: the real logic: slice module must round-trip through CLIF with
    // ZERO loss against the Exact `canonical-rdf12` reference.
    //
    // The comparison is taken at the canonical FIXPOINT, which is the mathematically correct
    // identity (not a weakening). The frontend's `extract_axioms` DOUBLE-extracts a rule's
    // flat `logic:head` / `logic:body` triples as `program.axioms` whose object IRIs are the
    // SOURCE serialization's blank-node labels (`c14n*`). No serializer reproduces those
    // source-dependent labels — `canonical-rdf12` ITSELF maps the raw parse (119 axioms) to a
    // fixpoint (123 axioms with minted `rule/_NNN/body/NNNN` IRIs), and a second pass is
    // stable. So the Exact reference is `fixpoint = parse ∘ canonical-rdf12 ∘ parse(module)`;
    // proving CLIF round-trips THAT exactly proves CLIF preserves everything the Exact
    // `canonical-rdf12` target does — the genuine Exact bar.
    use crate::projections::rdf;
    let ttl = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../slices/core/logic/module.ttl"
    ));
    let src = Some("urn:gmeow:slices/core/logic".to_owned());
    let (raw, _raw_diags) = parse_logic_str(ttl, src.clone()).expect("parse module.ttl");
    let canon = rdf::project_canonical_rdf12(&raw).expect("canonical-rdf12 of module");
    let (fixpoint, _) = parse_logic_str(&canon.content, src.clone()).expect("parse fixpoint");

    let clif = project_clif(&fixpoint).content;
    let (reparsed, diags) = parse_clif_str(&clif, src).expect("parse_clif_str(module)");
    let malformed: Vec<_> = diags
        .iter()
        .filter(|d| d.code == "CLIF_MALFORMED_SENTENCE")
        .collect();
    assert!(
        malformed.is_empty(),
        "malformed CLIF sentences in the production round-trip: {malformed:?}"
    );
    assert_ir_isomorphic(&fixpoint, &reparsed)
        .unwrap_or_else(|e| panic!("production module round-trip not isomorphic:\n{e}"));
    // Full structural equality (assert_ir_isomorphic does not diff correspondences / scope).
    assert!(
        fixpoint == reparsed,
        "production CLIF round-trip differs from the canonical fixpoint beyond the \
         isomorphism gate's surfaced collections (scope / correspondences / path shapes)"
    );
}
