// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! CLIF dialect tests: emit-shape, comprehensive IR round-trip, and the
//! production round-trip (the acceptance bar that proves the Exact claim is honest).

use crate::adapter::assert_ir_isomorphic;
use crate::clif::{parse_clif_str, project_clif};
use crate::frontend::parse_logic_str;
use crate::ir::{
    ContextualScope, Correspondence, CorrespondenceRelation, Formula, LegPath, LogicAxiom,
    LogicModality, LogicProgram, LogicRule, MorphismClass, MorphismKind, PathBase, PathShapeIr,
    ReasoningContract, SemanticProfileId, Term, TransactionProgramIr,
};

// The real `logic:` namespace (see `crate::ir::LOGIC_NAMESPACE`); a meta-channel triple
// is only re-classified as a domain axiom when its predicate sits in this namespace, so the
// round-trip fixtures must mint their IRIs here.
const LOGIC: &str = "https://blackcatinformatics.ca/logic/";

fn iri(local: &str) -> String {
    format!("{LOGIC}{local}")
}

/// Build a small program with one rule + a few formulas (quantifier, disjunction, strong
/// negation, sequence marker) + one axiom — the emit-shape fixture.
fn shape_program() -> LogicProgram {
    let axiom = LogicAxiom::ground(iri("a"), iri("knows"), iri("b"), false).expect("axiom");

    let rule = LogicRule::new(
        LogicAxiom::new(
            "?x",
            iri("ancestor"),
            "?z",
            false,
            false,
            ContextualScope::default(),
        )
        .expect("head"),
        vec![
            LogicAxiom::new(
                "?x",
                iri("parent"),
                "?y",
                false,
                false,
                ContextualScope::default(),
            )
            .expect("b1"),
            LogicAxiom::new(
                "?y",
                iri("parent"),
                "?z",
                false,
                false,
                ContextualScope::default(),
            )
            .expect("b2"),
        ],
        vec![("?x".to_owned(), "?z".to_owned())],
        ContextualScope::default(),
    );

    // (forall (?p) (or (mortal ?p) (not (mortal ?p))))  with a sequence marker arg.
    let inner_or = Formula::Or(vec![
        Formula::atom(
            Term::iri(iri("mortal")).unwrap(),
            vec![
                Term::var("p").unwrap(),
                Term::sequence_marker("rest").unwrap(),
            ],
        )
        .unwrap(),
        Formula::Not(Box::new(
            Formula::atom(
                Term::iri(iri("mortal")).unwrap(),
                vec![Term::var("p").unwrap()],
            )
            .unwrap(),
        )),
    ]);
    let formula = Formula::Forall {
        vars: vec!["p".to_owned()],
        body: Box::new(inner_or),
    };

    LogicProgram::new(
        vec![axiom],
        vec![rule],
        Vec::new(),
        Some("urn:test:shape".to_owned()),
    )
    .with_formulas(vec![formula])
}

#[test]
fn emit_shape_contains_idiomatic_forms() {
    let p = shape_program();
    let out = project_clif(&p).expect("project_clif").content;

    assert!(out.contains(";; GENERATED by"), "banner missing:\n{out}");
    assert!(out.contains("(forall"), "no (forall …):\n{out}");
    assert!(out.contains("(if "), "no (if …) for the rule:\n{out}");
    assert!(
        out.contains("(/= "),
        "no (/=) for the distinct pair:\n{out}"
    );
    assert!(out.contains("(or "), "no (or …):\n{out}");
    assert!(out.contains("(not "), "no (not …):\n{out}");
    assert!(
        out.contains("(seq "),
        "no (seq …) for the sequence marker:\n{out}"
    );
    // The axiom rides the RDF channel after the sentinel.
    assert!(
        out.contains("@@gmeow-rdf-meta@@"),
        "no RDF-meta sentinel for the axiom channel:\n{out}"
    );
}

#[test]
fn comprehensive_round_trip_is_isomorphic() {
    // An axiom, a rule (negated body atom + distinct pair), a full-FOL formula (quantifier
    // + disjunction + sequence marker), plus meta: a reasoning contract and a correspondence.
    let axiom = LogicAxiom::ground(iri("socrates"), iri("isA"), iri("Human"), false).unwrap();

    let rule = LogicRule::new(
        LogicAxiom::new(
            "?x",
            iri("eligible"),
            "?y",
            false,
            false,
            ContextualScope::default(),
        )
        .unwrap(),
        vec![
            LogicAxiom::new(
                "?x",
                iri("member"),
                "?y",
                false,
                false,
                ContextualScope::default(),
            )
            .unwrap(),
            // A negation-as-failure body atom (negated = the 5th arg).
            LogicAxiom::new(
                "?x",
                iri("banned"),
                "?y",
                false,
                true,
                ContextualScope::default(),
            )
            .unwrap(),
        ],
        vec![("?x".to_owned(), "?y".to_owned())],
        ContextualScope::default(),
    );

    let formula = Formula::Exists {
        vars: vec!["w".to_owned()],
        body: Box::new(Formula::Or(vec![
            Formula::atom(
                Term::iri(iri("rel")).unwrap(),
                vec![
                    Term::var("w").unwrap(),
                    Term::sequence_marker("rest").unwrap(),
                ],
            )
            .unwrap(),
            Formula::Not(Box::new(
                Formula::atom(
                    Term::iri(iri("rel")).unwrap(),
                    vec![Term::literal("v", Some(iri("Tag"))).unwrap()],
                )
                .unwrap(),
            )),
        ])),
    };

    let contract = ReasoningContract::from_preset(SemanticProfileId::StratifiedNaf);

    let correspondence = Correspondence::new(
        iri("corr/test"),
        CorrespondenceRelation::Equiv,
        MorphismClass::Isomorphism,
        MorphismKind::InstitutionMorphism,
        true,
        None,
        None,
        None,
        Vec::new(),
        Some(0.9),
        None,
        None,
        None,
        None,
        None,
    )
    .unwrap();

    let orig = LogicProgram::new(
        vec![axiom],
        vec![rule],
        vec![contract],
        Some("urn:test:comprehensive".to_owned()),
    )
    .with_correspondences(vec![correspondence])
    .unwrap()
    .with_formulas(vec![formula]);

    // First normalization: a programmatically-built program is not yet at the frontend's
    // canonical fixpoint (e.g. the frontend re-classifies a correspondence's `logic:`
    // predicates as flat axioms too, and re-derives a rule's structural head/body axioms).
    // The Exact property is that CLIF is an IDEMPOTENT lossless codec at that fixpoint: round-
    // tripping once reaches it, and EVERY further round-trip is the identity. Each leg also
    // checks the correspondence / contract / formula survive (none silently dropped).
    let src = Some("urn:test:comprehensive".to_owned());
    let clif1 = project_clif(&orig).expect("project_clif").content;
    let (fp, diags1) = parse_clif_str(&clif1, src.clone()).expect("parse_clif_str #1");
    assert!(
        diags1.iter().all(|d| d.code != "CLIF_MALFORMED_SENTENCE"),
        "malformed-sentence diagnostics on a well-formed round-trip: {diags1:?}\n--- CLIF ---\n{clif1}"
    );
    // The exercised constructs all survive into the fixpoint.
    assert_eq!(
        fp.correspondences.len(),
        1,
        "the correspondence must survive the round-trip"
    );
    assert_eq!(
        fp.contracts.len(),
        1,
        "the reasoning contract must survive the round-trip"
    );
    assert_eq!(
        fp.formulas.len(),
        1,
        "the full-FOL formula must survive the round-trip"
    );
    assert!(
        fp.rules.iter().any(|r| !r.distinct_pairs.is_empty()),
        "the rule's distinct pair must survive"
    );
    assert!(
        fp.rules.iter().any(|r| r.body.iter().any(|b| b.negated)),
        "the rule's negated body atom must survive"
    );

    // Idempotence: the second round-trip is the exact identity on the fixpoint.
    let clif2 = project_clif(&fp).expect("project_clif").content;
    assert_eq!(
        clif1, clif2,
        "CLIF emission is not idempotent at the fixpoint (byte drift):\n--- 1 ---\n{clif1}\n--- 2 ---\n{clif2}"
    );
    let (fp2, _diags2) = parse_clif_str(&clif2, src).expect("parse_clif_str #2");
    assert_ir_isomorphic(&fp, &fp2).unwrap_or_else(|e| {
        panic!("comprehensive round-trip not idempotent: {e}\n--- CLIF ---\n{clif2}")
    });
    assert!(
        fp == fp2,
        "comprehensive fixpoint round-trip differs (scope / correspondences)"
    );
}

#[test]
#[should_panic(expected = "iri-disallowed-char")]
fn forbidden_iriref_chars_are_refused_by_the_rdf_ir() {
    // `{ } | ^ ` `` ` ``, a space and a TAB are not legal in an IRI (RFC 3987), so the RDF
    // IR refuses to intern one carrying them and names the offending character and its byte
    // offset. This test used to assert the opposite — that such an IRI SURVIVED a
    // `project_clif` ∘ `parse_clif_str` round trip verbatim. It did survive, because the IR
    // interned it unchecked and the codec emitted Turtle no conforming parser would read
    // back; the round trip agreed with itself while agreeing with nothing else.
    //
    // Refusal is the correct behaviour and is pinned here so a regression to silent
    // acceptance is caught. The `\uXXXX` escaping this test formerly reached only
    // indirectly is covered directly by `crate::nt::tests`.
    let weird = format!("{LOGIC}weird/a{{b}}c|d^e`f g\th");
    let axiom = LogicAxiom::ground(weird, iri("knows"), iri("target"), false).unwrap();
    let orig = LogicProgram::new(
        vec![axiom],
        Vec::new(),
        Vec::new(),
        Some("urn:test:iri".to_owned()),
    );
    let _ = project_clif(&orig);
}

#[test]
#[should_panic(expected = "iri-disallowed-char")]
fn control_chars_del_c1_c0_are_refused_by_the_rdf_ir() {
    // DEL (0x7F), a C1 control (0x85) and a C0 control (0x01) are not legal in an IRI
    // (RFC 3987), so the RDF IR refuses to intern one carrying them and names the offending
    // codepoint and its byte offset. This test used to assert the opposite — that such an
    // IRI SURVIVED the round trip verbatim. It did, because the IR interned it unchecked
    // and the codec emitted output no conforming parser would read back.
    //
    // Refusal is the correct behaviour and is pinned here so a regression to silent
    // acceptance is caught. The full-control-range `\uXXXX` escaping this test formerly
    // reached only indirectly is covered directly by `crate::nt::tests`.
    let weird = format!("{LOGIC}weird/a\u{7F}b\u{85}c\u{01}d");
    let axiom = LogicAxiom::ground(weird, iri("knows"), iri("target"), false).unwrap();
    let orig = LogicProgram::new(
        vec![axiom],
        Vec::new(),
        Vec::new(),
        Some("urn:test:iri".to_owned()),
    );
    let _ = project_clif(&orig);
}

#[test]
fn path_shape_round_trips_with_typed_integer_depths() {
    // A logic:PathShape rides the RDF/predication channel. Its min/max depths are integers in
    // the IR (`u32`) and are emitted as typed `xsd:integer` literals; the whole shape — base
    // predicate, both depths, namespace scope, depth param — must survive the round-trip.
    let shape = PathShapeIr::new(
        iri("shape/ancestry"),
        PathBase::NamedPredicate(iri("parent")),
        1,
        Some(7),
        None,
        None,
    )
    .unwrap();
    let orig = LogicProgram::new(
        Vec::new(),
        Vec::new(),
        Vec::new(),
        Some("urn:test:pathshape".to_owned()),
    )
    .with_path_shapes(vec![shape]);

    let src = Some("urn:test:pathshape".to_owned());
    let clif1 = project_clif(&orig).expect("project_clif").content;
    // The depths are carried as typed xsd:integer literals, not bare strings.
    assert!(
        clif1.contains("http://www.w3.org/2001/XMLSchema#integer"),
        "path-shape depths are not emitted as typed xsd:integer literals:\n{clif1}"
    );

    let (fp, _diags) = parse_clif_str(&clif1, src.clone()).expect("parse_clif_str");
    assert_eq!(fp.path_shapes.len(), 1, "the path shape must survive");
    let got = &fp.path_shapes[0];
    assert_eq!(got.min_depth, 1, "min_depth lost");
    assert_eq!(got.max_depth, Some(7), "max_depth lost");
    assert!(
        matches!(&got.base, PathBase::NamedPredicate(p) if *p == iri("parent")),
        "path base predicate lost: {:?}",
        got.base
    );

    // Idempotent at the fixpoint.
    let clif2 = project_clif(&fp).expect("project_clif").content;
    assert_eq!(clif1, clif2, "path-shape CLIF emission is not idempotent");
}

#[test]
fn cl_modules_and_importation_round_trip_at_fixpoint() {
    // CL modules + importation + per-statement module membership survive CLIF at Exact.
    // Module objects (`rdf:type logic:Module`) and the import graph (`logic:imports`) ride the
    // axiom channel; per-statement membership rides the reifier-scope carrier (`logic:inModule`),
    // exactly like `logic:standpoint`. Compared at the canonical FIXPOINT (the Exact reference:
    // the frontend's flat extraction of a scoped reifier is idempotent but not identity on the
    // raw program), mirroring `production_module_round_trip_is_isomorphic`.
    // Module names are arbitrary IRIs (a CL module IRI is not `logic:`-namespaced — that
    // namespace is the ontology's own vocabulary, whose type declarations the frontend skips).
    let m1 = "https://example.org/module/geometry".to_owned();
    let m2 = "https://example.org/module/algebra".to_owned();
    let rdf_type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

    let m1_is_module = LogicAxiom::ground(m1.clone(), rdf_type, iri("Module"), false).unwrap();
    let m2_is_module = LogicAxiom::ground(m2.clone(), rdf_type, iri("Module"), false).unwrap();
    let imports = LogicAxiom::ground(m1.clone(), iri("imports"), m2.clone(), false).unwrap();

    let scope = ContextualScope::new(
        None,
        None,
        None,
        LogicModality::None,
        None,
        Some(m1.clone()),
    )
    .unwrap();
    let scoped = LogicAxiom::new(
        iri("point"),
        iri("liesOn"),
        iri("line"),
        false,
        false,
        scope,
    )
    .unwrap();

    let orig = LogicProgram::new(
        vec![m1_is_module, m2_is_module, imports, scoped],
        Vec::new(),
        Vec::new(),
        Some("urn:test:modules".to_owned()),
    );
    let src = Some("urn:test:modules".to_owned());

    // Reach the canonical fixpoint.
    let (fp, _d0) = parse_clif_str(
        &project_clif(&orig).expect("project #0").content,
        src.clone(),
    )
    .expect("parse #0");

    // Module objects + the import edge survive (they ride the ordinary axiom channel).
    assert!(
        fp.axioms
            .iter()
            .any(|a| a.subject == m1 && a.predicate == iri("imports") && a.obj == m2),
        "module import edge lost:\n{:#?}",
        fp.axioms
    );
    assert!(
        fp.axioms
            .iter()
            .any(|a| a.subject == m1 && a.predicate == rdf_type && a.obj == iri("Module")),
        "logic:Module type declaration lost"
    );
    // Per-statement module membership survives on the scoped statement.
    assert!(
        fp.axioms
            .iter()
            .any(|a| a.predicate == iri("liesOn") && a.scope.module.as_deref() == Some(m1.as_str())),
        "logic:inModule membership lost:\n{:#?}",
        fp.axioms
    );

    // Idempotent + isomorphic at the fixpoint.
    let clif1 = project_clif(&fp).expect("project #1").content;
    let (fp2, _d) = parse_clif_str(&clif1, src).expect("parse #1");
    let clif2 = project_clif(&fp2).expect("project #2").content;
    assert_eq!(
        clif1, clif2,
        "module CLIF emission is not idempotent at the fixpoint"
    );
    assert_ir_isomorphic(&fp, &fp2)
        .unwrap_or_else(|e| panic!("module round-trip not isomorphic: {e}"));
}

#[test]
fn hilog_relation_as_individual_round_trips() {
    // HiLog reflection: a relation is simultaneously an individual. `related` is used BOTH as an
    // atom predicate (a related b) AND as the subject of a typing (logic:instanceOf logic:Type,
    // logic:orderedType) — reusing logic:instanceOf / logic:orderedType / logic:Type, minting no
    // new terms (P5/P17). Both readings must round-trip through CLIF.
    let related = iri("related");
    let ax_pred = LogicAxiom::ground(iri("a"), related.clone(), iri("b"), false).unwrap();
    let ax_instanceof =
        LogicAxiom::ground(related.clone(), iri("instanceOf"), iri("Type"), false).unwrap();
    let ax_ordered = LogicAxiom::ground(
        related.clone(),
        iri("orderedType"),
        iri("BinaryRelation"),
        false,
    )
    .unwrap();

    let orig = LogicProgram::new(
        vec![ax_pred, ax_instanceof, ax_ordered],
        Vec::new(),
        Vec::new(),
        Some("urn:test:hilog".to_owned()),
    );
    let src = Some("urn:test:hilog".to_owned());
    let clif1 = project_clif(&orig).expect("project #1").content;
    let (fp, _d) = parse_clif_str(&clif1, src.clone()).expect("parse");

    // The relation survives BOTH as a predicate and as a typed individual.
    assert!(
        fp.axioms
            .iter()
            .any(|a| a.predicate == related && a.subject == iri("a") && a.obj == iri("b")),
        "relation-as-predicate reading lost:\n{:#?}",
        fp.axioms
    );
    assert!(
        fp.axioms.iter().any(|a| a.subject == related
            && a.predicate == iri("instanceOf")
            && a.obj == iri("Type")),
        "relation-as-individual (instanceOf Type) reading lost:\n{:#?}",
        fp.axioms
    );
    assert!(
        fp.axioms
            .iter()
            .any(|a| a.subject == related && a.predicate == iri("orderedType")),
        "orderedType typing lost"
    );

    // Idempotent.
    let clif2 = project_clif(&fp).expect("project #2").content;
    assert_eq!(clif1, clif2, "HiLog CLIF emission is not idempotent");
}

#[test]
fn fol_only_clif_without_meta_carrier_fails_closed() {
    // A CLIF document with idiomatic FOL sentences but NO RDF-meta carrier block cannot be
    // reconstructed (the FOL view is validated-only, never the round-trip authority). The
    // reader must FAIL CLOSED, not silently return an empty program (never silently drop).
    let clif = "(forall (?x) ('https://blackcatinformatics.ca/logic/mortal' ?x))\n";
    let err = parse_clif_str(clif, Some("urn:test:folonly".to_owned())).unwrap_err();
    assert!(
        err.0.contains("no `;; @@gmeow-rdf-meta@@` carrier"),
        "expected a fail-closed error for FOL-only input, got: {}",
        err.0
    );
}

#[test]
fn production_module_round_trip_is_isomorphic() {
    // The hard Exact proof: the real logic: slice module must round-trip through CLIF with
    // ZERO loss against the Exact `canonical-rdf12` reference.
    //
    // The comparison is taken at the canonical FIXPOINT, which is the mathematically correct
    // identity (not a weakening). The frontend's `extract_axioms` DOUBLE-extracts a rule's
    // flat `logic:head` / `logic:body` triples as `program.axioms` whose object IRIs are the
    // SOURCE serialization's blank-node labels (`c14n*`). No serializer reproduces those
    // source-dependent labels — `canonical-rdf12` ITSELF maps the raw parse (119 axioms) to a
    // fixpoint (123 axioms with minted `rule/_NNN/body/NNNN` IRIs), and a second pass is
    // stable. So the Exact reference is `fixpoint = parse ∘ canonical-rdf12 ∘ parse(module)`;
    // proving CLIF round-trips THAT exactly proves CLIF preserves everything the Exact
    // `canonical-rdf12` target does — the genuine Exact bar.
    use crate::projections::rdf;
    let ttl = include_str!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../slices/grounding/logic/module.ttl"
    ));
    let src = Some("urn:gmeow:slices/grounding/logic".to_owned());
    let (raw, _raw_diags) = parse_logic_str(ttl, src.clone()).expect("parse module.ttl");
    let canon = rdf::project_canonical_rdf12(&raw).expect("canonical-rdf12 of module");
    let (fixpoint, _) = parse_logic_str(&canon.content, src.clone()).expect("parse fixpoint");

    let clif = project_clif(&fixpoint).expect("project_clif").content;
    let (reparsed, diags) = parse_clif_str(&clif, src).expect("parse_clif_str(module)");
    let malformed: Vec<_> = diags
        .iter()
        .filter(|d| d.code == "CLIF_MALFORMED_SENTENCE")
        .collect();
    assert!(
        malformed.is_empty(),
        "malformed CLIF sentences in the production round-trip: {malformed:?}"
    );
    assert_ir_isomorphic(&fixpoint, &reparsed)
        .unwrap_or_else(|e| panic!("production module round-trip not isomorphic:\n{e}"));
    // Full structural equality (assert_ir_isomorphic does not diff correspondences / scope).
    assert!(
        fixpoint == reparsed,
        "production CLIF round-trip differs from the canonical fixpoint beyond the \
         isomorphism gate's surfaced collections (scope / correspondences / path shapes)"
    );
}

#[test]
fn transaction_program_round_trips() {
    // A correspondence carrying `logic:getLeg` / `logic:putLeg` IRIs, plus the realized
    // leg-body `logic:TransactionProgram`s those IRIs name. The CLIF writer must serialize the
    // leg bodies as `gm:` path-node triples (the faithful inverse of the frontend's
    // `parse_leg_path`), and the frontend must reconstruct them via `extract_leg_programs`
    // (which keys off the correspondence's leg IRIs). The Exact claim demands they survive.
    const GMEOW: &str = "https://blackcatinformatics.ca/gmeow/";
    let leg_get = format!("{GMEOW}example/getLeg");
    let leg_put = format!("{GMEOW}example/putLeg");
    let p1 = iri("propAlpha");
    let p2 = iri("propBeta");

    // get = α / ^β  (a Seq with a nested Inverse — exercises Seq, Step, and Inverse).
    let get_body = LegPath::Seq(vec![
        LegPath::Step(p1.clone()),
        LegPath::Inverse(Box::new(LegPath::Step(p2.clone()))),
    ]);
    // put = the lawful structural inverse: ^(α / ^β) = β / ^α.
    let put_body = get_body.invert();

    let correspondence = Correspondence::new(
        iri("corr/legtest"),
        CorrespondenceRelation::Equiv,
        MorphismClass::Isomorphism,
        MorphismKind::InstitutionMorphism,
        true,
        None,
        Some(leg_get.clone()),
        Some(leg_put.clone()),
        Vec::new(),
        Some(0.9),
        None,
        None,
        None,
        None,
        None,
    )
    .unwrap();

    let orig = LogicProgram::new(
        Vec::new(),
        Vec::new(),
        Vec::new(),
        Some("urn:test:legprograms".to_owned()),
    )
    .with_correspondences(vec![correspondence])
    .unwrap()
    .with_transaction_programs(vec![
        TransactionProgramIr {
            iri: leg_get,
            body: get_body,
        },
        TransactionProgramIr {
            iri: leg_put,
            body: put_body,
        },
    ]);

    // As in `comprehensive_round_trip`, a programmatically-built program is not yet at the
    // frontend's canonical fixpoint (the frontend re-classifies a correspondence's `logic:`
    // predicates as flat axioms too). The Exact property is that CLIF is an IDEMPOTENT lossless
    // codec AT that fixpoint: one round-trip reaches it, every further round-trip is identity.
    let src = Some("urn:test:legprograms".to_owned());
    let clif1 = project_clif(&orig).expect("project_clif").content;
    let (fp, diags1) = parse_clif_str(&clif1, src.clone()).expect("parse_clif_str #1");
    assert!(
        diags1.iter().all(|d| d.code != "CLIF_MALFORMED_SENTENCE"),
        "malformed-sentence diagnostics on a well-formed leg-program round-trip: {diags1:?}\n\
         --- CLIF ---\n{clif1}"
    );

    // The leg bodies survive the FIRST round-trip (reconstructed via `extract_leg_programs`
    // keying off the correspondence's leg IRIs) — the whole point of the fix.
    assert_eq!(
        fp.transaction_programs.len(),
        orig.transaction_programs.len(),
        "leg programs lost in the round-trip: {:?}",
        fp.transaction_programs
    );
    // And they reconstruct to the SAME leg bodies (content keys, not just count).
    let orig_keys: Vec<String> = orig
        .transaction_programs
        .iter()
        .map(crate::ir::TransactionProgramIr::content_key)
        .collect();
    let fp_keys: Vec<String> = fp
        .transaction_programs
        .iter()
        .map(crate::ir::TransactionProgramIr::content_key)
        .collect();
    assert_eq!(
        orig_keys, fp_keys,
        "leg bodies changed across the round-trip"
    );

    // Idempotence at the fixpoint: the second round-trip is the exact identity, leg bodies
    // included. This is the Exact bar — proving the leg-body channel is a lossless codec.
    let clif2 = project_clif(&fp).expect("project_clif").content;
    assert_eq!(
        clif1, clif2,
        "CLIF emission is not idempotent at the leg-program fixpoint (byte drift):\n\
         --- 1 ---\n{clif1}\n--- 2 ---\n{clif2}"
    );
    let (fp2, _diags2) = parse_clif_str(&clif2, src).expect("parse_clif_str #2");
    assert_ir_isomorphic(&fp, &fp2).unwrap_or_else(|e| {
        panic!("transaction-program round-trip not idempotent: {e}\n--- CLIF ---\n{clif2}")
    });
    assert!(
        fp == fp2,
        "leg-program fixpoint round-trip differs (transaction programs / correspondences)"
    );
    assert_eq!(
        fp2.transaction_programs.len(),
        orig.transaction_programs.len(),
        "leg programs lost across the idempotent re-round-trip"
    );
}
