// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The CLIF **writer**: [`LogicProgram`] → CLIF text (`generated/cl/gmeow.clif`).
//!
//! See [`crate::clif`] for the two-channel architecture. This module emits the
//! idiomatic FOL channel (`rules` + `formulas`) as Common Logic sentences and the
//! RDF/predication channel (everything else) as `(<P> <S> <O>)` predications after the
//! [`RDF_META_SENTINEL`](super::RDF_META_SENTINEL).

use crate::ir::{Formula, LogicAxiom, LogicProgram, Term};
use crate::projections::{rdf, target_meta, ProjectionResult};

use super::{escape_name, escape_string, RDF_META_SENTINEL};

use gmeow_rdf::{parse_dataset, RdfDataset, TermRef};

/// `xsd:string` — the datatype the dataset assigns a plain literal; emitted CLIF
/// distinguishes a plain `(lit "x")` from a typed `(lit "x" 'dt')` by suppressing this
/// datatype (so the round-trip reconstructs the plain literal).
const XSD_STRING: &str = "http://www.w3.org/2001/XMLSchema#string";
/// `rdf:langString` — the datatype of a language-tagged literal; emitted as
/// `(lit "x" @lang)`, the datatype itself suppressed (it is implied by the tag).
const RDF_LANG_STRING: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString";

/// Project a [`LogicProgram`] to CLIF text.
pub fn project_clif(program: &LogicProgram) -> ProjectionResult {
    // Registry is the single source of truth for (preservation, complexity, drops);
    // mirror `project_datalog`'s pattern so the ledger and the result agree.
    let (kind, cx, drops) = target_meta("clif");

    let mut lines: Vec<String> = vec![
        ";; GENERATED by `gmeow logic compile` — DO NOT EDIT.".to_owned(),
        ";; CLIF (Common Logic Interchange Format) projection of the canonical logic: program."
            .to_owned(),
        String::new(),
    ];

    // ── Idiomatic FOL channel (human-readable rendering) ────────────────────────
    // Rules and formulas are rendered as readable Common Logic sentences for human
    // consumption. This channel is WRITE-ONLY: the canonical IR carries an
    // `obj_is_literal` bit on a rule term (and a rule's minted reifier-node identity)
    // that idiomatic CL syntax cannot express, so reconstructing the byte-exact IR from a
    // `(forall …)` sentence would be lossy. The lossless carrier is the RDF/predication
    // channel below (the Exact `canonical-rdf12` leg), from which the reader reconstructs
    // the WHOLE program — rules and formulas included. The FOL sentences are therefore an
    // idiomatic view over the same content, never the round-trip authority.
    lines.push(
        ";; === Rules (idiomatic Common Logic sentences; human-readable view) ===".to_owned(),
    );
    for rule in &program.rules {
        lines.push(rule_to_clif(rule));
    }
    lines.push(String::new());
    lines.push(";; === Full first-order formulas (idiomatic view) ===".to_owned());
    for formula in &program.formulas {
        lines.push(formula_to_clif(formula));
    }

    // ── RDF / predication channel (the lossless round-trip carrier): the WHOLE program
    //    — axioms (+ scope), rules, formulas, contracts, correspondences — re-emitted as
    //    sorted CL predications from the Exact canonical-RDF-1.2 serializer. ───────────
    let meta_lines = meta_predications(program);
    if !meta_lines.is_empty() {
        lines.push(String::new());
        lines.push(RDF_META_SENTINEL.to_owned());
        lines.push(
            ";; RDF/predication channel — flat (logic:) triples as CL predications (P S O)."
                .to_owned(),
        );
        lines.extend(meta_lines);
    }

    let content = format!("{}\n", lines.join("\n"));
    ProjectionResult {
        target: "clif".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        lossy_drops: drops.into_iter().map(str::to_owned).collect(),
        // Exact target: every construct is carried (FOL channel verbatim, RDF channel via
        // the lossless canonical-RDF-1.2 leg). Nothing is dropped — the overclaim gate
        // requires this list be empty under an Exact claim.
        actual_drops: Vec::new(),
    }
}

// --------------------------------------------------------------------------- //
// Idiomatic FOL channel — rules
// --------------------------------------------------------------------------- //

/// Encode a [`LogicAxiom`] (a Horn triple) as a CL atom `(<pred> <subj> <obj>)`.
fn axiom_atom(axiom: &LogicAxiom) -> String {
    let pred = name_term(&axiom.predicate);
    let subj = horn_term(&axiom.subject, false);
    let obj = horn_term(&axiom.obj, axiom.obj_is_literal);
    format!("({pred} {subj} {obj})")
}

/// A Horn subject/object token: a `?var`, a typed/plain literal, or a quoted CL name.
fn horn_term(value: &str, is_literal: bool) -> String {
    if let Some(var) = value.strip_prefix('?') {
        format!("?{var}")
    } else if is_literal {
        // A plain literal in the Horn fragment (the canonical IR carries no datatype on
        // `LogicAxiom.obj`; that detail lives in the RDF channel). Encode as a plain lit.
        format!("(lit {})", quote_string(value))
    } else {
        name_term(value)
    }
}

/// Encode a [`crate::ir::LogicRule`] as `(forall (vars) (if (and body…) head))`, or — for
/// the degenerate empty-body rule — the bare head atom.
fn rule_to_clif(rule: &crate::ir::LogicRule) -> String {
    let head = axiom_atom(&rule.head);

    let mut body_atoms: Vec<String> = Vec::new();
    for ba in &rule.body {
        let atom = axiom_atom(ba);
        if ba.negated {
            body_atoms.push(format!("(not {atom})"));
        } else {
            body_atoms.push(atom);
        }
    }
    // `distinct_pairs` (a, b) → `(/= ?a ?b)` body conjuncts.
    for (a, b) in &rule.distinct_pairs {
        body_atoms.push(format!("(/= {} {})", var_token(a), var_token(b)));
    }

    if body_atoms.is_empty() {
        // A fact: emit the head alone (universally closed over its own variables).
        let vars = collect_rule_vars(rule);
        return if vars.is_empty() {
            head
        } else {
            format!("(forall ({}) {head})", vars.join(" "))
        };
    }

    let body = if body_atoms.len() == 1 {
        body_atoms.into_iter().next().expect("len==1")
    } else {
        format!("(and {})", body_atoms.join(" "))
    };

    let vars = collect_rule_vars(rule);
    let conditional = format!("(if {body} {head})");
    if vars.is_empty() {
        conditional
    } else {
        format!("(forall ({}) {conditional})", vars.join(" "))
    }
}

/// Collect the rule's universally-quantified variables (the `?`-vars appearing in head,
/// body, and distinct pairs), in first-appearance order, deduplicated.
fn collect_rule_vars(rule: &crate::ir::LogicRule) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    let consider =
        |s: &str, out: &mut Vec<String>, seen: &mut std::collections::HashSet<String>| {
            if let Some(name) = s.strip_prefix('?') {
                let tok = format!("?{name}");
                if seen.insert(tok.clone()) {
                    out.push(tok);
                }
            }
        };
    consider(&rule.head.subject, &mut out, &mut seen);
    consider(&rule.head.obj, &mut out, &mut seen);
    for ba in &rule.body {
        consider(&ba.subject, &mut out, &mut seen);
        consider(&ba.obj, &mut out, &mut seen);
    }
    for (a, b) in &rule.distinct_pairs {
        consider(a, &mut out, &mut seen);
        consider(b, &mut out, &mut seen);
    }
    out
}

/// Normalize a possibly-`?`-prefixed variable string to a CL `?name` token.
fn var_token(s: &str) -> String {
    match s.strip_prefix('?') {
        Some(name) => format!("?{name}"),
        None => format!("?{s}"),
    }
}

// --------------------------------------------------------------------------- //
// Idiomatic FOL channel — formulas
// --------------------------------------------------------------------------- //

/// Encode a [`Formula`] recursively as a CL sentence.
fn formula_to_clif(formula: &Formula) -> String {
    match formula {
        Formula::Atom { relation, args } => {
            let rel = term_to_clif(relation);
            let mut parts = vec![rel];
            for a in args {
                parts.push(term_to_clif(a));
            }
            format!("({})", parts.join(" "))
        }
        Formula::Not(inner) => format!("(not {})", formula_to_clif(inner)),
        Formula::And(fs) => {
            let parts: Vec<String> = fs.iter().map(formula_to_clif).collect();
            format!("(and {})", parts.join(" "))
        }
        Formula::Or(fs) => {
            let parts: Vec<String> = fs.iter().map(formula_to_clif).collect();
            format!("(or {})", parts.join(" "))
        }
        Formula::Implies(a, b) => {
            format!("(if {} {})", formula_to_clif(a), formula_to_clif(b))
        }
        Formula::Iff(a, b) => {
            format!("(iff {} {})", formula_to_clif(a), formula_to_clif(b))
        }
        Formula::Forall { vars, body } => {
            let vs: Vec<String> = vars.iter().map(|v| format!("?{v}")).collect();
            format!("(forall ({}) {})", vs.join(" "), formula_to_clif(body))
        }
        Formula::Exists { vars, body } => {
            let vs: Vec<String> = vars.iter().map(|v| format!("?{v}")).collect();
            format!("(exists ({}) {})", vs.join(" "), formula_to_clif(body))
        }
    }
}

/// Encode a [`Term`] as a CL term.
fn term_to_clif(term: &Term) -> String {
    match term {
        Term::Var(n) => format!("?{n}"),
        Term::Iri(i) => name_term(i),
        Term::Literal { lexical, datatype } => match datatype {
            None => format!("(lit {})", quote_string(lexical)),
            Some(dt) => format!("(lit {} {})", quote_string(lexical), name_term(dt)),
        },
        // A sequence marker → `(seq n)` reserved form.
        Term::SequenceMarker(n) => format!("(seq {})", quote_string(n)),
    }
}

// --------------------------------------------------------------------------- //
// RDF / predication channel
// --------------------------------------------------------------------------- //

/// Assemble the RDF/predication channel as sorted CL predications `(<P> <S> <O>)`. This is
/// the **lossless round-trip carrier** — built only from serializers the canonical frontend
/// round-trips at its fixpoint:
///
/// * **the whole program** — axioms (+ scope), rules, formulas, and contracts → the Exact
///   `canonical-rdf12` projection (which reifies rule head/body and full-FOL formula trees
///   and emits contract facets, all of which `parse_logic_dataset` reconstructs);
/// * **correspondences** → `project_correspondence` (round-trips to a content-key-equal
///   correspondence program — `correspondence/tests::projection_round_trips_to_equal_content_key`).
///
/// `path_shapes` are emitted DIRECTLY as the `logic:PathShape` triples the frontend's
/// `extract_path_shapes` reads (a faithful inverse). `transaction_programs` (a correspondence
/// leg's `gm:path` body) have no round-trippable RDF serializer in the codebase; the dialect
/// HARD-FAILS on them rather than silently dropping (the Exact claim stays honest for what it
/// carries — no construct vanishes in silence). Production carries neither.
fn meta_predications(program: &LogicProgram) -> Vec<String> {
    assert!(
        program.transaction_programs.is_empty(),
        "CLIF dialect: a program carrying logic:TransactionProgram leg bodies has no \
         round-trippable RDF serializer; refusing to silently drop it (#721 carries the \
         axiom / rule / formula / contract / correspondence / path-shape channels exactly)"
    );

    let mut preds: Vec<String> = Vec::new();

    // (0) Path shapes — emitted as the logic:PathShape triples `extract_path_shapes` reads.
    for shape in &program.path_shapes {
        preds.extend(path_shape_predications(shape));
    }

    // (1) The whole program (axioms + scope + rules + formulas + contracts) → the lossless
    //     canonical RDF 1.2 projection. Rules are reified as nodes (re-deriving the flat
    //     structural axioms exactly on re-parse) and formulas as logic:Formula trees, so the
    //     reconstruction is the Exact `canonical-rdf12` round-trip the frontend already pins.
    //
    //     A correspondence's `logic:` triples (e.g. `logic:confidence` / `logic:mnemomorphic`
    //     on the correspondence node) are DOUBLE-extracted by the frontend as flat axioms too;
    //     emitting them through canonical-rdf12 AND re-projecting them through the
    //     correspondence channel (2) would duplicate them with a different datatype (plain vs
    //     `xsd:decimal`), breaking idempotence. They are owned by the correspondence channel,
    //     so the axiom channel here EXCLUDES any axiom whose subject is a correspondence node
    //     (or one of its child / program nodes).
    let corr_subjects = correspondence_subjects(program);
    let axioms: Vec<_> = program
        .axioms
        .iter()
        .filter(|a| !is_correspondence_owned(&a.subject, &corr_subjects))
        .cloned()
        .collect();
    let canon_meta = LogicProgram::new(
        axioms,
        program.rules.clone(),
        program.contracts.clone(),
        program.source_iri.clone(),
    )
    .with_formulas(program.formulas.clone());
    let ttl = match rdf::project_canonical_rdf12(&canon_meta) {
        Ok(r) => r.content,
        Err(e) => panic!("CLIF meta channel: canonical-rdf12 projection failed: {e}"),
    };
    preds.extend(quads_as_predications(ttl.as_bytes(), "text/turtle"));

    // (2) Correspondences → the faithful correspondence N-Triples projection.
    if !program.correspondences.is_empty() {
        let cp = crate::projections::correspondence::CorrespondenceProgram::new(
            program.correspondences.clone(),
            Vec::new(),
            crate::ir::PreservationKind::Exact,
        );
        let nt = crate::projections::correspondence::project_correspondence(&cp);
        preds.extend(quads_as_predications(
            nt.as_bytes(),
            "application/n-triples",
        ));
    }

    preds.sort();
    preds.dedup();
    preds
}

/// Emit a [`PathShapeIr`] as the `logic:PathShape` CL predications its frontend extractor
/// reads (a faithful inverse of `extract_path_shapes`). Predicate-first `(P S O)` shape.
fn path_shape_predications(shape: &crate::ir::PathShapeIr) -> Vec<String> {
    let s = name_term(&shape.iri);
    let logic = |local: &str| name_term(&format!("{}{local}", crate::ir::LOGIC_NAMESPACE));
    let rdf_type = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

    let mut out = vec![format!(
        "({} {s} {})",
        name_term(rdf_type),
        logic("PathShape")
    )];
    match &shape.base {
        crate::ir::PathBase::NamedPredicate(p) => {
            out.push(format!(
                "({} {s} {})",
                logic("pathStepPredicate"),
                name_term(p)
            ));
        }
        crate::ir::PathBase::Wildcard => {
            out.push(format!("({} {s} (lit \"true\"))", logic("pathWildcard")));
        }
    }
    out.push(format!(
        "({} {s} (lit \"{}\"))",
        logic("pathMinDepth"),
        shape.min_depth
    ));
    if let Some(max) = shape.max_depth {
        out.push(format!("({} {s} (lit \"{max}\"))", logic("pathMaxDepth")));
    }
    if let Some(ns) = &shape.namespace_scope {
        out.push(format!(
            "({} {s} (lit {}))",
            logic("pathNamespaceScope"),
            quote_string(ns)
        ));
    }
    if let Some(param) = &shape.depth_param {
        out.push(format!(
            "({} {s} (lit {}))",
            logic("pathDepthParam"),
            quote_string(param)
        ));
    }
    out
}

/// The set of correspondence node IRIs whose flat axioms are owned by the correspondence
/// channel (the correspondence individuals + the singleton `correspondence-program` node).
/// Their law-claim / caveat child nodes are matched by IRI prefix in [`is_correspondence_owned`].
fn correspondence_subjects(program: &LogicProgram) -> Vec<String> {
    let mut subjects: Vec<String> = program
        .correspondences
        .iter()
        .map(|c| c.iri.clone())
        .collect();
    // The `project_correspondence` wrapper node (one per build).
    subjects.push(format!(
        "{}correspondence-program",
        crate::ir::LOGIC_NAMESPACE
    ));
    subjects
}

/// Whether `subject` is a correspondence node (exact match) or one of its child nodes (the
/// `project_correspondence` law-claim IRIs are minted as `<corr-iri>/lawclaim/<i>`, so an
/// IRI-prefix test catches them).
fn is_correspondence_owned(subject: &str, corr_subjects: &[String]) -> bool {
    corr_subjects
        .iter()
        .any(|c| subject == c || subject.starts_with(&format!("{c}/")))
}

/// Parse RDF `bytes` of `media_type` and emit each quad as a sorted-later CL predication.
fn quads_as_predications(bytes: &[u8], media_type: &str) -> Vec<String> {
    let ds = parse_dataset(bytes, media_type, None)
        .unwrap_or_else(|e| panic!("CLIF meta channel: re-parse of {media_type} failed: {e}"));
    ds.quad_refs()
        .map(|q| {
            let s = term_ref_to_clif(ds.as_ref(), q.s);
            let p = term_ref_to_clif(ds.as_ref(), q.p);
            let o = term_ref_to_clif(ds.as_ref(), q.o);
            format!("({p} {s} {o})")
        })
        .collect()
}

/// Encode a resolved RDF [`TermRef`] as a CL term, faithfully preserving datatype / lang.
fn term_ref_to_clif(ds: &RdfDataset, term: TermRef<'_>) -> String {
    match term {
        TermRef::Iri(iri) => name_term(iri),
        TermRef::Blank { label, .. } => name_term(&format!("_:{label}")),
        TermRef::Literal {
            lexical,
            datatype,
            language,
            ..
        } => {
            if let Some(lang) = language {
                format!("(lit {} @{lang})", quote_string(lexical))
            } else {
                let dt = match ds.resolve(datatype) {
                    TermRef::Iri(s) => s.to_owned(),
                    _ => XSD_STRING.to_owned(),
                };
                if dt == XSD_STRING {
                    format!("(lit {})", quote_string(lexical))
                } else if dt == RDF_LANG_STRING {
                    // A langString with no language is malformed; carry it as typed so the
                    // round-trip is total rather than silently dropping the datatype.
                    format!("(lit {} {})", quote_string(lexical), name_term(&dt))
                } else {
                    format!("(lit {} {})", quote_string(lexical), name_term(&dt))
                }
            }
        }
        // A triple term (RDF 1.2 quoted triple) — the canonical projection uses classic
        // reification, not `<<>>`, so this should not occur; if it does, recurse faithfully.
        TermRef::Triple { s, p, o } => {
            let st = term_ref_to_clif(ds, ds.resolve(s));
            let pt = term_ref_to_clif(ds, ds.resolve(p));
            let ot = term_ref_to_clif(ds, ds.resolve(o));
            format!("(triple {st} {pt} {ot})")
        }
    }
}

// --------------------------------------------------------------------------- //
// Term codecs
// --------------------------------------------------------------------------- //

/// Quote a CL name (IRI) as `'…'`, escaping `'` and `\`.
fn name_term(iri: &str) -> String {
    format!("'{}'", escape_name(iri))
}

/// Quote a string literal as `"…"`, escaping `"` and `\`.
fn quote_string(s: &str) -> String {
    format!("\"{}\"", escape_string(s))
}
