// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Exact original source fixtures selected by the structural-lint contracts.

pub(super) const SOURCES: [&str; 41] = [
    "slices/grounding/lang/tests/conformance-fixtures/ambiguity-saw-her-duck.ttl",
    "slices/grounding/lang/tests/conformance-fixtures/slot-contiguous.ttl",
    "slices/grounding/lang/tests/conformance-fixtures/surface-analyzed.ttl",
    "slices/grounding/lang/tests/counter-examples/gmn-compaction-silent-disambiguation.ttl",
    "slices/grounding/lang/tests/counter-examples/ingest-silent-drop.ttl",
    "slices/grounding/lang/tests/counter-examples/ingestion-silent-promotion.ttl",
    "slices/grounding/lang/tests/counter-examples/ingestion-unattributed-engine-claim.ttl",
    "slices/grounding/lang/tests/counter-examples/projection-exact-preservation-violated.ttl",
    "slices/grounding/lang/tests/counter-examples/projection-silent-disambiguation.ttl",
    "slices/grounding/lang/tests/counter-examples/projection-undeclared-unsupported.ttl",
    "slices/grounding/lang/tests/counter-examples/projection-unrecorded-epistemic-loss.ttl",
    "slices/grounding/lang/tests/counter-examples/slot-gap.ttl",
    "slices/grounding/lang/tests/counter-examples/surface-inline-blob-payload.ttl",
    "slices/grounding/math/tests/conformance-fixtures/bayesian-network-exact-complete.ttl",
    "slices/grounding/math/tests/conformance-fixtures/dependency-model-complete.ttl",
    "slices/grounding/math/tests/conformance-fixtures/distribution-parameter-positive.ttl",
    "slices/grounding/math/tests/conformance-fixtures/distribution-parameter-right-dimension.ttl",
    "slices/grounding/math/tests/conformance-fixtures/factor-graph-complete.ttl",
    "slices/grounding/math/tests/conformance-fixtures/factor-graph-exact-complete.ttl",
    "slices/grounding/math/tests/conformance-fixtures/joint-table-mass-one.ttl",
    "slices/grounding/math/tests/conformance-fixtures/markov-kernel-exact-complete.ttl",
    "slices/grounding/math/tests/conformance-fixtures/probability-in-bounds.ttl",
    "slices/grounding/math/tests/conformance-fixtures/probability-model-lowering-declared.ttl",
    "slices/grounding/math/tests/conformance-fixtures/projection-confidence-mapping-declared.ttl",
    "slices/grounding/math/tests/conformance-fixtures/projection-parameterization-recorded.ttl",
    "slices/grounding/math/tests/counter-examples/bayesian-network-exact-preservation-violated.ttl",
    "slices/grounding/math/tests/counter-examples/distribution-parameter-negative.ttl",
    "slices/grounding/math/tests/counter-examples/distribution-parameter-relational-dimension.ttl",
    "slices/grounding/math/tests/counter-examples/distribution-parameter-wrong-dimension.ttl",
    "slices/grounding/math/tests/counter-examples/exact-preservation-violated.ttl",
    "slices/grounding/math/tests/counter-examples/factor-graph-exact-preservation-violated.ttl",
    "slices/grounding/math/tests/counter-examples/factor-graph-incomplete.ttl",
    "slices/grounding/math/tests/counter-examples/incomplete-dependency-model.ttl",
    "slices/grounding/math/tests/counter-examples/ingest-run-unliftable.ttl",
    "slices/grounding/math/tests/counter-examples/markov-kernel-exact-preservation-violated.ttl",
    "slices/grounding/math/tests/counter-examples/missing-probability-model-lowering.ttl",
    "slices/grounding/math/tests/counter-examples/probability-out-of-bounds-signed.ttl",
    "slices/grounding/math/tests/counter-examples/probability-out-of-bounds.ttl",
    "slices/grounding/math/tests/counter-examples/projection-confidence-as-probability.ttl",
    "slices/grounding/math/tests/counter-examples/projection-dropped-parameterization.ttl",
    "slices/grounding/math/tests/fixtures/random-variable-distribution.ttl",
];
