// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Embed the verify "bad-example" query set — `queries/verify/*.rq` plus every
//! `slices/**/queries/verify/*.rq` — into the binary at compile time, so the
//! production verify lane (`crates/pipeline`, `gmeow-dev-cli`) never walks the
//! disk at runtime to assemble it. See `crate::verify::embedded_verify_queries`.
//!
//! Emits `OUT_DIR/verify_queries.rs`: a `pub static VERIFY_QUERIES: &[(&str,
//! &str)]` of `(stem, sparql_text)` pairs, sorted by stem (a `BTreeMap` walk),
//! each sparql text pulled in via `include_str!` on an absolute path so the
//! authored `.rq` files stay the single source of truth and edits to them
//! re-trigger this build. A stem collision between two source files (top-level
//! vs. slice, or slice vs. slice) is a hard build-time error — never a silent
//! dedup/overwrite.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    // crates/logic → workspace root is two levels up.
    let workspace = Path::new(&manifest)
        .join("..")
        .join("..")
        .canonicalize()
        .expect("canonicalize workspace root from CARGO_MANIFEST_DIR");

    let mut by_stem: BTreeMap<String, PathBuf> = BTreeMap::new();

    let top = workspace.join("queries").join("verify");
    println!("cargo:rerun-if-changed={}", top.display());
    collect_rq(&top, &mut by_stem);

    let slices = workspace.join("slices");
    println!("cargo:rerun-if-changed={}", slices.display());
    collect_slice_verify(&slices, &mut by_stem);

    assert!(
        !by_stem.is_empty(),
        "no queries/verify/*.rq or slices/**/queries/verify/*.rq sources found under {} \
         (fail-closed: the embedded verify query set must never be empty)",
        workspace.display()
    );

    let mut out = String::new();
    out.push_str(
        "/// Generated by `crates/logic/build.rs` — DO NOT EDIT.\n\
         /// `(stem, sparql_text)` pairs for every authored verify bad-example query,\n\
         /// sorted by stem. See `crate::verify::embedded_verify_queries`.\n\
         pub static VERIFY_QUERIES: &[(&str, &str)] = &[\n",
    );
    for (stem, path) in &by_stem {
        let path_str = path
            .to_str()
            .unwrap_or_else(|| panic!("non-UTF-8 verify query path: {}", path.display()));
        let _ = writeln!(out, "    ({stem:?}, include_str!({path_str:?})),");
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("verify_queries.rs");
    std::fs::write(&dest, out).expect("write verify_queries.rs");
}

/// Collect `*.rq` files directly under `dir` into `by_stem`, keyed by the file
/// basename without `.rq`. Panics on a stem collision: two source files
/// producing the same stem would silently shadow one query's coverage in the
/// embedded set, which is worse than a loud build failure.
fn collect_rq(dir: &Path, by_stem: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    paths.sort();
    for path in paths {
        if path.extension().is_some_and(|ext| ext == "rq") {
            println!("cargo:rerun-if-changed={}", path.display());
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or_else(|| panic!("non-UTF-8 verify query filename: {}", path.display()))
                .to_owned();
            if let Some(prior) = by_stem.insert(stem.clone(), path.clone()) {
                panic!(
                    "duplicate verify query stem {stem:?}: {} and {} both produce it — \
                     rename one so verify query stems stay globally unique",
                    prior.display(),
                    path.display()
                );
            }
        }
    }
}

/// Recurse `slices/**`, collecting `queries/verify/*.rq` under every directory
/// (at any depth) that has one — mirrors `slices/<group>/<slice>/queries/verify/`
/// without hardcoding the two-level group/slice shape.
fn collect_slice_verify(dir: &Path, by_stem: &mut BTreeMap<String, PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    paths.sort();
    for path in paths {
        if !path.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let verify = path.join("queries").join("verify");
        if verify.is_dir() {
            println!("cargo:rerun-if-changed={}", verify.display());
            collect_rq(&verify, by_stem);
        }
        collect_slice_verify(&path, by_stem);
    }
}
