// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Embed the complete authored reasoned-graph verification query set.
//!
//! Bundle-import producer identity belongs to the dependency-light
//! `gmeow-bundle-import` leaf. Keeping that fingerprint here made every unrelated
//! workspace source edit rebuild the reasoning core and invalidate the shared pack.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "../../build-support/embedded_logic_inputs.rs"]
mod embedded_logic_inputs;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let workspace = manifest
        .join("../..")
        .canonicalize()
        .expect("workspace root");
    embed_verify_queries(&workspace);
}

/// Preserve the pre-existing build-script authority that embeds every authored
/// `queries/verify/*.rq` source into `OUT_DIR/verify_queries.rs` fail-closed.
fn embed_verify_queries(workspace: &Path) {
    let by_stem = embedded_logic_inputs::verify_queries(workspace);
    let top = workspace.join("queries/verify");
    println!("cargo:rerun-if-changed={}", top.display());
    let slices = workspace.join("slices");
    println!("cargo:rerun-if-changed={}", slices.display());
    assert!(
        !by_stem.is_empty(),
        "the embedded verify query set must never be empty"
    );

    let mut out = String::new();
    out.push_str(
        "/// Generated by `crates/logic/build.rs` -- DO NOT EDIT.\n\
         pub static VERIFY_QUERIES: &[(&str, &str)] = &[\n",
    );
    for (stem, path) in &by_stem {
        println!("cargo:rerun-if-changed={}", path.display());
        let path = path
            .to_str()
            .unwrap_or_else(|| panic!("non-UTF-8 verify query path: {}", path.display()));
        let _ = writeln!(out, "    ({stem:?}, include_str!({path:?})),");
    }
    out.push_str("];\n");
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    std::fs::write(Path::new(&out_dir).join("verify_queries.rs"), out)
        .expect("write verify_queries.rs");
}
