from __future__ import annotations

import json
from pathlib import Path

from rdflib import RDF, Graph, Literal, Namespace, URIRef

from gmeow_tools.references import (
    CitationCandidate,
    build_bibtex,
    build_csl_json,
    build_markdown,
    candidates_to_graph,
    dedupe_candidates,
    extract_candidates_from_text,
    write_reference_exports,
)
from gmeow_tools.validate import run_shacl

GMEOW = Namespace("https://blackcatinformatics.ca/gmeow/")
EX = Namespace("https://example.org/references/")


def test_extract_candidates_from_urls_dois_and_bibliographic_strings() -> None:
    text = """
    See https://schema.org/ and https://doi.org/10.1234/example.
    gmeow:bibliographicCitation "Diallo, A. (2026). Grounded Retrieval."
    """

    candidates = dedupe_candidates(
        extract_candidates_from_text(
            text,
            citing_iri=str(EX.source),
            citing_label="source.md",
            citing_location="source.md",
        )
    )

    cited = {candidate.cited_iri for candidate in candidates}
    assert "https://schema.org/" in cited
    assert "https://doi.org/10.1234/example" in cited
    assert any(candidate.cited_kind == "bibliographic" for candidate in candidates)


def test_candidates_to_graph_uses_citation_act_shape() -> None:
    graph = candidates_to_graph(
        [
            CitationCandidate(
                citing_iri=str(EX.claim),
                citing_label="Claim carrier",
                citing_location="tests/source.ttl:1",
                cited_iri="https://schema.org/",
                cited_label="Schema.org",
                cited_kind="url",
                selector_locator="tests/source.ttl:1",
            )
        ]
    )

    citation = next(graph.subjects(RDF.type, GMEOW.CitationAct))
    assert (citation, GMEOW.citingEntity, EX.claim) in graph
    assert (citation, GMEOW.citedEntity, URIRef("https://schema.org/")) in graph
    assert (citation, GMEOW.citationIntent, GMEOW.intentBridgedByReference) in graph

    result = run_shacl(graph)
    assert result.ok, "\n".join(result.errors)


def test_reference_exports_are_deterministic_and_tool_shaped(tmp_path: Path) -> None:
    graph = Graph()
    graph.add((EX.paper, RDF.type, GMEOW.CreativeWork))
    graph.add((EX.paper, GMEOW.sourceLocation, Literal("https://doi.org/10.1234/x")))
    graph.add((EX.paper, GMEOW.datePublished, Literal("2026-06-14")))
    graph.add((EX.citation, RDF.type, GMEOW.CitationAct))
    graph.add((EX.citation, GMEOW.citedEntity, EX.paper))
    graph.add((EX.citation, GMEOW.citingEntity, EX.source))
    graph.add((EX.citation, GMEOW.citationIntent, GMEOW.intentCitesAsDataSource))

    csl = json.loads(build_csl_json(graph))
    assert csl == [
        {
            "URL": "https://doi.org/10.1234/x",
            "id": "paper-5c965d1e",
            "issued": {"date-parts": [[2026, 6, 14]]},
            "title": "https://example.org/references/paper",
            "type": "webpage",
        }
    ]

    assert "@misc{paper-5c965d1e," in build_bibtex(graph)
    assert "| https://example.org/references/paper |" in build_markdown(graph)

    write_reference_exports(
        graph,
        csl_path=tmp_path / "references.csl.json",
        bib_path=tmp_path / "references.bib",
        md_path=tmp_path / "references.md",
        name="references",
        source_hash="abc123",
    )
    assert json.loads((tmp_path / "references.csl.json").read_text("utf-8"))
    assert "GENERATED by gmeow references" in (tmp_path / "references.bib").read_text(
        "utf-8"
    )
    assert "GENERATED by gmeow references" in (tmp_path / "references.md").read_text(
        "utf-8"
    )
