from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest
from rdflib import RDF, Graph, Literal, Namespace, URIRef

import gmeow_tools.references as references
from gmeow_tools.references import (
    CitationCandidate,
    _gh_pr_review_summaries,
    _run_gh,
    build_bibtex,
    build_csl_json,
    build_markdown,
    candidates_to_graph,
    dedupe_candidates,
    extract_candidates_from_text,
    write_reference_exports,
)
from gmeow_tools.validate import run_shacl

GMEOW = Namespace("https://blackcatinformatics.ca/gmeow/")
EX = Namespace("https://example.org/references/")


def test_extract_candidates_from_urls_dois_and_bibliographic_strings() -> None:
    text = """
    See https://schema.org/ and https://doi.org/10.1234/example.
    gmeow:bibliographicCitation "Diallo, A. (2026). Grounded Retrieval."
    """

    candidates = dedupe_candidates(
        extract_candidates_from_text(
            text,
            citing_iri=str(EX.source),
            citing_label="source.md",
            citing_location="source.md",
        )
    )

    cited = {candidate.cited_iri for candidate in candidates}
    assert "https://schema.org/" in cited
    assert "https://doi.org/10.1234/example" in cited
    assert any(candidate.cited_kind == "bibliographic" for candidate in candidates)


def test_candidates_to_graph_uses_citation_act_shape() -> None:
    graph = candidates_to_graph(
        [
            CitationCandidate(
                citing_iri=str(EX.claim),
                citing_label="Claim carrier",
                citing_location="tests/source.ttl:1",
                cited_iri="https://schema.org/",
                cited_label="Schema.org",
                cited_kind="url",
                selector_locator="tests/source.ttl:1",
            )
        ]
    )

    citation = next(graph.subjects(RDF.type, GMEOW.CitationAct))
    assert (citation, GMEOW.citingEntity, EX.claim) in graph
    assert (citation, GMEOW.citedEntity, URIRef("https://schema.org/")) in graph
    assert (citation, GMEOW.citationIntent, GMEOW.intentBridgedByReference) in graph

    result = run_shacl(graph)
    assert result.ok, "\n".join(result.errors)


def test_reference_exports_are_deterministic_and_tool_shaped(tmp_path: Path) -> None:
    graph = Graph()
    graph.add((EX.paper, RDF.type, GMEOW.CreativeWork))
    graph.add((EX.paper, GMEOW.sourceLocation, Literal("https://doi.org/10.1234/x")))
    graph.add((EX.paper, GMEOW.datePublished, Literal("2026-06-14")))
    graph.add((EX.citation, RDF.type, GMEOW.CitationAct))
    graph.add((EX.citation, GMEOW.citedEntity, EX.paper))
    graph.add((EX.citation, GMEOW.citingEntity, EX.source))
    graph.add((EX.citation, GMEOW.citationIntent, GMEOW.intentCitesAsDataSource))

    csl = json.loads(build_csl_json(graph))
    assert csl == [
        {
            "URL": "https://doi.org/10.1234/x",
            "id": "paper-5c965d1e",
            "issued": {"date-parts": [[2026, 6, 14]]},
            "title": "https://example.org/references/paper",
            "type": "webpage",
        }
    ]

    assert "@misc{paper-5c965d1e," in build_bibtex(graph)
    assert "| https://example.org/references/paper |" in build_markdown(graph)

    write_reference_exports(
        graph,
        csl_path=tmp_path / "references.csl.json",
        bib_path=tmp_path / "references.bib",
        md_path=tmp_path / "references.md",
        name="references",
        source_hash="abc123",
    )
    assert json.loads((tmp_path / "references.csl.json").read_text("utf-8"))
    assert "GENERATED by gmeow references" in (tmp_path / "references.bib").read_text(
        "utf-8"
    )
    assert "GENERATED by gmeow references" in (tmp_path / "references.md").read_text(
        "utf-8"
    )


def test_run_gh_wraps_missing_cli(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def missing_cli(
        *_args: object, **_kwargs: object
    ) -> subprocess.CompletedProcess[str]:
        raise FileNotFoundError("gh")

    monkeypatch.setattr(subprocess, "run", missing_cli)

    with pytest.raises(RuntimeError, match="gh CLI is not installed"):
        _run_gh(["api", "rate_limit"])


def test_run_gh_wraps_timeout(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def timeout(*_args: object, **_kwargs: object) -> subprocess.CompletedProcess[str]:
        raise subprocess.TimeoutExpired(cmd=["gh"], timeout=120)

    monkeypatch.setattr(subprocess, "run", timeout)

    with pytest.raises(RuntimeError, match="timed out after 120s"):
        _run_gh(["api", "rate_limit"])


def test_review_summary_fetch_tolerates_null_graphql_fields(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    payloads = iter(
        [
            json.dumps({"data": {"repository": {"pullRequests": None}}}),
            json.dumps(
                {
                    "data": {
                        "repository": {
                            "pullRequests": {
                                "nodes": [
                                    {
                                        "number": 1,
                                        "title": "Null review page",
                                        "reviews": None,
                                    }
                                ],
                                "pageInfo": None,
                            }
                        }
                    }
                }
            ),
        ]
    )

    def fake_run_gh(_args: list[str]) -> str:
        return next(payloads)

    monkeypatch.setattr(references, "_run_gh", fake_run_gh)

    assert _gh_pr_review_summaries("owner/repo") == []
    assert _gh_pr_review_summaries("owner/repo") == []
