// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The XCL **writer**: [`LogicProgram`] → XCL XML (`generated/cl/gmeow.xcl`).
//!
//! See [`crate::xcl`] for the two-channel architecture. This module emits the idiomatic
//! sentence channel (`rules` + `formulas`) as readable XCL2 elements and the RDF/predication
//! channel (everything else) as canonical N-Triples inside the single
//! `RDF_META_ELEMENT` element.

use gmeow_errors::Diag;

use crate::ir::{Formula, LogicAxiom, LogicProgram, Term};
use crate::nt::nt_escape_literal;
use crate::projections::{ProjectionResult, rdf, target_meta};

use super::{RDF_META_ELEMENT, ROOT_ELEMENT, xml_escape_attr, xml_escape_text};

use purrdf::{SerializeGraph, parse_dataset, serialize_dataset};

/// `xsd:integer` — the datatype emitted for a path shape's integer min/max depths.
const XSD_INTEGER: &str = "http://www.w3.org/2001/XMLSchema#integer";

/// Project a [`LogicProgram`] to XCL XML.
///
/// Returns `Err` if the lossless RDF/predication carrier cannot be built (the
/// canonical-RDF-1.2 projection or its re-serialization failing is an invariant break, not a
/// recoverable condition) — surfacing a structured error to `compile_program` exactly like the
/// sibling projectors, rather than panicking.
pub fn project_xcl(program: &LogicProgram) -> gmeow_errors::Result<ProjectionResult> {
    // Registry is the single source of truth for (preservation, complexity, drops).
    let (kind, cx, _) = target_meta("xcl");

    let mut lines: Vec<String> = vec![
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>".to_owned(),
        "<!-- GENERATED by `gmeow logic compile` - DO NOT EDIT. -->".to_owned(),
        "<!-- XCL (eXtended Common Logic Markup Language) projection of the canonical logic program. -->"
            .to_owned(),
        format!("<{ROOT_ELEMENT}>"),
    ];

    // ── Idiomatic sentence channel (human-readable rendering) ───────────────────
    // Rules and formulas are rendered as readable XCL2 elements. This channel is WRITE-ONLY:
    // the canonical IR carries an `obj_is_literal` bit on a rule term (and a rule's minted
    // reifier-node identity) that idiomatic sentence syntax cannot express, so reconstructing
    // the byte-exact IR from the sentences would be lossy. The lossless carrier is the
    // RDF/predication channel below (the Exact `canonical-rdf12` leg), from which the reader
    // reconstructs the WHOLE program — rules and formulas included. The sentence elements are
    // therefore an idiomatic view over the same content, never the round-trip authority.
    lines.push("  <!-- Rules (idiomatic XCL2 sentences; human-readable view) -->".to_owned());
    lines.push("  <sentences>".to_owned());
    for rule in &program.rules {
        lines.push(format!("    {}", rule_to_xml(rule)));
    }
    for formula in &program.formulas {
        lines.push(format!("    {}", formula_to_xml(formula)));
    }
    lines.push("  </sentences>".to_owned());

    // ── RDF / predication channel (the lossless round-trip carrier): the WHOLE program
    //    — axioms (+ scope), rules, formulas, contracts, correspondences — serialized as
    //    canonical N-Triples inside a single `<gmeow-rdf-meta>` element. ────────────────────
    let meta_nt = meta_ntriples(program)?;
    lines.push(
        "  <!-- RDF/predication channel: canonical N-Triples (round-trip authority). -->"
            .to_owned(),
    );
    if meta_nt.is_empty() {
        lines.push(format!("  <{RDF_META_ELEMENT}></{RDF_META_ELEMENT}>"));
    } else {
        // A leading newline keeps the payload visually distinct; roxmltree preserves it and the
        // reader parses N-Triples line-by-line, so it is round-trip-neutral.
        let body = meta_nt.join("\n");
        lines.push(format!(
            "  <{RDF_META_ELEMENT}>\n{}\n  </{RDF_META_ELEMENT}>",
            xml_escape_text(&body)
        ));
    }

    lines.push(format!("</{ROOT_ELEMENT}>"));

    let content = format!("{}\n", lines.join("\n"));
    Ok(ProjectionResult {
        target: "xcl".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        // Exact target: every construct is carried (sentence channel verbatim, RDF channel via
        // the lossless canonical-RDF-1.2 leg). Nothing is dropped, so the writer never touches
        // the loss store — the drop-less row keeps its pure signature.
    })
}

// --------------------------------------------------------------------------- //
// Idiomatic sentence channel — rules
// --------------------------------------------------------------------------- //

/// Encode a [`LogicAxiom`] (a Horn triple) as an XCL2 `<atom>` predication.
fn axiom_atom(axiom: &LogicAxiom) -> String {
    let rel = format!("<name>{}</name>", xml_escape_text(&axiom.predicate));
    let subj = horn_term(&axiom.subject, false);
    let obj = horn_term(&axiom.obj, axiom.obj_is_literal);
    format!("<atom><rel>{rel}</rel><arg>{subj}</arg><arg>{obj}</arg></atom>")
}

/// A Horn subject/object argument: a `?var`, a literal, or a `<name>` IRI.
fn horn_term(value: &str, is_literal: bool) -> String {
    if let Some(var) = value.strip_prefix('?') {
        format!("<var>{}</var>", xml_escape_text(var))
    } else if is_literal {
        // A plain literal in the Horn fragment (the canonical IR carries no datatype on
        // `LogicAxiom.obj`; that detail lives in the RDF channel).
        format!("<literal>{}</literal>", xml_escape_text(value))
    } else {
        format!("<name>{}</name>", xml_escape_text(value))
    }
}

/// Encode a [`crate::ir::LogicRule`] as `<rule><body>…</body><head>…</head></rule>`, or — for
/// the degenerate empty-body rule — the bare head atom (a fact).
fn rule_to_xml(rule: &crate::ir::LogicRule) -> String {
    let head = axiom_atom(&rule.head);

    let mut body_parts: Vec<String> = Vec::new();
    for ba in &rule.body {
        let atom = axiom_atom(ba);
        if ba.negated {
            body_parts.push(format!("<not>{atom}</not>"));
        } else {
            body_parts.push(atom);
        }
    }
    // `distinct_pairs` (a, b) → a negated equality `<not><atom>(= ?a ?b)</atom></not>`.
    for (a, b) in &rule.distinct_pairs {
        body_parts.push(format!(
            "<not><atom><rel><name>=</name></rel><arg>{}</arg><arg>{}</arg></atom></not>",
            var_term(a),
            var_term(b)
        ));
    }

    if body_parts.is_empty() {
        // A fact: emit the head atom alone.
        return head;
    }

    format!(
        "<rule><body>{}</body><head>{head}</head></rule>",
        body_parts.join("")
    )
}

/// Normalize a possibly-`?`-prefixed variable string to an XCL2 `<var>` element.
fn var_term(s: &str) -> String {
    let name = s.strip_prefix('?').unwrap_or(s);
    format!("<var>{}</var>", xml_escape_text(name))
}

// --------------------------------------------------------------------------- //
// Idiomatic sentence channel — formulas
// --------------------------------------------------------------------------- //

/// Encode a [`Formula`] recursively as an XCL2 sentence element.
fn formula_to_xml(formula: &Formula) -> String {
    match formula {
        Formula::Atom { relation, args } => {
            let rel = term_to_xml(relation);
            let mut parts = format!("<rel>{rel}</rel>");
            for a in args {
                parts.push_str(&format!("<arg>{}</arg>", term_to_xml(a)));
            }
            format!("<atom>{parts}</atom>")
        }
        Formula::Not(inner) => format!("<not>{}</not>", formula_to_xml(inner)),
        Formula::And(fs) => {
            let parts: String = fs.iter().map(formula_to_xml).collect();
            format!("<and>{parts}</and>")
        }
        Formula::Or(fs) => {
            let parts: String = fs.iter().map(formula_to_xml).collect();
            format!("<or>{parts}</or>")
        }
        Formula::Implies(a, b) => {
            format!(
                "<implies>{}{}</implies>",
                formula_to_xml(a),
                formula_to_xml(b)
            )
        }
        Formula::Iff(a, b) => {
            format!("<iff>{}{}</iff>", formula_to_xml(a), formula_to_xml(b))
        }
        Formula::Forall { vars, body } => {
            let vs: String = vars
                .iter()
                .map(|v| format!("<var>{}</var>", xml_escape_text(v)))
                .collect();
            format!("<forall><vars>{vs}</vars>{}</forall>", formula_to_xml(body))
        }
        Formula::Exists { vars, body } => {
            let vs: String = vars
                .iter()
                .map(|v| format!("<var>{}</var>", xml_escape_text(v)))
                .collect();
            format!("<exists><vars>{vs}</vars>{}</exists>", formula_to_xml(body))
        }
    }
}

/// Encode a [`Term`] as an XCL2 term element.
fn term_to_xml(term: &Term) -> String {
    match term {
        Term::Var(n) => format!("<var>{}</var>", xml_escape_text(n)),
        Term::Iri(i) => format!("<name>{}</name>", xml_escape_text(i)),
        Term::Literal { lexical, datatype } => match datatype {
            None => format!("<literal>{}</literal>", xml_escape_text(lexical)),
            Some(dt) => format!(
                "<literal datatype=\"{}\">{}</literal>",
                xml_escape_attr(dt),
                xml_escape_text(lexical)
            ),
        },
        Term::SequenceMarker(n) => format!("<seq>{}</seq>", xml_escape_text(n)),
        // A function-term application → an `<app>` element whose head names the function symbol
        // and whose body is the ordered argument terms (each recursively rendered, so a nested
        // application nests its `<app>` elements).
        Term::App { symbol, args } => {
            let inner: String = args.iter().map(term_to_xml).collect();
            format!("<app><name>{}</name>{inner}</app>", xml_escape_text(symbol))
        }
    }
}

// --------------------------------------------------------------------------- //
// RDF / predication channel — canonical N-Triples carrier
// --------------------------------------------------------------------------- //

/// Assemble the RDF/predication channel as sorted, deduplicated canonical N-Triples lines.
/// This is the **lossless round-trip carrier** — built only from serializers the canonical
/// frontend round-trips at its fixpoint:
///
/// * **the whole program** — axioms (+ scope), rules, formulas, and contracts → the Exact
///   `canonical-rdf12` projection (which reifies rule head/body and full-FOL formula trees and
///   emits contract facets, all of which `parse_logic_dataset` reconstructs);
/// * **correspondences** → `project_correspondence` (round-trips to a content-key-equal program).
///
/// `path_shapes` are emitted DIRECTLY as the `logic:PathShape` triples the frontend's
/// `extract_path_shapes` reads (a faithful inverse). `transaction_programs` (a correspondence
/// leg's `gm:path` body) are emitted as the `gm:` leg-body triples the frontend's
/// `extract_leg_programs` reads (the faithful inverse of `parse_leg_path`). The Exact claim
/// therefore carries every construct losslessly.
///
/// Sorting + dedup make the emitted N-Triples byte-stable across regenerations regardless of the
/// serializer's internal ordering. Returns `Err` if the canonical-RDF-1.2 leg (or its
/// re-serialization) fails — the lossless carrier cannot be assembled, an invariant break
/// surfaced to the caller, not a panic.
fn meta_ntriples(program: &LogicProgram) -> gmeow_errors::Result<Vec<String>> {
    let mut lines: Vec<String> = Vec::new();

    // (0) Path shapes — emitted as the logic:PathShape triples `extract_path_shapes` reads.
    for shape in &program.path_shapes {
        lines.extend(path_shape_ntriples(shape));
    }

    // (0b) Transaction programs (correspondence leg bodies) — emitted as the `gm:` leg-body
    //      triples `extract_leg_programs` reads. A single counter mints deterministic structural
    //      node/cell IRIs so the sorted output is byte-stable.
    let mut leg_node_counter: usize = 0;
    for tp in &program.transaction_programs {
        let body_root = emit_leg_path(&tp.iri, &tp.body, &mut lines, &mut leg_node_counter);
        lines.push(nt_triple(&tp.iri, &gm("path"), &nt_iri(&body_root)));
    }

    // (1) The whole program (axioms + scope + rules + formulas + contracts) → the lossless
    //     canonical RDF 1.2 projection. A correspondence's `logic:` triples and a path shape's
    //     defining triples are owned by their own channels above, so exclude any axiom whose
    //     subject is a correspondence node (or child) or a path-shape node — emitting them twice
    //     with a different lexical form would break idempotence.
    let corr_subjects = correspondence_subjects(program);
    let path_subjects: std::collections::HashSet<&str> =
        program.path_shapes.iter().map(|p| p.iri.as_str()).collect();
    let axioms: Vec<_> = program
        .axioms
        .iter()
        .filter(|a| {
            !is_correspondence_owned(&a.subject, &corr_subjects)
                && !path_subjects.contains(a.subject.as_str())
        })
        .cloned()
        .collect();
    let canon_meta = LogicProgram::new(
        axioms,
        program.rules.clone(),
        program.contracts.clone(),
        program.source_iri.clone(),
    )
    .with_formulas(program.formulas.clone());
    let ttl = rdf::project_canonical_rdf12(&canon_meta)
        .map_err(|e| {
            Diag::of_kind(crate::error::Xcl {
                detail: format!("XCL meta channel: canonical-rdf12 projection failed: {e}"),
            })
        })?
        .content;
    lines.extend(rdf_text_to_ntriples(ttl.as_bytes(), "text/turtle")?);

    // (2) Correspondences → the faithful correspondence N-Triples projection.
    if !program.correspondences.is_empty() {
        let cp = crate::projections::correspondence::CorrespondenceProgram::new(
            program.correspondences.clone(),
            Vec::new(),
            crate::ir::PreservationKind::Exact,
        );
        let nt = crate::projections::correspondence::project_correspondence(&cp);
        lines.extend(rdf_text_to_ntriples(
            nt.as_bytes(),
            "application/n-triples",
        )?);
    }

    lines.sort();
    lines.dedup();
    Ok(lines)
}

/// The `gm:` namespace (`gmeow:`) — the leg-body path vocabulary the transaction layer uses.
const GM_NAMESPACE: &str = "https://blackcatinformatics.ca/gmeow/";
/// `rdf:type`.
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// A `gm:`-namespaced IRI.
fn gm(local: &str) -> String {
    format!("{GM_NAMESPACE}{local}")
}

/// Emit the structural `gm:` triples for a [`crate::ir::LegPath`] (the faithful inverse of the
/// frontend's `parse_leg_path`) into `lines`, returning the body node IRI a `gm:path` (or a
/// parent combinator) should reference.
fn emit_leg_path(
    base: &str,
    path: &crate::ir::LegPath,
    lines: &mut Vec<String>,
    counter: &mut usize,
) -> String {
    use crate::ir::LegPath;
    match path {
        LegPath::Step(pred) => pred.clone(),
        LegPath::Inverse(inner) => {
            let node = format!("{base}/legnode/{counter}");
            *counter += 1;
            lines.push(nt_triple(&node, RDF_TYPE, &nt_iri(&gm("InversePath"))));
            let inner_node = emit_leg_path(base, inner, lines, counter);
            lines.push(nt_triple(&node, &gm("pathStep"), &nt_iri(&inner_node)));
            node
        }
        LegPath::Seq(members) => emit_leg_list(
            base,
            members,
            &gm("SeqPath"),
            &gm("pathSteps"),
            lines,
            counter,
        ),
        LegPath::Alt(members) => emit_leg_list(
            base,
            members,
            &gm("AltPath"),
            &gm("pathAlts"),
            lines,
            counter,
        ),
    }
}

/// Emit a `gm:SeqPath` / `gm:AltPath` combinator node and its `gm:pathNext`-linked cell chain,
/// returning the combinator node IRI.
fn emit_leg_list(
    base: &str,
    members: &[crate::ir::LegPath],
    type_iri: &str,
    head_pred: &str,
    lines: &mut Vec<String>,
    counter: &mut usize,
) -> String {
    let node = format!("{base}/legnode/{counter}");
    *counter += 1;
    lines.push(nt_triple(&node, RDF_TYPE, &nt_iri(type_iri)));
    // Mint every cell IRI first so the (node head_pred cell0) and (cell_i pathNext cell_{i+1})
    // links use a stable, deterministic naming independent of recursion order.
    let cell_iris: Vec<String> = members
        .iter()
        .map(|_| {
            let cell = format!("{base}/legcell/{counter}");
            *counter += 1;
            cell
        })
        .collect();
    for (i, member) in members.iter().enumerate() {
        let cell = &cell_iris[i];
        let member_node = emit_leg_path(base, member, lines, counter);
        lines.push(nt_triple(cell, &gm("pathItem"), &nt_iri(&member_node)));
        if let Some(next) = cell_iris.get(i + 1) {
            lines.push(nt_triple(cell, &gm("pathNext"), &nt_iri(next)));
        }
    }
    if let Some(first) = cell_iris.first() {
        lines.push(nt_triple(&node, head_pred, &nt_iri(first)));
    }
    node
}

/// Emit a [`PathShapeIr`](crate::ir::PathShapeIr) as the `logic:PathShape` N-Triples its frontend
/// extractor reads (a faithful inverse of `extract_path_shapes`).
fn path_shape_ntriples(shape: &crate::ir::PathShapeIr) -> Vec<String> {
    let s = &shape.iri;
    let logic = |local: &str| format!("{}{local}", crate::ir::LOGIC_NAMESPACE);

    let mut out = vec![nt_triple(s, RDF_TYPE, &nt_iri(&logic("PathShape")))];
    match &shape.base {
        crate::ir::PathBase::NamedPredicate(p) => {
            out.push(nt_triple(s, &logic("pathStepPredicate"), &nt_iri(p)));
        }
        crate::ir::PathBase::Wildcard => {
            out.push(nt_triple(
                s,
                &logic("pathWildcard"),
                &nt_plain_literal("true"),
            ));
        }
    }
    // Depths are integers in the IR (`u32`); emit them as typed `xsd:integer` literals so the
    // generated N-Triples is type-faithful. The frontend's `parse_positive_int` reads the lexical
    // regardless, so this round-trips.
    out.push(nt_triple(
        s,
        &logic("pathMinDepth"),
        &nt_typed_literal(&shape.min_depth.to_string(), XSD_INTEGER),
    ));
    if let Some(max) = shape.max_depth {
        out.push(nt_triple(
            s,
            &logic("pathMaxDepth"),
            &nt_typed_literal(&max.to_string(), XSD_INTEGER),
        ));
    }
    if let Some(ns) = &shape.namespace_scope {
        out.push(nt_triple(
            s,
            &logic("pathNamespaceScope"),
            &nt_plain_literal(ns),
        ));
    }
    if let Some(param) = &shape.depth_param {
        out.push(nt_triple(
            s,
            &logic("pathDepthParam"),
            &nt_plain_literal(param),
        ));
    }
    out
}

/// The set of correspondence node IRIs whose flat axioms are owned by the correspondence channel
/// (the correspondence individuals + the singleton `correspondence-program` node).
fn correspondence_subjects(program: &LogicProgram) -> Vec<String> {
    let mut subjects: Vec<String> = program
        .correspondences
        .iter()
        .map(|c| c.iri.clone())
        .collect();
    subjects.push(format!(
        "{}correspondence-program",
        crate::ir::LOGIC_NAMESPACE
    ));
    subjects
}

/// Whether `subject` is a correspondence node (exact match) or one of its child nodes.
fn is_correspondence_owned(subject: &str, corr_subjects: &[String]) -> bool {
    corr_subjects.iter().any(|c| {
        subject == c
            || subject
                .strip_prefix(c.as_str())
                .is_some_and(|r| r.starts_with('/'))
    })
}

/// Parse RDF `bytes` of `media_type` and re-serialize to canonical N-Triples lines. Returns
/// `Err` if the projection's own serialized output cannot be re-parsed or re-serialized (an
/// invariant break in the canonical leg, surfaced to the caller rather than panicking).
fn rdf_text_to_ntriples(bytes: &[u8], media_type: &str) -> gmeow_errors::Result<Vec<String>> {
    let ds = parse_dataset(bytes, media_type, None).map_err(|e| {
        Diag::of_kind(crate::error::Xcl {
            detail: format!("XCL meta channel: re-parse of {media_type} failed: {e}"),
        })
    })?;
    let nt = serialize_dataset(&ds, "application/n-triples", SerializeGraph::DefaultGraph)
        .map_err(|e| {
            Diag::of_kind(crate::error::Xcl {
                detail: format!("XCL meta channel: N-Triples serialization failed: {e}"),
            })
        })?;
    let text = String::from_utf8(nt).map_err(|e| {
        Diag::of_kind(crate::error::Xcl {
            detail: format!("XCL meta channel: N-Triples not UTF-8: {e}"),
        })
    })?;
    Ok(text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .map(str::to_owned)
        .collect())
}

// --------------------------------------------------------------------------- //
// N-Triples term codecs
// --------------------------------------------------------------------------- //

/// Assemble one N-Triples statement `<s> <p> o .` from a subject IRI, a predicate IRI, and an
/// already-encoded object term.
fn nt_triple(subject: &str, predicate: &str, object: &str) -> String {
    format!("{} {} {object} .", nt_iri(subject), nt_iri(predicate))
}

/// Encode an IRI as an N-Triples `<…>`. See [`crate::nt::nt_escape_iri`] for the shared
/// inner-content escaper; this wraps it in the angle brackets.
fn nt_iri(iri: &str) -> String {
    format!("<{}>", crate::nt::nt_escape_iri(iri))
}

/// Encode a plain (`xsd:string`) literal as an N-Triples `"…"`.
fn nt_plain_literal(lexical: &str) -> String {
    format!("\"{}\"", nt_escape_literal(lexical))
}

/// Encode a typed literal as an N-Triples `"…"^^<dt>`.
fn nt_typed_literal(lexical: &str, datatype: &str) -> String {
    format!("\"{}\"^^{}", nt_escape_literal(lexical), nt_iri(datatype))
}
