// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The EDOAL correspondence lowering: the get leg + relation lattice + measure → one
//! `align:Alignment` (EDOAL level-2) per profile.
//!
//! EDOAL is an under-approximation of the correspondence: it drops the SOL caveats,
//! the put leg, and world/standpoint scope, so the ledger-row preservation is
//! `SoundUnder`. It renders from the SAME [`crate::projections::get_leg`] model
//! the SPARQL lowering uses.
//! The triples are built as N-Triples with a deterministic first-seen blank order and
//! rendered through the **wasm-clean** canonical-Turtle serializer
//! ([`gmeow_rdf::turtle_render`]) — no oxigraph: the serializer's object ordering is a
//! pure function of subtree content (every EDOAL blank inlines), so building the graph
//! and rendering reproduces the committed bytes byte-for-byte.

use std::collections::BTreeMap;

use gmeow_rdf::{parse_dataset, NativeRdfFormat};

use crate::ingest::prefixes::registry_pairs;
use crate::ingest::DslView;
use crate::projections::correspondence_frontend::CorrespondenceLookup;
use crate::projections::correspondence_gate::assert_relation_no_overclaim;
use crate::projections::get_leg::{
    curie, local, projections, Atom, MappingPattern, ProfileBinding, ProjectionCell, PROFILES,
};
use crate::projections::{correspondence_result, ProjectionResult};

const ONTOLOGY_IRI: &str = "https://blackcatinformatics.ca/gmeow";

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const RDF_FIRST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#first";
const RDF_REST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest";
const RDF_NIL: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil";
const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const RDFS_COMMENT: &str = "http://www.w3.org/2000/01/rdf-schema#comment";
const RDFS_SEE_ALSO: &str = "http://www.w3.org/2000/01/rdf-schema#seeAlso";
const DCTERMS_IS_PART_OF: &str = "http://purl.org/dc/terms/isPartOf";

const ALIGN: &str = "http://knowledgeweb.semanticweb.org/heterogeneity/alignment#";
const EDOAL: &str = "http://ns.inria.org/edoal/1.0/#";
const XSD_DOUBLE: &str = "http://www.w3.org/2001/XMLSchema#double";

const GM_LANGUAGE_TAG: &str = "https://blackcatinformatics.ca/gmeow/languageTag";
const GM_BCP47_TAG: &str = "https://blackcatinformatics.ca/gmeow/bcp47Tag";

const GENERATED_BANNER: &str =
    "GENERATED by `gmeow regenerate` (mappings) from mapping-dsl/ — DO NOT EDIT.";
const EN_TAG: &str = "x-gmeow-english";

/// The artifacts + per-correspondence loss ledger of the EDOAL lowering.
pub struct EdoalLowering {
    /// `<profile>.edoal.ttl` → Turtle.
    pub alignments: BTreeMap<String, String>,
    /// One [`ProjectionResult`] per correspondence (cell::profile binding) that drops
    /// something — the per-correspondence preservation rows for the loss ledger.
    pub ledger: Vec<ProjectionResult>,
}

/// Lower every profile's EDOAL alignment, keyed `<profile>.edoal.ttl`, plus the
/// per-correspondence loss ledger. `dsl` is the merged mapping-DSL view; `onto` the
/// merged ontology view (the language-tag map).
pub fn lower_edoal(
    dsl: &DslView,
    onto: &DslView,
    lookup: &CorrespondenceLookup,
) -> Result<EdoalLowering, String> {
    let cells = projections(dsl)?;
    let tag_map = build_tag_map(onto);
    let prefixes = registry_pairs();
    let mut alignments = BTreeMap::new();
    let mut ledger: Vec<ProjectionResult> = Vec::new();
    for profile in PROFILES {
        let emitted = emit_edoal_nt(&cells, profile, &tag_map, lookup)?;
        // Parse the freshly-built N-Triples into a wasm-clean dataset and render it
        // through the canonical-Turtle serializer (object order is content-derived, so
        // no oxigraph re-dump is needed to fix the blank order).
        let dataset = parse_dataset(
            emitted.nt.as_bytes(),
            NativeRdfFormat::NTriples.media_type(),
            None,
        )
        .map_err(|e| format!("EDOAL NT parse error: {e}"))?;
        let body = gmeow_rdf::turtle_render::render(&dataset, &prefixes);
        let text = format!("{}\n", body.trim_end_matches('\n'));
        alignments.insert(format!("{profile}.edoal.ttl"), text);
        ledger.extend(emitted.ledger);
    }
    Ok(EdoalLowering { alignments, ledger })
}

// ── Language-tag retag map ───────────────────────────────────────────────────────

fn build_tag_map(onto: &DslView) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    for (subject, object) in onto.quads_with_predicate(GM_LANGUAGE_TAG) {
        let (Some(internal), Some(subj_iri)) = (object.as_literal(), subject.as_iri()) else {
            continue;
        };
        if let Some(ext) = onto.object_literal(subj_iri, GM_BCP47_TAG) {
            map.insert(internal.to_owned(), ext);
        }
    }
    map
}

fn retag(tag: &str, tag_map: &BTreeMap<String, String>) -> String {
    tag_map.get(tag).cloned().unwrap_or_else(|| tag.to_owned())
}

// ── N-Triples builder ────────────────────────────────────────────────────────────

struct Nt {
    lines: String,
    counter: usize,
}

impl Nt {
    fn new() -> Self {
        Self {
            lines: String::new(),
            counter: 0,
        }
    }

    fn fresh_bnode(&mut self) -> String {
        let label = format!("_:b{}", self.counter);
        self.counter += 1;
        label
    }

    /// A deterministic, **injective** blank-node id for `label`. ASCII alphanumerics
    /// pass through verbatim; every other byte is hex-escaped as `_XX` (and a literal
    /// `_` is itself escaped, so the escape is unambiguous). This avoids the old
    /// many-to-one `non-alnum → '_'` collapse, under which `cell-a_b-0` and
    /// `cell-a-b-0` mapped to the same node and silently merged two cells.
    fn stable_bnode(label: &str) -> String {
        let mut safe = String::with_capacity(label.len());
        for &byte in label.as_bytes() {
            if byte.is_ascii_alphanumeric() {
                safe.push(byte as char);
            } else {
                safe.push_str(&format!("_{byte:02x}"));
            }
        }
        format!("_:n{safe}")
    }

    fn add_iri(&mut self, s: &str, p: &str, o: &str) {
        self.add_raw(s, p, &format!("<{o}>"));
    }

    fn add_bnode_obj(&mut self, s: &str, p: &str, o: &str) {
        self.add_raw(s, p, o);
    }

    fn add_node(&mut self, s: &str, p: &str, o: &str) {
        if o.starts_with("_:") {
            self.add_raw(s, p, o);
        } else {
            self.add_iri(s, p, o);
        }
    }

    fn add_raw(&mut self, subject: &str, pred: &str, object: &str) {
        let subj = if subject.starts_with("_:") {
            subject.to_owned()
        } else {
            format!("<{subject}>")
        };
        self.lines
            .push_str(&format!("{subj} <{pred}> {object} .\n"));
    }

    fn add_lang_literal(&mut self, s: &str, p: &str, text: &str, lang: &str) {
        let obj = format!("{}@{lang}", nt_quote(text));
        self.add_raw(s, p, &obj);
    }

    fn add_string_literal(&mut self, s: &str, p: &str, text: &str) {
        self.add_raw(s, p, &nt_quote(text));
    }

    fn add_typed_literal(&mut self, s: &str, p: &str, text: &str, datatype: &str) {
        let obj = format!("{}^^<{datatype}>", nt_quote(text));
        self.add_raw(s, p, &obj);
    }

    fn attach_list(&mut self, subject: &str, predicate: &str, items: &[String]) {
        let head = self.fresh_bnode();
        self.add_bnode_obj(subject, predicate, &head);
        let mut cur = head;
        for (i, item) in items.iter().enumerate() {
            self.add_node(&cur, RDF_FIRST, item);
            if i + 1 < items.len() {
                let next = self.fresh_bnode();
                self.add_bnode_obj(&cur, RDF_REST, &next);
                cur = next;
            } else {
                self.add_iri(&cur, RDF_REST, RDF_NIL);
            }
        }
    }
}

fn nt_quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for c in text.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── EDOAL emission ────────────────────────────────────────────────────────────

/// The N-Triples body of one profile's EDOAL alignment plus its per-correspondence
/// loss ledger.
#[derive(Debug)]
struct EmittedEdoal {
    nt: String,
    ledger: Vec<ProjectionResult>,
}

fn emit_edoal_nt(
    cells: &[ProjectionCell],
    profile: &str,
    tag_map: &BTreeMap<String, String>,
    lookup: &CorrespondenceLookup,
) -> Result<EmittedEdoal, String> {
    let mut nt = Nt::new();
    let mut ledger: Vec<ProjectionResult> = Vec::new();
    let align = format!("{ONTOLOGY_IRI}/projections/{profile}");
    let en = retag(EN_TAG, tag_map);

    nt.add_iri(&align, RDF_TYPE, &format!("{ALIGN}Alignment"));
    nt.add_lang_literal(
        &align,
        RDFS_LABEL,
        &format!("GMEOW → {profile} (EDOAL)"),
        &en,
    );
    nt.add_iri(&align, DCTERMS_IS_PART_OF, ONTOLOGY_IRI);
    nt.add_lang_literal(&align, RDFS_COMMENT, GENERATED_BANNER, &en);
    nt.add_string_literal(&align, &format!("{ALIGN}level"), "2EDOAL");
    for (n, name) in [
        (format!("{ALIGN}onto1"), "GMEOW"),
        (format!("{ALIGN}onto2"), profile),
    ] {
        let onto = nt.fresh_bnode();
        nt.add_iri(&onto, RDF_TYPE, &format!("{ALIGN}Ontology"));
        let formalism = nt.fresh_bnode();
        nt.add_string_literal(&formalism, &format!("{ALIGN}name"), name);
        nt.add_bnode_obj(&onto, &format!("{ALIGN}formalism"), &formalism);
        nt.add_bnode_obj(&align, &n, &onto);
    }

    for cell in cells {
        for b in &cell.bindings {
            if b.profile != profile {
                continue;
            }
            // Overclaim gate (Constitution Principle 5): the EDOAL `align:relation`
            // token `b.relation` is emitted verbatim in `make_cell`. A bridge / caveated
            // relation emitting the equivalence token `=` is a build failure. (Corpus
            // relations are `=`/`<=`; the `=` cells are genuine Equiv, so the gate
            // passes for the committed corpus.) The typed `(relation, class, kind)` is
            // CONSUMED from the materialized correspondence keyed by this cell's natural
            // identity `(cell IRI, profile)` — the single source of truth — not re-derived
            // inline. A miss is a HARD FAIL: every authored binding is transpiled.
            let typed = lookup.binding(&cell.iri, &b.profile)?;
            assert_relation_no_overclaim(
                "edoal",
                typed.relation,
                typed.morphism_class,
                typed.morphism_kind,
                &b.relation,
            )
            .map_err(|e| e.0)?;

            for map_cell in edoal_cells(&mut nt, cell, b, &en)? {
                nt.add_bnode_obj(&align, &format!("{ALIGN}map"), &map_cell);
            }

            // One preservation row per correspondence (cell::profile) that drops
            // something: EDOAL drops the SOL caveats, the put leg, and world/standpoint
            // scope (the dialect structural drops), plus any authored profile losses —
            // all attributed to the get leg.
            let mut residue: Vec<String> = Vec::new();
            for d in &b.lossy_drops {
                residue.push(format!("get-leg profile loss: {d}"));
            }
            residue.push("get-leg: the put leg is not carried by EDOAL".to_owned());
            residue.push("get-leg: world/standpoint scope is not carried by EDOAL".to_owned());
            let key = format!("{}::{}", local(&cell.iri), b.profile);
            ledger.push(correspondence_result("edoal", &key, residue));
        }
    }
    Ok(EmittedEdoal {
        nt: nt.lines,
        ledger,
    })
}

fn edoal_kind(kind: &str) -> &'static str {
    match kind {
        "class" => "Class",
        "relation" => "Relation",
        "property" => "Property",
        _ => "Property",
    }
}

fn edoal_entity(nt: &mut Nt, term: &str, kind: &str) -> String {
    let node = nt.fresh_bnode();
    nt.add_iri(&node, RDF_TYPE, &format!("{EDOAL}{}", edoal_kind(kind)));
    nt.add_iri(&node, &format!("{EDOAL}uri"), term);
    node
}

fn edoal_restriction(nt: &mut Nt, source: &str, attr: &str, value: &str) -> String {
    let cls = nt.fresh_bnode();
    nt.add_iri(&cls, RDF_TYPE, &format!("{EDOAL}Class"));
    let restriction = nt.fresh_bnode();
    nt.add_iri(
        &restriction,
        RDF_TYPE,
        &format!("{EDOAL}AttributeValueRestriction"),
    );
    let on_attr = nt.fresh_bnode();
    nt.add_iri(&on_attr, RDF_TYPE, &format!("{EDOAL}Relation"));
    nt.add_iri(&on_attr, &format!("{EDOAL}uri"), attr);
    nt.add_bnode_obj(&restriction, &format!("{EDOAL}onAttribute"), &on_attr);
    nt.add_iri(
        &restriction,
        &format!("{EDOAL}comparator"),
        &format!("{EDOAL}equals"),
    );
    let val = nt.fresh_bnode();
    nt.add_iri(&val, &format!("{EDOAL}uri"), value);
    nt.add_bnode_obj(&restriction, &format!("{EDOAL}value"), &val);
    let base = edoal_entity(nt, source, "class");
    nt.attach_list(&cls, &format!("{EDOAL}and"), &[base, restriction]);
    cls
}

fn edoal_cells(
    nt: &mut Nt,
    cell: &ProjectionCell,
    b: &ProfileBinding,
    en: &str,
) -> Result<Vec<String>, String> {
    let pattern = &cell.pattern;
    let mut cells = Vec::new();

    if !b.value_class_map.is_empty() {
        let Some(edoal_source) = &pattern.edoal_source else {
            return Err(format!("{}: value-class map needs edoalSource", cell.iri));
        };
        let attr = attr_of(pattern)?;
        for (i, vc) in b.value_class_map.iter().enumerate() {
            let entity1 = edoal_restriction(nt, edoal_source, &attr, &vc.when_value);
            let entity2 = edoal_entity(nt, &vc.to_class, "class");
            let label = format!(
                "{} [{}] → {}",
                curie(edoal_source),
                curie(&vc.when_value),
                curie(&vc.to_class)
            );
            let key = format!("{i}-{}", local(&vc.to_class));
            cells.push(make_cell(nt, cell, b, entity1, entity2, &label, &key, en));
        }
        return Ok(cells);
    }

    let (target, target_kind) = edoal_target(b);
    let Some(target) = target else {
        return Ok(cells);
    };

    let source: String = if pattern.edoal_path {
        match edoal_path(nt, pattern)? {
            Some(s) => s,
            None => {
                return Err(format!(
                    "{}: edoalPath set but no anchor→value path",
                    cell.iri
                ))
            }
        }
    } else if let Some(es) = &pattern.edoal_source {
        edoal_entity(nt, es, &pattern.edoal_source_kind)
    } else {
        return Ok(cells);
    };

    let target_entity = edoal_entity(nt, &target, target_kind);
    let label = if cell.label.is_empty() {
        format!("→ {}", curie(&target))
    } else {
        cell.label.clone()
    };
    cells.push(make_cell(
        nt,
        cell,
        b,
        source,
        target_entity,
        &label,
        "0",
        en,
    ));
    Ok(cells)
}

#[allow(clippy::too_many_arguments)]
fn make_cell(
    nt: &mut Nt,
    cell: &ProjectionCell,
    b: &ProfileBinding,
    entity1: String,
    entity2: String,
    label: &str,
    key: &str,
    en: &str,
) -> String {
    let node = Nt::stable_bnode(&format!("cell-{}-{}-{}", b.profile, local(&cell.iri), key));
    nt.add_iri(&node, RDF_TYPE, &format!("{ALIGN}Cell"));
    nt.add_lang_literal(&node, RDFS_LABEL, label, en);
    nt.add_bnode_obj(&node, &format!("{ALIGN}entity1"), &entity1);
    nt.add_bnode_obj(&node, &format!("{ALIGN}entity2"), &entity2);
    nt.add_string_literal(&node, &format!("{ALIGN}relation"), &b.relation);
    if let Some(transform) = &b.transform {
        let trans = nt.fresh_bnode();
        nt.add_iri(&trans, RDFS_SEE_ALSO, transform);
        nt.add_bnode_obj(&node, &format!("{EDOAL}transformation"), &trans);
    }
    if let Some(conf) = b.confidence {
        nt.add_typed_literal(
            &node,
            &format!("{EDOAL}measure"),
            &format_double(conf),
            XSD_DOUBLE,
        );
    }
    node
}

fn attr_of(pattern: &MappingPattern) -> Result<String, String> {
    for atom in pattern.flat_atoms() {
        if atom.object_var.as_deref() == pattern.value.as_deref()
            && pattern.value.is_some()
            && atom.predicate.is_some()
        {
            return Ok(atom.predicate.clone().unwrap());
        }
    }
    Err("value-class pattern has no value-binding predicate".to_owned())
}

fn edoal_target(b: &ProfileBinding) -> (Option<String>, &str) {
    if let Some(t) = &b.edoal_target {
        return (
            Some(t.clone()),
            b.edoal_target_kind.as_deref().unwrap_or("class"),
        );
    }
    if let Some(t) = &b.to_class {
        return (
            Some(t.clone()),
            b.edoal_target_kind.as_deref().unwrap_or("class"),
        );
    }
    if let Some(t) = &b.to_predicate {
        return (
            Some(t.clone()),
            b.edoal_target_kind.as_deref().unwrap_or("property"),
        );
    }
    (None, "property")
}

fn edoal_path(nt: &mut Nt, pattern: &MappingPattern) -> Result<Option<String>, String> {
    let Some(value) = &pattern.value else {
        return Ok(None);
    };
    let edges = nav_edges(pattern);
    let Some(steps) = find_var_path(&edges, &pattern.anchor, value) else {
        return Ok(None);
    };
    if steps.is_empty() {
        return Ok(None);
    }
    let mut relations = Vec::new();
    for (atom_idx, forward) in &steps {
        relations.push(edoal_relation_step(nt, &edges[*atom_idx].2, *forward));
    }
    if relations.len() == 1 {
        return Ok(Some(relations.into_iter().next().unwrap()));
    }
    let compose = nt.fresh_bnode();
    nt.add_iri(&compose, RDF_TYPE, &format!("{EDOAL}Relation"));
    nt.attach_list(&compose, &format!("{EDOAL}compose"), &relations);
    Ok(Some(compose))
}

type NavEdge = (String, String, Atom);

fn nav_edges(pattern: &MappingPattern) -> Vec<NavEdge> {
    let mut edges = Vec::new();
    for atom in pattern.flat_atoms() {
        let has_pred = atom.predicate.is_some()
            || atom.predicate_var.is_some()
            || atom.path.is_some()
            || !atom.path_alts.is_empty();
        if let Some(obj) = &atom.object_var {
            if has_pred {
                edges.push((atom.subject_var.clone(), obj.clone(), atom.clone()));
            }
        }
    }
    edges
}

fn find_var_path(edges: &[NavEdge], anchor: &str, value: &str) -> Option<Vec<(usize, bool)>> {
    use std::collections::{HashMap, HashSet, VecDeque};
    let mut adj: HashMap<String, Vec<(String, usize, bool)>> = HashMap::new();
    for (idx, (subj, obj, _)) in edges.iter().enumerate() {
        adj.entry(subj.clone())
            .or_default()
            .push((obj.clone(), idx, true));
        adj.entry(obj.clone())
            .or_default()
            .push((subj.clone(), idx, false));
    }
    let mut queue: VecDeque<(String, Vec<(usize, bool)>)> = VecDeque::new();
    queue.push_back((anchor.to_owned(), Vec::new()));
    let mut seen: HashSet<String> = HashSet::new();
    seen.insert(anchor.to_owned());
    while let Some((node, steps)) = queue.pop_front() {
        if node == value {
            return Some(steps);
        }
        if let Some(neighbours) = adj.get(&node) {
            for (nbr, idx, forward) in neighbours {
                if !seen.contains(nbr) {
                    seen.insert(nbr.clone());
                    let mut next = steps.clone();
                    next.push((*idx, *forward));
                    queue.push_back((nbr.clone(), next));
                }
            }
        }
    }
    None
}

fn edoal_relation_step(nt: &mut Nt, atom: &Atom, forward: bool) -> String {
    let base = if !atom.path_alts.is_empty() {
        if atom.path_alts.len() == 1 {
            edoal_entity(nt, &atom.path_alts[0], "relation")
        } else {
            let base = nt.fresh_bnode();
            nt.add_iri(&base, RDF_TYPE, &format!("{EDOAL}Relation"));
            let members: Vec<String> = atom
                .path_alts
                .iter()
                .map(|a| edoal_entity(nt, a, "relation"))
                .collect();
            nt.attach_list(&base, &format!("{EDOAL}or"), &members);
            base
        }
    } else if let Some(pred) = &atom.predicate {
        edoal_entity(nt, pred, "relation")
    } else {
        let base = nt.fresh_bnode();
        nt.add_iri(&base, RDF_TYPE, &format!("{EDOAL}Relation"));
        let comment = atom
            .path
            .clone()
            .or_else(|| atom.predicate_var.clone())
            .unwrap_or_else(|| "path".to_owned());
        nt.add_string_literal(&base, RDFS_COMMENT, &comment);
        base
    };
    if forward {
        return base;
    }
    let inverse = nt.fresh_bnode();
    nt.add_iri(&inverse, RDF_TYPE, &format!("{EDOAL}Relation"));
    nt.add_bnode_obj(&inverse, &format!("{EDOAL}inverse"), &base);
    inverse
}

fn format_double(v: f64) -> String {
    // Rust's default f64 Display is the shortest round-tripping form and matches the
    // committed canonical-Turtle doubles exactly: 1.0 → "1", 0.8 → "0.8". (The old
    // emitter relied on an oxigraph re-dump to normalize "1.0" → "1"; rendering
    // directly from the IR, we mint the canonical lexical here.)
    format!("{v}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stable_bnode_encodes_injectively() {
        // Alphanumerics pass through; `-` (0x2d) is hex-escaped.
        assert_eq!(Nt::stable_bnode("cell-foaf-x-0"), "_:ncell_2dfoaf_2dx_2d0");
        // The old `non-alnum → '_'` collapse mapped these two distinct labels to the
        // same id; the injective encoding keeps them distinct.
        assert_ne!(
            Nt::stable_bnode("cell-a_b-0"),
            Nt::stable_bnode("cell-a-b-0")
        );
        // A literal underscore is itself escaped, so the encoding is unambiguous.
        assert_eq!(Nt::stable_bnode("a_b"), "_:na_5fb");
    }

    #[test]
    fn format_double_matches_corpus() {
        assert_eq!(format_double(0.8), "0.8");
        assert_eq!(format_double(0.95), "0.95");
        assert_eq!(format_double(0.6), "0.6");
        assert_eq!(format_double(1.0), "1");
    }

    /// RED witness driving the overclaim gate THROUGH the real EDOAL lowering: a cell
    /// authored as a `BridgeView` whose EDOAL relation symbol is the equivalence token
    /// `=` must make the lowering return `Err` (Constitution Principle 5 — a bridge view
    /// may never assert equivalence). This exercises the gate at the production call
    /// site, not only the bare gate function.
    #[test]
    fn bridge_cell_emitting_equivalence_fails_the_lowering() {
        use crate::ir::MorphismClass;
        use crate::projections::correspondence_frontend::{CorrespondenceLookup, TypedRelation};

        let gm = "https://blackcatinformatics.ca/gmeow/";
        let bridge_cell = ProjectionCell {
            iri: format!("{gm}cellBridge"),
            label: "bridge".to_owned(),
            pattern: MappingPattern {
                anchor: "x".to_owned(),
                value: None,
                atoms: Vec::new(),
                suppress_when: Vec::new(),
                project_when: Vec::new(),
                exclude_when: Vec::new(),
                filters: Vec::new(),
                binds: Vec::new(),
                mints: Vec::new(),
                edoal_source: Some(format!("{gm}Foo")),
                edoal_source_kind: "class".to_owned(),
                edoal_path: false,
            },
            bindings: vec![ProfileBinding {
                profile: "schema-org".to_owned(),
                to_predicate: None,
                to_class: Some(format!("{gm}Bar")),
                template_atoms: Vec::new(),
                value_class_map: Vec::new(),
                // The EDOAL relation symbol is the equivalence token `=` …
                relation: "=".to_owned(),
                transform: None,
                confidence: None,
                lossy_drops: Vec::new(),
                edoal_target: None,
                edoal_target_kind: Some("class".to_owned()),
                // … but the correspondence is authored as a by-reference BridgeView.
                morphism_class: Some(MorphismClass::BridgeView),
            }],
        };
        let tag_map = BTreeMap::new();
        // The materialized correspondence for this binding: the relation `=` lattices to
        // Equiv, the authored class is BridgeView, the kind is InstitutionMorphism — the
        // exact triple `b.lattice()` (and so the transpiler) would mint. The gate consumes
        // this typed envelope, which forbids a BridgeView surfacing equivalence.
        let lookup = CorrespondenceLookup::for_binding_test(
            &format!("{gm}cellBridge"),
            "schema-org",
            TypedRelation {
                relation: crate::ir::CorrespondenceRelation::Equiv,
                morphism_class: MorphismClass::BridgeView,
                morphism_kind: crate::ir::MorphismKind::InstitutionMorphism,
            },
        );
        let err = emit_edoal_nt(&[bridge_cell], "schema-org", &tag_map, &lookup)
            .expect_err("a bridge view emitting `=` must be rejected by the lowering");
        assert!(err.contains("bridge"), "{err}");
        assert!(err.contains("Principle 5"), "{err}");
    }
}
