// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The FnO correspondence lowering: `gmeow:ProjectionFunction` + the transform
//! functions referenced by the get leg → the W3C Function Ontology catalog.
//!
//! FnO is the *transform-function* lowering of the correspondence calculus. The
//! signatures (parameters typed from each input predicate's ontology `rdfs:range`,
//! the output) are exact; FnO is not an entailment surface, so the ledger-row
//! preservation is `ValidationOnly`. The derivation (range typing, IRI minting, the
//! `used_by`/`transform_cells` scan, `_var_for_predicate`/`_output_var`, the sort
//! order, the deterministic blank-node labels) is reproduced exactly; the
//! [`purrdf::fno`] serializer owns the triple shapes. Extraction runs over the
//! oxigraph-free [`DslView`] (the DSL view for functions/cells, the ontology view for
//! ranges + the language-tag map).

use std::collections::{BTreeMap, BTreeSet};

use gmeow_errors::Diag;
use purrdf::fno::{
    self, FnFunction, FnImpl, FnMapping, FnOutput, FnParam, FnParamMapping, FnReturnMapping,
    FnoCatalog,
};
use purrdf::{RdfLiteral, RdfQuad, RdfTerm, turtle};

use crate::ingest::{DslTerm, DslView};
use crate::loss_ledger::LossLedger;
use crate::projections::{ProjectionResult, correspondence_result};

const GMEOW: &str = "https://blackcatinformatics.ca/gmeow/";
const ONTOLOGY_IRI: &str = "https://blackcatinformatics.ca/gmeow";

const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const RDFS_RANGE: &str = "http://www.w3.org/2000/01/rdf-schema#range";
const SKOS_DEFINITION: &str = "http://www.w3.org/2004/02/skos/core#definition";

const GM_PROJECTION_FUNCTION: &str = "https://blackcatinformatics.ca/gmeow/ProjectionFunction";
const GM_FN_INPUT: &str = "https://blackcatinformatics.ca/gmeow/fnInput";
const GM_FN_INPUT_OPTIONAL: &str = "https://blackcatinformatics.ca/gmeow/fnInputOptional";
const GM_FN_OUTPUT: &str = "https://blackcatinformatics.ca/gmeow/fnOutput";
const GM_FN_OUTPUT_TYPE: &str = "https://blackcatinformatics.ca/gmeow/fnOutputType";

const GM_PROJECTION_MAPPING: &str = "https://blackcatinformatics.ca/gmeow/ProjectionMapping";
const GM_HAS_MAPPING_PATTERN: &str = "https://blackcatinformatics.ca/gmeow/hasMappingPattern";
const GM_HAS_BINDING: &str = "https://blackcatinformatics.ca/gmeow/hasBinding";
const GM_PROFILE: &str = "https://blackcatinformatics.ca/gmeow/profile";
const GM_TRANSFORM: &str = "https://blackcatinformatics.ca/gmeow/transform";

const GM_VALUE: &str = "https://blackcatinformatics.ca/gmeow/value";
const GM_ATOM: &str = "https://blackcatinformatics.ca/gmeow/atom";
const GM_OPTIONAL_GROUP: &str = "https://blackcatinformatics.ca/gmeow/optionalGroup";
const GM_BIND: &str = "https://blackcatinformatics.ca/gmeow/bind";
const GM_BIND_VAR: &str = "https://blackcatinformatics.ca/gmeow/bindVar";
const GM_BIND_EXPR: &str = "https://blackcatinformatics.ca/gmeow/bindExpr";
const GM_EXPR_VAR: &str = "https://blackcatinformatics.ca/gmeow/exprVar";
const GM_EXPR_OP: &str = "https://blackcatinformatics.ca/gmeow/exprOp";
const GM_EXPR_ARGS: &str = "https://blackcatinformatics.ca/gmeow/exprArgs";

const GM_SUBJECT_VAR: &str = "https://blackcatinformatics.ca/gmeow/subjectVar";
const GM_T_SUBJ: &str = "https://blackcatinformatics.ca/gmeow/tSubj";
const GM_PREDICATE: &str = "https://blackcatinformatics.ca/gmeow/predicate";
const GM_T_PRED: &str = "https://blackcatinformatics.ca/gmeow/tPred";
const GM_PATH: &str = "https://blackcatinformatics.ca/gmeow/path";
const GM_PATH_ALTS: &str = "https://blackcatinformatics.ca/gmeow/pathAlts";
const GM_ALT_PATH: &str = "https://blackcatinformatics.ca/gmeow/AltPath";
const GM_OBJECT_VAR: &str = "https://blackcatinformatics.ca/gmeow/objectVar";
const GM_T_OBJ: &str = "https://blackcatinformatics.ca/gmeow/tObj";

const GENERATED_BANNER: &str = "GENERATED by `gmeow-dev sync --mode update --outputs generated` (mappings) from canonical mapping sources — DO NOT EDIT.";
const DOC_LABEL: &str = "GMEOW projection functions (FnO)";
const SPARQL_FORMAT: &str = "application/sparql-query";
const DEFAULT_PROFILE: &str = "schema-org";

// ── DSL model (the FnO-relevant subset) ──────────────────────────────────────────

#[derive(Debug, Clone)]
struct ProjectionFunction {
    iri: String,
    label: String,
    description: String,
    inputs: Vec<String>,
    optional_inputs: Vec<String>,
    output: String,
    output_type: String,
}

#[derive(Debug, Clone)]
struct Atom {
    predicate: Option<String>,
    path_alts: Vec<String>,
    object_var: Option<String>,
}

#[derive(Debug, Clone)]
struct Bind {
    var: String,
    refs: BTreeSet<String>,
}

#[derive(Debug, Clone)]
struct ProjectionCell {
    atoms: Vec<Atom>,
    value: Option<String>,
    binds: Vec<String>,
    transform_bindings: Vec<(String, String)>,
}

/// Lower the FnO catalog to its full-IRI N-Triples text from the DSL view (functions
/// + cells) and the ontology view (`rdfs:range` typing + the language-tag map).
///
/// # Errors
///
/// A malformed function declaration, an input predicate with no ontology `rdfs:range`
/// (the fail-closed `fno:type` guard), or a param-IRI minting collision is a hard
/// error — no degraded fallback.
/// The artifacts + per-correspondence loss ledger of the FnO lowering.
pub struct FnoLowering {
    /// The single FnO catalog N-Triples text.
    pub catalog: String,
    /// One [`ProjectionResult`] per `gmeow:ProjectionFunction` correspondence — FnO is
    /// `ValidationOnly`: signatures are exact, but the relation, caveats, and standpoint
    /// scope are dropped, so every function contributes a preservation row.
    pub ledger: Vec<ProjectionResult>,
    /// The per-correspondence loss store this lowering interned every drop into (keyed by
    /// target focus). The mappings stage unions it into the single report loss store so the
    /// FnO rows' `gmeow:lossyDrop` records read back from the SAME substrate ledger.
    pub loss: LossLedger,
}

pub fn lower_fno(dsl: &DslView, onto: &DslView) -> gmeow_errors::Result<FnoLowering> {
    let functions = extract_functions(dsl)?;
    let cells = extract_cells(dsl)?;
    let catalog_model = build_catalog(&functions, &cells, onto)?;
    let tag_map = build_tag_map(onto);
    // `purrdf::fno::to_quads` never emits `rdfs:isDefinedBy`/`gmeow:graphBoxRole` for
    // any subject, and its external `FnImpl` model carries no label/description
    // field at all — complete the A-Box structural-annotation contract on the raw
    // quads BEFORE the carrier-tag retag, so any label/definition this pass derives
    // rides the exact same `x-gmeow-english` → public-BCP-47 remap every other
    // catalog literal goes through.
    let completed =
        complete_fno_abox_annotations(fno::to_quads(&catalog_model), &catalog_model.document_iri);
    let quads: Vec<RdfQuad> = completed
        .into_iter()
        .map(|q| retag_quad(q, &tag_map))
        .collect();
    let catalog: String = quads.iter().map(turtle::emit_quad).collect();

    // One preservation row per function correspondence: FnO carries exact signatures but
    // is not an entailment surface, so the relation, caveats, and standpoint scope are
    // dropped (the dialect structural drops, attributed to the get leg).
    let mut ledger: Vec<ProjectionResult> = Vec::new();
    let mut loss = LossLedger::new();
    for func in &functions {
        let residue = vec![
            "get-leg: FnO is not an entailment surface — parameter/output signatures are \
             exact, but the transform's semantics are validation-only"
                .to_owned(),
            "get-leg: the correspondence relation, caveats, and standpoint scope are dropped"
                .to_owned(),
        ];
        ledger.push(correspondence_result(
            &mut loss, "fno", &func.iri, residue, None,
        ));
    }
    Ok(FnoLowering {
        catalog,
        ledger,
        loss,
    })
}

/// The single shared `rdfs:range` lookup (the FnO `fno:type` derivation + the lint's
/// `fno-ref`/type check): every range IRI of a predicate in the ontology view.
pub fn predicate_ranges(onto: &DslView, predicate: &str) -> Vec<String> {
    onto.object_iris(predicate, RDFS_RANGE)
}

// ── Extraction (over the oxigraph-free DslView) ──────────────────────────────────

fn extract_functions(dsl: &DslView) -> gmeow_errors::Result<Vec<ProjectionFunction>> {
    let mut out = Vec::new();
    for fn_iri in dsl.subjects_of_type(GM_PROJECTION_FUNCTION) {
        let (Some(output), Some(output_type)) = (
            dsl.object_iri(&fn_iri, GM_FN_OUTPUT),
            dsl.object_iri(&fn_iri, GM_FN_OUTPUT_TYPE),
        ) else {
            return Err(Diag::of_kind(crate::error::Fno {
                detail: format!("projection function {fn_iri} missing fnOutput/fnOutputType"),
            }));
        };
        // The `fno:expects` rdf:List is positional, so its order must be stable. Sort
        // each input set by predicate IRI — a deterministic order (replacing the
        // historical store's hash-order) that the catalog's expects-list reproduces.
        let mut inputs = dsl.object_iris(&fn_iri, GM_FN_INPUT);
        inputs.sort();
        let mut optional_inputs = dsl.object_iris(&fn_iri, GM_FN_INPUT_OPTIONAL);
        optional_inputs.sort();
        out.push(ProjectionFunction {
            label: dsl.object_literal(&fn_iri, RDFS_LABEL).unwrap_or_default(),
            description: dsl
                .object_literal(&fn_iri, SKOS_DEFINITION)
                .unwrap_or_default(),
            inputs,
            optional_inputs,
            output,
            output_type,
            iri: fn_iri,
        });
    }
    Ok(out)
}

fn extract_cells(dsl: &DslView) -> gmeow_errors::Result<Vec<ProjectionCell>> {
    let mut out = Vec::new();
    for cell_iri in dsl.subjects_of_type(GM_PROJECTION_MAPPING) {
        let Some(pattern_node) = dsl.first_object(&cell_iri, GM_HAS_MAPPING_PATTERN) else {
            return Err(Diag::of_kind(crate::error::Fno {
                detail: format!("projection mapping {cell_iri} missing hasMappingPattern"),
            }));
        };
        let (atoms, value, binds) = parse_pattern(dsl, &pattern_node)?;
        out.push(ProjectionCell {
            atoms,
            value,
            binds,
            transform_bindings: parse_transform_bindings(dsl, &cell_iri)?,
        });
    }
    Ok(out)
}

type ParsedPattern = (Vec<Atom>, Option<String>, Vec<String>);

fn parse_pattern(dsl: &DslView, pattern: &DslTerm) -> gmeow_errors::Result<ParsedPattern> {
    let value = dsl.object_literal_of_term(pattern, GM_VALUE);
    let atom_head = dsl.first_object_of(pattern, GM_ATOM);
    let mut atoms = Vec::new();
    for item in dsl.rdf_list(atom_head.as_ref()) {
        flatten_item(dsl, &item, &mut atoms)?;
    }
    let mut raw_binds = Vec::new();
    for bind_node in dsl.objects_of_term(pattern, GM_BIND) {
        raw_binds.push(parse_bind(dsl, &bind_node)?);
    }
    let binds = order_binds(raw_binds)?;
    Ok((atoms, value, binds))
}

fn flatten_item(dsl: &DslView, node: &DslTerm, out: &mut Vec<Atom>) -> gmeow_errors::Result<()> {
    if let Some(group_head) = dsl.first_object_of(node, GM_OPTIONAL_GROUP) {
        for item in dsl.rdf_list(Some(&group_head)) {
            flatten_item(dsl, &item, out)?;
        }
        return Ok(());
    }
    out.push(parse_atom(dsl, node)?);
    Ok(())
}

fn parse_atom(dsl: &DslView, node: &DslTerm) -> gmeow_errors::Result<Atom> {
    let predicate = dsl
        .object_iri_of_term(node, GM_PREDICATE)
        .or_else(|| dsl.object_iri_of_term(node, GM_T_PRED));
    let path_node = dsl.first_object_of(node, GM_PATH);
    let path_alts = match &path_node {
        Some(p) => alt_members(dsl, p),
        None => Vec::new(),
    };
    let object_var = dsl
        .object_literal_of_term(node, GM_OBJECT_VAR)
        .or_else(|| dsl.object_literal_of_term(node, GM_T_OBJ));
    let subj = dsl
        .object_literal_of_term(node, GM_SUBJECT_VAR)
        .or_else(|| dsl.object_literal_of_term(node, GM_T_SUBJ));
    if subj.is_none() {
        return Err(Diag::of_kind(crate::error::Fno {
            detail: "atom missing subjectVar/tSubj".to_owned(),
        }));
    }
    Ok(Atom {
        predicate,
        path_alts,
        object_var,
    })
}

fn alt_members(dsl: &DslView, node: &DslTerm) -> Vec<String> {
    if !node.is_blank() {
        return Vec::new();
    }
    if !dsl.types_of_term(node).iter().any(|t| t == GM_ALT_PATH) {
        return Vec::new();
    }
    let head = dsl.first_object_of(node, GM_PATH_ALTS);
    let members = dsl.rdf_list(head.as_ref());
    let mut alts = Vec::new();
    for m in &members {
        match m.as_iri() {
            Some(iri) => alts.push(iri.to_owned()),
            None => return Vec::new(),
        }
    }
    alts
}

fn parse_bind(dsl: &DslView, node: &DslTerm) -> gmeow_errors::Result<Bind> {
    let Some(var) = dsl.object_literal_of_term(node, GM_BIND_VAR) else {
        return Err(Diag::of_kind(crate::error::Fno {
            detail: "bind missing bindVar".to_owned(),
        }));
    };
    let mut refs = BTreeSet::new();
    let Some(expr_node) = dsl.first_object_of(node, GM_BIND_EXPR) else {
        return Err(Diag::of_kind(crate::error::Fno {
            detail: "bind missing bindExpr".to_owned(),
        }));
    };
    collect_expr_vars(dsl, &expr_node, &mut refs);
    Ok(Bind { var, refs })
}

fn collect_expr_vars(dsl: &DslView, node: &DslTerm, out: &mut BTreeSet<String>) {
    if !node.is_blank() {
        return;
    }
    if let Some(var) = dsl.object_literal_of_term(node, GM_EXPR_VAR) {
        out.insert(var);
        return;
    }
    if dsl.first_object_of(node, GM_EXPR_OP).is_some() {
        let args_head = dsl.first_object_of(node, GM_EXPR_ARGS);
        for arg in dsl.rdf_list(args_head.as_ref()) {
            collect_expr_vars(dsl, &arg, out);
        }
    }
}

fn order_binds(binds: Vec<Bind>) -> gmeow_errors::Result<Vec<String>> {
    let own: BTreeSet<String> = binds.iter().map(|b| b.var.clone()).collect();
    let mut deps: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for b in &binds {
        let d: BTreeSet<String> = b
            .refs
            .iter()
            .filter(|v| own.contains(*v) && **v != b.var)
            .cloned()
            .collect();
        deps.insert(b.var.clone(), d);
    }
    let mut placed: BTreeSet<String> = BTreeSet::new();
    let mut remaining: BTreeSet<String> = own.clone();
    let mut ordered: Vec<String> = Vec::new();
    while !remaining.is_empty() {
        let ready: Vec<String> = remaining
            .iter()
            .filter(|v| deps[*v].is_subset(&placed))
            .cloned()
            .collect();
        if ready.is_empty() {
            // An unresolvable dependency cycle: hard-fail rather than silently break
            // it (which would emit BINDs referring to not-yet-bound variables).
            let cycle: Vec<String> = remaining.iter().map(|v| format!("?{v}")).collect();
            return Err(Diag::of_kind(crate::error::Fno {
                detail: format!("cyclic BIND/mint dependency among {}", cycle.join(", ")),
            }));
        }
        for var in &ready {
            ordered.push(var.clone());
            placed.insert(var.clone());
        }
        for var in &ready {
            remaining.remove(var);
        }
    }
    Ok(ordered)
}

fn parse_transform_bindings(
    dsl: &DslView,
    cell_iri: &str,
) -> gmeow_errors::Result<Vec<(String, String)>> {
    let mut out = Vec::new();
    for binding in dsl.objects_of(cell_iri, GM_HAS_BINDING) {
        let Some(transform) = dsl.object_iri_of_term(&binding, GM_TRANSFORM) else {
            continue;
        };
        let Some(profile) = dsl.object_literal_of_term(&binding, GM_PROFILE) else {
            return Err(Diag::of_kind(crate::error::Fno {
                detail: "profile binding missing profile".to_owned(),
            }));
        };
        out.push((profile, transform));
    }
    Ok(out)
}

// ── Derivation (emit_fno + _emit_fnom) ───────────────────────────────────────────

fn build_catalog(
    functions: &[ProjectionFunction],
    cells: &[ProjectionCell],
    onto: &DslView,
) -> gmeow_errors::Result<FnoCatalog> {
    let mut used_by: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut transform_cells: BTreeMap<(String, String), Vec<usize>> = BTreeMap::new();
    for (idx, cell) in cells.iter().enumerate() {
        for (profile, transform) in &cell.transform_bindings {
            let profiles = used_by.entry(transform.clone()).or_default();
            if !profiles.contains(profile) {
                profiles.push(profile.clone());
            }
            transform_cells
                .entry((transform.clone(), profile.clone()))
                .or_default()
                .push(idx);
        }
    }

    let mut sorted_fns: Vec<&ProjectionFunction> = functions.iter().collect();
    sorted_fns.sort_by(|a, b| a.iri.cmp(&b.iri));

    let mut catalog_fns: Vec<FnFunction> = Vec::new();
    let mut catalog_params: Vec<FnParam> = Vec::new();
    let mut params_emitted: BTreeMap<String, (String, bool)> = BTreeMap::new();

    for func in &sorted_fns {
        let profiles = used_by.get(&func.iri);
        let see_also = profile_query_iri(
            profiles
                .and_then(|ps| ps.first())
                .map(String::as_str)
                .unwrap_or(DEFAULT_PROFILE),
        );

        let mut expects: Vec<String> = Vec::new();
        for (predicate, required) in func
            .inputs
            .iter()
            .map(|p| (p, true))
            .chain(func.optional_inputs.iter().map(|p| (p, false)))
        {
            let param = param_iri(predicate);
            let Some(rng) = predicate_ranges(onto, predicate).into_iter().next() else {
                return Err(Diag::of_kind(crate::error::Fno {
                    detail: format!(
                        "{}: input {predicate} has no rdfs:range — cannot derive its fno:type",
                        func.iri
                    ),
                }));
            };
            if let Some((prior_predicate, prior_required)) = params_emitted.get(&param) {
                if prior_predicate != predicate {
                    return Err(Diag::of_kind(crate::error::Fno {
                        detail: format!(
                            "param IRI collision: {param} is minted from both {prior_predicate} \
                             and {predicate}"
                        ),
                    }));
                }
                if *prior_required != required {
                    return Err(Diag::of_kind(crate::error::Fno {
                        detail: format!(
                            "param requiredness collision: {param} is both required and optional"
                        ),
                    }));
                }
            }
            expects.push(param.clone());
            if !params_emitted.contains_key(&param) {
                params_emitted.insert(param.clone(), (predicate.clone(), required));
                let (label, description) =
                    predicate_label_and_description(onto, predicate, "parameter");
                catalog_params.push(FnParam {
                    iri: param,
                    predicate: Some(predicate.clone()),
                    r#type: rng,
                    required,
                    label: Some(label),
                    description: Some(description),
                });
            }
        }

        let (output_label, output_description) =
            predicate_label_and_description(onto, &func.output, "output");
        catalog_fns.push(FnFunction {
            iri: func.iri.clone(),
            label: func.label.clone(),
            description: if func.description.is_empty() {
                None
            } else {
                Some(func.description.clone())
            },
            kind_types: vec![GM_PROJECTION_FUNCTION.to_owned()],
            see_also: Some(see_also),
            expects,
            output: FnOutput {
                iri: output_iri(&func.iri),
                predicate: Some(func.output.clone()),
                r#type: func.output_type.clone(),
                label: Some(output_label),
                description: Some(output_description),
            },
        });
    }

    let mut implementations: Vec<FnImpl> = Vec::new();
    let mut impl_emitted: BTreeSet<String> = BTreeSet::new();
    let mut mappings: Vec<FnMapping> = Vec::new();

    for func in &sorted_fns {
        let out_node = output_iri(&func.iri);
        let fn_local = local(&func.iri);
        let Some(profiles) = used_by.get(&func.iri) else {
            continue;
        };
        for profile in profiles {
            let impl_node = impl_iri(profile);
            if impl_emitted.insert(profile.clone()) {
                implementations.push(FnImpl {
                    iri: impl_node.clone(),
                    format: SPARQL_FORMAT.to_owned(),
                    see_also: profile_query_iri(profile),
                });
            }

            let empty: Vec<usize> = Vec::new();
            let cell_idxs = transform_cells
                .get(&(func.iri.clone(), profile.clone()))
                .unwrap_or(&empty);
            let mut param_vars: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
            let mut out_vars: BTreeSet<String> = BTreeSet::new();
            for &idx in cell_idxs {
                let cell = &cells[idx];
                for predicate in func.inputs.iter().chain(func.optional_inputs.iter()) {
                    if let Some(var) = var_for_predicate(cell, predicate) {
                        param_vars
                            .entry(param_iri(predicate))
                            .or_default()
                            .insert(var);
                    }
                }
                if let Some(out_var) = output_var(cell) {
                    out_vars.insert(out_var);
                }
            }

            let mut parameter_mappings: Vec<FnParamMapping> = Vec::new();
            for (param, vars) in &param_vars {
                let param_local = local(param);
                for var in vars {
                    parameter_mappings.push(FnParamMapping {
                        bnode_label: format!("param-{fn_local}-{profile}-{param_local}-{var}"),
                        label: format!("{param_local} ↦ ?{var}"),
                        function_parameter: param.clone(),
                        implementation_property: var.clone(),
                    });
                }
            }
            let mut return_mappings: Vec<FnReturnMapping> = Vec::new();
            for var in &out_vars {
                return_mappings.push(FnReturnMapping {
                    bnode_label: format!("return-{fn_local}-{profile}-{var}"),
                    label: format!("{fn_local} output ↦ ?{var}"),
                    function_output: out_node.clone(),
                    implementation_property: var.clone(),
                });
            }

            mappings.push(FnMapping {
                bnode_label: format!("mapping-{fn_local}-{profile}"),
                label: format!("{fn_local} → {profile} (FnO mapping)"),
                function: func.iri.clone(),
                implementation: impl_node,
                parameter_mappings,
                return_mappings,
            });
        }
    }

    Ok(FnoCatalog {
        ontology_iri: ONTOLOGY_IRI.to_owned(),
        document_iri: format!("{ONTOLOGY_IRI}/projections/functions"),
        doc_label: DOC_LABEL.to_owned(),
        banner: GENERATED_BANNER.to_owned(),
        functions: catalog_fns,
        params: catalog_params,
        implementations,
        mappings,
    })
}

/// Derive a real, non-fabricated `(label, description)` pair for `predicate` (an
/// input or output predicate of a projection function) from the ontology view:
/// the predicate's own authored `rdfs:label`/`skos:definition` when present, else
/// a readable form derived purely from its own local name — never invented
/// content, always re-derived from the predicate IRI itself.
fn predicate_label_and_description(
    onto: &DslView,
    predicate: &str,
    role: &str,
) -> (String, String) {
    let local_name = local(predicate);
    let label = onto
        .object_literal(predicate, RDFS_LABEL)
        .unwrap_or_else(|| humanize_local(&local_name));
    let description = onto
        .object_literal(predicate, SKOS_DEFINITION)
        .unwrap_or_else(|| {
            format!(
                "The {role} bound to the `{local_name}` predicate in the FnO projection catalog."
            )
        });
    (label, description)
}

/// Split a `camelCase`/`PascalCase` local name into space-separated words with a
/// lowercase first letter (`"addressLocality"` → `"address locality"`) — a
/// readable fallback label derived purely from the term's own local name, used
/// only when the ontology view carries no authored `rdfs:label` for the term.
fn humanize_local(local: &str) -> String {
    let mut out = String::with_capacity(local.len() + 4);
    for (i, ch) in local.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push(' ');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

// ── A-Box structural-annotation completion ────────────────────────────────────────

/// The `fno:` A-Box individual `rdf:type`s this completion pass covers — every
/// IRI-subject type `purrdf::fno::to_quads` mints for the catalog. Its
/// `fno:Mapping`/`fnom:PropertyParameterMapping`/`fnom:DefaultReturnMapping`
/// subjects are ALWAYS deterministic blank nodes (`purrdf::fno`'s internal
/// `bnode(label)`), never IRIs, so the structural lint's IRI-subject-only A-Box
/// scope already excludes them without help — they need no completion here.
const FNO_FUNCTION: &str = "https://w3id.org/function/ontology#Function";
const FNO_OUTPUT: &str = "https://w3id.org/function/ontology#Output";
const FNO_PARAMETER: &str = "https://w3id.org/function/ontology#Parameter";
const FNO_IMPLEMENTATION: &str = "https://w3id.org/function/ontology#Implementation";

/// Derive a real, non-fabricated `(label, description)` fallback for an
/// `fno:Implementation` individual purely from its own minted IRI — the external
/// `purrdf::fno::FnImpl` model carries NO label/description field at all, so this
/// is the only source available. [`impl_iri`] mints the IRI from the profile name
/// (`impl<CamelCaseProfile>`), so stripping the `impl` prefix and humanizing
/// recovers the profile name exactly.
fn implementation_label_and_description(iri: &str) -> (String, String) {
    let loc = local(iri);
    let stem = loc.strip_prefix("impl").unwrap_or(&loc);
    let humanized = humanize_local(stem);
    (
        format!("{humanized} implementation"),
        format!("The SPARQL-query implementation of the {humanized} projection profile."),
    )
}

/// Complete the FnO catalog's A-Box structural-annotation contract:
/// `purrdf::fno::to_quads` never emits `rdfs:isDefinedBy`/`gmeow:graphBoxRole` for
/// any subject, and `fno:Implementation` individuals structurally cannot get
/// `rdfs:label`/`skos:definition` from the external model at all (no such fields
/// exist on `FnImpl`). This pass scans the ACTUAL emitted quads (never assumes
/// presence from the catalog model — a DSL-authored function with no
/// `skos:definition` genuinely omits it from `to_quads`' output too) and appends
/// whatever is missing on every IRI-subject FnO A-Box individual
/// (`fno:Parameter`/`fno:Function`/`fno:Output`/`fno:Implementation`).
fn complete_fno_abox_annotations(mut quads: Vec<RdfQuad>, catalog_graph_iri: &str) -> Vec<RdfQuad> {
    let mut has_label: BTreeSet<String> = BTreeSet::new();
    let mut has_definition: BTreeSet<String> = BTreeSet::new();
    let mut has_is_defined_by: BTreeSet<String> = BTreeSet::new();
    let mut has_graph_box_role: BTreeSet<String> = BTreeSet::new();
    let mut typed: BTreeMap<String, &'static str> = BTreeMap::new();
    for q in &quads {
        let RdfTerm::Iri(subject) = &q.subject else {
            continue;
        };
        match q.predicate.as_str() {
            RDFS_LABEL => {
                has_label.insert(subject.clone());
            }
            SKOS_DEFINITION => {
                has_definition.insert(subject.clone());
            }
            predicate if predicate == gmeow_errors::abox::RDFS_IS_DEFINED_BY => {
                has_is_defined_by.insert(subject.clone());
            }
            predicate if predicate == gmeow_errors::abox::GRAPH_BOX_ROLE => {
                has_graph_box_role.insert(subject.clone());
            }
            predicate if predicate == gmeow_errors::abox::RDF_TYPE => {
                if let RdfTerm::Iri(ty) = &q.object {
                    let role = match ty.as_str() {
                        FNO_FUNCTION => Some("function"),
                        FNO_OUTPUT => Some("output"),
                        FNO_PARAMETER => Some("parameter"),
                        FNO_IMPLEMENTATION => Some("implementation"),
                        _ => None,
                    };
                    if let Some(role) = role {
                        typed.insert(subject.clone(), role);
                    }
                }
            }
            _ => {}
        }
    }

    let mut extra: Vec<RdfQuad> = Vec::new();

    // The catalog's own `owl:Ontology` document header (the catalog graph IRI
    // itself) is ALSO a gmeow-namespaced typed term, so the structural lint holds
    // it to the same four-predicate contract — `owl:Ontology` is not exempt, only
    // `<ns>self`-defined terms are (`crates/validate/src/lint.rs:557-619`). It is
    // a T-Box document, never an assertional individual, so it carries
    // `gmeow:graphBoxRole gmeow:boxTBox`, never [`gmeow_errors::abox::BOX_ABOX`].
    // `to_quads` already emits its `rdfs:label`/`rdfs:comment`/`dcterms:isPartOf`
    // (never `skos:definition`/`rdfs:isDefinedBy`/`gmeow:graphBoxRole`) — only add
    // what's missing, exactly like every other completion in this pass.
    let header = catalog_graph_iri.to_owned();
    if !has_label.contains(&header) {
        extra.push(RdfQuad::new(
            RdfTerm::iri(header.clone()),
            RDFS_LABEL,
            RdfTerm::literal(RdfLiteral::language_tagged(
                "GMEOW FnO function catalog",
                GMEOW_INTERNAL_ENGLISH,
            )),
        ));
    }
    if !has_definition.contains(&header) {
        extra.push(RdfQuad::new(
            RdfTerm::iri(header.clone()),
            SKOS_DEFINITION,
            RdfTerm::literal(RdfLiteral::language_tagged(
                "The generated FnO function catalog projecting gmeow correspondence \
                 functions to the Function Ontology.",
                GMEOW_INTERNAL_ENGLISH,
            )),
        ));
    }
    if !has_is_defined_by.contains(&header) {
        extra.push(RdfQuad::new(
            RdfTerm::iri(header.clone()),
            gmeow_errors::abox::RDFS_IS_DEFINED_BY,
            RdfTerm::iri(catalog_graph_iri.to_owned()),
        ));
    }
    if !has_graph_box_role.contains(&header) {
        extra.push(RdfQuad::new(
            RdfTerm::iri(header),
            gmeow_errors::abox::GRAPH_BOX_ROLE,
            RdfTerm::iri(gmeow_errors::abox::BOX_TBOX.to_owned()),
        ));
    }

    for (subject, role) in &typed {
        if !has_label.contains(subject) || !has_definition.contains(subject) {
            let (label, description) = if *role == "implementation" {
                implementation_label_and_description(subject)
            } else {
                // Function/Parameter/Output are always populated with real
                // label/description by `build_catalog` — this arm is a defensive
                // fallback (e.g. a DSL function authored with no skos:definition),
                // never the common path.
                (
                    humanize_local(&local(subject)),
                    format!(
                        "The {role} `{}` in the FnO projection catalog.",
                        local(subject)
                    ),
                )
            };
            if !has_label.contains(subject) {
                extra.push(RdfQuad::new(
                    RdfTerm::iri(subject.clone()),
                    RDFS_LABEL,
                    RdfTerm::literal(RdfLiteral::language_tagged(label, GMEOW_INTERNAL_ENGLISH)),
                ));
            }
            if !has_definition.contains(subject) {
                extra.push(RdfQuad::new(
                    RdfTerm::iri(subject.clone()),
                    SKOS_DEFINITION,
                    RdfTerm::literal(RdfLiteral::language_tagged(
                        description,
                        GMEOW_INTERNAL_ENGLISH,
                    )),
                ));
            }
        }
        extra.push(RdfQuad::new(
            RdfTerm::iri(subject.clone()),
            gmeow_errors::abox::RDFS_IS_DEFINED_BY,
            RdfTerm::iri(catalog_graph_iri.to_owned()),
        ));
        extra.push(RdfQuad::new(
            RdfTerm::iri(subject.clone()),
            gmeow_errors::abox::GRAPH_BOX_ROLE,
            RdfTerm::iri(gmeow_errors::abox::BOX_ABOX.to_owned()),
        ));
    }
    quads.extend(extra);
    quads
}

// ── IRI minting + var resolution ─────────────────────────────────────────────────

fn local(iri: &str) -> String {
    let cut = iri.rfind(['#', '/']).map(|i| i + 1).unwrap_or(0);
    iri[cut..].to_owned()
}

fn param_iri(predicate: &str) -> String {
    let local = local(predicate);
    let mut chars = local.chars();
    let head = match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>(),
        None => String::new(),
    };
    let rest: String = chars.collect();
    format!("{GMEOW}param{head}{rest}")
}

fn output_iri(fn_iri: &str) -> String {
    let local = local(fn_iri);
    let stem = local.strip_prefix("fn").unwrap_or(&local);
    format!("{GMEOW}out{stem}")
}

fn camel(text: &str) -> String {
    text.replace('_', "-")
        .split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn impl_iri(profile: &str) -> String {
    format!("{GMEOW}impl{}", camel(profile))
}

fn profile_query_iri(profile: &str) -> String {
    format!("{ONTOLOGY_IRI}/queries/projections/{profile}.rq")
}

fn var_for_predicate(cell: &ProjectionCell, predicate: &str) -> Option<String> {
    for atom in &cell.atoms {
        // An atom with no object var (e.g. an `objectValue` constraint) is skipped —
        // NOT an early return, or a non-var atom preceding the match would hide it.
        let Some(obj) = &atom.object_var else {
            continue;
        };
        let matches = atom.predicate.as_deref() == Some(predicate)
            || atom.path_alts.iter().any(|a| a == predicate);
        if matches {
            return Some(obj.clone());
        }
    }
    None
}

fn output_var(cell: &ProjectionCell) -> Option<String> {
    if let Some(v) = &cell.value {
        return Some(v.clone());
    }
    cell.binds.last().cloned()
}

// ── Language-tag retag (internal @x-gmeow-* → public BCP-47) ──────────────────────

/// The internal carrier tag (`x-gmeow-*`) rides `lang:carrierTag` on the three
/// carrier varieties since the lang: graft.
const LANG_CARRIER_TAG: &str = "https://blackcatinformatics.ca/lang/carrierTag";
/// A carrier variety names its parent sign system through `lang:varietyOf`.
const LANG_VARIETY_OF: &str = "https://blackcatinformatics.ca/lang/varietyOf";
/// A sign system's ISO 639 primary subtag is its `skos:notation`.
const SKOS_NOTATION: &str = "http://www.w3.org/2004/02/skos/core#notation";

fn build_tag_map(onto: &DslView) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    // internal `lang:carrierTag` (on a carrier variety) → DERIVED public BCP-47 tag:
    // the carrier's `lang:varietyOf` parent carries the ISO 639 primary subtag as
    // `skos:notation` (script suppressed for the carriers), matching the tag the
    // `bcp47` projection folds. The tag is never authored per language.
    for (subject, object) in onto.quads_with_predicate(LANG_CARRIER_TAG) {
        let (Some(internal), Some(subj_iri)) = (object.as_literal(), subject.as_iri()) else {
            continue;
        };
        let Some(parent) = onto.object_iri(subj_iri, LANG_VARIETY_OF) else {
            continue;
        };
        if let Some(ext) = onto.object_literal(&parent, SKOS_NOTATION) {
            map.insert(internal.to_owned(), ext.trim().to_ascii_lowercase());
        }
    }
    map
}

/// purrdf's FnO serializer stamps every localizable literal with its own neutral
/// placeholder tag until the consuming ontology remaps it (purrdf-core `fno`
/// `X_PURRDF_ENGLISH`). gmeow's catalog content is authored in gmeow-english, so
/// treat that placeholder as gmeow's internal `x-gmeow-english` tag — the
/// ontology-driven [`build_tag_map`] then remaps it to the public BCP-47 tag.
const PURRDF_FNO_ENGLISH_PLACEHOLDER: &str = "x-purrdf-english";
const GMEOW_INTERNAL_ENGLISH: &str = "x-gmeow-english";

fn retag_quad(mut quad: RdfQuad, tag_map: &BTreeMap<String, String>) -> RdfQuad {
    if let RdfTerm::Literal(lit) = &mut quad.object
        && let Some(lang) = &lit.language
    {
        let internal = if lang == PURRDF_FNO_ENGLISH_PLACEHOLDER {
            GMEOW_INTERNAL_ENGLISH
        } else {
            lang.as_str()
        };
        if let Some(ext) = tag_map.get(internal) {
            lit.language = Some(ext.clone());
        }
    }
    quad
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn iri_minting_matches_historical() {
        assert_eq!(
            local("https://blackcatinformatics.ca/gmeow/fullName"),
            "fullName"
        );
        assert_eq!(
            param_iri("https://blackcatinformatics.ca/gmeow/addressLocality"),
            "https://blackcatinformatics.ca/gmeow/paramAddressLocality"
        );
        assert_eq!(
            output_iri("https://blackcatinformatics.ca/gmeow/fnBirthEventToDate"),
            "https://blackcatinformatics.ca/gmeow/outBirthEventToDate"
        );
        assert_eq!(
            impl_iri("schema-org"),
            "https://blackcatinformatics.ca/gmeow/implSchemaOrg"
        );
        assert_eq!(camel("schema-org"), "SchemaOrg");
    }

    #[test]
    fn lower_fno_extracts_nested_collection_atoms() {
        use purrdf::{NativeRdfFormat, RdfDatasetBuilder, parse_dataset};
        let dsl_ttl = r#"
            @prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            gmeow:fnX a gmeow:ProjectionFunction ;
                rdfs:label "x" ;
                gmeow:fnInput gmeow:eventTime ;
                gmeow:fnOutput gmeow:outVal ; gmeow:fnOutputType rdfs:Literal .
            gmeow:cellX a gmeow:ProjectionMapping ;
                gmeow:hasMappingPattern [
                    gmeow:anchor "person" ; gmeow:value "bdate" ;
                    gmeow:atom (
                        [ gmeow:subjectVar "birth" ; gmeow:predicate gmeow:eventType ; gmeow:objectValue gmeow:eventTypeBirth ]
                        [ gmeow:subjectVar "birth" ; gmeow:predicate gmeow:eventTime ; gmeow:objectVar "bdate" ]
                    ) ] ;
                gmeow:hasBinding [ gmeow:profile "schema-org" ; gmeow:transform gmeow:fnX ] .
        "#;
        let onto_ttl = r#"
            @prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            gmeow:eventTime rdfs:range rdfs:Literal .
        "#;
        // Merge via push_dataset exactly as the caller does (fresh blank scope).
        let mut db = RdfDatasetBuilder::new();
        db.push_dataset(
            &parse_dataset(
                dsl_ttl.as_bytes(),
                NativeRdfFormat::Turtle.media_type(),
                None,
            )
            .expect("parse dsl"),
        );
        let dsl = db.freeze().expect("freeze dsl");

        let onto = parse_dataset(
            onto_ttl.as_bytes(),
            NativeRdfFormat::Turtle.media_type(),
            None,
        )
        .expect("parse onto");
        let nt = lower_fno(&DslView::new(&dsl), &DslView::new(&onto))
            .expect("lower")
            .catalog;
        // The param-mapping for (fnX, schema-org, paramEventTime ↦ ?bdate) must appear.
        assert!(
            nt.contains("functionParameter> <https://blackcatinformatics.ca/gmeow/paramEventTime>"),
            "expected paramEventTime mapping; got:\n{nt}"
        );
        assert!(
            nt.contains("implementationProperty> \"bdate\""),
            "expected ?bdate impl property; got:\n{nt}"
        );
    }

    /// Shift-left: parse the COMPLETED FnO catalog dataset back and confirm every
    /// A-Box FnO individual (`fno:Parameter`/`fno:Function`/`fno:Output`/
    /// `fno:Implementation`) carries all four structural annotations — the exact
    /// contract `gmeow_validate::lint::structural_lint_dataset` enforces at
    /// `make validate-gts`, caught here in a fast `cargo nextest -p
    /// gmeow-logic-compile` instead.
    #[test]
    fn fno_abox_individuals_carry_full_structural_annotations() {
        use purrdf::{NativeRdfFormat, RdfDatasetBuilder, parse_dataset};
        let dsl_ttl = r#"
            @prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            gmeow:fnY a gmeow:ProjectionFunction ;
                rdfs:label "y" ;
                gmeow:fnInput gmeow:eventTime ;
                gmeow:fnOutput gmeow:outVal ; gmeow:fnOutputType rdfs:Literal .
            gmeow:cellY a gmeow:ProjectionMapping ;
                gmeow:hasMappingPattern [
                    gmeow:anchor "person" ; gmeow:value "bdate" ;
                    gmeow:atom (
                        [ gmeow:subjectVar "birth" ; gmeow:predicate gmeow:eventTime ; gmeow:objectVar "bdate" ]
                    ) ] ;
                gmeow:hasBinding [ gmeow:profile "schema-org" ; gmeow:transform gmeow:fnY ] .
        "#;
        // `eventTime` deliberately carries an authored label/definition (exercises
        // the onto-derived branch of `predicate_label_and_description`); the
        // function itself authors no `skos:definition`, so its `fno:Function`
        // individual exercises the completion pass's defensive definition fallback.
        // The `lang:carrierTag` graft mirrors the real ontology's grounding: with
        // it declared, `build_tag_map` remaps EVERY English literal in this public
        // FnO document — both `to_quads`-native ones and the ones this completion
        // pass derives — from the internal `x-gmeow-english` carrier tag to the
        // public `en` BCP-47 tag, so the two sources end up carrying the SAME
        // final tag (proving the derived literals interoperate with the existing
        // carrier-tag retag pipeline rather than diverging from it).
        let onto_ttl = r#"
            @prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .
            @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
            @prefix skos: <http://www.w3.org/2004/02/skos/core#> .
            @prefix lang: <https://blackcatinformatics.ca/lang/> .
            gmeow:eventTime rdfs:range rdfs:Literal ;
                rdfs:label "event time" ;
                skos:definition "The time an event occurred." .
            gmeow:englishGmeowCarrier lang:carrierTag "x-gmeow-english" ;
                lang:varietyOf gmeow:englishSign .
            gmeow:englishSign skos:notation "en" .
        "#;
        let mut db = RdfDatasetBuilder::new();
        db.push_dataset(
            &parse_dataset(
                dsl_ttl.as_bytes(),
                NativeRdfFormat::Turtle.media_type(),
                None,
            )
            .expect("parse dsl"),
        );
        let dsl = db.freeze().expect("freeze dsl");
        let onto = parse_dataset(
            onto_ttl.as_bytes(),
            NativeRdfFormat::Turtle.media_type(),
            None,
        )
        .expect("parse onto");

        let catalog = lower_fno(&DslView::new(&dsl), &DslView::new(&onto))
            .expect("lower")
            .catalog;

        let catalog_ds = parse_dataset(
            catalog.as_bytes(),
            NativeRdfFormat::NTriples.media_type(),
            None,
        )
        .expect("parse completed fno catalog");
        let view = DslView::new(&catalog_ds);

        let document_iri = format!("{ONTOLOGY_IRI}/projections/functions");
        let expected_counts: [(&str, usize); 4] = [
            (FNO_PARAMETER, 1),
            (FNO_FUNCTION, 1),
            (FNO_OUTPUT, 1),
            (FNO_IMPLEMENTATION, 1),
        ];
        let mut checked = 0usize;
        for (fno_type, expected_count) in expected_counts {
            let subjects = view.subjects_of_type(fno_type);
            assert_eq!(
                subjects.len(),
                expected_count,
                "expected {expected_count} individual(s) typed {fno_type}, got {subjects:?}"
            );
            for subject in subjects {
                checked += 1;
                // The carrier-tag graft above resolves `x-gmeow-english` → `en`
                // for this public FnO document, so BOTH `to_quads`-native labels
                // (e.g. `fnY`'s DSL-authored label) and this completion pass's
                // OWN derived literals (e.g. `implSchemaOrg`'s, which never came
                // from `to_quads` at all — `FnImpl` has no label/description
                // field) must land on the identical public tag: proof the
                // completion pass's carrier-tagged literals ride the exact same
                // retag pipeline as everything else in the catalog.
                let label = view
                    .object_literal(&subject, RDFS_LABEL)
                    .unwrap_or_else(|| panic!("{subject} ({fno_type}) missing rdfs:label"));
                assert!(
                    catalog.contains(&format!("\"{}\"@en", label.replace('"', "\\\""))),
                    "{subject}'s rdfs:label {label:?} must carry the carrier-tag-resolved \
                     public 'en' tag; catalog:\n{catalog}"
                );
                let definition = view
                    .object_literal(&subject, SKOS_DEFINITION)
                    .unwrap_or_else(|| panic!("{subject} ({fno_type}) missing skos:definition"));
                assert!(
                    catalog.contains(&format!("\"{}\"@en", definition.replace('"', "\\\""))),
                    "{subject}'s skos:definition {definition:?} must carry the \
                     carrier-tag-resolved public 'en' tag; catalog:\n{catalog}"
                );
                assert_eq!(
                    view.object_iri(&subject, gmeow_errors::abox::RDFS_IS_DEFINED_BY),
                    Some(document_iri.clone()),
                    "{subject} ({fno_type}) must be rdfs:isDefinedBy the FnO catalog graph"
                );
                assert_eq!(
                    view.object_iri(&subject, gmeow_errors::abox::GRAPH_BOX_ROLE),
                    Some(gmeow_errors::abox::BOX_ABOX.to_owned()),
                    "{subject} ({fno_type}) must carry gmeow:graphBoxRole gmeow:boxABox"
                );
            }
        }
        assert_eq!(checked, 4, "fixture must exercise all four FnO A-Box types");

        // The catalog's own `owl:Ontology` document header is NOT exempt from the
        // structural lint (only `<ns>self`-defined terms are) — it must ALSO carry
        // all four annotations, but with `gmeow:graphBoxRole gmeow:boxTBox` (a
        // T-Box document), never `gmeow:boxABox`.
        let header_label = view
            .object_literal(&document_iri, RDFS_LABEL)
            .expect("fno catalog header missing rdfs:label");
        assert!(
            catalog.contains(&format!("\"{}\"@en", header_label.replace('"', "\\\""))),
            "fno catalog header's rdfs:label {header_label:?} must carry the \
             carrier-tag-resolved public 'en' tag; catalog:\n{catalog}"
        );
        let header_definition = view
            .object_literal(&document_iri, SKOS_DEFINITION)
            .expect("fno catalog header missing skos:definition");
        assert!(
            catalog.contains(&format!(
                "\"{}\"@en",
                header_definition.replace('"', "\\\"")
            )),
            "fno catalog header's skos:definition {header_definition:?} must carry the \
             carrier-tag-resolved public 'en' tag; catalog:\n{catalog}"
        );
        assert_eq!(
            view.object_iri(&document_iri, gmeow_errors::abox::RDFS_IS_DEFINED_BY),
            Some(document_iri.clone()),
            "fno catalog header must be rdfs:isDefinedBy the FnO catalog graph"
        );
        assert_eq!(
            view.object_iri(&document_iri, gmeow_errors::abox::GRAPH_BOX_ROLE),
            Some(gmeow_errors::abox::BOX_TBOX.to_owned()),
            "fno catalog header (a T-Box document) must carry gmeow:graphBoxRole \
             gmeow:boxTBox, never gmeow:boxABox"
        );
        assert_ne!(
            view.object_iri(&document_iri, gmeow_errors::abox::GRAPH_BOX_ROLE),
            Some(gmeow_errors::abox::BOX_ABOX.to_owned()),
            "fno catalog header must never carry gmeow:boxABox"
        );
    }

    #[test]
    fn order_binds_is_topological_with_alpha_tiebreak() {
        // c depends on a+b; a,b independent → a, b, then c.
        let binds = vec![
            Bind {
                var: "c".to_owned(),
                refs: BTreeSet::from(["a".to_owned(), "b".to_owned()]),
            },
            Bind {
                var: "b".to_owned(),
                refs: BTreeSet::new(),
            },
            Bind {
                var: "a".to_owned(),
                refs: BTreeSet::new(),
            },
        ];
        assert_eq!(order_binds(binds).unwrap(), vec!["a", "b", "c"]);
    }

    #[test]
    fn order_binds_rejects_cycle() {
        // a depends on b and b depends on a → unresolvable cycle, hard-fail.
        let binds = vec![
            Bind {
                var: "a".to_owned(),
                refs: BTreeSet::from(["b".to_owned()]),
            },
            Bind {
                var: "b".to_owned(),
                refs: BTreeSet::from(["a".to_owned()]),
            },
        ];
        let err = order_binds(binds).expect_err("a BIND cycle must be rejected");
        assert!(
            err.message().contains("cyclic BIND/mint dependency"),
            "{err}"
        );
    }
}
