// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Typed mapping legs shared by required profile-query output and native law execution.
//! Each binding lowers once; profile unions never replace per-cell law domains.

mod hygiene;
pub(crate) use hygiene::HelperNames;
pub(super) mod native;

use crate::ingest::{DslTerm, DslView};
use crate::loss_ledger::LossLedger;
use crate::projections::correspondence_frontend::CorrespondenceAnalysis;
use crate::projections::correspondence_gate::assert_relation_no_overclaim;
use crate::projections::get_leg::{
    Item, MappingPattern, PROFILES, ProfileBinding, ProjectionCell, RDF_TYPE, binding_key,
};
use crate::projections::{ProjectionResult, correspondence_result};
use native::{bgp, error, expr_var, extend, filter, iri, join, named, optional, triple, var};
use purrdf::sparql::{
    BlankNode, Expression, Function, GraphPattern, GroundTerm, Literal, PropertyPathExpression,
    Query, TermPattern, TriplePattern, Variable,
};
use std::collections::{BTreeMap, BTreeSet};

const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const RDFS_COMMENT: &str = "http://www.w3.org/2000/01/rdf-schema#comment";
const RDFS_RANGE: &str = "http://www.w3.org/2000/01/rdf-schema#range";
const RDFS_DOMAIN: &str = "http://www.w3.org/2000/01/rdf-schema#domain";
const RDFS_SUBCLASS_OF: &str = "http://www.w3.org/2000/01/rdf-schema#subClassOf";
const SKOS_DEFINITION: &str = "http://www.w3.org/2004/02/skos/core#definition";
const XSD_BOOLEAN: &str = "http://www.w3.org/2001/XMLSchema#boolean";
const GM_DISPLAYABLE: &str = "https://blackcatinformatics.ca/gmeow/displayable";
const GM_COARSEN_TO: &str = "https://blackcatinformatics.ca/gmeow/coarsenTo";
const GM_APPELLATION: &str = "https://blackcatinformatics.ca/gmeow/Appellation";
const GM_COARSEN_GUARDED: &str = "https://blackcatinformatics.ca/gmeow/coarsenGuarded";
const GM_FULL_NAME: &str = "https://blackcatinformatics.ca/gmeow/fullName";
const GM_PART_TEXT: &str = "https://blackcatinformatics.ca/gmeow/partText";
const GM_PART_EXPANSION: &str = "https://blackcatinformatics.ca/gmeow/partExpansion";
const GM_ROMANIZATION: &str = "https://blackcatinformatics.ca/gmeow/romanization";
const GM_DESCRIPTION: &str = "https://blackcatinformatics.ca/gmeow/description";
const GM_DESIGN_GOAL: &str = "https://blackcatinformatics.ca/gmeow/designGoal";
const GM_TITLE: &str = "https://blackcatinformatics.ca/gmeow/title";
const GM_SLOGAN: &str = "https://blackcatinformatics.ca/gmeow/slogan";
const GM_NAME_LANGUAGE: &str = "https://blackcatinformatics.ca/gmeow/nameLanguage";
const GM_HAS_NAME_PART: &str = "https://blackcatinformatics.ca/gmeow/hasNamePart";

pub(crate) const GENERATED_BANNER: &str = "GENERATED by `gmeow-dev sync --mode update --outputs generated` (mappings) from canonical mapping sources — DO NOT EDIT.";

/// One source binding's native legs. No put means no admitted inverse, never an empty carrier.
pub struct MappingLegs {
    /// The required forward carrier query.
    pub get: Query,
    /// The inverse admitted by this binding's declared polarity, when present.
    pub put: Option<Query>,
}

/// Required emitted profiles, typed binding programs and their single loss store.
pub struct SparqlLowering {
    /// Forward profile query artifacts.
    pub queries: BTreeMap<String, String>,
    /// Inverse profile query artifacts.
    pub put_queries: BTreeMap<String, String>,
    /// Exactly one set of attributed loss rows per binding and dialect.
    pub ledger: Vec<ProjectionResult>,
    /// Operation-scoped programs keyed by complete source binding identity.
    pub legs: BTreeMap<String, MappingLegs>,
    /// Shared content-addressed loss evidence.
    pub loss: LossLedger,
}

/// Lower each binding once, sharing algebra with profile emission and native laws.
pub fn lower_sparql(
    onto: &DslView,
    lookup: &CorrespondenceAnalysis,
) -> gmeow_errors::Result<SparqlLowering> {
    lower_cells(
        lookup.projection_cells(),
        &suppression_vocab(onto),
        lookup,
        PROFILES,
    )
}

pub(super) fn lower_cells(
    cells: &[ProjectionCell],
    vocab: &SuppressionVocab,
    lookup: &CorrespondenceAnalysis,
    profiles: &[&str],
) -> gmeow_errors::Result<SparqlLowering> {
    for cell in cells {
        for binding in &cell.bindings {
            if !profiles.contains(&binding.profile.as_str()) {
                return Err(error(format!(
                    "{}: mapping profile {:?} has no declared output",
                    cell.iri, binding.profile
                )));
            }
        }
    }
    let mut result = SparqlLowering {
        queries: BTreeMap::new(),
        put_queries: BTreeMap::new(),
        ledger: Vec::new(),
        legs: BTreeMap::new(),
        loss: LossLedger::new(),
    };
    for profile in profiles {
        let mut get = native::LegBuilder::default();
        let mut put = native::LegBuilder::default();
        let mut drops = Vec::new();
        let mut any_claim = false;
        for cell in cells {
            for binding in cell
                .bindings
                .iter()
                .filter(|binding| binding.profile == *profile)
            {
                let typed = lookup.binding(cell, binding)?;
                let key = binding_key(cell, binding);
                let names = HelperNames::for_binding(cell, binding);
                let mut guard_index = 0;
                let mut claim_index = 0;
                assert_relation_no_overclaim(
                    "sparql-construct",
                    typed.relation,
                    typed.morphism_class,
                    typed.morphism_kind,
                    &binding.relation,
                )
                .map_err(|why| error(why.0))?;
                let lowered = hygiene::admit(
                    lower_get(cell, binding, vocab, &mut guard_index, &names)?,
                    &key,
                )?;
                get.push(&lowered.template, &lowered.pattern);
                let mut own_get = native::LegBuilder::default();
                own_get.push(&lowered.template, &lowered.pattern);
                let mut own_put = native::LegBuilder::default();
                for drop in &binding.lossy_drops {
                    if !drops.contains(drop) {
                        drops.push(drop.clone());
                    }
                }
                let mut residue = binding
                    .lossy_drops
                    .iter()
                    .map(|drop| format!("get-leg profile loss: {drop}"))
                    .collect::<Vec<_>>();
                residue.extend(
                    lowered
                        .residue
                        .into_iter()
                        .map(|why| format!("get-leg: {why}")),
                );
                result.ledger.push(correspondence_result(
                    &mut result.loss,
                    "sparql",
                    &key,
                    residue,
                    None,
                ));
                if let Some(lowered) =
                    super::sparql_put::lower_binding(cell, binding, &mut claim_index, &names)?
                {
                    let lowered = hygiene::admit(lowered, &key)?;
                    put.push(&lowered.template, &lowered.pattern);
                    own_put.push(&lowered.template, &lowered.pattern);
                    any_claim |= lowered.claim;
                    if !lowered.residue.is_empty() {
                        result.ledger.push(correspondence_result(
                            &mut result.loss,
                            "sparql-put",
                            &key,
                            lowered.residue,
                            None,
                        ));
                    }
                }
                result.legs.insert(
                    key,
                    MappingLegs {
                        get: own_get
                            .finish()
                            .ok_or_else(|| error("binding lost its required get leg"))?,
                        put: own_put.finish(),
                    },
                );
            }
        }
        let get = get
            .finish()
            .ok_or_else(|| error(format!("no bindings for profile {profile:?}")))?;
        let drops = if drops.is_empty() {
            ".".into()
        } else {
            format!("; drops: {}.", drops.join("; "))
        };
        result.queries.insert(format!("{profile}.rq"), format!(
            "# Projection: GMEOW → pure {profile}. {GENERATED_BANNER}\n# Lossy and directional by design{drops}\n{}", native::emit(get)?));
        if let Some(put) = put.finish() {
            result.put_queries.insert(
                format!("{profile}.put.rq"),
                super::sparql_put::emit_profile(profile, any_claim, put)?,
            );
        }
    }
    Ok(result)
}

pub(crate) fn templates_of(
    cell: &ProjectionCell,
    binding: &ProfileBinding,
    vars: &BTreeMap<String, String>,
    names: &HelperNames,
) -> gmeow_errors::Result<Vec<TriplePattern>> {
    let pattern = &cell.pattern;
    if !binding.template_atoms.is_empty() {
        return binding
            .template_atoms
            .iter()
            .map(|atom| native::atom_triple(atom, vars))
            .collect();
    }
    if !binding.value_class_map.is_empty() {
        return native::class_template(&pattern.anchor, var(&names.class));
    }
    if let Some(class) = &binding.to_class {
        return native::class_template(&pattern.anchor, named(class)?);
    }
    if let Some(predicate) = &binding.to_predicate {
        let value = pattern.value.as_ref().ok_or_else(|| {
            error(format!(
                "{}: predicate mapping lacks its value variable",
                cell.iri
            ))
        })?;
        return Ok(vec![triple(
            var(&pattern.anchor),
            predicate,
            var(vars.get(value).unwrap_or(value)),
        )?]);
    }
    Err(error(format!(
        "{}: binding for {} has no output",
        cell.iri, binding.profile
    )))
}

pub(super) struct LoweredLeg {
    pub(super) template: Vec<TriplePattern>,
    pub(super) pattern: GraphPattern,
    pub(super) residue: Vec<String>,
    pub(super) claim: bool,
}

fn lower_get(
    cell: &ProjectionCell,
    binding: &ProfileBinding,
    vocab: &SuppressionVocab,
    guard_index: &mut usize,
    names: &HelperNames,
) -> gmeow_errors::Result<LoweredLeg> {
    let source = &cell.pattern;
    let mut pattern = native::items(&source.atoms)?;
    let mut residue = Vec::new();
    if !binding.value_class_map.is_empty() {
        let value = source
            .value
            .as_ref()
            .ok_or_else(|| error("value/class mapping lacks its value variable"))?;
        pattern = join(
            pattern,
            GraphPattern::Values {
                variables: vec![Variable::new(value), Variable::new(&names.class)],
                bindings: binding
                    .value_class_map
                    .iter()
                    .map(|entry| {
                        Ok(vec![
                            Some(GroundTerm::NamedNode(iri(&entry.when_value)?)),
                            Some(GroundTerm::NamedNode(iri(&entry.to_class)?)),
                        ])
                    })
                    .collect::<gmeow_errors::Result<_>>()?,
            },
        );
    }
    for (kind, values) in [("mint", &source.mints), ("bind", &source.binds)] {
        for value in values {
            match native::expression(&value.expr) {
                Ok(expression) => pattern = extend(pattern, &value.var, expression),
                Err(why) => residue.push(format!("{kind} ?{} dropped ({why})", value.var)),
            }
        }
    }
    let mut filters = Vec::new();
    for atom in source.suppress_when.iter().chain(&source.exclude_when) {
        filters.push(Expression::Not(Box::new(Expression::Exists(Box::new(
            native::atom_pattern(atom)?,
        )))));
    }
    for guard in injected_guards(source, vocab, guard_index, names)? {
        if !filters.contains(&guard) {
            filters.push(guard);
        }
    }
    for atom in &source.project_when {
        filters.push(Expression::Exists(Box::new(native::atom_pattern(atom)?)));
    }
    for expression in &source.filters {
        match native::expression(expression) {
            Ok(expression) => filters.push(expression),
            Err(why) => residue.push(format!("filter dropped ({why})")),
        }
    }
    let mut variables = BTreeMap::new();
    if let Some(retag) = retag_source(source, names) {
        let value = source
            .value
            .as_ref()
            .ok_or_else(|| error("language retag requires a value variable"))?;
        pattern = apply_retag(pattern, value, retag, names)?;
        variables.insert(value.clone(), names.final_value.clone());
    }
    // Group filters see the complete group, including later BIND/OPTIONAL.
    for expression in filters {
        pattern = filter(pattern, expression);
    }
    Ok(LoweredLeg {
        template: templates_of(cell, binding, &variables, names)?,
        pattern,
        residue,
        claim: false,
    })
}

fn injected_guards(
    source: &MappingPattern,
    vocab: &SuppressionVocab,
    guard_index: &mut usize,
    names: &HelperNames,
) -> gmeow_errors::Result<Vec<Expression>> {
    let required = source
        .atoms
        .iter()
        .filter_map(|item| match item {
            Item::Atom(atom) if !atom.optional => Some(atom),
            _ => None,
        })
        .collect::<Vec<_>>();
    let mut guards = Vec::new();
    let hidden = |variable: &str| -> gmeow_errors::Result<TriplePattern> {
        triple(
            var(variable),
            GM_DISPLAYABLE,
            TermPattern::Literal(Literal::new_typed("false", iri(XSD_BOOLEAN)?)),
        )
    };
    let negative = |pattern| Expression::Not(Box::new(Expression::Exists(Box::new(pattern))));
    let authored = required
        .iter()
        .copied()
        .chain(&source.suppress_when)
        .chain(&source.project_when)
        .filter(|atom| atom.predicate.as_deref() == Some(GM_DISPLAYABLE))
        .map(|atom| &atom.subject_var)
        .collect::<BTreeSet<_>>();
    let mut anchors = BTreeSet::new();
    for atom in &required {
        if !authored.contains(&atom.subject_var) && anchors.insert(&atom.subject_var) {
            guards.push(negative(bgp(vec![hidden(&atom.subject_var)?])));
        }
    }
    let coarsened = source
        .suppress_when
        .iter()
        .filter(|atom| atom.predicate.as_deref() == Some(GM_COARSEN_TO))
        .map(|atom| &atom.subject_var)
        .collect::<BTreeSet<_>>();
    for atom in &required {
        if atom
            .predicate
            .as_ref()
            .is_some_and(|predicate| vocab.coarsen_guarded.contains(predicate))
            && !coarsened.contains(&atom.subject_var)
        {
            let guard = negative(bgp(vec![triple(
                var(&atom.subject_var),
                GM_COARSEN_TO,
                TermPattern::BlankNode(BlankNode::new(format!("coarsened{guard_index}"))),
            )?]));
            *guard_index += 1;
            if !guards.contains(&guard) {
                guards.push(guard);
            }
        }
    }
    let bearer_visible = required
        .iter()
        .filter(|atom| {
            atom.predicate
                .as_ref()
                .is_some_and(|predicate| vocab.bearer_props.contains(predicate))
                || atom
                    .path_alts
                    .iter()
                    .any(|predicate| vocab.bearer_props.contains(predicate))
        })
        .filter_map(|atom| atom.object_var.as_ref())
        .collect::<BTreeSet<_>>();
    let mut appellations = BTreeSet::new();
    for atom in required {
        let appellation = atom
            .predicate
            .as_ref()
            .is_some_and(|predicate| vocab.appellation_domain_props.contains(predicate))
            || (atom.predicate.as_deref() == Some(RDF_TYPE)
                && atom
                    .object_value
                    .as_ref()
                    .is_some_and(|class| vocab.appellation_classes.contains(class)));
        if appellation
            && !bearer_visible.contains(&atom.subject_var)
            && appellations.insert(&atom.subject_var)
        {
            let mut paths = vocab
                .bearer_props
                .iter()
                .map(|value| iri(value).map(PropertyPathExpression::NamedNode));
            if let Some(first) = paths.next() {
                let path = paths.try_fold(first?, |left, right| {
                    Ok::<_, gmeow_errors::Diag>(PropertyPathExpression::Alternative(
                        Box::new(left),
                        Box::new(right?),
                    ))
                })?;
                guards.push(negative(join(
                    GraphPattern::Path {
                        subject: var(&names.bearer),
                        path,
                        object: var(&atom.subject_var),
                    },
                    bgp(vec![hidden(&names.bearer)?]),
                )));
            }
        }
    }
    Ok(guards)
}

struct RetagSource {
    parent: Option<String>,
    language: String,
}

fn retag_source(pattern: &MappingPattern, names: &HelperNames) -> Option<RetagSource> {
    let value = pattern.value.as_ref()?;
    let atoms = pattern.flat_atoms();
    let source = pattern.edoal_source.as_deref();
    let language_for = |parent: &str| {
        atoms
            .iter()
            .find(|atom| {
                atom.predicate.as_deref() == Some(GM_NAME_LANGUAGE) && atom.subject_var == parent
            })
            .and_then(|atom| atom.object_var.clone())
            .unwrap_or_else(|| names.language.clone())
    };
    if source == Some(GM_FULL_NAME) {
        let parent = &atoms
            .iter()
            .find(|atom| atom.predicate.as_deref() == Some(GM_FULL_NAME))?
            .subject_var;
        let language = language_for(parent);
        return Some(RetagSource {
            parent: Some(parent.clone()),
            language,
        });
    }
    if matches!(
        source,
        Some(GM_PART_TEXT) | Some(GM_PART_EXPANSION) | Some(GM_ROMANIZATION)
    ) {
        let part = &atoms
            .iter()
            .find(|atom| {
                matches!(
                    atom.predicate.as_deref(),
                    Some(GM_PART_TEXT) | Some(GM_PART_EXPANSION) | Some(GM_ROMANIZATION)
                )
            })?
            .subject_var;
        let parent = atoms
            .iter()
            .find(|atom| {
                atom.predicate.as_deref() == Some(GM_HAS_NAME_PART)
                    && atom.object_var.as_ref() == Some(part)
            })
            .or_else(|| {
                atoms
                    .iter()
                    .find(|atom| atom.object_var.as_ref() == Some(part))
            })?;
        return Some(RetagSource {
            parent: Some(parent.subject_var.clone()),
            language: language_for(&parent.subject_var),
        });
    }
    if matches!(
        source,
        Some(GM_DESCRIPTION) | Some(GM_DESIGN_GOAL) | Some(GM_TITLE) | Some(GM_SLOGAN)
    ) || atoms.iter().any(|atom| {
        matches!(
            atom.predicate.as_deref(),
            Some(RDFS_LABEL) | Some(SKOS_DEFINITION) | Some(RDFS_COMMENT)
        ) && atom.object_var.as_ref() == Some(value)
    }) {
        return Some(RetagSource {
            parent: None,
            language: names.language.clone(),
        });
    }
    None
}

fn apply_retag(
    pattern: GraphPattern,
    value: &str,
    source: RetagSource,
    names: &HelperNames,
) -> gmeow_errors::Result<GraphPattern> {
    let mut triples = Vec::new();
    if let Some(parent) = &source.parent {
        triples.push(triple(
            var(parent),
            GM_NAME_LANGUAGE,
            var(&source.language),
        )?);
    }
    triples.extend([
        triple(
            var(&names.variety),
            "https://blackcatinformatics.ca/lang/varietyOf",
            var(&source.language),
        )?,
        triple(
            var(&names.variety),
            "https://blackcatinformatics.ca/lang/carrierTag",
            var(&names.internal_tag),
        )?,
        triple(
            var(&names.variety),
            "https://blackcatinformatics.ca/gmeow/bcp47Tag",
            var(&names.external_tag),
        )?,
    ]);
    let mut right = bgp(triples);
    if let Some(parent) = &source.parent {
        right = optional(
            right,
            bgp(vec![triple(
                var(parent),
                "https://blackcatinformatics.ca/gmeow/nameScript",
                var(&names.script),
            )?]),
            None,
        );
    }
    let call = |function, values| Expression::FunctionCall(function, values);
    let condition = Expression::And(
        Box::new(call(Function::IsLiteral, vec![expr_var(value)])),
        Box::new(Expression::Equal(
            Box::new(call(Function::Lang, vec![expr_var(value)])),
            Box::new(expr_var(&names.internal_tag)),
        )),
    );
    let external = call(Function::Str, vec![expr_var(&names.external_tag)]);
    let language = if source.parent.is_some() {
        Expression::If(
            Box::new(Expression::Bound(Variable::new(&names.script))),
            Box::new(call(
                Function::Concat,
                vec![
                    external.clone(),
                    Expression::Literal(Literal::new_simple("-")),
                    expr_var(&names.script),
                ],
            )),
            Box::new(external),
        )
    } else {
        external
    };
    let expression = Expression::If(
        Box::new(Expression::Bound(Variable::new(&names.external_tag))),
        Box::new(call(
            Function::StrLang,
            vec![call(Function::Str, vec![expr_var(value)]), language],
        )),
        Box::new(expr_var(value)),
    );
    Ok(extend(
        optional(pattern, right, Some(condition)),
        &names.final_value,
        expression,
    ))
}

// ── Suppression vocabulary ───────────────────────────────────────────────────────

pub(crate) struct SuppressionVocab {
    bearer_props: Vec<String>,
    appellation_domain_props: BTreeSet<String>,
    appellation_classes: BTreeSet<String>,
    coarsen_guarded: BTreeSet<String>,
}

#[cfg(test)]
mod test_support;

fn iri_pairs(view: &DslView, pred: &str) -> Vec<(String, String)> {
    view.quads_with_predicate(pred)
        .into_iter()
        .filter_map(|(s, o)| match (s.as_iri(), o.as_iri()) {
            (Some(s), Some(o)) => Some((s.to_owned(), o.to_owned())),
            _ => None,
        })
        .collect()
}

fn suppression_vocab(onto: &DslView) -> SuppressionVocab {
    let classes = subclass_closure(onto, GM_APPELLATION);
    let mut bearer = BTreeSet::new();
    for (prop, rng) in iri_pairs(onto, RDFS_RANGE) {
        if classes.contains(&rng) {
            bearer.insert(prop);
        }
    }
    let mut domain_props = BTreeSet::new();
    for (prop, dom) in iri_pairs(onto, RDFS_DOMAIN) {
        if classes.contains(&dom) {
            domain_props.insert(prop);
        }
    }
    let mut coarsen = BTreeSet::new();
    for (s, o) in onto.quads_with_predicate(GM_COARSEN_GUARDED) {
        if let (DslTerm::Iri(s), Some(lex)) = (&s, crate::ingest::literal_lexical(&o))
            && lex == "true"
        {
            coarsen.insert(s.clone());
        }
    }
    SuppressionVocab {
        bearer_props: bearer.into_iter().collect(),
        appellation_domain_props: domain_props,
        appellation_classes: classes,
        coarsen_guarded: coarsen,
    }
}

fn subclass_closure(onto: &DslView, root: &str) -> BTreeSet<String> {
    let mut closure = BTreeSet::new();
    closure.insert(root.to_owned());
    let edges = iri_pairs(onto, RDFS_SUBCLASS_OF);
    loop {
        let mut grew = false;
        for (sub, sup) in &edges {
            if closure.contains(sup) && !closure.contains(sub) {
                closure.insert(sub.clone());
                grew = true;
            }
        }
        if !grew {
            break;
        }
    }
    closure
}

#[cfg(test)]
mod tests;
