// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The SPARQL-CONSTRUCT correspondence lowering: the get leg compiled to the closed
//! algebra → one executable `CONSTRUCT` query per profile.
//!
//! This is the faithful executable down-projection of the correspondence calculus;
//! profile losses are explicit (the `# Lossy and directional by design` header + the
//! per-binding `lossyDrop` list), so the ledger-row preservation is `SoundUnder`. It
//! renders from the SAME [`crate::projections::get_leg`] model the EDOAL
//! lowering uses, so the two cannot drift. Extraction of the suppression
//! vocabulary runs over the oxigraph-free ontology [`DslView`]; the render is
//! pure over the get-leg model.

use std::collections::{BTreeMap, BTreeSet};

use gmeow_errors::Diag;

use crate::ingest::prefixes::PREFIX_REGISTRY;
use crate::ingest::{DslTerm, DslView};
use crate::loss_ledger::LossLedger;
use crate::projections::correspondence_frontend::CorrespondenceLookup;
use crate::projections::correspondence_gate::assert_relation_no_overclaim;
use crate::projections::get_leg::{
    Atom, Item, MappingPattern, PROFILES, ProfileBinding, ProjectionCell, RDF_TYPE, curie,
    projections, render_expr, sparql_string,
};
use crate::projections::{ProjectionResult, correspondence_result};

const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const RDFS_COMMENT: &str = "http://www.w3.org/2000/01/rdf-schema#comment";
const RDFS_RANGE: &str = "http://www.w3.org/2000/01/rdf-schema#range";
const RDFS_DOMAIN: &str = "http://www.w3.org/2000/01/rdf-schema#domain";
const RDFS_SUBCLASS_OF: &str = "http://www.w3.org/2000/01/rdf-schema#subClassOf";
const SKOS_DEFINITION: &str = "http://www.w3.org/2004/02/skos/core#definition";
const XSD_BOOLEAN: &str = "http://www.w3.org/2001/XMLSchema#boolean";

const GM_DISPLAYABLE: &str = "https://blackcatinformatics.ca/gmeow/displayable";
const GM_COARSEN_TO: &str = "https://blackcatinformatics.ca/gmeow/coarsenTo";
const GM_APPELLATION: &str = "https://blackcatinformatics.ca/gmeow/Appellation";
const GM_COARSEN_GUARDED: &str = "https://blackcatinformatics.ca/gmeow/coarsenGuarded";
const GM_FULL_NAME: &str = "https://blackcatinformatics.ca/gmeow/fullName";
const GM_PART_TEXT: &str = "https://blackcatinformatics.ca/gmeow/partText";
const GM_PART_EXPANSION: &str = "https://blackcatinformatics.ca/gmeow/partExpansion";
const GM_ROMANIZATION: &str = "https://blackcatinformatics.ca/gmeow/romanization";
const GM_DESCRIPTION: &str = "https://blackcatinformatics.ca/gmeow/description";
const GM_DESIGN_GOAL: &str = "https://blackcatinformatics.ca/gmeow/designGoal";
const GM_TITLE: &str = "https://blackcatinformatics.ca/gmeow/title";
const GM_SLOGAN: &str = "https://blackcatinformatics.ca/gmeow/slogan";
const GM_NAME_LANGUAGE: &str = "https://blackcatinformatics.ca/gmeow/nameLanguage";
const GM_HAS_NAME_PART: &str = "https://blackcatinformatics.ca/gmeow/hasNamePart";

pub(crate) const GENERATED_BANNER: &str = "GENERATED by `gmeow-dev sync --mode update --outputs generated` (mappings) from canonical mapping sources — DO NOT EDIT.";

/// The artifacts + per-correspondence loss ledger of the SPARQL-CONSTRUCT lowering.
pub struct SparqlLowering {
    /// `<profile>.rq` → SPARQL CONSTRUCT (the forward, get-leg down-projection).
    pub queries: BTreeMap<String, String>,
    /// `<profile>.put.rq` → SPARQL CONSTRUCT (the inverse-ingest up-lift). A SEPARATE
    /// map from [`queries`](Self::queries): the put leg is the role-swap of get, never
    /// merged into the forward set. Empty until a binding authors an ingest claim /
    /// mnemomorphic witness (so a corpus without those authored yields no put drift).
    pub put_queries: BTreeMap<String, String>,
    /// One [`ProjectionResult`] per correspondence (cell::profile binding) that drops
    /// something — the per-correspondence preservation rows for the loss ledger.
    pub ledger: Vec<ProjectionResult>,
    /// Per-binding get/put CONSTRUCT fragments, keyed by `(cell IRI, profile)`: the
    /// single-cell slice of the per-profile query (the get fragment) and its inverse
    /// (`Some` only when the binding emits a put leg — `None` for an Unsupported binding such
    /// as `mapSiocTopic`). The per-profile `.rq`/`.put.rq` UNION is the WRONG unit for a lens
    /// law (it mixes recoverable and non-recoverable branches, so `put∘get` always drops); the
    /// mappings stage discharges each correspondence's OWN branch against its OWN put fragment.
    /// Pure strings — no SPARQL engine runs in logic-compile (F2).
    pub fragments: BTreeMap<(String, String), (String, Option<String>)>,
    /// The per-correspondence loss store this lowering interned every drop into (keyed by
    /// target focus) — both the `sparql-construct` get-leg rows and the `sparql-put` inverse
    /// rows. The mappings stage unions it into the single report loss store so both dialect
    /// families read back from the SAME substrate ledger. Only the per-profile emission interns
    /// here; the isolated per-cell fragment re-render (below) uses a throwaway store so no drop
    /// is double-counted.
    pub loss: LossLedger,
}

/// Lower every profile's SPARQL projection query, keyed `<profile>.rq`, plus the
/// per-correspondence loss ledger. `dsl` is the merged mapping-DSL view; `onto` the
/// merged ontology view (suppression vocabulary).
pub fn lower_sparql(
    dsl: &DslView,
    onto: &DslView,
    lookup: &CorrespondenceLookup,
) -> gmeow_errors::Result<SparqlLowering> {
    let cells = projections(dsl)?;
    let vocab = suppression_vocab(onto);
    let mut queries = BTreeMap::new();
    let mut put_queries = BTreeMap::new();
    let mut ledger: Vec<ProjectionResult> = Vec::new();
    let mut loss = LossLedger::new();
    for profile in PROFILES {
        let emitted = emit_sparql(&cells, profile, &vocab, lookup, &mut loss)?;
        queries.insert(format!("{profile}.rq"), emitted.query);
        ledger.extend(emitted.ledger);
        // The inverse-ingest (put) leg: the role-swap of get. A profile with no
        // put-liftable binding contributes nothing (`Ok(None)`) and stays out of the map,
        // so the forward `queries` set and the put set are independent. Its
        // `sparql-put` ledger rows carry the authored gmeow:ingestResidue disclosure into
        // the shared loss ledger, so the honesty note ships in the bundle rather than
        // being dropped at the put leg.
        if let Some(put) =
            crate::projections::sparql_put::emit_put(&cells, profile, &vocab, lookup, &mut loss)?
        {
            put_queries.insert(format!("{profile}.put.rq"), put.query);
            ledger.extend(put.ledger);
        }
    }

    // Per-binding get/put fragments: a single-cell slice of the same emitters, so each
    // correspondence's lens law is dischargeable in ISOLATION (the per-profile UNION mixes
    // recoverable and non-recoverable branches). Byte-independent of the per-profile queries
    // above — this is a separate, pure re-render over the already-parsed `cells`/`vocab`; no
    // engine runs here (F2). Keyed `(cell IRI, profile)` — the mappings stage joins it against
    // the `corr IRI → profile` map and each correspondence's `get_leg` (= its cell IRI).
    let mut fragments: BTreeMap<(String, String), (String, Option<String>)> = BTreeMap::new();
    for cell in &cells {
        let mut profiles: BTreeSet<&str> = BTreeSet::new();
        for b in &cell.bindings {
            profiles.insert(b.profile.as_str());
        }
        for profile in profiles {
            let slice = std::slice::from_ref(cell);
            // The isolated per-cell fragment re-render is a SEPARATE pure render whose only
            // product is the query text (its ledger rows are discarded); intern its drops into a
            // throwaway store so the per-profile emission above stays the sole contributor to
            // `loss` — otherwise every drop would be double-counted.
            let mut scratch = LossLedger::new();
            let get = emit_sparql(slice, profile, &vocab, lookup, &mut scratch)?.query;
            let put = crate::projections::sparql_put::emit_put(
                slice,
                profile,
                &vocab,
                lookup,
                &mut scratch,
            )?
            .map(|p| p.query);
            fragments.insert((cell.iri.clone(), profile.to_owned()), (get, put));
        }
    }

    Ok(SparqlLowering {
        queries,
        put_queries,
        ledger,
        fragments,
        loss,
    })
}

// ── Suppression vocabulary ───────────────────────────────────────────────────────

pub(crate) struct SuppressionVocab {
    bearer_props: Vec<String>,
    appellation_domain_props: BTreeSet<String>,
    appellation_classes: BTreeSet<String>,
    coarsen_guarded: BTreeSet<String>,
}

impl SuppressionVocab {
    /// An empty suppression vocabulary. The inverse-ingest (`put`) emitter injects no
    /// display-guards and so never reads the vocabulary, so a unit test that drives
    /// `emit_put` directly needs only this empty value to satisfy the parallel signature.
    #[cfg(test)]
    pub(crate) fn empty() -> Self {
        Self {
            bearer_props: Vec::new(),
            appellation_domain_props: BTreeSet::new(),
            appellation_classes: BTreeSet::new(),
            coarsen_guarded: BTreeSet::new(),
        }
    }
}

fn iri_pairs(view: &DslView, pred: &str) -> Vec<(String, String)> {
    view.quads_with_predicate(pred)
        .into_iter()
        .filter_map(|(s, o)| match (s.as_iri(), o.as_iri()) {
            (Some(s), Some(o)) => Some((s.to_owned(), o.to_owned())),
            _ => None,
        })
        .collect()
}

fn suppression_vocab(onto: &DslView) -> SuppressionVocab {
    let classes = subclass_closure(onto, GM_APPELLATION);
    let mut bearer = BTreeSet::new();
    for (prop, rng) in iri_pairs(onto, RDFS_RANGE) {
        if classes.contains(&rng) {
            bearer.insert(prop);
        }
    }
    let mut domain_props = BTreeSet::new();
    for (prop, dom) in iri_pairs(onto, RDFS_DOMAIN) {
        if classes.contains(&dom) {
            domain_props.insert(prop);
        }
    }
    let mut coarsen = BTreeSet::new();
    for (s, o) in onto.quads_with_predicate(GM_COARSEN_GUARDED) {
        if let (DslTerm::Iri(s), Some(lex)) = (&s, o.as_literal())
            && lex == "true"
        {
            coarsen.insert(s.clone());
        }
    }
    SuppressionVocab {
        bearer_props: bearer.into_iter().collect(),
        appellation_domain_props: domain_props,
        appellation_classes: classes,
        coarsen_guarded: coarsen,
    }
}

fn subclass_closure(onto: &DslView, root: &str) -> BTreeSet<String> {
    let mut closure = BTreeSet::new();
    closure.insert(root.to_owned());
    let edges = iri_pairs(onto, RDFS_SUBCLASS_OF);
    loop {
        let mut grew = false;
        for (sub, sup) in &edges {
            if closure.contains(sup) && !closure.contains(sub) {
                closure.insert(sub.clone());
                grew = true;
            }
        }
        if !grew {
            break;
        }
    }
    closure
}

// ── SPARQL emission ──────────────────────────────────────────────────────────────

/// One profile's emitted query plus its per-correspondence loss ledger.
pub(crate) struct EmittedQuery {
    pub(crate) query: String,
    pub(crate) ledger: Vec<ProjectionResult>,
}

fn emit_sparql(
    cells: &[ProjectionCell],
    profile: &str,
    vocab: &SuppressionVocab,
    lookup: &CorrespondenceLookup,
    loss: &mut LossLedger,
) -> gmeow_errors::Result<EmittedQuery> {
    let mut templates: Vec<String> = Vec::new();
    let mut branches: Vec<String> = Vec::new();
    let mut drops: Vec<String> = Vec::new();
    let mut seen_branches: BTreeSet<String> = BTreeSet::new();
    let mut ledger: Vec<ProjectionResult> = Vec::new();
    for cell in cells {
        for b in &cell.bindings {
            if b.profile != profile {
                continue;
            }
            // Overclaim gate (Constitution Principle 5): a SPARQL CONSTRUCT down-projection
            // is an equivalence-style assertion only when its relation is genuine
            // equivalence. A bridge / caveated relation emitting the `=` token is a build
            // failure, propagated as Err. (Corpus relations are `=`/`<=`; the `=` cells are
            // genuine Equiv, so the gate passes for the committed corpus.) The typed
            // `(relation, class, kind)` is CONSUMED from the materialized correspondence
            // keyed by `(cell IRI, profile)` — the single source of truth — not re-derived
            // inline. A miss is a HARD FAIL: every authored binding is transpiled.
            let typed = lookup.binding(&cell.iri, &b.profile)?;
            assert_relation_no_overclaim(
                "sparql-construct",
                typed.relation,
                typed.morphism_class,
                typed.morphism_kind,
                &b.relation,
            )
            .map_err(|e| Diag::of_kind(crate::error::Sparql { detail: e.0 }))?;

            // Build the value-var retag map ONCE per cell here and pass it to
            // `templates_of`: the CONSTRUCT head rewrites the value var to the retagged
            // `?_final_*` IFF `language_retag` actually emitted the BIND that defines it.
            // Hoisting it to the caller (from `templates_of`'s old internal body) lets the
            // inverse put emitter drive the same helper with an EMPTY map (plain external
            // vars), while the forward render stays byte-identical (same map computed).
            let mut var_map: BTreeMap<String, String> = BTreeMap::new();
            if let Some(val) = &cell.pattern.value
                && language_retag(&cell.pattern).1.is_some()
            {
                var_map.insert(val.clone(), format!("_final_{val}"));
            }
            for tmpl in templates_of(cell, b, &var_map)? {
                if !templates.contains(&tmpl) {
                    templates.push(tmpl);
                }
            }
            let branch = branch_of(cell, b, vocab)?;
            if seen_branches.insert(branch.text.clone()) {
                branches.push(branch.text);
            }
            for d in &b.lossy_drops {
                if !drops.contains(d) {
                    drops.push(d.clone());
                }
            }
            // One preservation row per correspondence (cell::profile): the SoundUnder
            // SPARQL down-projection always drops the put leg + world/standpoint scope,
            // plus any profile losses and A1's rejected BIND/FILTER constructs — all
            // attributed to the get leg that dropped them.
            let mut residue: Vec<String> = Vec::new();
            for d in &b.lossy_drops {
                residue.push(format!("get-leg profile loss: {d}"));
            }
            for r in branch.residue {
                residue.push(format!("get-leg: {r}"));
            }
            residue.push(
                "get-leg: the put leg is not carried by the SPARQL CONSTRUCT down-projection"
                    .to_owned(),
            );
            residue.push(
                "get-leg: world/standpoint scope is not carried by the SPARQL down-projection"
                    .to_owned(),
            );
            let key = format!("{}::{}", local_cell(&cell.iri), b.profile);
            ledger.push(correspondence_result(loss, "sparql", &key, residue, None));
        }
    }
    if branches.is_empty() {
        return Err(Diag::of_kind(crate::error::Sparql {
            detail: format!("no bindings for profile {profile:?}"),
        }));
    }
    let construct = templates
        .iter()
        .map(|t| format!("    {t}"))
        .collect::<Vec<_>>()
        .join("\n");
    let where_clause = balanced_union(&branches);
    let body = format!("CONSTRUCT {{\n{construct}\n}}\nWHERE {{\n    {where_clause}\n}}\n");
    let drops_part = if drops.is_empty() {
        ".".to_owned()
    } else {
        format!("; drops: {}.", drops.join("; "))
    };
    let header = format!(
        "# Projection: GMEOW → pure {profile}. {GENERATED_BANNER}\n# Lossy and directional by design{drops_part}\n"
    );
    let prefixes = prefix_block(&body);
    Ok(EmittedQuery {
        query: format!("{header}{prefixes}\n\n{body}"),
        ledger,
    })
}

/// Combine the emitted UNION branches into a **balanced** binary tree instead of a flat
/// left-associative chain.
///
/// Each branch is already a `{ … }` group graph pattern. A flat
/// `{b0} UNION {b1} UNION … {bN}` lowers to a left-nested `Union` algebra tree whose depth
/// grows linearly with the branch count, and the evaluator refuses a graph-pattern nesting
/// deeper than `purrdf_sparql_algebra::MAX_GRAPH_PATTERN_DEPTH` (128) — a large profile
/// (schema.org emits well over a hundred branches) trips that ceiling. Splitting at the
/// midpoint makes the depth `⌈log2 N⌉`, so even the largest profile stays far inside the
/// bound. `UNION` is associative and commutative under SPARQL's bag semantics, so the
/// result multiset is identical; only the parenthesisation the parser sees changes.
pub(super) fn balanced_union(branches: &[String]) -> String {
    match branches.len() {
        0 => String::new(),
        1 => branches[0].clone(),
        n => {
            let mid = n / 2;
            format!(
                "{{ {} }} UNION {{ {} }}",
                balanced_union(&branches[..mid]),
                balanced_union(&branches[mid..]),
            )
        }
    }
}

/// The local name of a cell IRI (after the last `#`/`/`) — the per-correspondence key
/// stem for its ledger row.
pub(crate) fn local_cell(iri: &str) -> String {
    iri.rsplit(['#', '/']).next().unwrap_or(iri).to_owned()
}

pub(crate) fn class_var(p: &MappingPattern) -> String {
    format!("{}Class", p.value.clone().unwrap_or_default())
}

pub(crate) fn term_of(
    atom: &Atom,
    var_map: &BTreeMap<String, String>,
) -> gmeow_errors::Result<String> {
    if let Some(obj_var) = &atom.object_var {
        let v = var_map
            .get(obj_var)
            .cloned()
            .unwrap_or_else(|| obj_var.clone());
        return Ok(format!("?{v}"));
    }
    if let Some(val) = &atom.object_value {
        return Ok(curie(val));
    }
    if let Some((lex, dt)) = &atom.object_literal {
        if dt.as_deref() == Some(XSD_BOOLEAN) {
            let lower = lex.to_lowercase();
            return Ok(if lower == "true" || lower == "1" {
                "true".to_owned()
            } else {
                "false".to_owned()
            });
        }
        return Ok(sparql_string(lex));
    }
    Err(Diag::of_kind(crate::error::Sparql {
        detail: "atom has no object".to_owned(),
    }))
}

pub(crate) fn atom_triple(
    atom: &Atom,
    var_map: &BTreeMap<String, String>,
) -> gmeow_errors::Result<String> {
    let subj_var = var_map
        .get(&atom.subject_var)
        .cloned()
        .unwrap_or_else(|| atom.subject_var.clone());
    let subj = format!("?{subj_var}");
    let pred = if let Some(path) = &atom.path {
        path.clone()
    } else if let Some(pv) = &atom.predicate_var {
        format!("?{pv}")
    } else if atom.predicate.as_deref() == Some(RDF_TYPE) && atom.object_value.is_some() {
        "a".to_owned()
    } else if let Some(p) = &atom.predicate {
        curie(p)
    } else {
        return Err(Diag::of_kind(crate::error::Sparql {
            detail: format!("atom on ?{} has no predicate/path", atom.subject_var),
        }));
    };
    Ok(format!("{subj} {pred} {} .", term_of(atom, var_map)?))
}

pub(crate) fn where_items(items: &[Item], indent: &str) -> gmeow_errors::Result<Vec<String>> {
    let empty: BTreeMap<String, String> = BTreeMap::new();
    let mut out = Vec::new();
    for item in items {
        match item {
            Item::Group(inner) => {
                out.push(format!("{indent}OPTIONAL {{"));
                out.extend(where_items(inner, &format!("{indent}    "))?);
                out.push(format!("{indent}}}"));
            }
            Item::Atom(atom) => {
                let triple = atom_triple(atom, &empty)?;
                let wrapped = if atom.optional {
                    format!("OPTIONAL {{ {triple} }}")
                } else {
                    triple
                };
                out.push(format!("{indent}{wrapped}"));
            }
        }
    }
    Ok(out)
}

pub(crate) fn suppression_anchors(p: &MappingPattern) -> Vec<String> {
    let mut anchors = Vec::new();
    for item in &p.atoms {
        if let Item::Atom(atom) = item {
            if atom.optional {
                continue;
            }
            if !anchors.contains(&atom.subject_var) {
                anchors.push(atom.subject_var.clone());
            }
        }
    }
    anchors
}

fn required_atoms(p: &MappingPattern) -> Vec<Atom> {
    let mut out = Vec::new();
    for item in &p.atoms {
        if let Item::Atom(atom) = item
            && !atom.optional
        {
            out.push(atom.clone());
        }
    }
    out
}

fn injected_guards(p: &MappingPattern, vocab: &SuppressionVocab) -> Vec<String> {
    let required = required_atoms(p);
    let mut guards = Vec::new();

    let mut displayable_authored = BTreeSet::new();
    for atom in required
        .iter()
        .chain(p.suppress_when.iter())
        .chain(p.project_when.iter())
    {
        if atom.predicate.as_deref() == Some(GM_DISPLAYABLE) {
            displayable_authored.insert(atom.subject_var.clone());
        }
    }
    for var in suppression_anchors(p) {
        if displayable_authored.contains(&var) {
            continue;
        }
        guards.push(format!(
            "FILTER NOT EXISTS {{ ?{var} gmeow:displayable false . }}"
        ));
    }
    let coarsen_suppressed: BTreeSet<String> = p
        .suppress_when
        .iter()
        .filter(|a| a.predicate.as_deref() == Some(GM_COARSEN_TO))
        .map(|a| a.subject_var.clone())
        .collect();
    for atom in &required {
        if let Some(pred) = &atom.predicate
            && vocab.coarsen_guarded.contains(pred)
        {
            if coarsen_suppressed.contains(&atom.subject_var) {
                continue;
            }
            let guard = format!(
                "FILTER NOT EXISTS {{ ?{} gmeow:coarsenTo [] . }}",
                atom.subject_var
            );
            if !guards.contains(&guard) {
                guards.push(guard);
            }
        }
    }
    let bearer_set: BTreeSet<&String> = vocab.bearer_props.iter().collect();
    let mut bearer_visible = BTreeSet::new();
    for atom in &required {
        let pred_bearer = atom
            .predicate
            .as_ref()
            .map(|p| bearer_set.contains(p))
            .unwrap_or(false);
        let alt_bearer =
            !atom.path_alts.is_empty() && atom.path_alts.iter().any(|a| bearer_set.contains(a));
        if (pred_bearer || alt_bearer)
            && let Some(obj) = &atom.object_var
        {
            bearer_visible.insert(obj.clone());
        }
    }
    let mut appellation_vars: Vec<String> = Vec::new();
    for atom in &required {
        let is_appellation = atom
            .predicate
            .as_ref()
            .map(|p| vocab.appellation_domain_props.contains(p))
            .unwrap_or(false)
            || (atom.predicate.as_deref() == Some(RDF_TYPE)
                && atom
                    .object_value
                    .as_ref()
                    .map(|o| vocab.appellation_classes.contains(o))
                    .unwrap_or(false));
        if is_appellation
            && !bearer_visible.contains(&atom.subject_var)
            && !appellation_vars.contains(&atom.subject_var)
        {
            appellation_vars.push(atom.subject_var.clone());
        }
    }
    if !appellation_vars.is_empty() && !vocab.bearer_props.is_empty() {
        let alternation = vocab
            .bearer_props
            .iter()
            .map(|p| curie(p))
            .collect::<Vec<_>>()
            .join("|");
        for var in &appellation_vars {
            guards.push(format!(
                "FILTER NOT EXISTS {{ ?_supBearer {alternation} ?{var} . ?_supBearer gmeow:displayable false . }}"
            ));
        }
    }
    guards
}

/// One emitted UNION branch plus the residue an unsupported construct left behind.
struct Branch {
    /// The legal SPARQL branch text.
    text: String,
    /// Residue: constructs (BIND/mint/FILTER expressions) this branch could not
    /// legalize and therefore omitted, attributed to the get leg that dropped them.
    residue: Vec<String>,
}

fn branch_of(
    cell: &ProjectionCell,
    b: &ProfileBinding,
    vocab: &SuppressionVocab,
) -> gmeow_errors::Result<Branch> {
    let p = &cell.pattern;
    let empty: BTreeMap<String, String> = BTreeMap::new();
    let mut lines = where_items(&p.atoms, "")?;
    let mut residue: Vec<String> = Vec::new();

    if !b.value_class_map.is_empty() {
        let cv = class_var(p);
        let val = p.value.clone().unwrap_or_default();
        lines.push(format!("VALUES ( ?{val} ?{cv} ) {{"));
        for vc in &b.value_class_map {
            lines.push(format!(
                "    ( {} {} )",
                curie(&vc.when_value),
                curie(&vc.to_class)
            ));
        }
        lines.push("}".to_owned());
    }
    // BIND / mint legalization: an unsupported operator yields no legal SPARQL, so the
    // construct is OMITTED and recorded as residue (⟨legal ⊕ residue⟩) — never a
    // malformed placeholder. A var without its BIND is unbound, exactly the honest
    // "this construct was dropped" signal the residue set documents.
    for mint in &p.mints {
        match render_expr(&mint.expr) {
            Ok(expr) => lines.push(format!("BIND ( {expr} AS ?{} )", mint.var)),
            Err(why) => residue.push(format!("mint ?{} dropped ({why})", mint.var)),
        }
    }
    for bind in &p.binds {
        match render_expr(&bind.expr) {
            Ok(expr) => lines.push(format!("BIND ( {expr} AS ?{} )", bind.var)),
            Err(why) => residue.push(format!("bind ?{} dropped ({why})", bind.var)),
        }
    }
    let mut authored_guards = BTreeSet::new();
    for atom in p.suppress_when.iter().chain(p.exclude_when.iter()) {
        let guard = format!("FILTER NOT EXISTS {{ {} }}", atom_triple(atom, &empty)?);
        authored_guards.insert(guard.clone());
        lines.push(guard);
    }
    for guard in injected_guards(p, vocab) {
        if !authored_guards.contains(&guard) {
            lines.push(guard);
        }
    }
    for atom in &p.project_when {
        lines.push(format!(
            "FILTER EXISTS {{ {} }}",
            atom_triple(atom, &empty)?
        ));
    }
    for flt in &p.filters {
        match render_expr(flt) {
            Ok(expr) => lines.push(format!("FILTER( {expr} )")),
            Err(why) => residue.push(format!("filter dropped ({why})")),
        }
    }

    if let (Some(retag_lines), Some(bind_expr)) = language_retag(p) {
        lines.extend(retag_lines);
        let val = p.value.clone().unwrap_or_default();
        lines.push(format!("BIND ( {bind_expr} AS ?_final_{val} )"));
    }

    let body = lines
        .iter()
        .map(|ln| format!("        {ln}"))
        .collect::<Vec<_>>()
        .join("\n");
    Ok(Branch {
        text: format!("{{\n{body}\n    }}"),
        residue,
    })
}

fn language_retag(p: &MappingPattern) -> (Option<Vec<String>>, Option<String>) {
    let Some(val) = &p.value else {
        return (None, None);
    };
    let flat = p.flat_atoms();
    let src = p.edoal_source.as_deref();

    if src == Some(GM_FULL_NAME) {
        let mut parent_var: Option<String> = None;
        for a in &flat {
            if a.predicate.as_deref() == Some(GM_FULL_NAME) {
                parent_var = Some(a.subject_var.clone());
                break;
            }
        }
        let Some(parent_var) = parent_var else {
            return (None, None);
        };
        let mut lang_var = "_lang".to_owned();
        for a in &flat {
            if a.predicate.as_deref() == Some(GM_NAME_LANGUAGE) && a.subject_var == parent_var {
                if let Some(ov) = &a.object_var {
                    lang_var = ov.clone();
                }
                break;
            }
        }
        // Reach the internal carrier tag + generated BCP-47 tag THROUGH the language's
        // carrier variety: `lang:carrierTag` (the `x-gmeow-*` tag) and the folded
        // `gmeow:bcp47Tag` both ride the `?_variety` that `lang:varietyOf ?{lang_var}`.
        let retag_lines = vec![
            "OPTIONAL {".to_owned(),
            format!("    ?{parent_var} gmeow:nameLanguage ?{lang_var} ."),
            format!("    ?_variety lang:varietyOf ?{lang_var} ."),
            "    ?_variety lang:carrierTag ?_intTag .".to_owned(),
            format!("    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)"),
            "    ?_variety gmeow:bcp47Tag ?_extTag .".to_owned(),
            format!("    OPTIONAL {{ ?{parent_var} gmeow:nameScript ?_sc . }}"),
            "}".to_owned(),
        ];
        let bind_expr = format!(
            "IF(BOUND(?_extTag), STRLANG(STR(?{val}), IF(BOUND(?_sc), CONCAT(STR(?_extTag), '-', ?_sc), STR(?_extTag))), ?{val})"
        );
        return (Some(retag_lines), Some(bind_expr));
    }

    if src == Some(GM_PART_TEXT) || src == Some(GM_PART_EXPANSION) || src == Some(GM_ROMANIZATION) {
        let mut np_var: Option<String> = None;
        for a in &flat {
            if matches!(
                a.predicate.as_deref(),
                Some(GM_PART_TEXT) | Some(GM_PART_EXPANSION) | Some(GM_ROMANIZATION)
            ) {
                np_var = Some(a.subject_var.clone());
                break;
            }
        }
        let mut app_var: Option<String> = None;
        if let Some(np) = &np_var {
            for a in &flat {
                if a.predicate.as_deref() == Some(GM_HAS_NAME_PART)
                    && a.object_var.as_deref() == Some(np.as_str())
                {
                    app_var = Some(a.subject_var.clone());
                    break;
                }
            }
            if app_var.is_none() {
                for a in &flat {
                    if a.object_var.as_deref() == Some(np.as_str()) {
                        app_var = Some(a.subject_var.clone());
                        break;
                    }
                }
            }
        }
        if let (Some(app_var), Some(_np_var)) = (&app_var, &np_var) {
            let retag_lines = vec![
                "OPTIONAL {".to_owned(),
                format!("    ?{app_var} gmeow:nameLanguage ?_lang ."),
                "    ?_variety lang:varietyOf ?_lang .".to_owned(),
                "    ?_variety lang:carrierTag ?_intTag .".to_owned(),
                format!("    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)"),
                "    ?_variety gmeow:bcp47Tag ?_extTag .".to_owned(),
                format!("    OPTIONAL {{ ?{app_var} gmeow:nameScript ?_sc . }}"),
                "}".to_owned(),
            ];
            let bind_expr = format!(
                "IF(BOUND(?_extTag), STRLANG(STR(?{val}), IF(BOUND(?_sc), CONCAT(STR(?_extTag), '-', ?_sc), STR(?_extTag))), ?{val})"
            );
            return (Some(retag_lines), Some(bind_expr));
        }
        return (None, None);
    }

    if matches!(
        src,
        Some(GM_DESCRIPTION) | Some(GM_DESIGN_GOAL) | Some(GM_TITLE) | Some(GM_SLOGAN)
    ) {
        let retag_lines = vec![
            "OPTIONAL {".to_owned(),
            "    ?_variety lang:varietyOf ?_lang .".to_owned(),
            "    ?_variety lang:carrierTag ?_intTag .".to_owned(),
            format!("    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)"),
            "    ?_variety gmeow:bcp47Tag ?_extTag .".to_owned(),
            "}".to_owned(),
        ];
        let bind_expr = format!("IF(BOUND(?_extTag), STRLANG(STR(?{val}), STR(?_extTag)), ?{val})");
        return (Some(retag_lines), Some(bind_expr));
    }

    let annotation = flat.iter().any(|a| {
        matches!(
            a.predicate.as_deref(),
            Some(RDFS_LABEL) | Some(SKOS_DEFINITION) | Some(RDFS_COMMENT)
        ) && a.object_var.as_deref() == Some(val.as_str())
    });
    if annotation {
        let retag_lines = vec![
            "OPTIONAL {".to_owned(),
            "    ?_variety lang:varietyOf ?_lang .".to_owned(),
            "    ?_variety lang:carrierTag ?_intTag .".to_owned(),
            format!("    FILTER(isLiteral(?{val}) && LANG(?{val}) = ?_intTag)"),
            "    ?_variety gmeow:bcp47Tag ?_extTag .".to_owned(),
            "}".to_owned(),
        ];
        let bind_expr = format!("IF(BOUND(?_extTag), STRLANG(STR(?{val}), STR(?_extTag)), ?{val})");
        return (Some(retag_lines), Some(bind_expr));
    }

    (None, None)
}

/// Render a binding's EXTERNAL template atoms (the forward CONSTRUCT head; the inverse
/// put emitter's WHERE). `var_map` rewrites the value var to the retagged `?_final_*` IFF
/// `language_retag` emitted the BIND that defines it — the forward caller passes exactly
/// that map (so the forward render is byte-identical), and the inverse put caller passes an
/// EMPTY map (plain external vars, since the put leg matches the external triples verbatim
/// with no language-retag BIND to define `?_final_*`). Passing the map explicitly is the
/// single source of truth for the rewrite decision and lets ONE helper serve both legs.
pub(crate) fn templates_of(
    cell: &ProjectionCell,
    b: &ProfileBinding,
    var_map: &BTreeMap<String, String>,
) -> gmeow_errors::Result<Vec<String>> {
    let p = &cell.pattern;

    if !b.template_atoms.is_empty() {
        let mut out = Vec::new();
        for a in &b.template_atoms {
            out.push(atom_triple(a, var_map)?);
        }
        return Ok(out);
    }
    if !b.value_class_map.is_empty() {
        return Ok(vec![format!("?{} a ?{} .", p.anchor, class_var(p))]);
    }
    if let Some(to_class) = &b.to_class {
        return Ok(vec![format!("?{} a {} .", p.anchor, curie(to_class))]);
    }
    if let Some(to_predicate) = &b.to_predicate {
        let raw = p.value.clone().unwrap_or_default();
        let val = var_map.get(&raw).cloned().unwrap_or(raw);
        return Ok(vec![format!(
            "?{} {} ?{val} .",
            p.anchor,
            curie(to_predicate)
        )]);
    }
    Err(Diag::of_kind(crate::error::Sparql {
        detail: format!("{}: binding for {} has no output", cell.iri, b.profile),
    }))
}

pub(crate) fn prefix_block(text: &str) -> String {
    let search_text = strip_iris(text);
    let mut lines = Vec::new();
    for (prefix, ns) in PREFIX_REGISTRY {
        if has_prefix_token(&search_text, prefix) {
            lines.push(format!("PREFIX {prefix}: <{ns}>"));
        }
    }
    lines.join("\n")
}

fn strip_iris(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_iri = false;
    for c in text.chars() {
        if in_iri {
            if c == '>' {
                in_iri = false;
            }
            continue;
        }
        if c == '<' {
            in_iri = true;
            continue;
        }
        out.push(c);
    }
    out
}

fn has_prefix_token(text: &str, prefix: &str) -> bool {
    let needle = format!("{prefix}:");
    let bytes = text.as_bytes();
    let nbytes = needle.as_bytes();
    let mut i = 0usize;
    while i + nbytes.len() <= bytes.len() {
        if &bytes[i..i + nbytes.len()] == nbytes {
            let ok = if i == 0 {
                true
            } else {
                let prev = bytes[i - 1];
                !(prev.is_ascii_alphanumeric() || prev == b'_')
            };
            if ok {
                return true;
            }
        }
        i += 1;
    }
    false
}
