// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The standalone-console producer.
//!
//! [`console_files`] is the SINGLE authority for "what the console is made of": the
//! `console/…` shell files (each a pinned `include_str!` / `include_bytes!` build input)
//! plus EVERY key of [`crate::render::interactive_asset_files`], so the console and the
//! documentation site ship the byte-identical engine the native↔wasm witness lanes prove.
//! There is no second list, and nothing is copied by hand.
//!
//! Four surfaces are GENERATED here, from the assembled map itself, because each of them
//! is a restatement of the key set or the byte set and a hand-authored restatement drifts
//! the moment a file is added:
//!
//! 1. the service worker's `SHELL` array — the install-time pre-cache set, which is the
//!    PRE-CACHED tier of the assembled tree and nothing else (see [`Fetch`]);
//! 2. the service worker's cache name — a BLAKE3 content digest of the assembled tree, so
//!    a rebuild that keeps every path but changes a byte cannot reuse the old cache;
//! 3. the console README's measured-byte table, the pre-cache ceiling DERIVED from that
//!    measurement, and the sentence stating the factor between them — measured over the
//!    emitted bytes and computed from one constant, never typed in;
//! 4. the console README's DEPLOYED-SITE sections. The one authored `README.md` is the
//!    published npm package's own README, shipped in the tarball verbatim, so it may only
//!    describe files the package carries; the service worker, the PWA shell and the measured
//!    byte table describe the assembled site tree, and they are substituted in only when
//!    this producer emits the document into that tree. A single document that described both
//!    was a published package documenting a worker, a manifest, four icons and a byte table
//!    none of which it shipped.
//!
//! Every substitution is fail-closed: a source whose marker is missing panics rather than
//! shipping a worker that caches nothing or a README that publishes a placeholder.
//!
//! Determinism is structural: the map is a [`BTreeMap`], every value is either a pinned
//! build input or a deterministic function of `exec`, and each generated surface is a pure
//! function of the map. Two calls over the same `exec` are byte-identical.

use std::collections::BTreeMap;

use gmeow_docs_model::exec::ExecutableDocsData;

use crate::render::interactive_asset_files;

/// The site-relative directory the console shell is emitted under.
pub const CONSOLE_PREFIX: &str = "console/";

/// The console-relative directory the console's own engine payload is served from.
///
/// On the SITE this holds one generated forwarder (see [`TRANSPORT_FORWARDER_KEY`]); in the
/// published npm package it holds the whole engine payload, staged there by the package's
/// `prepack` step from this producer's own output. Both trees therefore answer
/// `./pkg/mcp-transport.mjs` — which is why `console/engine.worker.mjs` can spell ONE
/// specifier and boot in both.
pub const CONSOLE_PAYLOAD_PREFIX: &str = "console/pkg/";

/// The shipped console README, whose measured-byte table [`console_files`] rewrites.
const README_KEY: &str = "console/README.md";

/// The transport entry point the console's engine worker imports.
pub const TRANSPORT_FORWARDER_KEY: &str = "console/pkg/mcp-transport.mjs";

/// The marker in the authored `sw.mjs` that the generated `SHELL` array replaces.
///
/// Public so the acceptance assertion can prove the authored source still carries it —
/// a renamed marker would otherwise degrade silently into "the substitution found
/// nothing", which the panic below already refuses at run time.
pub const SHELL_MARKER: &str = "[\"__GMEOW_CONSOLE_SHELL__\"]";

/// The marker in the authored `sw.mjs` that the generated build digest replaces.
pub const BUILD_MARKER: &str = "\"__GMEOW_CONSOLE_BUILD__\"";

/// The marker in the authored `README.md` that the generated byte table replaces.
///
/// Authored in [`SITE_SECTIONS_SOURCE`], not in `README.md`: the table measures the
/// assembled site tree, so it is one of the sections the published package does not carry.
pub const BYTE_TABLE_MARKER: &str = "<!-- __GMEOW_CONSOLE_BYTE_TABLE__ -->";

/// The marker in the authored `README.md` that the deployed-site sections replace.
///
/// The authored document is the npm package's README, shipped verbatim in the tarball. The
/// site-only sections — the offline contract, the PWA shell, the measured byte table —
/// describe the assembled tree and are substituted here, so the package's own document
/// cannot document a file the package does not ship.
///
/// The marker SAYS that, in the comment itself, because the tarball ships it unsubstituted:
/// a reader of the published bytes gets a sentence explaining what is missing and why, not
/// an unexplained build token.
pub const SITE_SECTIONS_MARKER: &str = "<!-- __GMEOW_CONSOLE_SITE_SECTIONS__ — the deployed \
     tree's offline contract, PWA shell and measured byte table are substituted here; they \
     document files the published package does not ship. -->";

/// The authored deployed-site sections, substituted at [`SITE_SECTIONS_MARKER`].
///
/// Deliberately OUTSIDE the npm package directory (`assets/console/`): a file inside it
/// could be pulled into the tarball by a `files` entry or by npm's own always-included set,
/// and this content exists precisely because it must not be published there. Its SPDX
/// header rides in a `.license` sidecar rather than inline, because these bytes are
/// concatenated into a document that already carries one.
const SITE_SECTIONS_SOURCE: &str = include_str!("../assets/console-site-readme.md");

/// The multiple of the MEASURED install pre-cache that the published ceiling sits at.
///
/// The whole of the rule, and the ONLY place it is stated. It used to be stated three times
/// — as a hand-typed constant, as an arithmetic comment beside it, and as a sentence in the
/// shipped README — and all three disagreed: the constant said `47 534 469 × 1.1`, the
/// measurement had since moved to `47 704 211`, so the published "plus ten percent of
/// headroom" was really 9.609 % and drifting further with every byte added. A factor
/// nothing computes is a number somebody has to remember to retype, and nobody did.
///
/// Now [`precache_ceiling`] derives the ceiling from the measurement, the README sentence is
/// generated from this same constant, and the ratio between the two published numbers is
/// this constant by construction rather than by anyone's arithmetic.
pub const PRECACHE_CEILING_FACTOR: u64 = 2;

/// The sentence the generated README publishes to say that the ceiling is NOT a budget.
///
/// Public so the acceptance assertion can require it verbatim in the shipped document. It
/// exists because the previous sentence read "it bounds what `cache.addAll` downloads at
/// install", which states a constraint, while [`precache_ceiling`] is a fixed multiple of
/// the very measurement it claimed to bound — so the reasoning segment could grow by
/// megabytes, the ceiling grew with it, and every assertion over the pair (`2n > n`,
/// `measured ≤ 2 × measured`) held by arithmetic no input could disturb.
///
/// Payload size is deliberately not constrained here. That is a decision, and stating the
/// decision is the honest artifact; a derived ratio dressed up as a gate is not. If a size
/// regression ever needs to red something, what has to land is a PINNED budget — a number
/// chosen independently of the measurement — and this sentence is what would come out.
pub const NO_SIZE_GATE_DISCLOSURE: &str = "**That ratio is not a budget, and nothing in this \
     repository gates a size regression of the console payload.** A ceiling derived as a \
     fixed multiple of a measurement cannot bound that measurement: add bytes anywhere in \
     the pre-cached tiers and this number rises with them, staying exactly the same factor \
     away, so no growth can ever cross it. It TRACKS the measurement; it does not limit it. \
     It is published only so that a reader comparing it with the total above can see that \
     the relationship between them is an identity rather than a limit somebody chose. \
     Constraining the payload is not a goal here — and if it becomes one, what has to land \
     is a pinned budget independent of the measurement, not this ratio.";

/// The published ceiling for a measured install pre-cache total.
///
/// A DERIVED identity, not a pin: `measured × `[`PRECACHE_CEILING_FACTOR`]. It moves with
/// the measurement, which is what makes it survive a re-vendored engine — and what stops
/// the number the README publishes from ever contradicting the number above it.
///
/// What it bounds is the set `sw.mjs` stores at install: [`Fetch::PageLoad`] +
/// [`Fetch::InstallOnly`], which is exactly what `cache.addAll` downloads. It is NOT the
/// page-load figure — that is a strictly smaller measurement, published on its own row —
/// and conflating the two is how the shipped README came to head a table of everything the
/// worker pre-caches with the sentence "everything fetched before any pane runs".
///
/// The browser smoke lane records what a fresh page load actually pulls off the wire and
/// asserts it BOTH ways against the published page-load set, and asserts the summed
/// pre-cache set against this ceiling. A load that reaches for something outside its tier —
/// the demand-loaded reasoning segment being the one this has been wrong about before —
/// fails that lane rather than quietly spending bytes.
#[must_use]
pub const fn precache_ceiling(precache_total: u64) -> u64 {
    precache_total * PRECACHE_CEILING_FACTOR
}

/// One console shell file: its `console/`-relative name, its pinned bytes, and WHEN the
/// console fetches it.
///
/// Every entry is an `include_*!` of a real file under `crates/docs/assets/console/`, so
/// the shipped console is exactly the reviewed source — never a string assembled here.
///
/// The tier column is authored HERE, beside the bytes, because that is the one place a file
/// is added: a new shell file cannot join a tier by accident, it has to be given one, and
/// [`fetch_tier`] refuses any key this table does not carry.
///
/// `smoke/` is deliberately absent. It is the dev-only browser smoke lane — its pinned
/// Playwright manifests, its runner configuration and global setup, its harness and its
/// specs — and including it deployed a private, `npm ci`-shaped scaffold to the public site
/// AND pre-cached it into every reader's offline storage, while the README said nothing
/// under `smoke/` ships. The lane reads those files from the repository, where they live.
const SHELL_FILES: &[(&str, &[u8], Fetch)] = &[
    (
        "index.html",
        include_bytes!("../assets/console/index.html"),
        Fetch::PageLoad,
    ),
    (
        "element.mjs",
        include_bytes!("../assets/console/element.mjs"),
        Fetch::PageLoad,
    ),
    (
        "engine.worker.mjs",
        include_bytes!("../assets/console/engine.worker.mjs"),
        Fetch::PageLoad,
    ),
    (
        "session.mjs",
        include_bytes!("../assets/console/session.mjs"),
        Fetch::PageLoad,
    ),
    (
        "examples/gallery.mjs",
        include_bytes!("../assets/console/examples/gallery.mjs"),
        Fetch::PageLoad,
    ),
    // The PWA shell. A browser reads the manifest and its icons when a reader INSTALLS the
    // console, not to paint the page, so none of it is on the page-load path — but all of
    // it is pre-cached, because a manifest naming an icon that is not there is not an
    // installable manifest, least of all offline.
    (
        "manifest.webmanifest",
        include_bytes!("../assets/console/manifest.webmanifest"),
        Fetch::InstallOnly,
    ),
    (
        "icon.svg",
        include_bytes!("../assets/console/icon.svg"),
        Fetch::InstallOnly,
    ),
    (
        "icon-192.png",
        include_bytes!("../assets/console/icon-192.png"),
        Fetch::InstallOnly,
    ),
    (
        "icon-512.png",
        include_bytes!("../assets/console/icon-512.png"),
        Fetch::InstallOnly,
    ),
    (
        "icon-maskable-512.png",
        include_bytes!("../assets/console/icon-maskable-512.png"),
        Fetch::InstallOnly,
    ),
    (
        "README.md",
        include_bytes!("../assets/console/README.md"),
        Fetch::Never,
    ),
];

/// The console files this producer GENERATES, and their tiers.
///
/// They are not in [`SHELL_FILES`] because they have no authored bytes, but they are emitted
/// console keys all the same and [`fetch_tier`] has to answer for them. The forwarder is
/// imported by the engine worker on every boot; the service worker is fetched by the
/// registration that begins the install, never by the boot path, and it is the one member of
/// the pre-cache set that caches itself.
const GENERATED_CONSOLE_FILES: &[(&str, Fetch)] = &[
    ("pkg/mcp-transport.mjs", Fetch::PageLoad),
    ("sw.mjs", Fetch::InstallOnly),
];

/// The tier of every SHARED `assets/…` key, by exact name or by directory prefix.
///
/// One row per key [`crate::render::interactive_asset_files`] can emit — the transport, the
/// client-side BLAKE3, the bundle snapshot and its integrity manifest, the two MCP engine
/// segments, the vendored purrdf engine, and the two assets that belong to the documentation
/// site rather than to the console. An entry ending in `/` covers a directory; every other
/// entry is an exact key.
///
/// Authored as a TABLE and consulted exhaustively, because the classification used to be
/// three `if`s and an `else` that swept everything else into the first-load tier. That
/// `else` is how 8 MB of vendored purrdf, four icons and a PWA manifest came to be published
/// under the heading "everything fetched before any pane runs" — nothing had ever decided
/// they belonged there.
const ASSET_TIERS: &[(&str, Fetch)] = &[
    ("assets/blake3.mjs", Fetch::PageLoad),
    ("assets/bundle-manifest.json", Fetch::PageLoad),
    ("assets/conjectures.ttl", Fetch::Never),
    ("assets/gmeow-docs.js", Fetch::Never),
    ("assets/gmeow.gts", Fetch::PageLoad),
    ("assets/mcp-core/", Fetch::PageLoad),
    ("assets/mcp-transport.mjs", Fetch::PageLoad),
    ("assets/mcp/", Fetch::Demand),
    // The DOCUMENTATION SITE's own assets, which reach this map because `console_files`
    // folds `interactive_asset_files` and the site emits its four per-capability wasm
    // engines plus its controller there. The console does not dispatch to any of them —
    // every console widget speaks JSON-RPC to the MCP segments above — so they are
    // `Never`: the console tree does not carry them and the service worker never caches
    // them. They are listed rather than filtered out because an emitted asset with no
    // tier is a hard error by design, and silence is exactly what that rule prevents.
    ("assets/gmn/", Fetch::Never),
    ("assets/playground.trig", Fetch::Never),
    ("assets/query/", Fetch::Never),
    ("assets/reason/", Fetch::Never),
    ("assets/validate/", Fetch::Never),
];

/// The authored service worker, whose `SHELL` array and cache name [`console_files`]
/// rewrites.
const SW_SOURCE: &str = include_str!("../assets/console/sw.mjs");

/// When the console fetches one emitted asset.
///
/// This is the console's OWN fetch behaviour, read off the shipped modules, and it is the
/// single partition three separate surfaces are derived from: the install-time `SHELL`, the
/// published byte table, and the ceiling assertion. One partition means the offline
/// pre-cache, the documented cost and the asserted budget cannot disagree.
///
/// [`PageLoad`](Self::PageLoad) and [`InstallOnly`](Self::InstallOnly) are BOTH pre-cached
/// (see [`is_precached`](Self::is_precached)) and are separated because they answer two
/// different questions that were previously answered with one number: what the worker stores
/// at install, and what a reader's page load actually costs. The published table now states
/// both, under headings that say which is which.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Fetch {
    /// Fetched by the PAGE on a first visit, before any pane can run: the document, the
    /// element and its worker, the session module, the vignette gallery, the transport, the
    /// always-resident core engine image and the ontology snapshot it boots over. Pre-cached
    /// too, so a returning reader gets them offline.
    PageLoad,
    /// Pre-cached at install, but NOT fetched by a page load: the service worker itself, the
    /// PWA manifest and its icon set (a browser reads those when a reader installs the
    /// console, not to paint it), and the vendored purrdf RDF/JS engine, which no pane
    /// dispatches to but which the published tree offers an embedder to import. All of it is
    /// pre-cached because it is part of the OFFLINE surface: an importable engine or a
    /// declared icon that was not cached would 404 for exactly the reader the offline
    /// contract is for.
    InstallOnly,
    /// Fetched only when a pane first needs it — the demand-loaded reasoning segment. It is
    /// NOT pre-cached at install; the worker's cache-first handler stores it the first time
    /// something actually asks for it, which is what makes the deferral real.
    Demand,
    /// Shipped in the tree but never fetched by the console: the documentation site's own
    /// controller, its conjecture library, and this README. They ride along because the
    /// console and the site share one `assets/` tree; the console asks for none of them.
    Never,
}

impl Fetch {
    /// Whether `sw.mjs` pre-caches this tier at install — the set the ceiling bounds.
    ///
    /// EXHAUSTIVE over the four variants, with no catch-all: a fifth tier has to say whether
    /// it is downloaded on install, and a `_` arm would answer for it silently.
    #[must_use]
    pub const fn is_precached(self) -> bool {
        match self {
            Self::PageLoad | Self::InstallOnly => true,
            Self::Demand | Self::Never => false,
        }
    }
}

/// Which tier an assembled key belongs to.
///
/// TOTAL BY REFUSAL, never by guess. Every console key is looked up in [`SHELL_FILES`] or
/// [`GENERATED_CONSOLE_FILES`], and every shared key in [`ASSET_TIERS`]; a key in none of
/// them panics. The classification this replaced fell through an `else` to the first-load
/// tier, so any newly emitted asset silently joined the set the published byte table calls
/// the first load and the service worker downloads at install — which is how the vendored
/// purrdf engine, the PWA manifest and four icons came to be published as bytes "fetched
/// before any pane runs" when no page load fetches any of them.
///
/// The tiers themselves are read off the shipped modules' own fetch routes: `assets/mcp/…`
/// is what `mcp-transport.mjs`'s `loadSegment` imports on the typed `mcp.segment-not-loaded`
/// signal, and `docs-controller.mjs` / `conjectures.ttl` are reached only from the
/// documentation site's pages, which are outside this worker's scope.
///
/// # Panics
///
/// If `key` is not a declared console file and matches no declared asset entry — an asset
/// was added to the emitted tree without being given a tier.
#[must_use]
pub fn fetch_tier(key: &str) -> Fetch {
    if let Some(name) = key.strip_prefix(CONSOLE_PREFIX) {
        return SHELL_FILES
            .iter()
            .find(|(shell, _, _)| *shell == name)
            .map(|(_, _, tier)| *tier)
            .or_else(|| {
                GENERATED_CONSOLE_FILES
                    .iter()
                    .find(|(generated, _)| *generated == name)
                    .map(|(_, tier)| *tier)
            })
            .unwrap_or_else(|| {
                panic!(
                    "the assembled console emits {key}, which is neither a declared shell \
                     file nor a generated console file — add it to SHELL_FILES or to \
                     GENERATED_CONSOLE_FILES with the tier it belongs to, in \
                     crates/docs/src/console.rs"
                )
            });
    }
    ASSET_TIERS
        .iter()
        .find(|(pattern, _)| covers(pattern, key))
        .map(|(_, tier)| *tier)
        .unwrap_or_else(|| {
            panic!(
                "the assembled console emits {key}, which no ASSET_TIERS entry covers — \
                 declare its tier in crates/docs/src/console.rs rather than letting it join \
                 one by default"
            )
        })
}

/// Whether an [`ASSET_TIERS`] pattern covers `key`: a directory prefix, or an exact key.
fn covers(pattern: &str, key: &str) -> bool {
    if pattern.ends_with('/') {
        key.starts_with(pattern)
    } else {
        key == pattern
    }
}

/// The complete standalone-console tree for an exec-backed render.
///
/// Keys span two prefixes and that is deliberate: `console/…` is the shell, and `assets/…`
/// is the shared engine set the documentation site already emits — the console does not
/// carry a second copy of a 7 MB wasm image.
///
/// Empty when the render is not interactive: a console with no engine is not a smaller
/// console, it is a broken one, so none of it is emitted rather than half of it.
///
/// # Panics
///
/// If the assembled tree has no pre-cached tier at all, if any generated surface's marker is
/// missing from its authored source, or if an emitted key has no declared [`Fetch`] tier.
#[must_use]
pub fn console_files(exec: &ExecutableDocsData) -> BTreeMap<String, Vec<u8>> {
    let mut files = interactive_asset_files(exec);
    if files.is_empty() {
        return files;
    }
    for (name, bytes, _) in SHELL_FILES {
        files.insert(format!("{CONSOLE_PREFIX}{name}"), bytes.to_vec());
    }
    files.insert(
        TRANSPORT_FORWARDER_KEY.to_string(),
        TRANSPORT_FORWARDER.as_bytes().to_vec(),
    );

    // The deployed-site sections go in FIRST, before anything is digested or measured. The
    // authored README is the npm package's own document and carries none of them; the site's
    // copy carries all of them, and both are then one file whose bytes this producer knows.
    files.insert(README_KEY.to_string(), site_readme(&files).into_bytes());

    // The build digest is taken over the assembled tree BEFORE the two derived surfaces are
    // written into it, so it is a function of the build inputs alone and cannot chase its
    // own tail. The README is digested with its site sections but WITHOUT its measured
    // table: the table is a pure function of the very files already digested here, so
    // nothing it could say is unrepresented.
    let build = build_digest(&files);

    // The worker is generated over the finished key set and then inserted — so its own path
    // is part of the shell it caches while its bytes stay a pure function of everything
    // else. The pre-cache set is every PRE-CACHED tier: pre-caching the demand-loaded
    // reasoning segment would download it on install and make the deferral a fiction.
    let mut shell: Vec<String> = files
        .keys()
        .filter(|key| fetch_tier(key).is_precached())
        .map(|key| sw_relative(key))
        .collect();
    shell.push(sw_relative(&format!("{CONSOLE_PREFIX}sw.mjs")));
    shell.sort();
    files.insert(
        format!("{CONSOLE_PREFIX}sw.mjs"),
        service_worker(&shell, &build).into_bytes(),
    );

    // The published byte table is measured over the FINAL runtime tree (the worker
    // included), and the ceiling the table publishes is DERIVED from that same measurement
    // — so the two numbers cannot disagree and the factor between them is an identity.
    //
    // What is asserted here is the one thing the derivation cannot supply: that there IS a
    // measurement, in each of the two tiers the table reports separately. A tree with an
    // empty page-load tier would publish a zero page-load total against which the browser's
    // recorded wire log would agree only by fetching nothing; a tree with an empty pre-cache
    // would publish a zero ceiling. Both would pass every downstream check vacuously over a
    // console that boots nothing.
    let report = ByteReport::of(&files);
    assert!(
        report.page_load_total > 0,
        "the assembled console has an empty page-load tier — there is nothing to measure, \
         so the published page-load total would be zero and the browser lane would assert \
         it against an empty wire log"
    );
    assert!(
        report.precache_total() > 0,
        "the assembled console has an empty pre-cache tier — there is nothing to measure, \
         so the published byte table and the ceiling derived from it would both be zero"
    );
    let readme = String::from_utf8(files[README_KEY].clone()).expect("the console README is UTF-8");
    assert!(
        readme.contains(BYTE_TABLE_MARKER),
        "crates/docs/assets/console-site-readme.md no longer carries the \
         {BYTE_TABLE_MARKER} marker — the measured byte table cannot be substituted"
    );
    files.insert(
        README_KEY.to_string(),
        readme
            .replacen(BYTE_TABLE_MARKER, &report.markdown(), 1)
            .into_bytes(),
    );
    files
}

/// The site's copy of the console README: the authored (npm) document with the deployed-site
/// sections substituted at [`SITE_SECTIONS_MARKER`].
///
/// # Panics
///
/// If the authored README no longer carries the marker. Shipping it unsubstituted would
/// deploy a console whose own document says nothing about the worker that serves it.
fn site_readme(files: &BTreeMap<String, Vec<u8>>) -> String {
    let readme = String::from_utf8(files[README_KEY].clone()).expect("the console README is UTF-8");
    assert!(
        readme.contains(SITE_SECTIONS_MARKER),
        "crates/docs/assets/console/README.md no longer carries the {SITE_SECTIONS_MARKER} \
         marker — the deployed-site sections cannot be substituted"
    );
    assert_eq!(
        hand_authored_byte_magnitudes(SITE_SECTIONS_SOURCE),
        Vec::<String>::new(),
        "crates/docs/assets/console-site-readme.md states a byte magnitude in its prose. \
         Every byte figure in that document is GENERATED from the assembled tree; a typed \
         one is a second source of truth that goes stale the next time an engine is \
         re-vendored, which is exactly what happened to the reasoning segment's size. Refer \
         to the measured table instead of restating a number beside it"
    );
    readme.replacen(SITE_SECTIONS_MARKER, SITE_SECTIONS_SOURCE.trim(), 1)
}

/// The units a hand-typed byte magnitude can be spelled in, longest spelling first.
///
/// Matched case-insensitively and longest-first, so `megabytes` is recognised before `b`
/// could match its tail. Bare `b` is included because `8 MB` and `8b` are the same defect.
const BYTE_UNITS: &[&str] = &[
    "gigabytes",
    "megabytes",
    "kilobytes",
    "gigabyte",
    "megabyte",
    "kilobyte",
    "bytes",
    "byte",
    "gib",
    "mib",
    "kib",
    "gb",
    "mb",
    "kb",
    "b",
];

/// Every hand-authored byte magnitude in `text` — a number immediately followed by a byte
/// unit — as the matched substrings, in order.
///
/// The gate on the spliced site sections, and the whole of it. `10 MB` sat twenty-two lines
/// above a GENERATED table reading `12 373 564` under a heading asserting "Nothing in this
/// section is typed in", because the image grew and the prose did not; the same class of
/// defect had been closed once already and came back in the next commit. Prose cannot be
/// kept in step with a measurement by remembering to retype it, so a magnitude in prose is
/// refused outright and the reader is sent to the measured table.
///
/// Deliberately SYNTACTIC and unit-anchored: it catches `10 MB`, `10MB`, `1.5 GiB`,
/// `12 373 564 bytes` and `8b`, and leaves alone the numbers that are not sizes — `icon-192`,
/// `RDF-1.2`, `BLAKE3`, `start_url`. A number with no unit beside it is not a byte claim.
#[must_use]
pub fn hand_authored_byte_magnitudes(text: &str) -> Vec<String> {
    let bytes = text.as_bytes();
    let mut found = Vec::new();
    let mut at = 0usize;
    while at < bytes.len() {
        // Anchor on a digit that starts a number (not one inside a longer token).
        if !bytes[at].is_ascii_digit() || (at > 0 && is_number_body(bytes[at - 1])) {
            at += 1;
            continue;
        }
        // The numeral: digits, with `.`, `,`, `_` or a single space allowed BETWEEN digits,
        // so grouped forms like `12 373 564` and `1.5` are one number rather than three.
        let start = at;
        let mut end = at;
        while end < bytes.len()
            && (bytes[end].is_ascii_digit()
                || (matches!(bytes[end], b'.' | b',' | b'_' | b' ')
                    && bytes.get(end + 1).is_some_and(u8::is_ascii_digit)))
        {
            end += 1;
        }
        at = end;
        // The unit, after at most one separating space.
        let unit_at = if bytes.get(end) == Some(&b' ') {
            end + 1
        } else {
            end
        };
        let tail = &text[unit_at..];
        if let Some(unit) = BYTE_UNITS.iter().find(|unit| {
            tail.len() >= unit.len()
                && tail[..unit.len()].eq_ignore_ascii_case(unit)
                // A unit must END the word: `10 Mbps` and `3blind` are not byte claims.
                && !tail[unit.len()..]
                    .chars()
                    .next()
                    .is_some_and(|c| c.is_alphanumeric())
        }) {
            found.push(text[start..unit_at + unit.len()].to_string());
        }
    }
    found
}

/// Whether `byte` continues a numeral or an identifier, so a digit after it does not start
/// a fresh number (`icon-512` starts one; `blake3x2` does not start one at `2`).
const fn is_number_body(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b',' | b'_')
}

/// The console's transport entry, as emitted into the SITE tree.
///
/// One generated forwarder, and it exists so that ONE import specifier
/// (`./pkg/mcp-transport.mjs`, in `console/engine.worker.mjs`) resolves in BOTH trees the
/// console ships as. On the site the real module is the shared `assets/mcp-transport.mjs`
/// the documentation controller also imports, so forwarding is what keeps the site at one
/// engine copy instead of two; in the published npm package there is no site around the
/// console, so the package's `prepack` stages the real module — and the whole engine
/// payload it imports — at this same path.
///
/// A re-export is not a second implementation: it resolves to the SAME module instance, so
/// the transport's configured asset base and its cached engine promise are shared, not
/// duplicated.
const TRANSPORT_FORWARDER: &str = "// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>\n\
     // SPDX-License-Identifier: AGPL-3.0-only\n\
     \n\
     // GENERATED by crates/docs/src/console.rs. Do not edit.\n\
     //\n\
     // The console's engine worker imports its transport as `./pkg/mcp-transport.mjs` so that\n\
     // one specifier resolves both in this site tree and in the published npm package, where\n\
     // the whole engine payload is staged under `pkg/`. Here the real module is the shared\n\
     // `assets/mcp-transport.mjs` the documentation controller imports too, so this forwards\n\
     // to it rather than duplicating a 29 kB module — and, transitively, the 7 MB engine\n\
     // image it pulls in.\n\
     //\n\
     // `export *` re-exports the SAME module instance: the transport's configured asset base\n\
     // and its cached boot promise are shared with every other importer, not re-created.\n\
     \n\
     export * from \"../../assets/mcp-transport.mjs\";\n";

/// A console-tree key expressed relative to `console/sw.mjs` (the worker's own URL).
///
/// `console/element.mjs` → `./element.mjs`; `assets/mcp-core/index.mjs` →
/// `../assets/mcp-core/index.mjs`. The worker resolves each against its own location, so
/// the console works at any site depth and from `file://`.
fn sw_relative(key: &str) -> String {
    match key.strip_prefix(CONSOLE_PREFIX) {
        Some(rest) => format!("./{rest}"),
        None => format!("../{key}"),
    }
}

/// The BLAKE3 content digest of an assembled tree, as the hex the cache name carries.
///
/// Keyed on BYTES, because the cache name's whole job is to make a rebuild un-reusable when
/// the bytes changed. Keying it on the shell's entry count and joined path length — which
/// is what it used to do — means any rebuild that keeps the same paths keeps the same cache
/// name and serves the OLD bytes to every returning reader, which is the exact failure a
/// versioned cache exists to prevent.
///
/// The encoding is length-prefixed per entry, so no pair of distinct trees can hash to the
/// same digest by moving bytes across a key boundary.
fn build_digest(files: &BTreeMap<String, Vec<u8>>) -> String {
    let mut hasher = blake3::Hasher::new();
    for (key, bytes) in files {
        hasher.update(&(key.len() as u64).to_le_bytes());
        hasher.update(key.as_bytes());
        hasher.update(&(bytes.len() as u64).to_le_bytes());
        hasher.update(bytes);
    }
    hasher.finalize().to_hex()[..16].to_string()
}

/// The service-worker source with its `SHELL` array and cache name substituted.
///
/// # Panics
///
/// If the authored `sw.mjs` no longer carries [`SHELL_MARKER`] or [`BUILD_MARKER`]. That is
/// a build-input break, not a runtime condition: shipping the unsubstituted source would
/// cache the literal string `__GMEOW_CONSOLE_SHELL__` and produce a console that appears to
/// work online and fails offline.
fn service_worker(shell: &[String], build: &str) -> String {
    assert!(
        SW_SOURCE.contains(SHELL_MARKER),
        "crates/docs/assets/console/sw.mjs no longer carries the {SHELL_MARKER} marker — the \
         generated SHELL cannot be substituted"
    );
    assert!(
        SW_SOURCE.contains(BUILD_MARKER),
        "crates/docs/assets/console/sw.mjs no longer carries the {BUILD_MARKER} marker — the \
         generated build digest cannot be substituted"
    );
    let rendered = shell
        .iter()
        .map(|path| format!("  {},", json_string(path)))
        .collect::<Vec<_>>()
        .join("\n");
    SW_SOURCE
        .replacen(SHELL_MARKER, &format!("[\n{rendered}\n]"), 1)
        .replacen(BUILD_MARKER, &json_string(build), 1)
}

/// A JSON string literal (the only escapes a site-relative path can need).
fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── the measured byte report ────────────────────────────────────────────────

/// The measured byte cost of an assembled console tree, partitioned by [`Fetch`].
///
/// MEASURED, never authored. The hand-written table this replaced was wrong on nearly
/// every row and omitted two assets the console fetches on every boot, because a table
/// typed into a document is a second source of truth for bytes that move on every build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ByteReport {
    /// `(key, bytes, tier)` for every emitted asset, in key order.
    pub rows: Vec<(String, u64, Fetch)>,
    /// What the PAGE fetches on a first visit, before any pane can run.
    pub page_load_total: u64,
    /// What the worker pre-caches at install that a page load never asks for.
    pub install_only_total: u64,
    /// The total the demand-loaded reasoning segment costs, when a pane first needs it.
    pub demand_total: u64,
}

impl ByteReport {
    /// What `cache.addAll` downloads at install: the page-load tier plus the install-only
    /// tier. This is the set the ceiling bounds, and it is strictly larger than
    /// [`page_load_total`](Self::page_load_total) — which is exactly why the two are
    /// published as separate numbers under headings that name them.
    #[must_use]
    pub const fn precache_total(&self) -> u64 {
        self.page_load_total + self.install_only_total
    }

    /// The published ceiling for THIS measurement — the derived identity
    /// [`precache_ceiling`], never a stored number. The ratio of this to
    /// [`precache_total`](Self::precache_total) is [`PRECACHE_CEILING_FACTOR`] by
    /// construction, which is what the generated README sentence states.
    #[must_use]
    pub const fn ceiling(&self) -> u64 {
        precache_ceiling(self.precache_total())
    }

    /// Measure an assembled tree.
    #[must_use]
    pub fn of(files: &BTreeMap<String, Vec<u8>>) -> Self {
        let rows: Vec<(String, u64, Fetch)> = files
            .iter()
            .map(|(key, bytes)| (key.clone(), bytes.len() as u64, fetch_tier(key)))
            .collect();
        let total = |tier: Fetch| {
            rows.iter()
                .filter(|(_, _, row)| *row == tier)
                .map(|(_, bytes, _)| *bytes)
                .sum()
        };
        Self {
            page_load_total: total(Fetch::PageLoad),
            install_only_total: total(Fetch::InstallOnly),
            demand_total: total(Fetch::Demand),
            rows,
        }
    }

    /// The report as the Markdown section the shipped README publishes.
    ///
    /// FOUR tiers, each under a heading that says what it is. The heading this replaced read
    /// "First load — everything fetched before any pane runs" over a table that also carried
    /// 8 MB of vendored purrdf, a PWA manifest and four icons — none of which a page load
    /// fetches, a fact the same document stated forty lines further down. The set was always
    /// the install pre-cache; only its title was wrong. Both numbers are published now, so
    /// neither has to stand in for the other.
    #[must_use]
    pub fn markdown(&self) -> String {
        let mut out = String::new();
        out.push_str(
            "*Generated by `crates/docs/src/console.rs` from the assembled tree — measured \
             uncompressed on-disk bytes, no transfer encoding assumed. Nothing in this \
             section is typed in.*\n",
        );
        self.section(
            &mut out,
            Fetch::PageLoad,
            "Page load",
            "what the page itself fetches on a first visit, before any pane can run. The \
             browser smoke lane records a real first load in Chromium and asserts the \
             recorded set against this one in BOTH directions, so a row here that no page \
             load asks for fails the gate instead of inflating the number",
        );
        self.section(
            &mut out,
            Fetch::InstallOnly,
            "Pre-cached at install, not fetched by a page load",
            "the service worker itself, the PWA manifest and its icons (a browser reads \
             those when a reader installs the console, not to paint it), and the vendored \
             purrdf engine an embedding page may import. Nothing here is on the boot path; \
             all of it is stored at install, because an offline reader who cannot install \
             the console or import the engine is exactly the reader the offline contract is \
             for",
        );
        self.section(
            &mut out,
            Fetch::Demand,
            "Demand-loaded reasoning segment",
            "fetched only when a pane first needs a reasoning-segment tool, and never at \
             all for a reader who only looks things up",
        );
        self.section(
            &mut out,
            Fetch::Never,
            "Shipped, never fetched by the console",
            "shared with the documentation site, which reaches them from its own pages. \
             This document is the one emitted file the table omits: it is where the table \
             is published, so a row for its own size could never be the size it reports",
        );
        out.push_str(&format!(
            "\n**Totals** — the sums of the sections above:\n\n| Set | Bytes |\n|---|---:|\n\
             | **Page-load total** | **{}** |\n\
             | **Install-only total** | **{}** |\n\
             | **Install pre-cache total** | **{}** |\n\
             | **Demand-loaded segment total** | **{}** |\n",
            grouped(self.page_load_total),
            grouped(self.install_only_total),
            grouped(self.precache_total()),
            grouped(self.demand_total),
        ));
        // Every number AND the factor in this sentence come from the same measurement and
        // the same constant the ceiling is derived from, so it cannot state a ratio the two
        // numbers above it contradict. The sentence it replaced was hard-coded prose
        // ("plus ten percent of headroom") sitting directly under a pair of numbers whose
        // real ratio had drifted to 1.09609.
        //
        // What the sentence then SAID about that derived number was still false. It read
        // "it bounds what `cache.addAll` downloads at install", which a reader takes for a
        // budget somebody chose and something enforces. A fixed multiple of a measurement
        // bounds nothing: the measured pre-cache moved by megabytes and the published
        // ceiling moved with it, staying exactly the same factor away, and no assertion
        // anywhere could have reddened — every check over it was of the form `2n > n`. So
        // the document now says what the number is (a ratio that TRACKS the measurement)
        // and says outright that no size-regression gate exists here, rather than
        // presenting an identity as a limit.
        out.push_str(&format!(
            "\nThe install pre-cache ceiling is **{}** bytes — the pre-cache total above × \
             {}, recomputed from that same measurement on every render.\n\
             \n{NO_SIZE_GATE_DISCLOSURE}\n\
             \nThe measured figures above are the load-bearing ones, and they are asserted \
             against reality rather than against each other: the assembled tree on disk must \
             sum to the published totals, and a recorded first load in a real browser must \
             fetch EXACTLY the published page-load set, checked in both directions. Those \
             checks red when the artifact and this document disagree. What `cache.addAll` \
             downloads at install is the two pre-cached sections together — not the \
             page-load figure, which is smaller and is the one asserted against the \
             browser's recorded wire log.\n",
            grouped(self.ceiling()),
            PRECACHE_CEILING_FACTOR,
        ));
        out
    }

    /// One tier's table.
    fn section(&self, out: &mut String, tier: Fetch, title: &str, gloss: &str) {
        out.push_str(&format!(
            "\n**{title}** — {gloss}:\n\n| Asset | Bytes |\n|---|---:|\n"
        ));
        for (key, bytes, row) in &self.rows {
            // The README carries this table, so its emitted size is strictly larger than
            // the size any row here could state. Omitting it is the only honest option: a
            // number that is wrong the instant it is written is worse than an absence that
            // is explained.
            if *row == tier && key != README_KEY {
                out.push_str(&format!("| `{key}` | {} |\n", grouped(*bytes)));
            }
        }
    }
}

/// A byte count with thousands separated by a space, matching the table's own style.
fn grouped(value: u64) -> String {
    let digits = value.to_string();
    let mut out = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index).is_multiple_of(3) {
            out.push(' ');
        }
        out.push(digit);
    }
    out
}

/// The generated `SHELL` set of an assembled console tree, read back out of its `sw.mjs`.
///
/// Exposed so the acceptance assertion can compare the GENERATED set against the PRE-CACHED
/// tiers in both directions, over the shipped bytes rather than over the producer's
/// intermediate state.
///
/// # Panics
///
/// If the tree carries no `console/sw.mjs`, or its `SHELL` array cannot be read.
#[must_use]
pub fn generated_shell(files: &BTreeMap<String, Vec<u8>>) -> Vec<String> {
    let text = sw_text(files);
    let open = text
        .find("const SHELL = [")
        .expect("sw.mjs declares const SHELL")
        + "const SHELL = [".len();
    let close = open + text[open..].find(']').expect("the SHELL array closes");
    text[open..close]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| entry.trim_matches('"').to_string())
        .collect()
}

/// The generated cache name of an assembled console tree, read back out of its `sw.mjs`.
///
/// # Panics
///
/// If the tree carries no `console/sw.mjs`, or its `BUILD` constant cannot be read.
#[must_use]
pub fn generated_build_digest(files: &BTreeMap<String, Vec<u8>>) -> String {
    let text = sw_text(files);
    let open = text
        .find("const BUILD = \"")
        .expect("sw.mjs declares const BUILD")
        + "const BUILD = \"".len();
    let close = open + text[open..].find('"').expect("the BUILD literal closes");
    text[open..close].to_string()
}

/// The assembled tree's service worker, as text.
fn sw_text(files: &BTreeMap<String, Vec<u8>>) -> String {
    let sw = files
        .get(&format!("{CONSOLE_PREFIX}sw.mjs"))
        .expect("an assembled console tree carries console/sw.mjs");
    String::from_utf8(sw.clone()).expect("sw.mjs is UTF-8")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An `exec` that makes a render interactive (the renderer only checks non-emptiness).
    fn interactive_exec() -> ExecutableDocsData {
        ExecutableDocsData {
            full_bundle_gts: b"gts-bundle-sentinel-bytes".to_vec(),
            conjectures_ttl: b"@prefix ex: <http://example/> .".to_vec(),
            ..Default::default()
        }
    }

    /// Determinism: the same `exec` yields byte-identical maps.
    #[test]
    fn console_files_is_deterministic() {
        let exec = interactive_exec();
        assert_eq!(console_files(&exec), console_files(&exec));
    }

    /// The console never re-cuts a shared asset: every key both maps carry is byte-equal.
    #[test]
    fn shared_asset_bytes_are_identical() {
        let exec = interactive_exec();
        let console = console_files(&exec);
        let shared = interactive_asset_files(&exec);
        assert!(!shared.is_empty(), "the fixture must be interactive");
        for (key, bytes) in &shared {
            assert_eq!(
                console.get(key),
                Some(bytes),
                "shared asset {key} differs between the console and the site"
            );
        }
    }

    /// The generated `SHELL` set EQUALS the PRE-CACHED tiers, in both directions.
    #[test]
    fn generated_shell_equals_the_precached_tiers() {
        let files = console_files(&interactive_exec());
        let generated: std::collections::BTreeSet<String> =
            generated_shell(&files).into_iter().collect();
        let expected: std::collections::BTreeSet<String> = files
            .keys()
            .filter(|key| fetch_tier(key).is_precached())
            .map(|key| sw_relative(key))
            .collect();
        assert_eq!(
            generated, expected,
            "the generated SHELL must equal the pre-cached tiers"
        );
        assert!(
            generated.contains("./sw.mjs"),
            "the worker caches its own script: {generated:?}"
        );
        assert!(
            generated.iter().any(|path| path.starts_with("../assets/")),
            "the out-of-scope engine assets must be pre-cached: {generated:?}"
        );
    }

    /// A non-interactive render emits NO console key at all.
    #[test]
    fn non_interactive_render_emits_no_console() {
        assert!(console_files(&ExecutableDocsData::default()).is_empty());
    }

    /// The substituted worker and README carry no marker residue.
    #[test]
    fn every_marker_is_fully_substituted() {
        let files = console_files(&interactive_exec());
        let sw = String::from_utf8(files[&format!("{CONSOLE_PREFIX}sw.mjs")].clone()).unwrap();
        assert!(
            !sw.contains("__GMEOW_CONSOLE_SHELL__") && !sw.contains("__GMEOW_CONSOLE_BUILD__"),
            "unsubstituted worker marker survived"
        );
        let readme = String::from_utf8(files[README_KEY].clone()).unwrap();
        assert!(
            !readme.contains("__GMEOW_CONSOLE_BYTE_TABLE__")
                && !readme.contains("__GMEOW_CONSOLE_SITE_SECTIONS__"),
            "unsubstituted README marker survived"
        );
    }

    /// Every declared tier row is USED, and no key matches two of them.
    ///
    /// A pattern that covers nothing is a classification for an asset that no longer exists,
    /// and a key covered twice is classified by table ORDER — which is the silent,
    /// order-dependent tiering the `else` arm this table replaced already had.
    #[test]
    fn the_tier_tables_are_exact() {
        let files = console_files(&interactive_exec());
        for (pattern, _) in ASSET_TIERS {
            assert!(
                files.keys().any(|key| covers(pattern, key)),
                "the ASSET_TIERS row {pattern} covers no emitted key"
            );
        }
        for key in files.keys() {
            if key.starts_with(CONSOLE_PREFIX) {
                continue;
            }
            let matched: Vec<&str> = ASSET_TIERS
                .iter()
                .filter(|(pattern, _)| covers(pattern, key))
                .map(|(pattern, _)| *pattern)
                .collect();
            assert_eq!(
                matched.len(),
                1,
                "{key} is covered by {matched:?} — a key must have exactly one declared tier"
            );
        }
        for (name, _, _) in SHELL_FILES {
            assert!(
                GENERATED_CONSOLE_FILES
                    .iter()
                    .all(|(generated, _)| generated != name),
                "console/{name} is declared both as an authored shell file and as a \
                 generated one"
            );
        }
    }

    /// An emitted key with no declared tier is REFUSED, not swept into one.
    #[test]
    #[should_panic(expected = "no ASSET_TIERS entry covers")]
    fn an_undeclared_asset_key_is_refused() {
        let _ = fetch_tier("assets/some-newly-vendored-engine/index.mjs");
    }

    /// The same refusal on the console side of the tree.
    #[test]
    #[should_panic(expected = "neither a declared shell file nor a generated console file")]
    fn an_undeclared_console_key_is_refused() {
        let _ = fetch_tier("console/newly-added-pane.mjs");
    }

    /// The two published totals are the two SUMS, and the pre-cache set is their union.
    #[test]
    fn the_published_totals_partition_the_measured_tree() {
        let files = console_files(&interactive_exec());
        let report = ByteReport::of(&files);
        let summed = |tier: Fetch| -> u64 {
            files
                .iter()
                .filter(|(key, _)| fetch_tier(key) == tier)
                .map(|(_, bytes)| bytes.len() as u64)
                .sum()
        };
        assert_eq!(report.page_load_total, summed(Fetch::PageLoad));
        assert_eq!(report.install_only_total, summed(Fetch::InstallOnly));
        assert_eq!(
            report.precache_total(),
            summed(Fetch::PageLoad) + summed(Fetch::InstallOnly)
        );
        assert!(
            report.install_only_total > 0,
            "the fixture must carry install-only bytes for the split to be meaningful"
        );
        assert!(
            report.precache_total() > report.page_load_total,
            "the pre-cache set must be strictly larger than the page load — otherwise the \
             two published numbers are the same number under two headings"
        );
        // There is deliberately NO assertion here relating `ceiling()` to `precache_total()`.
        // `ceiling()` IS `precache_total() × PRECACHE_CEILING_FACTOR` by definition, so
        // `assert_eq!(report.ceiling(), report.precache_total() * 2)` — which stood here —
        // restated the definition against a second hard-coded copy of the factor and no
        // measurement could ever have reddened it. What the README publishes about that
        // derived number IS asserted, in the producer acceptance lane, against the shipped
        // prose: that it is the derived figure, and that the document says outright it is
        // not a budget.
    }

    /// The AUTHORED site sections carry no hand-typed byte magnitude, anywhere in them.
    ///
    /// The total form of the gate — over the whole authored source, not over a slice of the
    /// emitted document — because this test can see the private constant the producer
    /// splices. `console_files` refuses to splice a source that fails this, so the check is
    /// fail-closed at render time as well; this pins it as a named test so the reason it
    /// exists is written down next to it rather than only inside a panic message.
    #[test]
    fn the_authored_site_sections_state_no_byte_magnitude() {
        assert_eq!(
            hand_authored_byte_magnitudes(SITE_SECTIONS_SOURCE),
            Vec::<String>::new(),
            "crates/docs/assets/console-site-readme.md states a byte magnitude in prose. It \
             carried \"a 10 MB image\" twenty-two lines above a GENERATED table measuring \
             that same image at 12 373 564 — under a heading asserting nothing in the \
             section is typed in — because the engine grew and the sentence did not. Refer \
             to the measured table; do not restate a number beside it"
        );
    }

    /// The scanner catches real hand-typed magnitudes and leaves real prose alone.
    ///
    /// Pins the gate itself. A detector that finds nothing is indistinguishable from clean
    /// prose, and the defect it exists to catch is one that already came back once.
    #[test]
    fn the_byte_magnitude_scanner_is_not_vacuous() {
        for typed in [
            "pre-caching a 10 MB image at install",
            "the 7 MB core image is not duplicated",
            "duplicating a 29 kB module",
            "cache.addAll over a 56MB tier",
            "a 1.5 GiB dataset",
            "12 373 564 bytes on disk",
            "an 8b header",
        ] {
            assert!(
                !hand_authored_byte_magnitudes(typed).is_empty(),
                "the scanner missed a hand-typed magnitude in {typed:?}"
            );
        }
        for clean in [
            "icon-192.png, icon-512.png and icon-maskable-512.png",
            "a BLAKE3 content digest of the assembled tree",
            "RDF-1.2 quoted triples over 38 tools",
            "`display: standalone`, `start_url: \".\"`",
            "the demand-loaded total in the table below",
            "a 10 Mbps link",
        ] {
            assert_eq!(
                hand_authored_byte_magnitudes(clean),
                Vec::<String>::new(),
                "the scanner flagged prose that states no byte magnitude: {clean:?}"
            );
        }
        assert_eq!(
            hand_authored_byte_magnitudes("a 10 MB image and a 7MB one"),
            vec!["10 MB".to_string(), "7MB".to_string()],
            "the scanner must report every magnitude it finds, in order"
        );
    }

    /// The cache name is a digest of the BYTES: same paths + different bytes ⇒ new cache.
    #[test]
    fn the_cache_name_changes_when_a_byte_changes() {
        let one = console_files(&interactive_exec());
        let mut other = interactive_exec();
        // Same length, one byte different — the substitution a length-based key accepts.
        other.full_bundle_gts = b"gts-bundle-sentinel-byteS".to_vec();
        let two = console_files(&other);
        assert_eq!(
            one.keys().collect::<Vec<_>>(),
            two.keys().collect::<Vec<_>>(),
            "the two trees must have identical paths for this to be the interesting case"
        );
        assert_ne!(
            generated_build_digest(&one),
            generated_build_digest(&two),
            "a byte-for-byte substitution must produce a different cache name"
        );
    }
}
