// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The standalone-console producer.
//!
//! [`console_files`] is the SINGLE authority for "what the console is made of": the
//! `console/…` shell files (each a pinned `include_str!` / `include_bytes!` build input)
//! plus EVERY key of [`crate::render::interactive_asset_files`], so the console and the
//! documentation site ship the byte-identical engine the native↔wasm witness lanes prove.
//! There is no second list, and nothing is copied by hand.
//!
//! Three surfaces are GENERATED here, from the assembled map itself, because each of them
//! is a restatement of the key set or the byte set and a hand-authored restatement drifts
//! the moment a file is added:
//!
//! 1. the service worker's `SHELL` array — the install-time pre-cache set, which is the
//!    FIRST-LOAD tier of the assembled tree and nothing else (see [`Fetch`]);
//! 2. the service worker's cache name — a BLAKE3 content digest of the assembled tree, so
//!    a rebuild that keeps every path but changes a byte cannot reuse the old cache;
//! 3. the console README's measured-byte table and the first-load ceiling it is asserted
//!    against — measured over the emitted bytes, never typed in.
//!
//! Every substitution is fail-closed: a source whose marker is missing panics rather than
//! shipping a worker that caches nothing or a README that publishes a placeholder.
//!
//! Determinism is structural: the map is a [`BTreeMap`], every value is either a pinned
//! build input or a deterministic function of `exec`, and each generated surface is a pure
//! function of the map. Two calls over the same `exec` are byte-identical.

use std::collections::BTreeMap;

use gmeow_docs_model::exec::ExecutableDocsData;

use crate::render::interactive_asset_files;

/// The site-relative directory the console shell is emitted under.
pub const CONSOLE_PREFIX: &str = "console/";

/// The console-relative directory the console's own engine payload is served from.
///
/// On the SITE this holds one generated forwarder (see [`TRANSPORT_FORWARDER_KEY`]); in the
/// published npm package it holds the whole engine payload, staged there by the package's
/// `prepack` step from this producer's own output. Both trees therefore answer
/// `./pkg/mcp-transport.mjs` — which is why `console/engine.worker.mjs` can spell ONE
/// specifier and boot in both.
pub const CONSOLE_PAYLOAD_PREFIX: &str = "console/pkg/";

/// The shipped console README, whose measured-byte table [`console_files`] rewrites.
const README_KEY: &str = "console/README.md";

/// The transport entry point the console's engine worker imports.
pub const TRANSPORT_FORWARDER_KEY: &str = "console/pkg/mcp-transport.mjs";

/// The marker in the authored `sw.mjs` that the generated `SHELL` array replaces.
///
/// Public so the acceptance assertion can prove the authored source still carries it —
/// a renamed marker would otherwise degrade silently into "the substitution found
/// nothing", which the panic below already refuses at run time.
pub const SHELL_MARKER: &str = "[\"__GMEOW_CONSOLE_SHELL__\"]";

/// The marker in the authored `sw.mjs` that the generated build digest replaces.
pub const BUILD_MARKER: &str = "\"__GMEOW_CONSOLE_BUILD__\"";

/// The marker in the authored `README.md` that the generated byte table replaces.
pub const BYTE_TABLE_MARKER: &str = "<!-- __GMEOW_CONSOLE_BYTE_TABLE__ -->";

/// The console's first-load byte ceiling.
///
/// Set by MEASUREMENT, not by judgement: the assembled first-load tier was measured and the
/// ceiling placed at that measurement plus ten percent of headroom, which is the whole of
/// the rule. [`console_files`] asserts the assembled first-load total against it on every
/// render, so a change that pushes the console past the headroom is a hard build failure
/// naming both numbers — never a silently heavier first load. Re-measure and re-set it
/// deliberately when the ceiling is genuinely meant to move.
///
/// 47 534 469 measured × 1.1.
pub const FIRST_LOAD_CEILING_BYTES: u64 = 52_287_915;

/// One console shell file: its `console/`-relative name and its pinned bytes.
///
/// Every entry is an `include_*!` of a real file under `crates/docs/assets/console/`, so
/// the shipped console is exactly the reviewed source — never a string assembled here.
///
/// `smoke/` is deliberately absent. It is the dev-only Playwright manifest pair, and
/// including it deployed a private, `npm ci`-shaped scaffold to the public site AND
/// pre-cached it into every reader's offline storage — while the README said nothing under
/// `smoke/` ships. The lane reads those two files from the repository, where they live.
const SHELL_FILES: &[(&str, &[u8])] = &[
    ("index.html", include_bytes!("../assets/console/index.html")),
    (
        "element.mjs",
        include_bytes!("../assets/console/element.mjs"),
    ),
    (
        "engine.worker.mjs",
        include_bytes!("../assets/console/engine.worker.mjs"),
    ),
    (
        "session.mjs",
        include_bytes!("../assets/console/session.mjs"),
    ),
    (
        "examples/gallery.mjs",
        include_bytes!("../assets/console/examples/gallery.mjs"),
    ),
    (
        "manifest.webmanifest",
        include_bytes!("../assets/console/manifest.webmanifest"),
    ),
    // The PWA icon set the manifest declares. A manifest naming an icon the site never
    // emits is a 404, and a 404 icon is not an installable manifest — so the declared set
    // and the emitted set are the same set.
    ("icon.svg", include_bytes!("../assets/console/icon.svg")),
    (
        "icon-192.png",
        include_bytes!("../assets/console/icon-192.png"),
    ),
    (
        "icon-512.png",
        include_bytes!("../assets/console/icon-512.png"),
    ),
    (
        "icon-maskable-512.png",
        include_bytes!("../assets/console/icon-maskable-512.png"),
    ),
    ("README.md", include_bytes!("../assets/console/README.md")),
];

/// The authored service worker, whose `SHELL` array and cache name [`console_files`]
/// rewrites.
const SW_SOURCE: &str = include_str!("../assets/console/sw.mjs");

/// When the console fetches one emitted asset.
///
/// This is the console's OWN fetch behaviour, read off the shipped modules, and it is the
/// single partition three separate surfaces are derived from: the install-time `SHELL`, the
/// published byte table, and the ceiling assertion. One partition means the offline
/// pre-cache, the documented first-load cost and the asserted budget cannot disagree about
/// what a first load is.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub enum Fetch {
    /// Fetched before any pane can run: the shell, the transport, the always-resident core
    /// engine image and the ontology snapshot it boots over.
    First,
    /// Fetched only when a pane first needs it — the demand-loaded reasoning segment. It is
    /// NOT pre-cached at install; the worker's cache-first handler stores it the first time
    /// something actually asks for it, which is what makes the deferral real.
    Demand,
    /// Shipped in the tree but never fetched by the console: the documentation site's own
    /// controller, its conjecture library, and this README. They ride along because the
    /// console and the site share one `assets/` tree; the console asks for none of them.
    Never,
}

/// Which tier an assembled key belongs to.
///
/// Derived from the shipped modules' own fetch routes: `assets/mcp/…` is what
/// `mcp-transport.mjs`'s `loadSegment` imports on the typed `mcp.segment-not-loaded`
/// signal, and `docs-controller.mjs` / `conjectures.ttl` are reached only from the
/// documentation site's pages, which are outside this worker's scope.
#[must_use]
pub fn fetch_tier(key: &str) -> Fetch {
    if key.starts_with("assets/mcp/") {
        Fetch::Demand
    } else if key == "assets/docs-controller.mjs"
        || key == "assets/conjectures.ttl"
        || key == README_KEY
    {
        Fetch::Never
    } else {
        Fetch::First
    }
}

/// The complete standalone-console tree for an exec-backed render.
///
/// Keys span two prefixes and that is deliberate: `console/…` is the shell, and `assets/…`
/// is the shared engine set the documentation site already emits — the console does not
/// carry a second copy of a 7 MB wasm image.
///
/// Empty when the render is not interactive: a console with no engine is not a smaller
/// console, it is a broken one, so none of it is emitted rather than half of it.
///
/// # Panics
///
/// If the assembled first-load tier exceeds [`FIRST_LOAD_CEILING_BYTES`], or if any
/// generated surface's marker is missing from its authored source.
#[must_use]
pub fn console_files(exec: &ExecutableDocsData) -> BTreeMap<String, Vec<u8>> {
    let mut files = interactive_asset_files(exec);
    if files.is_empty() {
        return files;
    }
    for (name, bytes) in SHELL_FILES {
        files.insert(format!("{CONSOLE_PREFIX}{name}"), bytes.to_vec());
    }
    files.insert(
        TRANSPORT_FORWARDER_KEY.to_string(),
        TRANSPORT_FORWARDER.as_bytes().to_vec(),
    );

    // The build digest is taken over the assembled tree BEFORE the two derived surfaces are
    // written into it, so it is a function of the build inputs alone and cannot chase its
    // own tail. The README is digested as its AUTHORED bytes: its published table is a pure
    // function of the very files already digested here, so nothing it could say is
    // unrepresented.
    let build = build_digest(&files);

    // The worker is generated over the finished key set and then inserted — so its own path
    // is part of the shell it caches while its bytes stay a pure function of everything
    // else. The pre-cache set is the FIRST-LOAD tier: pre-caching the demand-loaded
    // reasoning segment would download it on install and make the deferral a fiction.
    let mut shell: Vec<String> = files
        .keys()
        .filter(|key| fetch_tier(key) == Fetch::First)
        .map(|key| sw_relative(key))
        .collect();
    shell.push(sw_relative(&format!("{CONSOLE_PREFIX}sw.mjs")));
    shell.sort();
    files.insert(
        format!("{CONSOLE_PREFIX}sw.mjs"),
        service_worker(&shell, &build).into_bytes(),
    );

    // The published byte table is measured over the FINAL runtime tree (the worker
    // included), and the ceiling is asserted over the same measurement the table publishes.
    let report = ByteReport::of(&files);
    assert!(
        report.first_load_total <= FIRST_LOAD_CEILING_BYTES,
        "the console's first load is {} bytes, over the measured ceiling of {} \
         (FIRST_LOAD_CEILING_BYTES in crates/docs/src/console.rs). Re-measure and re-set \
         the ceiling deliberately, or take the bytes back out.",
        report.first_load_total,
        FIRST_LOAD_CEILING_BYTES
    );
    let readme = String::from_utf8(files[README_KEY].clone()).expect("the console README is UTF-8");
    assert!(
        readme.contains(BYTE_TABLE_MARKER),
        "crates/docs/assets/console/README.md no longer carries the {BYTE_TABLE_MARKER} \
         marker — the measured byte table cannot be substituted"
    );
    files.insert(
        README_KEY.to_string(),
        readme
            .replacen(BYTE_TABLE_MARKER, &report.markdown(), 1)
            .into_bytes(),
    );
    files
}

/// The console's transport entry, as emitted into the SITE tree.
///
/// One generated forwarder, and it exists so that ONE import specifier
/// (`./pkg/mcp-transport.mjs`, in `console/engine.worker.mjs`) resolves in BOTH trees the
/// console ships as. On the site the real module is the shared `assets/mcp-transport.mjs`
/// the documentation controller also imports, so forwarding is what keeps the site at one
/// engine copy instead of two; in the published npm package there is no site around the
/// console, so the package's `prepack` stages the real module — and the whole engine
/// payload it imports — at this same path.
///
/// A re-export is not a second implementation: it resolves to the SAME module instance, so
/// the transport's configured asset base and its cached engine promise are shared, not
/// duplicated.
const TRANSPORT_FORWARDER: &str = "// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>\n\
     // SPDX-License-Identifier: AGPL-3.0-only\n\
     \n\
     // GENERATED by crates/docs/src/console.rs. Do not edit.\n\
     //\n\
     // The console's engine worker imports its transport as `./pkg/mcp-transport.mjs` so that\n\
     // one specifier resolves both in this site tree and in the published npm package, where\n\
     // the whole engine payload is staged under `pkg/`. Here the real module is the shared\n\
     // `assets/mcp-transport.mjs` the documentation controller imports too, so this forwards\n\
     // to it rather than duplicating a 29 kB module — and, transitively, the 7 MB engine\n\
     // image it pulls in.\n\
     //\n\
     // `export *` re-exports the SAME module instance: the transport's configured asset base\n\
     // and its cached boot promise are shared with every other importer, not re-created.\n\
     \n\
     export * from \"../../assets/mcp-transport.mjs\";\n";

/// A console-tree key expressed relative to `console/sw.mjs` (the worker's own URL).
///
/// `console/element.mjs` → `./element.mjs`; `assets/mcp-core/index.mjs` →
/// `../assets/mcp-core/index.mjs`. The worker resolves each against its own location, so
/// the console works at any site depth and from `file://`.
fn sw_relative(key: &str) -> String {
    match key.strip_prefix(CONSOLE_PREFIX) {
        Some(rest) => format!("./{rest}"),
        None => format!("../{key}"),
    }
}

/// The BLAKE3 content digest of an assembled tree, as the hex the cache name carries.
///
/// Keyed on BYTES, because the cache name's whole job is to make a rebuild un-reusable when
/// the bytes changed. Keying it on the shell's entry count and joined path length — which
/// is what it used to do — means any rebuild that keeps the same paths keeps the same cache
/// name and serves the OLD bytes to every returning reader, which is the exact failure a
/// versioned cache exists to prevent.
///
/// The encoding is length-prefixed per entry, so no pair of distinct trees can hash to the
/// same digest by moving bytes across a key boundary.
fn build_digest(files: &BTreeMap<String, Vec<u8>>) -> String {
    let mut hasher = blake3::Hasher::new();
    for (key, bytes) in files {
        hasher.update(&(key.len() as u64).to_le_bytes());
        hasher.update(key.as_bytes());
        hasher.update(&(bytes.len() as u64).to_le_bytes());
        hasher.update(bytes);
    }
    hasher.finalize().to_hex()[..16].to_string()
}

/// The service-worker source with its `SHELL` array and cache name substituted.
///
/// # Panics
///
/// If the authored `sw.mjs` no longer carries [`SHELL_MARKER`] or [`BUILD_MARKER`]. That is
/// a build-input break, not a runtime condition: shipping the unsubstituted source would
/// cache the literal string `__GMEOW_CONSOLE_SHELL__` and produce a console that appears to
/// work online and fails offline.
fn service_worker(shell: &[String], build: &str) -> String {
    assert!(
        SW_SOURCE.contains(SHELL_MARKER),
        "crates/docs/assets/console/sw.mjs no longer carries the {SHELL_MARKER} marker — the \
         generated SHELL cannot be substituted"
    );
    assert!(
        SW_SOURCE.contains(BUILD_MARKER),
        "crates/docs/assets/console/sw.mjs no longer carries the {BUILD_MARKER} marker — the \
         generated build digest cannot be substituted"
    );
    let rendered = shell
        .iter()
        .map(|path| format!("  {},", json_string(path)))
        .collect::<Vec<_>>()
        .join("\n");
    SW_SOURCE
        .replacen(SHELL_MARKER, &format!("[\n{rendered}\n]"), 1)
        .replacen(BUILD_MARKER, &json_string(build), 1)
}

/// A JSON string literal (the only escapes a site-relative path can need).
fn json_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

// ── the measured byte report ────────────────────────────────────────────────

/// The measured byte cost of an assembled console tree, partitioned by [`Fetch`].
///
/// MEASURED, never authored. The hand-written table this replaced was wrong on nearly
/// every row and omitted two assets the console fetches on every boot, because a table
/// typed into a document is a second source of truth for bytes that move on every build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ByteReport {
    /// `(key, bytes, tier)` for every emitted asset, in key order.
    pub rows: Vec<(String, u64, Fetch)>,
    /// The total the reader pays before any pane can run.
    pub first_load_total: u64,
    /// The total the demand-loaded reasoning segment costs, when a pane first needs it.
    pub demand_total: u64,
}

impl ByteReport {
    /// Measure an assembled tree.
    #[must_use]
    pub fn of(files: &BTreeMap<String, Vec<u8>>) -> Self {
        let rows: Vec<(String, u64, Fetch)> = files
            .iter()
            .map(|(key, bytes)| (key.clone(), bytes.len() as u64, fetch_tier(key)))
            .collect();
        let total = |tier: Fetch| {
            rows.iter()
                .filter(|(_, _, row)| *row == tier)
                .map(|(_, bytes, _)| *bytes)
                .sum()
        };
        Self {
            first_load_total: total(Fetch::First),
            demand_total: total(Fetch::Demand),
            rows,
        }
    }

    /// The report as the Markdown section the shipped README publishes.
    #[must_use]
    pub fn markdown(&self) -> String {
        let mut out = String::new();
        out.push_str(
            "*Generated by `crates/docs/src/console.rs` from the assembled tree — measured \
             uncompressed on-disk bytes, no transfer encoding assumed. Nothing in this \
             section is typed in.*\n",
        );
        self.section(
            &mut out,
            Fetch::First,
            "First load",
            "everything fetched before any pane runs",
            Some(("First-load total", self.first_load_total)),
        );
        self.section(
            &mut out,
            Fetch::Demand,
            "Demand-loaded reasoning segment",
            "fetched only when a pane first needs a reasoning-segment tool, and never at \
             all for a reader who only looks things up",
            Some(("Segment total", self.demand_total)),
        );
        self.section(
            &mut out,
            Fetch::Never,
            "Shipped, never fetched by the console",
            "shared with the documentation site, which reaches them from its own pages. \
             This document is the one emitted file the table omits: it is where the table \
             is published, so a row for its own size could never be the size it reports",
            None,
        );
        out.push_str(&format!(
            "\nThe first-load ceiling is **{}** bytes — the measurement above plus ten \
             percent of headroom. `console_files` asserts the assembled first-load total \
             against it on every render, so exceeding it is a build failure, not a heavier \
             download.\n",
            grouped(FIRST_LOAD_CEILING_BYTES)
        ));
        out
    }

    /// One tier's table.
    fn section(
        &self,
        out: &mut String,
        tier: Fetch,
        title: &str,
        gloss: &str,
        total: Option<(&str, u64)>,
    ) {
        out.push_str(&format!("\n**{title}** — {gloss}:\n\n| Asset | Bytes |\n|---|---:|\n"));
        for (key, bytes, row) in &self.rows {
            // The README carries this table, so its emitted size is strictly larger than
            // the size any row here could state. Omitting it is the only honest option: a
            // number that is wrong the instant it is written is worse than an absence that
            // is explained.
            if *row == tier && key != README_KEY {
                out.push_str(&format!("| `{key}` | {} |\n", grouped(*bytes)));
            }
        }
        if let Some((label, value)) = total {
            out.push_str(&format!("| **{label}** | **{}** |\n", grouped(value)));
        }
    }
}

/// A byte count with thousands separated by a space, matching the table's own style.
fn grouped(value: u64) -> String {
    let digits = value.to_string();
    let mut out = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index).is_multiple_of(3) {
            out.push(' ');
        }
        out.push(digit);
    }
    out
}

/// The generated `SHELL` set of an assembled console tree, read back out of its `sw.mjs`.
///
/// Exposed so the acceptance assertion can compare the GENERATED set against the FIRST-LOAD
/// tier in both directions, over the shipped bytes rather than over the producer's
/// intermediate state.
///
/// # Panics
///
/// If the tree carries no `console/sw.mjs`, or its `SHELL` array cannot be read.
#[must_use]
pub fn generated_shell(files: &BTreeMap<String, Vec<u8>>) -> Vec<String> {
    let text = sw_text(files);
    let open = text
        .find("const SHELL = [")
        .expect("sw.mjs declares const SHELL")
        + "const SHELL = [".len();
    let close = open + text[open..].find(']').expect("the SHELL array closes");
    text[open..close]
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| entry.trim_matches('"').to_string())
        .collect()
}

/// The generated cache name of an assembled console tree, read back out of its `sw.mjs`.
///
/// # Panics
///
/// If the tree carries no `console/sw.mjs`, or its `BUILD` constant cannot be read.
#[must_use]
pub fn generated_build_digest(files: &BTreeMap<String, Vec<u8>>) -> String {
    let text = sw_text(files);
    let open = text
        .find("const BUILD = \"")
        .expect("sw.mjs declares const BUILD")
        + "const BUILD = \"".len();
    let close = open + text[open..].find('"').expect("the BUILD literal closes");
    text[open..close].to_string()
}

/// The assembled tree's service worker, as text.
fn sw_text(files: &BTreeMap<String, Vec<u8>>) -> String {
    let sw = files
        .get(&format!("{CONSOLE_PREFIX}sw.mjs"))
        .expect("an assembled console tree carries console/sw.mjs");
    String::from_utf8(sw.clone()).expect("sw.mjs is UTF-8")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An `exec` that makes a render interactive (the renderer only checks non-emptiness).
    fn interactive_exec() -> ExecutableDocsData {
        ExecutableDocsData {
            full_bundle_gts: b"gts-bundle-sentinel-bytes".to_vec(),
            conjectures_ttl: b"@prefix ex: <http://example/> .".to_vec(),
            ..Default::default()
        }
    }

    /// Determinism: the same `exec` yields byte-identical maps.
    #[test]
    fn console_files_is_deterministic() {
        let exec = interactive_exec();
        assert_eq!(console_files(&exec), console_files(&exec));
    }

    /// The console never re-cuts a shared asset: every key both maps carry is byte-equal.
    #[test]
    fn shared_asset_bytes_are_identical() {
        let exec = interactive_exec();
        let console = console_files(&exec);
        let shared = interactive_asset_files(&exec);
        assert!(!shared.is_empty(), "the fixture must be interactive");
        for (key, bytes) in &shared {
            assert_eq!(
                console.get(key),
                Some(bytes),
                "shared asset {key} differs between the console and the site"
            );
        }
    }

    /// The generated `SHELL` set EQUALS the FIRST-LOAD tier, in both directions.
    #[test]
    fn generated_shell_equals_the_first_load_tier() {
        let files = console_files(&interactive_exec());
        let generated: std::collections::BTreeSet<String> =
            generated_shell(&files).into_iter().collect();
        let expected: std::collections::BTreeSet<String> = files
            .keys()
            .filter(|key| fetch_tier(key) == Fetch::First)
            .map(|key| sw_relative(key))
            .collect();
        assert_eq!(
            generated, expected,
            "the generated SHELL must equal the first-load tier"
        );
        assert!(
            generated.contains("./sw.mjs"),
            "the worker caches its own script: {generated:?}"
        );
        assert!(
            generated.iter().any(|path| path.starts_with("../assets/")),
            "the out-of-scope engine assets must be pre-cached: {generated:?}"
        );
    }

    /// A non-interactive render emits NO console key at all.
    #[test]
    fn non_interactive_render_emits_no_console() {
        assert!(console_files(&ExecutableDocsData::default()).is_empty());
    }

    /// The substituted worker and README carry no marker residue.
    #[test]
    fn every_marker_is_fully_substituted() {
        let files = console_files(&interactive_exec());
        let sw = String::from_utf8(files[&format!("{CONSOLE_PREFIX}sw.mjs")].clone()).unwrap();
        assert!(
            !sw.contains("__GMEOW_CONSOLE_SHELL__") && !sw.contains("__GMEOW_CONSOLE_BUILD__"),
            "unsubstituted worker marker survived"
        );
        let readme = String::from_utf8(files[README_KEY].clone()).unwrap();
        assert!(
            !readme.contains("__GMEOW_CONSOLE_BYTE_TABLE__"),
            "unsubstituted README marker survived"
        );
    }

    /// The cache name is a digest of the BYTES: same paths + different bytes ⇒ new cache.
    #[test]
    fn the_cache_name_changes_when_a_byte_changes() {
        let one = console_files(&interactive_exec());
        let mut other = interactive_exec();
        // Same length, one byte different — the substitution a length-based key accepts.
        other.full_bundle_gts = b"gts-bundle-sentinel-byteS".to_vec();
        let two = console_files(&other);
        assert_eq!(
            one.keys().collect::<Vec<_>>(),
            two.keys().collect::<Vec<_>>(),
            "the two trees must have identical paths for this to be the interesting case"
        );
        assert_ne!(
            generated_build_digest(&one),
            generated_build_digest(&two),
            "a byte-for-byte substitution must produce a different cache name"
        );
    }
}
