# Competency question: "What deception-related event types and veridicality values does GMEOW model?"
# Expected: eventTypeDeception, ClaimVeridicality, veridicalityUntrue, veridicalityLicensedFalsehood.

PREFIX gmeow: <https://blackcatinformatics.ca/gmeow/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?deceptionType WHERE {
    { ?deceptionType a gmeow:EventType . FILTER(?deceptionType = gmeow:eventTypeDeception) }
    UNION
    { ?deceptionType a gmeow:ClaimVeridicality }
    UNION
    { ?deceptionType rdfs:subClassOf gmeow:ClaimVeridicality }
}
ORDER BY ?deceptionType
