# SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: CC-BY-4.0
# Competency (medium axis): which medium obligations are CONDITIONAL, on what trigger value,
# and what do they then require? These are exactly the three places where an unconditional
# obligation would have made an explicitly-declared selection inexpressible — the
# dictionary-LESS baseline medium, and the reps assigned to it — so the guard is the whole
# difference between "no dictionary was selected" and "a dictionary went unrecorded".
PREFIX gmeow: <https://blackcatinformatics.ca/gmeow/>
PREFIX logic: <https://blackcatinformatics.ca/logic/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?guarded ?trigger ?triggerValue ?required WHERE {
    ?constraint a logic:GuardedImplicationConstraint ;
                rdfs:isDefinedBy <https://blackcatinformatics.ca/gmeow/slices/gts> ;
                logic:onClass ?guarded ;
                logic:trigger ?trigger ;
                logic:triggerValue ?triggerValue ;
                logic:requires ?required .
}
ORDER BY ?guarded ?required
