// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `agreement` benchmark surface: the committed external-corpus agreement matrix.
//!
//! This is the public "we agree with the published external corpora on N% of X"
//! benchmark. It is a PURE PROJECTION of the single external-corpus grade
//! `stage-conformance` already ran: that stage attaches the per-corpus tallies as an
//! in-memory carrier artifact ([`super::conformance::AGREEMENT_TALLIES_PATH`]), and
//! [`AgreementMatrixStage`] consumes them and renders the committed, drift-gated
//! Markdown dashboard (`generated/agreement-matrix.md`). No corpus is re-walked or
//! re-graded here (PIPELINE_SPINE §3.2/§8, the razor).
//!
//! The render is PURELY deterministic — the tallies are integer counts in sorted
//! `BTreeMap` order and the agree rate is integer permille math (no `f64`→string) —
//! so it survives the strict-sync byte gate.
//!
//! Honest presentation: a `divergence`-lane corpus's `corpus-only` rows are the
//! DOCUMENTED, intended native↔published divergences (native EL correctly differs from
//! the published DL/Full answer). They are NOT engine defects, so they are listed in a
//! separate section and excluded from the headline agreement rate — counting them as
//! failures would misrepresent the reasoner.

use std::collections::BTreeMap;

use crate::node::{Stage, StageInput, StageOutput, StageProduct};
use crate::stages::conformance::{AGREEMENT_TALLIES_PATH, TallyRecord};

/// Committed, drift-gated agreement-matrix dashboard artifact. Lives at the
/// `generated/` root (a committed surface, like `generated/module-status.md`) — NOT
/// under `generated/conformance/`, which is gitignored for the ephemeral
/// release-evidence conformance roll-up.
pub const AGREEMENT_MATRIX_PATH: &str = "generated/agreement-matrix.md";

/// The `divergence` lane token (a corpus whose native↔published disagreements are
/// documented and intended, not defects).
const DIVERGENCE_LANE: &str = "divergence";

fn stage_err(message: &str) -> gmeow_errors::Diag {
    gmeow_errors::Diag::of_kind(crate::error::StageFailed {
        stage: "stage-export-agreement".to_string(),
        message: message.to_string(),
    })
}

/// The agree rate `agree/cases` rendered as `"N.N%"`, rounded to the nearest tenth of
/// a percent with integer math (no `f64`). A zero-`cases` corpus is a corpus-integrity
/// failure, never a rendered `0.0%`.
///
/// Rounding is half-up but with a HONESTY GUARD: a corpus renders `100.0%` only when it
/// is exactly perfect (`agree == cases`). An imperfect corpus whose rate rounds up to
/// `1000` permille is clamped to `99.9%` — the benchmark must never round a real
/// disagreement or coverage gap away into a false "100%".
fn agree_rate(agree: usize, cases: usize) -> Result<String, gmeow_errors::Diag> {
    if cases == 0 {
        return Err(stage_err(
            "agreement tally has zero cases — corpus-integrity failure (no degraded 0% row)",
        ));
    }
    // permille = round_half_up(1000 * agree / cases) = floor((2000*agree + cases) / (2*cases)).
    let mut permille = (2000 * agree + cases) / (2 * cases);
    if agree < cases && permille >= 1000 {
        permille = 999;
    }
    Ok(format!("{}.{}%", permille / 10, permille % 10))
}

/// Render the committed agreement matrix from the per-corpus tally JSON attached by
/// `stage-conformance`. PURELY deterministic (integer counts, sorted `BTreeMap`
/// order, integer-permille rate). Hard-fails on unparsable tallies or a zero-case
/// corpus — no degraded fallback.
pub(crate) fn render_agreement_matrix(
    tallies_json: &[u8],
) -> Result<BTreeMap<String, Vec<u8>>, gmeow_errors::Diag> {
    let records: BTreeMap<String, TallyRecord> = serde_json::from_slice(tallies_json)
        .map_err(|e| stage_err(&format!("parse agreement tallies: {e}")))?;

    let mut lines: Vec<String> = vec![
        "<!-- GENERATED by `gmeow-dev sync --mode update --outputs generated` (agreement) — DO NOT EDIT. -->".to_string(),
        String::new(),
        "# gmeow external-corpus agreement matrix".to_string(),
        String::new(),
        "The native reasoner graded against published external ground truth — TPTP SZS".to_string(),
        "problems, W3C `otest:`/`mf:` entailment manifests, and OntoUML foundation".to_string(),
        "disciplines — over the committed `conformance/logic/cases/external/` corpus. Each"
            .to_string(),
        "case's native verdict (frozen at vendor time, the golden the conformance harness"
            .to_string(),
        "re-asserts) is compared to the corpus's published expected verdict.".to_string(),
        String::new(),
        "* **agree** — the native verdict matched the published expected.".to_string(),
        "* **corpus-only** — the native path DECIDED but disagreed with the published".to_string(),
        "  expected (a real defect for an agreement-expected corpus; DOCUMENTED and".to_string(),
        "  intended for a `divergence`-lane corpus, see below).".to_string(),
        "* **dl-gap** — the native path could not decide the case (an honest coverage gap)."
            .to_string(),
        String::new(),
    ];

    // Partition on lane: agreement-expected (a/b) vs documented-divergence corpora.
    let agree_expected: Vec<(&String, &TallyRecord)> = records
        .iter()
        .filter(|(_, r)| r.lane != DIVERGENCE_LANE)
        .collect();
    let divergence: Vec<(&String, &TallyRecord)> = records
        .iter()
        .filter(|(_, r)| r.lane == DIVERGENCE_LANE)
        .collect();

    // ── Agreement-expected corpora (the headline benchmark) ──────────────────────────
    lines.push("## Agreement (agreement-expected corpora)".to_string());
    lines.push(String::new());
    lines.push("| corpus | lane | cases | agree | corpus-only | dl-gap | agree rate |".to_string());
    lines.push("|---|---|---|---|---|---|---|".to_string());
    let (mut t_cases, mut t_agree, mut t_corpus_only, mut t_dl_gap) = (0usize, 0, 0, 0);
    for (corpus, r) in &agree_expected {
        let rate = agree_rate(r.agree, r.cases)?;
        lines.push(format!(
            "| {corpus} | {} | {} | {} | {} | {} | {rate} |",
            r.lane, r.cases, r.agree, r.corpus_only, r.dl_gap
        ));
        t_cases += r.cases;
        t_agree += r.agree;
        t_corpus_only += r.corpus_only;
        t_dl_gap += r.dl_gap;
    }
    if t_cases == 0 {
        return Err(stage_err(
            "no agreement-expected external corpus cases graded — corpus-integrity failure",
        ));
    }
    let total_rate = agree_rate(t_agree, t_cases)?;
    lines.push(format!(
        "| **TOTAL** | — | {t_cases} | {t_agree} | {t_corpus_only} | {t_dl_gap} | **{total_rate}** |"
    ));
    lines.push(String::new());

    // ── Documented divergences (NOT defects) ─────────────────────────────────────────
    lines.push(
        "## Documented divergences (native EL intentionally differs — not defects)".to_string(),
    );
    lines.push(String::new());
    lines.push(
        "These `divergence`-lane corpora are vendored to PROVE the native engine correctly"
            .to_string(),
    );
    lines.push(
        "declines (a dl-gap) or differs (a corpus-only row) from the published DL/Full answer;"
            .to_string(),
    );
    lines.push(
        "both are documented, intended, and excluded from the headline agreement rate above."
            .to_string(),
    );
    lines.push(String::new());
    if divergence.is_empty() {
        lines.push("_(none in the committed corpus)_".to_string());
    } else {
        lines.push("| corpus | cases | agree | corpus-only (documented) | dl-gap |".to_string());
        lines.push("|---|---|---|---|---|".to_string());
        for (corpus, r) in &divergence {
            lines.push(format!(
                "| {corpus} | {} | {} | {} | {} |",
                r.cases, r.agree, r.corpus_only, r.dl_gap
            ));
        }
    }
    lines.push(String::new());

    // ── Capability gaps by shape (the reified gmeow:gapShape breakdown) ──────────────
    // The shipped, drift-gated consumer of the structured capability-gap data: for every
    // divergence case the native reasoner honestly could not grade, its `gmeow:gapShape`
    // token (vendoring-multi-goal / role-assertion / existential-witness /
    // native-coverage / malformed) is tallied here across all corpora. A non-empty
    // section proves the gap-shape data flowed; the byte gate pins it.
    let mut gap_shape_totals: BTreeMap<String, usize> = BTreeMap::new();
    for r in records.values() {
        for (shape, n) in &r.gap_shapes {
            *gap_shape_totals.entry(shape.clone()).or_insert(0) += n;
        }
    }
    lines.push("## Capability gaps (by shape)".to_string());
    lines.push(String::new());
    lines.push(
        "The structured `gmeow:gapShape` of every divergence case the native reasoner honestly"
            .to_string(),
    );
    lines.push(
        "declined to grade (an out-of-fragment conclusion shape), tallied across corpora carrying"
            .to_string(),
    );
    lines.push("structured gap shapes.".to_string());
    lines.push(String::new());
    if gap_shape_totals.is_empty() {
        lines.push("_(none in the committed corpus)_".to_string());
    } else {
        lines.push("| gap shape | count |".to_string());
        lines.push("|---|---|".to_string());
        for (shape, n) in &gap_shape_totals {
            lines.push(format!("| {shape} | {n} |"));
        }
    }
    lines.push(String::new());

    lines.push(format!(
        "{} agreement-expected corpus(es), {} documented-divergence corpus(es).",
        agree_expected.len(),
        divergence.len()
    ));

    let md = lines.join("\n") + "\n";
    let mut out: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    out.insert(AGREEMENT_MATRIX_PATH.to_string(), md.into_bytes());
    Ok(out)
}

/// The `stage-export-agreement` export leaf: the committed agreement-matrix dashboard,
/// projected from the single grade `stage-conformance` attached.
pub struct AgreementMatrixStage {
    consumes: Vec<String>,
}

impl AgreementMatrixStage {
    /// Construct the stage. It consumes `stage-conformance` — the single grade whose
    /// attached tallies it projects — so it never re-walks the corpus.
    pub fn new() -> Self {
        Self {
            consumes: vec!["stage-conformance".to_string()],
        }
    }
}

impl Default for AgreementMatrixStage {
    fn default() -> Self {
        Self::new()
    }
}

impl Stage for AgreementMatrixStage {
    fn id(&self) -> &str {
        "stage-export-agreement"
    }
    fn consumes(&self) -> &[String] {
        &self.consumes
    }
    fn impl_version(&self) -> &str {
        "agreement.v1"
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let conformance = input.upstream.get("stage-conformance").ok_or_else(|| {
            stage_err("stage-export-agreement requires the stage-conformance product")
        })?;
        let tallies = conformance
            .artifact(AGREEMENT_TALLIES_PATH)
            .ok_or_else(|| {
                stage_err(&format!(
                    "stage-conformance product is missing {AGREEMENT_TALLIES_PATH}"
                ))
            })?;
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            render_agreement_matrix(tallies)?,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    /// Repo root (the workspace, two levels up from this crate's manifest).
    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    #[test]
    fn agreement_matrix_is_byte_identical_to_committed() {
        // The committed generated/agreement-matrix.md must be reproduced byte-for-byte
        // from the single external-corpus grade (the drift gate): grade → tally → render.
        let root = repo_root();
        let by_corpus =
            crate::stages::conformance::grade_external_corpora(&root).expect("grade corpus");
        let tallies = crate::stages::conformance::agreement_tallies_json(&root, &by_corpus)
            .expect("build tallies");
        let arts = render_agreement_matrix(&tallies).expect("render matrix");
        let built = arts.get(AGREEMENT_MATRIX_PATH).expect("matrix produced");
        let committed = std::fs::read(root.join(AGREEMENT_MATRIX_PATH))
            .expect("committed generated/agreement-matrix.md exists");
        assert_eq!(
            built,
            &committed,
            "generated/agreement-matrix.md drifted from committed (built {} vs committed {} bytes)",
            built.len(),
            committed.len()
        );
    }

    /// A tally JSON with two agreement-expected corpora and one documented-divergence
    /// corpus, exercising a perfect corpus, a partial corpus, and a divergence corpus.
    fn sample_tallies() -> Vec<u8> {
        // agree rates: tptp-mini 6/6 = 100.0%; w3c-owl2-el 18/19 (1 dl-gap) = 94.7%.
        // headline over both: 24/25 = 96.0%.
        let json = r#"{
          "tptp-mini":      { "lane": "a", "cases": 6,  "agree": 6,  "corpus_only": 0, "dl_gap": 0 },
          "w3c-owl2-el":    { "lane": "a", "cases": 19, "agree": 18, "corpus_only": 0, "dl_gap": 1 },
          "w3c-owl2-el-divergence": { "lane": "divergence", "cases": 2, "agree": 0, "corpus_only": 2, "dl_gap": 0 }
        }"#;
        json.as_bytes().to_vec()
    }

    fn matrix(tallies: &[u8]) -> String {
        let arts = render_agreement_matrix(tallies).expect("render");
        String::from_utf8(arts.get(AGREEMENT_MATRIX_PATH).expect("matrix").clone()).expect("utf-8")
    }

    #[test]
    fn renders_headline_rate_and_per_corpus_rows() {
        let md = matrix(&sample_tallies());
        // Per-corpus permille rates (integer math, no f64 drift).
        assert!(
            md.contains("| tptp-mini | a | 6 | 6 | 0 | 0 | 100.0% |"),
            "{md}"
        );
        assert!(
            md.contains("| w3c-owl2-el | a | 19 | 18 | 0 | 1 | 94.7% |"),
            "{md}"
        );
        // Headline TOTAL over the agreement-expected lanes only: 24/25 = 96.0%.
        assert!(
            md.contains("| **TOTAL** | — | 25 | 24 | 0 | 1 | **96.0%** |"),
            "{md}"
        );
    }

    #[test]
    fn divergence_corpus_is_segregated_not_counted_as_failure() {
        let md = matrix(&sample_tallies());
        // The divergence corpus is NOT in the headline (else TOTAL cases would be 27).
        assert!(
            !md.contains("27"),
            "divergence cases must not enter the headline: {md}"
        );
        // It appears under the documented-divergences section with its counts.
        let (head, tail) = md
            .split_once("## Documented divergences")
            .expect("divergence section present");
        assert!(
            !head.contains("w3c-owl2-el-divergence"),
            "divergence corpus must not appear in the agreement section"
        );
        // Divergence table carries its own agree column: cases | agree | corpus-only | dl-gap.
        assert!(
            tail.contains("| w3c-owl2-el-divergence | 2 | 0 | 2 | 0 |"),
            "divergence corpus row missing: {tail}"
        );
    }

    #[test]
    fn gap_shape_breakdown_renders_and_aggregates_across_corpora() {
        // Two divergence corpora carrying structured gap shapes; the breakdown section
        // aggregates them by shape, sorted, with integer counts.
        let json = r#"{
          "entailment-mini": { "lane": "a", "cases": 4, "agree": 4, "corpus_only": 0, "dl_gap": 0 },
          "entailment-mini-divergence": { "lane": "divergence", "cases": 2, "agree": 0, "corpus_only": 0, "dl_gap": 2,
            "gap_shapes": { "vendoring-multi-goal": 1, "role-assertion": 1 } },
          "other-divergence": { "lane": "divergence", "cases": 1, "agree": 0, "corpus_only": 0, "dl_gap": 1,
            "gap_shapes": { "role-assertion": 3 } }
        }"#;
        let md = matrix(json.as_bytes());
        assert!(md.contains("## Capability gaps (by shape)"), "{md}");
        // role-assertion aggregates across both divergence corpora: 1 + 3 = 4.
        assert!(md.contains("| role-assertion | 4 |"), "{md}");
        assert!(md.contains("| vendoring-multi-goal | 1 |"), "{md}");
    }

    #[test]
    fn no_gap_shapes_renders_none_in_the_breakdown() {
        let json = r#"{ "tptp-mini": { "lane": "a", "cases": 2, "agree": 2, "corpus_only": 0, "dl_gap": 0 } }"#;
        let md = matrix(json.as_bytes());
        let (_, tail) = md
            .split_once("## Capability gaps (by shape)")
            .expect("gap-shape section present");
        assert!(
            tail.contains("_(none in the committed corpus)_"),
            "empty gap-shape breakdown renders none: {tail}"
        );
    }

    #[test]
    fn no_divergence_corpora_renders_none() {
        let json = r#"{ "tptp-mini": { "lane": "a", "cases": 2, "agree": 2, "corpus_only": 0, "dl_gap": 0 } }"#;
        let md = matrix(json.as_bytes());
        assert!(md.contains("_(none in the committed corpus)_"), "{md}");
    }

    #[test]
    fn zero_case_corpus_hard_fails() {
        let json = r#"{ "broken": { "lane": "a", "cases": 0, "agree": 0, "corpus_only": 0, "dl_gap": 0 } }"#;
        let err = render_agreement_matrix(json.as_bytes()).unwrap_err();
        assert!(
            format!("{err:?}").contains("zero cases"),
            "expected a zero-cases hard-fail, got {err:?}"
        );
    }

    #[test]
    fn render_is_deterministic() {
        let t = sample_tallies();
        assert_eq!(
            render_agreement_matrix(&t).unwrap(),
            render_agreement_matrix(&t).unwrap()
        );
    }

    #[test]
    fn agree_rate_rounds_to_nearest_tenth() {
        // Round half up, not floor: 2/3 = 66.66..% → 66.7% (floor would say 66.6%);
        // 37/38 = 97.36..% → 97.4% (floor would say 97.3%).
        assert_eq!(agree_rate(2, 3).unwrap(), "66.7%");
        assert_eq!(agree_rate(37, 38).unwrap(), "97.4%");
        // Exact tenths and a perfect corpus are unchanged.
        assert_eq!(agree_rate(18, 19).unwrap(), "94.7%");
        assert_eq!(agree_rate(6, 6).unwrap(), "100.0%");
    }

    #[test]
    fn agree_rate_never_overclaims_100() {
        // An imperfect corpus that rounds up to 1000 permille is clamped to 99.9% — the
        // benchmark must never render a real gap/disagreement away into a false 100%.
        assert_eq!(agree_rate(9999, 10000).unwrap(), "99.9%");
        assert_eq!(agree_rate(1999, 2000).unwrap(), "99.9%");
        // Only an exactly-perfect corpus earns 100.0%.
        assert_eq!(agree_rate(10000, 10000).unwrap(), "100.0%");
    }
}
