// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `apache` export leaf (P4): the content-negotiation include
//! (`generated/apache/gmeow.conf`).
//!
//! A genuine port of `src/gmeow_tools/apache.py` (no Rust existed). The `/gmeow`
//! publication contract is a static template; its ONLY input is the Signposting
//! `cite-as` concept DOI, read from `metadata/gmeow-self.ttl` (Principle 4 — the
//! DOI is never hard-coded). Byte-deterministic.

use std::collections::BTreeMap;
use std::path::Path;

use purrdf::{DatasetView, GraphMatch, TermRef, TermValue, parse_dataset};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

/// Committed logical path of the Apache content-negotiation include.
pub const APACHE_PATH: &str = "generated/apache/gmeow.conf";

const BANNER: &str = "# GENERATED by gmeow apache — DO NOT EDIT.\n# https://github.com/Blackcat-Informatics/gmeow-ontology\n\n";
const DCTERMS_IDENTIFIER: &str = "http://purl.org/dc/terms/identifier";

/// The static `/gmeow` content-negotiation contract (the Python `_TEMPLATE`,
/// already in its rendered form). `__CONCEPT_DOI__` is the only substitution.
const TEMPLATE: &str = r###"# GMEOW content-negotiation include (generated by gmeow_tools.apache).
# Include this from the <VirtualHost> body of the site serving https://blackcatinformatics.ca/gmeow —
# it is the COMPLETE /gmeow publication contract; do not duplicate these
# rules in the vhost.

<IfModule mod_rewrite.c>
    RewriteEngine On

    # --- /gmeow — the negotiated ontology IRI ------------------------------
    # Accept-header routing per the W3C Best Practice Recipes for Publishing
    # RDF Vocabularies. Browsers (text/html) fall through to the /gmeow/
    # directory index — the human landing page.
    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} text/turtle [OR]
    RewriteCond %{HTTP_ACCEPT} application/x-turtle
    RewriteRule ^/?gmeow/?$ /gmeow.ttl [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/rdf\+xml
    RewriteRule ^/?gmeow/?$ /gmeow.rdf [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/n-triples
    RewriteRule ^/?gmeow/?$ /gmeow.nt [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/ld\+json
    RewriteRule ^/?gmeow/?$ /gmeow.jsonld [R=303,L]

    # --- Slice IRIs --------------------------------------------------
    # Every term's rdfs:isDefinedBy points at its owning slice. RDF requests
    # get the canonical serialization; HTML lands on the generated slice guide.
    RewriteCond %{HTTP_ACCEPT} text/turtle [OR]
    RewriteCond %{HTTP_ACCEPT} application/rdf\+xml [OR]
    RewriteCond %{HTTP_ACCEPT} application/ld\+json
    RewriteRule ^/?gmeow/slices/([a-z][a-z0-9-]*)$ /gmeow.ttl [R=303,L]
    RewriteRule ^/?gmeow/slices/([a-z][a-z0-9-]*)$ /gmeow/slices/$1/ [R=303,L]

    # --- Profile IRIs ------------------------------------------------
    # The root IRI is the core profile; <…/gmeow/full> and
    # <…/gmeow/profiles/<name>> are generated owl:imports aggregations. RDF
    # requests get the canonical serialization; HTML lands on generated docs.
    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} text/turtle [OR]
    RewriteCond %{HTTP_ACCEPT} application/x-turtle
    RewriteRule ^/?gmeow/full$ /gmeow/full.ttl [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/rdf\+xml
    RewriteRule ^/?gmeow/full$ /gmeow/full.rdf [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/n-triples
    RewriteRule ^/?gmeow/full$ /gmeow/full.nt [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/ld\+json
    RewriteRule ^/?gmeow/full$ /gmeow/full.jsonld [R=303,L]

    RewriteCond %{HTTP_ACCEPT} text/html
    RewriteRule ^/?gmeow/full$ /gmeow/profiles/full/ [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} text/turtle [OR]
    RewriteCond %{HTTP_ACCEPT} application/x-turtle
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.ttl [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/rdf\+xml
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.rdf [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/n-triples
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.nt [R=303,L]

    RewriteCond %{HTTP_ACCEPT} !text/html
    RewriteCond %{HTTP_ACCEPT} application/ld\+json
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1.jsonld [R=303,L]

    RewriteCond %{HTTP_ACCEPT} text/html
    RewriteRule ^/?gmeow/profiles/([a-z][a-z0-9-]*)$ /gmeow/profiles/$1/ [R=303,L]

    # --- Release version IRIs (owl:versionIRI) ------------------------------
    # .../gmeow/<semver> is the immutable per-release snapshot — the target of
    # each release's owl:versionIRI and (when minted) the version DOI's
    # <resource>. It must resolve to a distinct landing page from the concept
    # IRI (CrossRef forbids two DOIs on the same URL). The release directory
    # holds that snapshot (and its /gmeow/<semver>/gmeow.gts package).
    RewriteRule ^/?gmeow/([0-9]+\.[0-9]+\.[0-9]+)$ /gmeow/$1/ [R=303,L]

    # --- Legacy module IRIs -------------------------------------------------
    # Pre-slice releases published .../gmeow/modules/<name> in isDefinedBy
    # values; released data is immutable (Principle 6), so those IRIs keep
    # dereferencing forever via a permanent redirect to the slice IRI.
    RewriteRule ^/?gmeow/modules/([a-z][a-z0-9-]*)$ /gmeow/slices/$1 [R=301,L]

    # --- Per-term dereferencing ---------------------------------------------
    # A bare term IRI (slash namespace, no extension) resolves to its native
    # static docs page. The docs generator emits /gmeow/terms/<local>/ aliases
    # for every class, property, individual, and datatype.
    RewriteRule ^/?gmeow/([A-Za-z][A-Za-z0-9_]*)$ \
        /gmeow/terms/$1/ [R=303,L,NE]
</IfModule>

# --- RDF media types ---------------------------------------------------------
# .ttl/.rdf/.nt/.jsonld are not globally typed, so scope them to /gmeow.
<LocationMatch "^/gmeow(\.ttl|/.+\.ttl)$">
    Header always set Content-Type "text/turtle; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\.rdf|/.+\.rdf)$">
    Header always set Content-Type "application/rdf+xml; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\.nt|/.+\.nt)$">
    Header always set Content-Type "application/n-triples; charset=utf-8"
</LocationMatch>
<LocationMatch "^/gmeow(\.jsonld|/.+\.jsonld|/context\.jsonld)$">
    Header always set Content-Type "application/ld+json; charset=utf-8"
</LocationMatch>

# --- CORS ----------------------------------------------------------------------
# A public vocabulary is expected to be cross-origin readable.
<LocationMatch "^/gmeow($|[./])">
    Header always set Access-Control-Allow-Origin "*"
</LocationMatch>

# --- GTS package serving (§16) -------------------------------------------------
# .gts files are CBOR Sequence packages with byte-accurate content hashes.
<FilesMatch "\.gts$">
    Header always set Content-Type "application/vnd.blackcat.gts+cbor"
    Header always set Accept-Ranges "bytes"
    Header always set Access-Control-Allow-Origin "*"
</FilesMatch>

# Versioned releases (e.g. /gmeow/1.2.3/gmeow.gts or
# /packages/music/2026-06-11/music.gts) are immutable for one year.
# The ETag SHOULD be the hex of the file's last segment head id (§16.3);
# if the deployment cannot compute it, Apache's default file ETag is acceptable
# because the URL itself names one exact byte sequence.
<LocationMatch "^/(?:gmeow|packages)(?:/.*)?/(?:[0-9]+(?:\.[0-9]+)*/|(?:[0-9]{4}-[0-9]{2}-[0-9]{2})/)[^/]+\.gts$">
    Header always set Cache-Control "public, max-age=31536000, immutable"
</LocationMatch>

# latest / conneg aliases may change; do not let a shared cache pin one variant.
<LocationMatch "^/(?:gmeow|packages)(?:/.*)?/latest/[^/]+\.gts$">
    Header always set Cache-Control "private, no-store"
    Header always set Vary "Accept"
</LocationMatch>

# --- Conneg cache semantics ------------------------------------------------------
# Every endpoint whose 303-target depends on the Accept header must Vary and
# must not be cached as a single variant, or a shared cache (Cloudflare) pins
# one serialization for every client. That is the bare /gmeow, the slice
# IRIs, and the profile IRIs — all negotiate. The
# serializations themselves, the per-term redirects, and the legacy 301s
# (one URL -> one target) stay cacheable.
<LocationMatch "^/gmeow(/?$|/(slices|profiles)/[a-z][a-z0-9-]*$|/full$)">
    Header always set Vary "Accept"
    Header always set Cache-Control "private, no-store"
</LocationMatch>

# --- FAIR Signposting (signposting.org/FAIR) -----------------------------------
# Typed links bridging the landing page to the three identifier legs:
#   cite-as     -> the DOI (citation identity)
#   describedby -> the RDF serializations (semantic identity)
#   item        -> every serialization, including the content-addressed GTS
#                  package whose head id is the intrinsic identity.
# Sourced from metadata/gmeow-self.ttl (Principle 4 — one source, generated here).
<LocationMatch "^/gmeow/?$">
    Header always set Link "<https://doi.org/__CONCEPT_DOI__>; rel=\"cite-as\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.ttl>; rel=\"describedby\"; type=\"text/turtle\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.rdf>; rel=\"describedby\"; type=\"application/rdf+xml\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.nt>; rel=\"describedby\"; type=\"application/n-triples\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.jsonld>; rel=\"describedby\"; type=\"application/ld+json\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.ttl>; rel=\"item\"; type=\"text/turtle\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.rdf>; rel=\"item\"; type=\"application/rdf+xml\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.nt>; rel=\"item\"; type=\"application/n-triples\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.jsonld>; rel=\"item\"; type=\"application/ld+json\""
    Header always add Link "<https://blackcatinformatics.ca/gmeow.gts>; rel=\"item\"; type=\"application/vnd.blackcat.gts+cbor\""
</LocationMatch>
"###;

/// Read the concept DOI (the `dcterms:identifier` literal matching `10.…/…`) from
/// `metadata/gmeow-self.ttl`.
fn concept_doi(root: &Path) -> Result<String, gmeow_errors::Diag> {
    let path = root.join("metadata").join("gmeow-self.ttl");
    let bytes = std::fs::read(&path)?;
    let ds = parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("syntax error in self-desc: {e}"),
        })
    })?;
    if let Some(pred) = ds.term_id_by_value(&TermValue::iri(DCTERMS_IDENTIFIER)) {
        for q in ds.quads_for_pattern(None, Some(pred), None, GraphMatch::Default) {
            if let TermRef::Literal { lexical, .. } = ds.resolve(q.o)
                && lexical.starts_with("10.")
                && lexical.contains('/')
            {
                return Ok(lexical.to_owned());
            }
        }
    }
    Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
        message: "no concept DOI (dcterms:identifier 10.…/…) in metadata/gmeow-self.ttl"
            .to_string(),
    }))
}

/// Render the Apache content-negotiation include.
pub fn render_apache(root: &Path) -> Result<String, gmeow_errors::Diag> {
    let doi = concept_doi(root)?;
    Ok(format!(
        "{BANNER}{}",
        TEMPLATE.replace("__CONCEPT_DOI__", &doi)
    ))
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `apache` export-leaf stage.
pub struct ApacheStage;

impl Stage for ApacheStage {
    fn id(&self) -> &str {
        "stage-export-apache"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "apache.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // Pure source read: the concept DOI comes from `metadata/gmeow-self.ttl`
        // (not the fold), so declare it as a cache input — a DOI change busts the
        // cache. The leaf consumes no upstream product (`consumes() == []`).
        Ok(vec![root.join("metadata").join("gmeow-self.ttl")])
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let conf = render_apache(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(APACHE_PATH.to_string(), conf.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}
