// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `catalog` export leaf (P4): the OASIS XML catalog (`catalog-v001.xml`).
//!
//! A genuine port of `src/gmeow_tools/catalog_gen.py` (no Rust existed): the
//! IRI→file map is 100% derived from the slice manifests + a static upper-ontology
//! spine. Output is byte-deterministic, so this is compared byte-for-byte to the
//! committed `catalog-v001.xml`.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use purrdf::{DatasetView, GraphMatch, TermRef, TermValue, parse_dataset};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};
use crate::stages::source_load::module_files;

/// Committed logical path of the OASIS catalog.
pub const CATALOG_PATH: &str = "catalog-v001.xml";

const GMEOW: &str = "https://blackcatinformatics.ca/gmeow";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const SLICE_CLASS: &str = "https://blackcatinformatics.ca/gmeow/Slice";
const SLICE_PROFILE: &str = "https://blackcatinformatics.ca/gmeow/sliceProfile";

/// Render `catalog-v001.xml` from the slice manifests under `root`.
pub fn render_catalog(root: &Path) -> Result<String, gmeow_errors::Diag> {
    // (slice_iri, module-rel-path) sorted by IRI; distinct profile names sorted.
    let mut slices: BTreeMap<String, String> = BTreeMap::new();
    let mut profiles: BTreeSet<String> = BTreeSet::new();

    for module in module_files(root)? {
        let manifest = module.with_file_name("manifest.ttl");
        if !manifest.is_file() {
            continue;
        }
        let (iri, profs) = parse_manifest(&manifest)?;
        let rel = module
            .strip_prefix(root)
            .unwrap_or(&module)
            .to_string_lossy()
            .replace('\\', "/");
        slices.insert(iri, rel);
        profiles.extend(profs);
    }

    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
    out.push_str("<!-- GENERATED by gmeow catalog — DO NOT EDIT.\n");
    out.push_str("     OASIS XML catalog: maps ontology IRIs to local files so the\n");
    out.push_str("     import closure (gUFO spine + GMEOW slices) resolves offline for\n");
    out.push_str("     ROBOT, Protégé, and the reasoning pipeline. Paths are relative\n");
    out.push_str("     to this file (the repository root). Derived from the slice\n");
    out.push_str("     manifests by the gmeow catalog generator. -->\n");
    out.push_str(
        "<catalog prefer=\"public\" xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\">\n",
    );
    out.push_str("    <!-- Upper-ontology spine (static allowlist) -->\n");
    out.push_str("    <uri name=\"http://purl.org/nemo/gufo#\" uri=\"imports/gufo.ttl\"/>\n");
    out.push_str(&format!(
        "    <uri name=\"{GMEOW}\" uri=\"ontology/gmeow.ttl\"/>\n"
    ));
    out.push_str(&format!(
        "    <uri name=\"{GMEOW}/full\" uri=\"generated/profiles/full.ttl\"/>\n"
    ));
    out.push('\n');
    out.push_str("    <!-- GMEOW slices (discovered from manifests) -->\n");
    for (iri, rel) in &slices {
        out.push_str(&format!("    <uri name=\"{iri}\" uri=\"{rel}\"/>\n"));
    }
    if !profiles.is_empty() {
        out.push('\n');
        out.push_str("    <!-- Named profiles (generated) -->\n");
        for name in &profiles {
            out.push_str(&format!(
                "    <uri name=\"{GMEOW}/profiles/{name}\" uri=\"generated/profiles/{name}.ttl\"/>\n"
            ));
        }
    }
    out.push_str("</catalog>\n");
    Ok(out)
}

/// Parse one manifest for `(slice_iri, sliceProfile names)`.
fn parse_manifest(path: &Path) -> Result<(String, Vec<String>), gmeow_errors::Diag> {
    let bytes = std::fs::read(path)?;
    let ds = parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("syntax error in {}: {e}", path.display()),
        })
    })?;
    let mut iri: Option<String> = None;
    if let (Some(p), Some(o)) = (
        ds.term_id_by_value(&TermValue::iri(RDF_TYPE)),
        ds.term_id_by_value(&TermValue::iri(SLICE_CLASS)),
    ) {
        for q in ds.quads_for_pattern(None, Some(p), Some(o), GraphMatch::Default) {
            if let TermRef::Iri(nn) = ds.resolve(q.s) {
                iri = Some(nn.to_owned());
            }
        }
    }
    let iri = iri.ok_or_else(|| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("no `a gmeow:Slice` in {}", path.display()),
        })
    })?;
    let mut profiles = Vec::new();
    if let (Some(s), Some(p)) = (
        ds.term_id_by_value(&TermValue::iri(&iri)),
        ds.term_id_by_value(&TermValue::iri(SLICE_PROFILE)),
    ) {
        for q in ds.quads_for_pattern(Some(s), Some(p), None, GraphMatch::Default) {
            if let TermRef::Literal { lexical, .. } = ds.resolve(q.o) {
                profiles.push(lexical.to_owned());
            }
        }
    }
    Ok((iri, profiles))
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `catalog` export-leaf stage.
pub struct CatalogStage;

impl Stage for CatalogStage {
    fn id(&self) -> &str {
        "stage-export-catalog"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "catalog.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // Pure source read: the IRI→file map is derived from the slice manifests
        // (`gmeow:sliceProfile` lives in `manifest.ttl`, which is NOT folded into
        // the snapshot — only `module.ttl` is). Declare the manifests so a slice
        // add/rename/profile-change busts the cache. `consumes() == []`.
        crate::stages::source_load::manifest_files(root)
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let xml = render_catalog(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(CATALOG_PATH.to_string(), xml.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}
