// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `catalog` export leaf (#861 P4): the OASIS XML catalog (`catalog-v001.xml`).
//!
//! A genuine port of `src/gmeow_tools/catalog_gen.py` (no Rust existed): the
//! IRI→file map is 100% derived from the slice manifests + a static upper-ontology
//! spine. Output is byte-deterministic, so this is compared byte-for-byte to the
//! committed `catalog-v001.xml`.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::model::Term;
use oxigraph::store::Store;

use crate::error::PipelineError;
use crate::node::{Stage, StageInput, StageKind, StageOutput, StageProduct};
use crate::stages::source_load::module_files;

/// Committed logical path of the OASIS catalog.
pub const CATALOG_PATH: &str = "catalog-v001.xml";

const GMEOW: &str = "https://blackcatinformatics.ca/gmeow";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const SLICE_CLASS: &str = "https://blackcatinformatics.ca/gmeow/Slice";
const SLICE_PROFILE: &str = "https://blackcatinformatics.ca/gmeow/sliceProfile";

/// Render `catalog-v001.xml` from the slice manifests under `root`.
pub fn render_catalog(root: &Path) -> Result<String, PipelineError> {
    // (slice_iri, module-rel-path) sorted by IRI; distinct profile names sorted.
    let mut slices: BTreeMap<String, String> = BTreeMap::new();
    let mut profiles: BTreeSet<String> = BTreeSet::new();

    for module in module_files(root)? {
        let manifest = module.with_file_name("manifest.ttl");
        if !manifest.is_file() {
            continue;
        }
        let (iri, profs) = parse_manifest(&manifest)?;
        let rel = module
            .strip_prefix(root)
            .unwrap_or(&module)
            .to_string_lossy()
            .replace('\\', "/");
        slices.insert(iri, rel);
        profiles.extend(profs);
    }

    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
    out.push_str("<!-- GENERATED by gmeow catalog — DO NOT EDIT.\n");
    out.push_str("     OASIS XML catalog: maps ontology IRIs to local files so the\n");
    out.push_str("     import closure (gUFO spine + GMEOW slices) resolves offline for\n");
    out.push_str("     ROBOT, Protégé, and the reasoning pipeline. Paths are relative\n");
    out.push_str("     to this file (the repository root). Derived from the slice\n");
    out.push_str("     manifests by src/gmeow_tools/catalog_gen.py (#331). -->\n");
    out.push_str(
        "<catalog prefer=\"public\" xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\">\n",
    );
    out.push_str("    <!-- Upper-ontology spine (static allowlist) -->\n");
    out.push_str("    <uri name=\"http://purl.org/nemo/gufo#\" uri=\"imports/gufo.ttl\"/>\n");
    out.push_str(&format!(
        "    <uri name=\"{GMEOW}\" uri=\"ontology/gmeow.ttl\"/>\n"
    ));
    out.push_str(&format!(
        "    <uri name=\"{GMEOW}/full\" uri=\"generated/profiles/full.ttl\"/>\n"
    ));
    out.push('\n');
    out.push_str("    <!-- GMEOW slices (discovered from manifests) -->\n");
    for (iri, rel) in &slices {
        out.push_str(&format!("    <uri name=\"{iri}\" uri=\"{rel}\"/>\n"));
    }
    if !profiles.is_empty() {
        out.push('\n');
        out.push_str("    <!-- Named profiles (generated, #330) -->\n");
        for name in &profiles {
            out.push_str(&format!(
                "    <uri name=\"{GMEOW}/profiles/{name}\" uri=\"generated/profiles/{name}.ttl\"/>\n"
            ));
        }
    }
    out.push_str("</catalog>\n");
    Ok(out)
}

/// Parse one manifest for `(slice_iri, sliceProfile names)`.
fn parse_manifest(path: &Path) -> Result<(String, Vec<String>), PipelineError> {
    let bytes = std::fs::read(path)?;
    let store =
        Store::new().map_err(|e| PipelineError::Parse(format!("store creation failed: {e}")))?;
    for quad in RdfParser::from_format(RdfFormat::Turtle)
        .lenient()
        .for_reader(bytes.as_slice())
    {
        let quad = quad.map_err(|e| {
            PipelineError::Parse(format!("syntax error in {}: {e}", path.display()))
        })?;
        store
            .insert(&quad)
            .map_err(|e| PipelineError::Parse(format!("store insert failed: {e}")))?;
    }
    let rdf_type = oxigraph::model::NamedNode::new(RDF_TYPE).unwrap();
    let slice_class = oxigraph::model::NamedNode::new(SLICE_CLASS).unwrap();
    let mut iri: Option<String> = None;
    for quad in store.quads_for_pattern(
        None,
        Some(rdf_type.as_ref()),
        Some((&slice_class).into()),
        None,
    ) {
        let quad = quad.map_err(|e| PipelineError::Parse(e.to_string()))?;
        if let oxigraph::model::NamedOrBlankNode::NamedNode(nn) = &quad.subject {
            iri = Some(nn.as_str().to_string());
        }
    }
    let iri = iri
        .ok_or_else(|| PipelineError::Parse(format!("no `a gmeow:Slice` in {}", path.display())))?;
    let prof_pred = oxigraph::model::NamedNode::new(SLICE_PROFILE).unwrap();
    let subject = oxigraph::model::NamedNode::new(&iri).unwrap();
    let mut profiles = Vec::new();
    for quad in store.quads_for_pattern(
        Some((&subject).into()),
        Some(prof_pred.as_ref()),
        None,
        None,
    ) {
        let quad = quad.map_err(|e| PipelineError::Parse(e.to_string()))?;
        if let Term::Literal(l) = &quad.object {
            profiles.push(l.value().to_string());
        }
    }
    Ok((iri, profiles))
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `catalog` export-leaf stage.
pub struct CatalogStage;

impl Stage for CatalogStage {
    fn id(&self) -> &str {
        "stage-export-catalog"
    }
    fn kind(&self) -> StageKind {
        StageKind::ExportLeaf
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "catalog.v1"
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, PipelineError> {
        let xml = render_catalog(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(CATALOG_PATH.to_string(), xml.into_bytes());
        Ok(StageOutput {
            product: StageProduct::from_artifacts(self.id(), artifacts),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    #[test]
    fn catalog_is_byte_identical_to_committed() {
        let root = repo_root();
        let fresh = render_catalog(&root).expect("render");
        let committed =
            std::fs::read_to_string(root.join(CATALOG_PATH)).expect("committed catalog");
        assert_eq!(fresh, committed, "catalog-v001.xml drifted from committed");
    }
}
