// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `constraint-shapes` export leaf (P4/P17): the SHACL projection of the `logic:`
//! open-world FOL axioms that were previously hand-authored as `sh:sparql` constraints.
//!
//! Four families, one canonical `logic:` source each, projected to `sh:SPARQLConstraint`
//! node shapes (the validation peer of the `sh:SPARQLRule` computation surface in
//! `shacl_af`; `design/LOGIC-VALIDATION.md`):
//!
//! * **irreflexivity** — a `logic:PropertyCharacteristicAssertion` with
//!   `logic:characteristicSort logic:irreflexiveProperty` (gmeow:counterGoal,
//!   gmeow:overrides): `$this P $this`.
//! * **acyclicity** — `logic:characteristicSort logic:acyclicProperty` (gmeow:linkNext):
//!   `$this P+ $this`.
//! * **relatum-distinctness** — a `logic:RelatumDistinctnessAssertion` naming a target
//!   class and two roles: `$this r1 ?v . $this r2 ?v` (a coincident-value equality join).
//! * **class-disjointness** — a NAMED `owl:AllDisjointClasses` carrying `logic:formalizes`
//!   (gmeow:identityAxisDisjointness, gmeow:softwareFacetDisjointness): an ordered pair of
//!   member classes on one focus node (subclass-closure form).
//!
//! Each shape carries a `logic:formalizes` back-reference to its canonical `logic:` source,
//! so it is self-evidently a projection (the shape-half projection-purity gate keys on it).
//! Byte-deterministic → compared byte-for-byte to the committed
//! `generated/shapes/constraint-shapes.ttl`. Emit-only; the canon is the authoring ground.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use purrdf::slice::rdf_query::{Dataset, DatasetAccumulator, Object, Subject};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

/// Committed logical path of the generated constraint shapes.
pub const CONSTRAINT_SHAPES_PATH: &str = "generated/shapes/constraint-shapes.ttl";

const NS: &str = "https://blackcatinformatics.ca/gmeow/";
use gmeow_ns::LOGIC_NS;
const RDFS_DOMAIN: &str = "http://www.w3.org/2000/01/rdf-schema#domain";
const RDF_FIRST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#first";
const RDF_REST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest";
// The class-disjointness set is authored in the canonical `logic:` spelling
// (`logic:AllDisjointClasses` / `logic:members`); `owl:` is its generated projection, so it is
// read canonical-first with the `owl:` spelling kept only as a fallback for an external corpus.
const LOGIC_ALL_DISJOINT: &str = "https://blackcatinformatics.ca/logic/AllDisjointClasses";
const LOGIC_MEMBERS: &str = "https://blackcatinformatics.ca/logic/members";
const OWL_ALL_DISJOINT: &str = "http://www.w3.org/2002/07/owl#AllDisjointClasses";
const OWL_MEMBERS: &str = "http://www.w3.org/2002/07/owl#members";
const CHAR_ASSERTION: &str = "https://blackcatinformatics.ca/logic/PropertyCharacteristicAssertion";
const DISTINCTNESS_ASSERTION: &str =
    "https://blackcatinformatics.ca/logic/RelatumDistinctnessAssertion";
const CONDITIONAL_RANGE_ASSERTION: &str =
    "https://blackcatinformatics.ca/logic/ConditionalRangeAssertion";
const ROLE_COMPOSITION_EXCLUSION_ASSERTION: &str =
    "https://blackcatinformatics.ca/logic/RoleCompositionExclusionAssertion";
const MEDIATED_REQUIREMENT_ASSERTION: &str =
    "https://blackcatinformatics.ca/logic/MediatedPropertyRequirementAssertion";

const HEADER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (constraint-shapes) from the logic: FOL axioms\n# (irreflexivity / acyclicity / relatum-distinctness / class-disjointness / conditional-range /\n# role-composition-exclusion / mediated-property-requirement) — DO NOT EDIT\n# (P4/P17: logic: is canonical, SHACL is the projection; the Rust authority is\n# gmeow-pipeline::stages::constraint_shapes). Each shape carries logic:formalizes naming\n# its canonical logic: source (design/LOGIC-VALIDATION.md).\n@prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .\n@prefix logic: <https://blackcatinformatics.ca/logic/> .\n@prefix sh:    <http://www.w3.org/ns/shacl#> .\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n";

/// Load the root ontology + every slice module into one frozen dataset (NO imports),
/// mirroring the frame/result-shape leaves so the axioms, their domains, and the named
/// disjointness sets are all visible.
fn load_authored(root: &Path) -> Result<Dataset, gmeow_errors::Diag> {
    let mut acc = DatasetAccumulator::new();
    let mut files = vec![root.join("ontology").join("gmeow.ttl")];
    files.extend(crate::stages::source_load::module_files(root)?);
    for path in files {
        if !path.is_file() {
            continue;
        }
        let bytes = std::fs::read(&path)?;
        acc.add_turtle(&bytes, None, &path.display().to_string())
            .map_err(|e| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: e.to_string(),
                })
            })?;
    }
    acc.freeze().map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: e.to_string(),
        })
    })
}

/// The local name of a `gmeow:`/`logic:` IRI (the part after the last `/`).
fn local(iri: &str) -> &str {
    iri.rsplit('/').next().unwrap_or(iri)
}

/// The local name with its first character upper-cased (`counterGoal` → `CounterGoal`).
fn pascal(iri: &str) -> String {
    let l = local(iri);
    let mut c = l.chars();
    match c.next() {
        Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

/// The `rdf:first` / `rdf:rest` edges of every blank list node, keyed by the blank's
/// scope-qualified label — the form `for_each_quad` yields (and that `objects()` returns
/// for the list head). A blank `Object` label does NOT round-trip through
/// `objects_of_subject`, so the list is walked through these maps instead.
struct ListEdges {
    first: BTreeMap<String, String>,
    rest: BTreeMap<String, Object>,
}

impl ListEdges {
    fn collect(ds: &Dataset) -> Self {
        let mut first = BTreeMap::new();
        let mut rest = BTreeMap::new();
        ds.for_each_quad(|s, p, o, _g| {
            let Subject::Blank(label) = s else { return };
            if p == RDF_FIRST {
                if let Object::Named(m) = o {
                    first.insert(label, m);
                }
            } else if p == RDF_REST {
                rest.insert(label, o);
            }
        });
        Self { first, rest }
    }

    /// Walk an `owl:members` list from its head object, returning member IRIs in order.
    /// A non-blank node (rdf:nil or a stray term) ends the walk.
    fn members(&self, head: &Object) -> Vec<String> {
        let mut out = Vec::new();
        let mut seen: BTreeSet<String> = BTreeSet::new();
        let mut node = head.clone();
        while let Object::Blank(label) = &node {
            let label = label.clone();
            // Guard against a malformed/cyclic list whose rdf:rest loops back to an
            // already-visited node: stop the walk instead of spinning forever.
            if !seen.insert(label.clone()) {
                break;
            }
            if let Some(m) = self.first.get(&label) {
                out.push(m.clone());
            }
            match self.rest.get(&label) {
                Some(next) => node = next.clone(),
                None => break,
            }
        }
        out
    }
}

/// One generated shape: its IRI (the sort key) and its rendered block.
struct ShapeBlock {
    iri: String,
    block: String,
}

/// A `FILTER(?var IN (<m1>, <m2>, …))` clause from the member IRIs, in list order.
fn filter_in(var: &str, members: &[String]) -> String {
    let list = members
        .iter()
        .map(|m| format!("<{m}>"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("FILTER(?{var} IN ({list}))")
}

/// Render the constraint-shapes document.
pub fn render_constraint_shapes(root: &Path) -> Result<String, gmeow_errors::Diag> {
    let ds = load_authored(root)?;
    let q = |e: purrdf::slice::SliceError| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: e.to_string(),
        })
    };
    let mut shapes: Vec<ShapeBlock> = Vec::new();

    // ── Irreflexivity + acyclicity (property-characteristic assertions) ──────────
    for rec in ds.subjects_of_type(CHAR_ASSERTION).map_err(q)? {
        let Some(sort) = ds
            .first_object_iri(&rec, &format!("{LOGIC_NS}characteristicSort"))
            .map_err(q)?
        else {
            continue;
        };
        let kind = match local(&sort) {
            "irreflexiveProperty" => "Irreflexivity",
            "acyclicProperty" => "Acyclicity",
            _ => continue, // transitive/symmetric/functional carry no constraint shape
        };
        let prop = ds
            .first_object_iri(&rec, &format!("{LOGIC_NS}characterizes"))
            .map_err(q)?
            .ok_or_else(|| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: format!("characteristic assertion {rec} lacks characterizes"),
                })
            })?;
        let domain = ds
            .first_object_iri(&prop, RDFS_DOMAIN)
            .map_err(q)?
            .ok_or_else(|| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: format!(
                        "constraint-shapes: {prop} has no rdfs:domain for its {kind} target class"
                    ),
                })
            })?;
        let prop_local = local(&prop);
        let iri = format!("{NS}{}{kind}ConstraintShape", pascal(&prop));
        let (path, phrase) = if kind == "Acyclicity" {
            (
                format!("<{prop}>+"),
                format!("reach itself through gmeow:{prop_local} (acyclic)"),
            )
        } else {
            (
                format!("<{prop}>"),
                format!("be its own gmeow:{prop_local} (irreflexive)"),
            )
        };
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{rec}> ;\n    sh:targetClass <{domain}> ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"A <{domain}> instance must never {phrase}.\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this {path} $this . }}\"\"\" ;\n    ] .\n",
        );
        shapes.push(ShapeBlock { iri, block });
    }

    // ── Relatum-distinctness assertions ──────────────────────────────────────────
    for rec in ds.subjects_of_type(DISTINCTNESS_ASSERTION).map_err(q)? {
        let target = ds
            .first_object_iri(&rec, &format!("{LOGIC_NS}distinctnessTarget"))
            .map_err(q)?
            .ok_or_else(|| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: format!("distinctness assertion {rec} lacks distinctnessTarget"),
                })
            })?;
        let mut roles = ds
            .object_iris(&rec, &format!("{LOGIC_NS}distinctnessRole"))
            .map_err(q)?;
        roles.sort();
        if roles.len() != 2 {
            return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: format!(
                    "constraint-shapes: distinctness assertion {rec} must name exactly two roles, found {}",
                    roles.len()
                ),
            }));
        }
        let (r1, r2) = (&roles[0], &roles[1]);
        let iri = format!("{NS}{}ConstraintShape", pascal(&rec));
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{rec}> ;\n    sh:targetClass <{target}> ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"A <{target}> instance's gmeow:{r1l} and gmeow:{r2l} must be distinct.\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this <{r1}> ?v . $this <{r2}> ?v . }}\"\"\" ;\n    ] .\n",
            r1l = local(r1),
            r2l = local(r2),
        );
        shapes.push(ShapeBlock { iri, block });
    }

    // ── Class-disjointness (named logic:AllDisjointClasses carrying logic:formalizes) ──
    let list_edges = ListEdges::collect(&ds);
    let mut seen_disjoint: BTreeSet<String> = BTreeSet::new();
    let mut disjoint_subjects = Vec::new();
    for ty in [LOGIC_ALL_DISJOINT, OWL_ALL_DISJOINT] {
        for subj in ds.subjects_of_type(ty).map_err(q)? {
            if seen_disjoint.insert(subj.to_string()) {
                disjoint_subjects.push(subj);
            }
        }
    }
    for disjoint in disjoint_subjects {
        // Only the NAMED, projection-anchored sets (blank ones are DL-gate only).
        if ds
            .first_object_iri(&disjoint, &format!("{LOGIC_NS}formalizes"))
            .map_err(q)?
            .is_none()
        {
            continue;
        }
        let head = match ds
            .objects(&disjoint, LOGIC_MEMBERS)
            .map_err(q)?
            .into_iter()
            .next()
        {
            Some(h) => Some(h),
            None => ds
                .objects(&disjoint, OWL_MEMBERS)
                .map_err(q)?
                .into_iter()
                .next(),
        };
        let Some(head) = head else {
            continue;
        };
        let members = list_edges.members(&head);
        if members.len() < 2 {
            return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: format!(
                    "constraint-shapes: disjointness {disjoint} has fewer than two members"
                ),
            }));
        }
        let iri = format!("{NS}{}ConstraintShape", pascal(&disjoint));
        let target_filter = filter_in("m", &members);
        let a_filter = filter_in("a", &members);
        let b_filter = filter_in("b", &members);
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{disjoint}> ;\n    sh:target [\n        a sh:SPARQLTarget ;\n        sh:select \"\"\"SELECT ?this WHERE {{ ?this a/rdfs:subClassOf* ?m . {target_filter} }}\"\"\" ;\n    ] ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"An individual may fill at most one of these mutually disjoint classes (no overtyping).\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this a/rdfs:subClassOf* ?a ; a/rdfs:subClassOf* ?b . FILTER(STR(?a) < STR(?b)) {a_filter} {b_filter} }}\"\"\" ;\n    ] .\n",
        );
        shapes.push(ShapeBlock { iri, block });
    }

    // ── Conditional-range assertions (a discriminant value fixes a relatum's type) ──
    for rec in ds
        .subjects_of_type(CONDITIONAL_RANGE_ASSERTION)
        .map_err(q)?
    {
        let field = |p: &str| -> Result<String, gmeow_errors::Diag> {
            ds.first_object_iri(&rec, &format!("{LOGIC_NS}{p}"))
                .map_err(q)?
                .ok_or_else(|| {
                    gmeow_errors::Diag::of_kind(crate::error::Parse {
                        message: format!("conditional-range assertion {rec} lacks logic:{p}"),
                    })
                })
        };
        let target = field("conditionalRangeTarget")?;
        let selector = field("conditionalRangeSelector")?;
        let sel_value = field("conditionalRangeSelectorValue")?;
        let value_prop = field("conditionalRangeValue")?;
        let req_type = field("conditionalRangeRequiredType")?;
        let iri = format!("{NS}{}ConstraintShape", pascal(&rec));
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{rec}> ;\n    sh:targetClass <{target}> ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"A <{target}> whose gmeow:{sel_l} is gmeow:{selv_l} must bind a <{req_type}> via gmeow:{val_l}.\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this <{selector}> <{sel_value}> . $this <{value_prop}> ?v . FILTER NOT EXISTS {{ ?v a/rdfs:subClassOf* <{req_type}> }} }}\"\"\" ;\n    ] .\n",
            sel_l = local(&selector),
            selv_l = local(&sel_value),
            val_l = local(&value_prop),
        );
        shapes.push(ShapeBlock { iri, block });
    }

    // ── Role-composition-exclusion assertions (a relator's two roles are not whole/part) ──
    for rec in ds
        .subjects_of_type(ROLE_COMPOSITION_EXCLUSION_ASSERTION)
        .map_err(q)?
    {
        let field = |p: &str| -> Result<String, gmeow_errors::Diag> {
            ds.first_object_iri(&rec, &format!("{LOGIC_NS}{p}"))
                .map_err(q)?
                .ok_or_else(|| {
                    gmeow_errors::Diag::of_kind(crate::error::Parse {
                        message: format!(
                            "role-composition-exclusion assertion {rec} lacks logic:{p}"
                        ),
                    })
                })
        };
        let target = field("compositionExclusionTarget")?;
        let whole = field("compositionExclusionWhole")?;
        let part = field("compositionExclusionPart")?;
        let mut via = ds
            .object_iris(&rec, &format!("{LOGIC_NS}compositionExclusionVia"))
            .map_err(q)?;
        via.sort();
        if via.is_empty() {
            return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: format!(
                    "role-composition-exclusion assertion {rec} names no logic:compositionExclusionVia step"
                ),
            }));
        }
        let union = via
            .iter()
            .map(|v| format!("{{ ?w <{v}> ?p }}"))
            .collect::<Vec<_>>()
            .join(" UNION ");
        let iri = format!("{NS}{}ConstraintShape", pascal(&rec));
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{rec}> ;\n    sh:targetClass <{target}> ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"A <{target}> instance's gmeow:{whole_l} must not name its gmeow:{part_l} as one of its own components.\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this <{whole}> ?w . $this <{part}> ?p . {union} }}\"\"\" ;\n    ] .\n",
            whole_l = local(&whole),
            part_l = local(&part),
        );
        shapes.push(ShapeBlock { iri, block });
    }

    // ── Mediated-property-requirement assertions (a mediated value must carry a property) ──
    for rec in ds
        .subjects_of_type(MEDIATED_REQUIREMENT_ASSERTION)
        .map_err(q)?
    {
        let field = |p: &str| -> Result<String, gmeow_errors::Diag> {
            ds.first_object_iri(&rec, &format!("{LOGIC_NS}{p}"))
                .map_err(q)?
                .ok_or_else(|| {
                    gmeow_errors::Diag::of_kind(crate::error::Parse {
                        message: format!("mediated-requirement assertion {rec} lacks logic:{p}"),
                    })
                })
        };
        let target = field("mediatedRequirementTarget")?;
        let via = field("mediatedRequirementVia")?;
        let required = field("mediatedRequirementProperty")?;
        let iri = format!("{NS}{}ConstraintShape", pascal(&rec));
        let block = format!(
            "<{iri}>\n    a sh:NodeShape ;\n    logic:formalizes <{rec}> ;\n    sh:targetClass <{target}> ;\n    sh:sparql [\n        a sh:SPARQLConstraint ;\n        sh:severity sh:Violation ;\n        sh:message \"A <{target}> instance's gmeow:{via_l} value must declare a gmeow:{req_l}.\" ;\n        sh:select \"\"\"SELECT $this WHERE {{ $this <{via}> ?v . FILTER NOT EXISTS {{ ?v <{required}> ?x }} }}\"\"\" ;\n    ] .\n",
            via_l = local(&via),
            req_l = local(&required),
        );
        shapes.push(ShapeBlock { iri, block });
    }

    shapes.sort_by(|a, b| a.iri.cmp(&b.iri));
    let mut out = String::from(HEADER);
    for s in shapes {
        out.push('\n');
        out.push_str(&s.block);
    }
    Ok(out)
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `constraint-shapes` export-leaf stage.
pub struct ConstraintShapesStage;

impl Stage for ConstraintShapesStage {
    fn id(&self) -> &str {
        "stage-export-constraint-shapes"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "constraint_shapes.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // The axioms, their domains, and the named disjointness sets live across the
        // authored root ontology + slice modules; a change to any busts the cache.
        let mut files = vec![root.join("ontology").join("gmeow.ttl")];
        files.extend(crate::stages::source_load::module_files(root)?);
        Ok(files)
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let ttl = render_constraint_shapes(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(CONSTRAINT_SHAPES_PATH.to_string(), ttl.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[path = "constraint_shapes.tests.rs"]
#[cfg(test)]
mod tests;
