// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `frame-shapes` export leaf (P4): Principle 11 SHACL by annotation.
//!
//! A genuine port of `src/gmeow_tools/frame_shapes_gen.py` (no Rust existed):
//! every `gmeow:requiresFrame` declaration in the root ontology + slice modules
//! becomes a generated frame-relativity NodeShape. Byte-deterministic → compared
//! byte-for-byte to the committed `generated/shapes/frame-shapes.ttl`.

use std::collections::BTreeMap;
use std::path::Path;

use gmeow_errors::abox::{BOX_ABOX, abox_annotation_turtle_lines};
use gmeow_logic_compile::ir::{
    ConstraintComponent, ConstraintProvenance, PropertyConstraintIr, ShaclNodeKind, ShaclSeverity,
    ShapeTarget, ValidationShapeIr,
};
use purrdf::slice::rdf_query::{Dataset, DatasetAccumulator, Object};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};
use crate::stages::rule_severity::RuleSeverity;
use crate::stages::source_load::module_files;

/// Committed logical path of the generated frame-relativity shapes.
pub const FRAME_SHAPES_PATH: &str = "generated/shapes/frame-shapes.ttl";

const NS: &str = "https://blackcatinformatics.ca/gmeow/";
/// The canonical `logic:functionalProperty` characteristic authored in a module.
const LOGIC_FUNCTIONAL: &str = "https://blackcatinformatics.ca/logic/functionalProperty";
/// Its generated OWL view (`owl:FunctionalProperty`, upper-camel).
const OWL_FUNCTIONAL: &str = "http://www.w3.org/2002/07/owl#FunctionalProperty";

const HEADER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (frame-shapes) from gmeow:requiresFrame\n# declarations in the slice modules — DO NOT EDIT.\n@prefix gmeow: <https://blackcatinformatics.ca/gmeow/> .\n@prefix sh:    <http://www.w3.org/ns/shacl#> .\n@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .\n";

/// The `rdfs:isDefinedBy` target every minted `*FrameRequirementShape` individual
/// carries — the deterministic per-committed-path graph-identity IRI
/// [`crate::stages::superset::rdf_fanout_graph_iri`] derives for any RDF file under
/// `generated/`. NOTE: `FRAME_SHAPES_PATH` currently rides in the `REP_SHAPES`
/// OPAQUE archive member (`carrier.rs::build_archive_blobs`), not an authored
/// `rdf-fanout` row in `slices/core/pipeline/module.ttl` — this IRI is the
/// document's stable identity label, not (yet) an independently RDF-fold-verified
/// named graph inside `gmeow.gts`.
fn frame_shapes_graph_iri() -> String {
    crate::stages::superset::rdf_fanout_graph_iri(FRAME_SHAPES_PATH)
        .expect("FRAME_SHAPES_PATH is a committed .ttl path under generated/")
}

/// Load the root ontology + every slice module into one frozen dataset (NO imports —
/// matching `load_merged_graph(include_imports=False)`). Each source's anonymous
/// blanks are standardized apart per file (a fresh blank scope per `add`), the native
/// twin of the old per-source scope prefix.
fn load_authored_no_imports(root: &Path) -> Result<Dataset, gmeow_errors::Diag> {
    let mut acc = DatasetAccumulator::new();
    let mut files = vec![root.join("ontology").join("gmeow.ttl")];
    files.extend(module_files(root)?);
    for path in files {
        if !path.is_file() {
            continue;
        }
        let bytes = std::fs::read(&path)?;
        acc.add_turtle(&bytes, None, &path.display().to_string())
            .map_err(|e| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: e.to_string(),
                })
            })?;
    }
    acc.freeze().map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: e.to_string(),
        })
    })
}

/// Single object of `(subject, predicate)` as a string, if any — a literal's lexical
/// value OR a named node's IRI (first match in dataset order), matching the prior
/// oxigraph `single_value`.
fn single_value(dataset: &Dataset, subject_iri: &str, predicate: &str) -> Option<String> {
    dataset
        .objects(subject_iri, predicate)
        .ok()?
        .into_iter()
        .find_map(|o| match o {
            Object::Literal { value, .. } => Some(value),
            Object::Named(iri) => Some(iri),
            _ => None,
        })
}

/// `(carrier-local, frame-prop-local, exactly_one, severity)` per declaration, sorted.
fn frame_requirements(
    dataset: &Dataset,
) -> Result<Vec<(String, String, bool, RuleSeverity)>, gmeow_errors::Diag> {
    let requires = format!("{NS}requiresFrame");

    // Collect (carrier, frame_prop) IRI pairs, sorted (named subject + named object).
    let mut pairs: Vec<(String, String)> =
        dataset.subject_object_iri_pairs(&requires).map_err(|e| {
            gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: e.to_string(),
            })
        })?;
    pairs.sort();
    pairs.dedup();

    let mut rows = Vec::with_capacity(pairs.len());
    for (carrier, frame_prop) in pairs {
        let exactly_one = match single_value(dataset, &carrier, &format!("{NS}frameCardinality")) {
            Some(v) => v == "exactly-one",
            None => {
                let has_char = |ty: &str| {
                    dataset.has_type(&frame_prop, ty).map_err(|e| {
                        gmeow_errors::Diag::of_kind(crate::error::Parse {
                            message: e.to_string(),
                        })
                    })
                };
                // Canonical `logic:functionalProperty` OR its `owl:` view.
                has_char(LOGIC_FUNCTIONAL)? || has_char(OWL_FUNCTIONAL)?
            }
        };
        let severity = RuleSeverity::parse(
            single_value(dataset, &carrier, &format!("{NS}ruleSeverity")).as_deref(),
        )?;
        rows.push((
            carrier.strip_prefix(NS).unwrap_or(&carrier).to_string(),
            frame_prop
                .strip_prefix(NS)
                .unwrap_or(&frame_prop)
                .to_string(),
            exactly_one,
            severity,
        ));
    }
    Ok(rows)
}

/// A frame-shapes invalid-declaration diagnostic on the unified Diag substrate — the
/// single crossing point where a shape-construction String error becomes a `Diag`.
fn invalid(message: String) -> gmeow_errors::Diag {
    gmeow_errors::Diag::of_kind(crate::error::InvalidDeclaration { message })
}

/// Map a per-rule [`RuleSeverity`] onto the canonical IR [`ShaclSeverity`] via its
/// SHACL token — the single crossing point where the frame stage's severity tier
/// becomes the constraint model's severity. The token set is closed, so an unmapped
/// token is a hard fail (never a silently-coerced default).
fn map_severity(severity: RuleSeverity) -> Result<ShaclSeverity, gmeow_errors::Diag> {
    match severity.shacl_token() {
        "sh:Violation" => Ok(ShaclSeverity::Violation),
        "sh:Warning" => Ok(ShaclSeverity::Warning),
        "sh:Info" => Ok(ShaclSeverity::Info),
        other => Err(invalid(format!(
            "frame-shapes: unmapped SHACL severity token `{other}`"
        ))),
    }
}

/// Build the canonical [`ValidationShapeIr`]s for the frame-relativity requirements —
/// the constraint DATA now lives in the shared IR (anti-drift), not in ad-hoc tuples.
/// The frame-specific renderer ([`render_frame_shape`]) consumes these.
fn frame_shapes(dataset: &Dataset) -> Result<Vec<ValidationShapeIr>, gmeow_errors::Diag> {
    let mut shapes = Vec::new();
    for (carrier, prop, exactly_one, severity) in frame_requirements(dataset)? {
        let count = if exactly_one {
            "exactly one"
        } else {
            "at least one"
        };
        let property = PropertyConstraintIr::new(
            format!("{NS}{prop}"),
            Some(1),
            if exactly_one { Some(1) } else { None },
            Some(ConstraintProvenance::OwlRestriction),
            vec![ConstraintComponent::NodeKindShacl(ShaclNodeKind::Iri)],
        )
        .map_err(|e| invalid(e.to_string()))?
        .with_severity(map_severity(severity)?)
        .with_message(format!(
            "A {carrier} must carry {count} reference frame (gmeow:{prop}) — a value asserted without its frame is ill-formed (CONSTITUTION P11)."
        ))
        .map_err(|e| invalid(e.to_string()))?;
        let shape = ValidationShapeIr::new(
            format!("{NS}{carrier}FrameRequirementShape"),
            ShapeTarget::Class(format!("{NS}{carrier}")),
            vec![property],
            None,
        )
        .map_err(|e| invalid(e.to_string()))?
        .with_label(format!("{carrier} frame-relativity shape (generated)"))
        .map_err(|e| invalid(e.to_string()))?;
        shapes.push(shape);
    }
    Ok(shapes)
}

/// Strip the `gmeow:` namespace prefix off an IRI to recover its local name.
fn local_name(iri: &str) -> &str {
    iri.strip_prefix(NS).unwrap_or(iri)
}

/// The frame render mode: reproduce the exact committed bytes for ONE shape by
/// CONSUMING its canonical [`ValidationShapeIr`] — the local names, cardinality,
/// node-kind, severity, message, and label are all read back off the IR, never
/// re-derived from the tuple, so the constraint model is the single source of truth.
fn render_frame_shape(shape: &ValidationShapeIr) -> Result<String, gmeow_errors::Diag> {
    let carrier = match &shape.target {
        ShapeTarget::Class(c) => local_name(c),
        other => {
            return Err(invalid(format!(
                "frame-shapes: expected a class target, got {other:?}"
            )));
        }
    };
    let label = shape
        .label
        .as_deref()
        .ok_or_else(|| invalid("frame-shapes: shape is missing its rdfs:label".to_owned()))?;
    let property = match shape.properties.as_slice() {
        [p] => p,
        _ => {
            return Err(invalid(
                "frame-shapes: expected exactly one property shape".to_owned(),
            ));
        }
    };
    let prop = local_name(&property.path);
    let min = property
        .min_count
        .ok_or_else(|| invalid("frame-shapes: property is missing sh:minCount".to_owned()))?;
    let node_kind = property
        .components
        .iter()
        .find_map(|c| match c {
            ConstraintComponent::NodeKindShacl(k) => Some(k),
            _ => None,
        })
        .ok_or_else(|| invalid("frame-shapes: property is missing sh:nodeKind".to_owned()))?;
    let severity = property
        .severity
        .ok_or_else(|| invalid("frame-shapes: property is missing sh:severity".to_owned()))?;
    let message = property
        .message
        .as_deref()
        .ok_or_else(|| invalid("frame-shapes: property is missing sh:message".to_owned()))?;

    let graph_iri = frame_shapes_graph_iri();
    let definition =
        format!("SHACL frame-requirement shape for the {carrier} carrier (generated).");
    let subject_iri = format!("{NS}{carrier}FrameRequirementShape");
    let mut lines: Vec<String> = vec![
        format!("gmeow:{carrier}FrameRequirementShape"),
        "    a sh:NodeShape ;".to_string(),
    ];
    lines.extend(abox_annotation_turtle_lines(
        &subject_iri,
        label,
        &definition,
        &graph_iri,
        BOX_ABOX,
        "    ",
    ));
    lines.extend([
        format!("    sh:targetClass gmeow:{carrier} ;"),
        "    sh:property [".to_string(),
        format!("        sh:path gmeow:{prop} ;"),
        format!("        sh:minCount {min} ;"),
    ]);
    if let Some(max) = property.max_count {
        lines.push(format!("        sh:maxCount {max} ;"));
    }
    lines.push(format!("        sh:nodeKind sh:{} ;", node_kind.as_str()));
    lines.push(format!("        sh:severity sh:{} ;", severity.as_str()));
    lines.push(format!("        sh:message \"{message}\" ;"));
    lines.push("    ] .".to_string());
    Ok(lines.join("\n") + "\n")
}

/// Render the frame-relativity shapes document — the constraint data flows through
/// [`ValidationShapeIr`], then the frame-specific renderer reproduces the committed bytes.
pub fn render_frame_shapes(root: &Path) -> Result<String, gmeow_errors::Diag> {
    let store = load_authored_no_imports(root)?;
    let mut blocks: Vec<String> = vec![HEADER.to_string()];
    for shape in &frame_shapes(&store)? {
        blocks.push(render_frame_shape(shape)?);
    }
    Ok(blocks.join("\n"))
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `frame-shapes` export-leaf stage.
pub struct FrameShapesStage;

impl Stage for FrameShapesStage {
    fn id(&self) -> &str {
        "stage-export-frame-shapes"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "frame_shapes.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // The `gmeow:requiresFrame` declarations this leaf reads ARE in the fold's
        // authored default graph, so a consume-`stage-snapshot` rewrite is possible
        // (the MAXIMAL-INFORMATION-FLOW option). We instead declare the SAME authored
        // sources (root ontology + slice modules) as cache inputs: it is exactly as
        // sound (the fold's default graph is built from these same files, and the
        // IRI→IRI frame declarations are language-neutral so translations never touch
        // them) while keeping `consumes() == []` — no DAG re-wire, no byte-parity risk
        // from re-reading through the GTS store. A declaration change busts the cache.
        let mut files = vec![root.join("ontology").join("gmeow.ttl")];
        files.extend(crate::stages::source_load::module_files(root)?);
        Ok(files)
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let ttl = render_frame_shapes(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(FRAME_SHAPES_PATH.to_string(), ttl.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[path = "frame_shapes.tests.rs"]
#[cfg(test)]
mod tests;
