// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `governance-floors` export leaf (P4/P17): the two slice-quality floor TSVs
//! projected from the ontology-resident floor commitments.
//!
//! The canonical floors live as individuals in the `slice-quality-rubric` slice —
//! one `gmeow:AxisFloorCommitment` per committed `(slice, axis)` measured-score
//! floor, one `gmeow:SliceTierFloor` per committed per-slice roll-up tier floor. The
//! slice-quality gate reads them straight out of the ontology (via
//! [`gmeow_slice_quality::load_repo_floors`]); these two TSVs are their **lossy
//! projection** for humans and external tooling, never a second source of truth.
//!
//! * `generated/governance/slice-quality-axis-floors.tsv` — one
//!   `<slice-iri>\t<axis-local>\t<floor:f64>` row per `gmeow:AxisFloorCommitment`,
//!   sorted by `(slice-iri, axis-local)`, the floor emitted at full f64 precision
//!   (the shortest round-tripping decimal, with a `.0` suffix on integer-valued
//!   floors so the projection is byte-stable and human-legible).
//! * `generated/governance/slice-quality-floors.tsv` — one
//!   `<slice-iri>\t<tier-local>` row per `gmeow:SliceTierFloor`, sorted by slice-iri.
//!
//! Byte-deterministic and carried as opaque blob members of the bundle's
//! `generated`-fanout archive (a TSV is non-RDF, so it rides as a byte projection,
//! not a named-graph fold); the superset gate reconstructs both byte-for-byte. A
//! human RAISES a floor by editing the commitment individual in the slice, never by
//! editing these read-only projections. Emit-only; the ontology is the authoring
//! ground (Principle 17).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use gmeow_logic_compile::ir::PreservationKind;
use gmeow_logic_compile::loss_ledger::LossLedger;
use gmeow_logic_compile::projections::ProjectionResult;
use gmeow_slice_quality::model::GovernanceFloors;

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

/// Committed logical path of the generated per-axis floor projection.
pub const AXIS_FLOORS_PATH: &str = "generated/governance/slice-quality-axis-floors.tsv";
/// Committed logical path of the generated per-slice roll-up tier floor projection.
pub const TIER_FLOORS_PATH: &str = "generated/governance/slice-quality-floors.tsv";

/// The one authored source these projections are folded from: the rubric module the
/// floor commitments live in. A change to it busts this stage's cache.
const RUBRIC_MODULE: &str = "slices/core/slice-quality-rubric/module.ttl";

const AXIS_HEADER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (governance-floors) — DO NOT EDIT\n# (Principle 17: the gmeow:AxisFloorCommitment individuals in the slice-quality-rubric\n# slice are canonical; this TSV is their lossy projection. A human RAISES a floor by\n# editing the gmeow:AxisFloorCommitment individual for that slice/axis in the\n# slice-quality-rubric slice and re-running `make sync` — never by editing this\n# read-only generated file.)\n# Format: <slice-iri>\\t<axis-local-name>\\t<floor:f64>\n";

const TIER_HEADER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (governance-floors) — DO NOT EDIT\n# (Principle 17: the gmeow:SliceTierFloor individuals in the slice-quality-rubric slice\n# are canonical; this TSV is their lossy projection. A human RAISES a floor by editing\n# the gmeow:SliceTierFloor individual for that slice in the slice-quality-rubric slice\n# and re-running `make sync` — never by editing this read-only generated file.)\n# Format: <slice-iri>\\t<tier-local-name>\n";

/// The two loss-ledger projection targets (mirrors `docs-format:<slug>`), one per TSV.
const AXIS_LOSS_TARGET: &str = "governance-floor:axis-floors";
const TIER_LOSS_TARGET: &str = "governance-floor:tier-floors";

/// The local name of a `gmeow:` IRI (the part after the last `/` or `#`).
fn local(iri: &str) -> &str {
    iri.rsplit(['/', '#']).next().unwrap_or(iri)
}

/// Render one floor as its shortest round-tripping decimal, with a `.0` suffix on an
/// integer-valued float so `1.0` reads as `1.0` (not the Display default `1`). The
/// loader hard-failed any non-finite floor, so this only ever sees a finite value.
fn fmt_floor(floor: f64) -> String {
    let s = format!("{floor}");
    if s.contains('.') || s.contains('e') || s.contains('E') {
        s
    } else {
        format!("{s}.0")
    }
}

/// Render the per-axis floor TSV: the `gmeow:AxisFloorCommitment` set projected to
/// `<slice-iri>\t<axis-local>\t<floor>` rows, sorted by `(slice-iri, axis-local)`.
#[must_use]
pub fn render_axis_floors(floors: &GovernanceFloors) -> String {
    let mut rows: Vec<(String, String, f64)> = floors
        .commitments
        .iter()
        .map(|c| (c.slice.clone(), local(&c.axis).to_owned(), c.floor))
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));
    let mut out = String::from(AXIS_HEADER);
    for (slice, axis, floor) in rows {
        out.push_str(&format!("{slice}\t{axis}\t{}\n", fmt_floor(floor)));
    }
    out
}

/// Render the per-slice roll-up tier floor TSV: the `gmeow:SliceTierFloor` set
/// projected to `<slice-iri>\t<tier-local>` rows, sorted by slice-iri.
#[must_use]
pub fn render_tier_floors(floors: &GovernanceFloors) -> String {
    let mut rows: Vec<(String, String)> = floors
        .tier_floors
        .iter()
        .map(|tf| (tf.slice.clone(), local(&tf.tier).to_owned()))
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0));
    let mut out = String::from(TIER_HEADER);
    for (slice, tier) in rows {
        out.push_str(&format!("{slice}\t{tier}\n"));
    }
    out
}

/// Fold the two governance-floor projections' preservation judgments into the shared
/// projection loss ledger. Blob-free (a pure structural statement of what each TSV
/// projection drops), so the mappings stage — where the single report loss store
/// lives — folds it exactly like every sibling `lang:` / docs-format corpus.
///
/// Each TSV is a `PreservationKind::SoundUnder` (sound under-approximation): every row
/// it carries is entailed by the ontology commitment it projects, but the projection
/// drops the reified commitment's subject identity (the `gmeow:AxisFloorCommitment` /
/// `gmeow:SliceTierFloor` individual IRI) and any annotation coat (rationale,
/// provenance) the individual carries — recorded here, never silently dropped.
pub fn fold_governance_floors_loss(ledger: &mut Vec<ProjectionResult>, loss: &mut LossLedger) {
    for (target, subject_kind) in [
        (AXIS_LOSS_TARGET, "gmeow:AxisFloorCommitment"),
        (TIER_LOSS_TARGET, "gmeow:SliceTierFloor"),
    ] {
        let lossy_drops = vec![
            format!(
                "the reified {subject_kind} subject identity (the individual IRI) is dropped: \
                 the TSV row carries only the projected (slice, floor) tuple, not its reifier"
            ),
            format!(
                "the {subject_kind} annotation coat (any rationale / provenance triples on the \
                 individual) is dropped: the TSV projects only the core floor tuple"
            ),
        ];
        let actual_drops = vec![format!(
            "governance-floor projection '{target}' is a sound under-approximation: every emitted \
             row is entailed by its {subject_kind} individual; the reifier identity and annotation \
             coat are the enumerated residue (derived preservation = logic:{})",
            PreservationKind::SoundUnder.as_str(),
        )];
        loss.record_projection_drops(
            target,
            PreservationKind::SoundUnder,
            &lossy_drops,
            &actual_drops,
        );
        ledger.push(ProjectionResult {
            target: target.to_owned(),
            content: String::new(),
            is_rdf: false,
            preservation: PreservationKind::SoundUnder,
            complexity: "n/a".to_string(),
        });
    }
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `governance-floors` export-leaf stage.
pub struct GovernanceFloorsStage;

impl Stage for GovernanceFloorsStage {
    fn id(&self) -> &str {
        "stage-export-governance-floors"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "governance_floors.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<PathBuf>, gmeow_errors::Diag> {
        // The canonical floors live as individuals in the rubric module; an edit to it
        // (raising a floor) busts this stage's cache and re-projects both TSVs.
        Ok(vec![root.join(RUBRIC_MODULE)])
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let floors = gmeow_slice_quality::load_repo_floors(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(
            AXIS_FLOORS_PATH.to_string(),
            render_axis_floors(&floors).into_bytes(),
        );
        artifacts.insert(
            TIER_FLOORS_PATH.to_string(),
            render_tier_floors(&floors).into_bytes(),
        );
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    #[test]
    fn fmt_floor_matches_python_repr_style() {
        // The migration-fidelity invariant: an integer-valued floor reads as `1.0`
        // (matching the pre-deletion hand-authored values), a fractional floor is the
        // shortest round-tripping decimal unchanged.
        assert_eq!(fmt_floor(1.0), "1.0");
        assert_eq!(fmt_floor(0.9954337899543378), "0.9954337899543378");
        assert_eq!(fmt_floor(0.0), "0.0");
    }

    #[test]
    fn axis_floors_project_deterministically_from_the_ontology() {
        let root = repo_root();
        let floors = gmeow_slice_quality::load_repo_floors(&root).expect("load floors");
        let a = render_axis_floors(&floors);
        let b = render_axis_floors(&floors);
        assert_eq!(a, b, "axis-floor projection must be deterministic");

        let data_rows: Vec<&str> = a.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(
            data_rows.len(),
            floors.commitments.len(),
            "one data row per gmeow:AxisFloorCommitment"
        );
        // The migration spot-check: the accounts slice's axisGmn1Coverage floor
        // reproduces its historical value exactly (ontology → projection fidelity).
        assert!(
            a.contains(
                "https://blackcatinformatics.ca/gmeow/slices/accounts\taxisGmn1Coverage\t0.9954337899543378\n"
            ),
            "the accounts axis floor must reproduce the historical 0.9954337899543378"
        );
        // Rows are sorted by (slice-iri, axis-local).
        let mut sorted = data_rows.clone();
        sorted.sort();
        assert_eq!(data_rows, sorted, "axis-floor rows must be sorted");
    }

    #[test]
    fn tier_floors_project_deterministically_from_the_ontology() {
        let root = repo_root();
        let floors = gmeow_slice_quality::load_repo_floors(&root).expect("load floors");
        let out = render_tier_floors(&floors);
        let data_rows: Vec<&str> = out.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(
            data_rows.len(),
            floors.tier_floors.len(),
            "one data row per gmeow:SliceTierFloor"
        );
        for row in &data_rows {
            let cols: Vec<&str> = row.split('\t').collect();
            assert_eq!(
                cols.len(),
                2,
                "tier-floor row is <slice-iri>\\t<tier-local>"
            );
        }
    }

    #[test]
    fn generated_axis_floors_are_byte_reconstructible_from_the_bundle() {
        // The opaque-blob superset property: the shipped gmeow.gts reconstructs both
        // committed governance TSVs byte-for-byte (they ride as REP_GENERATED members),
        // and the reconstruction equals THIS stage's fresh projection.
        let root = repo_root();
        let gts = std::fs::read(root.join("generated/dist/gmeow.gts")).expect("read bundle");
        let projection = crate::stages::superset::project_bundle(&gts).expect("project bundle");

        let floors = gmeow_slice_quality::load_repo_floors(&root).expect("load floors");
        for (path, fresh) in [
            (AXIS_FLOORS_PATH, render_axis_floors(&floors)),
            (TIER_FLOORS_PATH, render_tier_floors(&floors)),
        ] {
            let reconstructed = projection.files.get(path).unwrap_or_else(|| {
                panic!("{path} must reconstruct from gmeow.gts as a blob member")
            });
            assert_eq!(
                reconstructed,
                &fresh.into_bytes(),
                "{path} bundle reconstruction must equal the fresh ontology projection"
            );
            let committed = std::fs::read(root.join(path))
                .unwrap_or_else(|_| panic!("committed {path} must exist"));
            assert_eq!(
                reconstructed, &committed,
                "{path} bundle reconstruction must equal the committed bytes"
            );
        }
    }
}
