// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `metadata` export leaf (#861 P4): VoID + DCAT dataset descriptions.
//!
//! A genuine port of `src/gmeow_tools/metadata.py` (no Rust existed). Reads the
//! composed fold (`gmeow.gts`) and emits two RDF/Turtle artifacts:
//!   * `generated/metadata/void.ttl` — the VoID dataset description + linksets
//!     (what the LOD-Cloud submission consumes), and
//!   * `generated/metadata/dcat.ttl` — a FAIR DCAT dataset / distribution /
//!     profile view (#330).
//!
//! Every data-derived value comes from the GTS snapshot: the version + abstract
//! from the ontology header in the *default* graph, the linksets from the
//! `graph/alignments` named graph, the Wikidata links from `graph/metadata`. The
//! committed artifacts were rdflib-serialized; we serialize with oxigraph and
//! the gate compares by graph ISOMORPHISM (both files are blank-node-free, so
//! isomorphism reduces to triple-set equality).

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use gmeow_rdf::model::{RdfLiteral, RdfTerm};
use gmeow_rdf::oxigraph::dataset_from_store;
use gmeow_rdf::{serialize_dataset, RdfDataset, SerializeGraph};
use oxigraph::model::{Literal, NamedNode, Quad, Term};
use oxigraph::store::Store;
use sha2::{Digest, Sha256};

use crate::error::PipelineError;
use crate::node::{Stage, StageInput, StageKind, StageOutput, StageProduct};
use crate::stages::profiles::{
    dependency_closure, discover_slices, group_named_profiles, SliceMeta,
};

/// Logical path of the generated VoID document.
pub const VOID_PATH: &str = "generated/metadata/void.ttl";
/// Logical path of the generated DCAT document.
pub const DCAT_PATH: &str = "generated/metadata/dcat.ttl";

const ONTOLOGY_IRI: &str = "https://blackcatinformatics.ca/gmeow";
const NAMESPACE: &str = "https://blackcatinformatics.ca/gmeow/";
const VOID_DATASET_IRI: &str = "https://blackcatinformatics.ca/gmeow/.well-known/void.ttl#dataset";
const FULL_PROFILE_IRI: &str = "https://blackcatinformatics.ca/gmeow/full";
const NAMED_PROFILE_NS: &str = "https://blackcatinformatics.ca/gmeow/profiles/";

// GTS named-graph scopes.
const GTS_GRAPH_ALIGNMENTS: &str = "https://blackcatinformatics.ca/gmeow/graph/alignments";
const GTS_GRAPH_METADATA: &str = "https://blackcatinformatics.ca/gmeow/graph/metadata";

// Vocabulary IRIs.
const OWL: &str = "http://www.w3.org/2002/07/owl#";
const RDFS: &str = "http://www.w3.org/2000/01/rdf-schema#";
const SKOS: &str = "http://www.w3.org/2004/02/skos/core#";
const DCTERMS: &str = "http://purl.org/dc/terms/";
const FOAF: &str = "http://xmlns.com/foaf/0.1/";
const GUFO: &str = "http://purl.org/nemo/gufo#";
const VOID: &str = "http://rdfs.org/ns/void#";
const DCAT: &str = "http://www.w3.org/ns/dcat#";
const XSD: &str = "http://www.w3.org/2001/XMLSchema#";

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const OWL_VERSION_INFO: &str = "http://www.w3.org/2002/07/owl#versionInfo";
const DCTERMS_DESCRIPTION: &str = "http://purl.org/dc/terms/description";
const GMEOW_AUTHORITY_LINK: &str = "https://blackcatinformatics.ca/gmeow/authorityLink";
const SKOS_EXACT_MATCH: &str = "http://www.w3.org/2004/02/skos/core#exactMatch";
const WIKIDATA_PREFIX: &str = "http://www.wikidata.org/entity/";

const CC_BY: &str = "https://creativecommons.org/licenses/by/4.0/";
const PUBLISHER: &str = "https://blackcatinformatics.ca/#bii";

const CLASS_TYPES: &[&str] = &[
    "http://www.w3.org/2002/07/owl#Class",
    "http://www.w3.org/2000/01/rdf-schema#Class",
];
const PROPERTY_TYPES: &[&str] = &[
    "http://www.w3.org/2002/07/owl#ObjectProperty",
    "http://www.w3.org/2002/07/owl#DatatypeProperty",
    "http://www.w3.org/2002/07/owl#AnnotationProperty",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
];

/// W3C format-registry IRIs by published extension. Order matters (matches the
/// Python dict insertion order: ttl, rdf, nt, jsonld).
const FORMAT_IRI: &[(&str, &str)] = &[
    ("ttl", "http://www.w3.org/ns/formats/Turtle"),
    ("rdf", "http://www.w3.org/ns/formats/RDF_XML"),
    ("nt", "http://www.w3.org/ns/formats/N-Triples"),
    ("jsonld", "http://www.w3.org/ns/formats/JSON-LD"),
];
/// Media types by extension, same order.
const MEDIA_TYPE: &[(&str, &str)] = &[
    ("ttl", "text/turtle"),
    ("rdf", "application/rdf+xml"),
    ("nt", "application/n-triples"),
    ("jsonld", "application/ld+json"),
];

include!("metadata_targets.rs");
include!("lpg_prefixes.rs");

const BANNER: &str = "# GENERATED by gmeow metadata — DO NOT EDIT.\n# https://github.com/Blackcat-Informatics/gmeow-ontology\n\n";

// ── Fold reads ───────────────────────────────────────────────────────────────

fn term_iri(t: &RdfTerm) -> Option<&str> {
    match t {
        RdfTerm::Iri(i) => Some(i),
        _ => None,
    }
}

fn graph_iri(t: &Option<RdfTerm>) -> Option<&str> {
    match t {
        Some(RdfTerm::Iri(i)) => Some(i),
        _ => None,
    }
}

/// A subject's identity key for the class/property census (IRI or blank node).
fn subject_key(t: &RdfTerm) -> String {
    match t {
        RdfTerm::Iri(i) => format!("I{i}"),
        RdfTerm::BlankNode(b) => format!("B{b}"),
        _ => format!("?{t:?}"),
    }
}

/// CURIE under the longest matching prefix (`PREFIXES_BY_LEN` is longest-first).
fn curie(iri: &str) -> String {
    for (prefix, ns) in PREFIXES_BY_LEN.iter() {
        if let Some(rest) = iri.strip_prefix(ns) {
            return format!("{prefix}:{rest}");
        }
    }
    iri.to_string()
}

/// Namespace of an IRI: split on the last `#`, else the last `/` (Python
/// `object_namespace`). If neither present, return the IRI unchanged.
fn object_namespace(iri: &str) -> String {
    for sep in ['#', '/'] {
        if let Some(pos) = iri.rfind(sep) {
            return format!("{}{sep}", &iri[..pos]);
        }
    }
    iri.to_string()
}

/// The lexical value of a literal/IRI object of `(ONTOLOGY_IRI, predicate)` in
/// the default graph (`graph_name == None`).
fn fold_header_value(store: &RdfDataset, predicate: &str) -> Result<Option<String>, PipelineError> {
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name).is_some() {
            continue; // default graph only
        }
        if term_iri(&q.subject) != Some(ONTOLOGY_IRI) || q.predicate != predicate {
            continue;
        }
        if let RdfTerm::Literal(RdfLiteral { lexical_form, .. }) = &q.object {
            return Ok(Some(lexical_form.clone()));
        }
    }
    Ok(None)
}

fn fold_version(store: &RdfDataset) -> Result<String, PipelineError> {
    fold_header_value(store, OWL_VERSION_INFO)?.ok_or_else(|| {
        PipelineError::Parse(format!("snapshot lacks owl:versionInfo on {ONTOLOGY_IRI}"))
    })
}

fn fold_description(store: &RdfDataset) -> Result<String, PipelineError> {
    fold_header_value(store, DCTERMS_DESCRIPTION)?.ok_or_else(|| {
        PipelineError::Parse(format!(
            "snapshot lacks dcterms:description on {ONTOLOGY_IRI}"
        ))
    })
}

/// Wikidata authority/exact-match links for the Work, scoped to `graph/metadata`.
fn fold_wikidata_links(store: &RdfDataset) -> Result<Vec<String>, PipelineError> {
    let mut links: BTreeSet<String> = BTreeSet::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name) != Some(GTS_GRAPH_METADATA) {
            continue;
        }
        if term_iri(&q.subject) != Some(ONTOLOGY_IRI) {
            continue;
        }
        if q.predicate != GMEOW_AUTHORITY_LINK && q.predicate != SKOS_EXACT_MATCH {
            continue;
        }
        if let Some(obj) = term_iri(&q.object) {
            if obj.starts_with(WIKIDATA_PREFIX) {
                links.insert(obj.to_string());
            }
        }
    }
    Ok(links.into_iter().collect())
}

struct VoidStats {
    triples: u64,
    classes: u64,
    properties: u64,
    entities: u64,
}

/// VoID statistics over the *default* graph (`graph_name == None`).
fn fold_stats(store: &RdfDataset) -> Result<VoidStats, PipelineError> {
    let mut triples: u64 = 0;
    let mut entities: BTreeSet<String> = BTreeSet::new();
    let mut classes: BTreeSet<String> = BTreeSet::new();
    let mut properties: BTreeSet<String> = BTreeSet::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name).is_some() {
            continue; // default graph only
        }
        triples += 1;
        if let Some(s) = term_iri(&q.subject) {
            if s.starts_with(NAMESPACE) {
                entities.insert(s.to_string());
            }
        }
        // Class/property census counts every subject (IRI *or* blank node),
        // mirroring Python `subjects_by_type` which buckets by term-id.
        if q.predicate == RDF_TYPE {
            if let Some(obj) = term_iri(&q.object) {
                if CLASS_TYPES.contains(&obj) || PROPERTY_TYPES.contains(&obj) {
                    let key = subject_key(&q.subject);
                    if CLASS_TYPES.contains(&obj) {
                        classes.insert(key.clone());
                    } else {
                        properties.insert(key);
                    }
                }
            }
        }
    }
    Ok(VoidStats {
        triples,
        classes: classes.len() as u64,
        properties: properties.len() as u64,
        entities: entities.len() as u64,
    })
}

/// One VoID linkset row.
struct Linkset {
    iri: String,
    target_ns: String,
    predicate_iri: String,
    count: u64,
    label: String,
}

/// Linksets from the `graph/alignments` named graph: one per (target namespace,
/// predicate) pair where both predicate and object are IRIs.
fn fold_linksets(store: &RdfDataset) -> Result<Vec<Linkset>, PipelineError> {
    let mut buckets: BTreeMap<(String, String), u64> = BTreeMap::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name) != Some(GTS_GRAPH_ALIGNMENTS) {
            continue;
        }
        let Some(obj) = term_iri(&q.object) else {
            continue; // alignment axioms are IRI→IRI by construction
        };
        let target_ns = object_namespace(obj);
        *buckets.entry((target_ns, q.predicate.clone())).or_insert(0) += 1;
    }
    let mut out: Vec<Linkset> = Vec::new();
    for ((target_ns, predicate_iri), count) in buckets {
        let predicate_id = curie(&predicate_iri);
        let slug = predicate_id.replace(':', "_");
        let target_slug = {
            let trimmed = target_ns.trim_end_matches(['#', '/']);
            let last = trimmed.rsplit('/').next().unwrap_or("");
            if last.is_empty() {
                "target".to_string()
            } else {
                last.to_string()
            }
        };
        let ns_hash: String = Sha256::digest(target_ns.as_bytes())
            .iter()
            .take(3)
            .map(|b| format!("{b:02x}"))
            .collect();
        let iri = format!("{VOID_DATASET_IRI}-linkset-{target_slug}-{ns_hash}-{slug}");
        let label = format!("GMEOW {predicate_id} links to {target_ns} ({count})");
        out.push(Linkset {
            iri,
            target_ns,
            predicate_iri,
            count,
            label,
        });
    }
    Ok(out)
}

// ── Oxigraph term helpers ──────────────────────────────────────────────────────

fn nn(iri: &str) -> NamedNode {
    NamedNode::new(iri).expect("valid IRI")
}

fn add(store: &Store, s: &NamedNode, p: &str, o: Term) {
    let quad = Quad::new(
        s.clone(),
        nn(p),
        o,
        oxigraph::model::GraphName::DefaultGraph,
    );
    store.insert(&quad).expect("insert");
}

fn lit_en(s: &str) -> Term {
    Literal::new_language_tagged_literal(s, "en")
        .expect("lang tag")
        .into()
}

fn lit_int(n: u64) -> Term {
    Literal::new_typed_literal(n.to_string(), nn(&format!("{XSD}integer"))).into()
}

fn lit_str(s: &str) -> Term {
    Literal::new_simple_literal(s).into()
}

fn iri_term(s: &str) -> Term {
    nn(s).into()
}

// ── Graph builders ─────────────────────────────────────────────────────────────

fn build_void_store(store: &RdfDataset) -> Result<Store, PipelineError> {
    let out = Store::new().map_err(|e| PipelineError::Parse(e.to_string()))?;
    let dataset = nn(VOID_DATASET_IRI);

    add(
        &out,
        &dataset,
        RDF_TYPE,
        iri_term(&format!("{VOID}Dataset")),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}title"),
        lit_en("GMEOW — Global Metadata and Entity Ontology for the Web"),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}description"),
        lit_en(&fold_description(store)?),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}license"),
        iri_term(CC_BY),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}publisher"),
        iri_term(PUBLISHER),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}creator"),
        iri_term(PUBLISHER),
    );
    add(
        &out,
        &dataset,
        &format!("{FOAF}homepage"),
        iri_term(ONTOLOGY_IRI),
    );
    for link in fold_wikidata_links(store)? {
        add(&out, &dataset, GMEOW_AUTHORITY_LINK, iri_term(&link));
        add(&out, &dataset, SKOS_EXACT_MATCH, iri_term(&link));
    }
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}hasVersion"),
        lit_str(&fold_version(store)?),
    );
    add(
        &out,
        &dataset,
        &format!("{VOID}uriSpace"),
        lit_str(NAMESPACE),
    );
    add(
        &out,
        &dataset,
        &format!("{VOID}exampleResource"),
        iri_term(&format!("{NAMESPACE}Person")),
    );

    let stats = fold_stats(store)?;
    add(
        &out,
        &dataset,
        &format!("{VOID}triples"),
        lit_int(stats.triples),
    );
    add(
        &out,
        &dataset,
        &format!("{VOID}classes"),
        lit_int(stats.classes),
    );
    add(
        &out,
        &dataset,
        &format!("{VOID}properties"),
        lit_int(stats.properties),
    );
    add(
        &out,
        &dataset,
        &format!("{VOID}entities"),
        lit_int(stats.entities),
    );

    for (ext, fmt_iri) in FORMAT_IRI {
        add(&out, &dataset, &format!("{VOID}feature"), iri_term(fmt_iri));
        add(
            &out,
            &dataset,
            &format!("{VOID}dataDump"),
            iri_term(&format!("{ONTOLOGY_IRI}.{ext}")),
        );
    }

    for ns in [OWL, RDFS, SKOS, DCTERMS, GUFO] {
        add(&out, &dataset, &format!("{VOID}vocabulary"), iri_term(ns));
    }
    for ns in ALIGNMENT_TARGET_NS {
        add(&out, &dataset, &format!("{VOID}vocabulary"), iri_term(ns));
    }

    for ls in fold_linksets(store)? {
        let linkset = nn(&ls.iri);
        add(
            &out,
            &linkset,
            RDF_TYPE,
            iri_term(&format!("{VOID}Linkset")),
        );
        add(
            &out,
            &linkset,
            &format!("{VOID}subjectsTarget"),
            iri_term(VOID_DATASET_IRI),
        );
        add(
            &out,
            &linkset,
            &format!("{VOID}objectsTarget"),
            iri_term(&ls.target_ns),
        );
        add(
            &out,
            &linkset,
            &format!("{VOID}linkPredicate"),
            iri_term(&ls.predicate_iri),
        );
        add(&out, &linkset, &format!("{VOID}triples"), lit_int(ls.count));
        add(&out, &linkset, &format!("{RDFS}label"), lit_en(&ls.label));
        add(&out, &dataset, &format!("{VOID}subset"), iri_term(&ls.iri));
    }

    Ok(out)
}

fn build_dcat_store(store: &RdfDataset, root: &Path) -> Result<Store, PipelineError> {
    let out = Store::new().map_err(|e| PipelineError::Parse(e.to_string()))?;
    let dataset = nn(ONTOLOGY_IRI);

    add(
        &out,
        &dataset,
        RDF_TYPE,
        iri_term(&format!("{DCAT}Dataset")),
    );
    add(&out, &dataset, &format!("{DCTERMS}title"), lit_en("GMEOW"));
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}description"),
        lit_en(&fold_description(store)?),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}license"),
        iri_term(CC_BY),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}publisher"),
        iri_term(PUBLISHER),
    );
    add(
        &out,
        &dataset,
        &format!("{DCAT}landingPage"),
        iri_term(ONTOLOGY_IRI),
    );
    add(
        &out,
        &dataset,
        &format!("{DCTERMS}hasVersion"),
        lit_str(&fold_version(store)?),
    );
    for link in fold_wikidata_links(store)? {
        add(&out, &dataset, GMEOW_AUTHORITY_LINK, iri_term(&link));
        add(&out, &dataset, SKOS_EXACT_MATCH, iri_term(&link));
    }
    for (ext, media) in MEDIA_TYPE {
        let dist = nn(&format!("{ONTOLOGY_IRI}#dist-{ext}"));
        add(
            &out,
            &dist,
            RDF_TYPE,
            iri_term(&format!("{DCAT}Distribution")),
        );
        add(
            &out,
            &dist,
            &format!("{DCAT}downloadURL"),
            iri_term(&format!("{ONTOLOGY_IRI}.{ext}")),
        );
        let media_lit = Literal::new_typed_literal(*media, nn(&format!("{XSD}string"))).into();
        add(&out, &dist, &format!("{DCAT}mediaType"), media_lit);
        add(
            &out,
            &dataset,
            &format!("{DCAT}distribution"),
            iri_term(dist.as_str()),
        );
    }

    // Profile IRIs are datasets too (#330).
    let slices: BTreeMap<String, SliceMeta> = discover_slices(root)?;
    let full = nn(FULL_PROFILE_IRI);
    add(&out, &full, RDF_TYPE, iri_term(&format!("{DCAT}Dataset")));
    add(
        &out,
        &full,
        &format!("{DCTERMS}title"),
        lit_en("GMEOW — full profile"),
    );
    add(
        &out,
        &full,
        &format!("{DCTERMS}hasPart"),
        iri_term(ONTOLOGY_IRI),
    );
    add(
        &out,
        &full,
        &format!("{DCAT}landingPage"),
        iri_term(FULL_PROFILE_IRI),
    );

    for (name, members) in group_named_profiles(&slices) {
        let profile_iri = format!("{NAMED_PROFILE_NS}{name}");
        let profile = nn(&profile_iri);
        let closure = dependency_closure(&name, &members, &slices)?;
        add(
            &out,
            &profile,
            RDF_TYPE,
            iri_term(&format!("{DCAT}Dataset")),
        );
        add(
            &out,
            &profile,
            &format!("{DCTERMS}title"),
            lit_en(&format!("GMEOW — {name} profile")),
        );
        add(
            &out,
            &profile,
            &format!("{DCTERMS}description"),
            lit_en(&format!(
                "Slim dependency-closed profile: {} declared slice(s), {} in the import closure.",
                members.len(),
                closure.len()
            )),
        );
        add(
            &out,
            &profile,
            &format!("{DCTERMS}isPartOf"),
            iri_term(FULL_PROFILE_IRI),
        );
        add(
            &out,
            &profile,
            &format!("{DCAT}landingPage"),
            iri_term(&profile_iri),
        );
    }
    Ok(out)
}

/// Serialize a store's default graph to Turtle bytes, banner-prefixed.
fn serialize(store: &Store) -> Result<Vec<u8>, PipelineError> {
    let mut buf: Vec<u8> = BANNER.as_bytes().to_vec();
    let dataset = dataset_from_store(store).map_err(|e| PipelineError::Parse(e.to_string()))?;
    let body = serialize_dataset(&dataset, "text/turtle", SerializeGraph::DefaultGraph)
        .map_err(|e| PipelineError::Parse(format!("turtle serialize: {e}")))?;
    buf.extend_from_slice(&body);
    Ok(buf)
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `metadata` export-leaf stage.
pub struct MetadataStage {
    consumes: Vec<String>,
}

impl MetadataStage {
    /// Construct the stage; it consumes THIS run's snapshot fold.
    pub fn new() -> Self {
        Self {
            consumes: vec!["stage-snapshot".to_string()],
        }
    }
}

impl Default for MetadataStage {
    fn default() -> Self {
        Self::new()
    }
}

impl Stage for MetadataStage {
    fn id(&self) -> &str {
        "stage-export-metadata"
    }
    fn kind(&self) -> StageKind {
        StageKind::ExportLeaf
    }
    fn consumes(&self) -> &[String] {
        &self.consumes
    }
    fn impl_version(&self) -> &str {
        "metadata.v1"
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, PipelineError> {
        // The shared parse-once event-import view of THIS run's snapshot fold (#1132
        // C5) — no re-parse of the gmeow.gts bytes.
        let events = crate::stages::snapshot::snapshot_events(input.upstream)?;
        let store = events.dataset.as_ref();

        let void = build_void_store(store)?;
        let dcat = build_dcat_store(store, input.root)?;

        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(VOID_PATH.to_string(), serialize(&void)?);
        artifacts.insert(DCAT_PATH.to_string(), serialize(&dcat)?);

        Ok(StageOutput {
            product: StageProduct::from_artifacts(self.id(), artifacts),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    /// N-Triple-encoded triple set of a store's default graph.
    fn triple_set(store: &Store) -> BTreeSet<String> {
        store
            .quads_for_pattern(None, None, None, None)
            .map(|q| {
                let q = q.unwrap();
                format!("{} {} {} .", q.subject, q.predicate, q.object)
            })
            .collect()
    }

    fn parse_committed(path: &Path) -> Store {
        let bytes = std::fs::read(path).unwrap_or_else(|_| panic!("committed missing: {path:?}"));
        crate::stages::source_load::turtle_bytes_to_store(&bytes, &format!("{path:?}"))
            .unwrap_or_else(|e| panic!("parse {path:?}: {e}"))
    }

    #[test]
    fn metadata_void_is_isomorphic_to_committed() {
        let root = repo_root();
        let gts = std::fs::read(root.join("generated/dist/gmeow.gts")).unwrap();
        let bundle = gmeow_rdf::import_gts_events(&gts).unwrap();
        let built = build_void_store(bundle.dataset.as_ref()).unwrap();
        let committed = parse_committed(&root.join(VOID_PATH));
        let a = triple_set(&built);
        let b = triple_set(&committed);
        // Stats sanity: the dataset's void:triples literal must be present.
        assert_eq!(
            a,
            b,
            "void.ttl drifted (built {} triples, committed {} triples)",
            a.len(),
            b.len()
        );
    }

    #[test]
    fn metadata_dcat_is_isomorphic_to_committed() {
        let root = repo_root();
        let gts = std::fs::read(root.join("generated/dist/gmeow.gts")).unwrap();
        let bundle = gmeow_rdf::import_gts_events(&gts).unwrap();
        let built = build_dcat_store(bundle.dataset.as_ref(), &root).unwrap();
        let committed = parse_committed(&root.join(DCAT_PATH));
        let a = triple_set(&built);
        let b = triple_set(&committed);
        assert_eq!(
            a,
            b,
            "dcat.ttl drifted (built {} triples, committed {} triples)",
            a.len(),
            b.len()
        );
    }

    /// Read a `void:<key>` integer literal off the dataset subject of the
    /// committed `void.ttl`, so the expected stats are sourced from the
    /// canonical artifact itself and never go stale on a refold.
    fn committed_void_stat(committed: &Store, key: &str) -> u64 {
        let dataset = nn(VOID_DATASET_IRI);
        let predicate = nn(&format!("{VOID}{key}"));
        let mut found: Option<u64> = None;
        for q in committed.quads_for_pattern(
            Some((&dataset).into()),
            Some((&predicate).into()),
            None,
            None,
        ) {
            let q = q.unwrap();
            if let Term::Literal(lit) = &q.object {
                found = Some(
                    lit.value()
                        .parse()
                        .unwrap_or_else(|_| panic!("void:{key} not an integer: {}", lit.value())),
                );
            }
        }
        found.unwrap_or_else(|| panic!("committed void.ttl lacks void:{key} on dataset"))
    }

    #[test]
    fn metadata_stats_match_committed_targets() {
        let root = repo_root();
        let gts = std::fs::read(root.join("generated/dist/gmeow.gts")).unwrap();
        let bundle = gmeow_rdf::import_gts_events(&gts).unwrap();
        let stats = fold_stats(bundle.dataset.as_ref()).unwrap();
        // Expected values are read from the committed `void.ttl` dataset subject
        // (the canonical artifact) rather than hardcoded, so they track every
        // refold automatically. `fold_stats` counts the default graph exactly as
        // the Python `metadata._fold_stats` does over `FoldView.quads(DEFAULT)`.
        let committed = parse_committed(&root.join(VOID_PATH));
        assert_eq!(
            stats.triples,
            committed_void_stat(&committed, "triples"),
            "triples"
        );
        assert_eq!(
            stats.entities,
            committed_void_stat(&committed, "entities"),
            "entities"
        );
        assert_eq!(
            stats.classes,
            committed_void_stat(&committed, "classes"),
            "classes"
        );
        assert_eq!(
            stats.properties,
            committed_void_stat(&committed, "properties"),
            "properties"
        );
    }
}
