// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `metadata` export leaf (P4): VoID + DCAT dataset descriptions.
//!
//! A genuine port of `src/gmeow_tools/metadata.py` (no Rust existed). Reads the
//! composed fold (`gmeow.gts`) and emits two RDF/Turtle artifacts:
//!   * `generated/metadata/void.ttl` — the VoID dataset description + linksets
//!     (what the LOD-Cloud submission consumes), and
//!   * `generated/metadata/dcat.ttl` — a FAIR DCAT dataset / distribution /
//!     profile view.
//!
//! Every data-derived value comes from the GTS snapshot: the version + abstract
//! from the ontology header in the *default* graph, the linksets from the
//! `graph/alignments` named graph, the Wikidata links from `graph/metadata`. The
//! committed artifacts were rdflib-serialized; we build the output as a native
//! [`RdfQuad`] set, fold it into the frozen IR via
//! [`purrdf::dataset_from_quads`], and serialize with the native codecs. The
//! gate compares by graph ISOMORPHISM (both files are blank-node-free, so
//! isomorphism reduces to triple-set equality).

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use purrdf::model::{RdfLiteral, RdfTerm};
use purrdf::{RdfDataset, RdfQuad, SerializeGraph, dataset_from_quads, serialize_dataset};
use sha2::{Digest, Sha256};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};
use crate::stages::profiles::{
    SliceMeta, dependency_closure, discover_slices, group_named_profiles,
};

/// Logical path of the generated VoID document.
pub const VOID_PATH: &str = "generated/metadata/void.ttl";
/// Logical path of the generated DCAT document.
pub const DCAT_PATH: &str = "generated/metadata/dcat.ttl";

const ONTOLOGY_IRI: &str = "https://blackcatinformatics.ca/gmeow";
const NAMESPACE: &str = "https://blackcatinformatics.ca/gmeow/";
const VOID_DATASET_IRI: &str = "https://blackcatinformatics.ca/gmeow/.well-known/void.ttl#dataset";
const FULL_PROFILE_IRI: &str = "https://blackcatinformatics.ca/gmeow/full";
const NAMED_PROFILE_NS: &str = "https://blackcatinformatics.ca/gmeow/profiles/";

// GTS named-graph scopes.
const GTS_GRAPH_ALIGNMENTS: &str = "https://blackcatinformatics.ca/gmeow/graph/alignments";
const GTS_GRAPH_METADATA: &str = "https://blackcatinformatics.ca/gmeow/graph/metadata";

// Vocabulary IRIs.
const OWL: &str = "http://www.w3.org/2002/07/owl#";
const RDFS: &str = "http://www.w3.org/2000/01/rdf-schema#";
const SKOS: &str = "http://www.w3.org/2004/02/skos/core#";
const DCTERMS: &str = "http://purl.org/dc/terms/";
const FOAF: &str = "http://xmlns.com/foaf/0.1/";
const GUFO: &str = "http://purl.org/nemo/gufo#";
const VOID: &str = "http://rdfs.org/ns/void#";
const DCAT: &str = "http://www.w3.org/ns/dcat#";
const XSD: &str = "http://www.w3.org/2001/XMLSchema#";

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const OWL_VERSION_INFO: &str = "http://www.w3.org/2002/07/owl#versionInfo";
const DCTERMS_DESCRIPTION: &str = "http://purl.org/dc/terms/description";
const GMEOW_AUTHORITY_LINK: &str = "https://blackcatinformatics.ca/gmeow/authorityLink";
const SKOS_EXACT_MATCH: &str = "http://www.w3.org/2004/02/skos/core#exactMatch";
const WIKIDATA_PREFIX: &str = "http://www.wikidata.org/entity/";

const CC_BY: &str = "https://creativecommons.org/licenses/by/4.0/";
const PUBLISHER: &str = "https://blackcatinformatics.ca/#bii";

const CLASS_TYPES: &[&str] = &[
    gmeow_ns::LOGIC_CLASS,
    "http://www.w3.org/2002/07/owl#Class",
    "http://www.w3.org/2000/01/rdf-schema#Class",
];
const PROPERTY_TYPES: &[&str] = &[
    gmeow_ns::LOGIC_OBJECT_PROPERTY,
    gmeow_ns::LOGIC_DATATYPE_PROPERTY,
    gmeow_ns::LOGIC_ANNOTATION_PROPERTY,
    "http://www.w3.org/2002/07/owl#ObjectProperty",
    "http://www.w3.org/2002/07/owl#DatatypeProperty",
    "http://www.w3.org/2002/07/owl#AnnotationProperty",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property",
];

/// W3C format-registry IRIs by published extension. Order matters (matches the
/// Python dict insertion order: ttl, rdf, nt, jsonld).
const FORMAT_IRI: &[(&str, &str)] = &[
    ("ttl", "http://www.w3.org/ns/formats/Turtle"),
    ("rdf", "http://www.w3.org/ns/formats/RDF_XML"),
    ("nt", "http://www.w3.org/ns/formats/N-Triples"),
    ("jsonld", "http://www.w3.org/ns/formats/JSON-LD"),
];
/// Media types by extension, same order.
const MEDIA_TYPE: &[(&str, &str)] = &[
    ("ttl", "text/turtle"),
    ("rdf", "application/rdf+xml"),
    ("nt", "application/n-triples"),
    ("jsonld", "application/ld+json"),
];

include!("metadata_targets.rs");
// The canonical, longest-first CURIE table — the ONE definition lives in the
// read-side leaf (`gmeow_bundle_view::lpg_prefixes`), whose flat-export renderers
// are its heaviest consumer.
use gmeow_bundle_view::lpg_prefixes::PREFIXES_BY_LEN;

const BANNER: &str = "# GENERATED by gmeow metadata — DO NOT EDIT.\n# https://github.com/Blackcat-Informatics/gmeow-ontology\n\n";

// ── Fold reads ───────────────────────────────────────────────────────────────

fn term_iri(t: &RdfTerm) -> Option<&str> {
    match t {
        RdfTerm::Iri(i) => Some(i),
        _ => None,
    }
}

fn graph_iri(t: &Option<RdfTerm>) -> Option<&str> {
    match t {
        Some(RdfTerm::Iri(i)) => Some(i),
        _ => None,
    }
}

/// A subject's identity key for the class/property census (IRI or blank node).
fn subject_key(t: &RdfTerm) -> String {
    match t {
        RdfTerm::Iri(i) => format!("I{i}"),
        RdfTerm::BlankNode(b) => format!("B{b}"),
        _ => format!("?{t:?}"),
    }
}

/// CURIE under the longest matching prefix (`PREFIXES_BY_LEN` is longest-first).
fn curie(iri: &str) -> String {
    for (prefix, ns) in PREFIXES_BY_LEN.iter() {
        if let Some(rest) = iri.strip_prefix(ns) {
            return format!("{prefix}:{rest}");
        }
    }
    iri.to_string()
}

/// Namespace of an IRI: split on the last `#`, else the last `/` (Python
/// `object_namespace`). If neither present, return the IRI unchanged.
fn object_namespace(iri: &str) -> String {
    for sep in ['#', '/'] {
        if let Some(pos) = iri.rfind(sep) {
            return format!("{}{sep}", &iri[..pos]);
        }
    }
    iri.to_string()
}

/// The lexical value of a literal/IRI object of `(ONTOLOGY_IRI, predicate)` in
/// the default graph (`graph_name == None`).
fn fold_header_value(
    store: &RdfDataset,
    predicate: &str,
) -> Result<Option<String>, gmeow_errors::Diag> {
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name).is_some() {
            continue; // default graph only
        }
        if term_iri(&q.subject) != Some(ONTOLOGY_IRI) || q.predicate != predicate {
            continue;
        }
        if let RdfTerm::Literal(RdfLiteral { lexical_form, .. }) = &q.object {
            return Ok(Some(lexical_form.clone()));
        }
    }
    Ok(None)
}

fn fold_version(store: &RdfDataset) -> Result<String, gmeow_errors::Diag> {
    fold_header_value(store, OWL_VERSION_INFO)?.ok_or_else(|| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("snapshot lacks owl:versionInfo on {ONTOLOGY_IRI}"),
        })
    })
}

fn fold_description(store: &RdfDataset) -> Result<String, gmeow_errors::Diag> {
    fold_header_value(store, DCTERMS_DESCRIPTION)?.ok_or_else(|| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("snapshot lacks dcterms:description on {ONTOLOGY_IRI}"),
        })
    })
}

/// Wikidata authority/exact-match links for the Work, scoped to `graph/metadata`.
fn fold_wikidata_links(store: &RdfDataset) -> Result<Vec<String>, gmeow_errors::Diag> {
    let mut links: BTreeSet<String> = BTreeSet::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name) != Some(GTS_GRAPH_METADATA) {
            continue;
        }
        if term_iri(&q.subject) != Some(ONTOLOGY_IRI) {
            continue;
        }
        if q.predicate != GMEOW_AUTHORITY_LINK && q.predicate != SKOS_EXACT_MATCH {
            continue;
        }
        if let Some(obj) = term_iri(&q.object)
            && obj.starts_with(WIKIDATA_PREFIX)
        {
            links.insert(obj.to_string());
        }
    }
    Ok(links.into_iter().collect())
}

struct VoidStats {
    triples: u64,
    classes: u64,
    properties: u64,
    entities: u64,
}

/// VoID statistics over the *default* graph (`graph_name == None`).
fn fold_stats(store: &RdfDataset) -> Result<VoidStats, gmeow_errors::Diag> {
    let mut triples: u64 = 0;
    let mut entities: BTreeSet<String> = BTreeSet::new();
    let mut classes: BTreeSet<String> = BTreeSet::new();
    let mut properties: BTreeSet<String> = BTreeSet::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name).is_some() {
            continue; // default graph only
        }
        triples += 1;
        if let Some(s) = term_iri(&q.subject)
            && s.starts_with(NAMESPACE)
        {
            entities.insert(s.to_string());
        }
        // Class/property census counts every subject (IRI *or* blank node),
        // mirroring Python `subjects_by_type` which buckets by term-id.
        if q.predicate == RDF_TYPE
            && let Some(obj) = term_iri(&q.object)
            && (CLASS_TYPES.contains(&obj) || PROPERTY_TYPES.contains(&obj))
        {
            let key = subject_key(&q.subject);
            if CLASS_TYPES.contains(&obj) {
                classes.insert(key.clone());
            } else {
                properties.insert(key);
            }
        }
    }
    Ok(VoidStats {
        triples,
        classes: classes.len() as u64,
        properties: properties.len() as u64,
        entities: entities.len() as u64,
    })
}

/// One VoID linkset row.
struct Linkset {
    iri: String,
    target_ns: String,
    predicate_iri: String,
    count: u64,
    label: String,
}

/// Linksets from the `graph/alignments` named graph: one per (target namespace,
/// predicate) pair where both predicate and object are IRIs.
fn fold_linksets(store: &RdfDataset) -> Result<Vec<Linkset>, gmeow_errors::Diag> {
    let mut buckets: BTreeMap<(String, String), u64> = BTreeMap::new();
    for q in store.owned_quads() {
        if graph_iri(&q.graph_name) != Some(GTS_GRAPH_ALIGNMENTS) {
            continue;
        }
        let Some(obj) = term_iri(&q.object) else {
            continue; // alignment axioms are IRI→IRI by construction
        };
        let target_ns = object_namespace(obj);
        *buckets.entry((target_ns, q.predicate.clone())).or_insert(0) += 1;
    }
    let mut out: Vec<Linkset> = Vec::new();
    for ((target_ns, predicate_iri), count) in buckets {
        let predicate_id = curie(&predicate_iri);
        let slug = predicate_id.replace(':', "_");
        let target_slug = {
            let trimmed = target_ns.trim_end_matches(['#', '/']);
            let last = trimmed.rsplit('/').next().unwrap_or("");
            if last.is_empty() {
                "target".to_string()
            } else {
                last.to_string()
            }
        };
        let ns_hash: String = Sha256::digest(target_ns.as_bytes())
            .iter()
            .take(3)
            .map(|b| format!("{b:02x}"))
            .collect();
        let iri = format!("{VOID_DATASET_IRI}-linkset-{target_slug}-{ns_hash}-{slug}");
        let label = format!("GMEOW {predicate_id} links to {target_ns} ({count})");
        out.push(Linkset {
            iri,
            target_ns,
            predicate_iri,
            count,
            label,
        });
    }
    Ok(out)
}

// ── Native term helpers ──────────────────────────────────────────────────────

/// Push one default-graph triple `<s> <p> o` into the output quad set.
fn add(out: &mut Vec<RdfQuad>, s: &str, p: &str, o: RdfTerm) {
    out.push(RdfQuad::new(RdfTerm::iri(s), p, o));
}

fn lit_en(s: &str) -> RdfTerm {
    RdfTerm::literal(RdfLiteral::language_tagged(s, "en"))
}

fn lit_int(n: u64) -> RdfTerm {
    RdfTerm::literal(RdfLiteral::typed(n.to_string(), format!("{XSD}integer")))
}

fn lit_str(s: &str) -> RdfTerm {
    // The old oxigraph path built `new_simple_literal`, which the Store typed as
    // `xsd:string`; the native text parser likewise types a bare literal `xsd:string`.
    // Keep the explicit datatype so the built quad matches the committed-artifact parse
    // (both serialize bare through the native turtle serializer — the redundant
    // `xsd:string` is dropped — so the committed bytes are unchanged).
    RdfTerm::literal(RdfLiteral::typed(s, format!("{XSD}string")))
}

fn iri_term(s: &str) -> RdfTerm {
    RdfTerm::iri(s)
}

// ── Graph builders ─────────────────────────────────────────────────────────────

fn build_void_quads(store: &RdfDataset) -> Result<Vec<RdfQuad>, gmeow_errors::Diag> {
    let mut out: Vec<RdfQuad> = Vec::new();
    let dataset = VOID_DATASET_IRI;

    add(
        &mut out,
        dataset,
        RDF_TYPE,
        iri_term(&format!("{VOID}Dataset")),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}title"),
        lit_en("GMEOW — Global Metadata and Entity Ontology for the Web"),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}description"),
        lit_en(&fold_description(store)?),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}license"),
        iri_term(CC_BY),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}publisher"),
        iri_term(PUBLISHER),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}creator"),
        iri_term(PUBLISHER),
    );
    add(
        &mut out,
        dataset,
        &format!("{FOAF}homepage"),
        iri_term(ONTOLOGY_IRI),
    );
    for link in fold_wikidata_links(store)? {
        add(&mut out, dataset, GMEOW_AUTHORITY_LINK, iri_term(&link));
        add(&mut out, dataset, SKOS_EXACT_MATCH, iri_term(&link));
    }
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}hasVersion"),
        lit_str(&fold_version(store)?),
    );
    add(
        &mut out,
        dataset,
        &format!("{VOID}uriSpace"),
        lit_str(NAMESPACE),
    );
    add(
        &mut out,
        dataset,
        &format!("{VOID}exampleResource"),
        iri_term(&format!("{NAMESPACE}Person")),
    );

    let stats = fold_stats(store)?;
    add(
        &mut out,
        dataset,
        &format!("{VOID}triples"),
        lit_int(stats.triples),
    );
    add(
        &mut out,
        dataset,
        &format!("{VOID}classes"),
        lit_int(stats.classes),
    );
    add(
        &mut out,
        dataset,
        &format!("{VOID}properties"),
        lit_int(stats.properties),
    );
    add(
        &mut out,
        dataset,
        &format!("{VOID}entities"),
        lit_int(stats.entities),
    );

    for (ext, fmt_iri) in FORMAT_IRI {
        add(
            &mut out,
            dataset,
            &format!("{VOID}feature"),
            iri_term(fmt_iri),
        );
        add(
            &mut out,
            dataset,
            &format!("{VOID}dataDump"),
            iri_term(&format!("{ONTOLOGY_IRI}.{ext}")),
        );
    }

    for ns in [OWL, RDFS, SKOS, DCTERMS, GUFO] {
        add(
            &mut out,
            dataset,
            &format!("{VOID}vocabulary"),
            iri_term(ns),
        );
    }
    for ns in ALIGNMENT_TARGET_NS {
        add(
            &mut out,
            dataset,
            &format!("{VOID}vocabulary"),
            iri_term(ns),
        );
    }

    for ls in fold_linksets(store)? {
        let linkset = ls.iri.as_str();
        add(
            &mut out,
            linkset,
            RDF_TYPE,
            iri_term(&format!("{VOID}Linkset")),
        );
        add(
            &mut out,
            linkset,
            &format!("{VOID}subjectsTarget"),
            iri_term(VOID_DATASET_IRI),
        );
        add(
            &mut out,
            linkset,
            &format!("{VOID}objectsTarget"),
            iri_term(&ls.target_ns),
        );
        add(
            &mut out,
            linkset,
            &format!("{VOID}linkPredicate"),
            iri_term(&ls.predicate_iri),
        );
        add(
            &mut out,
            linkset,
            &format!("{VOID}triples"),
            lit_int(ls.count),
        );
        add(
            &mut out,
            linkset,
            &format!("{RDFS}label"),
            lit_en(&ls.label),
        );
        add(
            &mut out,
            dataset,
            &format!("{VOID}subset"),
            iri_term(&ls.iri),
        );
    }

    Ok(out)
}

fn build_dcat_quads(store: &RdfDataset, root: &Path) -> Result<Vec<RdfQuad>, gmeow_errors::Diag> {
    let mut out: Vec<RdfQuad> = Vec::new();
    let dataset = ONTOLOGY_IRI;

    add(
        &mut out,
        dataset,
        RDF_TYPE,
        iri_term(&format!("{DCAT}Dataset")),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}title"),
        lit_en("GMEOW"),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}description"),
        lit_en(&fold_description(store)?),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}license"),
        iri_term(CC_BY),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}publisher"),
        iri_term(PUBLISHER),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCAT}landingPage"),
        iri_term(ONTOLOGY_IRI),
    );
    add(
        &mut out,
        dataset,
        &format!("{DCTERMS}hasVersion"),
        lit_str(&fold_version(store)?),
    );
    for link in fold_wikidata_links(store)? {
        add(&mut out, dataset, GMEOW_AUTHORITY_LINK, iri_term(&link));
        add(&mut out, dataset, SKOS_EXACT_MATCH, iri_term(&link));
    }
    for (ext, media) in MEDIA_TYPE {
        let dist = format!("{ONTOLOGY_IRI}#dist-{ext}");
        add(
            &mut out,
            &dist,
            RDF_TYPE,
            iri_term(&format!("{DCAT}Distribution")),
        );
        add(
            &mut out,
            &dist,
            &format!("{DCAT}downloadURL"),
            iri_term(&format!("{ONTOLOGY_IRI}.{ext}")),
        );
        // `xsd:string`-typed, matching the old oxigraph-built quad and the native
        // parse of the committed artifact; the native serializer drops the redundant
        // datatype, so the committed bytes stay bare.
        let media_lit = RdfTerm::literal(RdfLiteral::typed(*media, format!("{XSD}string")));
        add(&mut out, &dist, &format!("{DCAT}mediaType"), media_lit);
        add(
            &mut out,
            dataset,
            &format!("{DCAT}distribution"),
            iri_term(&dist),
        );
    }

    // Profile IRIs are datasets too.
    let slices: BTreeMap<String, SliceMeta> = discover_slices(root)?;
    let full = FULL_PROFILE_IRI;
    add(
        &mut out,
        full,
        RDF_TYPE,
        iri_term(&format!("{DCAT}Dataset")),
    );
    add(
        &mut out,
        full,
        &format!("{DCTERMS}title"),
        lit_en("GMEOW — full profile"),
    );
    add(
        &mut out,
        full,
        &format!("{DCTERMS}hasPart"),
        iri_term(ONTOLOGY_IRI),
    );
    add(
        &mut out,
        full,
        &format!("{DCAT}landingPage"),
        iri_term(FULL_PROFILE_IRI),
    );

    for (name, members) in group_named_profiles(&slices) {
        let profile_iri = format!("{NAMED_PROFILE_NS}{name}");
        let profile = profile_iri.as_str();
        let closure = dependency_closure(&name, &members, &slices)?;
        add(
            &mut out,
            profile,
            RDF_TYPE,
            iri_term(&format!("{DCAT}Dataset")),
        );
        add(
            &mut out,
            profile,
            &format!("{DCTERMS}title"),
            lit_en(&format!("GMEOW — {name} profile")),
        );
        add(
            &mut out,
            profile,
            &format!("{DCTERMS}description"),
            lit_en(&format!(
                "Slim dependency-closed profile: {} declared slice(s), {} in the import closure.",
                members.len(),
                closure.len()
            )),
        );
        add(
            &mut out,
            profile,
            &format!("{DCTERMS}isPartOf"),
            iri_term(FULL_PROFILE_IRI),
        );
        add(
            &mut out,
            profile,
            &format!("{DCAT}landingPage"),
            iri_term(&profile_iri),
        );
    }
    Ok(out)
}

/// Fold a built quad set into the frozen IR (the native twin of the old
/// `Store` + `dataset_from_store`), then serialize the default graph to Turtle
/// bytes, banner-prefixed. The quad set is blank-node-free plain triples, so the
/// statement-layer fold is a no-op and the output is byte-identical to the prior
/// oxigraph-built path.
fn serialize(quads: &[RdfQuad]) -> Result<Vec<u8>, gmeow_errors::Diag> {
    let mut buf: Vec<u8> = BANNER.as_bytes().to_vec();
    let dataset = dataset_from_quads(quads)
        .map_err(|m| gmeow_errors::Diag::of_kind(crate::error::Parse { message: m }))?;
    let body =
        serialize_dataset(&dataset, "text/turtle", SerializeGraph::DefaultGraph).map_err(|e| {
            gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: format!("turtle serialize: {e}"),
            })
        })?;
    buf.extend_from_slice(&body);
    Ok(buf)
}

/// Render the committed metadata artifacts from the same carrier dataset the
/// export leaf reads. The snapshot folds these byte projections into the generated
/// archive so the superset gate can reconstruct the committed files without adding
/// self-describing metadata graphs back into the carrier they describe.
pub(crate) fn render_metadata_from_dataset(
    root: &Path,
    store: &RdfDataset,
) -> Result<BTreeMap<String, Vec<u8>>, gmeow_errors::Diag> {
    let void = build_void_quads(store)?;
    let dcat = build_dcat_quads(store, root)?;

    let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    artifacts.insert(VOID_PATH.to_string(), serialize(&void)?);
    artifacts.insert(DCAT_PATH.to_string(), serialize(&dcat)?);
    Ok(artifacts)
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `metadata` export-leaf stage.
pub struct MetadataStage {
    consumes: Vec<String>,
}

impl MetadataStage {
    /// Construct the stage; it consumes THIS run's snapshot fold.
    pub fn new() -> Self {
        Self {
            consumes: vec!["stage-snapshot".to_string()],
        }
    }
}

impl Default for MetadataStage {
    fn default() -> Self {
        Self::new()
    }
}

impl Stage for MetadataStage {
    fn id(&self) -> &str {
        "stage-export-metadata"
    }
    fn consumes(&self) -> &[String] {
        &self.consumes
    }
    fn impl_version(&self) -> &str {
        "metadata.v2-public-en"
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        // THIS run's snapshot carrier dataset, read DIRECTLY off the product bundle —
        // no re-parse of the gmeow.gts bytes (GTS is exit-only).
        let dataset = crate::stages::carrier::snapshot_dataset(input.upstream)?;
        let store = dataset.as_ref();
        let artifacts = render_metadata_from_dataset(input.root, store)?;

        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    /// Read a `void:<key>` integer literal from the authenticated producer
    /// artifact so this semantic check never consults the materialized tree.
    fn authenticated_void_stat(dataset: &RdfDataset, key: &str) -> u64 {
        let predicate = format!("{VOID}{key}");
        let mut found: Option<u64> = None;
        for q in dataset.owned_quads() {
            if term_iri(&q.subject) != Some(VOID_DATASET_IRI) || q.predicate != predicate {
                continue;
            }
            if let RdfTerm::Literal(RdfLiteral { lexical_form, .. }) = &q.object {
                found = Some(
                    lexical_form
                        .parse()
                        .unwrap_or_else(|_| panic!("void:{key} not an integer: {lexical_form}")),
                );
            }
        }
        found.unwrap_or_else(|| panic!("authenticated void.ttl lacks void:{key} on dataset"))
    }

    #[test]
    fn authenticated_metadata_stats_are_non_zero() {
        let root = repo_root();
        let artifact =
            crate::fixture::authenticated_artifact(&root, "stage-export-metadata", VOID_PATH)
                .expect("authenticated VoID artifact; tests never produce it");
        let dataset = purrdf::parse_dataset(&artifact, "text/turtle", None)
            .expect("authenticated VoID artifact parses");
        for key in ["triples", "entities", "classes", "properties"] {
            assert!(
                authenticated_void_stat(&dataset, key) > 0,
                "authenticated void:{key} census must be non-zero"
            );
        }
    }

    #[test]
    fn metadata_census_counts_canonical_logic_typing() {
        let dataset = purrdf::parse_dataset(
            br#"@prefix logic: <https://blackcatinformatics.ca/logic/> .
                @prefix ex: <https://blackcatinformatics.ca/gmeow/test/> .
                ex:Class a logic:Class .
                ex:object a logic:ObjectProperty .
                ex:data a logic:DatatypeProperty .
                ex:annotation a logic:AnnotationProperty ."#,
            "text/turtle",
            None,
        )
        .expect("canonical logic typing fixture parses");
        let stats = fold_stats(&dataset).expect("metadata census succeeds");
        assert_eq!(stats.classes, 1);
        assert_eq!(stats.properties, 3);
    }

    #[test]
    fn authenticated_external_metadata_uses_only_public_english_tags() {
        let root = repo_root();
        for path in [VOID_PATH, DCAT_PATH] {
            let artifact =
                crate::fixture::authenticated_artifact(&root, "stage-export-metadata", path)
                    .unwrap_or_else(|error| {
                        panic!("authenticated {path}; tests never produce it: {error}")
                    });
            let dataset = purrdf::parse_dataset(&artifact, "text/turtle", None)
                .unwrap_or_else(|error| panic!("{path} parses: {error}"));
            let languages: Vec<String> = dataset
                .owned_quads()
                .filter_map(|quad| match quad.object {
                    RdfTerm::Literal(RdfLiteral { language, .. }) => language,
                    _ => None,
                })
                .collect();
            assert!(
                !languages.is_empty(),
                "{path} carries language-tagged prose"
            );
            assert!(
                languages.iter().all(|language| language == "en"),
                "{path} publishes only public English language tags: {languages:?}"
            );
            assert!(
                !String::from_utf8_lossy(&artifact).contains("@x-gmeow-"),
                "{path} must not leak internal carrier language tags"
            );
        }
    }
}
