// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `projection-ceilings` export leaf (P4/P17): the two projection-vocabulary
//! ratchet TSVs projected from the ontology-resident ceiling commitments and the
//! guarded vocabulary registry.
//!
//! The canonical ratchet data lives as individuals in the `slice-quality-rubric`
//! slice — one `gmeow:ProjectionCeilingCommitment` per committed `(slice, vocabulary)`
//! ungrounded-residue ceiling, one `gmeow:ProjectionVocabulary` per guarded
//! `logic:`-subsumable projection surface the ratchet counts against. The ratchet gate
//! reads them straight out of the ontology (via
//! [`gmeow_slice_quality::load_repo_ceilings`]); these two TSVs are their **lossy
//! projection** for humans and external tooling, never a second source of truth.
//!
//! * `generated/governance/slice-quality-projection-ceilings.tsv` — one
//!   `<slice-iri>\t<vocab-prefix>\t<count>` row per `gmeow:ProjectionCeilingCommitment`,
//!   sorted by `(slice-iri, vocab-prefix)`.
//! * `generated/governance/slice-quality-projection-vocabularies.tsv` — one
//!   `<prefix>\t<namespaces>\t<count-kind>\t<default-ceiling>\t<preservation-local>` row
//!   per `gmeow:ProjectionVocabulary`, sorted by prefix. `namespaces` is the vocab's
//!   asserted `gmeow:vocabularyNamespace` set joined by `,` (already sorted/deduped by
//!   the loader).
//!
//! Byte-deterministic and carried as opaque blob members of the bundle's
//! `generated`-fanout archive (a TSV is non-RDF, so it rides as a byte projection,
//! not a named-graph fold); the superset gate reconstructs both byte-for-byte. A
//! human RAISES a vocabulary's ceiling by editing the commitment individual in the
//! slice, never by editing these read-only projections. Emit-only; the ontology is
//! the authoring ground (Principle 17).
//!
//! **Not projected here:** the MEASURED residue and the resulting headroom are
//! empirical scan results entailed by no resident individual — projecting them as a
//! `SoundUnder` ontology projection would be a false loss judgment (a measured count
//! isn't derivable from any committed triple, it's the live counter's output). They
//! live only on the live CLI/gate path, never as a pipeline projection.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use gmeow_logic_compile::ir::PreservationKind;
use gmeow_logic_compile::loss_ledger::LossLedger;
use gmeow_logic_compile::projections::ProjectionResult;
use gmeow_slice_quality::model::GovernanceFloors;

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

/// Committed logical path of the generated per-(slice, vocabulary) ceiling projection.
pub const CEILINGS_PATH: &str = "generated/governance/slice-quality-projection-ceilings.tsv";
/// Committed logical path of the generated guarded-vocabulary registry projection.
pub const VOCABULARIES_PATH: &str =
    "generated/governance/slice-quality-projection-vocabularies.tsv";

/// The one authored source these projections are folded from: the rubric module the
/// ceiling commitments and the vocabulary registry live in. A change to it busts this
/// stage's cache.
const RUBRIC_MODULE: &str = "slices/core/slice-quality-rubric/module.ttl";

const CEILINGS_HEADER: &str = "# GENERATED by `gmeow regenerate` (projection-ceilings) — DO NOT EDIT\n# (Principle 17: the gmeow:ProjectionCeilingCommitment individuals in the\n# slice-quality-rubric slice are canonical; this TSV is their lossy projection. A\n# human LOWERS a ceiling by editing the gmeow:ProjectionCeilingCommitment individual\n# for that slice/vocabulary in the slice-quality-rubric slice and re-running\n# `make regenerate` — never by editing this read-only generated file.)\n# Format: <slice-iri>\\t<vocab-prefix>\\t<count>\n";

const VOCABULARIES_HEADER: &str = "# GENERATED by `gmeow regenerate` (projection-ceilings) — DO NOT EDIT\n# (Principle 17: the gmeow:ProjectionVocabulary individuals in the\n# slice-quality-rubric slice are canonical; this TSV is their lossy projection. A\n# human registers a new guarded vocabulary by minting a gmeow:ProjectionVocabulary\n# individual in the slice-quality-rubric slice and re-running `make regenerate` —\n# never by editing this read-only generated file.)\n# Format: <prefix>\\t<namespaces>\\t<count-kind>\\t<default-ceiling>\\t<preservation-local>\n";

/// The two loss-ledger projection targets, one per TSV.
const CEILINGS_LOSS_TARGET: &str = "projection-ceiling:ceilings";
const VOCABULARIES_LOSS_TARGET: &str = "projection-ceiling:vocabularies";

/// The local name of a `gmeow:` IRI (the part after the last `/` or `#`).
fn local(iri: &str) -> &str {
    iri.rsplit(['/', '#']).next().unwrap_or(iri)
}

/// Render the per-(slice, vocabulary) ceiling TSV: the `gmeow:ProjectionCeilingCommitment`
/// set projected to `<slice-iri>\t<vocab-prefix>\t<count>` rows, sorted by
/// `(slice-iri, vocab-prefix)`.
#[must_use]
pub fn render_ceilings(floors: &GovernanceFloors) -> String {
    let mut rows: Vec<(String, String, u64)> = floors
        .ceilings
        .iter()
        .map(|c| (c.slice.clone(), c.vocab_prefix.clone(), c.count))
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));
    let mut out = String::from(CEILINGS_HEADER);
    for (slice, prefix, count) in rows {
        out.push_str(&format!("{slice}\t{prefix}\t{count}\n"));
    }
    out
}

/// Render the guarded projection-vocabulary registry TSV: the `gmeow:ProjectionVocabulary`
/// set projected to `<prefix>\t<namespaces>\t<count-kind>\t<default-ceiling>\t<preservation-local>`
/// rows, sorted by prefix.
#[must_use]
pub fn render_vocabularies(floors: &GovernanceFloors) -> String {
    let mut rows: Vec<(String, String, &'static str, u64, String)> = floors
        .vocabularies
        .iter()
        .map(|v| {
            (
                v.prefix.clone(),
                v.namespaces.join(","),
                v.count_kind.as_local(),
                v.default_ceiling,
                local(&v.preservation).to_owned(),
            )
        })
        .collect();
    rows.sort_by(|a, b| a.0.cmp(&b.0));
    let mut out = String::from(VOCABULARIES_HEADER);
    for (prefix, namespaces, count_kind, default_ceiling, preservation) in rows {
        out.push_str(&format!(
            "{prefix}\t{namespaces}\t{count_kind}\t{default_ceiling}\t{preservation}\n"
        ));
    }
    out
}

/// Fold the two projection-ceiling projections' preservation judgments into the shared
/// projection loss ledger. Blob-free (a pure structural statement of what each TSV
/// projection drops), so the mappings stage — where the single report loss store
/// lives — folds it exactly like every sibling `lang:` / docs-format corpus.
///
/// Each TSV is a `PreservationKind::SoundUnder` (sound under-approximation): every row
/// it carries is entailed by the ontology commitment it projects, but the projection
/// drops the reified commitment's subject identity (the `gmeow:ProjectionCeilingCommitment`
/// / `gmeow:ProjectionVocabulary` individual IRI) and any annotation coat (rationale,
/// provenance) the individual carries — recorded here, never silently dropped.
pub fn fold_projection_ceilings_loss(ledger: &mut Vec<ProjectionResult>, loss: &mut LossLedger) {
    for (target, subject_kind) in [
        (CEILINGS_LOSS_TARGET, "gmeow:ProjectionCeilingCommitment"),
        (VOCABULARIES_LOSS_TARGET, "gmeow:ProjectionVocabulary"),
    ] {
        let lossy_drops = vec![
            format!(
                "the reified {subject_kind} subject identity (the individual IRI) is dropped: \
                 the TSV row carries only the projected tuple, not its reifier"
            ),
            format!(
                "the {subject_kind} annotation coat (any rationale / provenance triples on the \
                 individual) is dropped: the TSV projects only the core tuple"
            ),
        ];
        let actual_drops = vec![format!(
            "projection-ceiling projection '{target}' is a sound under-approximation: every \
             emitted row is entailed by its {subject_kind} individual; the reifier identity and \
             annotation coat are the enumerated residue (derived preservation = logic:{})",
            PreservationKind::SoundUnder.as_str(),
        )];
        loss.record_projection_drops(
            target,
            PreservationKind::SoundUnder,
            &lossy_drops,
            &actual_drops,
        );
        ledger.push(ProjectionResult {
            target: target.to_owned(),
            content: String::new(),
            is_rdf: false,
            preservation: PreservationKind::SoundUnder,
            complexity: "n/a".to_string(),
        });
    }
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `projection-ceilings` export-leaf stage.
pub struct ProjectionCeilingsStage;

impl Stage for ProjectionCeilingsStage {
    fn id(&self) -> &str {
        "stage-export-projection-ceilings"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "projection_ceilings.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<PathBuf>, gmeow_errors::Diag> {
        // The canonical ceilings + vocabulary registry live as individuals in the
        // rubric module; an edit to it (lowering a ceiling, registering a vocab)
        // busts this stage's cache and re-projects both TSVs.
        Ok(vec![root.join(RUBRIC_MODULE)])
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let floors = gmeow_slice_quality::load_repo_ceilings(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(
            CEILINGS_PATH.to_string(),
            render_ceilings(&floors).into_bytes(),
        );
        artifacts.insert(
            VOCABULARIES_PATH.to_string(),
            render_vocabularies(&floors).into_bytes(),
        );
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    #[test]
    fn ceilings_project_deterministically_from_the_ontology() {
        let root = repo_root();
        let floors = gmeow_slice_quality::load_repo_ceilings(&root).expect("load ceilings");
        let a = render_ceilings(&floors);
        let b = render_ceilings(&floors);
        assert_eq!(a, b, "ceiling projection must be deterministic");

        let data_rows: Vec<&str> = a.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(
            data_rows.len(),
            floors.ceilings.len(),
            "one data row per gmeow:ProjectionCeilingCommitment"
        );
        for row in &data_rows {
            let cols: Vec<&str> = row.split('\t').collect();
            assert_eq!(
                cols.len(),
                3,
                "ceiling row is <slice-iri>\\t<vocab-prefix>\\t<count>"
            );
        }
        // Rows are sorted by (slice-iri, vocab-prefix).
        let mut sorted = data_rows.clone();
        sorted.sort();
        assert_eq!(data_rows, sorted, "ceiling rows must be sorted");
    }

    #[test]
    fn vocabularies_project_deterministically_from_the_ontology() {
        let root = repo_root();
        let floors = gmeow_slice_quality::load_repo_ceilings(&root).expect("load ceilings");
        let a = render_vocabularies(&floors);
        let b = render_vocabularies(&floors);
        assert_eq!(a, b, "vocabulary projection must be deterministic");

        let data_rows: Vec<&str> = a.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(
            data_rows.len(),
            floors.vocabularies.len(),
            "one data row per gmeow:ProjectionVocabulary"
        );
        for row in &data_rows {
            let cols: Vec<&str> = row.split('\t').collect();
            assert_eq!(
                cols.len(),
                5,
                "vocabulary row is <prefix>\\t<namespaces>\\t<count-kind>\\t<default-ceiling>\\t<preservation-local>"
            );
        }
        // Rows are sorted by prefix.
        let mut sorted = data_rows.clone();
        sorted.sort();
        assert_eq!(data_rows, sorted, "vocabulary rows must be sorted");
    }

    #[test]
    #[ignore = "requires generated TSVs + bundle from make regenerate (stage3)"]
    fn generated_projection_ceilings_are_byte_reconstructible_from_the_bundle() {
        // The opaque-blob superset property: the shipped gmeow.gts reconstructs both
        // committed projection-ceiling TSVs byte-for-byte (they ride as REP_GENERATED
        // members), and the reconstruction equals THIS stage's fresh projection.
        let root = repo_root();
        let gts = std::fs::read(root.join("generated/dist/gmeow.gts")).expect("read bundle");
        let projection = crate::stages::superset::project_bundle(&gts).expect("project bundle");

        let floors = gmeow_slice_quality::load_repo_ceilings(&root).expect("load ceilings");
        for (path, fresh) in [
            (CEILINGS_PATH, render_ceilings(&floors)),
            (VOCABULARIES_PATH, render_vocabularies(&floors)),
        ] {
            let reconstructed = projection.files.get(path).unwrap_or_else(|| {
                panic!("{path} must reconstruct from gmeow.gts as a blob member")
            });
            assert_eq!(
                reconstructed,
                &fresh.into_bytes(),
                "{path} bundle reconstruction must equal the fresh ontology projection"
            );
            let committed = std::fs::read(root.join(path))
                .unwrap_or_else(|_| panic!("committed {path} must exist"));
            assert_eq!(
                reconstructed, &committed,
                "{path} bundle reconstruction must equal the committed bytes"
            );
        }
    }
}
