// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `references` export leaf (P4): the citation-ledger exports.
//!
//! A genuine port of the render half of `src/gmeow_tools/references.py` (no Rust
//! existed): the curated `metadata/references.ttl` ledger → CSL-JSON, BibTeX, and
//! a Markdown bibliography. (The repo-scanning *candidate discovery* writes a
//! gitignored `dist/` file and is not part of the committed outputs.)
//! Byte-deterministic; compared to `generated/references/*`.

use std::collections::BTreeMap;
use std::path::Path;
use std::sync::Arc;

use purrdf::{DatasetView, GraphMatch, RdfDataset, TermRef, TermValue, parse_dataset};
use sha2::{Digest, Sha256};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

pub const CSL_PATH: &str = "generated/references/references.csl.json";
pub const BIB_PATH: &str = "generated/references/references.bib";
pub const MD_PATH: &str = "generated/references/references.md";

const GM: &str = "https://blackcatinformatics.ca/gmeow/";
const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
const DCTERMS_ISSUED: &str = "http://purl.org/dc/terms/issued";

const BIB_BANNER: &str = "# GENERATED by gmeow references — DO NOT EDIT.\n# https://github.com/Blackcat-Informatics/gmeow-ontology\n\n";
const MD_BANNER: &str = "<!-- GENERATED by gmeow references - DO NOT EDIT. -->\n<!-- https://github.com/Blackcat-Informatics/gmeow-ontology -->\n\n";

fn parse_store(path: &Path) -> Result<Arc<RdfDataset>, gmeow_errors::Diag> {
    let bytes = std::fs::read(path)?;
    parse_dataset(&bytes, "text/turtle", None).map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("syntax error in {}: {e}", path.display()),
        })
    })
}

fn first_literal(ds: &RdfDataset, subject: &str, predicate: &str) -> String {
    let (Some(s), Some(p)) = (
        ds.term_id_by_value(&TermValue::iri(subject)),
        ds.term_id_by_value(&TermValue::iri(predicate)),
    ) else {
        return String::new();
    };
    for q in ds.quads_for_pattern(Some(s), Some(p), None, GraphMatch::Default) {
        if let TermRef::Literal { lexical, .. } = ds.resolve(q.o) {
            return lexical.to_owned();
        }
    }
    String::new()
}

fn slug(value: &str) -> String {
    // re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")[:72].strip("-") or "reference"
    let lower = value.to_lowercase();
    let mut s = String::new();
    let mut prev_dash = false;
    for ch in lower.chars() {
        if ch.is_ascii_lowercase() || ch.is_ascii_digit() {
            s.push(ch);
            prev_dash = false;
        } else if !prev_dash {
            s.push('-');
            prev_dash = true;
        }
    }
    let s = s.trim_matches('-').to_string();
    let s = if s.is_empty() {
        "reference".to_string()
    } else {
        s
    };
    let s: String = s.chars().take(72).collect();
    let s = s.trim_matches('-').to_string();
    if s.is_empty() {
        "reference".to_string()
    } else {
        s
    }
}

fn hash8(value: &str) -> String {
    let d = Sha256::digest(value.as_bytes());
    d.iter().take(4).map(|b| format!("{b:02x}")).collect()
}

/// `_reference_id`: doi.org → `doi-<slug(path)>`; else `<slug(tail|netloc)>-<hash8>`.
fn reference_id(iri: &str) -> String {
    // crude URL parse: scheme://netloc/path
    let after_scheme = iri.split_once("://").map(|x| x.1).unwrap_or(iri);
    let (netloc, path) = match after_scheme.split_once('/') {
        Some((n, p)) => (n, format!("/{p}")),
        None => (after_scheme, String::new()),
    };
    if netloc.to_lowercase() == "doi.org" {
        return format!("doi-{}", slug(path.trim_start_matches('/')));
    }
    let trimmed = iri.trim_end_matches('/');
    let tail = trimmed
        .rsplit('/')
        .next()
        .unwrap_or(trimmed)
        .rsplit('#')
        .next()
        .unwrap_or(trimmed);
    let base = if tail.is_empty() { netloc } else { tail };
    format!("{}-{}", slug(base), hash8(iri))
}

/// Cited CreativeWork subjects (objects of gmeow:citedEntity), unique, sorted by IRI.
fn cited_subjects(ds: &RdfDataset) -> Vec<String> {
    let mut set = std::collections::BTreeSet::new();
    if let Some(p) = ds.term_id_by_value(&TermValue::iri(format!("{GM}citedEntity"))) {
        for q in ds.quads_for_pattern(None, Some(p), None, GraphMatch::Default) {
            if let TermRef::Iri(n) = ds.resolve(q.o) {
                set.insert(n.to_owned());
            }
        }
    }
    set.into_iter().collect()
}

fn date_parts(value: &str) -> Option<Vec<i64>> {
    let bytes = value.as_bytes();
    let year: String = value.chars().take(4).collect();
    if year.len() != 4 || !year.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }
    let mut parts = vec![year.parse::<i64>().unwrap()];
    // -MM
    if bytes.len() >= 7 && bytes[4] == b'-' && value[5..7].chars().all(|c| c.is_ascii_digit()) {
        parts.push(value[5..7].parse().unwrap());
        if bytes.len() >= 10 && bytes[7] == b'-' && value[8..10].chars().all(|c| c.is_ascii_digit())
        {
            parts.push(value[8..10].parse().unwrap());
        }
    }
    Some(parts)
}

/// `json.dumps(s, ensure_ascii=True)` of a string (the CSL default): escape
/// non-ASCII as `\uXXXX` (astral → surrogate pair).
fn json_ascii_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c if (c as u32) < 0x7f => out.push(c),
            c => {
                let cp = c as u32;
                if cp <= 0xFFFF {
                    out.push_str(&format!("\\u{cp:04x}"));
                } else {
                    let v = cp - 0x10000;
                    let hi = 0xD800 + (v >> 10);
                    let lo = 0xDC00 + (v & 0x3FF);
                    out.push_str(&format!("\\u{hi:04x}\\u{lo:04x}"));
                }
            }
        }
    }
    out.push('"');
    out
}

/// Build CSL JSON (`json.dumps(items, indent=2, sort_keys=True)` + "\n").
fn build_csl(store: &RdfDataset) -> String {
    let mut items: Vec<String> = Vec::new();
    for iri in cited_subjects(store) {
        // (key, json-value) pairs, then sort_keys.
        let mut fields: Vec<(String, String)> = Vec::new();
        fields.push(("id".into(), json_ascii_str(&reference_id(&iri))));
        fields.push(("type".into(), json_ascii_str("webpage")));
        let title = {
            let t = first_literal(store, &iri, RDFS_LABEL);
            if t.is_empty() { iri.clone() } else { t }
        };
        fields.push(("title".into(), json_ascii_str(&title)));
        let source_location = first_literal(store, &iri, &format!("{GM}sourceLocation"));
        if !source_location.is_empty() {
            fields.push(("URL".into(), json_ascii_str(&source_location)));
        } else if iri.starts_with("http://") || iri.starts_with("https://") {
            fields.push(("URL".into(), json_ascii_str(&iri)));
        }
        if let Some(doi) = iri.strip_prefix("https://doi.org/") {
            fields.push(("DOI".into(), json_ascii_str(doi)));
        }
        let date = {
            let d = first_literal(store, &iri, &format!("{GM}datePublished"));
            if d.is_empty() {
                first_literal(store, &iri, DCTERMS_ISSUED)
            } else {
                d
            }
        };
        if let Some(parts) = date_parts(&date) {
            let inner: Vec<String> = parts.iter().map(|n| n.to_string()).collect();
            fields.push((
                "issued".into(),
                format!("{{\n        \"date-parts\": [\n          [\n            {}\n          ]\n        ]\n      }}", inner.join(",\n            ")),
            ));
        }
        let note = first_literal(store, &iri, &format!("{GM}bibliographicCitation"));
        if !note.is_empty() {
            fields.push(("note".into(), json_ascii_str(&note)));
        }
        fields.sort_by(|a, b| a.0.cmp(&b.0));
        let body: Vec<String> = fields
            .iter()
            .map(|(k, v)| format!("    {}: {}", json_ascii_str(k), v))
            .collect();
        items.push(format!("  {{\n{}\n  }}", body.join(",\n")));
    }
    if items.is_empty() {
        return "[]\n".to_string();
    }
    format!("[\n{}\n]\n", items.join(",\n"))
}

fn bibtex_escape(value: &str) -> String {
    value
        .replace('\\', "\\textbackslash{}")
        .replace('{', "\\{")
        .replace('}', "\\}")
}

fn build_bibtex(store: &RdfDataset) -> String {
    let mut entries: Vec<String> = Vec::new();
    for iri in cited_subjects(store) {
        let key = reference_id(&iri);
        let title = {
            let t = first_literal(store, &iri, RDFS_LABEL);
            if t.is_empty() { iri.clone() } else { t }
        };
        let mut fields = vec![format!("  title = {{{}}}", bibtex_escape(&title))];
        let source_location = first_literal(store, &iri, &format!("{GM}sourceLocation"));
        let url = if !source_location.is_empty() {
            source_location
        } else if iri.starts_with("http://") || iri.starts_with("https://") {
            iri.clone()
        } else {
            String::new()
        };
        if !url.is_empty() {
            fields.push(format!("  url = {{{}}}", bibtex_escape(&url)));
        }
        if let Some(doi) = iri.strip_prefix("https://doi.org/") {
            fields.push(format!("  doi = {{{}}}", bibtex_escape(doi)));
        }
        fields.push("  note = {Generated from the GMEOW citation ledger}".to_string());
        entries.push(format!("@misc{{{key},\n{}\n}}", fields.join(",\n")));
    }
    if entries.is_empty() {
        String::new()
    } else {
        entries.join("\n\n") + "\n"
    }
}

fn build_markdown(store: &RdfDataset) -> String {
    // counts: how many citedEntity triples point at each entity.
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    if let Some(p) = store.term_id_by_value(&TermValue::iri(format!("{GM}citedEntity"))) {
        for q in store.quads_for_pattern(None, Some(p), None, GraphMatch::Default) {
            if let TermRef::Iri(n) = store.resolve(q.o) {
                *counts.entry(n.to_owned()).or_default() += 1;
            }
        }
    }
    let mut lines = vec![
        "# GMEOW Citation Ledger".to_string(),
        String::new(),
        "This bibliography is generated from `metadata/references.ttl`.".to_string(),
        String::new(),
        "| Reference | Locator | Citation acts |".to_string(),
        "|---|---:|---:|".to_string(),
    ];
    for iri in cited_subjects(store) {
        let title = {
            let t = first_literal(store, &iri, RDFS_LABEL);
            if t.is_empty() { iri.clone() } else { t }
        };
        let sl = first_literal(store, &iri, &format!("{GM}sourceLocation"));
        let source_location = if sl.is_empty() { iri.clone() } else { sl };
        let locator =
            if source_location.starts_with("http://") || source_location.starts_with("https://") {
                format!("[link]({source_location})")
            } else {
                format!("`{source_location}`")
            };
        lines.push(format!(
            "| {title} | {locator} | {} |",
            counts.get(&iri).copied().unwrap_or(0)
        ));
    }
    lines.join("\n") + "\n"
}

/// Render the three reference exports from `metadata/references.ttl` under `root`.
pub fn render_references(root: &Path) -> Result<BTreeMap<String, Vec<u8>>, gmeow_errors::Diag> {
    let store = parse_store(&root.join("metadata").join("references.ttl"))?;
    let store: &RdfDataset = &store;
    let mut out: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    out.insert(CSL_PATH.to_string(), build_csl(store).into_bytes());
    out.insert(
        BIB_PATH.to_string(),
        format!("{BIB_BANNER}{}", build_bibtex(store)).into_bytes(),
    );
    out.insert(
        MD_PATH.to_string(),
        format!("{MD_BANNER}{}", build_markdown(store)).into_bytes(),
    );
    Ok(out)
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `references` export-leaf stage.
pub struct ReferencesStage;

impl Stage for ReferencesStage {
    fn id(&self) -> &str {
        "stage-export-references"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "references.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // Pure source read: the citation ledger `metadata/references.ttl` is a raw
        // NON-fold source, so declare it as a cache input — a ledger edit busts the
        // cache. The leaf consumes no upstream product (`consumes() == []`).
        Ok(vec![root.join("metadata").join("references.ttl")])
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            render_references(input.root)?,
        )))
    }
}
