// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `skos-surface` export leaf (P4): the generated SKOS concept-scheme surface
//! (AC1/R3).
//!
//! A pure projection of the lifted [`NodeKind::Annotation`] axioms: every
//! GMEOW-authored, carrier-tagged (`@x-gmeow-english`) RDFS/SKOS annotation the
//! `logic:` frontend lifts (`parse_logic_dataset`) is re-emitted as a triple on the
//! authored term, and each term is bound into ONE minted `skos:ConceptScheme`
//! individual. The surface is a pure function of the lifted axiom set (AC1
//! anti-drift): [`render_skos_surface_from_axioms`] never re-reads the source
//! triples. The materialized `generated/skos/gmeow-skos.ttl` (git-ignored) is
//! written back through the RDF-fanout writer's own serializer, so the anti-drift
//! gate compares it to this stage's render SEMANTICALLY (as a set of triples), the
//! same way the superset/fold gate compares the graph.

use std::collections::BTreeMap;
use std::path::Path;

use gmeow_errors::abox::{AboxObject, X_GMEOW_ENGLISH, abox_annotations};
use gmeow_logic_compile::ir::{LogicAxiom, NodeKind};
use purrdf::{RdfDatasetBuilder, RdfLiteral, RdfQuad, RdfTerm, SerializeGraph, serialize_dataset};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};

/// Committed logical path of the generated SKOS concept-scheme surface.
pub const SKOS_SURFACE_PATH: &str = "generated/skos/gmeow-skos.ttl";

const NS: &str = "https://blackcatinformatics.ca/gmeow/";
/// The local name of the one minted concept-scheme individual every projected term is
/// bound into; its IRI is `{NS}{SCHEME_LOCAL}`.
const SCHEME_LOCAL: &str = "GmeowConceptScheme";

const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
const SKOS_CONCEPT_SCHEME: &str = "http://www.w3.org/2004/02/skos/core#ConceptScheme";
const SKOS_IN_SCHEME: &str = "http://www.w3.org/2004/02/skos/core#inScheme";
const OWL_NAMED_INDIVIDUAL: &str = "http://www.w3.org/2002/07/owl#NamedIndividual";

const HEADER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (skos-surface):\n# a projection of the lifted NodeKind::Annotation axioms (GMEOW-authored RDFS/SKOS\n# annotations) into a SKOS concept scheme — DO NOT EDIT.\n";

/// The deterministic per-committed-path graph-identity IRI every minted individual's
/// `rdfs:isDefinedBy` carries — the same identity
/// [`crate::stages::superset::rdf_fanout_graph_iri`] derives for any RDF file under
/// `generated/`.
fn skos_surface_graph_iri() -> String {
    crate::stages::superset::rdf_fanout_graph_iri(SKOS_SURFACE_PATH)
        .expect("SKOS_SURFACE_PATH is a committed .ttl path under generated/")
}

/// A skos-surface serialization diagnostic on the unified Diag substrate.
fn parse_err(message: String) -> gmeow_errors::Diag {
    gmeow_errors::Diag::of_kind(crate::error::Parse { message })
}

/// Push the four A-Box annotation contract triples for `subject_iri` into the builder's
/// DEFAULT graph, routing through the single [`abox_annotations`] contract core (the
/// predicate set + `boxABox` box-role default live ONLY there). The contract triples
/// ride the default graph (not `annotate_builder`'s named graph) so the Turtle
/// serializer — which flattens to the default graph — reproduces them.
fn push_abox_contract(
    builder: &mut RdfDatasetBuilder,
    subject_iri: &str,
    label: &str,
    definition: &str,
    graph_iri: &str,
) {
    let subject = RdfTerm::iri(subject_iri.to_owned());
    for (predicate, object) in abox_annotations(subject_iri, label, definition, graph_iri) {
        let object_term = match object {
            AboxObject::Iri(iri) => RdfTerm::iri(iri),
            AboxObject::CarrierLiteral(value) => {
                RdfTerm::literal(RdfLiteral::language_tagged(value, X_GMEOW_ENGLISH))
            }
        };
        builder.push_owned_quad(&RdfQuad::new(subject.clone(), predicate, object_term));
    }
}

/// Render the SKOS concept-scheme surface as a PURE FUNCTION of the lifted annotation
/// axioms — the AC1 anti-drift contract. The surface is built ONLY from the passed
/// axioms (never a re-read of the source triples): one minted `skos:ConceptScheme`
/// individual carrying the full A-Box annotation contract, every annotation axiom
/// re-emitted as a carrier-tagged triple on its authored subject, and one
/// `skos:inScheme` binding per subject.
pub fn render_skos_surface_from_axioms(
    annotations: &[LogicAxiom],
) -> Result<String, gmeow_errors::Diag> {
    let graph_iri = skos_surface_graph_iri();
    let scheme_iri = format!("{NS}{SCHEME_LOCAL}");
    let mut builder = RdfDatasetBuilder::new();

    // The one minted concept-scheme individual. Typed (so the structural lint holds it
    // to the A-Box contract, which it satisfies); the projected terms below stay
    // UNTYPED so the lint's per-term contract checks never fire on them.
    let scheme = RdfTerm::iri(scheme_iri.clone());
    builder.push_owned_quad(&RdfQuad::new(
        scheme.clone(),
        RDF_TYPE,
        RdfTerm::iri(SKOS_CONCEPT_SCHEME.to_owned()),
    ));
    builder.push_owned_quad(&RdfQuad::new(
        scheme.clone(),
        RDF_TYPE,
        RdfTerm::iri(OWL_NAMED_INDIVIDUAL.to_owned()),
    ));
    push_abox_contract(
        &mut builder,
        &scheme_iri,
        "GMEOW Concept Scheme",
        "The generated SKOS concept scheme projecting every GMEOW-authored term's lifted RDFS/SKOS annotations.",
        &graph_iri,
    );

    // Group the annotation axioms by subject (BTreeMap → deterministic subject order,
    // one `skos:inScheme` binding per subject).
    let mut by_subject: BTreeMap<&str, Vec<&LogicAxiom>> = BTreeMap::new();
    for axiom in annotations {
        by_subject
            .entry(axiom.subject.as_str())
            .or_default()
            .push(axiom);
    }
    for (subject, axioms) in &by_subject {
        let subject_term = RdfTerm::iri((*subject).to_owned());
        for axiom in axioms {
            // The six `ANNOTATION_LIFT_PREDS` are all literal-range predicates, so every
            // `NodeKind::Annotation` axiom must carry a literal object. Assert it rather than
            // silently rendering a future non-literal annotation as a language-tagged literal.
            debug_assert!(
                axiom.obj_is_literal,
                "NodeKind::Annotation axiom on {subject} ({}) must be literal-valued",
                axiom.predicate
            );
            builder.push_owned_quad(&RdfQuad::new(
                subject_term.clone(),
                axiom.predicate.clone(),
                RdfTerm::literal(RdfLiteral::language_tagged(
                    axiom.obj.clone(),
                    X_GMEOW_ENGLISH,
                )),
            ));
        }
        builder.push_owned_quad(&RdfQuad::new(
            subject_term.clone(),
            SKOS_IN_SCHEME,
            scheme.clone(),
        ));
    }

    let dataset = builder
        .freeze()
        .map_err(|e| parse_err(format!("skos-surface: freeze failed: {e}")))?;
    // All projected quads live in the default graph → `SerializeGraph::DefaultGraph` is
    // faithful. Every row of this surface is an independent one-line triple (all
    // IRIs/literals, no blank nodes or `;`/`,` grouping), so we can canonicalize the
    // serializer's output by sorting its rows.
    let bytes = serialize_dataset(
        dataset.as_ref(),
        "text/turtle",
        SerializeGraph::DefaultGraph,
    )
    .map_err(|e| parse_err(format!("skos-surface: serialize failed: {e}")))?;
    let raw = String::from_utf8(bytes)
        .map_err(|e| parse_err(format!("skos-surface: non-UTF8 serialization: {e}")))?;
    // purrdf 0.8.x's parallel de-dup serializer does NOT pin its row order across runs
    // (the order varies with thread scheduling under load). Partition the `@prefix`/
    // `@base` directives from the triple rows and sort each block bytewise so this
    // stage's direct render is a reproducible, byte-stable artifact regardless of thread
    // timing. (The materialized `generated/skos/gmeow-skos.ttl` rides the RDF-fanout
    // writer's own serializer, so the anti-drift gate compares the two SEMANTICALLY —
    // see `skos_surface_matches_the_materialized_projection` — but a stable direct render
    // keeps this producer deterministic in its own right.)
    let mut directives: Vec<&str> = Vec::new();
    let mut triples: Vec<&str> = Vec::new();
    for line in raw.lines() {
        let line = line.trim_end();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('@') || line.starts_with("PREFIX ") || line.starts_with("BASE ") {
            directives.push(line);
        } else {
            triples.push(line);
        }
    }
    directives.sort_unstable();
    triples.sort_unstable();
    let mut body = String::new();
    for directive in &directives {
        body.push_str(directive);
        body.push('\n');
    }
    if !directives.is_empty() && !triples.is_empty() {
        body.push('\n');
    }
    for triple in &triples {
        body.push_str(triple);
        body.push('\n');
    }
    Ok(format!("{HEADER}{body}"))
}

/// Render the SKOS concept-scheme surface for the authored corpus at `root`: load the
/// full authored dataset, lift its RDFS/SKOS annotations into `NodeKind::Annotation`
/// axioms via the `logic:` frontend, then project through the pure
/// [`render_skos_surface_from_axioms`].
pub fn render_skos_surface(root: &Path) -> Result<String, gmeow_errors::Diag> {
    let dataset = crate::stages::source_load::load_authored_dataset(root)?;
    let (program, _diags) =
        gmeow_logic_compile::frontend::parse_logic_dataset(dataset.as_ref(), None)
            .map_err(|e| parse_err(format!("skos-surface: logic lift failed: {e}")))?;
    let mut annotations: Vec<LogicAxiom> = program
        .axioms
        .iter()
        .filter(|a| a.node_kind == NodeKind::Annotation)
        .cloned()
        .collect();
    annotations.sort_by_key(LogicAxiom::sort_key);
    render_skos_surface_from_axioms(&annotations)
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `skos-surface` export-leaf stage.
pub struct SkosSurfaceStage;

impl Stage for SkosSurfaceStage {
    fn id(&self) -> &str {
        "stage-export-skos-surface"
    }
    fn consumes(&self) -> &[String] {
        &[]
    }
    fn impl_version(&self) -> &str {
        "skos_surface.v1"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // The RDFS/SKOS annotations this leaf lifts ARE in the fold's authored default
        // graph; declaring the SAME authored sources (root ontology + slice modules) as
        // cache inputs keeps `consumes() == []` while busting the cache on any authored
        // annotation change (mirrors `frame_shapes`).
        let mut files = vec![root.join("ontology").join("gmeow.ttl")];
        files.extend(crate::stages::source_load::module_files(root)?);
        Ok(files)
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let ttl = render_skos_surface(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(SKOS_SURFACE_PATH.to_string(), ttl.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts(
            self.id(),
            artifacts,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gmeow_logic_compile::ir::ContextualScope;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    #[test]
    fn skos_surface_matches_the_materialized_projection() {
        use std::collections::BTreeSet;

        use purrdf::{DatasetView, GraphMatch};

        // `generated/skos/gmeow-skos.ttl` is a git-ignored, pipeline-materialized product:
        // this stage builds the named-graph CONTENT via `render_skos_surface`, and the
        // materializer (the RDF-fanout writer / bundle serializer) writes it back through
        // purrdf's canonical serializer. purrdf 0.8.x's parallel de-dup serializer does not
        // pin its concrete Turtle/N-Triples surface (prefixing, grouping, and row order vary
        // with thread scheduling), so a byte comparison is not the invariant — the invariant
        // is that the materialized surface carries EXACTLY the triples this stage projects
        // from the lifted RDFS/SKOS annotation axioms. Assert set-of-triples equality (the
        // real anti-drift check; the superset/fold gate likewise compares this graph
        // semantically). The surface has no blank nodes, so a resolved-term string key is a
        // stable identity.
        let root = repo_root();
        let fresh = render_skos_surface(&root).expect("render");
        let committed = std::fs::read_to_string(root.join(SKOS_SURFACE_PATH))
            .expect("materialized generated/skos/gmeow-skos.ttl (run `make check` first)");
        let triple_keys = |ttl: &str| -> BTreeSet<String> {
            let dataset = purrdf::parse_dataset(ttl.as_bytes(), "text/turtle", None)
                .expect("skos surface parses as valid Turtle");
            // The resolved-term Debug carries the full identity (IRI string, or literal
            // lexical + datatype + language tag) and is stable for the IRI/literal-only
            // surface — no blank-node scopes to differ between the two parses.
            dataset
                .quads_for_pattern(None, None, None, GraphMatch::Any)
                .map(|q| {
                    format!(
                        "{:?}\t{:?}\t{:?}",
                        dataset.resolve(q.s),
                        dataset.resolve(q.p),
                        dataset.resolve(q.o)
                    )
                })
                .collect()
        };
        let fresh_keys = triple_keys(&fresh);
        let committed_keys = triple_keys(&committed);
        assert_eq!(
            fresh_keys,
            committed_keys,
            "gmeow-skos.ttl drifted from the lifted-axiom projection \
             ({} freshly-rendered triples vs {} materialized triples)",
            fresh_keys.len(),
            committed_keys.len()
        );
    }

    /// Shift-left: drive the SAME native structural lint `make validate`/`make check`
    /// runs over this generator's real output, so a missing/incorrect A-Box annotation
    /// on the minted concept-scheme individual reds HERE (a fast `cargo nextest`) rather
    /// than only at the next expensive gate (mirrors
    /// `frame_shapes::tests::minted_shapes_satisfy_the_assertional_abox_contract`).
    #[test]
    fn skos_surface_lint_green() {
        use gmeow_validate::lint::{
            LintConfig, default_annotation_predicates, structural_lint_dataset,
        };

        let root = repo_root();
        let ttl = render_skos_surface(&root).expect("render");
        // The real bundle supplies `gmeow:boxABox a gmeow:GraphBoxRole` from the kernel
        // slice; add it here so the graphBoxRole-typing check has its declaration to
        // resolve against. Self-describe it (`rdfs:isDefinedBy <ns>self`) so the bare
        // role individual is exempt from the per-term contract (as the kernel definition
        // is), keeping the whole report clean.
        let doc = format!(
            "{ttl}\n<{NS}boxABox> a <{NS}GraphBoxRole> ; \
             <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <{NS}self> .\n"
        );
        let native = purrdf::parse_dataset(doc.as_bytes(), "text/turtle", None)
            .expect("parse skos-surface into native dataset");

        let cfg = LintConfig {
            namespace: NS.to_string(),
            ontology_iri: NS.trim_end_matches('/').to_string(),
            selector_tokens: Default::default(),
            core_slice_iris: Default::default(),
            annotation_predicates: default_annotation_predicates().into_iter().collect(),
        };
        let report = structural_lint_dataset(&native, &cfg);
        assert!(
            report.errors().is_empty(),
            "the generated SKOS surface must be structural-lint-clean: {:?}",
            report.errors()
        );
    }

    #[test]
    fn skos_surface_non_vacuous() {
        // A stable, GMEOW-authored `skos:definition` (gmeow:Agreement) must survive the
        // lift → projection round-trip into the rendered surface.
        let root = repo_root();
        let ttl = render_skos_surface(&root).expect("render");
        assert!(
            ttl.contains("mutual understanding between two or more agents"),
            "a known GMEOW term's skos:definition must appear in the rendered surface"
        );
    }

    /// AC1 anti-drift (the load-bearing test): the renderer is a PURE FUNCTION of the
    /// lifted axiom set, NOT a raw source re-read. An injected sentinel definition — a
    /// string that appears in NO source file — must reach the rendered output when it is
    /// passed as a `NodeKind::Annotation` axiom, proving the surface is built from the
    /// axioms it is handed.
    #[test]
    fn skos_surface_renders_from_lifted_axioms() {
        let sentinel = "ZZZ_INJECTED_SENTINEL_DEFINITION";
        let injected = vec![
            LogicAxiom::new(
                format!("{NS}InjectedSentinelTerm"),
                "http://www.w3.org/2004/02/skos/core#definition",
                sentinel,
                true,  // obj_is_literal
                false, // negated
                ContextualScope::default(),
            )
            .expect("valid axiom")
            .with_node_kind(NodeKind::Annotation),
        ];
        let ttl = render_skos_surface_from_axioms(&injected).expect("render from axioms");
        assert!(
            ttl.contains(sentinel),
            "the renderer must consume the passed axiom set (AC1 anti-drift): {ttl}"
        );
    }
}
