// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `statements` stage (#861 P3): compile `dsl/statements/*.ttl` into the OWL
//! axiom-annotation downcast + the RDF 1.2 lead artifact.
//!
//! This re-cuts `src/gmeow_tools/statement_compile.py` as an in-memory Rust
//! stage. The statement DSL is authored as plain Turtle (rdflib cannot parse
//! RDF 1.2 triple terms), so it parses with oxigraph; each
//! `gmeow:StatementMetadata` cell is a 1:1 transcription of one reifying
//! statement (a quoted base triple + the annotations on its reifier). The OWL
//! form reuses the reifier IRI as the named `owl:Axiom` node; the RDF 1.2 lead
//! is materialized from it by the SAME pure-Rust codec the Python called
//! (`gmeow_rdf::statements::project_owl_to_rdf12`, #667). Outputs are compared by
//! graph isomorphism, never bytes, so serialization formatting is immaterial.

use std::collections::BTreeMap;
use std::path::Path;

use oxigraph::io::{RdfFormat, RdfParser};
use oxigraph::model::{NamedNode, Term};
use oxigraph::store::Store;
use sha1::{Digest as Sha1Digest, Sha1};

use crate::error::PipelineError;
use crate::node::{Stage, StageInput, StageKind, StageOutput, StageProduct};

const GMEOW: &str = "https://blackcatinformatics.ca/gmeow/";
const OWL: &str = "http://www.w3.org/2002/07/owl#";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// Committed logical path of the OWL downcast.
pub const OWL_PATH: &str = "generated/statements/gmeow-statements.owl.ttl";
/// Committed logical path of the RDF 1.2 lead artifact.
pub const RDF12_PATH: &str = "generated/statements/gmeow.rdf12.ttl";

const OWL_BANNER: &str = "# GENERATED by `gmeow regenerate` (statements) from dsl/statements/ — DO NOT EDIT.\n# OWL 2 axiom-annotation downcast of GMEOW's canonical RDF 1.2 statement metadata.\n";
const RDF12_BANNER: &str = "# RDF 1.2 / RDF* — GMEOW's canonical statement-level model, the lead serialization.\n# Generated natively by `gmeow regenerate` (statements) from dsl/statements/.\n# DO NOT EDIT — author in dsl/statements/.\n";

/// A quoted base triple `<<( s p o )>>` of a reified statement.
struct QuotedTriple {
    subject: NamedNode,
    predicate: NamedNode,
    object: Term,
}

/// One reified statement: quoted triple + reifier + sorted annotations.
struct StatementCell {
    reifier: NamedNode,
    triple: QuotedTriple,
    /// `(annProperty, annValue)` pairs, sorted by `(prop, value-n3)`.
    annotations: Vec<(NamedNode, Term)>,
}

/// Compile the statement DSL under `root` into `(owl_ttl, rdf12_ttl)`, both
/// banner-prefixed. The OWL form is the axiom-annotation downcast; the RDF 1.2
/// form is materialized from it by the native codec.
pub fn compile_statements(root: &Path) -> Result<(String, String), PipelineError> {
    let store = parse_statement_dsl(root)?;
    let mut cells = extract_cells(&store)?;
    // Deterministic: by reifier IRI.
    cells.sort_by(|a, b| a.reifier.as_str().cmp(b.reifier.as_str()));

    let owl_ntriples = emit_owl(&cells);
    let rdf12 = gmeow_rdf::statements::project_owl_to_rdf12(&owl_ntriples).map_err(|e| {
        PipelineError::Stage {
            stage: "stage-statements".to_string(),
            message: format!("OWL → RDF 1.2 projection failed: {e}"),
        }
    })?;

    let owl_out = format!("{OWL_BANNER}{}\n", owl_ntriples.trim_end());
    let rdf12_out = format!("{RDF12_BANNER}{}\n", rdf12.trim_end());
    Ok((owl_out, rdf12_out))
}

/// Parse every `dsl/statements/*.ttl` into one lenient oxigraph store.
fn parse_statement_dsl(root: &Path) -> Result<Store, PipelineError> {
    let dir = root.join("dsl").join("statements");
    let store =
        Store::new().map_err(|e| PipelineError::Parse(format!("store creation failed: {e}")))?;
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(&dir)?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "ttl"))
        .collect();
    files.sort();
    for path in files {
        let bytes = std::fs::read(&path)?;
        for quad in RdfParser::from_format(RdfFormat::Turtle)
            .lenient()
            .for_reader(bytes.as_slice())
        {
            let quad = quad.map_err(|e| {
                PipelineError::Parse(format!("syntax error in {}: {e}", path.display()))
            })?;
            store
                .insert(&quad)
                .map_err(|e| PipelineError::Parse(format!("store insert failed: {e}")))?;
        }
    }
    Ok(store)
}

/// Extract every `gmeow:StatementMetadata` cell from the store.
fn extract_cells(store: &Store) -> Result<Vec<StatementCell>, PipelineError> {
    let rdf_type = nn(RDF_TYPE)?;
    let cell_class = nn(&format!("{GMEOW}StatementMetadata"))?;
    let mut cells = Vec::new();
    for quad in store.quads_for_pattern(
        None,
        Some(rdf_type.as_ref()),
        Some((&cell_class).into()),
        None,
    ) {
        let quad = quad.map_err(|e| PipelineError::Parse(e.to_string()))?;
        let oxigraph::model::NamedOrBlankNode::NamedNode(cell) = &quad.subject else {
            return Err(PipelineError::Parse(
                "statement metadata cell must be a named IRI".to_string(),
            ));
        };
        cells.push(parse_cell(store, cell)?);
    }
    Ok(cells)
}

fn parse_cell(store: &Store, cell: &NamedNode) -> Result<StatementCell, PipelineError> {
    let subject = single_named(store, cell, &format!("{GMEOW}qSubject"))?
        .ok_or_else(|| cell_err(cell, "missing an IRI qSubject"))?;
    let predicate = single_named(store, cell, &format!("{GMEOW}qPredicate"))?
        .ok_or_else(|| cell_err(cell, "missing an IRI qPredicate"))?;
    let obj_iri = single_object(store, cell, &format!("{GMEOW}qObject"))?;
    let obj_lit = single_object(store, cell, &format!("{GMEOW}qObjectLiteral"))?;
    let object = match (obj_iri, obj_lit) {
        (Some(o), None) | (None, Some(o)) => o,
        _ => {
            return Err(cell_err(
                cell,
                "needs exactly one of qObject / qObjectLiteral",
            ))
        }
    };
    let triple = QuotedTriple {
        subject,
        predicate,
        object,
    };
    let reifier = match single_named(store, cell, &format!("{GMEOW}reifier"))? {
        Some(r) => r,
        None => mint_reifier(&triple)?,
    };
    let mut annotations = parse_annotations(store, cell)?;
    annotations.sort_by(|a, b| (a.0.as_str(), term_n3(&a.1)).cmp(&(b.0.as_str(), term_n3(&b.1))));
    Ok(StatementCell {
        reifier,
        triple,
        annotations,
    })
}

fn parse_annotations(
    store: &Store,
    cell: &NamedNode,
) -> Result<Vec<(NamedNode, Term)>, PipelineError> {
    let ann_pred = nn(&format!("{GMEOW}annotation"))?;
    let mut out = Vec::new();
    for quad in store.quads_for_pattern(Some(cell.into()), Some(ann_pred.as_ref()), None, None) {
        let quad = quad.map_err(|e| PipelineError::Parse(e.to_string()))?;
        // The annotation node is a blank node (the [ ... ] cell).
        let ann_subj: oxigraph::model::NamedOrBlankNode = match quad.object {
            Term::NamedNode(n) => n.into(),
            Term::BlankNode(b) => b.into(),
            _ => return Err(cell_err(cell, "annotation must be a node")),
        };
        let prop = single_named_of(store, &ann_subj, &format!("{GMEOW}annProperty"))?
            .ok_or_else(|| cell_err(cell, "annotation missing an IRI annProperty"))?;
        let value = single_object_of(store, &ann_subj, &format!("{GMEOW}annValue"))?
            .ok_or_else(|| cell_err(cell, "annotation missing annValue"))?;
        out.push((prop, value));
    }
    Ok(out)
}

/// Emit the OWL axiom-annotation form as N-Triples (a Turtle subset), sorted.
fn emit_owl(cells: &[StatementCell]) -> String {
    let mut lines: Vec<String> = Vec::new();
    for cell in cells {
        let s = cell.triple.subject.to_string();
        let p = cell.triple.predicate.to_string();
        let o = cell.triple.object.to_string();
        let ax = cell.reifier.to_string();
        lines.push(format!("{s} {p} {o} ."));
        lines.push(format!("{ax} <{RDF_TYPE}> <{OWL}Axiom> ."));
        lines.push(format!("{ax} <{OWL}annotatedSource> {s} ."));
        lines.push(format!("{ax} <{OWL}annotatedProperty> {p} ."));
        lines.push(format!("{ax} <{OWL}annotatedTarget> {o} ."));
        for (prop, value) in &cell.annotations {
            lines.push(format!("{ax} {} {} .", prop, value));
        }
    }
    lines.sort();
    lines.dedup();
    lines.join("\n")
}

/// Mint a deterministic reifier IRI: `sha1(n3(s) " " n3(p) " " n3(o))`. Mirrors
/// the Python `mint_reifier` so an unauthored reifier is stable across compiles.
fn mint_reifier(triple: &QuotedTriple) -> Result<NamedNode, PipelineError> {
    let s = Term::from(triple.subject.clone());
    let p = Term::from(triple.predicate.clone());
    let o = term_n3(&triple.object);
    let canonical = format!("{s} {p} {o}");
    let digest = hex_lower(&Sha1::digest(canonical.as_bytes()));
    nn(&format!("{GMEOW}reifier/{digest}"))
}

// ── small oxigraph helpers (mirror loader.rs idioms) ─────────────────────────

fn nn(iri: &str) -> Result<NamedNode, PipelineError> {
    NamedNode::new(iri).map_err(|e| PipelineError::Parse(format!("invalid IRI {iri}: {e}")))
}

fn single_object(
    store: &Store,
    subject: &NamedNode,
    predicate: &str,
) -> Result<Option<Term>, PipelineError> {
    single_object_of(store, &subject.clone().into(), predicate)
}

fn single_object_of(
    store: &Store,
    subject: &oxigraph::model::NamedOrBlankNode,
    predicate: &str,
) -> Result<Option<Term>, PipelineError> {
    let p = nn(predicate)?;
    let mut objs: Vec<Term> = Vec::new();
    for quad in store.quads_for_pattern(Some(subject.as_ref()), Some(p.as_ref()), None, None) {
        let quad = quad.map_err(|e| PipelineError::Parse(e.to_string()))?;
        objs.push(quad.object);
    }
    if objs.len() > 1 {
        return Err(PipelineError::Parse(format!(
            "{subject} has {} values for {predicate} — expected one",
            objs.len()
        )));
    }
    Ok(objs.into_iter().next())
}

fn single_named(
    store: &Store,
    subject: &NamedNode,
    predicate: &str,
) -> Result<Option<NamedNode>, PipelineError> {
    single_named_of(store, &subject.clone().into(), predicate)
}

fn single_named_of(
    store: &Store,
    subject: &oxigraph::model::NamedOrBlankNode,
    predicate: &str,
) -> Result<Option<NamedNode>, PipelineError> {
    match single_object_of(store, subject, predicate)? {
        Some(Term::NamedNode(n)) => Ok(Some(n)),
        Some(_) => Err(PipelineError::Parse(format!(
            "{subject} {predicate} must be an IRI"
        ))),
        None => Ok(None),
    }
}

/// An N3-style serialization of a term for content hashing (IRIs as `<iri>`,
/// literals as `"lex"`, `"lex"@lang`, or `"lex"^^<dt>`). oxigraph's `Term`
/// Display already produces this N-Triples form.
fn term_n3(term: &Term) -> String {
    term.to_string()
}

fn cell_err(cell: &NamedNode, msg: &str) -> PipelineError {
    PipelineError::Parse(format!("statement {cell} {msg}"))
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `statements` pipeline stage.
pub struct StatementsStage;

impl Stage for StatementsStage {
    fn id(&self) -> &str {
        "stage-statements"
    }
    fn kind(&self) -> StageKind {
        StageKind::Transform
    }
    fn consumes(&self) -> &[String] {
        // Declared empty: the compiler reads dsl/statements/ from the root. The
        // dogfooded DAG wires it after source-load; the consumes-agreement check
        // is reconciled when source-load publishes the loaded dataset (P3 wiring).
        &[]
    }
    fn impl_version(&self) -> &str {
        "statements.v1"
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, PipelineError> {
        let (owl, rdf12) = compile_statements(input.root)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(OWL_PATH.to_string(), owl.into_bytes());
        artifacts.insert(RDF12_PATH.to_string(), rdf12.into_bytes());
        Ok(StageOutput {
            product: StageProduct::from_artifacts(self.id(), artifacts),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The repo root (two levels up from crates/pipeline).
    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .canonicalize()
            .unwrap()
    }

    /// Parse Turtle into a sorted set of N-Triples lines (blank-node-free graphs
    /// only — the statement artifacts have no blanks, so set equality == graph
    /// isomorphism).
    fn triple_set(ttl: &str) -> std::collections::BTreeSet<String> {
        let store = Store::new().unwrap();
        for quad in RdfParser::from_format(RdfFormat::Turtle)
            .lenient()
            .for_reader(ttl.as_bytes())
        {
            store.insert(&quad.unwrap()).unwrap();
        }
        store
            .iter()
            .map(|q| {
                let q = q.unwrap();
                format!("{} {} {} .", q.subject, q.predicate, q.object)
            })
            .collect()
    }

    #[test]
    fn statements_owl_is_isomorphic_to_committed() {
        let root = repo_root();
        let (owl, rdf12) = compile_statements(&root).expect("compile");

        // OWL downcast: triple-set equality with the committed file.
        let committed_owl = std::fs::read_to_string(root.join(OWL_PATH)).expect("committed owl");
        assert_eq!(
            triple_set(&owl),
            triple_set(&committed_owl),
            "fresh OWL downcast must be isomorphic to committed gmeow-statements.owl.ttl"
        );

        // RDF 1.2 lead: normalize BOTH back to OWL (the codec rdflib can't parse
        // RDF 1.2 directly) and compare the normalized triple sets.
        let committed_rdf12 =
            std::fs::read_to_string(root.join(RDF12_PATH)).expect("committed rdf12");
        let fresh_norm = gmeow_rdf::statements::normalize_rdf12_to_owl(&rdf12).expect("norm fresh");
        let committed_norm = gmeow_rdf::statements::normalize_rdf12_to_owl(&committed_rdf12)
            .expect("norm committed");
        assert_eq!(
            triple_set(&fresh_norm),
            triple_set(&committed_norm),
            "fresh RDF 1.2 lead must round-trip-isomorphic to committed gmeow.rdf12.ttl"
        );
    }
}
