// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The `statements` stage (P3): compile `dsl/statements/*.ttl` into the OWL
//! axiom-annotation downcast + the RDF 1.2 lead artifact.
//!
//! This is the native Rust statement compiler stage. The statement DSL is
//! authored as plain Turtle (rdflib cannot parse RDF 1.2 triple terms), so it
//! parses through the native `purrdf` codecs into a frozen [`RdfDataset`]; each
//! `gmeow:StatementMetadata` cell is a 1:1 transcription of one reifying
//! statement (a quoted base triple + the annotations on its reifier). The OWL
//! form reuses the reifier IRI as the named `owl:Axiom` node; the RDF 1.2 lead
//! is materialized from it by the SAME pure-Rust codec the Python called
//! (`purrdf::statements::project_owl_to_rdf12`). Outputs are compared by
//! graph isomorphism, never bytes, so serialization formatting is immaterial.
//!
//! The stage also renders the statement layer's JSON-LD-family surface — the
//! JSON-LD-star + YAML-LD-star projections of the SAME frozen dataset — onto the
//! INTERNAL [`RDF12_JSONLD_PATH`] / [`RDF12_YAMLLD_PATH`] lane. They are not committed
//! files: their shipping channel is the bundle's `yaml-ld-archive` frame, which
//! `stage-archive-blobs` tars off this product. The frame rides UNPRIMED: the claim
//! dictionary that once selected it did not pay for its own in-band bytes.
//!
//! oxigraph-free. Every parse routes through `purrdf::parse_dataset`
//! and merges via `RdfDataset::union`; the invariant + lossless checks call the
//! native `gmeow_validate::statement::*_dataset` twins (the `Store`-based functions
//! stay for the PyO3 surface). The cell/annotation queries use the native
//! `DatasetView` (id-keyed pattern lookups + borrowed `TermRef`s).

use std::collections::BTreeMap;
use std::path::Path;
use std::sync::Arc;

use purrdf::{DatasetView, GraphMatch, RdfDataset, TermRef, TermValue};
use sha1::{Digest as Sha1Digest, Sha1};

use crate::node::{Stage, StageInput, StageOutput, StageProduct};
use crate::stages::source_load::turtle_bytes_to_dataset;

const GMEOW: &str = "https://blackcatinformatics.ca/gmeow/";
const OWL: &str = "http://www.w3.org/2002/07/owl#";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// Committed logical path of the OWL downcast.
///
/// BYTE-DECORATED RDF: the committed file carries [`OWL_BANNER`], which is not graph
/// data, so it cannot reconstruct from a canonical named-graph fold and travels as a
/// byte projection. It rides
/// [`REP_STATEMENTS`](crate::stages::archive_blobs::REP_STATEMENTS) — the claim
/// corpus's own rep, which rides the dictionary-less medium — while the queryable
/// statement semantics keep riding the `graph/statements` named graph.
pub const OWL_PATH: &str = "generated/statements/gmeow-statements.owl.ttl";
/// Committed logical path of the RDF 1.2 lead artifact. Byte-decorated with
/// [`RDF12_BANNER`] and carried exactly as [`OWL_PATH`] is, for the same reason.
pub const RDF12_PATH: &str = "generated/statements/gmeow.rdf12.ttl";

/// INTERNAL logical path of the JSON-LD-star projection of the statement layer.
///
/// Under the `pipeline/` prefix, so the post-run reconcile passes it between stages
/// without writing a committed file (`crate::run`): its shipping channel is the
/// bundle's `yaml-ld-archive` frame, not a `generated/` file. A second on-disk copy
/// would oblige the superset gate to reconstruct bytes the bundle already carries,
/// exactly as the trained dictionaries' `pipeline/medium/` family avoids.
pub const RDF12_JSONLD_PATH: &str = "pipeline/statements/gmeow.rdf12.jsonld";
/// INTERNAL logical path of the YAML-LD-star projection of the statement layer
/// (see [`RDF12_JSONLD_PATH`] for why it is not a committed output).
pub const RDF12_YAMLLD_PATH: &str = "pipeline/statements/gmeow.rdf12.yamlld";

const OWL_BANNER: &str = "# GENERATED by `gmeow-dev sync --mode update --outputs generated` (statements) from dsl/statements/ — DO NOT EDIT.\n# OWL 2 axiom-annotation downcast of GMEOW's canonical RDF 1.2 statement metadata.\n";
const RDF12_BANNER: &str = "# RDF 1.2 / RDF* — GMEOW's canonical statement-level model, the lead serialization.\n# Generated natively by `gmeow-dev sync --mode update --outputs generated` (statements) from dsl/statements/.\n# DO NOT EDIT — author in dsl/statements/.\n";

/// An IRI in term position — the oxigraph-free replacement for
/// `oxigraph::model::NamedNode`. `Display` renders the N-Triples `<iri>` form (the
/// same form `NamedNode`'s `Display` produced, which `emit_owl` depends on).
#[derive(Clone, PartialEq, Eq)]
struct Iri(String);

impl Iri {
    fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for Iri {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "<{}>", self.0)
    }
}

/// An RDF object term — the oxigraph-free replacement for `oxigraph::model::Term` in
/// object position. `Display` renders the N-Triples form (`<iri>`, `"lex"`,
/// `"lex"@lang`, `"lex"^^<dt>`), byte-identical to the oxigraph `Term` `Display`
/// `emit_owl` and the reifier mint relied on.
#[derive(Clone, PartialEq, Eq)]
enum ObjTerm {
    Iri(String),
    Literal {
        lexical: String,
        datatype: String,
        language: Option<String>,
    },
}

impl std::fmt::Display for ObjTerm {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ObjTerm::Iri(iri) => write!(f, "<{iri}>"),
            ObjTerm::Literal {
                lexical,
                datatype,
                language,
            } => {
                let escaped = escape_literal(lexical);
                match language {
                    Some(lang) => write!(f, "\"{escaped}\"@{lang}"),
                    None if datatype == "http://www.w3.org/2001/XMLSchema#string" => {
                        // oxigraph `Term` Display omits the `^^xsd:string` datatype
                        // for a plain string literal — match that exactly.
                        write!(f, "\"{escaped}\"")
                    }
                    None => write!(f, "\"{escaped}\"^^<{datatype}>"),
                }
            }
        }
    }
}

/// Escape a literal lexical form for the N-Triples quoted-string Display.
fn escape_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

/// A quoted base triple `<<( s p o )>>` of a reified statement.
#[derive(Clone)]
struct QuotedTriple {
    subject: Iri,
    predicate: Iri,
    object: ObjTerm,
}

/// One reified statement: quoted triple + reifier + sorted annotations.
struct StatementCell {
    reifier: Iri,
    triple: QuotedTriple,
    /// `(annProperty, annValue)` pairs, sorted by `(prop, value-n3)`.
    annotations: Vec<(Iri, ObjTerm)>,
}

/// Compile the statement DSL under `root` into `(owl_ttl, rdf12_ttl)`, both
/// banner-prefixed. The OWL form is the axiom-annotation downcast; the RDF 1.2
/// form is materialized from it by the native codec.
pub fn compile_statements(root: &Path) -> Result<(String, String), gmeow_errors::Diag> {
    let store = parse_statement_dsl(root)?;
    let mut cells = extract_cells(&store)?;
    // Deterministic: by reifier IRI.
    cells.sort_by(|a, b| a.reifier.as_str().cmp(b.reifier.as_str()));

    let owl_ntriples = emit_owl(&cells);
    let rdf12 = purrdf::statements::project_owl_to_rdf12(&owl_ntriples).map_err(|e| {
        gmeow_errors::Diag::of_kind(crate::error::StageFailed {
            stage: "stage-statements".to_string(),
            message: format!("OWL → RDF 1.2 projection failed: {e}"),
        })
    })?;

    let owl_out = format!("{OWL_BANNER}{}\n", owl_ntriples.trim_end());
    let rdf12_out = format!("{RDF12_BANNER}{}\n", rdf12.trim_end());
    Ok((owl_out, rdf12_out))
}

/// Compile statement artifacts and fold their diagnostics into the native report.
///
/// This is the Rust-owned implementation behind the Python feedback surface:
/// Python supplies the already-loaded ontology graph as N-Triples, but parsing,
/// statement compilation, invariant checking, RDF 1.2 normalization, lossless
/// comparison, and compile-error reporting all happen here.
pub fn compile_diagnostics_report(root: &Path, ontology_nt: &str) -> gmeow_errors::Report {
    let mut report = gmeow_errors::Report::new("statement-compile");
    let (owl_ttl, rdf12_ttl) = match compile_statements(root) {
        Ok(artifacts) => artifacts,
        Err(err) => {
            add_dsl_error(&mut report, err.to_string());
            return report;
        }
    };

    match invariant_findings(&owl_ttl, ontology_nt) {
        Ok(findings) => {
            for finding in findings {
                report.add_finding(finding);
            }
        }
        Err(err) => {
            add_dsl_error(&mut report, err.to_string());
            return report;
        }
    }

    let normalized_owl = match purrdf::statements::normalize_rdf12_to_owl(&rdf12_ttl) {
        Ok(normalized) => normalized,
        Err(err) => {
            add_dsl_error(&mut report, format!("RDF 1.2 normalization failed: {err}"));
            return report;
        }
    };

    match lossless_findings(&owl_ttl, &normalized_owl) {
        Ok(findings) => {
            for finding in findings {
                report.add_finding(finding);
            }
        }
        Err(err) => add_dsl_error(&mut report, err.to_string()),
    }
    report
}

fn add_dsl_error(report: &mut gmeow_errors::Report, message: String) {
    report.add_finding(
        gmeow_errors::Finding::new(
            gmeow_errors::Severity::Error,
            "statement-compile.dsl-error",
            message,
        )
        .with_tool("statement-compile"),
    );
}

fn invariant_findings(
    statement_owl_ttl: &str,
    ontology_nt: &str,
) -> Result<Vec<gmeow_errors::Finding>, gmeow_errors::Diag> {
    // Union the emitted OWL (Turtle) with the ontology (N-Triples) in one default-graph
    // native dataset — the exact union the Store version built by inserting both into one
    // store — then run the native invariant twin over it.
    let owl = turtle_bytes_to_dataset(statement_owl_ttl.as_bytes(), "statement OWL")?;
    let ontology = crate::stages::source_load::rdf_bytes_to_dataset(
        ontology_nt.as_bytes(),
        "application/n-triples",
        "ontology N-Triples",
    )?;
    let ds = RdfDataset::union(&[owl.as_ref(), ontology.as_ref()]);
    Ok(gmeow_validate::statement::check_statement_invariants_dataset(&ds))
}

fn lossless_findings(
    authored_owl_ttl: &str,
    normalized_owl_ttl: &str,
) -> Result<Vec<gmeow_errors::Finding>, gmeow_errors::Diag> {
    let authored = turtle_bytes_to_dataset(authored_owl_ttl.as_bytes(), "authored OWL")?;
    let normalized = turtle_bytes_to_dataset(normalized_owl_ttl.as_bytes(), "normalized OWL")?;
    Ok(gmeow_validate::statement::check_statement_lossless_dataset(
        &authored,
        &normalized,
    ))
}

/// The sorted `dsl/statements/*.ttl` source files (the leaf's raw inputs — folded
/// into the cache key via `input_files` so a DSL edit busts the cache).
pub fn statement_dsl_files(root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
    let dir = root.join("dsl").join("statements");
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut files: Vec<std::path::PathBuf> = Vec::new();
    // Fail-fast on a read_dir entry error: a transient FS error must surface, not
    // silently drop a DSL file (no-optionality).
    for entry in std::fs::read_dir(&dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|x| x == "ttl") {
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

/// Parse every `dsl/statements/*.ttl` into one frozen native dataset.
///
/// Each file is parsed standalone and the per-file datasets are merged via
/// [`RdfDataset::union`], which standardizes blank scopes apart per input — the native
/// twin of the old per-source blank-prefix scoping (annotation cells use anonymous
/// blanks that restart at `_:gts_0` each parse, so distinct DSL files must not merge
/// them).
fn parse_statement_dsl(root: &Path) -> Result<Arc<RdfDataset>, gmeow_errors::Diag> {
    let mut parsed: Vec<Arc<RdfDataset>> = Vec::new();
    for path in statement_dsl_files(root)? {
        let bytes = std::fs::read(&path)?;
        let dataset = turtle_bytes_to_dataset(&bytes, &path.display().to_string())?;
        parsed.push(dataset);
    }
    let refs: Vec<&RdfDataset> = parsed.iter().map(|d| d.as_ref()).collect();
    Ok(Arc::new(RdfDataset::union(&refs)))
}

/// Extract every `gmeow:StatementMetadata` cell from the dataset.
fn extract_cells(ds: &RdfDataset) -> Result<Vec<StatementCell>, gmeow_errors::Diag> {
    let mut cells = Vec::new();
    let (Some(type_id), Some(class_id)) = (
        ds.term_id_by_value(&TermValue::iri(RDF_TYPE)),
        ds.term_id_by_value(&TermValue::iri(format!("{GMEOW}StatementMetadata"))),
    ) else {
        return Ok(cells);
    };
    for q in ds.quads_for_pattern(None, Some(type_id), Some(class_id), GraphMatch::Default) {
        let TermRef::Iri(cell) = ds.resolve(q.s) else {
            return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
                message: "statement metadata cell must be a named IRI".to_string(),
            }));
        };
        let cell = Iri(cell.to_owned());
        cells.extend(parse_cell(ds, &cell)?);
    }
    Ok(cells)
}

/// Parse one `gmeow:StatementMetadata` cell into one StatementCell per reifier.
///
/// RDF 1.2 permits several reifiers per statement: one proposition (the quoted
/// base triple) may be put forward by several claim tokens. Each authored
/// `gmeow:reifier` becomes its own `owl:Axiom` node reifying the shared triple
/// and carrying the cell's annotations; a cell with no authored reifier mints a
/// single deterministic one. The base triple and annotations are parsed once and
/// cloned per reifier.
fn parse_cell(ds: &RdfDataset, cell: &Iri) -> Result<Vec<StatementCell>, gmeow_errors::Diag> {
    let cell_id = ds
        .term_id_by_value(&TermValue::iri(cell.as_str()))
        .ok_or_else(|| cell_err(cell, "metadata cell IRI vanished from dataset"))?;
    let subject = single_named(ds, cell_id, cell, &format!("{GMEOW}qSubject"))?
        .ok_or_else(|| cell_err(cell, "missing an IRI qSubject"))?;
    let predicate = single_named(ds, cell_id, cell, &format!("{GMEOW}qPredicate"))?
        .ok_or_else(|| cell_err(cell, "missing an IRI qPredicate"))?;
    let obj_iri = single_object(ds, cell_id, cell, &format!("{GMEOW}qObject"))?;
    let obj_lit = single_object(ds, cell_id, cell, &format!("{GMEOW}qObjectLiteral"))?;
    let object = match (obj_iri, obj_lit) {
        (Some(o), None) | (None, Some(o)) => o,
        _ => {
            return Err(cell_err(
                cell,
                "needs exactly one of qObject / qObjectLiteral",
            ));
        }
    };
    let triple = QuotedTriple {
        subject,
        predicate,
        object,
    };
    let mut reifiers = all_named(ds, cell_id, cell, &format!("{GMEOW}reifier"))?;
    if reifiers.is_empty() {
        reifiers.push(mint_reifier(&triple)?);
    }
    // Deterministic across reifiers within a cell.
    reifiers.sort_by(|a, b| a.as_str().cmp(b.as_str()));
    reifiers.dedup();
    let mut annotations = parse_annotations(ds, cell_id, cell)?;
    annotations.sort_by(|a, b| (a.0.as_str(), term_n3(&a.1)).cmp(&(b.0.as_str(), term_n3(&b.1))));
    Ok(reifiers
        .into_iter()
        .map(|reifier| StatementCell {
            reifier,
            triple: triple.clone(),
            annotations: annotations.clone(),
        })
        .collect())
}

fn parse_annotations(
    ds: &RdfDataset,
    cell_id: purrdf::TermId,
    cell: &Iri,
) -> Result<Vec<(Iri, ObjTerm)>, gmeow_errors::Diag> {
    let Some(ann_pred_id) = ds.term_id_by_value(&TermValue::iri(format!("{GMEOW}annotation")))
    else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    // Materialize the annotation-node ids first so the borrow of `ds` from the pattern
    // iterator ends before the per-node sub-queries (which also borrow `ds`).
    let ann_node_ids: Vec<purrdf::TermId> = ds
        .quads_for_pattern(Some(cell_id), Some(ann_pred_id), None, GraphMatch::Default)
        .map(|q| q.o)
        .collect();
    for ann_id in ann_node_ids {
        // The annotation node is an IRI or a blank node (the `[ ... ]` cell).
        match ds.resolve(ann_id) {
            TermRef::Iri(_) | TermRef::Blank { .. } => {}
            _ => return Err(cell_err(cell, "annotation must be a node")),
        }
        let prop = single_named(ds, ann_id, cell, &format!("{GMEOW}annProperty"))?
            .ok_or_else(|| cell_err(cell, "annotation missing an IRI annProperty"))?;
        let value = single_object(ds, ann_id, cell, &format!("{GMEOW}annValue"))?
            .ok_or_else(|| cell_err(cell, "annotation missing annValue"))?;
        out.push((prop, value));
    }
    Ok(out)
}

/// Emit the OWL axiom-annotation form as N-Triples (a Turtle subset), sorted.
fn emit_owl(cells: &[StatementCell]) -> String {
    let mut lines: Vec<String> = Vec::new();
    for cell in cells {
        let s = cell.triple.subject.to_string();
        let p = cell.triple.predicate.to_string();
        let o = cell.triple.object.to_string();
        let ax = cell.reifier.to_string();
        lines.push(format!("{s} {p} {o} ."));
        lines.push(format!("{ax} <{RDF_TYPE}> <{OWL}Axiom> ."));
        lines.push(format!("{ax} <{OWL}annotatedSource> {s} ."));
        lines.push(format!("{ax} <{OWL}annotatedProperty> {p} ."));
        lines.push(format!("{ax} <{OWL}annotatedTarget> {o} ."));
        for (prop, value) in &cell.annotations {
            lines.push(format!("{ax} {} {} .", prop, value));
        }
    }
    lines.sort();
    lines.dedup();
    lines.join("\n")
}

/// Mint a deterministic reifier IRI: `sha1(n3(s) " " n3(p) " " n3(o))`. Mirrors
/// the Python `mint_reifier` so an unauthored reifier is stable across compiles. The
/// `Display` of [`Iri`]/[`ObjTerm`] reproduces the oxigraph `Term` N-Triples form the
/// old `mint_reifier` hashed, keeping minted IRIs byte-identical across the cutover.
fn mint_reifier(triple: &QuotedTriple) -> Result<Iri, gmeow_errors::Diag> {
    let s = triple.subject.to_string();
    let p = triple.predicate.to_string();
    let o = term_n3(&triple.object);
    let canonical = format!("{s} {p} {o}");
    let digest = hex_lower(&Sha1::digest(canonical.as_bytes()));
    Ok(Iri(format!("{GMEOW}reifier/{digest}")))
}

// ── small native query helpers (mirror crates/slice/src/rdf_query.rs idioms) ──

/// The native object term at `(subject_id, predicate, ?)`, materialized as an owned
/// [`ObjTerm`] if it is an IRI or literal. Blank/triple-term objects map to `None`
/// here (no statement field accepts them; the callers below either require an IRI or
/// a literal/IRI value).
fn resolve_obj(ds: &RdfDataset, id: purrdf::TermId) -> Option<ObjTerm> {
    match ds.resolve(id) {
        TermRef::Iri(iri) => Some(ObjTerm::Iri(iri.to_owned())),
        TermRef::Literal {
            lexical,
            datatype,
            language,
            ..
        } => {
            let dt = match ds.resolve(datatype) {
                TermRef::Iri(iri) => iri.to_owned(),
                other => format!("{other:?}"),
            };
            Some(ObjTerm::Literal {
                lexical: lexical.to_owned(),
                datatype: dt,
                language: language.map(str::to_owned),
            })
        }
        TermRef::Blank { .. } | TermRef::Triple { .. } => None,
    }
}

/// The single object of `(subject_id, predicate, ?)` (IRI or literal), or `None` if
/// absent. More than one value is a hard error (no silent pick).
fn single_object(
    ds: &RdfDataset,
    subject_id: purrdf::TermId,
    subject: &Iri,
    predicate: &str,
) -> Result<Option<ObjTerm>, gmeow_errors::Diag> {
    let Some(p_id) = ds.term_id_by_value(&TermValue::iri(predicate)) else {
        return Ok(None);
    };
    let obj_ids: Vec<purrdf::TermId> = ds
        .quads_for_pattern(Some(subject_id), Some(p_id), None, GraphMatch::Default)
        .map(|q| q.o)
        .collect();
    if obj_ids.len() > 1 {
        return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!(
                "{subject} has {} values for {predicate} — expected one",
                obj_ids.len()
            ),
        }));
    }
    match obj_ids.into_iter().next() {
        Some(id) => resolve_obj(ds, id).map(Some).ok_or_else(|| {
            // A blank-node / triple-term value where an IRI or literal was expected.
            cell_err(
                subject,
                &format!("{predicate} value must be an IRI or literal"),
            )
        }),
        None => Ok(None),
    }
}

/// The single IRI value of `(subject_id, predicate, ?)`, or `None` if absent. A
/// non-IRI value is a hard error.
fn single_named(
    ds: &RdfDataset,
    subject_id: purrdf::TermId,
    subject: &Iri,
    predicate: &str,
) -> Result<Option<Iri>, gmeow_errors::Diag> {
    match single_object(ds, subject_id, subject, predicate)? {
        Some(ObjTerm::Iri(iri)) => Ok(Some(Iri(iri))),
        Some(_) => Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
            message: format!("{subject} {predicate} must be an IRI"),
        })),
        None => Ok(None),
    }
}

/// Every IRI value of `predicate` on `subject` (for multi-valued properties such
/// as `gmeow:reifier`, where RDF 1.2 allows several reifiers per statement). A
/// non-IRI value is a hard error (no silent skip).
fn all_named(
    ds: &RdfDataset,
    subject_id: purrdf::TermId,
    subject: &Iri,
    predicate: &str,
) -> Result<Vec<Iri>, gmeow_errors::Diag> {
    let Some(p_id) = ds.term_id_by_value(&TermValue::iri(predicate)) else {
        return Ok(Vec::new());
    };
    let obj_ids: Vec<purrdf::TermId> = ds
        .quads_for_pattern(Some(subject_id), Some(p_id), None, GraphMatch::Default)
        .map(|q| q.o)
        .collect();
    let mut out: Vec<Iri> = Vec::new();
    for id in obj_ids {
        match ds.resolve(id) {
            TermRef::Iri(iri) => out.push(Iri(iri.to_owned())),
            _ => {
                return Err(gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: format!("{subject} {predicate} must be an IRI"),
                }));
            }
        }
    }
    Ok(out)
}

/// An N3-style serialization of a term for content hashing (IRIs as `<iri>`,
/// literals as `"lex"`, `"lex"@lang`, or `"lex"^^<dt>`) — the [`ObjTerm`] `Display`
/// reproduces the oxigraph `Term` N-Triples form byte-for-byte.
fn term_n3(term: &ObjTerm) -> String {
    term.to_string()
}

fn cell_err(cell: &Iri, msg: &str) -> gmeow_errors::Diag {
    gmeow_errors::Diag::of_kind(crate::error::Parse {
        message: format!("statement {cell} {msg}"),
    })
}

fn hex_lower(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

// ── Stage impl ───────────────────────────────────────────────────────────────

/// The `statements` pipeline stage.
pub struct StatementsStage;

impl Stage for StatementsStage {
    fn id(&self) -> &str {
        "stage-statements"
    }
    fn consumes(&self) -> &[String] {
        // Declared empty: the compiler reads dsl/statements/ from the root. The
        // dogfooded DAG wires it after source-load; the consumes-agreement check
        // is reconciled when source-load publishes the loaded dataset (P3 wiring).
        &[]
    }
    fn impl_version(&self) -> &str {
        // v2: the statement layer's JSON-LD-star / YAML-LD-star projections join the
        // product on the INTERNAL `pipeline/statements/` lane, so `stage-archive-blobs`
        // folds them into the bundle's `yaml-ld-archive` frame without a second render.
        "statements.v2"
    }
    fn input_files(&self, root: &Path) -> Result<Vec<std::path::PathBuf>, gmeow_errors::Diag> {
        // Raw source read: the RDF-1.2 statement cells come from `dsl/statements/`,
        // which no upstream product reflects. Declare them so a DSL edit busts the
        // cache. `consumes() == []` (the leaf reads sources, not upstream products).
        statement_dsl_files(root)
    }
    fn run(&self, input: StageInput<'_>) -> Result<StageOutput, gmeow_errors::Diag> {
        let (owl, rdf12) = compile_statements(input.root)?;
        // Carry the RDF 1.2 statement layer as the bundle's frozen dataset (the
        // contribution `gts_compose` unions over the base graph). Parsing the rdf12
        // Turtle folds the statement layer — `rdf:reifies` triple-term objects become
        // reifier bindings and the reifiers' other triples become annotations — so
        // the side-tables ride in the dataset, not flattened into base quads. The
        // OWL_PATH / RDF12_PATH byte lanes are kept for the pre-C3 byte readers.
        let dataset =
            purrdf::parse_dataset(rdf12.as_bytes(), "text/turtle", None).map_err(|e| {
                gmeow_errors::Diag::of_kind(crate::error::Parse {
                    message: format!("RDF 1.2 statement-layer parse: {e}"),
                })
            })?;
        // The claim corpus's JSON-LD-family surface, rendered ONCE here (the
        // transform-once razor) from the SAME frozen statement dataset the Turtle lead
        // parsed into — never re-derived downstream, and never from the committed file,
        // which is not flushed until the post-run reconcile returns. `stage-archive-blobs`
        // tars these two into the bundle's `yaml-ld-archive` frame, the frame
        // that rides unprimed: a JSON-LD-family consumer reads the reified
        // statement layer directly, in the syntax whose distinguishing repeated substrings
        // (the reifier IRIs, the `gmeow:qSubject`/`qPredicate`/`qObject` coat, the
        // standpoint qualifiers) are exactly what that dictionary is trained on.
        let jsonld = crate::stages::yaml_ld::serialize_graph(dataset.as_ref())?;
        let yamlld = crate::stages::yaml_ld::serialize_graph_yaml(dataset.as_ref(), None)?;
        let mut artifacts: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        artifacts.insert(OWL_PATH.to_string(), owl.into_bytes());
        artifacts.insert(RDF12_PATH.to_string(), rdf12.into_bytes());
        artifacts.insert(RDF12_JSONLD_PATH.to_string(), jsonld.into_bytes());
        artifacts.insert(RDF12_YAMLLD_PATH.to_string(), yamlld.into_bytes());
        Ok(StageOutput::new(StageProduct::from_artifacts_over(
            self.id(),
            dataset,
            artifacts,
        )))
    }
}
