"""GMEOW models — slice GMEOW Affect Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/affect
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class AestheticQualityEnum(StrEnum):
    qualityElegance = "gmeow:qualityElegance"
    qualityKitsch = "gmeow:qualityKitsch"
    qualitySublimity = "gmeow:qualitySublimity"


class AffectFunctionEnum(StrEnum):
    fnAffectiveIntensity = "gmeow:fnAffectiveIntensity"
    fnArgmax = "gmeow:fnArgmax"


class AppraisalDimensionEnum(StrEnum):
    dimensionAgency = "gmeow:dimensionAgency"
    dimensionCertainty = "gmeow:dimensionCertainty"
    dimensionCoping = "gmeow:dimensionCoping"
    dimensionGoalCongruence = "gmeow:dimensionGoalCongruence"
    dimensionGoalRelevance = "gmeow:dimensionGoalRelevance"
    dimensionNormCompatibility = "gmeow:dimensionNormCompatibility"
    dimensionNovelty = "gmeow:dimensionNovelty"
    dimensionObjectFocus = "gmeow:dimensionObjectFocus"
    dimensionTemporalOrientation = "gmeow:dimensionTemporalOrientation"


class CoreAffectDimensionEnum(StrEnum):
    dimensionArousal = "gmeow:dimensionArousal"
    dimensionDominance = "gmeow:dimensionDominance"
    dimensionUnpredictability = "gmeow:dimensionUnpredictability"
    dimensionValence = "gmeow:dimensionValence"


class DimensionFamilyEnum(StrEnum):
    familyAppraisal = "gmeow:familyAppraisal"
    familyCoreAffect = "gmeow:familyCoreAffect"


class EmotionTypeEnum(StrEnum):
    emotionAnger = "gmeow:emotionAnger"
    emotionAnticipation = "gmeow:emotionAnticipation"
    emotionDisgust = "gmeow:emotionDisgust"
    emotionFear = "gmeow:emotionFear"
    emotionJoy = "gmeow:emotionJoy"
    emotionSadness = "gmeow:emotionSadness"
    emotionSaudade = "gmeow:emotionSaudade"
    emotionSchadenfreude = "gmeow:emotionSchadenfreude"
    emotionSurprise = "gmeow:emotionSurprise"
    emotionTrust = "gmeow:emotionTrust"


class LabelSetDecisionRuleEnum(StrEnum):
    decisionArgmax = "gmeow:decisionArgmax"
    decisionIndependentThreshold = "gmeow:decisionIndependentThreshold"


class ScalePolarityEnum(StrEnum):
    polarityBipolar = "gmeow:polarityBipolar"
    polarityUnipolar = "gmeow:polarityUnipolar"


class ScoreSemanticsEnum(StrEnum):
    scoreCalibratedProbability = "gmeow:scoreCalibratedProbability"
    scoreEntailment = "gmeow:scoreEntailment"
    scoreLogit = "gmeow:scoreLogit"
    scoreMargin = "gmeow:scoreMargin"
    scoreSigmoid = "gmeow:scoreSigmoid"
    scoreSoftmax = "gmeow:scoreSoftmax"


class WeightingPolicyEnum(StrEnum):
    weightingEqualCoreAffect = "gmeow:weightingEqualCoreAffect"
    weightingValenceDominant = "gmeow:weightingValenceDominant"


class AffectClassifierLabel(ConfiguredBaseModel):
    """Affect Classifier Label.

    The exact, lossless external identity of a label emitted by a classifier or dataset
    label set (GoEmotions joy, SST-2 NEGATIVE, CardiffNLP Positive). An information
    artifact, NEVER a gmeow:EmotionType: labels live under their own per-registry authority
    (gmeow-goemotions:, gmeow-hf:) so a model label can never be mistaken for a canonical
    emotion. 'NEG', 'Negative', 'LABEL_0' are distinct identities until a reviewed
    correspondence maps them (Principle 5). The reviewed skos:closeMatch/exactMatch link to
    a canonical GMEOW term is a generated correspondence lowering, authored separately.

    When to use:
        - Use to register the exact identity of an external classifier/dataset label, preserved
          losslessly and kept distinct from canonical GMEOW emotion vocabulary.

    When to avoid:
        - Avoid typing a classifier label as a gmeow:EmotionType (that is a category error, and
          'neutral' as an EmotionType is a hard fail) and avoid asserting an unreviewed exactMatch
          to a canonical term (closeMatch by default).

    How to use:
        - Register each external label as a gmeow:AffectClassifierLabel individual under its
          per-registry prefix, bind it to its gmeow:AffectLabelSet via gmeow:memberOfLabelSet, and
          map it to canonical GMEOW terms only through a reviewed correspondence lowering.

    Examples:
        - gmeow-goemotions:joy a gmeow:AffectClassifierLabel ; gmeow:memberOfLabelSet
          gmeow-labelset:GoEmotions .

    Usage:
        >>> from gmeow_models.affect import AffectClassifierLabel
        >>> AffectClassifierLabel.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectClassifierLabel'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectClassifierLabel
    CURIE:  gmeow:AffectClassifierLabel

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectClassifierLabel", "curie": "gmeow:AffectClassifierLabel", "definitionDigest": "blake3:6f2a0e1b88a01ecacfc17a4a09563c38baff3744d993965f17fcb85e721b288e", "iri": "https://blackcatinformatics.ca/gmeow/AffectClassifierLabel"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    memberOfLabelSet: list[str] = Field(min_length=1, description="Binds a gmeow:AffectClassifierLabel to the gmeow:AffectLabelSet it belongs to (GoEmotions, Ekman-7, SST-2, CardiffNLP). Mandatory on a label (SHACL): an unregistered label fails canonical projection.", alias="gmeow:memberOfLabelSet")


class AffectClassifierOutput(ConfiguredBaseModel):
    """Affect Classifier Output.

    One emitted model output over one target span — a model-vantage gmeow:Observation
    carrying the emitted label (gmeow:emittedLabel), raw score (gmeow:classifierScore),
    score semantics (gmeow:scoreSemantics), and threshold (gmeow:thresholdApplied), produced
    by a gmeow:ModelInferenceRun (gmeow:producedBy). It is EVIDENCE, not the human-level
    claim and not an inner-state truth: 'this model, at this revision, over this span,
    emitted this label with this score under this label set'. A raw sigmoid/softmax score is
    logic:evidenceStrength/probability under declared calibration, NEVER logic:confidence.
    It supports a gmeow:AffectiveClaim by gmeow:supportsAffectiveClaim (an evidence link,
    never entailment).

    When to use:
        - Use for one classifier output over one target — attributed model evidence with score and
          provenance, never a privileged truth about inner affect.

    When to avoid:
        - Avoid asserting an inner affect directly from an output (it must support a
          gmeow:AffectiveClaim, never entail one) and avoid storing its score as logic:confidence
          without calibration metadata (a raw score is not a calibrated probability — a hard
          fail).

    How to use:
        - Record each model output as a gmeow:AffectClassifierOutput linked to its
          gmeow:ModelInferenceRun (gmeow:producedBy), its target (gmeow:classifiedTarget), its
          emitted label, raw score, and score semantics; link it to a richer claim via
          gmeow:supportsAffectiveClaim.

    Examples:
        - ex:out a gmeow:AffectClassifierOutput ; gmeow:producedBy ex:run ; gmeow:emittedLabel
          gmeow-goemotions:joy ; gmeow:classifierScore 0.84 ; gmeow:scoreSemantics
          gmeow:scoreSigmoid .

    Usage:
        >>> from gmeow_models.affect import AffectClassifierOutput
        >>> AffectClassifierOutput.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectClassifierOutput'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectClassifierOutput
    CURIE:  gmeow:AffectClassifierOutput

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectClassifierOutput", "curie": "gmeow:AffectClassifierOutput", "definitionDigest": "blake3:95a50b103e8827164ea4c89116db84844947406aeea5b5eaf977dad342a5d07a", "iri": "https://blackcatinformatics.ca/gmeow/AffectClassifierOutput"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    classifiedTarget: list[str] = Field(min_length=1, description="The target span a classifier output was emitted over — the chunk/text/segment classified (⊑ gmeow:observedFeature, the observation-spine bridge). Range intentionally open. Mandatory on an output (SHACL): an output with no target is unmoored evidence.", alias="gmeow:classifiedTarget")
    classifierScore: list[float] = Field(min_length=1, description="The raw score a classifier emitted for its label. Its MEANING is fixed by gmeow:scoreSemantics (sigmoid/softmax/logit/…), never assumed: a raw score is logic:evidenceStrength/probability, and only a CALIBRATED probability may be read as confidence. Mandatory on an output (SHACL).", alias="gmeow:classifierScore")
    emittedLabel: list[str] = Field(min_length=1, description="The exact external gmeow:AffectClassifierLabel a classifier output emitted — its lossless label identity (gmeow-goemotions:joy, gmeow-hf:sst2Negative). Mandatory on an output (SHACL); the label MUST be registered in a gmeow:AffectLabelSet or canonical projection fails.", alias="gmeow:emittedLabel")
    producedBy: list[str] = Field(min_length=1, description="The gmeow:ModelInferenceRun that produced a classifier output — its provenance handle (PROV-O prov:wasGeneratedBy by generated correspondence). Mandatory and functional (SHACL): one output, one run.", alias="gmeow:producedBy")
    scoreSemantics: list[ScoreSemanticsEnum] = Field(description="What a gmeow:classifierScore MEANS — a sigmoid score, softmax probability, calibrated probability, logit, or margin (open gmeow:ScoreSemantics vocab). Mandatory on an output (SHACL): a bare number with no declared semantics is uninterpretable.", alias="gmeow:scoreSemantics")


class Emotion(ConfiguredBaseModel):
    """Emotion.

    An emotion as an intrinsic affective mode inhering in one agent, grafted under
    gmeow:AffectiveMoment ⊑ gmeow:MentalMoment — the kernel agent-mental-life family,
    sibling to teleology's gmeow:IntentionalMode (the Desire/Intention grounding). Episodic
    temporal scope rides validFrom/validUntil on the statement; the felt-episode and mood
    surfaces are part of the fuller model in design/AFFECT-DESIGN.md. Whether an emotion is
    self-reported or attributed is the vantage axis of the claims about it; self-report is
    top authority for the subject's own standpoint.

    Usage:
        >>> from gmeow_models.affect import Emotion
        >>> Emotion.model_config["json_schema_extra"]["curie"]
        'gmeow:Emotion'

    IRI:    https://blackcatinformatics.ca/gmeow/Emotion
    CURIE:  gmeow:Emotion

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Emotion", "curie": "gmeow:Emotion", "definitionDigest": "blake3:5250579c36ef1ef2605ab6e10afe526194de77dc94b66fa37c0e0cdfde8f3fea", "iri": "https://blackcatinformatics.ca/gmeow/Emotion"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    emotionBearer: Any = Field(description="The agent in whom this emotion inheres. Functional and mandatory (SHACL): an intrinsic mode has exactly one bearer (the intentBearer pattern).", alias="gmeow:emotionBearer")
    emotionType: list[Any] = Field(min_length=1, description="The kind(s) of this emotion. NOT functional: blended emotions carry several types, and classifications from different traditions coexist (Principle 9). At least one (SHACL); open vocabulary (sh:nodeKind sh:IRI, never sh:in).", alias="gmeow:emotionType")


class AffectComposite(Emotion):
    """Affect Composite.

    A named emotion whose meaning is given by a DECLARED composition — a core-affect vector
    bound by relations to its elicitor, target, agency attribution, norm, and, where
    relevant, other emotions — rather than left as an unanalyzed primitive. GMEOW models up:
    schadenfreude and saudade are structure over the foundational axes and relations, not
    new primitive EmotionTypes. A composite MUST carry its decomposition via
    gmeow:affectiveConstituent (SHACL); if a quality cannot be decomposed into the current
    axes, that is evidence the axis basis is incomplete (add an axis), never a licence for
    an opaque primitive.

    When to use:
        - Use for a culturally salient named affect (schadenfreude, saudade) minted for developer
          utility and mapping ONLY when it carries its declared decomposition links.

    When to avoid:
        - Avoid it for an unanalyzed primitive feeling (mint no opaque emotionX — either decompose
          it here or add the missing axis) and for the felt EPISODE (that is
          gmeow:AffectiveExperience).

    How to use:
        - Type the named compound gmeow:AffectComposite, bind its bearer, and declare its
          decomposition with gmeow:affectiveConstituent — a gmeow:AffectVectorObservation for the
          core-affect signature plus the elicitor/target/agency/norm relations that differentiate
          it.

    Examples:
        - ex:schadenfreude a gmeow:AffectComposite ; gmeow:emotionBearer ex:agent ;
          gmeow:affectiveConstituent ex:positiveCoreVector , ex:otherMisfortuneElicited .

    Usage:
        >>> from gmeow_models.affect import AffectComposite
        >>> AffectComposite.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectComposite'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectComposite
    CURIE:  gmeow:AffectComposite

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectComposite", "curie": "gmeow:AffectComposite", "definitionDigest": "blake3:5f5ed61dcf7e41e5000b466787c4e4b459192300df61ac6bfdeb8965eae72285", "iri": "https://blackcatinformatics.ca/gmeow/AffectComposite"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    affectiveConstituent: list[str] = Field(min_length=1, description="A declared part of a gmeow:AffectComposite's decomposition — a core-affect gmeow:AffectVectorObservation, a constituent gmeow:Emotion, or an appraisal/relation cell (elicitor, target, agency, norm) that gives the named compound its structure. Range intentionally open; NOT functional (a composite has several constituents). Mandatory on a composite (SHACL): a composite with no declared constituent is an unanalyzed primitive, which is forbidden.", alias="gmeow:affectiveConstituent")


class AffectDecision(ConfiguredBaseModel):
    """Affect Decision.

    A single-label classifier's categorical decision over one target — the argmax
    (gmeow:decidedLabel) recorded as model-vantage EVIDENCE (gmeow:vantage = the run,
    gmeow:observedFeature = the target), derived by gmeow:fnArgmax over a
    gmeow:decisionArgmax label set. A fact about the CLASSIFIER'S OUTPUT over external
    gmeow:AffectClassifierLabel identities, NEVER a gmeow:AffectiveClaim about inner affect
    and never a gmeow:EmotionType — so it needs no reviewed closeMatch and is recorded even
    when the argmax falls BELOW the claim threshold (gmeow:decisionCrossedThreshold false).
    This preserves the model's decision faithfully (maximal information flow) without
    forcing a claim (the evidence/claim boundary, Principle 9). Only a gmeow:decisionArgmax
    set carries one: a multi-label set has no single categorical winner. Supersedes
    gmeow:AffectEvaluationConcluded for single-label sets — a decided winner, even a
    low-margin one, is the positive 'checked' fact, never silence.

    When to use:
        - Use to record a single-label classifier's argmax decision as faithful evidence over a
          target — including the below-threshold case where the model decided but no claim is
          routed.

    When to avoid:
        - Avoid minting it for a multi-label (gmeow:decisionIndependentThreshold) set (there is no
          single argmax winner), avoid treating it as a gmeow:AffectiveClaim about inner affect
          (it is classifier-output evidence over an external label), and avoid asserting a
          gmeow:decisionMargin when the run emitted a single top-1 score (no runner-up exists).

    How to use:
        - For a gmeow:decisionArgmax label set, mint one gmeow:AffectDecision per (run, target):
          gmeow:vantage the run, gmeow:observedFeature the target, gmeow:decidedLabel the argmax
          label, gmeow:decisionCrossedThreshold whether it crossed the claim threshold,
          gmeow:derivedByFunction gmeow:fnArgmax, and gmeow:decisionMargin (top1−top2) only when
          ≥2 scores are present.

    Examples:
        - ex:decision a gmeow:AffectDecision ; gmeow:vantage ex:run ; gmeow:observedFeature
          ex:chunk ; gmeow:decidedLabel gmeow-hf:ekmanJoy ; gmeow:decisionCrossedThreshold false ;
          gmeow:decisionMargin 0.07 ; gmeow:derivedByFunction gmeow:fnArgmax .

    Usage:
        >>> from gmeow_models.affect import AffectDecision
        >>> AffectDecision.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectDecision'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectDecision
    CURIE:  gmeow:AffectDecision

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectDecision", "curie": "gmeow:AffectDecision", "definitionDigest": "blake3:20219e0f7068980b8e9470871d954fce25386182a9f5cad3354e340b119fdbee", "iri": "https://blackcatinformatics.ca/gmeow/AffectDecision"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    decidedLabel: Any = Field(description="The single gmeow:AffectClassifierLabel a gmeow:AffectDecision decides — the argmax (categorical mode) over a gmeow:decisionArgmax label set. Functional: a decision has exactly one decided label — the categorical winner-take-all exclusivity bound, authored in the reasoning layer as gmeow:AffectDecision owl:maxQualifiedCardinality 1 (owl:onClass owl:Thing) on this property (with owl:FunctionalProperty) and projected to SHACL sh:minCount 1 / sh:maxCount 1 (Principle 17): a decision with no decided label is meaningless, and two labels is not a single-label decision.", alias="gmeow:decidedLabel")
    decisionCrossedThreshold: Any = Field(description="Whether the decided label's score crossed its claim threshold (true) or the model decided but no claim was routed (false). Makes 'decided-but-below-threshold' a queryable fact distinct from a routed gmeow:AffectiveClaim — the argmax is recorded either way, only the claim is gated. Mandatory and single-valued: authored in the reasoning layer as gmeow:AffectDecision owl:maxQualifiedCardinality 1 (owl:onClass owl:Thing) on this property (with owl:FunctionalProperty) and projected to SHACL sh:minCount 1 / sh:maxCount 1 (Principle 17). The qualified idiom owl:maxQualifiedCardinality 1 with owl:onClass owl:Thing is the in-fragment form the native reasoner DECIDES — degrading the qualified count to the same class-unrestricted single-valued bound the unqualified form intended — so this single-valued datatype bound is a reasoning-layer fact, not a hand-authored SHACL constraint: a decision must record exactly one crossed-threshold verdict, its presence is never optional and two verdicts are incoherent.", alias="gmeow:decisionCrossedThreshold")
    derivedByFunction: list[Any] = Field(min_length=1, description="The named gmeow:AffectFunction that produced a derived-affect observation — the CLI-exposed handle for the computation, carried out outside the logic (Principle 12). Applies to any derived gmeow:Observation: gmeow:fnAffectiveIntensity on a gmeow:DerivedAffectIntensityObservation, gmeow:fnArgmax on a gmeow:AffectDecision.", alias="gmeow:derivedByFunction")
    observedFeature: Any = Field(description="The individual whose property or state is being observed — the feature of interest. The range is intentionally open (owl:Thing) because anything can be observed: a place, a person, an event, a document, a quality value, or a situation. SHACL shapes enforce closed-world constraints per observation kind.", alias="gmeow:observedFeature")
    vantage: list[Any] = Field(min_length=1, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class AffectScaleProfile(ConfiguredBaseModel):
    """Affect Scale Profile.

    The declared reference frame a numeric affect reading is expressed against: its range
    (gmeow:profileRangeMin/gmeow:profileRangeMax), midpoint (gmeow:profileMidpoint),
    polarity (gmeow:profilePolarity — bipolar/unipolar), and normalization transform
    (gmeow:profileTransform). A magnitude on an affect axis is meaningless without one
    (Principle 11: a value asserted without its frame is ill-formed). Scale arithmetic —
    normalization, cross-scale conversion, and the metric under which magnitudes combine
    into an intensity — is solver work outside the logic (Principle 12); the profile
    DECLARES the frame, it does not compute in triples. The affect-domain analogue of the
    rubrics facility's gmeow:ScoreScale, minted here because affect is core and cannot
    depend on the norms extension.

    When to use:
        - Use to declare the scale/frame a numeric affect magnitude is read against — range,
          midpoint, polarity, and normalization transform — so a reading carries its own
          interpretation.

    When to avoid:
        - Avoid encoding normalization or cross-scale conversion arithmetic in triples (that is
          solver work — Principle 12), and avoid a bare numeric reading with no profile — an
          unframed magnitude is ill-formed, not a default.

    How to use:
        - Mint the profile with gmeow:profileRangeMin / gmeow:profileRangeMax (and
          gmeow:profileMidpoint / gmeow:profilePolarity / gmeow:profileTransform as the tradition
          declares), then bind every gmeow:appraisalValue to it via gmeow:appraisalScaleProfile
          and name a vector reading's basis via gmeow:vectorProfile.

    Examples:
        - ex:padUnitScale a gmeow:AffectScaleProfile ; gmeow:profileRangeMin -1.0 ;
          gmeow:profileRangeMax 1.0 ; gmeow:profileMidpoint 0.0 ; gmeow:profilePolarity
          gmeow:polarityBipolar .

    Usage:
        >>> from gmeow_models.affect import AffectScaleProfile
        >>> AffectScaleProfile.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectScaleProfile'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectScaleProfile
    CURIE:  gmeow:AffectScaleProfile

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectScaleProfile", "curie": "gmeow:AffectScaleProfile", "definitionDigest": "blake3:13a8859301445b24287025ae92bf7e41a3303302ec4163a6ff4a90c88760bade", "iri": "https://blackcatinformatics.ca/gmeow/AffectScaleProfile"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    profileRangeMax: list[float] = Field(min_length=1, description="The maximum of an affect scale's range (must exceed gmeow:profileRangeMin). Mandatory (SHACL). Functional.", alias="gmeow:profileRangeMax")
    profileRangeMin: list[float] = Field(min_length=1, description="The minimum of an affect scale's range (below gmeow:profileRangeMax). Mandatory (SHACL). Functional.", alias="gmeow:profileRangeMin")


class AffectVectorObservation(ConfiguredBaseModel):
    """Affect Vector Observation.

    The stable, queryable identity for 'the vector reading' — a reified multidimensional
    assessment (the same idiom as logic:GoalEvaluation / logic:AgencyAssessment) grouping
    the per-axis gmeow:Appraisal cells that share vantage, target, elicitor, and time, and
    naming its metric/basis via gmeow:vectorProfile. One cell per axis is preserved
    (gmeow:vectorComponent → each dimensional Appraisal); the grouping is the handle that
    makes the vector citable, signable, suppressible, and projectable as a unit. Overall
    intensity and cross-basis coordinates are DERIVED views over this record, never stored
    cells (Principle 12).

    When to use:
        - Use to give a multi-axis affect reading one queryable identity — the stable handle for
          the vector, distinct from its per-axis cells and from any derived intensity.

    When to avoid:
        - Avoid materialising a dense high-frequency stream as vector observations (that is a
          gmeow:AffectTelemetryStream dense block by-reference) and avoid storing the norm as a
          component cell (it is derived).

    How to use:
        - Mint the vector observation, name its basis with gmeow:vectorProfile, and attach one
          dimensional gmeow:Appraisal per axis via gmeow:vectorComponent; share
          vantage/target/elicitor/time across the cells.

    Examples:
        - ex:vec a gmeow:AffectVectorObservation ; gmeow:vantage ex:agent ; gmeow:vectorProfile
          ex:padUnitScale ; gmeow:vectorComponent ex:valenceCell , ex:arousalCell .

    Usage:
        >>> from gmeow_models.affect import AffectVectorObservation
        >>> AffectVectorObservation.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectVectorObservation'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectVectorObservation
    CURIE:  gmeow:AffectVectorObservation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectVectorObservation", "curie": "gmeow:AffectVectorObservation", "definitionDigest": "blake3:afd2e77d2066695f98a90c1c22615e4cffa51b8cfbb121afe5627cb580666236", "iri": "https://blackcatinformatics.ca/gmeow/AffectVectorObservation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    vectorComponent: list[str] = Field(min_length=1, description="A per-axis gmeow:Appraisal cell grouped by a gmeow:AffectVectorObservation — one dimensional reading (dimension + value + scale profile) that is one component of the vector. NOT functional: a vector groups several axis cells. One cell per axis is preserved; the grouping does not overwrite the cells.", alias="gmeow:vectorComponent")
    vectorProfile: list[str] = Field(min_length=1, description="The gmeow:AffectScaleProfile naming the metric/basis of a gmeow:AffectVectorObservation — the frame the whole vector is read against. Mandatory (SHACL). Functional: one vector, one declared basis.", alias="gmeow:vectorProfile")


class AffectiveClaim(ConfiguredBaseModel):
    """Affective Claim.

    A richer GMEOW affect claim SUPPORTED BY evidence — a classifier output, an expression
    observation, or a self-report — with its own vantage and standpoint. The evidence/claim
    boundary made explicit (Principle 9): a classifier output that directly asserts
    someone's inner affect WITHOUT this claim boundary is a hard fail. Self-report outranks
    third-party attribution for the subject's own standpoint but does not delete the
    attributed claim; both coexist. The text-expresses-joy / speaker-reports-joy /
    speaker-likely-felt-joy / reader-appraised-joyful readings are SEPARATE claims, never
    collapsed.

    When to use:
        - Use for a human-level affective claim distinct from its evidence — the thing evidence
          SUPPORTS, never the raw model output itself.

    When to avoid:
        - Avoid collapsing the distinct claim templates (expresses / reports / felt / appraised)
          into one and avoid deleting a superseded claim (suppress/close it — both standpoints
          stay queryable).

    How to use:
        - Mint the claim with its vantage and target, and link the evidence that supports it via
          the inverse of gmeow:supportsAffectiveClaim from each gmeow:AffectClassifierOutput /
          expression / self-report.

    Examples:
        - ex:claim a gmeow:AffectiveClaim ; gmeow:vantage ex:analyst ; gmeow:observedFeature
          ex:author .

    Usage:
        >>> from gmeow_models.affect import AffectiveClaim
        >>> AffectiveClaim.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectiveClaim'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectiveClaim
    CURIE:  gmeow:AffectiveClaim

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectiveClaim", "curie": "gmeow:AffectiveClaim", "definitionDigest": "blake3:117c553be03a30d2512c367d581c577c6dad93e467dfb37c121e4d37fc2d2274", "iri": "https://blackcatinformatics.ca/gmeow/AffectiveClaim"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class AffectiveExperience(ConfiguredBaseModel):
    """Affective Experience.

    The phenomenally-conscious felt affective episode — the OCCURRENT (perdurant) of
    undergoing an affective state, an episode there is something it is like to feel. A
    subset of mentation's gmeow:Experience whose kind is pinned to
    gmeow:processAffectiveExperience by an owl:hasValue restriction (the gmeow:DreamReport
    idiom: a restriction-pinned queryable handle, NOT overtyping — the kind still lives in
    the gmeow:mentalProcessType value, Principle 9). Distinct from the ENDURANT
    gmeow:Emotion mode it realizes via gmeow:feltAffect: an agent can bear an emotion mode
    without currently feeling it, and one felt episode can realize it. Inherits
    gmeow:experiencer and gmeow:mentalProcessType from gmeow:MentalProcess — the occurrent
    side of the mode/experience cut.

    When to use:
        - Use for the occurrent, phenomenal episode of feeling — 'I felt angry for five minutes' —
          distinct from the enduring gmeow:Emotion mode it realizes, so an agent's felt mental
          life is a first-class, queryable event on the mental timeline.

    When to avoid:
        - Avoid it for the ENDURING affective mode itself (that is gmeow:Emotion, a
          gmeow:AffectiveMoment ⊑ gmeow:MentalMoment — an endurant, never an occurrent) and for
          sub-personal affective processing carrying no first-person character (type plain
          gmeow:MentalProcess with the process type).

    How to use:
        - Type the felt episode gmeow:AffectiveExperience (it carries gmeow:mentalProcessType
          gmeow:processAffectiveExperience by the pinned restriction), bind its bearer with
          gmeow:experiencer, and link the affective mode it manifests with gmeow:feltAffect (an
          affect-scoped refinement of mentation's gmeow:realizesMentalMoment).

    Examples:
        - ex:feltAnger a gmeow:AffectiveExperience ; gmeow:experiencer ex:agent ; gmeow:feltAffect
          ex:angerMode .

    Usage:
        >>> from gmeow_models.affect import AffectiveExperience
        >>> AffectiveExperience.model_config["json_schema_extra"]["curie"]
        'gmeow:AffectiveExperience'

    IRI:    https://blackcatinformatics.ca/gmeow/AffectiveExperience
    CURIE:  gmeow:AffectiveExperience

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/AffectiveExperience", "curie": "gmeow:AffectiveExperience", "definitionDigest": "blake3:2c9912e6b77af01fddda7f3726b709858ba9c5e8282c91602a2f13914ebfa53b", "iri": "https://blackcatinformatics.ca/gmeow/AffectiveExperience"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    experiencer: list[str] = Field(min_length=1, description="The agent whose mental process this is — the one undergoing the perceiving, reasoning, or dreaming. Functional: one process, one experiencer (a mental occurrent inheres in exactly one agent; two agents reasoning about the same thing are two processes).", alias="gmeow:experiencer")
    feltAffect: list[str] = Field(min_length=1, description="Links a felt gmeow:AffectiveExperience (occurrent) to the gmeow:AffectiveMoment (endurant affective mode — an Emotion, later a Mood) it MANIFESTS. The affect-scoped, discoverable refinement of mentation's generic gmeow:realizesMentalMoment (domain narrowed to gmeow:AffectiveExperience, range to gmeow:AffectiveMoment), following the gmeow:appraisalOf ⊑ gmeow:observedFeature idiom. NOT functional — one episode may manifest several coexisting modes; the episode's gmeow:experiencer and the mode's gmeow:emotionBearer are the same agent.", alias="gmeow:feltAffect")
    mentalProcessType: list[str] | None = Field(default=None, description="The kind of a mental process — a gmeow:MentalProcessType value (gmeow:processPerception, gmeow:processReasoning, gmeow:processDreaming, …). NOT functional: a single occurrence may carry several type values (a reverie that is both imagining and mind-wandering). Mirrors gmeow:eventType.", alias="gmeow:mentalProcessType")


class Appraisal(ConfiguredBaseModel):
    """Appraisal.

    An affective or aesthetic reading of something, as an observation: vantage = the
    appraiser. Dimensional (PAD: a valence/arousal/dominance value) or qualitative (an
    aesthetic quality: elegance, sublimity, kitsch) — at least one of the two forms (SHACL).
    Two critics disagreeing are two coexisting cells; self-report is top authority for the
    subject's own standpoint (Principle 9, the facetVantage precedent).

    Usage:
        >>> from gmeow_models.affect import Appraisal
        >>> Appraisal.model_config["json_schema_extra"]["curie"]
        'gmeow:Appraisal'

    IRI:    https://blackcatinformatics.ca/gmeow/Appraisal
    CURIE:  gmeow:Appraisal

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Appraisal", "curie": "gmeow:Appraisal", "definitionDigest": "blake3:e4d0d76a2d7dadca4bc48051586a0ca792a546d0302333188291ab8a93ddf2e7", "iri": "https://blackcatinformatics.ca/gmeow/Appraisal"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    appraisalDimension: Any | None = Field(default=None, description="The dimension a dimensional appraisal reads. At most one per appraisal (SHACL — one cell, one reading; a PAD triple is three Appraisals sharing a vantage). Open vocabulary (sh:nodeKind sh:IRI).", alias="gmeow:appraisalDimension")
    appraisalOf: str = Field(description="What is appraised — an agent's state, a work, an event, an emotion (⊑ observedFeature, the observation-spine bridge idiom). Range intentionally open. Functional: one appraisal, one subject.", alias="gmeow:appraisalOf")
    appraisalScaleProfile: list[AffectScaleProfile] | None = Field(default=None, description="The gmeow:AffectScaleProfile a dimensional gmeow:appraisalValue is read against — the declared range, midpoint, polarity, and transform that give the bare magnitude its meaning. MANDATORY on any dimensional appraisal (a cell carrying gmeow:appraisalValue): the greenfield reshape removed the bare-decimal floor, so an unframed reading is ill-formed, not a permitted default (Principle 6, Principle 11). Functional: one reading, one frame.", alias="gmeow:appraisalScaleProfile")
    appraisalValue: float | None = Field(default=None, description="The magnitude of a dimensional reading, ALWAYS expressed against the gmeow:AffectScaleProfile named by gmeow:appraisalScaleProfile — a bare number carries no meaning without its declared frame (Principle 11), and the greenfield reshape removed the old plain-decimal floor (Principle 6). At most one per appraisal, and only alongside its dimension AND its scale profile (SHACL). Constitutive of this one cell — divergent readings are divergent Appraisals, not extra values.", alias="gmeow:appraisalValue")
    vantage: list[str] = Field(min_length=1, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class DerivedAffectIntensityObservation(ConfiguredBaseModel):
    """Derived Affect Intensity Observation.

    Overall affect intensity as a DERIVED view — the norm of a gmeow:AffectVectorObservation
    computed OUTSIDE the logic under a declared metric (Principle 12), never a separately
    stored ground fact. Because the axis basis is non-orthogonal (valence correlates with
    goal-congruence, dominance overlaps coping), a raw Euclidean L² norm is NOT the default:
    the metric is an explicit declared weighted / metric-tensor form. An intensity record
    MUST declare its basis (gmeow:intensityBasis), scale normalization
    (gmeow:metricProfile), weighting policy (gmeow:weightingPolicy), and norm/distance
    function (gmeow:normFunction) — any missing declaration is a hard fail. No intensity is
    canonical without that named basis.

    When to use:
        - Use to expose overall intensity (the vector norm) to the CLI as a derived observation
          under a named metric — the answer to 'how intense, and along which dominant axis?'.

    When to avoid:
        - Avoid storing it as a canonical ground fact (it is a recomputable view), avoid a bare L²
          norm over the non-orthogonal basis, and avoid omitting any of basis / scale / weighting
          / norm (each omission is a hard fail).

    How to use:
        - Compute the norm externally, then record it as a gmeow:DerivedAffectIntensityObservation
          declaring gmeow:intensityBasis, gmeow:metricProfile, gmeow:weightingPolicy, and
          gmeow:normFunction (and gmeow:derivedByFunction gmeow:fnAffectiveIntensity for the CLI
          handle).

    Examples:
        - ex:intensity a gmeow:DerivedAffectIntensityObservation ; gmeow:intensityBasis ex:vec ;
          gmeow:metricProfile gmeow:coreAffectMetricPAD ; gmeow:weightingPolicy
          gmeow:weightingEqualCoreAffect ; gmeow:normFunction gmeow:affectMetricTensorNorm ;
          gmeow:derivedByFunction gmeow:fnAffectiveIntensity .

    Usage:
        >>> from gmeow_models.affect import DerivedAffectIntensityObservation
        >>> DerivedAffectIntensityObservation.model_config["json_schema_extra"]["curie"]
        'gmeow:DerivedAffectIntensityObservation'

    IRI:    https://blackcatinformatics.ca/gmeow/DerivedAffectIntensityObservation
    CURIE:  gmeow:DerivedAffectIntensityObservation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/DerivedAffectIntensityObservation", "curie": "gmeow:DerivedAffectIntensityObservation", "definitionDigest": "blake3:43214c64a6d02c3ef7e2d65b5a0c0e1798bedc4591eca647f9f6b243e6719a21", "iri": "https://blackcatinformatics.ca/gmeow/DerivedAffectIntensityObservation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class ModelInferenceRun(ConfiguredBaseModel):
    """Model Inference Run.

    One execution of a classifier over an input — a PROV-O-aligned activity (prov:Activity
    by generated correspondence) carrying its full run provenance: a pinned model id
    (gmeow:modelIdentifier) and MANDATORY revision (gmeow:modelRevision), model
    framework/task, tokenizer + label-set revisions, the id2label mapping,
    activation/functionToApply, topK/returnAllScores, threshold policy, and a calibration
    profile whenever a score is claimed as a probability. A model name without a pinned
    revision fails reproducibility (a hard fail). Its outputs are
    gmeow:AffectClassifierOutput observations (gmeow:producedBy).

    When to use:
        - Use for one classifier execution over an input — the provenance-bearing activity whose
          outputs are attributed affect evidence.

    When to avoid:
        - Avoid recording a run without a pinned gmeow:modelRevision (unreproducible — a hard
          fail) and avoid treating the run's outputs as inner-state truth (they are attributed
          evidence).

    How to use:
        - Record the run with its pinned model id + revision and full
          framework/task/tokenizer/label-set provenance, link its input via gmeow:usedInput, and
          attach each emitted output via gmeow:producedBy.

    Examples:
        - ex:run a gmeow:ModelInferenceRun ; gmeow:modelIdentifier
          "SamLowe/roberta-base-go_emotions" ; gmeow:modelRevision "a1b2c3d" ; gmeow:usedInput
          ex:chunk .

    Usage:
        >>> from gmeow_models.affect import ModelInferenceRun
        >>> ModelInferenceRun.model_config["json_schema_extra"]["curie"]
        'gmeow:ModelInferenceRun'

    IRI:    https://blackcatinformatics.ca/gmeow/ModelInferenceRun
    CURIE:  gmeow:ModelInferenceRun

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/ModelInferenceRun", "curie": "gmeow:ModelInferenceRun", "definitionDigest": "blake3:32b3b85a5753e06b6cdf9cc250f5532b03263d99a60e5271ff811d7e4077c09e", "iri": "https://blackcatinformatics.ca/gmeow/ModelInferenceRun"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    modelIdentifier: list[str] = Field(min_length=1, description="The model repository id of an inference run (e.g. the Hugging Face repo 'SamLowe/roberta-base-go_emotions'). Mandatory (SHACL); a model id WITHOUT a pinned gmeow:modelRevision fails reproducibility.", alias="gmeow:modelIdentifier")
    modelRevision: list[str] = Field(min_length=1, description="The pinned model revision/commit of an inference run — MANDATORY (SHACL). A model name without a pinned revision is unreproducible and fails. The single most drift-prone field for zero-shot/generative adapters.", alias="gmeow:modelRevision")
