"""GMEOW models — slice GMEOW Archaeological Evidence Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/archaeological-evidence
Tier:       extension
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class PhysicalCarrierTypeEnum(StrEnum):
    carrierBone = "gmeow:carrierBone"
    carrierCoin = "gmeow:carrierCoin"
    carrierManuscript = "gmeow:carrierManuscript"
    carrierMetal = "gmeow:carrierMetal"
    carrierOstracon = "gmeow:carrierOstracon"
    carrierPapyrus = "gmeow:carrierPapyrus"
    carrierPotterySherd = "gmeow:carrierPotterySherd"
    carrierSeal = "gmeow:carrierSeal"
    carrierStela = "gmeow:carrierStela"
    carrierTablet = "gmeow:carrierTablet"
    carrierWallInscription = "gmeow:carrierWallInscription"
    carrierWood = "gmeow:carrierWood"


class ArchaeologicalFindContext(ConfiguredBaseModel):
    """Archaeological Find Context.

    A reified find context binding a physical carrier to its stratigraphic unit, find-spot,
    excavation or documentation event, and dating evidence. A single carrier may have
    multiple coexisting context claims from different excavation campaigns or analytical
    standpoints (Principle 9). Follows the universal Observation + Relator pattern.

    Usage:
        >>> from gmeow_models.archaeological_evidence import ArchaeologicalFindContext
        >>> ArchaeologicalFindContext.model_config["json_schema_extra"]["curie"]
        'gmeow:ArchaeologicalFindContext'

    IRI:    https://blackcatinformatics.ca/gmeow/ArchaeologicalFindContext
    CURIE:  gmeow:ArchaeologicalFindContext

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/ArchaeologicalFindContext", "curie": "gmeow:ArchaeologicalFindContext", "definitionDigest": "blake3:28b54adac5147c235ff5a6090eb97bd51f41df4fad2a149f349c6dda1c2d7d8c", "iri": "https://blackcatinformatics.ca/gmeow/ArchaeologicalFindContext"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    findContextTarget: list[PhysicalObject] | None = Field(default=None, description="The physical carrier whose find context is being described. Functional per relator: one target carrier per ArchaeologicalFindContext.", alias="gmeow:findContextTarget")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class InscriptionReading(ConfiguredBaseModel):
    """Inscription Reading.

    A scholarly reading of an inscription — the Observation that produces a LexicalForm from
    a sign-bearing feature. The reading is a standpoint-scoped claim, not ground truth: two
    scholars may read the same marks differently, and both readings coexist (Principle 9).
    Follows the universal Observation + Relator pattern.

    Usage:
        >>> from gmeow_models.archaeological_evidence import InscriptionReading
        >>> InscriptionReading.model_config["json_schema_extra"]["curie"]
        'gmeow:InscriptionReading'

    IRI:    https://blackcatinformatics.ca/gmeow/InscriptionReading
    CURIE:  gmeow:InscriptionReading

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/InscriptionReading", "curie": "gmeow:InscriptionReading", "definitionDigest": "blake3:3b0e744439b3a2373650e58f58482e6138e19c5c8a8fdb53734e0b5e6ca72399", "iri": "https://blackcatinformatics.ca/gmeow/InscriptionReading"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    readingOf: list[str] | None = Field(default=None, description="Within gmeow:InscriptionReading, values are node references constrained to gmeow:Inscription. The inscription that a reading observes. Functional per relator: one source inscription per InscriptionReading.", alias="gmeow:readingOf")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class InscriptionTranslation(ConfiguredBaseModel):
    """Inscription Translation.

    A translation of an inscription into another language — an Observation that produces a
    LexicalForm representing the meaning of the source inscription in a target language.
    Standpoint-scoped: competing translations coexist without privilege (Principle 9).

    Usage:
        >>> from gmeow_models.archaeological_evidence import InscriptionTranslation
        >>> InscriptionTranslation.model_config["json_schema_extra"]["curie"]
        'gmeow:InscriptionTranslation'

    IRI:    https://blackcatinformatics.ca/gmeow/InscriptionTranslation
    CURIE:  gmeow:InscriptionTranslation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/InscriptionTranslation", "curie": "gmeow:InscriptionTranslation", "definitionDigest": "blake3:7eb01f7b9ea8cf31d5e859380ccd42fafa932c8525c067c8be454cbaed059101", "iri": "https://blackcatinformatics.ca/gmeow/InscriptionTranslation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    translationOf: list[str] | None = Field(default=None, description="Within gmeow:InscriptionTranslation, values are node references constrained to gmeow:Inscription. The inscription that a translation renders into another language. Functional per relator: one source inscription per InscriptionTranslation.", alias="gmeow:translationOf")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class InscriptionTransliteration(ConfiguredBaseModel):
    """Inscription Transliteration.

    A transliteration of an inscription into another script — an Observation that maps sign
    sequences from one writing system to another, producing a LexicalForm.
    Standpoint-scoped: competing transliteration schemes (e.g. Hepburn vs Kunrei-shiki)
    coexist without a single winner (Principle 9).

    Usage:
        >>> from gmeow_models.archaeological_evidence import InscriptionTransliteration
        >>> InscriptionTransliteration.model_config["json_schema_extra"]["curie"]
        'gmeow:InscriptionTransliteration'

    IRI:    https://blackcatinformatics.ca/gmeow/InscriptionTransliteration
    CURIE:  gmeow:InscriptionTransliteration

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/InscriptionTransliteration", "curie": "gmeow:InscriptionTransliteration", "definitionDigest": "blake3:fb160658ae35393dd8d88613ef5ca07cc000915e0a2ddd11811fbc7e02b572fc", "iri": "https://blackcatinformatics.ca/gmeow/InscriptionTransliteration"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    transliterationOf: list[str] | None = Field(default=None, description="Within gmeow:InscriptionTransliteration, values are node references constrained to gmeow:Inscription. The inscription that a transliteration maps into another script. Functional per relator: one source inscription per InscriptionTransliteration.", alias="gmeow:transliterationOf")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class ScriptLanguageAttribution(ConfiguredBaseModel):
    """Script Language Attribution.

    A standpoint-scoped claim assigning a language, writing system, or notation system to an
    inscription. Handles disputed, uncertain, and undeciphered cases: an undeciphered
    inscription may carry an attribution to a NotationSystem with low confidence and
    determinacy = disputed, while competing palaeographic classifications coexist as
    separate attributions (Principle 9). Follows the universal Observation + Relator
    pattern.

    Usage:
        >>> from gmeow_models.archaeological_evidence import ScriptLanguageAttribution
        >>> ScriptLanguageAttribution.model_config["json_schema_extra"]["curie"]
        'gmeow:ScriptLanguageAttribution'

    IRI:    https://blackcatinformatics.ca/gmeow/ScriptLanguageAttribution
    CURIE:  gmeow:ScriptLanguageAttribution

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/ScriptLanguageAttribution", "curie": "gmeow:ScriptLanguageAttribution", "definitionDigest": "blake3:777ab835c78f5cc944672fd374a426d2d6c453a3cc68b19f3da17acee996e25c", "iri": "https://blackcatinformatics.ca/gmeow/ScriptLanguageAttribution"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    attributionTarget: list[str] | None = Field(default=None, description="Within gmeow:ScriptLanguageAttribution, values are node references constrained to gmeow:Inscription. The inscription being classified by a script/language attribution. Functional per relator: one target inscription per ScriptLanguageAttribution.", alias="gmeow:attributionTarget")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")
