"""GMEOW models — slice GMEOW Calendar and Scheduling Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/calendar
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class AvailabilityStatusEnum(StrEnum):
    availabilityStatusBusy = "gmeow:availabilityStatusBusy"
    availabilityStatusFree = "gmeow:availabilityStatusFree"
    availabilityStatusOutOfOffice = "gmeow:availabilityStatusOutOfOffice"
    availabilityStatusTentative = "gmeow:availabilityStatusTentative"


class ExceptionTypeEnum(StrEnum):
    exceptionTypeCancellation = "gmeow:exceptionTypeCancellation"
    exceptionTypeRescheduling = "gmeow:exceptionTypeRescheduling"


class InvitationStatusEnum(StrEnum):
    invitationStatusAccepted = "gmeow:invitationStatusAccepted"
    invitationStatusDeclined = "gmeow:invitationStatusDeclined"
    invitationStatusNeedsAction = "gmeow:invitationStatusNeedsAction"
    invitationStatusTentative = "gmeow:invitationStatusTentative"


class ReminderActionEnum(StrEnum):
    reminderActionAudio = "gmeow:reminderActionAudio"
    reminderActionDisplay = "gmeow:reminderActionDisplay"
    reminderActionEmail = "gmeow:reminderActionEmail"


class RsvpStatusEnum(StrEnum):
    rsvpStatusAccepted = "gmeow:rsvpStatusAccepted"
    rsvpStatusDeclined = "gmeow:rsvpStatusDeclined"
    rsvpStatusNeedsAction = "gmeow:rsvpStatusNeedsAction"
    rsvpStatusTentative = "gmeow:rsvpStatusTentative"


class TaskStatusEnum(StrEnum):
    taskStatusCancelled = "gmeow:taskStatusCancelled"
    taskStatusCompleted = "gmeow:taskStatusCompleted"
    taskStatusInProgress = "gmeow:taskStatusInProgress"
    taskStatusNotStarted = "gmeow:taskStatusNotStarted"


class Availability(ConfiguredBaseModel):
    """Availability.

    A time-scoped statement of an agent's availability over an interval — free, busy,
    tentative, or out-of-office. The free-busy spine of the calendar layer.

    When to use:
        - Use to state whether an agent is free, busy, tentative, or out-of-office over a bounded
          interval — the iCalendar VFREEBUSY case, reified as a time-scoped situation so the slot
          and status are queryable.

    When to avoid:
        - Avoid for attendance at a specific event (use gmeow:Participation /
          gmeow:EventInvitation) and for a timeless 'usually busy' generalization; an availability
          holds only across its named interval.

    How to use:
        - Inherit the time-scope from gmeow:TimeScopedRelation: name the gmeow:availabilityAgent,
          bound it with a gmeow:availabilitySlot interval, and set the gmeow:availabilityStatus
          value.

    Examples:
        - ex:lillithBusy a gmeow:Availability ; gmeow:availabilityAgent ex:lillith ;
          gmeow:availabilitySlot ex:morningSlot ; gmeow:availabilityStatus
          gmeow:availabilityStatusBusy .

    Usage:
        >>> from gmeow_models.calendar import Availability
        >>> Availability.model_config["json_schema_extra"]["curie"]
        'gmeow:Availability'

    IRI:    https://blackcatinformatics.ca/gmeow/Availability
    CURIE:  gmeow:Availability

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Availability", "curie": "gmeow:Availability", "definitionDigest": "blake3:feec9afa0041cb7bf901fcd3adf331f35f3af14b72359ba47524aa3b419cc4f1", "iri": "https://blackcatinformatics.ca/gmeow/Availability"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    availabilityAgent: Agent = Field(description="The agent whose availability is stated.", alias="gmeow:availabilityAgent")
    availabilitySlot: TimeInterval = Field(description="The time interval over which the availability status holds.", alias="gmeow:availabilitySlot")
    availabilityStatus: AvailabilityStatusEnum = Field(description="The availability status for this slot — free, busy, tentative, or out-of-office.", alias="gmeow:availabilityStatus")


class EventInvitation(ConfiguredBaseModel):
    """Event Invitation.

    A social act inviting an agent to attend an event, reified as a relator. Models the
    invitation as an Agreement to attend, reusing gmeow:hasParty for the invitee and the
    invitation status for the response state. Standpoint-indexed: a disputed invitation
    status is several coexisting claims, none privileged (Principle 9).

    When to use:
        - Use to reify the act of inviting an agent to an event as a first-class relator — so the
          invitee, the organizer's status, and the invitee's RSVP are each queryable and can
          disagree (Principle 9).

    When to avoid:
        - Avoid flattening the invitation into a property on the event, and avoid using it for
          mere attendance (that is gmeow:Participation on the occurred event); the invitation is
          the social act, not the showing-up.

    How to use:
        - Link it to its gmeow:invitationEvent and one or more gmeow:invitationInvitee, carry the
          organizer's view on gmeow:invitationStatus and the invitee's on gmeow:rsvpStatus;
          standpoint-index a disputed status via accordingTo rather than overwriting.

    Examples:
        - ex:standupInvite a gmeow:EventInvitation ; gmeow:invitationEvent ex:standupEvent ;
          gmeow:invitationInvitee ex:lillith ; gmeow:invitationStatus
          gmeow:invitationStatusAccepted .

    Usage:
        >>> from gmeow_models.calendar import EventInvitation
        >>> EventInvitation.model_config["json_schema_extra"]["curie"]
        'gmeow:EventInvitation'

    IRI:    https://blackcatinformatics.ca/gmeow/EventInvitation
    CURIE:  gmeow:EventInvitation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/EventInvitation", "curie": "gmeow:EventInvitation", "definitionDigest": "blake3:07f7bad1c2738ec1ad936cc82d33f9228cea4ecf2f69222b86b34d9f7d634637", "iri": "https://blackcatinformatics.ca/gmeow/EventInvitation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    invitationEvent: Event = Field(description="The event being invited to.", alias="gmeow:invitationEvent")
    invitationInvitee: list[Agent] = Field(min_length=1, description="An agent invited to the event. Non-functional: a joint invitation may name several invitees.", alias="gmeow:invitationInvitee")
    invitationStatus: InvitationStatusEnum = Field(description="The current status of the invitation as set by the organizer — needs-action, accepted, declined, tentative.", alias="gmeow:invitationStatus")


class EventSchedule(ConfiguredBaseModel):
    """Event Schedule.

    A recurrence rule anchored to a template event and a time zone, generating a series of
    concrete Event occurrences. A relator mediating the template event, the recurrence rule,
    and the generated occurrences. Distinct from any one occurrence; the schedule is the
    generator, not the generated.

    When to use:
        - Use to model the rule-plus-anchor that GENERATES a series of occurrences — a weekly
          standup, a monthly review — when the generator must be a queryable thing distinct from
          any occurrence it produces (Principle 1).

    When to avoid:
        - Avoid for a one-off event (just a gmeow:Event) and for an individual generated
          occurrence (that is a gmeow:Event linked by gmeow:scheduleOccurrence); the schedule is
          the generator, never the generated.

    How to use:
        - Anchor it with one gmeow:scheduleTemplateEvent, attach one or more
          gmeow:scheduleRecurrenceRule, set the gmeow:scheduleTimeZone the rule expands in, and
          link each generated gmeow:Event via gmeow:scheduleOccurrence; record cancellations/moves
          as gmeow:ScheduleException rather than editing the rule.

    Examples:
        - ex:standupSchedule a gmeow:EventSchedule ; gmeow:scheduleTemplateEvent
          ex:standupTemplate ; gmeow:scheduleTimeZone ex:torontoZone ; gmeow:scheduleOccurrence
          ex:standup0612 .

    Usage:
        >>> from gmeow_models.calendar import EventSchedule
        >>> EventSchedule.model_config["json_schema_extra"]["curie"]
        'gmeow:EventSchedule'

    IRI:    https://blackcatinformatics.ca/gmeow/EventSchedule
    CURIE:  gmeow:EventSchedule

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/EventSchedule", "curie": "gmeow:EventSchedule", "definitionDigest": "blake3:c55512a765eee39f577b346fac83d24e5c81363d8b3829a224d5920ff25b7f9c", "iri": "https://blackcatinformatics.ca/gmeow/EventSchedule"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    scheduleTemplateEvent: list[Event] | None = Field(default=None, description="The template event from which occurrences are generated — the anchor event carrying title, location, participants, and duration. Functional: one template per schedule.", alias="gmeow:scheduleTemplateEvent")


class Reminder(ConfiguredBaseModel):
    """Reminder.

    A reminder associated with an event — a trigger (offset or absolute time) and an action
    (display, email, audio).

    When to use:
        - Use to model an iCalendar VALARM attached to an event — a trigger (an offset before it
          or an absolute time) plus an action to fire.

    When to avoid:
        - Avoid for the event's own temporal placement (that is on the event) and for a task's due
          date (use gmeow:taskDueDate); a reminder is an alert about a target, not the target's
          schedule.

    How to use:
        - Bind it to its gmeow:reminderTarget event, set a gmeow:reminderTrigger (xsd:duration
          offset or absolute xsd:dateTime), and choose a gmeow:reminderAction.

    Examples:
        - ex:standupAlarm a gmeow:Reminder ; gmeow:reminderTarget ex:standupEvent ;
          gmeow:reminderTrigger "PT15M"^^xsd:duration ; gmeow:reminderAction
          gmeow:reminderActionDisplay .

    Usage:
        >>> from gmeow_models.calendar import Reminder
        >>> Reminder.model_config["json_schema_extra"]["curie"]
        'gmeow:Reminder'

    IRI:    https://blackcatinformatics.ca/gmeow/Reminder
    CURIE:  gmeow:Reminder

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Reminder", "curie": "gmeow:Reminder", "definitionDigest": "blake3:35878c5dbd3a4de098ee63df159683463b77aeef353722f2346059480494763a", "iri": "https://blackcatinformatics.ca/gmeow/Reminder"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    reminderAction: ReminderActionEnum = Field(description="The action to take when the reminder fires — display, email, or audio.", alias="gmeow:reminderAction")
    reminderTarget: Event = Field(description="The event this reminder is attached to.", alias="gmeow:reminderTarget")
    reminderTrigger: Any = Field(description="The trigger for a reminder — either an xsd:duration offset before the target event (e.g. PT15M) or an absolute xsd:dateTime.", alias="gmeow:reminderTrigger")


class ScheduleException(ConfiguredBaseModel):
    """Schedule Exception.

    An exception to a recurring event schedule — a cancellation or rescheduling of a
    specific generated occurrence. A relator mediating the schedule, the original date, and
    optionally a replacement event. Retained with displayable false rather than deleted
    (Principle 10).

    When to use:
        - Use when one occurrence of a recurring schedule is cancelled or moved — the RFC 5545
          EXDATE/RECURRENCE-ID case — so the deviation is recorded against the rule without
          rewriting it.

    When to avoid:
        - Avoid for changing the whole series (edit the gmeow:scheduleRecurrenceRule instead) and
          never delete the affected occurrence — a cancelled occurrence is displayable false plus
          this exception, retained (Principle 10).

    How to use:
        - Link it to its gmeow:exceptionSchedule, stamp the gmeow:exceptionOriginalDate of the
          occurrence it overrides, set gmeow:exceptionType, and add
          gmeow:exceptionReplacementEvent for a reschedule (omit it for a pure cancellation).

    Examples:
        - ex:standupSkip a gmeow:ScheduleException ; gmeow:exceptionSchedule ex:standupSchedule ;
          gmeow:exceptionOriginalDate "2026-06-19T09:00:00Z"^^xsd:dateTime ; gmeow:exceptionType
          gmeow:exceptionTypeCancellation .

    Usage:
        >>> from gmeow_models.calendar import ScheduleException
        >>> ScheduleException.model_config["json_schema_extra"]["curie"]
        'gmeow:ScheduleException'

    IRI:    https://blackcatinformatics.ca/gmeow/ScheduleException
    CURIE:  gmeow:ScheduleException

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/ScheduleException", "curie": "gmeow:ScheduleException", "definitionDigest": "blake3:8e86cec2962c0156b1c3e8d6028636d021bd6f41abea0e6b15dcaa1ab1562fdb", "iri": "https://blackcatinformatics.ca/gmeow/ScheduleException"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    exceptionOriginalDate: list[datetime] | None = Field(default=None, description="The original date/time of the occurrence being excepted — the instance that would have been generated by the recurrence rule.", alias="gmeow:exceptionOriginalDate")
    exceptionSchedule: list[EventSchedule] | None = Field(default=None, description="The event schedule to which this exception applies.", alias="gmeow:exceptionSchedule")


class Task(ConfiguredBaseModel):
    """Task.

    A to-do or task — an event with a due date, status, priority, and optional
    recurrence-until-done. A subtype of gmeow:Event so it participates in the full event
    spine: temporal placement, location, participation, and scheduling. The kind of task is
    a gmeow:eventType value, never a subclass (Principle 9).

    When to use:
        - Use for an iCalendar VTODO — a to-do with a due date, status, and priority that should
          inherit the full event spine (temporal placement, location, participation, scheduling).

    When to avoid:
        - Avoid for a fixed-time meeting (a plain gmeow:Event) and avoid subclassing it for the
          kind of task; the kind is a gmeow:eventType value (Principle 9).

    How to use:
        - Type it gmeow:Task (inheriting gmeow:Event), set gmeow:taskDueDate, gmeow:taskStatus,
          and gmeow:taskPriority; use gmeow:taskRecurrenceUntilDone for an open-ended recurring
          task and gmeow:eventType for its kind.

    Examples:
        - ex:fileReport a gmeow:Task ; gmeow:taskDueDate "2026-06-20T17:00:00Z"^^xsd:dateTime ;
          gmeow:taskStatus gmeow:taskStatusInProgress ; gmeow:taskPriority 1 .

    Usage:
        >>> from gmeow_models.calendar import Task
        >>> Task.model_config["json_schema_extra"]["curie"]
        'gmeow:Task'

    IRI:    https://blackcatinformatics.ca/gmeow/Task
    CURIE:  gmeow:Task

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Task", "curie": "gmeow:Task", "definitionDigest": "blake3:17bfac90ddcec84dbf92391b81169477c07e70c3e8022756fdeda055b78586cc", "iri": "https://blackcatinformatics.ca/gmeow/Task"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    taskStatus: TaskStatusEnum = Field(description="The status of the task — not-started, in-progress, completed, or cancelled.", alias="gmeow:taskStatus")


class TimeZone(ConfiguredBaseModel):
    """Time Zone.

    A time zone identified by an IANA tzid (e.g. America/Toronto). Used by calendars,
    schedules, and events to express civil time relative to a geographic reference position.

    When to use:
        - Use to name a civil offset by its IANA tzid for calendars, schedules, and events — the
          local-time anchor that decides how a UTC dateTime renders as wall-clock time.

    When to avoid:
        - Avoid conflating it with a temporal frame's gmeow:ReferencePosition at the physics layer
          (a TimeZone is the civil-offset case of one) and avoid encoding the offset numerically
          instead of naming the tzid, which loses DST rules.

    How to use:
        - Give it a gmeow:timeZoneIanaId and reference it from gmeow:calendarTimeZone,
          gmeow:scheduleTimeZone, or gmeow:eventTimeZone; let the tzid, not a fixed offset, carry
          the DST behaviour.

    Examples:
        - ex:torontoZone a gmeow:TimeZone ; gmeow:timeZoneIanaId "America/Toronto" .

    Usage:
        >>> from gmeow_models.calendar import TimeZone
        >>> TimeZone.model_config["json_schema_extra"]["curie"]
        'gmeow:TimeZone'

    IRI:    https://blackcatinformatics.ca/gmeow/TimeZone
    CURIE:  gmeow:TimeZone
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/timezone-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/TimeZone", "curie": "gmeow:TimeZone", "definitionDigest": "blake3:9930f6e41a09c96ae6a1df89cdc183edff5764ffd8a002882f88898528523f52", "iri": "https://blackcatinformatics.ca/gmeow/TimeZone"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    timeZoneIanaId: str = Field(description="The IANA time zone identifier, e.g. America/Toronto, Europe/Paris, UTC.", alias="gmeow:timeZoneIanaId")
