"""GMEOW models — slice GMEOW Connectivity Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/connectivity
Tier:       extension
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum


class RouteKindEnum(StrEnum):
    routeKindAccessible = "gmeow:routeKindAccessible"
    routeKindCitation = "gmeow:routeKindCitation"
    routeKindDependency = "gmeow:routeKindDependency"
    routeKindFlight = "gmeow:routeKindFlight"
    routeKindNetwork = "gmeow:routeKindNetwork"
    routeKindSocial = "gmeow:routeKindSocial"
    routeKindTransit = "gmeow:routeKindTransit"
    routeKindWalking = "gmeow:routeKindWalking"
