"""GMEOW models — slice GMEOW Diagnostics Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/diagnostics
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class BlockingDispositionEnum(StrEnum):
    blockingBlocking = "gmeow:blockingBlocking"
    blockingCoherent = "gmeow:blockingCoherent"


class DiagnosticSeverityEnum(StrEnum):
    severityError = "gmeow:severityError"
    severityInfo = "gmeow:severityInfo"
    severityNote = "gmeow:severityNote"
    severityWarning = "gmeow:severityWarning"


class DiagnosticStandpointEnum(StrEnum):
    standpointAdvisory = "gmeow:standpointAdvisory"
    standpointBinding = "gmeow:standpointBinding"
    standpointPerspectival = "gmeow:standpointPerspectival"


class GapShapeEnum(StrEnum):
    GapShapeExistentialWitness = "gmeow:GapShapeExistentialWitness"
    GapShapeMalformed = "gmeow:GapShapeMalformed"
    GapShapeNativeCoverage = "gmeow:GapShapeNativeCoverage"
    GapShapeRoleAssertion = "gmeow:GapShapeRoleAssertion"
    GapShapeVendoringMultiGoal = "gmeow:GapShapeVendoringMultiGoal"


class GateVerdictEnum(StrEnum):
    gateCollected = "gmeow:gateCollected"
    gateFatal = "gmeow:gateFatal"


class VerdictLatticeRelationEnum(StrEnum):
    VerdictEquivalent = "gmeow:VerdictEquivalent"
    VerdictIncomparable = "gmeow:VerdictIncomparable"
    VerdictWeaker = "gmeow:VerdictWeaker"


class Finding(ConfiguredBaseModel):
    """Finding.

    A single diagnostic — a validation violation, lint warning, reasoning divergence, or
    external-tool failure — modelled as a specialization of gmeow:Observation, the universal
    claim construct. The producing tool is the gmeow:vantage (no diagnostic is privileged; a
    finding is one tool's perspectival claim, Principle 9), the offending statement or
    construct is the gmeow:observedFeature (reached via gmeow:findingLocation), and the
    verdict is a gmeow:DiagnosticSeverity reached via gmeow:findingSeverity. A Finding is
    the gmeow: RDF projection of one Rust gmeow_diagnostics::Finding; it is never the
    canonical source (that stays in Rust so it can report on an unparsable graph), only one
    projection beside SARIF, JSON, HTML, and CLI.

    When to use:
        - Use to record a diagnostic as a first-class, queryable RDF claim — when a
          validation/lint/reasoning verdict should ride in the graph (e.g. embedded in a .gts
          feedback bundle) so it can be joined against the ontology it describes.

    When to avoid:
        - Avoid authoring Findings by hand as the source of truth — they are a projection of the
          Rust report, regenerated, never edited — and avoid using a Finding where a plain
          SARIF/CLI message suffices and no RDF query over diagnostics is needed.

    How to use:
        - Project one Finding per Rust gmeow_diagnostics::Finding: bind gmeow:findingSeverity,
          gmeow:findingCode, gmeow:findingMessage, the producing tool via gmeow:vantage (and
          gmeow:findingTool for the flat name), and gmeow:findingLocation at the reified
          statement, hanging the GTS wire coordinates on the location node.

    Examples:
        - ex:f1 a gmeow:Finding ; gmeow:findingSeverity gmeow:severityError ; gmeow:findingCode
          "shacl.MinCount" ; gmeow:vantage ex:shaclTool .

    Usage:
        >>> from gmeow_models.diagnostics import Finding
        >>> Finding.model_config["json_schema_extra"]["curie"]
        'gmeow:Finding'

    IRI:    https://blackcatinformatics.ca/gmeow/Finding
    CURIE:  gmeow:Finding

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Finding", "curie": "gmeow:Finding", "definitionDigest": "blake3:c09ce7e2e586efc8e397c71682ad6cda5c86968fcb5f6be5fb7a220df9829cee", "iri": "https://blackcatinformatics.ca/gmeow/Finding"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    findingCode: str = Field(description="The stable rule identifier of a finding (e.g. \"shacl.MinCountConstraintComponent\", \"validate.error\") — the SARIF ruleId and the key by which findings are grouped and suppressed. Short and stable across runs.", alias="gmeow:findingCode")
    findingMessage: str = Field(description="The human-readable message of a finding — the one-line description shown in CLI, SARIF, and HTML. Distinct from gmeow:findingCode (the stable rule key): the message explains this occurrence, the code names the rule.", alias="gmeow:findingMessage")
    findingSeverity: list[DiagnosticSeverityEnum] | None = Field(default=None, description="The verdict grade of a finding — a gmeow:DiagnosticSeverity individual. A subproperty of gmeow:observationResult: a finding's severity IS its observation result (the value the diagnostic observation produced), so generic observation-result consumers read it by inheritance.", alias="gmeow:findingSeverity")


class CrossNodeGlutWitness(Finding):
    """Cross-Node Glut Witness.

    A reasoner-minted meta-finding recording a cross-node glut: two findings at ONE
    gmeow:findingAnchor whose logic:FindingCategory polarities (gmeow:categoryPolarity)
    OPPOSE — a Supported/Opposed clash the same-fingerprint merge cannot detect because the
    merge keys on the code, and the two conflicting findings carry different codes. It is
    itself a gmeow:Finding (so it carries its own gmeow:findingSeverity /
    gmeow:findingStandpoint grade and gmeow:findingCategory polarity) minted by a diagnostic
    meta-rule (gmeow:DiagnosticMetaRule), never authored by hand; it links to the two
    conflicting findings through gmeow:glutWitnessOf. The glut it witnesses is a coherence
    conflict SURFACED across codes, not a gate failure.

    When to use:
        - Use as the reasoner-derived meta-finding for a cross-node glut — two opposing-polarity
          findings at one anchor the same-fingerprint merge cannot detect across codes.

    When to avoid:
        - Avoid authoring it by hand (it is minted by a gmeow:DiagnosticMetaRule from opposing
          gmeow:categoryPolarity at one gmeow:findingAnchor) and avoid reading it as a gate
          failure; it is an informational cross-code coherence witness the same-fingerprint merge
          structurally misses.

    How to use:
        - Read a CrossNodeGlutWitness off the reasoned graph: its two gmeow:glutWitnessOf links
          name the conflicting findings, and its own grade and polarity carry how the glut is
          surfaced; render it as a 'these two findings at one anchor disagree' note.

    Examples:
        - ex:glut1 a gmeow:CrossNodeGlutWitness ; gmeow:glutWitnessOf ex:f1 , ex:f2 .

    Usage:
        >>> from gmeow_models.diagnostics import CrossNodeGlutWitness
        >>> CrossNodeGlutWitness.model_config["json_schema_extra"]["curie"]
        'gmeow:CrossNodeGlutWitness'

    IRI:    https://blackcatinformatics.ca/gmeow/CrossNodeGlutWitness
    CURIE:  gmeow:CrossNodeGlutWitness

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/CrossNodeGlutWitness", "curie": "gmeow:CrossNodeGlutWitness", "definitionDigest": "blake3:8ba118b42886d57b136fd82d193805335fde00b0b723fe52b8a385e897b008cd", "iri": "https://blackcatinformatics.ca/gmeow/CrossNodeGlutWitness"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    glutWitnessOf: list[Finding] | None = Field(default=None, description="Links a gmeow:CrossNodeGlutWitness to each of the two conflicting findings it witnesses — the findings at one shared gmeow:findingAnchor whose gmeow:categoryPolarity values oppose. A glut witness carries exactly two gmeow:glutWitnessOf edges, one per side of the coherence conflict. DERIVED by a diagnostic meta-rule (gmeow:DiagnosticMetaRule), never authored by hand.", alias="gmeow:glutWitnessOf")
