"""GMEOW models — slice GMEOW Entities Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/entities
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class Organization(ConfiguredBaseModel):
    """Organization.

    A structured group of agents — a company, institution, association, or governmental body
    — able to act as a single agent.

    When to use:
        - Use for a formally structured collective that acts as one agent — a company,
          institution, association, or governmental body — when its internal structure and
          capacity to bear responsibility matter.

    When to avoid:
        - Avoid for an informal, structure-free collection of agents (use gmeow:Group instead) and
          for an individual human (use gmeow:Person); Organization is disjoint with Person and
          SoftwareAgent.

    How to use:
        - Type the body as gmeow:Organization, name it through gmeow:hasOrganizationName /
          gmeow:OrganizationName (names module) rather than the flat gmeow:name literal, and model
          departments and membership through the part/whole spine (gmeow:subOrganizationOf) and
          role relators.

    Examples:
        - ex:blackcat a gmeow:Organization ; gmeow:hasOrganizationName ex:blackcatLegalName .

    Usage:
        >>> from gmeow_models.entities import Organization
        >>> Organization.model_config["json_schema_extra"]["curie"]
        'gmeow:Organization'

    IRI:    https://blackcatinformatics.ca/gmeow/Organization
    CURIE:  gmeow:Organization

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Organization", "curie": "gmeow:Organization", "definitionDigest": "blake3:82863306b24cd56b6ff2ab36c80d8a58399186b393c581a2227a3e5bd2d4e4bc", "iri": "https://blackcatinformatics.ca/gmeow/Organization"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class Person(ConfiguredBaseModel):
    """Person.

    An individual human being, living or deceased.

    When to use:
        - Use for an individual human being who acts, authors, or is described — the human
          specialization of gmeow:Agent that supplies its own principle of identity (gufo:Kind).

    When to avoid:
        - Avoid for non-human actors (use gmeow:SoftwareAgent), for collectives (use gmeow:Group
          or gmeow:Organization), and for a merely named human role; Person is disjoint with
          Organization and SoftwareAgent.

    How to use:
        - Type the human as gmeow:Person, carry their name through the structured gmeow:hasName /
          gmeow:PersonName apparatus (names module) rather than the flat gmeow:name literal, and
          attach nationality, contributions, and contacts through their dedicated properties and
          role relators.

    Examples:
        - ex:lillith a gmeow:Person ; gmeow:hasName ex:lillithName ; gmeow:nationality ex:canada .

    Usage:
        >>> from gmeow_models.entities import Person
        >>> Person.model_config["json_schema_extra"]["curie"]
        'gmeow:Person'

    IRI:    https://blackcatinformatics.ca/gmeow/Person
    CURIE:  gmeow:Person

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Person", "curie": "gmeow:Person", "definitionDigest": "blake3:be629b5e11dacfa31f62ddc93139f67eea74cdaecc85b4ab89040d363a1b465d", "iri": "https://blackcatinformatics.ca/gmeow/Person"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class SoftwareAgent(ConfiguredBaseModel):
    """Software Agent.

    A software process or autonomous program that acts on behalf of a person or
    organization.

    When to use:
        - Use for a non-human actor — a software process, bot, model invocation, or autonomous
          program — that acts, authors, or bears provenance on behalf of a person or organization.

    When to avoid:
        - Avoid for a human actor (use gmeow:Person) and for a passive software artifact that
          carries content without acting (use gmeow:InformationObject or a software-document
          class); SoftwareAgent is disjoint with Person and Organization.

    How to use:
        - Type the actor as gmeow:SoftwareAgent and link it as the agent of its acts through
          provenance and contribution relators (e.g. the agentic slice's ModelInvocation idiom);
          attach a flat gmeow:name and its owning principal rather than the structured person-name
          apparatus.

    Examples:
        - ex:lillithBot a gmeow:SoftwareAgent ; gmeow:name "Lillith"@en .

    Usage:
        >>> from gmeow_models.entities import SoftwareAgent
        >>> SoftwareAgent.model_config["json_schema_extra"]["curie"]
        'gmeow:SoftwareAgent'

    IRI:    https://blackcatinformatics.ca/gmeow/SoftwareAgent
    CURIE:  gmeow:SoftwareAgent

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/SoftwareAgent", "curie": "gmeow:SoftwareAgent", "definitionDigest": "blake3:30226666ffce52f4a2cdbe218b7edd08e87435ac0d1bced1aadf712a0b41635e", "iri": "https://blackcatinformatics.ca/gmeow/SoftwareAgent"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
