"""GMEOW models — slice GMEOW Genealogy Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/genealogy
Tier:       extension
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class KinRelationship(ConfiguredBaseModel):
    """Kin Relationship.

    A reified kinship relationship between persons, modelled as an observation (a
    claim-from-a-vantage) in the universal stack (observation-spine bridge). Able to bear
    its own events, dates, sources, and standpoint-indexed claims. A disputed kinship is
    several coexisting gmeow:accordingTo-annotated relators, none privileged (Principle 9).
    The relationshipParent and relationshipChild are co-observed features of the
    observation.

    Usage:
        >>> from gmeow_models.genealogy import KinRelationship
        >>> KinRelationship.model_config["json_schema_extra"]["curie"]
        'gmeow:KinRelationship'

    IRI:    https://blackcatinformatics.ca/gmeow/KinRelationship
    CURIE:  gmeow:KinRelationship

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/KinRelationship", "curie": "gmeow:KinRelationship", "definitionDigest": "blake3:7f1aff9d0a99cbd425991dffcf92d772d8903b67030d75ca71616aa3d76a1f5c", "iri": "https://blackcatinformatics.ca/gmeow/KinRelationship"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    relationshipChild: list[str] = Field(min_length=1, description="The child in a reified parent-child relationship.", alias="gmeow:relationshipChild")
    relationshipParent: list[str] = Field(min_length=1, description="The parent in a reified parent-child relationship.", alias="gmeow:relationshipParent")


class ParentChildRelationship(KinRelationship):
    """Parent-Child Relationship.

    A reified parent-child relationship, typed by its nature (biological, adoptive, step, or
    foster).

    Usage:
        >>> from gmeow_models.genealogy import ParentChildRelationship
        >>> ParentChildRelationship.model_config["json_schema_extra"]["curie"]
        'gmeow:ParentChildRelationship'

    IRI:    https://blackcatinformatics.ca/gmeow/ParentChildRelationship
    CURIE:  gmeow:ParentChildRelationship

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/ParentChildRelationship", "curie": "gmeow:ParentChildRelationship", "definitionDigest": "blake3:3e62aa7a05dc8e80b534664940fe212565559612b852636c10b8081c63e8c6ef", "iri": "https://blackcatinformatics.ca/gmeow/ParentChildRelationship"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    relationshipChild: list[Person] | None = Field(default=None, description="The child in a reified parent-child relationship.", alias="gmeow:relationshipChild")
    relationshipParent: list[Person] | None = Field(default=None, description="The parent in a reified parent-child relationship.", alias="gmeow:relationshipParent")
