"""GMEOW models — slice GMEOW GTS Transport Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/gts
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class CodecClassEnum(StrEnum):
    codecClassCompress = "gmeow:codecClassCompress"
    codecClassEncode = "gmeow:codecClassEncode"
    codecClassEncrypt = "gmeow:codecClassEncrypt"


class GTSProfileEnum(StrEnum):
    gtsProfileAiPackage = "gmeow:gtsProfileAiPackage"
    gtsProfileBundle = "gmeow:gtsProfileBundle"
    gtsProfileDist = "gmeow:gtsProfileDist"
    gtsProfileEvidence = "gmeow:gtsProfileEvidence"
    gtsProfileGeneric = "gmeow:gtsProfileGeneric"
    gtsProfileImage = "gmeow:gtsProfileImage"
    gtsProfileOpaque = "gmeow:gtsProfileOpaque"


class OpacityReasonEnum(StrEnum):
    opacityDamaged = "gmeow:opacityDamaged"
    opacityMissingKey = "gmeow:opacityMissingKey"
    opacityUnknownCodec = "gmeow:opacityUnknownCodec"


class TransformCodecEnum(StrEnum):
    codecBase64 = "gmeow:codecBase64"
    codecBase85 = "gmeow:codecBase85"
    codecCoseEncrypt0 = "gmeow:codecCoseEncrypt0"
    codecGzip = "gmeow:codecGzip"
    codecIdentity = "gmeow:codecIdentity"
    codecLzma2 = "gmeow:codecLzma2"
    codecZstd = "gmeow:codecZstd"


class GTSDocument(ConfiguredBaseModel):
    """GTS Document.

    A single-file Graph Transport Substrate artifact (docs/GTS-SPEC.md): a CBOR Sequence of
    one or more append-only segments carrying an RDF 1.2 graph and any content-addressed
    binaries it references. A Manifestation in the WEMI sense — the packaged, shippable
    embodiment. Its composite identity is the ORDERED list of its segments' chain heads
    (spec §3.1); byte-concatenation of valid documents is a valid document, so a document's
    segment list grows by append, never by rewrite.

    When to use:
        - Use to model a whole shippable GTS file as a first-class entity — when you need to talk
          about the package itself (its segment list, its composite identity, its provenance)
          rather than the individual frames or the graph it carries.

    When to avoid:
        - Avoid for a single log within the file (use gmeow:GTSSegment) and for the content claims
          the document carries (those are ordinary quads); the document is the transport envelope,
          never the truth of its payload.

    How to use:
        - Link its ordered segments with gmeow:gtsSegment and read its composite identity off the
          segment heads (gmeow:gtsHeadId taken in gmeow:gtsSegmentIndex order); record production
          and compaction lineage with gmeow:wasGeneratedBy / gmeow:wasDerivedFrom rather than on
          the segments.

    Examples:
        - ex:bundle a gmeow:GTSDocument ; gmeow:gtsSegment ex:seg0 .

    Usage:
        >>> from gmeow_models.gts import GTSDocument
        >>> GTSDocument.model_config["json_schema_extra"]["curie"]
        'gmeow:GTSDocument'

    IRI:    https://blackcatinformatics.ca/gmeow/GTSDocument
    CURIE:  gmeow:GTSDocument

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/GTSDocument", "curie": "gmeow:GTSDocument", "definitionDigest": "blake3:4db0458088190dbdfcad5fad3f77940d5698b56e4eac8cd1b10b2891642541c5", "iri": "https://blackcatinformatics.ca/gmeow/GTSDocument"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class GTSSegment(ConfiguredBaseModel):
    """GTS Segment.

    One complete header-plus-frames log inside a GTS document — the unit of independent
    integrity (spec §3.1): a segment has its own genesis hash, its own id/prev chain, its
    own profile, its own transform catalog, and its own signers. Segments compose by
    concatenation and never vouch for one another; a third-party segment keeps its
    third-party attestation. Itself a Manifestation: a segment is a complete, independently
    shippable artifact.

    When to use:
        - Use for one independently-verifiable log within a document — the unit that carries its
          own chain, profile, codec catalog, and signers, and the subject a transport Attestation
          vouches for.

    When to avoid:
        - Avoid for the whole file (use gmeow:GTSDocument) and for a single frame; never make one
          segment vouch for another — each keeps its own attestation by design.

    How to use:
        - Place it in its document with gmeow:gtsSegmentOf, order it with gmeow:gtsSegmentIndex,
          commit its history with gmeow:gtsHeadId, declare its purpose with gmeow:gtsProfile, and
          attach signatures as gmeow:hasSignature / gmeow:Attestation whose attestedSubject is
          this segment.

    Examples:
        - ex:seg0 a gmeow:GTSSegment ; gmeow:gtsSegmentOf ex:bundle ; gmeow:gtsHeadId
          "blake3:9f2c…" .

    Usage:
        >>> from gmeow_models.gts import GTSSegment
        >>> GTSSegment.model_config["json_schema_extra"]["curie"]
        'gmeow:GTSSegment'

    IRI:    https://blackcatinformatics.ca/gmeow/GTSSegment
    CURIE:  gmeow:GTSSegment
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/gtssegment-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/GTSSegment", "curie": "gmeow:GTSSegment", "definitionDigest": "blake3:0b55168ff369e46bab4390c10254c9e7373443bd0e79d38892f4bb6fdb936322", "iri": "https://blackcatinformatics.ca/gmeow/GTSSegment"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    gtsHeadId: str = Field(description="The chain head of a segment — the content-id of its last frame, written 'blake3:<hex>'. Transitively commits to the segment's entire history (spec §9.1), making it a version fingerprint of the segment rather than a digest of its bytes: hence a subproperty of gmeow:versionFingerprint, distinct from gmeow:contentDigest (which is byte-exact identity and applies to the file or a blob as a whole). Functional: a segment has exactly one head. It is also the key of a gmeow:GTSSegment (owl:hasKey on the class): the head is a BLAKE3 content-id committing transitively to the segment's whole frame history, so two distinct segments sharing a head would be a full-history BLAKE3 collision — impossible by construction; the head therefore uniquely identifies its segment (content-addressing IS the identity). A datatype key is stated as owl:hasKey (OWL 2 DL) rather than owl:InverseFunctionalProperty (which on a datatype property would be OWL 2 Full).", alias="gmeow:gtsHeadId")
    gtsProfile: list[GTSProfileEnum] | None = Field(default=None, description="The declared profile of a segment (spec §13) — a value vocabulary individual naming the segment's purpose and requirement set. Functional per segment; a multi-segment DOCUMENT's effective requirement set is the union of its segments' profiles (spec §3.1) and is derived, never asserted.", alias="gmeow:gtsProfile")
    gtsSegmentIndex: int = Field(description="The zero-based position of a segment within its document's file order. The ordered list of segment heads — gmeow:gtsHeadId taken in gmeow:gtsSegmentIndex order — IS the document's composite identity (spec §3.1).", alias="gmeow:gtsSegmentIndex")


class OpaqueFrame(ConfiguredBaseModel):
    """Opaque Frame.

    A sealed or undecodable region of a GTS segment, surfaced by the reader as a first-class
    object rather than dropped (spec §7.6): an encrypted frame the reader holds no key for,
    a frame using a codec the reader lacks, or a damaged frame. Opacity is VANTAGE-RELATIVE
    epistemic state, not a property of the bytes — the same frame is transparent to a
    recipient holding the key (standpoint/privacy, Principle 9). The frame's bytes remain
    present, hash-linked, and chain-verifiable.

    When to use:
        - Use when a reader surfaces a frame it cannot decode — sealed without a key, using an
          unknown codec, or damaged — so the gap is described rather than silently dropped,
          preserving the chain.

    When to avoid:
        - Avoid asserting opacity as a property of the bytes themselves — it is vantage-relative,
          true only for the describing reader; do not use it for a frame the reader decoded
          successfully, nor as a privacy classification (that is the kernel sensitivity/disclosure
          axes).

    How to use:
        - Anchor it to its segment with gmeow:opaqueFrameIn, state the required
          gmeow:opacityReason, and for sealed frames list the agents who can decrypt it with
          gmeow:sealedRecipient so the vantage-relativity is explicit.

    Examples:
        - ex:frame7 a gmeow:OpaqueFrame ; gmeow:opaqueFrameIn ex:seg0 ; gmeow:opacityReason
          gmeow:opacityMissingKey .

    Usage:
        >>> from gmeow_models.gts import OpaqueFrame
        >>> OpaqueFrame.model_config["json_schema_extra"]["curie"]
        'gmeow:OpaqueFrame'

    IRI:    https://blackcatinformatics.ca/gmeow/OpaqueFrame
    CURIE:  gmeow:OpaqueFrame

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/OpaqueFrame", "curie": "gmeow:OpaqueFrame", "definitionDigest": "blake3:8afdd495b1de9f269b92f668a11b29cd91d05069fd1ff5154518fe71e64c13c6", "iri": "https://blackcatinformatics.ca/gmeow/OpaqueFrame"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    opacityReason: list[OpacityReasonEnum] | None = Field(default=None, description="Why a frame is opaque to the describing reader (spec §7.6): an encrypt-class codec without a key, a codec the reader lacks, or damage. Functional and REQUIRED (see shapes): opacity without a stated reason is indistinguishable from data loss.", alias="gmeow:opacityReason")
    opaqueFrameIn: list[GTSSegment] | None = Field(default=None, description="The GTS segment an opaque frame belongs to. Functional: a frame occupies one position in one segment's chain.", alias="gmeow:opaqueFrameIn")
