"""GMEOW models — slice GMEOW Mentation Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/mentation
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum


class MentalProcessTypeEnum(StrEnum):
    processAffectiveExperience = "gmeow:processAffectiveExperience"
    processAttention = "gmeow:processAttention"
    processAudit = "gmeow:processAudit"
    processDeliberation = "gmeow:processDeliberation"
    processDreaming = "gmeow:processDreaming"
    processExport = "gmeow:processExport"
    processImagining = "gmeow:processImagining"
    processLearning = "gmeow:processLearning"
    processMindWandering = "gmeow:processMindWandering"
    processPerception = "gmeow:processPerception"
    processReasoning = "gmeow:processReasoning"
    processRecollection = "gmeow:processRecollection"
    processTraining = "gmeow:processTraining"
