"""GMEOW models — slice GMEOW Notes & Annotation Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/notes
Tier:       extension
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class AnnotationMotivationEnum(StrEnum):
    motivationAssessing = "gmeow:motivationAssessing"
    motivationBookmarking = "gmeow:motivationBookmarking"
    motivationCommenting = "gmeow:motivationCommenting"
    motivationDescribing = "gmeow:motivationDescribing"
    motivationHighlighting = "gmeow:motivationHighlighting"
    motivationLinking = "gmeow:motivationLinking"
    motivationModerating = "gmeow:motivationModerating"
    motivationQuestioning = "gmeow:motivationQuestioning"
    motivationReplying = "gmeow:motivationReplying"
    motivationTagging = "gmeow:motivationTagging"


class Annotation(ConfiguredBaseModel):
    """Annotation.

    A reified binding of a body to a target with a motivation — the W3C Web Annotation idiom
    expressed as a gufo:Relator. Mediates annotationBody (the note or literal),
    annotationTarget (the annotated entity), and annotationMotivation (the purpose). A
    highlight is an Annotation with a target span but no body; a bookmark is an Annotation
    motivated by bookmarking. Standpoint, confidence, and suppression are carried by the
    relator's provenance layer (accordingTo, displayable) or by RDF-star annotations on the
    shortcut.

    Usage:
        >>> from gmeow_models.notes import Annotation
        >>> Annotation.model_config["json_schema_extra"]["curie"]
        'gmeow:Annotation'

    IRI:    https://blackcatinformatics.ca/gmeow/Annotation
    CURIE:  gmeow:Annotation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Annotation", "curie": "gmeow:Annotation", "definitionDigest": "blake3:b3feaa840482e1e6274ce66cf82119c1aa7992675914eef53c1153d82cbca9fd", "iri": "https://blackcatinformatics.ca/gmeow/Annotation"},
    )


class Note(ConfiguredBaseModel):
    """Note.

    A piece of content in a personal or collective knowledge graph — an annotation body, a
    Zettelkasten card, a comment, or a standalone thought. Grounded as an information object
    whose authorship is mediated by Participation / wasAttributedTo, whose temporal scope is
    carried by the four clocks, and whose standpoint is indexed by accordingTo. Reuses
    isAbout and hasTag / Tagging for topic and tagging; does not mint parallel properties.

    Usage:
        >>> from gmeow_models.notes import Note
        >>> Note.model_config["json_schema_extra"]["curie"]
        'gmeow:Note'

    IRI:    https://blackcatinformatics.ca/gmeow/Note
    CURIE:  gmeow:Note

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Note", "curie": "gmeow:Note", "definitionDigest": "blake3:9b2217858d6f81ed04eddb7afb8a112838b5876ebc4923214897abfa3abff218", "iri": "https://blackcatinformatics.ca/gmeow/Note"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class Comment(Note):
    """Comment.

    A note that replies to an annotation or another comment — a threaded discussion node.
    Every Comment has exactly one commentParent (the annotation or comment being replied
    to). The transitive hasReply reaches all descendants in the thread. A note without a
    parent is a plain Note, not a Comment.

    Usage:
        >>> from gmeow_models.notes import Comment
        >>> Comment.model_config["json_schema_extra"]["curie"]
        'gmeow:Comment'

    IRI:    https://blackcatinformatics.ca/gmeow/Comment
    CURIE:  gmeow:Comment

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Comment", "curie": "gmeow:Comment", "definitionDigest": "blake3:2719d2c378ae364d656e6dff90d16e5ca1f4963adc189516af3098bc611faa7b", "iri": "https://blackcatinformatics.ca/gmeow/Comment"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    commentParent: Any = Field(description="The annotation or comment that this comment replies to. Every Comment has exactly one commentParent. The range is gmeow:Entity (encompassing Annotation and Comment) so that a comment may reply to any annotatable entity without identity clash.", alias="gmeow:commentParent")


class Highlight(Annotation):
    """Highlight.

    An annotation that marks an anchored span within a target and carries no body — a pure
    target+selector binding motivated by highlighting.

    Usage:
        >>> from gmeow_models.notes import Highlight
        >>> Highlight.model_config["json_schema_extra"]["curie"]
        'gmeow:Highlight'

    IRI:    https://blackcatinformatics.ca/gmeow/Highlight
    CURIE:  gmeow:Highlight

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Highlight", "curie": "gmeow:Highlight", "definitionDigest": "blake3:779e2b6ba658f171b5b7d948594460b472751cd85a4457a45976848d6bc02c19", "iri": "https://blackcatinformatics.ca/gmeow/Highlight"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    annotationTargetSpan: list[str] = Field(min_length=1, description="Within gmeow:Highlight, values are node references constrained to gmeow:EvidenceSpan. An optional anchored span within the annotation target — a text quote, position, or fragment selector. Non-functional: an annotation may reference multiple spans (e.g. several disjoint highlights in the same document). Reuses EvidenceSpan and its selector properties; no second selector model is minted.", alias="gmeow:annotationTargetSpan")
