"""GMEOW models — slice GMEOW Observations Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/observations
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class GenericQualityEnum(StrEnum):
    pressure = "gmeow:pressure"


class ObservablePropertyEnum(StrEnum):
    observablePropertyAirQualityIndex = "gmeow:observablePropertyAirQualityIndex"
    observablePropertyAtmosphericPressure = "gmeow:observablePropertyAtmosphericPressure"
    observablePropertyHumidity = "gmeow:observablePropertyHumidity"
    observablePropertyLightIntensity = "gmeow:observablePropertyLightIntensity"
    observablePropertyLoudness = "gmeow:observablePropertyLoudness"
    observablePropertyRadiationLevel = "gmeow:observablePropertyRadiationLevel"
    observablePropertyRoughness = "gmeow:observablePropertyRoughness"
    observablePropertySoundPressureLevel = "gmeow:observablePropertySoundPressureLevel"
    observablePropertyTemperature = "gmeow:observablePropertyTemperature"
    observablePropertyTimbre = "gmeow:observablePropertyTimbre"
    observablePropertyTimingDeviation = "gmeow:observablePropertyTimingDeviation"


class ObservationMethodEnum(StrEnum):
    methodComputationalModel = "gmeow:methodComputationalModel"
    methodDirectObservation = "gmeow:methodDirectObservation"
    methodExpertJudgement = "gmeow:methodExpertJudgement"
    methodGNSSRTK = "gmeow:methodGNSSRTK"
    methodGPS = "gmeow:methodGPS"
    methodInstrumentalReading = "gmeow:methodInstrumentalReading"
    methodLiDAR = "gmeow:methodLiDAR"
    methodLlmExtraction = "gmeow:methodLlmExtraction"
    methodNliDerivation = "gmeow:methodNliDerivation"
    methodPhotogrammetry = "gmeow:methodPhotogrammetry"
    methodRemoteSensing = "gmeow:methodRemoteSensing"
    methodStreaming = "gmeow:methodStreaming"
    methodSurvey = "gmeow:methodSurvey"
    methodTotalStation = "gmeow:methodTotalStation"


class ObservationTypeEnum(StrEnum):
    observationTypeDerived = "gmeow:observationTypeDerived"
    observationTypeIdentity = "gmeow:observationTypeIdentity"
    observationTypeKinship = "gmeow:observationTypeKinship"
    observationTypeMeasurement = "gmeow:observationTypeMeasurement"
    observationTypeNaming = "gmeow:observationTypeNaming"
    observationTypeRights = "gmeow:observationTypeRights"
    observationTypeSensory = "gmeow:observationTypeSensory"
    observationTypeSimulation = "gmeow:observationTypeSimulation"
    observationTypeStandpoint = "gmeow:observationTypeStandpoint"
    observationTypeStreaming = "gmeow:observationTypeStreaming"


class Observation(ConfiguredBaseModel):
    """Observation.

    A reified act of observing, measuring, or asserting a feature of interest — the
    universal claim construct unifying spatial measurement, temporal dating, sensory
    reading, standpoint claims, identity claims, naming claims, rights claims, and kinship
    claims. Mediates between an observer (vantage), a feature (observedFeature), and a
    result (observationResult). Every observation carries at least a vantage and an
    observedFeature (EL open-world); closed-world cardinality is SHACL's concern.

    When to use:
        - Use as the universal claim spine whenever a value is HELD by some vantage rather than
          asserted as a global fact — a measurement, a sensory reading, a standpoint, an
          identity/name/rights/kinship claim — so the claim carries its observer, feature, and
          result explicitly (Principle 9: every value is perspectival, none privileged).

    When to avoid:
        - Avoid when the relationship is genuinely frame-free and uncontested (assert the flat
          triple and reify on demand); for a domain-specific claim prefer the matching Observation
          subclass (Measurement, SensoryObservation, StandpointClaim, NameUsage, IdentityFacet) so
          the bridged role properties carry their local typing.

    How to use:
        - Mint one Observation per held claim, bind gmeow:vantage and gmeow:observedFeature (the
          EL minimum), add gmeow:observationResult, gmeow:observationMethod,
          gmeow:observationType, evidence, and statement metadata as needed; specialized
          subclasses inherit these roles through rdfs:subPropertyOf bridges so generic consumers
          query 'all observations about X' uniformly.

    Examples:
        - ex:reading a gmeow:Observation ; gmeow:vantage ex:sensor ; gmeow:observedFeature ex:room
          ; gmeow:observationResult ex:temp22 .

    Usage:
        >>> from gmeow_models.observations import Observation
        >>> Observation.model_config["json_schema_extra"]["curie"]
        'gmeow:Observation'

    IRI:    https://blackcatinformatics.ca/gmeow/Observation
    CURIE:  gmeow:Observation
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/observation-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Observation", "curie": "gmeow:Observation", "definitionDigest": "blake3:01ef6ea64751a4c1b4e860f50e0442d3080a5b27ddaf69848137dcd1f6492fea", "iri": "https://blackcatinformatics.ca/gmeow/Observation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observedAt: datetime | None = Field(default=None, description="The time index of a dated gmeow:Observation — when this reading of its persistent gmeow:Quality was taken. Functional: one observation, one time index. The dating that turns a quality's observations into an ordered value-history (gmeow:observationOf supplies the quality; this supplies the time).", alias="gmeow:observedAt")
    observedFeature: list[str] | None = Field(default=None, description="The individual whose property or state is being observed — the feature of interest. The range is intentionally open (owl:Thing) because anything can be observed: a place, a person, an event, a document, a quality value, or a situation. SHACL shapes enforce closed-world constraints per observation kind.", alias="gmeow:observedFeature")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class Measurement(Observation):
    """Measurement.

    An observation that assigns a quantitative or qualitative value to a feature of
    interest, typically carrying a unit, uncertainty, and determinacy model. The parent of
    temporal dating, spatial coordinate assignment, and scalar quantity measurements.

    When to use:
        - Use when an observation assigns a value to its feature — a dating, a coordinate fix, a
          scalar reading — so the claim inherits the observation roles while signalling it is a
          quantified/qualified measurement carrying unit, uncertainty, and determinacy.

    When to avoid:
        - Avoid for a bare standpoint assertion with no assigned value (use gmeow:StandpointClaim)
          or a raw sensor reading you want typed as such (gmeow:SensoryObservation); specialize
          further to gmeow:TemporalMeasurement or a spatial coordinate measurement where the slice
          provides one.

    How to use:
        - Type the act gmeow:Measurement, make gmeow:observationResult a math:Quantity carrying
          math:quantityValue plus the applicable gmeow:unit, gmeow:hasDeterminacy, and
          gmeow:quantityUncertainty qualifiers, and let domain slices deepen it with their own
          measurement subclasses and seeds.

    Examples:
        - ex:tempReading a gmeow:Measurement ; gmeow:observationResult ex:temp22 .

    Usage:
        >>> from gmeow_models.observations import Measurement
        >>> Measurement.model_config["json_schema_extra"]["curie"]
        'gmeow:Measurement'

    IRI:    https://blackcatinformatics.ca/gmeow/Measurement
    CURIE:  gmeow:Measurement

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Measurement", "curie": "gmeow:Measurement", "definitionDigest": "blake3:166b8f4c5ea72771077b0030895d3d395c2095dde9a351c72a4f3fea3126b772", "iri": "https://blackcatinformatics.ca/gmeow/Measurement"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observationMethod: ObservationMethodEnum = Field(description="The method or protocol used to produce the observation. Functional: one method per observation (compound protocols are modelled as a single fused method individual, e.g. 'GPS-RTK survey with ground control'). Distinct from gmeow:vantage: the method is *how* it was done, the vantage is *who* did it.", alias="gmeow:observationMethod")


class MonetaryAmount(ConfiguredBaseModel):
    """Monetary Amount.

    A quantity of money expressed as a decimal value in an explicit currency reference
    frame. The canonical superset of schema:MonetaryAmount and FIBO
    fibo-fnd-acc-cur:MonetaryAmount. Frame-relative (Principle 11): a value without its
    currency frame is ill-formed.

    When to use:
        - Use for any quantity of money — a price, salary, fee, balance — so the amount always
          travels with its currency frame; consumed by employment, agreements, and finance alike
          (it lives on the measurement spine, not in a finance silo).

    When to avoid:
        - Avoid for a unit-bearing physical quantity (use math:Quantity with math:quantityValue
          and gmeow:unit) and avoid stating a bare amount without gmeow:currency — a value without
          its currency frame is ill-formed (Principle 11).

    How to use:
        - Mint the amount, set gmeow:monetaryValue (xsd:decimal) and the required gmeow:currency
          reference frame; the generated frame-relativity shape (gmeow:requiresFrame) enforces
          exactly the currency the amount is denominated in.

    Examples:
        - ex:price a gmeow:MonetaryAmount ; gmeow:monetaryValue 19.99 ; gmeow:currency ex:usd .

    Usage:
        >>> from gmeow_models.observations import MonetaryAmount
        >>> MonetaryAmount.model_config["json_schema_extra"]["curie"]
        'gmeow:MonetaryAmount'

    IRI:    https://blackcatinformatics.ca/gmeow/MonetaryAmount
    CURIE:  gmeow:MonetaryAmount

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/MonetaryAmount", "curie": "gmeow:MonetaryAmount", "definitionDigest": "blake3:600b382077b61e129412eb8b0e13b2a1236b4883dc31672215d094d62bed4c32", "iri": "https://blackcatinformatics.ca/gmeow/MonetaryAmount"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    currency: list[ReferenceFrame] | None = Field(default=None, description="The currency reference frame in which this monetary amount is expressed. Functional: a MonetaryAmount is in exactly one currency frame. A subproperty of gmeow:hasReferenceFrame (Principle 11).", alias="gmeow:currency")
    monetaryValue: float = Field(description="The numeric value of a monetary amount as an xsd:decimal. Functional: a MonetaryAmount has exactly one numeric value.", alias="gmeow:monetaryValue")


class SensoryObservation(Observation):
    """Sensory Observation.

    An observation produced by a sensor or sensory apparatus reading a physical property of
    the environment. Specialises Observation with sensor-specific properties (sensory
    property, sensor platform, sampling feature).

    When to use:
        - Use when the observation is a reading taken by a sensor or sensory apparatus of a
          physical property of the environment — the form that travels in a gmeow:Stream and
          carries sensor/platform/sampling-feature detail.

    When to avoid:
        - Avoid for a human judgement or a derived/computed value (use gmeow:Measurement with the
          matching gmeow:observationType) and for a standpoint assertion (gmeow:StandpointClaim);
          this kind is specifically instrument-mediated sensing.

    How to use:
        - Type the reading gmeow:SensoryObservation, put the sensor or platform in gmeow:vantage
          (or gmeow:streamSensor / gmeow:streamPlatform when streamed), and attach the value as a
          math:Quantity result; group time-ordered readings under a gmeow:Stream.

    Examples:
        - ex:humidityReading a gmeow:SensoryObservation ; gmeow:vantage ex:hygrometer .

    Usage:
        >>> from gmeow_models.observations import SensoryObservation
        >>> SensoryObservation.model_config["json_schema_extra"]["curie"]
        'gmeow:SensoryObservation'

    IRI:    https://blackcatinformatics.ca/gmeow/SensoryObservation
    CURIE:  gmeow:SensoryObservation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/SensoryObservation", "curie": "gmeow:SensoryObservation", "definitionDigest": "blake3:f0022e01760b59828db7f8663d93b86a8ae3fa5dce8bd368639021ae5d80f7df", "iri": "https://blackcatinformatics.ca/gmeow/SensoryObservation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observationMethod: ObservationMethodEnum = Field(description="The method or protocol used to produce the observation. Functional: one method per observation (compound protocols are modelled as a single fused method individual, e.g. 'GPS-RTK survey with ground control'). Distinct from gmeow:vantage: the method is *how* it was done, the vantage is *who* did it.", alias="gmeow:observationMethod")
    sensoryObservationOf: list[Entity] | None = Field(default=None, description="The entity whose property is being observed — the observedFeature of a sensory observation. Subproperty of gmeow:observedFeature so generic consumers can query all observations without knowing the domain.", alias="gmeow:sensoryObservationOf")
    sensoryProperty: list[ObservablePropertyEnum] | None = Field(default=None, description="The observable property that a sensory observation measures — temperature, humidity, light intensity, etc. Distinct from gmeow:observationMethod (the procedure or protocol used); this names the property itself. A sensory observation concerns exactly one observable property per observation; multiple properties require multiple observations (Principle 9).", alias="gmeow:sensoryProperty")
    sensoryResult: list[str] | None = Field(default=None, description="Within gmeow:SensoryObservation, values are node references constrained to gmeow:SensoryQuantity. The scalar quantity result of a sensory observation — a value with unit, determinacy, and granularity. Subproperty of gmeow:observationResult so generic consumers can query all observation results without knowing the domain. The reference frame in which the quantity is expressed is carried on the observation via gmeow:hasReferenceFrame and propagates to the result via the existing isResultOf ∘ hasReferenceFrame chain.", alias="gmeow:sensoryResult")
    vantage: list[Agent] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class StandpointClaim(Observation):
    """Standpoint Claim.

    An observation made from a specific standpoint or frame — an assertion, denial, or
    qualified position that a proposition holds. Realises the standpoint side of Principle 3
    (Observation ≡ Measurement ≡ Standpoint). The vantage is the standpoint; the
    observedFeature is the proposition or fact being claimed; the observationResult is the
    modality (unequivocal, probable, conceivable, refuted).

    When to use:
        - Use when a proposition is asserted, denied, or held with a qualified modality FROM a
          standpoint — the perspectival claim form where the value produced is a doxastic modality
          rather than a measured quantity (Principle 9: no standpoint privileged).

    When to avoid:
        - Avoid for a value-assigning reading (gmeow:Measurement / gmeow:SensoryObservation) and
          for marking a proposition false by fiat — a falsehood is a refuted StandpointClaim
          (modality refuted), never an isFalse flag; competing standpoints coexist rather than
          resolve.

    How to use:
        - Put the standpoint in gmeow:vantage, the proposition or fact in gmeow:observedFeature,
          and a modality value (unequivocal, probable, conceivable, refuted) in
          gmeow:observationResult; record a contested fact as several coexisting StandpointClaims,
          each with its own gmeow:accordingTo.

    Examples:
        - ex:claim a gmeow:StandpointClaim ; gmeow:vantage ex:authorityA ; gmeow:observedFeature
          ex:proposition .

    Usage:
        >>> from gmeow_models.observations import StandpointClaim
        >>> StandpointClaim.model_config["json_schema_extra"]["curie"]
        'gmeow:StandpointClaim'

    IRI:    https://blackcatinformatics.ca/gmeow/StandpointClaim
    CURIE:  gmeow:StandpointClaim
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/standpointclaim-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/StandpointClaim", "curie": "gmeow:StandpointClaim", "definitionDigest": "blake3:66d8fcfd7961ae12988109e2867f5e304daf74cd1f5fec5014c1f246adc5fc0e", "iri": "https://blackcatinformatics.ca/gmeow/StandpointClaim"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class Stream(ConfiguredBaseModel):
    """Stream.

    A time-ordered sequence of observations or samples produced by a sensor or platform over
    a time interval. The ordering of samples is implicit via their individual timestamps,
    not asserted as a list structure (Principle 12). A stream is the canonical source from
    which a continuous trajectory may be derived by the solver layer.

    When to use:
        - Use to group a time-ordered run of observations or samples about one entity from a
          sensor or platform — the canonical source a solver derives a continuous trajectory from
          (no list structure is asserted).

    When to avoid:
        - Avoid for a single isolated reading (use a bare Observation) and avoid encoding sample
          order as an RDF list — ordering is implicit via each sample's timestamp (Principle 12),
          and the interpolated trajectory is a solver concern.

    How to use:
        - Mint the Stream, bind its subject with the functional gmeow:streamOf, attach readings
          via gmeow:streamSample, name gmeow:streamPlatform / gmeow:streamSensor, and bound it
          with the functional gmeow:streamInterval; an entity reaches its streams through
          gmeow:hasStream.

    Examples:
        - ex:roverTrack a gmeow:Stream ; gmeow:streamOf ex:rover ; gmeow:streamSample ex:fix1 .

    Usage:
        >>> from gmeow_models.observations import Stream
        >>> Stream.model_config["json_schema_extra"]["curie"]
        'gmeow:Stream'

    IRI:    https://blackcatinformatics.ca/gmeow/Stream
    CURIE:  gmeow:Stream

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Stream", "curie": "gmeow:Stream", "definitionDigest": "blake3:2d3bb1c8fd6d1d607f43d037feed97e5abf1826e835065d6b7ff2a421cef424e", "iri": "https://blackcatinformatics.ca/gmeow/Stream"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    streamOf: list[Entity] | None = Field(default=None, description="The entity whose observations the stream contains — the moving feature, device, or thing being tracked. Functional: a stream belongs to exactly one entity.", alias="gmeow:streamOf")
