"""GMEOW models — slice GMEOW Observations Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/observations
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class GenericQualityEnum(StrEnum):
    pressure = "gmeow:pressure"


class ObservationMethodEnum(StrEnum):
    methodComputationalModel = "gmeow:methodComputationalModel"
    methodDirectObservation = "gmeow:methodDirectObservation"
    methodExpertJudgement = "gmeow:methodExpertJudgement"
    methodGNSSRTK = "gmeow:methodGNSSRTK"
    methodGPS = "gmeow:methodGPS"
    methodInstrumentalReading = "gmeow:methodInstrumentalReading"
    methodLiDAR = "gmeow:methodLiDAR"
    methodLlmExtraction = "gmeow:methodLlmExtraction"
    methodNliDerivation = "gmeow:methodNliDerivation"
    methodPhotogrammetry = "gmeow:methodPhotogrammetry"
    methodRemoteSensing = "gmeow:methodRemoteSensing"
    methodStreaming = "gmeow:methodStreaming"
    methodSurvey = "gmeow:methodSurvey"
    methodTotalStation = "gmeow:methodTotalStation"


class ObservationTypeEnum(StrEnum):
    observationTypeDerived = "gmeow:observationTypeDerived"
    observationTypeIdentity = "gmeow:observationTypeIdentity"
    observationTypeKinship = "gmeow:observationTypeKinship"
    observationTypeMeasurement = "gmeow:observationTypeMeasurement"
    observationTypeNaming = "gmeow:observationTypeNaming"
    observationTypeRights = "gmeow:observationTypeRights"
    observationTypeSensory = "gmeow:observationTypeSensory"
    observationTypeSimulation = "gmeow:observationTypeSimulation"
    observationTypeStandpoint = "gmeow:observationTypeStandpoint"
    observationTypeStreaming = "gmeow:observationTypeStreaming"


class Magnitude(ConfiguredBaseModel):
    """Magnitude.

    The frame-independent true quantity a measurement is of — the magnitude that exists
    prior to any unit or reference frame (the pressure itself, not its reading in mmHg). The
    domain grounding of logic:trueQuantity (Principle 17): a measured value points at its
    Magnitude via gmeow:trueQuantity, and the Magnitude carries only its gmeow:dimension
    (the generic quality it is a magnitude of), never a value, unit, or frame — those are
    the frame-relative facets carried on the measured value (Principle 11). The same
    Magnitude round-trips across unit systems without re-identification.

    When to use:
        - Use to name the frame-independent magnitude a measurement is of — the YAMATO true
          quantity, distinct from the value+unit+frame measured value — so the same quantity is
          shared across readings in different unit systems.

    When to avoid:
        - Avoid putting a value, unit, or reference frame on the Magnitude (those belong on the
          measured value — the Magnitude is frame-independent by construction) and avoid minting
          one where a plain framed math:Quantity suffices; reach for it when the unit-independent
          magnitude must be named in its own right.

    How to use:
        - Mint the Magnitude, set gmeow:dimension to the generic quality it is a magnitude of, and
          point the framed measured value at it via gmeow:trueQuantity; keep value, unit, and
          frame on the measured value, not here.

    Examples:
        - ex:bpMagnitude a gmeow:Magnitude ; gmeow:dimension gmeow:pressure .

    Usage:
        >>> from gmeow_models.observations import Magnitude
        >>> Magnitude.model_config["json_schema_extra"]["curie"]
        'gmeow:Magnitude'

    IRI:    https://blackcatinformatics.ca/gmeow/Magnitude
    CURIE:  gmeow:Magnitude

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Magnitude", "curie": "gmeow:Magnitude", "definitionDigest": "blake3:5d9bacd5148c5527db47f5d8ccf23331bed47db72c18b71cc72dfee53f8e013d", "iri": "https://blackcatinformatics.ca/gmeow/Magnitude"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    dimension: Any | None = Field(default=None, description="Relates a gmeow:Magnitude to the generic quality it is a magnitude of — pressure, length, mass. Functional: a magnitude is of exactly one dimension. The frame-independent quality kind (a logic:genericQuality target, aligned by reference to qudt:QuantityKind), distinct from the contextual quality-role the value plays and from the unit it is read in. Range a generic quality (stated in prose, matching the module's convention).", alias="gmeow:dimension")


class Observation(ConfiguredBaseModel):
    """Observation.

    A reified act of observing, measuring, or asserting a feature of interest — the
    universal claim construct unifying spatial measurement, temporal dating, sensory
    reading, standpoint claims, identity claims, naming claims, rights claims, and kinship
    claims. Mediates between an observer (vantage), a feature (observedFeature), and a
    result (observationResult). Every observation carries at least a vantage and an
    observedFeature (EL open-world); closed-world cardinality is SHACL's concern.

    When to use:
        - Use as the universal claim spine whenever a value is HELD by some vantage rather than
          asserted as a global fact — a measurement, a sensory reading, a standpoint, an
          identity/name/rights/kinship claim — so the claim carries its observer, feature, and
          result explicitly (Principle 9: every value is perspectival, none privileged).

    When to avoid:
        - Avoid when the relationship is genuinely frame-free and uncontested (assert the flat
          triple and reify on demand); for a domain-specific claim prefer the matching Observation
          subclass (Measurement, SensoryObservation, StandpointClaim, NameUsage, IdentityFacet) so
          the bridged role properties carry their local typing.

    How to use:
        - Mint one Observation per held claim, bind gmeow:vantage and gmeow:observedFeature (the
          EL minimum), add gmeow:observationResult, gmeow:observationMethod,
          gmeow:observationType, evidence, and statement metadata as needed; specialized
          subclasses inherit these roles through rdfs:subPropertyOf bridges so generic consumers
          query 'all observations about X' uniformly.

    Examples:
        - ex:reading a gmeow:Observation ; gmeow:vantage ex:sensor ; gmeow:observedFeature ex:room
          ; gmeow:observationResult ex:temp22 .

    Usage:
        >>> from gmeow_models.observations import Observation
        >>> Observation.model_config["json_schema_extra"]["curie"]
        'gmeow:Observation'

    IRI:    https://blackcatinformatics.ca/gmeow/Observation
    CURIE:  gmeow:Observation
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/observation-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Observation", "curie": "gmeow:Observation", "definitionDigest": "blake3:3bca512f4dd0b22ce02fa7578da4a29caca9d5ea4d7178dcd681eab9031ebefb", "iri": "https://blackcatinformatics.ca/gmeow/Observation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observedFeature: list[str] | None = Field(default=None, description="The individual whose property or state is being observed — the feature of interest. The range is intentionally open (owl:Thing) because anything can be observed: a place, a person, an event, a document, a quality value, or a situation. SHACL shapes enforce closed-world constraints per observation kind.", alias="gmeow:observedFeature")
    vantage: list[Entity] | None = Field(default=None, description="The agent or standpoint from which the observation is made — the reified-object-property counterpart of gmeow:accordingTo. Semantically, gmeow:vantage ⊑ gmeow:accordingTo: when an annotated statement is promoted to a reified Observation, its gmeow:accordingTo becomes the gmeow:vantage of the relator. The agent in the vantage role — an observer, a sensor, a perceiver — IS a standpoint (Principle 9): no frame is privileged, and every vantage is a co-equal facet from which the claim is held. Range is gmeow:Entity (encompassing both gmeow:Agent and gmeow:Standpoint) because a vantage may be a bare agent (person, organization, software agent, sensor) or a gmeow:Standpoint individual when the frame needs its own identity. Non-functional: joint observations (a reading co-authored by two agencies) are valid.", alias="gmeow:vantage")


class Measurement(Observation):
    """Measurement.

    An observation that assigns a quantitative or qualitative value to a feature of
    interest, typically carrying a unit, uncertainty, and determinacy model. The parent of
    temporal dating, spatial coordinate assignment, and scalar quantity measurements.

    When to use:
        - Use when an observation assigns a value to its feature — a dating, a coordinate fix, a
          scalar reading — so the claim inherits the observation roles while signalling it is a
          quantified/qualified measurement carrying unit, uncertainty, and determinacy.

    When to avoid:
        - Avoid for a bare standpoint assertion with no assigned value (use gmeow:StandpointClaim)
          or a raw sensor reading you want typed as such (gmeow:SensoryObservation); specialize
          further to gmeow:TemporalMeasurement or a spatial coordinate measurement where the slice
          provides one.

    How to use:
        - Type the act gmeow:Measurement, make gmeow:observationResult a math:Quantity carrying
          math:quantityValue plus the applicable gmeow:unit, gmeow:hasDeterminacy, and
          gmeow:quantityUncertainty qualifiers, and let domain slices deepen it with their own
          measurement subclasses and seeds.

    Examples:
        - ex:tempReading a gmeow:Measurement ; gmeow:observationResult ex:temp22 .

    Usage:
        >>> from gmeow_models.observations import Measurement
        >>> Measurement.model_config["json_schema_extra"]["curie"]
        'gmeow:Measurement'

    IRI:    https://blackcatinformatics.ca/gmeow/Measurement
    CURIE:  gmeow:Measurement

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Measurement", "curie": "gmeow:Measurement", "definitionDigest": "blake3:49415f08f5da6f4081b0f87d8c4741a557263904f3dc8aa2179d55b82cadb838", "iri": "https://blackcatinformatics.ca/gmeow/Measurement"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observationMethod: ObservationMethodEnum = Field(description="The method or protocol used to produce the observation. Functional: one method per observation (compound protocols are modelled as a single fused method individual, e.g. 'GPS-RTK survey with ground control'). Distinct from gmeow:vantage: the method is *how* it was done, the vantage is *who* did it.", alias="gmeow:observationMethod")


class MonetaryAmount(ConfiguredBaseModel):
    """Monetary Amount.

    A quantity of money expressed as a decimal value in an explicit currency reference
    frame. The canonical superset of schema:MonetaryAmount and FIBO
    fibo-fnd-acc-cur:MonetaryAmount. Frame-relative (Principle 11): a value without its
    currency frame is ill-formed.

    When to use:
        - Use for any quantity of money — a price, salary, fee, balance — so the amount always
          travels with its currency frame; consumed by employment, agreements, and finance alike
          (it lives on the measurement spine, not in a finance silo).

    When to avoid:
        - Avoid for a unit-bearing physical quantity (use math:Quantity with math:quantityValue
          and gmeow:unit) and avoid stating a bare amount without gmeow:currency — a value without
          its currency frame is ill-formed (Principle 11).

    How to use:
        - Mint the amount, set gmeow:monetaryValue (xsd:decimal) and the required gmeow:currency
          reference frame; the generated frame-relativity shape (gmeow:requiresFrame) enforces
          exactly the currency the amount is denominated in.

    Examples:
        - ex:price a gmeow:MonetaryAmount ; gmeow:monetaryValue 19.99 ; gmeow:currency ex:usd .

    Usage:
        >>> from gmeow_models.observations import MonetaryAmount
        >>> MonetaryAmount.model_config["json_schema_extra"]["curie"]
        'gmeow:MonetaryAmount'

    IRI:    https://blackcatinformatics.ca/gmeow/MonetaryAmount
    CURIE:  gmeow:MonetaryAmount

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/MonetaryAmount", "curie": "gmeow:MonetaryAmount", "definitionDigest": "blake3:266f1abe7cc5d9dfe0537891bf7c4f83ed0629b3bcecb82b5cb1824aca8de552", "iri": "https://blackcatinformatics.ca/gmeow/MonetaryAmount"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    currency: list[ReferenceFrame] | None = Field(default=None, description="The currency reference frame in which this monetary amount is expressed. Functional: a MonetaryAmount is in exactly one currency frame. A subproperty of gmeow:hasReferenceFrame (Principle 11).", alias="gmeow:currency")


class Quality(ConfiguredBaseModel):
    """Quality.

    A persistent quality of a bearer — a patient's systolic blood pressure, a road's width —
    that endures while its measured values change over time. The domain grounding of the
    foundational logic:Quality (Principle 17): it inheres in its gmeow:bearer, instantiates
    a generic quality via logic:genericQuality, and may play a quality-role in a
    bearer-context via logic:qualityRole over logic:Role. Dated gmeow:Observations attach to
    it via gmeow:observationOf rather than minting a fresh free-floating result each time,
    so 'how did this value change over time?' is a first-class query (Principle 9, the
    unified observation construct).

    When to use:
        - Use when a quality endures across multiple dated observations and you want its
          value-history as a first-class series — a vital sign, a measured dimension, a monitored
          property — rather than disconnected per-reading results.

    When to avoid:
        - Avoid using it for a one-off reading with no enduring identity (wrap that as a
          math:Quantity result of a single observation) and avoid asserting raw gufo:inheresIn —
          name the bearer with gmeow:bearer, the by-reference inherence prop (Principle 5).

    How to use:
        - Mint one persistent Quality per enduring quality of a bearer, set gmeow:bearer,
          logic:genericQuality, and (where a role applies) logic:qualityRole; attach each dated
          reading as a gmeow:Observation with gmeow:observationOf this quality and
          gmeow:observedAt the time.

    Examples:
        - ex:sysBP a gmeow:Quality ; gmeow:bearer ex:patientP ; logic:genericQuality
          gmeow:pressure ; logic:qualityRole gmeow:systolicRole .

    Usage:
        >>> from gmeow_models.observations import Quality
        >>> Quality.model_config["json_schema_extra"]["curie"]
        'gmeow:Quality'

    IRI:    https://blackcatinformatics.ca/gmeow/Quality
    CURIE:  gmeow:Quality
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/quality-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Quality", "curie": "gmeow:Quality", "definitionDigest": "blake3:12a7c1e54a0cf8128bbdf957e5a15df92db14683d1c02c91b10ce0d5488ed2ed", "iri": "https://blackcatinformatics.ca/gmeow/Quality"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    bearer: str | None = Field(default=None, description="The entity in which a persistent gmeow:Quality inheres — the patient whose blood pressure it is, the road whose width it is. Functional: a quality inheres in exactly one bearer. The by-reference inherence relation (Principle 5): the alignment to gufo:inheresIn is a generated mapping cell, never an asserted axiom, and raw gufo:inheresIn or a generic logic:inheresIn predicate is deliberately NOT used (either would trip the inherence surface guard).", alias="gmeow:bearer")


class SensoryObservation(Observation):
    """Sensory Observation.

    An observation produced by a sensor or sensory apparatus reading a physical property of
    the environment. Specialises Observation with sensor-specific properties (sensory
    property, sensor platform, sampling feature).

    When to use:
        - Use when the observation is a reading taken by a sensor or sensory apparatus of a
          physical property of the environment — the form that travels in a gmeow:Stream and
          carries sensor/platform/sampling-feature detail.

    When to avoid:
        - Avoid for a human judgement or a derived/computed value (use gmeow:Measurement with the
          matching gmeow:observationType) and for a standpoint assertion (gmeow:StandpointClaim);
          this kind is specifically instrument-mediated sensing.

    How to use:
        - Type the reading gmeow:SensoryObservation, put the sensor or platform in gmeow:vantage
          (or gmeow:streamSensor / gmeow:streamPlatform when streamed), and attach the value as a
          math:Quantity result; group time-ordered readings under a gmeow:Stream.

    Examples:
        - ex:humidityReading a gmeow:SensoryObservation ; gmeow:vantage ex:hygrometer .

    Usage:
        >>> from gmeow_models.observations import SensoryObservation
        >>> SensoryObservation.model_config["json_schema_extra"]["curie"]
        'gmeow:SensoryObservation'

    IRI:    https://blackcatinformatics.ca/gmeow/SensoryObservation
    CURIE:  gmeow:SensoryObservation

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/SensoryObservation", "curie": "gmeow:SensoryObservation", "definitionDigest": "blake3:09ea82d0f40697c4f9507e0b895698cc7f62f7bd6b17c2326744fc5393aba232", "iri": "https://blackcatinformatics.ca/gmeow/SensoryObservation"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    observationMethod: ObservationMethodEnum = Field(description="The method or protocol used to produce the observation. Functional: one method per observation (compound protocols are modelled as a single fused method individual, e.g. 'GPS-RTK survey with ground control'). Distinct from gmeow:vantage: the method is *how* it was done, the vantage is *who* did it.", alias="gmeow:observationMethod")


class StandpointClaim(Observation):
    """Standpoint Claim.

    An observation made from a specific standpoint or frame — an assertion, denial, or
    qualified position that a proposition holds. Realises the standpoint side of Principle 3
    (Observation ≡ Measurement ≡ Standpoint). The vantage is the standpoint; the
    observedFeature is the proposition or fact being claimed; the observationResult is the
    modality (unequivocal, probable, conceivable, refuted).

    When to use:
        - Use when a proposition is asserted, denied, or held with a qualified modality FROM a
          standpoint — the perspectival claim form where the value produced is a doxastic modality
          rather than a measured quantity (Principle 9: no standpoint privileged).

    When to avoid:
        - Avoid for a value-assigning reading (gmeow:Measurement / gmeow:SensoryObservation) and
          for marking a proposition false by fiat — a falsehood is a refuted StandpointClaim
          (modality refuted), never an isFalse flag; competing standpoints coexist rather than
          resolve.

    How to use:
        - Put the standpoint in gmeow:vantage, the proposition or fact in gmeow:observedFeature,
          and a modality value (unequivocal, probable, conceivable, refuted) in
          gmeow:observationResult; record a contested fact as several coexisting StandpointClaims,
          each with its own gmeow:accordingTo.

    Examples:
        - ex:claim a gmeow:StandpointClaim ; gmeow:vantage ex:authorityA ; gmeow:observedFeature
          ex:proposition .

    Usage:
        >>> from gmeow_models.observations import StandpointClaim
        >>> StandpointClaim.model_config["json_schema_extra"]["curie"]
        'gmeow:StandpointClaim'

    IRI:    https://blackcatinformatics.ca/gmeow/StandpointClaim
    CURIE:  gmeow:StandpointClaim
    Docs:   https://blackcatinformatics.ca/gmeow/documentation/term/standpointclaim-class

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/StandpointClaim", "curie": "gmeow:StandpointClaim", "definitionDigest": "blake3:e6c81c196b791f92b30d5afb7c2d84729b82aeb9ac699325f4ae2a5439846b96", "iri": "https://blackcatinformatics.ca/gmeow/StandpointClaim"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")


class Stream(ConfiguredBaseModel):
    """Stream.

    A time-ordered sequence of observations or samples produced by a sensor or platform over
    a time interval. The ordering of samples is implicit via their individual timestamps,
    not asserted as a list structure (Principle 12). A stream is the canonical source from
    which a continuous trajectory may be derived by the solver layer.

    When to use:
        - Use to group a time-ordered run of observations or samples about one entity from a
          sensor or platform — the canonical source a solver derives a continuous trajectory from
          (no list structure is asserted).

    When to avoid:
        - Avoid for a single isolated reading (use a bare Observation) and avoid encoding sample
          order as an RDF list — ordering is implicit via each sample's timestamp (Principle 12),
          and the interpolated trajectory is a solver concern.

    How to use:
        - Mint the Stream, bind its subject with the functional gmeow:streamOf, attach readings
          via gmeow:streamSample, name gmeow:streamPlatform / gmeow:streamSensor, and bound it
          with the functional gmeow:streamInterval; an entity reaches its streams through
          gmeow:hasStream.

    Examples:
        - ex:roverTrack a gmeow:Stream ; gmeow:streamOf ex:rover ; gmeow:streamSample ex:fix1 .

    Usage:
        >>> from gmeow_models.observations import Stream
        >>> Stream.model_config["json_schema_extra"]["curie"]
        'gmeow:Stream'

    IRI:    https://blackcatinformatics.ca/gmeow/Stream
    CURIE:  gmeow:Stream

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Stream", "curie": "gmeow:Stream", "definitionDigest": "blake3:2d3bb1c8fd6d1d607f43d037feed97e5abf1826e835065d6b7ff2a421cef424e", "iri": "https://blackcatinformatics.ca/gmeow/Stream"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    streamOf: list[Entity] | None = Field(default=None, description="The entity whose observations the stream contains — the moving feature, device, or thing being tracked. Functional: a stream belongs to exactly one entity.", alias="gmeow:streamOf")
