"""GMEOW models — slice GMEOW Profile Meta-pattern Module.

Slice IRI:  https://blackcatinformatics.ca/gmeow/slices/profiles
Tier:       core
DOI:        —

GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
"""
from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from ._base import ConfiguredBaseModel


class Profile(ConfiguredBaseModel):
    """Profile.

    A closed descriptor schema for an open-but-structured facet. A Profile self-describes
    the properties that constitute the facet and the open value vocabularies from which
    their values are drawn, enabling extensibility-by-construction.

    When to use:
        - Use to declare the closed descriptor schema for an open-but-structured facet — the set
          of descriptor properties and the open value vocabularies a frame, value, or named slice
          profile is built from.

    When to avoid:
        - Avoid for an ordinary instance of a facet (a Profile describes the schema, not a value
          of it) and avoid subclassing the facet's open vocabularies into the descriptor — list
          them with gmeow:profileOpenValue instead.

    How to use:
        - Mint the Profile as an individual, name its target class with gmeow:profileAppliesTo,
          enumerate descriptor properties with gmeow:profileDescriptor, and the open value classes
          with gmeow:profileOpenValue; instances reference it via gmeow:hasProfile.

    Examples:
        - ex:profileReferenceFrame a gmeow:Profile ; gmeow:profileAppliesTo gmeow:ReferenceFrame .

    Usage:
        >>> from gmeow_models.profiles import Profile
        >>> Profile.model_config["json_schema_extra"]["curie"]
        'gmeow:Profile'

    IRI:    https://blackcatinformatics.ca/gmeow/Profile
    CURIE:  gmeow:Profile

    GENERATED by the gmeow pydantic emitter — DO NOT EDIT.
    """

    model_config = ConfigDict(
        extra="allow",
        json_schema_extra={"$id": "https://blackcatinformatics.ca/gmeow/Profile", "curie": "gmeow:Profile", "definitionDigest": "blake3:547de60caa5c6ccdae501218f6351f811a3d674449f1929b23558444a8b90ae7", "iri": "https://blackcatinformatics.ca/gmeow/Profile"},
    )

    annotation: Annotation | None = Field(default=None, alias="@annotation")
    id: str | None = Field(default=None, alias="@id")
    type_: str | list[str] | None = Field(default=None, alias="@type")
    profileAppliesTo: list[str] | None = Field(default=None, description="The class of entities to which this Profile applies.", alias="gmeow:profileAppliesTo")
    profileDescriptor: list[Any] = Field(min_length=1, description="A property that is part of this Profile's closed descriptor schema.", alias="gmeow:profileDescriptor")
    definition: list[Any] = Field(min_length=1, alias="http://www.w3.org/2004/02/skos/core#definition")
    label: list[Any] = Field(min_length=1, alias="rdfs:label")
