// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The CGIF **writer**: [`LogicProgram`] → CGIF text (`generated/cl/gmeow.cgif`).
//!
//! See [`crate::cgif`] for the two-channel architecture. This module emits the idiomatic
//! conceptual-graph channel (`rules` + `formulas`) as readable conceptual graphs and the
//! RDF/predication channel (everything else) as `("P" "S" "O")` relation predications after
//! the `RDF_META_SENTINEL`.

use gmeow_errors::Diag;

use crate::ir::{Formula, LogicAxiom, LogicProgram, Term};
use crate::projections::{ProjectionResult, rdf, target_meta};

use super::{RDF_META_SENTINEL, escape_string};

use purrdf::{RdfDataset, TermRef, parse_dataset};

/// `xsd:string` — the datatype the dataset assigns a plain literal; emitted CGIF distinguishes
/// a plain `(lit "x")` from a typed `(lit "x" "dt")` by suppressing this datatype (so the
/// round-trip reconstructs the plain literal).
const XSD_STRING: &str = "http://www.w3.org/2001/XMLSchema#string";
/// `xsd:integer` — the datatype emitted for a path shape's integer min/max depths.
const XSD_INTEGER: &str = "http://www.w3.org/2001/XMLSchema#integer";

/// Project a [`LogicProgram`] to CGIF text.
///
/// Returns `Err` if the lossless RDF/predication carrier cannot be built (the
/// canonical-RDF-1.2 projection or its re-parse failing is an invariant break, not a
/// recoverable condition) — surfacing a structured error to `compile_program` exactly like
/// the sibling projectors, rather than panicking.
pub fn project_cgif(program: &LogicProgram) -> gmeow_errors::Result<ProjectionResult> {
    // Registry is the single source of truth for (preservation, complexity, drops).
    let (kind, cx, _) = target_meta("cgif");

    let mut lines: Vec<String> = vec![
        "/* GENERATED by `gmeow logic compile` — DO NOT EDIT. */".to_owned(),
        "/* CGIF (Conceptual Graph Interchange Format) projection of the canonical logic program. */"
            .to_owned(),
        String::new(),
    ];

    // ── Idiomatic conceptual-graph channel (human-readable rendering) ───────────
    // Rules and formulas are rendered as readable conceptual graphs. This channel is
    // WRITE-ONLY: the canonical IR carries an `obj_is_literal` bit on a rule term (and a
    // rule's minted reifier-node identity) that idiomatic conceptual-graph syntax cannot
    // express, so reconstructing the byte-exact IR from a graph would be lossy. The lossless
    // carrier is the RDF/predication channel below (the Exact `canonical-rdf12` leg), from
    // which the reader reconstructs the WHOLE program — rules and formulas included. The
    // conceptual graphs are therefore an idiomatic view over the same content, never the
    // round-trip authority.
    lines.push("/* === Rules (idiomatic conceptual graphs; human-readable view) === */".to_owned());
    for rule in &program.rules {
        lines.push(rule_to_cgif(rule));
    }
    lines.push(String::new());
    lines.push("/* === Full first-order formulas (idiomatic view) === */".to_owned());
    for formula in &program.formulas {
        lines.push(formula_to_cgif(formula));
    }

    // ── RDF / predication channel (the lossless round-trip carrier): the WHOLE program
    //    — axioms (+ scope), rules, formulas, contracts, correspondences — re-emitted as
    //    sorted CGIF relation predications from the Exact canonical-RDF-1.2 serializer. ─────
    let meta_lines = meta_predications(program)?;
    if !meta_lines.is_empty() {
        lines.push(String::new());
        lines.push(RDF_META_SENTINEL.to_owned());
        lines.push(
            "/* RDF/predication channel: flat logic triples as CGIF relations. */".to_owned(),
        );
        lines.extend(meta_lines);
    }

    let content = format!("{}\n", lines.join("\n"));
    Ok(ProjectionResult {
        target: "cgif".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        // Exact target: every construct is carried (graph channel verbatim, RDF channel via
        // the lossless canonical-RDF-1.2 leg). Nothing is dropped, so it interns nothing
        // into the single loss store.
    })
}

// --------------------------------------------------------------------------- //
// Idiomatic conceptual-graph channel — rules
// --------------------------------------------------------------------------- //

/// Encode a [`LogicAxiom`] (a Horn triple) as a CGIF relation `("<pred>" <subj> <obj>)`.
fn axiom_relation(axiom: &LogicAxiom) -> String {
    let pred = name_term(&axiom.predicate);
    let subj = horn_term(&axiom.subject, false);
    let obj = horn_term(&axiom.obj, axiom.obj_is_literal);
    format!("({pred} {subj} {obj})")
}

/// A Horn subject/object arc: a `?var` bound label, a bracketed literal concept, or a
/// double-quoted CGIF name (an IRI).
fn horn_term(value: &str, is_literal: bool) -> String {
    if let Some(var) = value.strip_prefix('?') {
        format!("?{var}")
    } else if is_literal {
        // A plain literal in the Horn fragment (the canonical IR carries no datatype on
        // `LogicAxiom.obj`; that detail lives in the RDF channel). Render as a concept whose
        // referent is the string value: `[: "lex"]`.
        format!("[: {}]", quote_string(value))
    } else {
        name_term(value)
    }
}

/// Encode a [`crate::ir::LogicRule`] as `[If: <body graphs> [Then: <head>]]`, or — for the
/// degenerate empty-body rule — the bare head relation (a fact).
fn rule_to_cgif(rule: &crate::ir::LogicRule) -> String {
    let head = axiom_relation(&rule.head);

    let mut body_graphs: Vec<String> = Vec::new();
    for ba in &rule.body {
        let atom = axiom_relation(ba);
        if ba.negated {
            body_graphs.push(format!("~[{atom}]"));
        } else {
            body_graphs.push(atom);
        }
    }
    // `distinct_pairs` (a, b) → a negated equality context `~[("=" ?a ?b)]`.
    for (a, b) in &rule.distinct_pairs {
        body_graphs.push(format!(
            "~[({} {} {})]",
            name_term("="),
            var_token(a),
            var_token(b)
        ));
    }

    if body_graphs.is_empty() {
        // A fact: emit the head relation alone (its coreference labels are implicitly universal).
        return head;
    }

    format!("[If: {} [Then: {head}]]", body_graphs.join(" "))
}

/// Normalize a possibly-`?`-prefixed variable string to a CGIF `?name` bound label.
fn var_token(s: &str) -> String {
    match s.strip_prefix('?') {
        Some(name) => format!("?{name}"),
        None => format!("?{s}"),
    }
}

// --------------------------------------------------------------------------- //
// Idiomatic conceptual-graph channel — formulas
// --------------------------------------------------------------------------- //

/// Encode a [`Formula`] recursively as a conceptual graph.
fn formula_to_cgif(formula: &Formula) -> String {
    match formula {
        Formula::Atom { relation, args } => {
            let rel = term_to_cgif(relation);
            let mut parts = vec![rel];
            for a in args {
                parts.push(term_to_cgif(a));
            }
            format!("({})", parts.join(" "))
        }
        // Negated context.
        Formula::Not(inner) => format!("~[{}]", formula_to_cgif(inner)),
        // Conjunction is juxtaposition inside a context node `[ … ]`.
        Formula::And(fs) => {
            let parts: Vec<String> = fs.iter().map(formula_to_cgif).collect();
            format!("[{}]", parts.join(" "))
        }
        // Disjunction via De Morgan: `~[ ~[f1] ~[f2] … ]`.
        Formula::Or(fs) => {
            let parts: Vec<String> = fs
                .iter()
                .map(|f| format!("~[{}]", formula_to_cgif(f)))
                .collect();
            format!("~[{}]", parts.join(" "))
        }
        Formula::Implies(a, b) => {
            format!(
                "[If: {} [Then: {}]]",
                formula_to_cgif(a),
                formula_to_cgif(b)
            )
        }
        // Biconditional as two implication contexts.
        Formula::Iff(a, b) => {
            let (ca, cb) = (formula_to_cgif(a), formula_to_cgif(b));
            format!("[If: {ca} [Then: {cb}]] [If: {cb} [Then: {ca}]]")
        }
        // Universals introduce `[@every*v]` concepts scoping the body.
        Formula::Forall { vars, body } => {
            let vs: Vec<String> = vars.iter().map(|v| format!("[@every*{v}]")).collect();
            format!("{} {}", vs.join(" "), formula_to_cgif(body))
        }
        // Existentials introduce `[*v]` defining concepts scoping the body.
        Formula::Exists { vars, body } => {
            let vs: Vec<String> = vars.iter().map(|v| format!("[*{v}]")).collect();
            format!("{} {}", vs.join(" "), formula_to_cgif(body))
        }
    }
}

/// Encode a [`Term`] as a CGIF arc / concept.
fn term_to_cgif(term: &Term) -> String {
    match term {
        Term::Var(n) => format!("?{n}"),
        Term::Iri(i) => name_term(i),
        Term::Literal { lexical, datatype } => match datatype {
            // Untyped literal → a concept whose referent is the string.
            None => format!("[: {}]", quote_string(lexical)),
            // Typed literal → a concept typed by the datatype IRI.
            Some(dt) => format!("[{}: {}]", name_term(dt), quote_string(lexical)),
        },
        // A sequence marker → a `[Sequence: "name"]` concept.
        Term::SequenceMarker(n) => format!("[Sequence: {}]", quote_string(n)),
        // A function-term application → the CGIF functional relation `(f t₀ … tₙ)`, the same
        // parenthesized conceptual-relation form an atom uses, with the function symbol as the
        // relation type over its argument concepts.
        Term::App { symbol, args } => {
            let mut parts = vec![name_term(symbol)];
            parts.extend(args.iter().map(term_to_cgif));
            format!("({})", parts.join(" "))
        }
    }
}

// --------------------------------------------------------------------------- //
// RDF / predication channel
// --------------------------------------------------------------------------- //

/// Assemble the RDF/predication channel as sorted CGIF relation predications `("P" "S" "O")`.
/// This is the **lossless round-trip carrier** — built only from serializers the canonical
/// frontend round-trips at its fixpoint:
///
/// * **the whole program** — axioms (+ scope), rules, formulas, and contracts → the Exact
///   `canonical-rdf12` projection (which reifies rule head/body and full-FOL formula trees and
///   emits contract facets, all of which `parse_logic_dataset` reconstructs);
/// * **correspondences** → `project_correspondence` (round-trips to a content-key-equal program).
///
/// `path_shapes` are emitted DIRECTLY as the `logic:PathShape` triples the frontend's
/// `extract_path_shapes` reads (a faithful inverse). `transaction_programs` (a correspondence
/// leg's `gm:path` body) are emitted as the `gm:` leg-body triples the frontend's
/// `extract_leg_programs` reads (the faithful inverse of `parse_leg_path`). The Exact claim
/// therefore carries every construct losslessly.
///
/// Returns `Err` if the canonical-RDF-1.2 leg (or its re-parse) fails — the lossless carrier
/// cannot be assembled, which is an invariant break surfaced to the caller, not a panic.
fn meta_predications(program: &LogicProgram) -> gmeow_errors::Result<Vec<String>> {
    let mut preds: Vec<String> = Vec::new();

    // (0) Path shapes — emitted as the logic:PathShape triples `extract_path_shapes` reads.
    for shape in &program.path_shapes {
        preds.extend(path_shape_predications(shape));
    }

    // (0b) Transaction programs (correspondence leg bodies) — emitted as the `gm:` leg-body
    //      triples `extract_leg_programs` reads. A single counter mints deterministic structural
    //      node/cell IRIs so the sorted output is byte-stable.
    let mut leg_node_counter: usize = 0;
    for tp in &program.transaction_programs {
        let body_root = emit_leg_path(&tp.iri, &tp.body, &mut preds, &mut leg_node_counter);
        // ("gm:path" <leg-iri> <body-root-node>)
        preds.push(format!(
            "({} {} {})",
            name_term(&gm("path")),
            name_term(&tp.iri),
            name_term(&body_root)
        ));
    }

    // (1) The whole program (axioms + scope + rules + formulas + contracts) → the lossless
    //     canonical RDF 1.2 projection. Rules are reified as nodes and formulas as logic:Formula
    //     trees, so the reconstruction is the Exact `canonical-rdf12` round-trip the frontend
    //     already pins.
    //
    //     A correspondence's `logic:` triples and a path shape's defining triples are also
    //     re-extracted by the frontend as flat axioms; emitting them through canonical-rdf12 AND
    //     their own channel would duplicate them with a different lexical form, breaking
    //     idempotence. They are owned by their channels, so exclude any axiom whose subject is a
    //     correspondence node (or child) or a path-shape node.
    let corr_subjects = correspondence_subjects(program);
    let path_subjects: std::collections::HashSet<&str> =
        program.path_shapes.iter().map(|p| p.iri.as_str()).collect();
    let axioms: Vec<_> = program
        .axioms
        .iter()
        .filter(|a| {
            !is_correspondence_owned(&a.subject, &corr_subjects)
                && !path_subjects.contains(a.subject.as_str())
        })
        .cloned()
        .collect();
    let canon_meta = LogicProgram::new(
        axioms,
        program.rules.clone(),
        program.contracts.clone(),
        program.source_iri.clone(),
    )
    .with_formulas(program.formulas.clone());
    let ttl = rdf::project_canonical_rdf12(&canon_meta)
        .map_err(|e| {
            Diag::of_kind(crate::error::Cgif {
                detail: format!("CGIF meta channel: canonical-rdf12 projection failed: {e}"),
            })
        })?
        .content;
    preds.extend(quads_as_predications(ttl.as_bytes(), "text/turtle")?);

    // (2) Correspondences → the faithful correspondence N-Triples projection.
    if !program.correspondences.is_empty() {
        let cp = crate::projections::correspondence::CorrespondenceProgram::new(
            program.correspondences.clone(),
            Vec::new(),
            crate::ir::PreservationKind::Exact,
        );
        let nt = crate::projections::correspondence::project_correspondence(&cp);
        preds.extend(quads_as_predications(
            nt.as_bytes(),
            "application/n-triples",
        )?);
    }

    preds.sort();
    preds.dedup();
    Ok(preds)
}

/// The `gm:` namespace (`gmeow:`) — the leg-body path vocabulary the transaction layer uses.
const GM_NAMESPACE: &str = "https://blackcatinformatics.ca/gmeow/";
/// `rdf:type`.
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// A `gm:`-namespaced IRI.
fn gm(local: &str) -> String {
    format!("{GM_NAMESPACE}{local}")
}

/// Emit the structural `gm:` triples for a [`crate::ir::LegPath`] (the faithful inverse of the
/// frontend's `parse_leg_path`) into `preds`, returning the body node IRI a `gm:path` (or a
/// parent combinator) should reference.
fn emit_leg_path(
    base: &str,
    path: &crate::ir::LegPath,
    preds: &mut Vec<String>,
    counter: &mut usize,
) -> String {
    use crate::ir::LegPath;
    match path {
        LegPath::Step(pred) => pred.clone(),
        LegPath::Inverse(inner) => {
            let node = format!("{base}/legnode/{counter}");
            *counter += 1;
            preds.push(format!(
                "({} {} {})",
                name_term(RDF_TYPE),
                name_term(&node),
                name_term(&gm("InversePath"))
            ));
            let inner_node = emit_leg_path(base, inner, preds, counter);
            preds.push(format!(
                "({} {} {})",
                name_term(&gm("pathStep")),
                name_term(&node),
                name_term(&inner_node)
            ));
            node
        }
        LegPath::Seq(members) => emit_leg_list(
            base,
            members,
            &gm("SeqPath"),
            &gm("pathSteps"),
            preds,
            counter,
        ),
        LegPath::Alt(members) => emit_leg_list(
            base,
            members,
            &gm("AltPath"),
            &gm("pathAlts"),
            preds,
            counter,
        ),
    }
}

/// Emit a `gm:SeqPath` / `gm:AltPath` combinator node and its `gm:pathNext`-linked cell chain,
/// returning the combinator node IRI.
fn emit_leg_list(
    base: &str,
    members: &[crate::ir::LegPath],
    type_iri: &str,
    head_pred: &str,
    preds: &mut Vec<String>,
    counter: &mut usize,
) -> String {
    let node = format!("{base}/legnode/{counter}");
    *counter += 1;
    preds.push(format!(
        "({} {} {})",
        name_term(RDF_TYPE),
        name_term(&node),
        name_term(type_iri)
    ));
    // Mint every cell IRI first so the (node head_pred cell0) and (cell_i pathNext cell_{i+1})
    // links use a stable, deterministic naming independent of recursion order.
    let cell_iris: Vec<String> = members
        .iter()
        .map(|_| {
            let cell = format!("{base}/legcell/{counter}");
            *counter += 1;
            cell
        })
        .collect();
    for (i, member) in members.iter().enumerate() {
        let cell = &cell_iris[i];
        let member_node = emit_leg_path(base, member, preds, counter);
        preds.push(format!(
            "({} {} {})",
            name_term(&gm("pathItem")),
            name_term(cell),
            name_term(&member_node)
        ));
        if let Some(next) = cell_iris.get(i + 1) {
            preds.push(format!(
                "({} {} {})",
                name_term(&gm("pathNext")),
                name_term(cell),
                name_term(next)
            ));
        }
    }
    // (node head_pred cell0)
    if let Some(first) = cell_iris.first() {
        preds.push(format!(
            "({} {} {})",
            name_term(head_pred),
            name_term(&node),
            name_term(first)
        ));
    }
    node
}

/// Emit a [`PathShapeIr`](crate::ir::PathShapeIr) as the `logic:PathShape` CGIF predications its
/// frontend extractor reads (a faithful inverse of `extract_path_shapes`). Predicate-first shape.
fn path_shape_predications(shape: &crate::ir::PathShapeIr) -> Vec<String> {
    let s = name_term(&shape.iri);
    let logic = |local: &str| name_term(&format!("{}{local}", crate::ir::LOGIC_NAMESPACE));

    let mut out = vec![format!(
        "({} {s} {})",
        name_term(RDF_TYPE),
        logic("PathShape")
    )];
    match &shape.base {
        crate::ir::PathBase::NamedPredicate(p) => {
            out.push(format!(
                "({} {s} {})",
                logic("pathStepPredicate"),
                name_term(p)
            ));
        }
        crate::ir::PathBase::Wildcard => {
            out.push(format!("({} {s} (lit \"true\"))", logic("pathWildcard")));
        }
    }
    // Depths are integers in the IR (`u32`); emit them as typed `xsd:integer` literals so the
    // generated CGIF is type-faithful. The frontend's `parse_positive_int` reads the lexical
    // regardless, so this round-trips.
    let xsd_int = name_term(XSD_INTEGER);
    out.push(format!(
        "({} {s} (lit \"{}\" {xsd_int}))",
        logic("pathMinDepth"),
        shape.min_depth
    ));
    if let Some(max) = shape.max_depth {
        out.push(format!(
            "({} {s} (lit \"{max}\" {xsd_int}))",
            logic("pathMaxDepth")
        ));
    }
    if let Some(ns) = &shape.namespace_scope {
        out.push(format!(
            "({} {s} (lit {}))",
            logic("pathNamespaceScope"),
            quote_string(ns)
        ));
    }
    if let Some(param) = &shape.depth_param {
        out.push(format!(
            "({} {s} (lit {}))",
            logic("pathDepthParam"),
            quote_string(param)
        ));
    }
    out
}

/// The set of correspondence node IRIs whose flat axioms are owned by the correspondence
/// channel (the correspondence individuals + the singleton `correspondence-program` node).
fn correspondence_subjects(program: &LogicProgram) -> Vec<String> {
    let mut subjects: Vec<String> = program
        .correspondences
        .iter()
        .map(|c| c.iri.clone())
        .collect();
    // The `project_correspondence` wrapper node (one per build).
    subjects.push(format!(
        "{}correspondence-program",
        crate::ir::LOGIC_NAMESPACE
    ));
    subjects
}

/// Whether `subject` is a correspondence node (exact match) or one of its child nodes.
fn is_correspondence_owned(subject: &str, corr_subjects: &[String]) -> bool {
    corr_subjects.iter().any(|c| {
        subject == c
            || subject
                .strip_prefix(c.as_str())
                .is_some_and(|r| r.starts_with('/'))
    })
}

/// Parse RDF `bytes` of `media_type` and emit each quad as a sorted-later CGIF predication.
/// Returns `Err` if the projection's own serialized output cannot be re-parsed (an invariant
/// break in the canonical leg, surfaced to the caller rather than panicking).
fn quads_as_predications(bytes: &[u8], media_type: &str) -> gmeow_errors::Result<Vec<String>> {
    let ds = parse_dataset(bytes, media_type, None).map_err(|e| {
        Diag::of_kind(crate::error::Cgif {
            detail: format!("CGIF meta channel: re-parse of {media_type} failed: {e}"),
        })
    })?;
    Ok(ds
        .quad_refs()
        .map(|q| {
            let s = term_ref_to_cgif(ds.as_ref(), q.s);
            let p = term_ref_to_cgif(ds.as_ref(), q.p);
            let o = term_ref_to_cgif(ds.as_ref(), q.o);
            format!("({p} {s} {o})")
        })
        .collect())
}

/// Encode a resolved RDF [`TermRef`] as a CGIF term, faithfully preserving datatype / lang.
fn term_ref_to_cgif(ds: &RdfDataset, term: TermRef<'_>) -> String {
    match term {
        TermRef::Iri(iri) => name_term(iri),
        TermRef::Blank { label, .. } => name_term(&format!("_:{label}")),
        TermRef::Literal {
            lexical,
            datatype,
            language,
            ..
        } => {
            if let Some(lang) = language {
                format!("(lit {} @{lang})", quote_string(lexical))
            } else {
                let dt = match ds.resolve(datatype) {
                    TermRef::Iri(s) => s,
                    _ => XSD_STRING,
                };
                if dt == XSD_STRING {
                    format!("(lit {})", quote_string(lexical))
                } else {
                    // Any non-string datatype is carried as `(lit "lex" dt)` — including a
                    // langString with no language (malformed RDF the parser never produces), so
                    // the round-trip stays total rather than silently dropping the datatype.
                    format!("(lit {} {})", quote_string(lexical), name_term(dt))
                }
            }
        }
        // A triple term (RDF 1.2 quoted triple) — the canonical projection uses classic
        // reification, not `<<>>`, so this should not occur; if it does, recurse faithfully.
        TermRef::Triple { s, p, o } => {
            let st = term_ref_to_cgif(ds, ds.resolve(s));
            let pt = term_ref_to_cgif(ds, ds.resolve(p));
            let ot = term_ref_to_cgif(ds, ds.resolve(o));
            format!("(triple {st} {pt} {ot})")
        }
    }
}

// --------------------------------------------------------------------------- //
// Term codecs
// --------------------------------------------------------------------------- //

/// Quote a CGIF name (IRI) as `"…"`, escaping `"` and `\`.
fn name_term(iri: &str) -> String {
    format!("\"{}\"", escape_string(iri))
}

/// Quote a string literal as `"…"`, escaping `"` and `\`.
fn quote_string(s: &str) -> String {
    format!("\"{}\"", escape_string(s))
}
