// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! The #697 native ⊇ oracle DL-gold conformance lane (Gap G).
//!
//! Issue #697 criteria 2 & 4 require the native, Docker-free reasoning path to
//! catch *every* inconsistency / unsatisfiable class the classic Java oracles
//! (HermiT, ELK) catch — native ⊇ oracle. This test proves that OFFLINE against
//! a small set of curated OWL/gUFO datasets whose GOLD verdict was produced by a
//! real ROBOT/HermiT run and FROZEN under `coverage/external/697-dl-oracle-gold/`.
//!
//! Honesty doctrine (issue #697): the frozen verdicts are the *oracle's* output,
//! never hand-typed to match native and never edited to make this test pass. They
//! are regenerated by `make maint-697-oracle-gold` (a non-required maintainer
//! lane that re-runs HermiT in Docker). This test itself needs NO Docker, Java,
//! or network — it loads the committed fixtures and the committed gold and runs
//! the native `gmeow_logic::reason::reason_all` engine.
//!
//! ## The native ⊇ oracle contract
//!
//! For each dataset, given the frozen HermiT verdict:
//!
//! * If the oracle found the ontology **inconsistent**, native must too
//!   (`!verdict.consistent`). An inconsistent ontology has *every* class
//!   unsatisfiable, so no further class-level check is required.
//! * If the oracle found the ontology **consistent** but reported unsatisfiable
//!   classes, native must report each of those classes as unsatisfiable as well
//!   (its set may be a SUPERSET — that is allowed and is the whole point).
//!
//! The native set being a strict superset is *never* a failure: native deciding
//! MORE than the oracle is the goal (native ⊇ oracle). Only native deciding LESS
//! — missing an oracle inconsistency or unsat class — fails the gate.

use std::collections::BTreeSet;
use std::path::PathBuf;

use gmeow_logic::reason::reason_all;
use gmeow_rdf::{dataset_from_bytes, NativeRdfFormat};
use serde_json::Value;

/// The frozen-gold root, `coverage/external/697-dl-oracle-gold/`.
fn gold_root() -> PathBuf {
    gmeow_conformance::paths::repo_root()
        .join("coverage")
        .join("external")
        .join("697-dl-oracle-gold")
}

/// One frozen oracle verdict, read from its committed JSON.
struct OracleGold {
    dataset: String,
    consistent: bool,
    unsatisfiable_classes: BTreeSet<String>,
}

/// Parse one committed `expected/<stem>.json` frozen verdict.
fn read_gold(path: &std::path::Path) -> OracleGold {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let value: Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()));
    let dataset = value["dataset"]
        .as_str()
        .unwrap_or_else(|| panic!("{}: missing string `dataset`", path.display()))
        .to_owned();
    let consistent = value["consistent"]
        .as_bool()
        .unwrap_or_else(|| panic!("{}: missing bool `consistent`", path.display()));
    let unsatisfiable_classes = value["unsatisfiable_classes"]
        .as_array()
        .unwrap_or_else(|| panic!("{}: missing array `unsatisfiable_classes`", path.display()))
        .iter()
        .map(|v| {
            v.as_str()
                .unwrap_or_else(|| panic!("{}: non-string unsat class", path.display()))
                .to_owned()
        })
        .collect();
    OracleGold {
        dataset,
        consistent,
        unsatisfiable_classes,
    }
}

/// Run native `reason_all` over one Turtle fixture and return
/// `(consistent, unsat_class_iris)`.
fn native_verdict(dataset_path: &std::path::Path) -> (bool, BTreeSet<String>) {
    let bytes = std::fs::read(dataset_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", dataset_path.display()));
    let dataset = dataset_from_bytes(&bytes, NativeRdfFormat::Turtle)
        .unwrap_or_else(|e| panic!("parse {}: {e}", dataset_path.display()));
    let result = reason_all(dataset.as_ref())
        .unwrap_or_else(|e| panic!("native reason_all on {}: {e}", dataset_path.display()));
    let unsat = result
        .verdict
        .unsatisfiable_classes
        .iter()
        .map(|u| u.class.clone())
        .collect();
    (result.verdict.consistent, unsat)
}

/// The single offline assertion: for every frozen oracle verdict, the native
/// Docker-free reasoner reproduces it (native ⊇ oracle). Aggregates all
/// mismatches into one error so a regression names every offending dataset.
#[test]
fn native_reasoner_is_a_superset_of_the_frozen_oracle_gold() {
    let expected_dir = gold_root().join("expected");
    let datasets_dir = gold_root().join("datasets");

    let mut gold_files: Vec<PathBuf> = std::fs::read_dir(&expected_dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", expected_dir.display()))
        .map(|e| e.expect("dir entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    gold_files.sort();
    assert!(
        !gold_files.is_empty(),
        "no frozen oracle gold found under {} — run `make maint-697-oracle-gold`",
        expected_dir.display()
    );

    let mut failures: Vec<String> = Vec::new();

    for gold_path in &gold_files {
        let gold = read_gold(gold_path);
        let dataset_path = datasets_dir.join(&gold.dataset);
        let (native_consistent, native_unsat) = native_verdict(&dataset_path);

        // native ⊇ oracle on inconsistency: an oracle inconsistency MUST be a
        // native inconsistency (native may also be inconsistent where the oracle
        // is merely incoherent — that is still a superset and allowed).
        if !gold.consistent && native_consistent {
            failures.push(format!(
                "{}: oracle=INCONSISTENT but native=consistent (native MISSED an \
                 oracle inconsistency)",
                gold.dataset
            ));
            continue;
        }

        // native ⊇ oracle on unsat classes. An inconsistent native verdict makes
        // every class unsatisfiable, so the class-level check only applies when
        // native reports the ontology consistent.
        if native_consistent {
            let missed: Vec<&String> = gold
                .unsatisfiable_classes
                .iter()
                .filter(|c| !native_unsat.contains(*c))
                .collect();
            if !missed.is_empty() {
                failures.push(format!(
                    "{}: native MISSED oracle-unsat class(es) {:?}; native unsat = {:?}",
                    gold.dataset, missed, native_unsat
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "native ⊇ oracle violated for {} dataset(s):\n  • {}",
        failures.len(),
        failures.join("\n  • ")
    );
}
