// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Projection report: the preservation loss ledger
//! (`generated/logic/projection-report.ttl`).
//!
//! A faithful Rust port of `build_projection_report`.  Emits, per target, a
//! `logic:ProjectionTarget` node with `logic:preservationKind`,
//! `logic:complexityClass`, and aggregated `gmeow:lossyDrop` records; runs the
//! overclaim gate per target so an overclaim blocks serialization (red build).
//! Compared by RDF isomorphism, like the other RDF targets.

use oxigraph::model::{Literal, NamedNode};

use super::super::ir::LogicProgram;
use super::rdf::TripleSink;
use super::{
    assert_no_overclaim, OverclaimError, ProjectionResult, GMEOW_NS, LOGIC_NS, RDFS_NS, RDF_TYPE,
    XSD_NS,
};

fn logic(local: &str) -> String {
    format!("{LOGIC_NS}{local}")
}

fn int_literal(n: usize) -> Literal {
    let dt = NamedNode::new(format!("{XSD_NS}integer")).expect("xsd:integer is valid");
    Literal::new_typed_literal(n.to_string(), dt)
}

/// Build the projection-report Turtle (`generated/logic/projection-report.ttl`).
///
/// # Errors
///
/// Returns [`OverclaimError`] if any projection declares `ExactPreservation` but
/// produced drops.
pub fn build_projection_report(
    program: &LogicProgram,
    projections: &[ProjectionResult],
) -> Result<String, OverclaimError> {
    let mut g = TripleSink::default();

    let report_iri = logic("projection-report");
    g.add_iri(&report_iri, RDF_TYPE, &logic("ProjectionReport"));
    g.add_lit(
        &report_iri,
        &logic("axiomCount"),
        int_literal(program.axioms.len()),
    );
    g.add_lit(
        &report_iri,
        &logic("ruleCount"),
        int_literal(program.rules.len()),
    );
    g.add_lit(
        &report_iri,
        &logic("profileCount"),
        int_literal(program.profiles.len()),
    );

    // Targets in sorted order (the Python `sorted(projections, key=target)`).
    let mut sorted: Vec<&ProjectionResult> = projections.iter().collect();
    sorted.sort_by(|a, b| a.target.cmp(&b.target));

    for proj in sorted {
        // Overclaim gate (projection-level drops only; no materialization phase).
        assert_no_overclaim(&proj.target, proj.preservation, &proj.actual_drops)?;

        let target_iri = format!("{LOGIC_NS}target/{}", proj.target);
        g.add_iri(&report_iri, &logic("hasProjection"), &target_iri);
        g.add_iri(&target_iri, RDF_TYPE, &logic("ProjectionTarget"));
        g.add_lit(
            &target_iri,
            &format!("{RDFS_NS}label"),
            Literal::new_simple_literal(&proj.target),
        );
        g.add_iri(
            &target_iri,
            &logic("preservationKind"),
            &logic(proj.preservation.as_str()),
        );
        g.add_lit(
            &target_iri,
            &logic("complexityClass"),
            Literal::new_simple_literal(&proj.complexity),
        );

        let lossy_drop = format!("{GMEOW_NS}lossyDrop");
        let mut structural = proj.lossy_drops.clone();
        structural.sort();
        for note in &structural {
            g.add_lit(&target_iri, &lossy_drop, Literal::new_simple_literal(note));
        }
        let mut actual = proj.actual_drops.clone();
        actual.sort();
        for a in &actual {
            g.add_lit(
                &target_iri,
                &lossy_drop,
                Literal::new_simple_literal(format!("actual: {a}")),
            );
        }
    }

    let banner = "# GENERATED by `gmeow logic compile` — DO NOT EDIT.\n\
                  # Preservation loss ledger for all logic: projections.\n";
    Ok(g.serialize(banner))
}
