// SPDX-FileCopyrightText: 2026 Blackcat Informatics® Inc. <paudley@blackcatinformatics.ca>
// SPDX-License-Identifier: AGPL-3.0-only

//! Byte-identical text projection back-ends: Datalog, N3, Nemo `.rls`.
//!
//! These are compared **byte-for-byte** against the conformance goldens, so every
//! separator, quote style, and sort order reproduces `logic_projections.py`
//! exactly.

use super::super::ir::{LogicModality, LogicProgram, LogicRule};
use super::{
    is_modal_or_scoped, python_repr, target_meta, ProjectionResult, GMEOW_NS, LOGIC_NS, OWL_NS,
    RDFS_NS, RDF_NS, RDF_TYPE,
};

/// Extract a safe Datalog predicate name from an IRI (port of `_local`).
fn datalog_local(iri: &str) -> String {
    for ns in [LOGIC_NS, GMEOW_NS, RDF_NS, OWL_NS, RDFS_NS] {
        if let Some(raw) = iri.strip_prefix(ns) {
            return raw.replace(['-', '.', '#'], "_");
        }
    }
    // Fall back to the last path segment, then the last `#` segment.
    let after_slash = iri.rsplit('/').next().unwrap_or(iri);
    after_slash
        .rsplit('#')
        .next()
        .unwrap_or(after_slash)
        .to_owned()
}

/// Datalog term token for a subject/object (port of `_dl_term`).
fn dl_term(value: &str, is_literal: bool) -> String {
    if value.starts_with('?') {
        value.to_owned()
    } else if is_literal {
        python_repr(value)
    } else {
        format!("\"{value}\"")
    }
}

/// The context string for a ground axiom fact (modality value or `"default"`).
fn ctx_str(axiom: &super::super::ir::LogicAxiom) -> String {
    if is_modal_or_scoped(axiom) && axiom.scope.modality != LogicModality::None {
        axiom.scope.modality.as_str().to_owned()
    } else {
        "default".to_owned()
    }
}

/// A fresh world variable not colliding with the rule's logical variables
/// (`base` is `"?C"` for Datalog, `"?W"` for Nemo).
fn fresh_world_var(rule: &LogicRule, base: &str) -> String {
    let mut rule_vars: std::collections::HashSet<&str> = std::collections::HashSet::new();
    if rule.head.subject.starts_with('?') {
        rule_vars.insert(&rule.head.subject);
    }
    if rule.head.obj.starts_with('?') {
        rule_vars.insert(&rule.head.obj);
    }
    for ba in &rule.body {
        if ba.subject.starts_with('?') {
            rule_vars.insert(&ba.subject);
        }
        if ba.obj.starts_with('?') {
            rule_vars.insert(&ba.obj);
        }
    }
    let mut world = base.to_owned();
    let mut suffix = 0;
    while rule_vars.contains(world.as_str()) {
        suffix += 1;
        world = format!("{base}{suffix}");
    }
    world
}

// --------------------------------------------------------------------------- //
// Datalog
// --------------------------------------------------------------------------- //

/// Project to Datalog text (`generated/datalog/gmeow.dl`).
pub fn project_datalog(program: &LogicProgram) -> ProjectionResult {
    let (kind, cx, drops) = target_meta("datalog");
    let mut lines: Vec<String> = vec![
        "% GENERATED by `gmeow logic compile` — DO NOT EDIT.".to_owned(),
        "% Datalog projection of the canonical logic: program.".to_owned(),
        String::new(),
        "% === Ground facts (axioms) ===".to_owned(),
    ];
    for axiom in &program.axioms {
        let pred = if axiom.predicate == RDF_TYPE {
            "type".to_owned()
        } else {
            datalog_local(&axiom.predicate)
        };
        let obj = dl_term(&axiom.obj, axiom.obj_is_literal);
        let subj = dl_term(&axiom.subject, false);
        lines.push(format!("{pred}({subj}, {obj}, \"{}\").", ctx_str(axiom)));
    }

    lines.push(String::new());
    lines.push("% === Rules ===".to_owned());
    for rule in &program.rules {
        let head = &rule.head;
        let head_pred = if head.predicate == RDF_TYPE {
            "type".to_owned()
        } else {
            datalog_local(&head.predicate)
        };
        let head_subj = dl_term(&head.subject, false);
        let head_obj = dl_term(&head.obj, head.obj_is_literal);
        let world = fresh_world_var(rule, "?C");

        let mut body_parts: Vec<String> = Vec::new();
        for ba in &rule.body {
            let bp = if ba.predicate == RDF_TYPE {
                "type".to_owned()
            } else {
                datalog_local(&ba.predicate)
            };
            let bs = dl_term(&ba.subject, false);
            let bo = dl_term(&ba.obj, ba.obj_is_literal);
            let prefix = if ba.negated { "not " } else { "" };
            body_parts.push(format!("{prefix}{bp}({bs}, {bo}, {world})"));
        }
        for (a, b) in &rule.distinct_pairs {
            body_parts.push(format!("{a} != {b}"));
        }
        let body_str = if body_parts.is_empty() {
            "true".to_owned()
        } else {
            body_parts.join(",\n    ")
        };
        lines.push(format!("{head_pred}({head_subj}, {head_obj}, {world}) :-"));
        lines.push(format!("    {body_str}."));
    }

    let content = format!("{}\n", lines.join("\n"));
    ProjectionResult {
        target: "datalog".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        lossy_drops: drops.into_iter().map(str::to_owned).collect(),
        actual_drops: Vec::new(),
    }
}

// --------------------------------------------------------------------------- //
// N3
// --------------------------------------------------------------------------- //

/// N3 term token (port of `_n3_term`).
fn n3_term(value: &str, is_literal: bool) -> String {
    if value.starts_with('?') {
        value.to_owned()
    } else if is_literal {
        python_repr(value)
    } else {
        format!("<{value}>")
    }
}

/// Project to N3 rules (`generated/n3/gmeow.n3`).
pub fn project_n3(program: &LogicProgram) -> ProjectionResult {
    let (kind, cx, drops) = target_meta("n3");
    let mut lines: Vec<String> = vec![
        format!("@prefix logic: <{LOGIC_NS}> ."),
        format!("@prefix gmeow: <{GMEOW_NS}> ."),
        "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .".to_owned(),
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .".to_owned(),
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .".to_owned(),
        "@prefix log: <http://www.w3.org/2000/10/swap/log#> .".to_owned(),
        String::new(),
        "# GENERATED by `gmeow logic compile` — DO NOT EDIT.".to_owned(),
        "# N3 projection of the canonical logic: program.".to_owned(),
        String::new(),
        "# === Axioms ===".to_owned(),
    ];

    for axiom in &program.axioms {
        let subj_n3 = format!("<{}>", axiom.subject);
        let pred_n3 = if axiom.predicate == RDF_TYPE {
            "a".to_owned()
        } else {
            format!("<{}>", axiom.predicate)
        };
        let obj_n3 = if axiom.obj_is_literal {
            python_repr(&axiom.obj)
        } else {
            format!("<{}>", axiom.obj)
        };

        if is_modal_or_scoped(axiom) {
            let modal = axiom.scope.modality.as_str();
            lines.push(format!("# modal context: {modal}"));
            lines.push(format!(
                "{{ {subj_n3} {pred_n3} {obj_n3} }} log:implies \
                 {{ {subj_n3} <{LOGIC_NS}holds> {obj_n3} }} ."
            ));
        } else {
            lines.push(format!("{subj_n3} {pred_n3} {obj_n3} ."));
        }
    }

    lines.push(String::new());
    lines.push("# === Rules ===".to_owned());
    for rule in &program.rules {
        let head = &rule.head;
        let head_subj = n3_term(&head.subject, false);
        let head_pred = if head.predicate == RDF_TYPE {
            "a".to_owned()
        } else {
            format!("<{}>", head.predicate)
        };
        let head_obj = n3_term(&head.obj, head.obj_is_literal);

        let mut body_parts: Vec<String> = Vec::new();
        for b in &rule.body {
            let bs = n3_term(&b.subject, false);
            let bp = if b.predicate == RDF_TYPE {
                "a".to_owned()
            } else {
                format!("<{}>", b.predicate)
            };
            let bo = n3_term(&b.obj, b.obj_is_literal);
            body_parts.push(format!("{bs} {bp} {bo}"));
        }
        for (a, b) in &rule.distinct_pairs {
            body_parts.push(format!("{a} log:notEqualTo {b}"));
        }
        let body_str = if body_parts.is_empty() {
            "true .".to_owned()
        } else {
            format!("{} .", body_parts.join(" . "))
        };
        lines.push(format!(
            "{{ {body_str} }} log:implies {{ {head_subj} {head_pred} {head_obj} . }} ."
        ));
    }

    let content = format!("{}\n", lines.join("\n"));
    ProjectionResult {
        target: "n3".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        lossy_drops: drops.into_iter().map(str::to_owned).collect(),
        actual_drops: Vec::new(),
    }
}

// --------------------------------------------------------------------------- //
// Nemo
// --------------------------------------------------------------------------- //

fn nemo_iri(iri: &str) -> String {
    format!("<{iri}>")
}

fn nemo_literal(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Project to Nemo `.rls` rule source (`generated/logic/gmeow.rls`).
///
/// # Errors
///
/// Returns `Err` if a rule head contains a variable absent from every body atom
/// (a Nemo safety violation), mirroring the Python `ValueError`.
pub fn project_nemo(program: &LogicProgram) -> Result<ProjectionResult, String> {
    let (kind, cx, drops) = target_meta("nemo");
    let mut lines: Vec<String> = vec![
        "% GENERATED by `gmeow logic compile` — DO NOT EDIT.".to_owned(),
        "% Nemo (.rls) projection of the canonical logic: program.".to_owned(),
        String::new(),
        "% === Ground facts (axioms) ===".to_owned(),
    ];
    for axiom in &program.axioms {
        let pred = nemo_iri(&axiom.predicate);
        let subj = nemo_iri(&axiom.subject);
        let obj = if axiom.obj_is_literal {
            nemo_literal(&axiom.obj)
        } else {
            nemo_iri(&axiom.obj)
        };
        let ctx = if is_modal_or_scoped(axiom) && axiom.scope.modality != LogicModality::None {
            nemo_literal(axiom.scope.modality.as_str())
        } else {
            nemo_literal("default")
        };
        lines.push(format!("{pred}({subj}, {obj}, {ctx})."));
    }

    lines.push(String::new());
    lines.push("% === Rules ===".to_owned());
    for rule in &program.rules {
        let head = &rule.head;
        let head_pred = nemo_iri(&head.predicate);
        let head_subj = if head.subject.starts_with('?') {
            head.subject.clone()
        } else {
            nemo_iri(&head.subject)
        };
        let head_obj = if head.obj.starts_with('?') {
            head.obj.clone()
        } else if head.obj_is_literal {
            nemo_literal(&head.obj)
        } else {
            nemo_iri(&head.obj)
        };

        // Safety: every variable in the head, in a negated body atom, or in a
        // distinct_pairs guard must be bound by at least one POSITIVE (non-negated)
        // body atom.  Variables that appear ONLY in negated atoms or only in a !=
        // guard are unsafe and make Nemo fail or produce wrong results.
        let mut head_vars: Vec<&str> = Vec::new();
        if head.subject.starts_with('?') {
            head_vars.push(&head.subject);
        }
        if head.obj.starts_with('?') {
            head_vars.push(&head.obj);
        }
        let mut positive_body_vars: std::collections::HashSet<&str> =
            std::collections::HashSet::new();
        let mut negated_body_vars: std::collections::HashSet<&str> =
            std::collections::HashSet::new();
        for ba in &rule.body {
            if ba.negated {
                if ba.subject.starts_with('?') {
                    negated_body_vars.insert(&ba.subject);
                }
                if ba.obj.starts_with('?') {
                    negated_body_vars.insert(&ba.obj);
                }
            } else {
                if ba.subject.starts_with('?') {
                    positive_body_vars.insert(&ba.subject);
                }
                if ba.obj.starts_with('?') {
                    positive_body_vars.insert(&ba.obj);
                }
            }
        }
        let mut guard_vars: std::collections::HashSet<&str> = std::collections::HashSet::new();
        for (a, b) in &rule.distinct_pairs {
            if a.starts_with('?') {
                guard_vars.insert(a.as_str());
            }
            if b.starts_with('?') {
                guard_vars.insert(b.as_str());
            }
        }
        let required_vars: std::collections::HashSet<&str> = head_vars
            .iter()
            .copied()
            .chain(negated_body_vars.iter().copied())
            .chain(guard_vars.iter().copied())
            .collect();
        let mut unbound: Vec<&str> = required_vars
            .iter()
            .copied()
            .filter(|v| !positive_body_vars.contains(v))
            .collect();
        if !unbound.is_empty() {
            unbound.sort_unstable();
            return Err(format!(
                "Nemo safety violation: rule head variables {unbound:?} do not appear in \
                 any body atom. Head: {} {} {}",
                head.subject, head.predicate, head.obj
            ));
        }

        let world = fresh_world_var(rule, "?W");
        let mut body_parts: Vec<String> = Vec::new();
        for ba in &rule.body {
            let bp = nemo_iri(&ba.predicate);
            let bs = if ba.subject.starts_with('?') {
                ba.subject.clone()
            } else {
                nemo_iri(&ba.subject)
            };
            let bo = if ba.obj.starts_with('?') {
                ba.obj.clone()
            } else if ba.obj_is_literal {
                nemo_literal(&ba.obj)
            } else {
                nemo_iri(&ba.obj)
            };
            let prefix = if ba.negated { "~" } else { "" };
            body_parts.push(format!("{prefix}{bp}({bs}, {bo}, {world})"));
        }
        for (a, b) in &rule.distinct_pairs {
            body_parts.push(format!("{a} != {b}"));
        }

        let rule_name_iri = rule
            .scope
            .provenance
            .clone()
            .unwrap_or_else(|| format!("{LOGIC_NS}rule/anonymous"));
        let rule_name_escaped = rule_name_iri.replace('\\', "\\\\").replace('"', "\\\"");
        lines.push(format!("#[name(\"{rule_name_escaped}\")]"));

        if body_parts.is_empty() {
            lines.push(format!(
                "{head_pred}({head_subj}, {head_obj}, \"default\")."
            ));
        } else {
            let body_str = body_parts.join(",\n    ");
            lines.push(format!("{head_pred}({head_subj}, {head_obj}, {world}) :-"));
            lines.push(format!("    {body_str} ."));
        }
    }

    let content = format!("{}\n", lines.join("\n"));
    Ok(ProjectionResult {
        target: "nemo".to_owned(),
        content,
        is_rdf: false,
        preservation: kind,
        complexity: cx.to_owned(),
        lossy_drops: drops.into_iter().map(str::to_owned).collect(),
        actual_drops: Vec::new(),
    })
}

/// Extract the `% === Rules ===` section of a `.rls` string (port of
/// `extract_nemo_rules_section`).
///
/// # Errors
///
/// Returns `Err` if the rules marker is absent (corrupt projection output).
pub fn extract_nemo_rules_section(nemo_content: &str) -> Result<String, String> {
    const MARKER: &str = "% === Rules ===";
    match nemo_content.find(MARKER) {
        Some(idx) => Ok(nemo_content[idx + MARKER.len()..].trim().to_owned()),
        None => Err(
            "Nemo projection is missing the \"% === Rules ===\" marker; cannot extract \
             certifier input safely."
                .to_owned(),
        ),
    }
}
